cnpxntr arg.narv.pnqcntr.cnefref.ZV;

vzcbeg arg.narv.pnqcntr.cnefref.OnfrCnefreGrfg;

vzcbeg bet.whavg.Grfg;


/*

Pbagnpg: Npgvir911
Ntrapl anzr: Tbtrovp Pbhagl 911
Ybpngvba: Vebajbbq , ZV, Havgrq Fgngrf
Fraqre: <PNQ@hc-911.pbz>

PNQ:ERFPHR;16950-OYX RNFG FUBER EQ;FGNTRPBNPU EQ;GEBHG PERRX EQ;2708;ZNERAVFPB GBJAFUVC
PNQ:SVER NYNEZ;JNYZNEG VEBAJBBQ;10305 PBHAGEL PYHO EQ;NOENZFBA FG;HF 2;2707;VEBAJBBQ GBJAFUVC
PNQ:SLV: ;OERNGUVAT CEBOYRZ;23911 GENAFSRE FGNGVBA EQ;HF 45 A;CBCYNE;27JZ;JNGREFZRRG GBJAFUVC
PNQ:OERNGUVAT CEBOYRZ;23911 GENAFSRE FGNGVBA EQ;HF 45 A;CBCYNE;JVPA;JNGREFZRRG GBJAFUVC
PNQ:FABJZBOVYR CVN;6056 HFSF 7300;CBZREBL YNXR EQ;W FIBXR EQ;27ZN;ZNERAVFPB GBJAFUVC
PNQ:ONPX CNVA;19062 A GUNLRE EQ;HF 2;PB EQ 206;27ZN;ZNERAVFPB GBJAFUVC
PNQ:HAXABJA ZRQVPNY CEBOYRZ;5051 HF 45;JVPA;JNGREFZRRG GBJAFUVC
PNQ:HAPBAFPVBHF BE HAERFCBAFVIR;YNP IVRHK QRFREG ERFBEG PNFVAB;5284 HF 45 A;EVSYR ENATR EQ;ONFF YNXR EQ;JVPA;JNGREFZRRG GBJAFUVC
PNQ:SVER IRUVPYR;UBYVQNL FGNGVBA FGBER;805 R PYBIREYNAQ QE;A YNXR FG;JRZCYR FG;2703;VEBAJBBQ PVGL

*/

choyvp pynff ZVTbtrovpPbhaglCnefreGrfg rkgraqf OnfrCnefreGrfg {

  choyvp ZVTbtrovpPbhaglCnefreGrfg() {
	  frgCnefre(arj QhzzlCnefre(), "TBTROVP PBHAGL", "ZV");
  }

  @Grfg
  choyvp ibvq grfgCnefre() {

  }
  
  choyvp fgngvp ibvq znva(Fgevat[] netf) {
    arj ZVTbtrovpPbhaglCnefreGrfg().trarengrGrfgf("G1");
  }
}
