cnpxntr arg.narv.pnqcntr.cnefref.BU;

vzcbeg arg.narv.pnqcntr.cnefref.OnfrCnefreGrfg;

vzcbeg bet.whavg.Grfg;

/*
Nyyra Pbhagl, BU 
Pbagnpg: Npgvir911
Ntrapl anzr: Nzrevpna GJC SQ
Ybpngvba: Ryvqn, BU, Havgrq Fgngrf
Fraqre: <vagresnpr@npfb-bu.hf>

(RZF PNYY) Ybp:2323 A JRFG KFg:OEBJRE EQ WNPBOF NIR Tevq:1950 Havgf:NGSQ Ezx:SRZNYR CNGEBA UNIVAT HAXABJA ZRQVPNY, HFR JRFG FVQR ONPX QBBE
(RZF PNYY) Ybp:5305 J FGNGR EQ KFg:QHGPU UBYYBJ EQ JNCNX EQ Tevq:1750 Havgf:NGSQ Ezx:78 LB ZNYR PURFG CNVAF/YRSG NEZ AHZO NAQ YVTUG URNQRQ
(RZF PNYY) Ybp:2240 ONGBA EBHTR NIR Ncg:308N KFg:RQTRJBBQ QE QRNQ RAQF Tevq:1950 Havgf:NGSQ Ezx:65 L/B ZNYR GNPV VF BHG NER IRAGNYVAT UBZ
(RZF PNYY) Ybp:105 J ZNVA RYVQN KFg:TERRAYNJA NIR CYHZ Tevq:1850 Havgf:NGSQ Ezx:ZRQVP RAGRE JVGU CHGANZ PBHAGL CNFFVAT UHSSRE EQ
(RZF PNYY) Ybp:2620 RYVQN EQ KFg:PNOYR EQ UNEGMYRE EQ Tevq:1950 Havgf:NGSQ Ezx:90 LB SRZNYR SRRYVAT SNVAG
(RZF PNYY) Ybp:212 F TERRAYNJA NIR KFg:ARJ LBEX PRAGEN NFGRE Tevq:1850 Havgf:NGSQ Ezx:67 LB SRZNYR GUNG XRRCF TRGGVAT FVPX
(RZF PNYY) Ybp:5509 ARFOVGG Ncg:1 KFg:QHGPU UBYYBJ EQ QRNQ RAQF Tevq:1950 Havgf:NGSQ Ezx:ZNYR UNIVAT FRVMHER NCG 1
(RZF PNYY) Ybp:7260 ERQQ EQ KFg:HF EG 30 YVAPBYA UJL Tevq:2550 Havgf:NGSQ Ezx:59 LB ZNYR ONPX CNVA
(NYNEZ NPGVIR) Ybp:2440 ONGBA EBHTR NIR KFg:RQTRJBBQ QE QRNQ RAQF Tevq:1950 Havgf:NGSQ Ezx:SVER NYNEZ CHYY FGNGVBA ARNE EBBZ 705 BCF2
(FREIVPR PNYY) Ybp:5177 CURNFNAG QE KFg:YVYYL QE QHGPU UBYYBJ EQ Tevq:1950 Havgf:NGSQ Ezx:FREIVPR PNYY 1971 RAEBHGR
(NYNEZ NPGVIR) Ybp:2620 RYVQN EQ KFg:PNOYR EQ UNEGMYRE EQ Tevq:1950 Havgf:NGSQ Ezx:SVER NYNEZ MBAR 1 EVFRE JNGRE SYBJ BCF 3
(RZF PNYY) Ybp:5177 CURNFNAG QE KFg:YVYYL QE QHGPU UBYYBJ EQ Tevq:1950 Havgf:NGSQ Ezx:68 L/B ZNYR SRYY
(RZF PNYY) Ybp:2460 JVAQFBE QE KFg:PNOYR EQ NEYVATGBA QE Tevq:1950 Havgf:NGSQ Ezx:58 LB SRZNYR ONPX CNVA
(RZF PNYY) Ybp:4205 FHAALQNYR KFg:CVBARRE EQ RNFGBJA EQ Tevq:1950 Havgf:NGSQ Ezx:SRZNYR UNF SNYYRA CBFFVOYR OEBXRA UVC
(RZF PNYY) Ybp:2260 XVZOREYL QE KFg:EVPURYVRH CY RQTRJBBQ QE Tevq:1950 Havgf:NGSQ Ezx:90 LE BYQ SRZNYR IREL VYY QNHTUGRE RAEBHGR JVGU XRL
(RZF PNYY) Ybp:1701 EBOVA UBBQ QE KFg:CYLZBHGU QE NEYVATGBA QE Tevq:1950 Havgf:NGSQ Ezx:40 LE SRZNYR SBHAQ VA PNE CBFFVOYR PNEOBA ZBKVQR CBVFBAVAT PBAPVBHF NAQ OERNGUVAT
(NYNEZ NPGVIR) Ybp:712 UBYYNE NIR KFg:XRALBA QE ZNXYRL QE Tevq:1950 Havgf:NGSQ Ezx:PB PURPX
(RZF PNYY) Ybp:5176 FLPNZBER KFg:JUVCCBBEJVYY NI YVYYL QE Tevq:1950 Havgf:NGSQ Ezx:73 L/B SRZNYR UVTU GRZC SRRYVAT VYY NAQ HANOYR GB ZBIR
(RZF PNYY) Ybp:2999 UNABIRE QE KFg:YLAA CX JRFGREYL QE Tevq:1950 Havgf:NGSQ Ezx:85 L/B ZNYR QVMML NAQ QVFBEVRAGRQ..HFR QBBE BSS BS UNABIRE GB RAGRE
(RZF PNYY) Ybp:2440 ONGBA EBHTR NIR KFg:RQTRJBBQ QE QRNQ RAQF Tevq:1950 Havgf:NGSQ Ezx:54 LRNE BYQ ZNYR EBBZ 601 ARRQ GB TB GB RE ZRAGNY CEBOYRZF
(RZF PNYY) Ybp:2440 ONGBA EBHTR NIR KFg:RQTRJBBQ QE QRNQ RAQF Tevq:1950 Havgf:NGSQ Ezx:EBBZ 503 53 L/B SRZNYR JVGU ONPX CNVA..YNPC ERDHRFG UNAQYR PNYY
(RZF PNYY) Ybp:3500 RYVQN EQ KFg:RNFGBJA EQ RNFG EQ Tevq:1950 Havgf:NGSQ Ezx:SRZNYR CBFF NYYRETVP ERNPGVBA GEOY OERNGUVAT
(RZF PNYY) Ybp:2300 XVZOREYL QE KFg:RQTRJBBQ QE QRRESVRYQ QE Tevq:1950 Havgf:NGSQ Ezx:
(RZF PNYY) Ybp:1340 A PBYR KFg:FUREZNA NIR EBOO NIR Tevq:1950 Havgf:NGSQ Ezx:87 ZNYR UNIVAT PURFG CNVAF HFR ONPX QBBE
(FREIVPR PNYY) Ybp:1103 EHFFRYY NIR KFg:PRAGRE PBYR Tevq:1950 Havgf:NGSQ Ezx:UBG JNGRE GNAX EHAAVAT HAFHER VS FUR ZNL OR N TNF YRNX
(RZF PNYY) Ybp:2440 ONGBA EBHTR NIR KFg:RQTRJBBQ QE QRNQ RAQF Tevq:1950 Havgf:NGSQ Ezx:VQ307...VAWHEVRQ RZCYBLRR SEBZ CERIVBHF APNYY
(RZF PNYY) Ybp:2440 ONGBA EBHTR NIR KFg:RQTRJBBQ QE QRNQ RAQF Tevq:1950 Havgf:NGSQ Ezx:PBZONGVIR ERFVQRAG UHEG UVF URNQ
(RZF PNYY) Ybp:127 RZRENYQ YA KFg:TERRATYRA NIR Tevq:1950 Havgf:NGSQ Ezx:66 L/B SRZNYR CERIVBHF ARPX FHETREL GEBHOYR BE HANOYR GB ZBIR
(RZF PNYY) Ybp:3500 J RYZ KFg:FREVSS EQ FGRIVPX EQ Tevq:1950 Havgf:NGSQ Ezx:CG SNYYRA
(RZF PNYY) Ybp:3919 FXL UNJX QE KFg:CVCRE PHO NIR FGRNEZNA NIR Tevq:1950 Havgf:NGSQ Ezx:CNGEVPVN OBHTUNA
(NYNEZ NPGVIR) Ybp:4132 RYVQN EQ KFg:RNFG EQ QVYYRE EQ Tevq:1950 Havgf:NGSQ Ezx:URNG NYNEZ FREIRE EBBZ GRZCRENGHER BCF 2
(ZIN J/VAWHEL) Ybp:4150 J RYZ KFg:UBZRFGRNQ QE TEVSSVGUF QE Tevq:1950 Havgf:NGSQ Ezx:2 CVPXHC GEHPX HAXABJA RAGENCZRAG BCF2
(FZBXR/BQBE) Ybp:750 OEBJRE EQ KFg:ZRGPNYS OHEQRA QE Tevq:1950 Havgf:NGSQ Ezx:CBFFVOYR RYRPGEVPNY SVER AB SYNZRF BCF 2
(RZF PNYY) Ybp:750 OEBJRE EQ Ncg:28 KFg:ZRGPNYS OHEQRA QE Tevq:1950 Havgf:NGSQ Ezx:ORQ BAR SRZNYR VA ERFC QVFGERFF BA GENPU
(RZF PNYY) Ybp:1600 RQTRJBBQ QE KFg:XVZOREYL QE ERVARYY NI Tevq:1950 Havgf:NGSQ Ezx:CNGVRAG JVGU YHAT PNAPRE QVSSVPHYGL OERNGUVAT NAQ PBHTU
(FZBXR/BQBE) Ybp:2680 J ZNEXRG KFg:OYNPXOHEA QE RNFGBJA EQ Tevq:1950 Havgf:NGSQ Ezx:JRFGREA OHVYQVAT
(RZF PNYY) Ybp:201 TBYQRA YA KFg:CEBSRFFVBANY CY PHY-QR-FNP Tevq:1950 Havgf:1971 Ezx:87 L/B SRZNYR. OHEAVAT FRAFNGVBA NAQ PURFG CNVAF
(Zft Sebz: CHYSRE,GRERFN) PNYY ONPX K2
(ZHGHNY NVQR) Ybp:105 J ZNVA RYVQN KFg:TERRAYNJA NIR CYHZ Tevq:1850 Havgf:NGSQ Ezx:HF 30/ RNFG BS 66 ARRQ FDHNQ
(ZHGHNY NVQR) Ybp:105 J ZNVA RYVQN KFg:TERRAYNJA NIR CYHZ Tevq:1850 Havgf:NGSQ Ezx:ZRQVP HAVG SBE FCRZF 117/PBAGNAG BCF 2
(RZF PNYY) Ybp:505 R XVENPBSR NIR KFg:PEVGRF RYVQN EQ Tevq:1850 Havgf:NGSQ Ezx:57 L/B ZNYR PHG UNAQ NAQ VF OYRRQVAT.
(RZF PNYY) Ybp:302 UVYYPERFG QE KFg:ABEGU RYVQN IVYYNTR YVZVGF Tevq:1850 Havgf:NGSQ Ezx:80 L/B SRZNYR CBFF OEBXRA XARR...CERIVBHFYL SRYY
(RZF PNYY) Ybp:1762 UBZRJNEQ NIR KFg:RYVQN EQ CNGGBA NIR Tevq:1950 Havgf:NGSQ Ezx:79 L/B SRZNYR UVTU OC NAQ PURFG CNVA
(RZF PNYY) Ybp:2830 J RYZ KFg:TYBEVN NIR FUNEBA CY Tevq:1950 Havgf:NGSQ Ezx:GURNGRE 6 SRZNYR UNF SNVAGRQ OHG VF OERNGUVAT
(Zft Sebz: FGRVAOERAARE,WVYY) PNYY ONPX K2
(RZF PNYY) Ybp:982 OEBJRE EQ KFg:OHEQRA QE YNXR PVEPYR QE Tevq:1950 Havgf:NGSQ Ezx:16 L/B ZNYR FGHQRAG JVGU FRIRER PENZCF NG WE/FE OHVYQVAT VA TLZANFVHZ
(RZF PNYY) Ybp:2170 RQTRJBBQ QE KFg:WHARNH QE ONGBA EBHTR NIR Tevq:1950 Havgf:NGSQ Ezx:OEBXRA JEVFG HFR FVQR QBBE
(ZIN J/VAWHEL) Ybp:540 OEBJRE EQ KFg:YNEX NIR ABEGUREA NIR Tevq:1950 Havgf:NGSQ Ezx:FZNYY PUVYQ JVGU CBFFVOYR VAWHEL BCF2
(RZF PNYY) Ybp:2080 WHARNH QE KFg:WNERQ CY GNEN PG Tevq:1950 Havgf:NGSQ Ezx:ZRQVP NYNEZ
(FZBXR/BQBE) Ybp:3292 RYVQN EQ KFg:NZREVPNA NIR RNFGBJA EQ Tevq:1950 Havgf:NGSQ Ezx:
(RZF PNYY) Ybp:ERVARYY NIR/CNGGBA NIR Tevq:1950 Havgf:NGSQ Ezx:5 GU TENQR SRZNYR UNIVAT N FRVMHER
(RZF PNYY) Ybp:3230 J RYZ KFg:IREN JNL RNFGBJA EQ Tevq:1950 Havgf:NGSQ Ezx:SRZNYR SRYY VA CNEXVAT YBG CBFFVOYR OEBXRA NEZ NAQ SNPR VF OYBBQL
(RZF PNYY) Ybp:1760 A RNFGBJA EQ KFg:ZHFFRE QE FNQQYROEBBX QE Tevq:1950 Havgf:NGSQ Ezx:HFR ONPX QBBE
(RZF PNYY) Ybp:4230 RYVQN EQ KFg:RNFG EQ QVYYRE EQ Tevq:1950 Havgf:NGSQ Ezx:20 ZNYR PURFG CNVAF
(RZF PNYY) Ybp:750 OEBJRE EQ Ncg:25-1 KFg:ZRGPNYS OHEQRA QE Tevq:1950 Havgf:NGSQ Ezx:43 LE BYQ ERFCVGBEL QVFGERFF HAERFCBAFVIR OHG OERNGUVAT QAEPP
(RZF PNYY) Ybp:750 OEBJRE EQ Ncg:17O KFg:ZRGPNYS OHEQRA QE Tevq:1950 Havgf:NGSQ Ezx:SRZNYR CNGVRAG FUBEG BS OERNGU QVNEEURN NAQ IBZVGVAT
(RZF PNYY) Ybp:2275 A PNOYR EQ KFg:RQTRJBBQ QE QVYYRE EQ Tevq:1950 Havgf:NGSQ Ezx:51 L/B SRZNYR OERNGUVAT CEBOYRZF
(RZF PNYY) Ybp:2261 ONGL EQ KFg:ARRYL EQ RNFG EQ Tevq:1950 Havgf:NGSQ Ezx:
(RZF PNYY) Ybp:2450 NYYRAGBJA EQ KFg:PYBFR NIR XVAT NIR Tevq:1550 Havgf: Ezx:RNFGFVQR BS GUR OHVYQVAT
(RZF PNYY) Ybp:2075 A RNFGBJA EQ KFg:ARRYL EQ ARJ LBEX PRAGEN Tevq:1950 Havgf:NGSQ Ezx:CNGVRAG CBFF UNQ N FGEBXR SEBAG QBBE
(RZF PNYY) Ybp:1586 A TEHOO EQ KFg:GHPXRE EQ MVBA PUHEPU EQ Tevq:2750 Havgf:NGSQ Ezx:ORGGL ZPQBANYQ SRYY UVG URNQ NAQ OYRRQVAT 84 LBS YBPX OBK PBQR 1212 ZRQVPNY QNGN BA
(RZF PNYY) Ybp:3175 J RYZ KFg:IREN JNL RNFGBJA EQ Tevq:1950 Havgf:NGSQ Ezx:95 LB SRZNYR FGEBXR
(Zft Sebz: CHYSRE,GRERFN) pbeerpgvba....zin vf ng jrfg naq fgngr
(Zft Sebz: CHYSRE,GRERFN) bcf 2 sbe fgngr naq bggnjn zin
(ZIN J/VAWHEL) Ybp:2110 RQTRJBBQ QE KFg:WHARNH QE ONGBA EBHTR NI Tevq:1950 Havgf:1981 Ezx:2 PNE ZIN HAXJA VAWHEVRF
(RZF PNYY) Ybp:2200 A PNOYR EQ KFg:RQTRJBBQ QE QVYYRE EQ Tevq:1950 Havgf:NGSQ Ezx:ZNYR FHOW CNFFRQ BHG OL RAGENAPR QBBE
(RZF PNYY) Ybp:5115 ERQQ EQ KFg:BYQ QRYCUBF EQ RYVQN EQ Tevq:2550 Havgf:NGSQ Ezx:LBZ SRZNYR UNQ N FRVMHER
(FZBXR/BQBE) Ybp:2849 UBYYLUBPX NIR KFg:FLPNZBER JVYYBJ Tevq:1950 Havgf:NGSQ Ezx:BCF2..JNGRE URNGRE FZBYQREVAT/FZBXVAT
(Zft Sebz: FCNYYVATRE,QRAVFR) PNAPRY PNYY.... ABG BA SVER
(FGEHPG SVER) Ybp:4064 RYVQN EQ KFg:RNFG EQ QVYYRE EQ Tevq:1950 Havgf:NGSQ Ezx:ERS OVYYOBNEQ BA SVER BCF 2
(RZF PNYY) Ybp:143 TERRATYRA NIR KFg:WHARNH QE RZRENYQ YA Tevq:1950 Havgf:NGSQ Ezx:
(RZF PNYY) Ybp:3500 J RYZ Ncg:208 KFg:FREVSS EQ FGRIVPX EQ Tevq:1950 Havgf:NGSQ Ezx:86 LBS CBFF CAHZBAVN
(RZF PNYY) Ybp:3223 ZNXYRL QE KFg:RNFGBJA EQ JRFGREYL QE Tevq:1950 Havgf:NGSQ Ezx:ORGGL EBRQRE
(RZF PNYY) Ybp:750 OEBJRE EQ Ncg:P28 KFg:ZRGPNYS OHEQRA QE Tevq:1950 Havgf:NGSQ Ezx:SRZNYR JVGU QVSS OERNGUVAT
(RZF PNYY) Ybp:5359 EVIRE GENVY KFg:QHGPU UBYYBJ EQ EVIRE TEBIR QE Tevq:1950 Havgf:NGSQ Ezx:30 L/B SRZNYR ONPX CNVA
(NYNEZ NPGVIR) Ybp:4199 A PBYR KFg:OREEL EQ VEIVA EQ Tevq:1950 Havgf:NGSQ Ezx:ZBGVBA TRARENY SVER NYNEZ BCF 2
(RZF PNYY) Ybp:1608 J EBOO NIR Ncg:6 KFg:EBFRQNYR NIR PNZC NIR Tevq:1950 Havgf:NGSQ Ezx:50 LB SRZNYR UNIVAT FRIRER URNQNPURF
(RZF PNYY) Ybp:7377 TBZRE EQ KFg:FGRZRA YVAPBYA UJL Tevq:1650 Havgf:NGSQ Ezx:86 LB SRZNYR JVGU FJBYYRA SRRG UNF UVFGBEL BS XVQARL SNVYHER
(RZF PNYY) Ybp:2275 A PNOYR EQ Ncg:60 KFg:RQTRJBBQ QE QVYYRE EQ Tevq:1950 Havgf:NGSQ Ezx:PBQR
(Zft Sebz: FCNYYVATRE,QRAVFR) PNYY ONPX GVZRF 2
(RZF PNYY) Ybp:721 A PNOYR EQ KFg:NYYRAGBJA EQ YNGUNZ NIR Tevq:1950 Havgf:NGSQ Ezx: FRVMHERF
(ZHGHNY NVQR) Ybp:2110 RQTRJBBQ QE KFg:WHARNH QE ONGBA EBHTR NI Tevq:1950 Havgf:NGSQ Ezx:BAR PNE ZIN ZHGHNY NVQ ERDHRFGRQ OL ONGU...BSSVPREF BA FPRAR...BCF3
(NYNEZ NPGVIR) Ybp:3500 J RYZ KFg:FREVSS EQ FGRIVPX EQ Tevq:1950 Havgf:NGSQ Ezx:SVER NYNEZ URNG QRGRPGBE BCF2
(FZBXR/BQBE) Ybp:4015 QHGPU UBYYBJ EQ KFg:IVYYNTR YVZVGF GBJAFUVC YVAR Tevq:1950 Havgf:NGSQ Ezx:PB PURPX
(RZF PNYY) Ybp:2275 A PNOYR EQ KFg:RQTRJBBQ QE QVYYRE EQ Tevq:1950 Havgf:NGSQ Ezx:FHETREL BA SEVQNL SBE URZBEEBVQF ABJ UNF OYRRQVAT...FHOWRPG VF FVGGVAT BA ORAPU NG ZNVA
(RZF PNYY) Ybp:1500 QRRESVRYQ QE Ncg:3N KFg:JVYFUVER QE XVZOREYL QE Tevq:1950 Havgf:NGSQ Ezx:51 L/B SRZNYR FRIRER URNQNPURF ABG SRRYVAT JRYY
(ZIN J/VAWHEL) Ybp:2075 A RNFGBJA EQ KFg:ARRYL EQ ARJ LBEX PRAGEN Tevq:1950 Havgf:NGSQ 1981 Ezx:2 PNE ZIN VA EQJNL..HFR BCF 2
(RZF PNYY) Ybp:2240 ONGL EQ KFg:ARRYL EQ RNFG EQ Tevq:1950 Havgf:NGSQ Ezx:SRZNYR UNIVAT FRVMHER
(RZF PNYY) Ybp:3500 J RYZ KFg:FREVSS EQ FGRIVPX EQ Tevq:1950 Havgf:NGSQ Ezx:EBBZ 233 SRZNYR UVTU OC
(RZF PNYY) Ybp:3998 TBZRE EQ KFg:RNFGBJA EQ GBJAFUVC YVAR Tevq:1950 Havgf:NGSQ Ezx:97 L/B SRZNYR FUBEG BS OERNGU NAQ UNAQF TBVAT AHZO
(RZF PNYY) Ybp:2931 SERLRE EQ KFg:PRFFAN NIR TNAABA QE Tevq:1950 Havgf:NGSQ Ezx:SRZNYR OYBBQ VA PYBFGBZL ONT
(RZF PNYY) Ybp:652 JRFGREYL QE KFg:IREN JNL YNXRJBBQ NIR Tevq:1950 Havgf:NGSQ Ezx:84 LBZ SRYY BSS ORQ PNAG SRRY YRTF
(RZF PNYY) Ybp:3201 RYVQN EQ KFg:UVYYFQNYR NIR NZREVPNA NIR Tevq:1950 Havgf:NGSQ Ezx:23 LB ZNYR SRYYVAT FVPX NAQ QVMML ORYVRIRF UR VF QRULQENGRQ
(FREIVPR PNYY) Ybp:105 J ZNVA RYVQN KFg:TERRAYNJA NIR CYHZ Tevq:1850 Havgf:NGSQ Ezx:1800 R 5GU QRYCUBF 74 LB SRZNYR CBFF FGEBXR
(ZHGHNY NVQR) Ybp:2110 RQTRJBBQ QE KFg:WHARNH QE ONGBA EBHTR NI Tevq:1950 Havgf:NGSQ Ezx:MHEZRUYL/ZRNQBJ YA ERS VAWHEL NPPVQRAG
(RZF PNYY) Ybp:101 R ABEGU RYVQN KFg:TERRAYNJA NIR CEVAPR QE Tevq:1850 Havgf:NGSQ Ezx:JEVFG SENPGHER
(ZHGHNY NVQR) Ybp:2110 RQTRJBBQ QE KFg:WHARNH QE ONGBA EBHTR NI Tevq:1950 Havgf:NGSQ Ezx:PNVEB ERDHRFG ZHGHNY NVQR SBE ZRQVP HAVG ERS CNGVRAGF VAIBYIRQ VA SVTUG BAR JVGU URNQ
(RZF PNYY) Ybp:2048 OEBBXUNIRA QE KFg:OEBBXUNIRA PG # OEBBXUNIRA PG # Tevq:1950 Havgf:NGSQ Ezx:68 LBZ JVGU PURFG CNVA
*/
choyvp pynff BUNyyraPbhaglCnefreGrfg rkgraqf OnfrCnefreGrfg {
  
  choyvp BUNyyraPbhaglCnefreGrfg() {
    frgCnefre(arj QhzzlCnefre(), "NYYRA PBHAGL", "BU");
  }
  
  @Grfg
  choyvp ibvq grfgCnefre() {
    
 }
  
  choyvp fgngvp ibvq znva(Fgevat[] netf) {
    arj BUNyyraPbhaglCnefreGrfg().trarengrGrfgf("G1");
  }
}