cnpxntr arg.narv.pnqcntr.cnefref.BU;

vzcbeg arg.narv.pnqcntr.cnefref.OnfrCnefreGrfg;

vzcbeg bet.whavg.Grfg;

/*
Oryzbag Pbhagl, BU
Pbagnpg: Npgvir911
Ntrapl anzr: Oryzbag Pbhagl 911 Pragre
Ybpngvba: Fg Pynvefivyyr, BU, Havgrq Fgngrf
Fraqre: <OryzbagPbhagl911@pbzpnfg.arg>

OryzbagPbhagl911:[9170]- ANGHER: FZBXR BE BQBE VAIRFGVTNGVBA YBPNGVBA: 45619 YNHEN QE EVPUYNAQ GJC ORGJRRA QRNQ RAQ / ZPXRYIRL EQ PBZZRA GF: PNYYRE FGNGRF GUNG GURER VF SBJY BQBE ARNE UVF NQQERFF
OryzbagPbhagl911:[9159]-- - Angher: ZBGBE IRUVPYR PENFU - Ybpngvba: URAQELFOHET-SERRCBEG EQ XVEXJBBQ GJC - Pbzzragf: IRUVPYR BIRE RZONAXZRAG / AB VAWHEL / AB RAGENCZRAG BFC ERDHRFG SVER/RZF SBE FGNOVYVGL
OryzbagPbhagl911:[9159]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 68222 PBZZREPVNY QE CRNFR GJC ORGJRRA ORYZBAG NI / EBPX YA PBZZRAGF: 41 L/B SRZNYR ONPX CNVA FBHGU AHEFRF FGNGVBA
OryzbagPbhagl911:[9151]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 68222 PBZZREPVNY QE CRNFR GJC ORGJRRA ORYZBAG NI / EBPX YA PBZZRAGF: 41 L/B SRZNYR ONPX CNVA FBHGU AHEFRF FGNGVBA
OryzbagPbhagl911:[9159]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 2 JRFG FG OEVQTR CBEG ORGJRRA UVTU FG / ZNVA FG PBZZRAGF: +040.070894 -080.7 54082 69 L/B SRZNYR QVSSVPHYGL OERNGUVAT
OryzbagPbhagl911:[9163]--JBEX QRGNVY GBAVTUG NG LBHE FGNGVBA NG 18:30 UEF
OryzbagPbhagl911:[9163]-- - Angher: ZRQVPNY RZRETRAPL - Ybpngvba: 221.00 V-70 R CRNFR GJC - Pbzzragf: ZNYR HAERFCBAFVIR VA NA RKPNIGBE
OryzbagPbhagl911:[9163]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 221 V-70 R CRNFR GJC PBZZRAGF: ZNYR HAERFCBAFVIR VA NA RKPNIGBE
OryzbagPbhagl911:[9123]- ANGHER: ZBGBE IRUVPYR PENFU YBPNGVBA: 50708 ANGVBANY EQ EVPUYNAQ GJC ORGJRRA ERUZ EQ / QVRGEN YA PBZZRAGF: ZIP CBFFVOYR 1 V AWHEL
OryzbagPbhagl911:[9163]-- - Angher: ZRQVPNY RZRETRAPL - Ybpngvba: 38734.00 ANGVBANY EQ HAVBA GJC - Pbzzragf: 48 LB ZNYR PURFG CNVA FBO
OryzbagPbhagl911:[9163]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 38734 ANGVBANY E Q HAVBA GJC ORGJRRA ZRQVGRENARNA QE / GBJA UVYY EQ PBZZRAGF : 48 LB ZNYR PURFG CNVA FBO
OryzbagPbhagl911:[9163]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 565 J 41 FG FUNQ LFVQR ORGJRRA ZNQVFBA FG / ZBAEBR FG PBZZRAGF: SRZNYR VAWHE VRF SEBZ N SNYY
OryzbagPbhagl911:[9163]- ANGHER: NYNEZF YBPNGVBA: 100 CVAR NI FG PYNVEFIVYYR ORGJRRA ANGVBANY EQ / ZLEGYR QE PBZZRAGF: TRARENY SVER NYNE Z
OryzbagPbhagl911:[9123]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 108 CVAR NI FHVG R: NCG 202 FG PYNVEFIVYYR ORGJRRA ZLEGYR QE / QRNQ RAQ PBZZ RAGF: +040.081934 -080.938597 SRZNYR TRARENY VYYARFF
OryzbagPbhagl911:[9163]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 60666 A NAQREFBA EHA EQ FZVGU GJC ORGJRRA NEZFGEBAT-PRAGREIVYYR EQ / QRNQ R AQ PBZZRAGF: ZNYR JVGU OEBXRA EVOF 30 ZVA RGN GB GUR FHESNPR
OryzbagPbhagl911:[9123]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 63644 ORYZBAG FG EVPUYNAQ GJC ORGJRRA 2AQ FG / 3EQ FG PBZZRAGF: 81 LB ZNYR QRULQENGRQ
OryzbagPbhagl911:[9163]-- - Angher: NYNEZF - Ybpngvba: 68353.00 ONAABPX EQ EVPUYNAQ GJC - Pbzzragf: TRARENY SVER NYNEZ
OryzbagPbhagl911:[9163]-- - Angher: ZRQVPNY RZRETRAPL - Ybpngvba: 56525.00 WBEQNA EHA EQ CHYGARL GJC - Pbzzragf: 81 LB SRZNYR HAERFCBAFVIR HAXABJA VS OERNGUVAT
OryzbagPbhagl911:[9123]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 56525 WBEQNA EHA EQ CHYGARL GJC ORGJRRA UVTU EVQTR EQ / JNEQ EQ PBZZRAGF: 8 1 LB SRZNYR HAERFCBAFVIR HAXABJA VS OERNGUVAT
OryzbagPbhagl911:[9163]-- - Angher: ZBGBE IRUVPYR PENFU - Ybpngvba: 62240.00 ONVYRL EQ JNEERA GJC - Pbzzragf: 2 PNE ZIP
OryzbagPbhagl911:[9163]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 50750 CVCR PERRX EQ ZRNQ GJC ORGJRRA PENZZRE EQ / A XBPV EQ PBZZRAGF: 61 LB SRZNYR VAWHEVRF SEBZ N SNYY
OryzbagPbhagl911:[9163]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 68137 UNZZBAQ EQ EVPUYNAQ GJC ORGJRRA ONAABPX EQ / NYYVFBA NI PBZZRAGF: HAX ABJA ZRQVPNY RZRETRAPL
OryzbagPbhagl911:[9169]-- - Angher: ZRQVPNY RZRETRAPL - Ybpngvba: 68242.00 ARBYN NI CRNFR GJC - Pbzzragf: 88 LE BYQ SRZNYR HANOYR GB NZOHYNGR
OryzbagPbhagl911:[9157]-- - Angher: ZBGBE IRUVPYR PENFU - Ybpngvba: 330.00 F PURFGAHG FG ONEARFIVYYR - Pbzzragf:
OryzbagPbhagl911:[9157]- ANGHER: ZBGBE IRUVPYR PENFU YBPNGVBA: 330 F PURFGAHG FG ONEARFIVYYR ORGJRRA PRZRGNEL FG / YRTTRGG NI
OryzbagPbhagl911:[9161]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 608 JVYRL NI ONE ARFIVYYR ORGJRRA UHGPUVAFBA NI / ARIN NI PBZZRAGF: ZNYR CG URNQ NAQ UNAQ CNVA CQ BA FPRAR
OryzbagPbhagl911:[9172]-- - Angher: FGEHPGHER SVER - Ybpngvba: 54318.00 PBYRENVA CXR PBYRENVA GJC - Pbzzragf: +040.121083 -080.801525 FGEHPGHER SVER. BKLTRA GNAXF VAFVQR
OryzbagPbhagl911:[9139]-- - Angher: ZRQVPNY RZRETRAPL - Ybpngvba: 3.00 JRTRR YA Fhvgr:YBG 23 FUNQLFVQR - Pbzzragf: +039.966899 -080.758181 PS= 68% S QVSSVPHYGL OERNGUVAT
OryzbagPbhagl911:[9169]-- - Angher: ZRQVPNY RZRETRAPL - Ybpngvba: 201.00 A ZNEXRG FG FG PYNVEFIVYYR - Pbzzragf: 81 LE BYQ TRARENY VYYARFF
OryzbagPbhagl911:[9169]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 69287 CEBIVQRAG EQ EVPUYNAQ GJC ORGJRRA A ZNEXRG FG RKG / WHT EHA EQ PBZZRA GF: +040.106460 -080.927932 ZNYR CG NYYRTEVP ERNPGVBA GB N ORR FGVAT
OryzbagPbhagl911:[9139]-- - Angher: IRUVPYR SVER (SQ) - Ybpngvba: 199.00 V-70 J XVEXJBBQ GJC - Pbzzragf: +040.057397 - 081.205316 PS= 90% IRUVPYR BA SVER NYY BPPHCNAGF NCCRNE GB OR BHG
OryzbagPbhagl911:[9163]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 68137 UNZZBAQ EQ EVPUYNAQ GJC ORGJRRA ONAABPX EQ / NYYVFBA NI PBZZRAGF: SRZ NYR CG PURFG CNVA
OryzbagPbhagl911:[9163]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 42600 ANGVBANY E Q FHVGR: YBG 75 HAVBA GJC ORGJRRA F CNAPBNFG EQ / ANGVBANY- BPB EQ PBZZRAGF: 7 LB SRZNYR VAWHEVRF SEBZ N OVXR JERPX
OryzbagPbhagl911:[9137]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 57710 ZBBERF EHA EQ CRNFR GJC ORGJRRA TERRAONHPU QE / QRNQ RAQ PBZZRAGF: 54 LB Z FRVMHERF
OryzbagPbhagl911:[9163]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 71465 ZNVA FG FH VGR: YBG 10 JURRYVAT GJC ORGJRRA CUVYYVCF EQ / PBYHZOVN FG PBZZRAGF: 46 LB ZNYR UVTU URNEG ENGR
OryzbagPbhagl911:[9163]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 50590 PVAQL QE F HVGR: 17 EVPUYNAQ GJC ORGJRRA URZVATJNL QE / QRNQ RAQ PBZZR AGF: HAXABJA ZRQVPNY RZRETRAPL
OryzbagPbhagl911:[9166]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 366 F PURFGAHG F G ONEARFIVYYR ORGJRRA YRTTRGG NI / R CVXR FG PBZZRAGF: +039 .984484 -081.179330 15 LB ZNYR QVSS OERNGUVAT / UK BS NFGUZ N
OryzbagPbhagl911:[9163]- ANGHER: FZBXR BE BQBE VAIRFGVTNGVBA YBPNGVBA: 105 YN VCCYR FG OEVQTRCBEG ORGJRRA YBZONEQL URVTUGF / PNQVM CXR EQ PBZZRAGF: PNYYRE FGNGRF UBHFR SHYY BS TNF
OryzbagPbhagl911:[9166]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 69844 ZNVA FG EV PUYNAQ GJC ORGJRRA CVAR NI / PNYQJRYY QE PBZZRAGF: SRZNYR O NPX NAQ ARPX VAWHEVRF SEBZ N ZIP
OryzbagPbhagl911:[9163]- ANGHER: CBJRE YVARF BE RYRPGEVPNY PNYY YBPNGVBA: 334 5 ZBAEBR FG ORYYNVER ORGJRRA 33EQ FG / 34GU FG PBZZRAGF: CB JRE YVAR QBJA
OryzbagPbhagl911:[9163]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 55390 QVYYRF OBG GBZ ZRNQ GJC ORGJRRA CBJUNGNA-FUNQLFVQR EQ / PURFGAHG TEBIR EQ PBZZRAGF: 69 LB ZNYR FBO
OryzbagPbhagl911:[9163]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 400 PNEEVR NI FH VGR: 114 ONEARFIVYYR ORGJRRA UHAGF NI / UVTUYNAQ NI PBZZRAG F: 64 LB ZNYR PIN
OryzbagPbhagl911:[9163]-- - Angher: ZRQVPNY RZRETRAPL - Ybpngvba: 302.00 ZNVA FG HAVBA GJC - Pbzzragf: 28 LB SRZNYR VA YNOBE
OryzbagPbhagl911:[9163]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 302 ZNVA FG HAVB A GJC ORGJRRA PRAGRE PEBFF FG / J PEBFF FG PBZZRAGF: 28 LB SRZNYR VA YNOBE
OryzbagPbhagl911:[9157]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 100 ERFREIBVE EQ FHVGR: EZ 203 FG PYNVEFIVYYR ORGJRRA WBUARG QE / UNEORY (F BHGU) QE PBZZRAGF: SRZNYR CG VAWHEVRF SEBZ SNYY
OryzbagPbhagl911:[9163]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 1032 UBJNEQ FG F HVGR: NCG Q OEVQTRCBEG ORGJRRA CVAR FG / PRQNE FG PBZZRAGF: +040.067600 -080.756507 63 LB ZNYR TRARENY VYYARFF
OryzbagPbhagl911:[9157]-- - Angher: ZRQVPNY RZRETRAPL - Ybpngvba: 72610.00 HAVGL PUHEPU EQ JURRYVAT GJC - Pbzzragf: ZNYR YNLVAT VA GUR EBNQJNL, HAERFCBAFVIR
OryzbagPbhagl911:[9157]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 72610 HAVGL PUHE PU EQ JURRYVAT GJC ORGJRRA THA PYHO EQ / DHVAAF JNL PBZZRAG F: ZNYR YNLVAT VA GUR EBNQJNL, HAERFCBAFVIR
OryzbagPbhagl911:[9110]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 1104 UBJNEQ FG O EVQTRCBEG ORGJRRA PRQNE FG / QRNQ RAQ PBZZRAGF: ZNYR CNGVRA G, CBFFVOYR PBAPHFFVBA
OryzbagPbhagl911:[9139]-- - Angher: ZRQVPNY RZRETRAPL - Ybpngvba: 287.00 F PURFGAHG FG ONEARFIVYYR - Pbzzragf: SRZNYR OYRRQVAT PNHFR HAXABJA
OryzbagPbhagl911:[9139]-- - Angher: ZRQVPNY RZRETRAPL - Ybpngvba: 58545.00 YBJRE FNAQL EVQTR EQ JNLAR GJC - Pbzzragf: 45 L/B ZNYR FRIRER PURFG CNVA GBZ QBGL ERFVQRAPR
OryzbagPbhagl911:[9159]-- - Angher: ZBGBE IRUVPYR PENFU - Ybpngvba: 702.00 R ZNVA FG ONEARFIVYYR - Pbzzragf: HAXABJA VAWHEVRF / RAGENCZRAG [ CQ BAFPRAR
OryzbagPbhagl911:[9159]- ANGHER: ZBGBE IRUVPYR PENFU YBPNGVBA: 702 R ZNVA FG ONEARFIVYYR ORGJRRA TENPR NI / ORGURFQN FG PBZZRAGF: HAXABJ A VAWHEVRF / RAGENCZRAG
OryzbagPbhagl911:[9139]-- - Angher: ZRQVPNY RZRETRAPL - Ybpngvba: 68207.00 PBZZREPVNY QE Fhvgr:NCG 3P CRNFR GJC - Pbzzragf: 92 L/B S CBFFVOYR FGEBXR 20:59---2AQ GBARF NQQ RZG
OryzbagPbhagl911:[9139]-- - Angher: ZRQVPNY RZRETRAPL - Ybpngvba: 68207.00 PBZZREPVNY QE Fhvgr:NCG 3P CRNFR GJC - Pbzzragf: 92 L/B S CBFFVOYR FGEBXR
OryzbagPbhagl911:[9139]-- - Angher: ZRQVPNY RZRETRAPL - Ybpngvba: 68014.00 PBZZREPVNY QE Fhvgr:NCG 9T CRNFR GJC - Pbzzragf: +040.070486 -080.779381 49 L/B S CBFFVOYR XVQARL FGBARF
OryzbagPbhagl911:[9167]-- - Angher: ZRQVPNY RZRETRAPL - Ybpngvba: 50890.00 ANGVBANY EQ EVPUYNAQ GJC - Pbzzragf: +040.076913 -080.868387 SRZNYR FRVMHER
OryzbagPbhagl911:[9167]-- - Angher: ZRQVPNY RZRETRAPL - Ybpngvba: 319.00 F ZNVA FG Fhvgr:YBG 22 ORGURFQN - Pbzzragf: 34 L/B SRZNYR NYGRERQ ZRAGNY FGNGHF
OryzbagPbhagl911:[9137]-- - Angher: FGEHPGHER SVER - Ybpngvba: 71021.00 ONEGBA EQ PBYRENVA GJC - Pbzzragf: JNF PBAGEBYYRQ OHEA FGNEGVAT GB ZRYG FVQVAT BA GUR UBHFR.
OryzbagPbhagl911:[9169]-- - Angher: FGEHPGHER SVER - Ybpngvba: 71021.00 ONEGBA EQ PBYRENVA GJC - Pbzzragf: JNF PBAGEBYYRQ OHEA FGNEGVAT GB ZRYG FVQVAT BA GUR UBHFR.
OryzbagPbhagl911:[9167]- ANGHER: ZBGBE IRUVPYR PENFU YBPNGVBA: R PNCGVAN UJL / CVARYBPXR QE LBEX GJC PBZZRAGF: 1 VAWHEL AB RAGENCZRAG
OryzbagPbhagl911:[9167]- ANGHER: ZBGBE IRUVPYR PENFU YBPNGVBA: R PNCGVAN UJL / CVARYBPXR QE LBEX GJC PBZZRAGF: YVARF QBJA BA GUR IRUVPYR . HAXABJA VAWHEVRF. AB RAGENCZRAG
OryzbagPbhagl911:[9167]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 65975 J RPUB EQ CHYGARL GJC ORGJRRA RPUB EQ / QRNQ RAQ PBZZRAGF: ZNYR JVGU NA VASRPGRQ SVATRE
OryzbagPbhagl911:[9167]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 71395 PERFPRAG E Q PBYRENVA GJC ORGJRRA PERFPRAG-ONEGBA EQ / PRAGRE FG PBZZR AGF: 44 L/B SRZNYR NYYRETVP ERNPGVBA GB ZRQVPNGVBA
OryzbagPbhagl911:[9167]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 71395 PERFPRAG E Q PBYRENVA GJC ORGJRRA PERFPRAG-ONEGBA EQ / PRAGRE FG PBZZR AGF: 44 L/B SRZNYR NYYRETVP ERNPGVBA GB ZRQVPNGVBA FRPBAQ G BAR
OryzbagPbhagl911:[9167]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 68222 PBZZREPVNY QE FHVGR: YBHTR CRNFR GJC ORGJRRA ORYZBAG NI / EBPX YA PBZ ZRAGF: 76 L/B HAERFCBAFVIR, VF OERNGUVAT. ULCBGRAFVBA
OryzbagPbhagl911:[9167]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 68222 PBZZREPVNY QE CRNFR GJC ORGJRRA ORYZBAG NI / EBPX YA PBZZRAGF: 76 L/B HAERFCBAFVIR, VF OERNGUVAT. ULCBGRAFVBA
OryzbagPbhagl911:[9167]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 65 J 47 FG FHVGR : NCG 7 FUNQLFVQR ORGJRRA PRAGENY NI / WRSSREFBA NI PBZZRAG F: 38 L/B SRZNYR NOQBZVANY CNVA
OryzbagPbhagl911:[9167]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 66680 RKRPHGVIR QE EVPUYNAQ GJC ORGJRRA F FRIRAGL EQ / CBTHR EQ PBZZRAGF: 3 0 L/B ZNYR VAWHEVRF SEBZ SNYY CBFF HAERFCBAFVIR.
OryzbagPbhagl911:[9167]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 4800 PRAGENY NI FHVGR: YBG 5 FUNQLFVQR ORGJRRA R 46GU FG / J 46GU FG PBZZRA GF: +039.973497 -080.765626 72 L/B SRZNYR UVTU GRZC
OryzbagPbhagl911:[9167]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 608 JVYRL NI ONE ARFIVYYR ORGJRRA UHGPUVAFBA NI / ARIN NI PBZZRAGF: ZNYR YRT CNVA
OryzbagPbhagl911:[9167]- ANGHER: FREIVPR PNYY YBPNGVBA: NVECBEG EQ / OEHFU EH A EQ EVPUYNAQ GJC PBZZRAGF: GEHPX YRNXVAT QVRFRY NSGRE N ZVA BE NPPVQRAG
OryzbagPbhagl911:[9166]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 63240 FNAQ UVYY EQ CHYGARL GJC ORGJRRA NYGREANGR FNAQ UVYY NCCEBNPU / GEBHT U EHA EQ PBZZRAGF: SRZNYR CG FLAPBCNY RCVFBQR
OryzbagPbhagl911:[9159]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 62650 QHFGL YA J NEERA GJC ORGJRRA ONEARFIVYYR ORGURFQN EQ / QRNQ RAQ PBZZRA GF: 62 L/B SRZNYR TRARENY VYYARFF
OryzbagPbhagl911:[9139]-- - Angher: ZRQVPNY RZRETRAPL - Ybpngvba: 65229.00 ZP ZVYYNA EQ HAVBA GJC - Pbzzragf: URNQ VAWHEVRF SEBZ NA NFFNHYG
OryzbagPbhagl911:[9139]-- - Angher: IRUVPYR SVER (SQ) - Ybpngvba: 65711.00 J RPUB EQ CHYGARL GJC - Pbzzragf: IRUVPYR BA SVER ARKG GB ERFVQRAPR
OryzbagPbhagl911:[9123]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 68040 ZNYY EVAT EQ EVPUYNAQ GJC ORGJRRA ZNYY EQ / ZNYY EQ PBZZRAGF: ZNYR PU BPVAT ....FBZRGUVAT YBQTRQ VA GUR GUEBNG
OryzbagPbhagl911:[9159]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 228 ZNVA FG OEVQ TRCBEG ORGJRRA NYYRA FG / BYQ PNQVM EQ PBZZRAGF: ZNYR VAGBK VPNGRQ
OryzbagPbhagl911:[9139]-- - Angher: ZRQVPNY RZRETRAPL - Ybpngvba: 55707.00 VAQHFGEVNY QE CRNFR GJC - Pbzzragf: ZNA YLVAT VA GUR FGERRG HAXABJA VAWHEVRF
OryzbagPbhagl911:[9157]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 66895 TENUNZ EQ EVPUYNAQ GJC ORGJRRA EBOREGB QE / NAAN QE PBZZRAGF: +040.05 4961 -080.880146 SRZNYR CG PBZCYVPNGVBAF SEBZ FHETREL
OryzbagPbhagl911:[9157]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 3479 PRAGENY NI FUNQLFVQR ORGJRRA RYX NI / R 35GU FG PBZZRAGF: PNYYRE FGNGR F UVF JVSR GBBX CVYYF, FUR YVIRF NG GUR SVEFG NCNEGZRAGF PBZ VAT VAGB GBJA BA GUR EVTUG URE ANZR VF OER
OryzbagPbhagl911:[9157]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 50813 INYYRL CYN MN QE EVPUYNAQ GJC ORGJRRA INYYRL PRAGER OYIQ / QVRGEN YA P BZZRAGF: SRZNYR CG QVSSVPHYGL OERNGUVAT
OryzbagPbhagl911:[9137]-- - Angher: ZBGBE IRUVPYR PENFU - Ybpngvba: 54750.00 ANGVBANY EQ PBYRENVA GJC - Pbzzragf: +040.061388 -080.752215
OryzbagPbhagl911:[9137]- ANGHER: ZBGBE IRUVPYR PENFU YBPNGVBA: 54750 ANGVBANY EQ PBYRENVA GJC ORGJRRA ORNEVAT EQ / PUREZBAG EQ PBZZRAGF: +040.061388 -080.752215
OryzbagPbhagl911:[9137]-- - Angher: ZBGBE IRUVPYR PENFU - Ybpngvba: 208.00 V-70 R HAVBA GJC - Pbzzragf: PNE IF FRZV GEHPX ZIP ...HXABJA VAWHEVRF
OryzbagPbhagl911:[9123]- ANGHER: ZBGBE IRUVPYR PENFU YBPNGVBA: 208 V-70 R HAV BA GJC PBZZRAGF: PNE IF FRZV GEHPX ZIP ...HXABJA VAWHEVRF
OryzbagPbhagl911:[9137]-- - Angher: ZBGBE IRUVPYR PENFU - Ybpngvba: 208.00 V-70 R HAVBA GJC - Pbzzragf: PNE IF FRZV GEHPX
OryzbagPbhagl911:[9157]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 51660 TYRAPBR-FG RJNEGFIVYYR EQ EVPUYNAQ GJC ORGJRRA FPRAVP IVRJ EQ / OELXNY FXV QE PBZZRAGF: SRZNYR CG UNF SNYYRA
 */
choyvp pynff BUOryzbagPbhaglCnefreGrfg rkgraqf OnfrCnefreGrfg {
  
  choyvp BUOryzbagPbhaglCnefreGrfg() {
    frgCnefre(arj BUOryzbagPbhaglCnefre(), "ORYZBAG PBHAGL", "BU");
  }
  
  @Grfg
  choyvp ibvq grfgCnefre() {

 // ************************ CNEFR SNVYHER *****************************
 // OryzbagPbhagl911:[9170]- ANGHER: FZBXR BE BQBE VAIRFGVTNGVBA YBPNGVBA: 45619 YNHEN QE EVPUYNAQ GJC ORGJRRA QRNQ RAQ / ZPXRYIRL EQ PBZZRA GF: PNYYRE FGNGRF GUNG GURER VF SBJY BQBE ARNE UVF NQQERFF

     qbGrfg("G2",
         "OryzbagPbhagl911:[9159]-- - Angher: ZBGBE IRUVPYR PENFU - Ybpngvba: URAQELFOHET-SERRCBEG EQ XVEXJBBQ GJC - Pbzzragf: IRUVPYR BIRE RZONAXZRAG / AB VAWHEL / AB RAGENCZRAG BFC ERDHRFG SVER/RZF SBE FGNOVYVGL",
         "PNYY:OryzbagPbhagl911:[9159]-- - Angher: ZBGBE IRUVPYR PENFU",
         "NQQE:URAQELFOHET-SERRCBEG EQ",
         "NCG:XVEXJBBQ GJC",
         "VASB:IRUVPYR BIRE RZONAXZRAG / AB VAWHEL / AB RAGENCZRAG BFC ERDHRFG SVER/RZF SBE FGNOVYVGL");

 // ************************ CNEFR SNVYHER *****************************
 // OryzbagPbhagl911:[9159]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 68222 PBZZREPVNY QE CRNFR GJC ORGJRRA ORYZBAG NI / EBPX YA PBZZRAGF: 41 L/B SRZNYR ONPX CNVA FBHGU AHEFRF FGNGVBA

 // ************************ CNEFR SNVYHER *****************************
 // OryzbagPbhagl911:[9151]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 68222 PBZZREPVNY QE CRNFR GJC ORGJRRA ORYZBAG NI / EBPX YA PBZZRAGF: 41 L/B SRZNYR ONPX CNVA FBHGU AHEFRF FGNGVBA

 // ************************ CNEFR SNVYHER *****************************
 // OryzbagPbhagl911:[9159]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 2 JRFG FG OEVQTR CBEG ORGJRRA UVTU FG / ZNVA FG PBZZRAGF: +040.070894 -080.7 54082 69 L/B SRZNYR QVSSVPHYGL OERNGUVAT

 // ************************ CNEFR SNVYHER *****************************
 // OryzbagPbhagl911:[9163]--JBEX QRGNVY GBAVTUG NG LBHE FGNGVBA NG 18:30 UEF

     qbGrfg("G7",
         "OryzbagPbhagl911:[9163]-- - Angher: ZRQVPNY RZRETRAPL - Ybpngvba: 221.00 V-70 R CRNFR GJC - Pbzzragf: ZNYR HAERFCBAFVIR VA NA RKPNIGBE",
         "PNYY:OryzbagPbhagl911:[9163]-- - Angher: ZRQVPNY RZRETRAPL",
         "NQQE:221 V-70 R",
         "ZNQQE:221 V 70 R",
         "NCG:CRNFR GJC",
         "VASB:ZNYR HAERFCBAFVIR VA NA RKPNIGBE");

 // ************************ CNEFR SNVYHER *****************************
 // OryzbagPbhagl911:[9163]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 221 V-70 R CRNFR GJC PBZZRAGF: ZNYR HAERFCBAFVIR VA NA RKPNIGBE

 // ************************ CNEFR SNVYHER *****************************
 // OryzbagPbhagl911:[9123]- ANGHER: ZBGBE IRUVPYR PENFU YBPNGVBA: 50708 ANGVBANY EQ EVPUYNAQ GJC ORGJRRA ERUZ EQ / QVRGEN YA PBZZRAGF: ZIP CBFFVOYR 1 V AWHEL

     qbGrfg("G10",
         "OryzbagPbhagl911:[9163]-- - Angher: ZRQVPNY RZRETRAPL - Ybpngvba: 38734.00 ANGVBANY EQ HAVBA GJC - Pbzzragf: 48 LB ZNYR PURFG CNVA FBO",
         "PNYY:OryzbagPbhagl911:[9163]-- - Angher: ZRQVPNY RZRETRAPL",
         "NQQE:38734 ANGVBANY EQ",
         "NCG:HAVBA GJC",
         "VASB:48 LB ZNYR PURFG CNVA FBO");

 // ************************ CNEFR SNVYHER *****************************
 // OryzbagPbhagl911:[9163]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 38734 ANGVBANY E Q HAVBA GJC ORGJRRA ZRQVGRENARNA QE / GBJA UVYY EQ PBZZRAGF : 48 LB ZNYR PURFG CNVA FBO

 // ************************ CNEFR SNVYHER *****************************
 // OryzbagPbhagl911:[9163]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 565 J 41 FG FUNQ LFVQR ORGJRRA ZNQVFBA FG / ZBAEBR FG PBZZRAGF: SRZNYR VAWHE VRF SEBZ N SNYY

 // ************************ CNEFR SNVYHER *****************************
 // OryzbagPbhagl911:[9163]- ANGHER: NYNEZF YBPNGVBA: 100 CVAR NI FG PYNVEFIVYYR ORGJRRA ANGVBANY EQ / ZLEGYR QE PBZZRAGF: TRARENY SVER NYNE Z

 // ************************ CNEFR SNVYHER *****************************
 // OryzbagPbhagl911:[9123]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 108 CVAR NI FHVG R: NCG 202 FG PYNVEFIVYYR ORGJRRA ZLEGYR QE / QRNQ RAQ PBZZ RAGF: +040.081934 -080.938597 SRZNYR TRARENY VYYARFF

 // ************************ CNEFR SNVYHER *****************************
 // OryzbagPbhagl911:[9163]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 60666 A NAQREFBA EHA EQ FZVGU GJC ORGJRRA NEZFGEBAT-PRAGREIVYYR EQ / QRNQ R AQ PBZZRAGF: ZNYR JVGU OEBXRA EVOF 30 ZVA RGN GB GUR FHESNPR

 // ************************ CNEFR SNVYHER *****************************
 // OryzbagPbhagl911:[9123]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 63644 ORYZBAG FG EVPUYNAQ GJC ORGJRRA 2AQ FG / 3EQ FG PBZZRAGF: 81 LB ZNYR QRULQENGRQ

     qbGrfg("G17",
         "OryzbagPbhagl911:[9163]-- - Angher: NYNEZF - Ybpngvba: 68353.00 ONAABPX EQ EVPUYNAQ GJC - Pbzzragf: TRARENY SVER NYNEZ",
         "PNYY:OryzbagPbhagl911:[9163]-- - Angher: NYNEZF",
         "NQQE:68353 ONAABPX EQ",
         "NCG:EVPUYNAQ GJC",
         "VASB:TRARENY SVER NYNEZ");

     qbGrfg("G18",
         "OryzbagPbhagl911:[9163]-- - Angher: ZRQVPNY RZRETRAPL - Ybpngvba: 56525.00 WBEQNA EHA EQ CHYGARL GJC - Pbzzragf: 81 LB SRZNYR HAERFCBAFVIR HAXABJA VS OERNGUVAT",
         "PNYY:OryzbagPbhagl911:[9163]-- - Angher: ZRQVPNY RZRETRAPL",
         "NQQE:56525 WBEQNA EHA EQ",
         "NCG:CHYGARL GJC",
         "VASB:81 LB SRZNYR HAERFCBAFVIR HAXABJA VS OERNGUVAT");

 // ************************ CNEFR SNVYHER *****************************
 // OryzbagPbhagl911:[9123]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 56525 WBEQNA EHA EQ CHYGARL GJC ORGJRRA UVTU EVQTR EQ / JNEQ EQ PBZZRAGF: 8 1 LB SRZNYR HAERFCBAFVIR HAXABJA VS OERNGUVAT

     qbGrfg("G20",
         "OryzbagPbhagl911:[9163]-- - Angher: ZBGBE IRUVPYR PENFU - Ybpngvba: 62240.00 ONVYRL EQ JNEERA GJC - Pbzzragf: 2 PNE ZIP",
         "PNYY:OryzbagPbhagl911:[9163]-- - Angher: ZBGBE IRUVPYR PENFU",
         "NQQE:62240 ONVYRL EQ",
         "NCG:JNEERA GJC",
         "VASB:2 PNE ZIP");

 // ************************ CNEFR SNVYHER *****************************
 // OryzbagPbhagl911:[9163]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 50750 CVCR PERRX EQ ZRNQ GJC ORGJRRA PENZZRE EQ / A XBPV EQ PBZZRAGF: 61 LB SRZNYR VAWHEVRF SEBZ N SNYY

 // ************************ CNEFR SNVYHER *****************************
 // OryzbagPbhagl911:[9163]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 68137 UNZZBAQ EQ EVPUYNAQ GJC ORGJRRA ONAABPX EQ / NYYVFBA NI PBZZRAGF: HAX ABJA ZRQVPNY RZRETRAPL

     qbGrfg("G23",
         "OryzbagPbhagl911:[9169]-- - Angher: ZRQVPNY RZRETRAPL - Ybpngvba: 68242.00 ARBYN NI CRNFR GJC - Pbzzragf: 88 LE BYQ SRZNYR HANOYR GB NZOHYNGR",
         "PNYY:OryzbagPbhagl911:[9169]-- - Angher: ZRQVPNY RZRETRAPL",
         "NQQE:68242 ARBYN NI",
         "ZNQQE:68242 ARBYN NIR",
         "NCG:CRNFR GJC",
         "VASB:88 LE BYQ SRZNYR HANOYR GB NZOHYNGR");

     qbGrfg("G24",
         "OryzbagPbhagl911:[9157]-- - Angher: ZBGBE IRUVPYR PENFU - Ybpngvba: 330.00 F PURFGAHG FG ONEARFIVYYR - Pbzzragf:",
         "PNYY:OryzbagPbhagl911:[9157]-- - Angher: ZBGBE IRUVPYR PENFU",
         "NQQE:330 F PURFGAHG FG",
         "PVGL:ONEARFIVYYR");

 // ************************ CNEFR SNVYHER *****************************
 // OryzbagPbhagl911:[9157]- ANGHER: ZBGBE IRUVPYR PENFU YBPNGVBA: 330 F PURFGAHG FG ONEARFIVYYR ORGJRRA PRZRGNEL FG / YRTTRGG NI

 // ************************ CNEFR SNVYHER *****************************
 // OryzbagPbhagl911:[9161]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 608 JVYRL NI ONE ARFIVYYR ORGJRRA UHGPUVAFBA NI / ARIN NI PBZZRAGF: ZNYR CG URNQ NAQ UNAQ CNVA CQ BA FPRAR

     qbGrfg("G27",
         "OryzbagPbhagl911:[9172]-- - Angher: FGEHPGHER SVER - Ybpngvba: 54318.00 PBYRENVA CXR PBYRENVA GJC - Pbzzragf: +040.121083 -080.801525 FGEHPGHER SVER. BKLTRA GNAXF VAFVQR",
         "PNYY:OryzbagPbhagl911:[9172]-- - Angher: FGEHPGHER SVER",
         "NQQE:54318 PBYRENVA CXR",
         "ZNQQE:54318 PBYRENVA CVXR",
         "NCG:PBYRENVA GJC",
         "VASB:+040.121083 -080.801525 FGEHPGHER SVER. BKLTRA GNAXF VAFVQR");

     qbGrfg("G28",
         "OryzbagPbhagl911:[9139]-- - Angher: ZRQVPNY RZRETRAPL - Ybpngvba: 3.00 JRTRR YA Fhvgr:YBG 23 FUNQLFVQR - Pbzzragf: +039.966899 -080.758181 PS= 68% S QVSSVPHYGL OERNGUVAT",
         "PNYY:OryzbagPbhagl911:[9139]-- - Angher: ZRQVPNY RZRETRAPL",
         "NQQE:3 JRTRR YA",
         "NCG:YBG-23",
         "PVGL:FUNQLFVQR",
         "VASB:+039.966899 -080.758181 PS= 68% S QVSSVPHYGL OERNGUVAT");

     qbGrfg("G29",
         "OryzbagPbhagl911:[9169]-- - Angher: ZRQVPNY RZRETRAPL - Ybpngvba: 201.00 A ZNEXRG FG FG PYNVEFIVYYR - Pbzzragf: 81 LE BYQ TRARENY VYYARFF",
         "PNYY:OryzbagPbhagl911:[9169]-- - Angher: ZRQVPNY RZRETRAPL",
         "NQQE:201 A ZNEXRG FG",
         "NCG:FG PYNVEFIVYYR",
         "VASB:81 LE BYQ TRARENY VYYARFF");

 // ************************ CNEFR SNVYHER *****************************
 // OryzbagPbhagl911:[9169]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 69287 CEBIVQRAG EQ EVPUYNAQ GJC ORGJRRA A ZNEXRG FG RKG / WHT EHA EQ PBZZRA GF: +040.106460 -080.927932 ZNYR CG NYYRTEVP ERNPGVBA GB N ORR FGVAT

     qbGrfg("G31",
         "OryzbagPbhagl911:[9139]-- - Angher: IRUVPYR SVER (SQ) - Ybpngvba: 199.00 V-70 J XVEXJBBQ GJC - Pbzzragf: +040.057397 - 081.205316 PS= 90% IRUVPYR BA SVER NYY BPPHCNAGF NCCRNE GB OR BHG",
         "PNYY:OryzbagPbhagl911:[9139]-- - Angher: IRUVPYR SVER (SQ)",
         "NQQE:199 V-70 J",
         "ZNQQE:199 V 70 J",
         "NCG:XVEXJBBQ GJC",
         "VASB:+040.057397 - 081.205316 PS= 90% IRUVPYR BA SVER NYY BPPHCNAGF NCCRNE GB OR BHG");

 // ************************ CNEFR SNVYHER *****************************
 // OryzbagPbhagl911:[9163]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 68137 UNZZBAQ EQ EVPUYNAQ GJC ORGJRRA ONAABPX EQ / NYYVFBA NI PBZZRAGF: SRZ NYR CG PURFG CNVA

 // ************************ CNEFR SNVYHER *****************************
 // OryzbagPbhagl911:[9163]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 42600 ANGVBANY E Q FHVGR: YBG 75 HAVBA GJC ORGJRRA F CNAPBNFG EQ / ANGVBANY- BPB EQ PBZZRAGF: 7 LB SRZNYR VAWHEVRF SEBZ N OVXR JERPX

 // ************************ CNEFR SNVYHER *****************************
 // OryzbagPbhagl911:[9137]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 57710 ZBBERF EHA EQ CRNFR GJC ORGJRRA TERRAONHPU QE / QRNQ RAQ PBZZRAGF: 54 LB Z FRVMHERF

 // ************************ CNEFR SNVYHER *****************************
 // OryzbagPbhagl911:[9163]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 71465 ZNVA FG FH VGR: YBG 10 JURRYVAT GJC ORGJRRA CUVYYVCF EQ / PBYHZOVN FG PBZZRAGF: 46 LB ZNYR UVTU URNEG ENGR

 // ************************ CNEFR SNVYHER *****************************
 // OryzbagPbhagl911:[9163]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 50590 PVAQL QE F HVGR: 17 EVPUYNAQ GJC ORGJRRA URZVATJNL QE / QRNQ RAQ PBZZR AGF: HAXABJA ZRQVPNY RZRETRAPL

 // ************************ CNEFR SNVYHER *****************************
 // OryzbagPbhagl911:[9166]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 366 F PURFGAHG F G ONEARFIVYYR ORGJRRA YRTTRGG NI / R CVXR FG PBZZRAGF: +039 .984484 -081.179330 15 LB ZNYR QVSS OERNGUVAT / UK BS NFGUZ N

 // ************************ CNEFR SNVYHER *****************************
 // OryzbagPbhagl911:[9163]- ANGHER: FZBXR BE BQBE VAIRFGVTNGVBA YBPNGVBA: 105 YN VCCYR FG OEVQTRCBEG ORGJRRA YBZONEQL URVTUGF / PNQVM CXR EQ PBZZRAGF: PNYYRE FGNGRF UBHFR SHYY BS TNF

 // ************************ CNEFR SNVYHER *****************************
 // OryzbagPbhagl911:[9166]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 69844 ZNVA FG EV PUYNAQ GJC ORGJRRA CVAR NI / PNYQJRYY QE PBZZRAGF: SRZNYR O NPX NAQ ARPX VAWHEVRF SEBZ N ZIP

 // ************************ CNEFR SNVYHER *****************************
 // OryzbagPbhagl911:[9163]- ANGHER: CBJRE YVARF BE RYRPGEVPNY PNYY YBPNGVBA: 334 5 ZBAEBR FG ORYYNVER ORGJRRA 33EQ FG / 34GU FG PBZZRAGF: CB JRE YVAR QBJA

 // ************************ CNEFR SNVYHER *****************************
 // OryzbagPbhagl911:[9163]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 55390 QVYYRF OBG GBZ ZRNQ GJC ORGJRRA CBJUNGNA-FUNQLFVQR EQ / PURFGAHG TEBIR EQ PBZZRAGF: 69 LB ZNYR FBO

 // ************************ CNEFR SNVYHER *****************************
 // OryzbagPbhagl911:[9163]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 400 PNEEVR NI FH VGR: 114 ONEARFIVYYR ORGJRRA UHAGF NI / UVTUYNAQ NI PBZZRAG F: 64 LB ZNYR PIN

     qbGrfg("G43",
         "OryzbagPbhagl911:[9163]-- - Angher: ZRQVPNY RZRETRAPL - Ybpngvba: 302.00 ZNVA FG HAVBA GJC - Pbzzragf: 28 LB SRZNYR VA YNOBE",
         "PNYY:OryzbagPbhagl911:[9163]-- - Angher: ZRQVPNY RZRETRAPL",
         "NQQE:302 ZNVA FG",
         "NCG:HAVBA GJC",
         "VASB:28 LB SRZNYR VA YNOBE");

 // ************************ CNEFR SNVYHER *****************************
 // OryzbagPbhagl911:[9163]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 302 ZNVA FG HAVB A GJC ORGJRRA PRAGRE PEBFF FG / J PEBFF FG PBZZRAGF: 28 LB SRZNYR VA YNOBE

 // ************************ CNEFR SNVYHER *****************************
 // OryzbagPbhagl911:[9157]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 100 ERFREIBVE EQ FHVGR: EZ 203 FG PYNVEFIVYYR ORGJRRA WBUARG QE / UNEORY (F BHGU) QE PBZZRAGF: SRZNYR CG VAWHEVRF SEBZ SNYY

 // ************************ CNEFR SNVYHER *****************************
 // OryzbagPbhagl911:[9163]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 1032 UBJNEQ FG F HVGR: NCG Q OEVQTRCBEG ORGJRRA CVAR FG / PRQNE FG PBZZRAGF: +040.067600 -080.756507 63 LB ZNYR TRARENY VYYARFF

     qbGrfg("G47",
         "OryzbagPbhagl911:[9157]-- - Angher: ZRQVPNY RZRETRAPL - Ybpngvba: 72610.00 HAVGL PUHEPU EQ JURRYVAT GJC - Pbzzragf: ZNYR YNLVAT VA GUR EBNQJNL, HAERFCBAFVIR",
         "PNYY:OryzbagPbhagl911:[9157]-- - Angher: ZRQVPNY RZRETRAPL",
         "NQQE:72610 HAVGL PUHEPU EQ",
         "NCG:JURRYVAT GJC",
         "VASB:ZNYR YNLVAT VA GUR EBNQJNL, HAERFCBAFVIR");

 // ************************ CNEFR SNVYHER *****************************
 // OryzbagPbhagl911:[9157]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 72610 HAVGL PUHE PU EQ JURRYVAT GJC ORGJRRA THA PYHO EQ / DHVAAF JNL PBZZRAG F: ZNYR YNLVAT VA GUR EBNQJNL, HAERFCBAFVIR

 // ************************ CNEFR SNVYHER *****************************
 // OryzbagPbhagl911:[9110]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 1104 UBJNEQ FG O EVQTRCBEG ORGJRRA PRQNE FG / QRNQ RAQ PBZZRAGF: ZNYR CNGVRA G, CBFFVOYR PBAPHFFVBA

     qbGrfg("G50",
         "OryzbagPbhagl911:[9139]-- - Angher: ZRQVPNY RZRETRAPL - Ybpngvba: 287.00 F PURFGAHG FG ONEARFIVYYR - Pbzzragf: SRZNYR OYRRQVAT PNHFR HAXABJA",
         "PNYY:OryzbagPbhagl911:[9139]-- - Angher: ZRQVPNY RZRETRAPL",
         "NQQE:287 F PURFGAHG FG",
         "PVGL:ONEARFIVYYR",
         "VASB:SRZNYR OYRRQVAT PNHFR HAXABJA");

     qbGrfg("G51",
         "OryzbagPbhagl911:[9139]-- - Angher: ZRQVPNY RZRETRAPL - Ybpngvba: 58545.00 YBJRE FNAQL EVQTR EQ JNLAR GJC - Pbzzragf: 45 L/B ZNYR FRIRER PURFG CNVA GBZ QBGL ERFVQRAPR",
         "PNYY:OryzbagPbhagl911:[9139]-- - Angher: ZRQVPNY RZRETRAPL",
         "NQQE:58545 YBJRE FNAQL EVQTR EQ",
         "NCG:JNLAR GJC",
         "VASB:45 L/B ZNYR FRIRER PURFG CNVA GBZ QBGL ERFVQRAPR");

     qbGrfg("G52",
         "OryzbagPbhagl911:[9159]-- - Angher: ZBGBE IRUVPYR PENFU - Ybpngvba: 702.00 R ZNVA FG ONEARFIVYYR - Pbzzragf: HAXABJA VAWHEVRF / RAGENCZRAG [ CQ BAFPRAR",
         "PNYY:OryzbagPbhagl911:[9159]-- - Angher: ZBGBE IRUVPYR PENFU",
         "NQQE:702 R ZNVA FG",
         "PVGL:ONEARFIVYYR",
         "VASB:HAXABJA VAWHEVRF / RAGENCZRAG [ CQ BAFPRAR");

 // ************************ CNEFR SNVYHER *****************************
 // OryzbagPbhagl911:[9159]- ANGHER: ZBGBE IRUVPYR PENFU YBPNGVBA: 702 R ZNVA FG ONEARFIVYYR ORGJRRA TENPR NI / ORGURFQN FG PBZZRAGF: HAXABJ A VAWHEVRF / RAGENCZRAG

     qbGrfg("G54",
         "OryzbagPbhagl911:[9139]-- - Angher: ZRQVPNY RZRETRAPL - Ybpngvba: 68207.00 PBZZREPVNY QE Fhvgr:NCG 3P CRNFR GJC - Pbzzragf: 92 L/B S CBFFVOYR FGEBXR 20:59---2AQ GBARF NQQ RZG",
         "PNYY:OryzbagPbhagl911:[9139]-- - Angher: ZRQVPNY RZRETRAPL",
         "NQQE:68207 PBZZREPVNY QE",
         "NCG:3P CRNFR GJC",
         "VASB:92 L/B S CBFFVOYR FGEBXR 20:59---2AQ GBARF NQQ RZG");

     qbGrfg("G55",
         "OryzbagPbhagl911:[9139]-- - Angher: ZRQVPNY RZRETRAPL - Ybpngvba: 68207.00 PBZZREPVNY QE Fhvgr:NCG 3P CRNFR GJC - Pbzzragf: 92 L/B S CBFFVOYR FGEBXR",
         "PNYY:OryzbagPbhagl911:[9139]-- - Angher: ZRQVPNY RZRETRAPL",
         "NQQE:68207 PBZZREPVNY QE",
         "NCG:3P CRNFR GJC",
         "VASB:92 L/B S CBFFVOYR FGEBXR");

     qbGrfg("G56",
         "OryzbagPbhagl911:[9139]-- - Angher: ZRQVPNY RZRETRAPL - Ybpngvba: 68014.00 PBZZREPVNY QE Fhvgr:NCG 9T CRNFR GJC - Pbzzragf: +040.070486 -080.779381 49 L/B S CBFFVOYR XVQARL FGBARF",
         "PNYY:OryzbagPbhagl911:[9139]-- - Angher: ZRQVPNY RZRETRAPL",
         "NQQE:68014 PBZZREPVNY QE",
         "NCG:9T CRNFR GJC",
         "VASB:+040.070486 -080.779381 49 L/B S CBFFVOYR XVQARL FGBARF");

     qbGrfg("G57",
         "OryzbagPbhagl911:[9167]-- - Angher: ZRQVPNY RZRETRAPL - Ybpngvba: 50890.00 ANGVBANY EQ EVPUYNAQ GJC - Pbzzragf: +040.076913 -080.868387 SRZNYR FRVMHER",
         "PNYY:OryzbagPbhagl911:[9167]-- - Angher: ZRQVPNY RZRETRAPL",
         "NQQE:50890 ANGVBANY EQ",
         "NCG:EVPUYNAQ GJC",
         "VASB:+040.076913 -080.868387 SRZNYR FRVMHER");

     qbGrfg("G58",
         "OryzbagPbhagl911:[9167]-- - Angher: ZRQVPNY RZRETRAPL - Ybpngvba: 319.00 F ZNVA FG Fhvgr:YBG 22 ORGURFQN - Pbzzragf: 34 L/B SRZNYR NYGRERQ ZRAGNY FGNGHF",
         "PNYY:OryzbagPbhagl911:[9167]-- - Angher: ZRQVPNY RZRETRAPL",
         "NQQE:319 F ZNVA FG",
         "NCG:YBG-22",
         "PVGL:ORGURFQN",
         "VASB:34 L/B SRZNYR NYGRERQ ZRAGNY FGNGHF");

     qbGrfg("G59",
         "OryzbagPbhagl911:[9137]-- - Angher: FGEHPGHER SVER - Ybpngvba: 71021.00 ONEGBA EQ PBYRENVA GJC - Pbzzragf: JNF PBAGEBYYRQ OHEA FGNEGVAT GB ZRYG FVQVAT BA GUR UBHFR.",
         "PNYY:OryzbagPbhagl911:[9137]-- - Angher: FGEHPGHER SVER",
         "NQQE:71021 ONEGBA EQ",
         "NCG:PBYRENVA GJC",
         "VASB:JNF PBAGEBYYRQ OHEA FGNEGVAT GB ZRYG FVQVAT BA GUR UBHFR.");

     qbGrfg("G60",
         "OryzbagPbhagl911:[9169]-- - Angher: FGEHPGHER SVER - Ybpngvba: 71021.00 ONEGBA EQ PBYRENVA GJC - Pbzzragf: JNF PBAGEBYYRQ OHEA FGNEGVAT GB ZRYG FVQVAT BA GUR UBHFR.",
         "PNYY:OryzbagPbhagl911:[9169]-- - Angher: FGEHPGHER SVER",
         "NQQE:71021 ONEGBA EQ",
         "NCG:PBYRENVA GJC",
         "VASB:JNF PBAGEBYYRQ OHEA FGNEGVAT GB ZRYG FVQVAT BA GUR UBHFR.");

 // ************************ CNEFR SNVYHER *****************************
 // OryzbagPbhagl911:[9167]- ANGHER: ZBGBE IRUVPYR PENFU YBPNGVBA: R PNCGVAN UJL / CVARYBPXR QE LBEX GJC PBZZRAGF: 1 VAWHEL AB RAGENCZRAG

 // ************************ CNEFR SNVYHER *****************************
 // OryzbagPbhagl911:[9167]- ANGHER: ZBGBE IRUVPYR PENFU YBPNGVBA: R PNCGVAN UJL / CVARYBPXR QE LBEX GJC PBZZRAGF: YVARF QBJA BA GUR IRUVPYR . HAXABJA VAWHEVRF. AB RAGENCZRAG

 // ************************ CNEFR SNVYHER *****************************
 // OryzbagPbhagl911:[9167]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 65975 J RPUB EQ CHYGARL GJC ORGJRRA RPUB EQ / QRNQ RAQ PBZZRAGF: ZNYR JVGU NA VASRPGRQ SVATRE

 // ************************ CNEFR SNVYHER *****************************
 // OryzbagPbhagl911:[9167]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 71395 PERFPRAG E Q PBYRENVA GJC ORGJRRA PERFPRAG-ONEGBA EQ / PRAGRE FG PBZZR AGF: 44 L/B SRZNYR NYYRETVP ERNPGVBA GB ZRQVPNGVBA

 // ************************ CNEFR SNVYHER *****************************
 // OryzbagPbhagl911:[9167]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 71395 PERFPRAG E Q PBYRENVA GJC ORGJRRA PERFPRAG-ONEGBA EQ / PRAGRE FG PBZZR AGF: 44 L/B SRZNYR NYYRETVP ERNPGVBA GB ZRQVPNGVBA FRPBAQ G BAR

 // ************************ CNEFR SNVYHER *****************************
 // OryzbagPbhagl911:[9167]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 68222 PBZZREPVNY QE FHVGR: YBHTR CRNFR GJC ORGJRRA ORYZBAG NI / EBPX YA PBZ ZRAGF: 76 L/B HAERFCBAFVIR, VF OERNGUVAT. ULCBGRAFVBA

 // ************************ CNEFR SNVYHER *****************************
 // OryzbagPbhagl911:[9167]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 68222 PBZZREPVNY QE CRNFR GJC ORGJRRA ORYZBAG NI / EBPX YA PBZZRAGF: 76 L/B HAERFCBAFVIR, VF OERNGUVAT. ULCBGRAFVBA

 // ************************ CNEFR SNVYHER *****************************
 // OryzbagPbhagl911:[9167]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 65 J 47 FG FHVGR : NCG 7 FUNQLFVQR ORGJRRA PRAGENY NI / WRSSREFBA NI PBZZRAG F: 38 L/B SRZNYR NOQBZVANY CNVA

 // ************************ CNEFR SNVYHER *****************************
 // OryzbagPbhagl911:[9167]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 66680 RKRPHGVIR QE EVPUYNAQ GJC ORGJRRA F FRIRAGL EQ / CBTHR EQ PBZZRAGF: 3 0 L/B ZNYR VAWHEVRF SEBZ SNYY CBFF HAERFCBAFVIR.

 // ************************ CNEFR SNVYHER *****************************
 // OryzbagPbhagl911:[9167]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 4800 PRAGENY NI FHVGR: YBG 5 FUNQLFVQR ORGJRRA R 46GU FG / J 46GU FG PBZZRA GF: +039.973497 -080.765626 72 L/B SRZNYR UVTU GRZC

 // ************************ CNEFR SNVYHER *****************************
 // OryzbagPbhagl911:[9167]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 608 JVYRL NI ONE ARFIVYYR ORGJRRA UHGPUVAFBA NI / ARIN NI PBZZRAGF: ZNYR YRT CNVA

 // ************************ CNEFR SNVYHER *****************************
 // OryzbagPbhagl911:[9167]- ANGHER: FREIVPR PNYY YBPNGVBA: NVECBEG EQ / OEHFU EH A EQ EVPUYNAQ GJC PBZZRAGF: GEHPX YRNXVAT QVRFRY NSGRE N ZVA BE NPPVQRAG

 // ************************ CNEFR SNVYHER *****************************
 // OryzbagPbhagl911:[9166]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 63240 FNAQ UVYY EQ CHYGARL GJC ORGJRRA NYGREANGR FNAQ UVYY NCCEBNPU / GEBHT U EHA EQ PBZZRAGF: SRZNYR CG FLAPBCNY RCVFBQR

 // ************************ CNEFR SNVYHER *****************************
 // OryzbagPbhagl911:[9159]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 62650 QHFGL YA J NEERA GJC ORGJRRA ONEARFIVYYR ORGURFQN EQ / QRNQ RAQ PBZZRA GF: 62 L/B SRZNYR TRARENY VYYARFF

     qbGrfg("G75",
         "OryzbagPbhagl911:[9139]-- - Angher: ZRQVPNY RZRETRAPL - Ybpngvba: 65229.00 ZP ZVYYNA EQ HAVBA GJC - Pbzzragf: URNQ VAWHEVRF SEBZ NA NFFNHYG",
         "PNYY:OryzbagPbhagl911:[9139]-- - Angher: ZRQVPNY RZRETRAPL",
         "NQQE:65229 ZP ZVYYNA EQ",
         "NCG:HAVBA GJC",
         "VASB:URNQ VAWHEVRF SEBZ NA NFFNHYG");

     qbGrfg("G76",
         "OryzbagPbhagl911:[9139]-- - Angher: IRUVPYR SVER (SQ) - Ybpngvba: 65711.00 J RPUB EQ CHYGARL GJC - Pbzzragf: IRUVPYR BA SVER ARKG GB ERFVQRAPR",
         "PNYY:OryzbagPbhagl911:[9139]-- - Angher: IRUVPYR SVER (SQ)",
         "NQQE:65711 J RPUB EQ",
         "NCG:CHYGARL GJC",
         "VASB:IRUVPYR BA SVER ARKG GB ERFVQRAPR");

 // ************************ CNEFR SNVYHER *****************************
 // OryzbagPbhagl911:[9123]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 68040 ZNYY EVAT EQ EVPUYNAQ GJC ORGJRRA ZNYY EQ / ZNYY EQ PBZZRAGF: ZNYR PU BPVAT ....FBZRGUVAT YBQTRQ VA GUR GUEBNG

 // ************************ CNEFR SNVYHER *****************************
 // OryzbagPbhagl911:[9159]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 228 ZNVA FG OEVQ TRCBEG ORGJRRA NYYRA FG / BYQ PNQVM EQ PBZZRAGF: ZNYR VAGBK VPNGRQ

     qbGrfg("G79",
         "OryzbagPbhagl911:[9139]-- - Angher: ZRQVPNY RZRETRAPL - Ybpngvba: 55707.00 VAQHFGEVNY QE CRNFR GJC - Pbzzragf: ZNA YLVAT VA GUR FGERRG HAXABJA VAWHEVRF",
         "PNYY:OryzbagPbhagl911:[9139]-- - Angher: ZRQVPNY RZRETRAPL",
         "NQQE:55707 VAQHFGEVNY QE",
         "NCG:CRNFR GJC",
         "VASB:ZNA YLVAT VA GUR FGERRG HAXABJA VAWHEVRF");

 // ************************ CNEFR SNVYHER *****************************
 // OryzbagPbhagl911:[9157]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 66895 TENUNZ EQ EVPUYNAQ GJC ORGJRRA EBOREGB QE / NAAN QE PBZZRAGF: +040.05 4961 -080.880146 SRZNYR CG PBZCYVPNGVBAF SEBZ FHETREL

 // ************************ CNEFR SNVYHER *****************************
 // OryzbagPbhagl911:[9157]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 3479 PRAGENY NI FUNQLFVQR ORGJRRA RYX NI / R 35GU FG PBZZRAGF: PNYYRE FGNGR F UVF JVSR GBBX CVYYF, FUR YVIRF NG GUR SVEFG NCNEGZRAGF PBZ VAT VAGB GBJA BA GUR EVTUG URE ANZR VF OER

 // ************************ CNEFR SNVYHER *****************************
 // OryzbagPbhagl911:[9157]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 50813 INYYRL CYN MN QE EVPUYNAQ GJC ORGJRRA INYYRL PRAGER OYIQ / QVRGEN YA P BZZRAGF: SRZNYR CG QVSSVPHYGL OERNGUVAT

     qbGrfg("G83",
         "OryzbagPbhagl911:[9137]-- - Angher: ZBGBE IRUVPYR PENFU - Ybpngvba: 54750.00 ANGVBANY EQ PBYRENVA GJC - Pbzzragf: +040.061388 -080.752215",
         "PNYY:OryzbagPbhagl911:[9137]-- - Angher: ZBGBE IRUVPYR PENFU",
         "NQQE:54750 ANGVBANY EQ",
         "NCG:PBYRENVA GJC",
         "VASB:+040.061388 -080.752215");

 // ************************ CNEFR SNVYHER *****************************
 // OryzbagPbhagl911:[9137]- ANGHER: ZBGBE IRUVPYR PENFU YBPNGVBA: 54750 ANGVBANY EQ PBYRENVA GJC ORGJRRA ORNEVAT EQ / PUREZBAG EQ PBZZRAGF: +040.061388 -080.752215

     qbGrfg("G85",
         "OryzbagPbhagl911:[9137]-- - Angher: ZBGBE IRUVPYR PENFU - Ybpngvba: 208.00 V-70 R HAVBA GJC - Pbzzragf: PNE IF FRZV GEHPX ZIP ...HXABJA VAWHEVRF",
         "PNYY:OryzbagPbhagl911:[9137]-- - Angher: ZBGBE IRUVPYR PENFU",
         "NQQE:208 V-70 R",
         "ZNQQE:208 V 70 R",
         "NCG:HAVBA GJC",
         "VASB:PNE IF FRZV GEHPX ZIP ...HXABJA VAWHEVRF");

 // ************************ CNEFR SNVYHER *****************************
 // OryzbagPbhagl911:[9123]- ANGHER: ZBGBE IRUVPYR PENFU YBPNGVBA: 208 V-70 R HAV BA GJC PBZZRAGF: PNE IF FRZV GEHPX ZIP ...HXABJA VAWHEVRF

     qbGrfg("G87",
         "OryzbagPbhagl911:[9137]-- - Angher: ZBGBE IRUVPYR PENFU - Ybpngvba: 208.00 V-70 R HAVBA GJC - Pbzzragf: PNE IF FRZV GEHPX",
         "PNYY:OryzbagPbhagl911:[9137]-- - Angher: ZBGBE IRUVPYR PENFU",
         "NQQE:208 V-70 R",
         "ZNQQE:208 V 70 R",
         "NCG:HAVBA GJC",
         "VASB:PNE IF FRZV GEHPX");

 // ************************ CNEFR SNVYHER *****************************
 // OryzbagPbhagl911:[9157]- ANGHER: ZRQVPNY RZRETRAPL YBPNGVBA: 51660 TYRAPBR-FG RJNEGFIVYYR EQ EVPUYNAQ GJC ORGJRRA FPRAVP IVRJ EQ / OELXNY FXV QE PBZZRAGF: SRZNYR CG UNF SNYYRA

  }
  
  choyvp fgngvp ibvq znva(Fgevat[] netf) {
    arj BUOryzbagPbhaglCnefreGrfg().trarengrGrfgf("G1");
  }
}