cnpxntr arg.narv.pnqcntr.cnefref.BU;

vzcbeg arg.narv.pnqcntr.cnefref.OnfrCnefreGrfg;

vzcbeg bet.whavg.Grfg;

/*
Phlnubtn Pbhagl, BU
Pbagnpg: Npgvir911
Ntrapl anzr: Punteva Snyyf Sver Qrcg.
Ybpngvba: Punteva Snyyf, BU, Havgrq Fgngrf
Fraqre: qvfcngpu@puntevasnyyfcq.pbz

(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e308  SBK JNL     \ePHG JEVFG 
(Qvfcngpu Zrffntr) ZIN \a123  SNVEIVRJ QE    F EHFFRYY \aRYQREYL SRZNYR VAIBYIRQ VA YBJ FCRRQ ZIN
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e35952  FBYBA EQ    ORAGYRLIVYYR \eZNYR CVAARQ ORGJRRA GERR NAQ EVQVAT ZBJRE, NQVIFRQ ABG VAWHERQ 
(Qvfcngpu Zrffntr) ZIN \a ERDHRFGRQ FDHNQ NVE ONT QRCYBLZRAG, \a 
(Qvfcngpu Zrffntr) ZIN \e  PUVYYVPBGUR EQ    F EHFFRYY \eTPFB NQIVFRQ IRUVPYR ( TEL INA) VA GUR QVGPU, AB VAWHEVRF 
(Qvfcngpu Zrffntr) OBK 100  \e  UVENZ GEY    PUNTEVA SNYY \eERDHRFGRQ OL BP3 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e200  UNZYRG UVYYF QE  123  PUNTEVA SNYY \eRYQREYL SRZNYR SRYY, HAVAWHERQ 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e150  XRAFVATGBA PVE    F EHFFRYY \eFRVIREF FRPHEVGL  216-383-1234 BCE/ WRFFVPN\aZRQVPNY NYNEZ 
(Qvfcngpu Zrffntr) SVER- TRARENY \e  PBL YA    PUNTEVA SNYY \eTNENTR FZBXVAT VA GUR ERNE BS GUR UBHFR ARKG QBBE 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e70  EVIRE FGBAR QE    ZBERYNAQ UVY \eRYQREYL SRZNYR SRYY CBFFVOYR VAWHERQ NEZ 
(Qvfcngpu Zrffntr) NAVZNY- ZVFP. \e83  ZNCYR FG   \eQBT FGHPX HAQRE PNE 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e3841  JVYGFUVER EQ    ZBERYNAQ UVY \eZNYR JVGU CNEXVAFBAF ARRQF GB OR GENAFCBEGRQ 
(Qvfcngpu Zrffntr) ZIN-CRQRFG.VAWHEL  \e98  A ZNVA FG    PUNTEVA SNYY \eSRZNYR FGEHPX OL IRUVPYR 
(Qvfcngpu Zrffntr) NYNEZF-SVER  \e2657  PUNTEVA EVIRE    UHAGVAT INYY \eNPPRFF CEBGRPGVIR 800.498.7565\aVAQ/CHYY FGNGVBA \aBCE/EVNFUVNU 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e5192  PUVYYVPBGUR EQ    F EHFFRYY \e46 LE BYQ SRZNYR, NOQBZVANY CNVA 
(Qvfcngpu Zrffntr) NYNEZF-PB QRGRPGBE  \e1584  ORYY FG    F EHFFRYY \ePB QRGRPGBEF VA GUR ONFRZRAG NER FBHAQVAT 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e245  FCEVATQNYR YA    ZBERYNAQ UVY \e83 LEB SRZNYR URNEG CEBOYRZ NAQ SRRYVAT SNVAG 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e200  UNZYRG UVYYF QE  307  PUNTEVA SNYY \eVAINYVQ NFFVFG ARRQRQ BA ZNYR CNEGL 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e25  CYRNFNAG QE   PUNTEVA SNYY \eRYQREYL SRZNYR HAERFCBAFVIR, OERNGUVAT 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e200  UNZYRG UVYYF QE  310  PUNTEVA SNYY \eHAXABJA ZRQVPNY, FDHNQ ERDHRFGRQ OL ERFVQRAG 
(Qvfcngpu Zrffntr) NYNEZF-ZRQVPNY  \a16  SBERFG QE    F EHFFRYY \ayvsryvar frp 888 289 2018 UVFGBEL BS SNYYVAT BCE/WNAR 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e47  CNJ CNJ YNXR QE    F EHFFRYY \eSRZNYR JNF PUBXVAT, FUR VF ABJ UNIVAT GEBHOYR OERNGUVAT 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e36030  PUNTEVA OYIQ    ZBERYNAQ UVY \eHAERFCBAFVIR SRZNYR 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e400  R JNFUVATGBA FG   PUNTEVA SNYY \eUVG VA SNPR J ONYY PBA/OERNGU 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e305  R JNFUVATGBA FG   PUNTEVA SNYY \e84 LE BYQ SRZNYR .,CBFFVOYR FGEBXR 
(Qvfcngpu Zrffntr) NYNEZF-SVER  \e40  YNHERY PBHEG   ZBERYNAQ UVY \eFGNAYRL FRPHEVGL\aBCE : ZRTNA\a216-361-1050\aVAQ : PYRIRYNAQ EBBZ 
(Qvfcngpu Zrffntr) FDHNQ PNYY\a200  UNZYRG UVYYF QE  217  \aRYQREYL SRZNYR SRYY BHG BS ORQ\aARRQF NFFVFGNAPR TRGGVAT HC 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e205  UNZYRG UVYYF QE  75  PUNTEVA SNYY \eSRZNYR SRYY QVMML 
(Qvfcngpu Zrffntr) ZHGHNY NVQ, TVIRA  \a6025  XEHFR QE    PUNTEVA SNYY \aFBYBA SQ ERDHRFGRQ N YNQQRE GEHPX  
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \eR JNFUVATGBA FG & EVQTRJBBQ    PUNTEVA SNYY \eZNYR SRYY BSS OVXR NAQ ABG ZBIVAT 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e116  PBHAGELFVQR    F EHFFRYY \eANHFRN, FJRNGF NAQ QVMML, SRZNYR VF FGVYY OERNGUVAT , PBAFPVBHF 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e102  YNHERY EQ   F EHFFRYY \eSRZNYR VA URE 90'F, UNF SNYYRA N PBHCYR BS GVZRF, PBAFGNAG CNVA 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \a\aVAQ/ ERQ URYC OHGGBA CERFFRQ, AB ERFCBAFR SEBZ 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e5188  PUVYYVPBGUR EQ   F EHFFRYY \e35 LE BYQ ZNYR JVGU PURFG CNVAF  FVGGVAT VA N PURIL INA 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e35  UVTU PBHEG   PUNTEVA SNYY \eRYQREYL ZNYR IBZVGVAT & OYBBQL FGBBY 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e31  FBHGU FG    PUNTEVA SNYY \eSRZNYR QVFBEVRAGRQ 
(Qvfcngpu Zrffntr) TNF BQBE  \e32605  WNPXFBA EQ    ZBERYNAQ UVY \eIRUPVYR ENA BIRE TNF ZRGRE TNF VF VA GUR NVE 
(Qvfcngpu Zrffntr) ZIN-VAWHEL \e5000  PUNTEVA EVIRE    ZBERYNAQ UVY \eCRE NAQL JRVATNEG 440 623 9069 CBEF VAGB N THNEQ ENVY 
(Qvfcngpu Zrffntr) NFFVFG-SVER QRCNEGZRAG  \e  R JNFUVATGBA FG    PUNTEVA SNYY \eNG EVQTRJBBQ SBE N CBFFVOYR SHRY FCVYY 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e551  R JNFUVATGBA FG   F EHFFRYY \e84LBZ ERPGNY OYRRQ, FRIRER FGBZNPU CNVA 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e34114  PUNTEVA OYIQ  8106 \eRYQREYL ZNYR SRYY NAQ VF OYRRQVAT  PBA/OERNGU 
(Qvfcngpu Zrffntr) NYNEZF-SVER \e35  GNEGNA PG  \eTVYZBER FRPHEVGL BCE/50  440-232-6458\aVAQ/ TRARENY 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e40  JUVGRGNVY YNAR   \eZNYR SRYY BSS FXNGR OBNEQ\aOYRRQVAT SEBZ URNQ\aNAAVR 440-552-9766 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e41  JUVGRGNVY YNAR   \eZNYR SRYY BSS FXNGR OBNEQ\aOYRRQVAT SEBZ URNQ 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e38879  OREXRYRL NIR   \e88 LRNE BYQ SRZNYR SRYY BA GUR CNGVB UVG URE URNQ 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e33001  FBYBA EQ  202 \eZHGHNY NVQ SBE FBYBA 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e551  R JNFUVATGBA FG  \e44 lrne byq znxr purfg cnvaf ngevny syhggre 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e551  R JNFUVATGBA FG  \eZNYR PURFG CNVAF 
(Qvfcngpu Zrffntr)  \e49  J BENATR FG   \e27 LBN SRZNYR UNIVAT N FRVMHER 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e111  UNZYRG UVYYF QE  22 \eRYQREYL ZNYR PNGU CEBOYRZF 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e551  R JNFUVATGBA  \eSRZNYR CBFFVOYR URNEG NGGNPX VA GUR HETRAG PNER 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e21  J JNFUVATGBA FG  \eZNYR JVGU PURFG CNVAF 
(Qvfcngpu Zrffntr)  \a200  UNZYRG UVYYF QE  \aZRQVPNY RZRETRAPL\aZHGHNY NVQ  SEBZ ONVAOEVQTR SQ 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e200  UNZYRG UVYYF QE  \eRYQREYL  ZNYR UNIVAT YRT CNVA, PBAFPVBHF NAQ OERNGUVAT 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e108  SNVEIVRJ EQ   \e 86 ryqreyl srznyr qvmml hanoyr gb or fgrnql ba ure srrg 
(Qvfcngpu Zrffntr) TNF BQBE \e45  FGREAPERFG QE   \eVYYHZVANGVAT PB ERCBEG GB BISQ N FZRYY BS ANGHENY TNF SEBZ GUR NOBIR YBPNGVBA 
(Qvfcngpu Zrffntr) SVER- TRARENY \e6005  CNEXYNAQ QE   \eTNF TEVYY HANOYR GB OR GHEARQ BSS, ANGHENY TNF TEVYY VF ARNE GUR UBHFR 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e40  SNEJBBQ QE   \eUNIVAT GEBHOYR OERNGUVAT\a 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e200  UNZYRG UVYYF QE  109 \eRYQREYL SRZNYR SRRYVAT AHZO 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e85  JVYYBJ JBBQ YA   \eRYQREYL SRZNYR UVC VAWHEL 
(Qvfcngpu Zrffntr) SVER- TRARENY \e100  A ZNVA FG  \eYVTUG VA PRVYVAT PNHTUG BA SVER VF ABJ BHG 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \a31  FBHGU FG   \aSRZNYR CNFFRQ BHG ABJ PBAFPVBHF, UVTU OYBBQ CERFFHER
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e200  UNZYRG UVYYF QE  213 \eZNYR JUB UNF SNYYRA 
(Qvfcngpu Zrffntr) NYNEZF-PB QRGRPGBE \e65  BYVIR FG   \eNYNEZ ERNQVAT TNF NYNEZ, AB FLZCGBZF RINPHNGRQ 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e20  FGBARJBBQ QE  \eRYQREYL SRZNYR CBFFVOYR URNEG NGGNPX 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e200  UNZYRG UVYYF QE  221 \eSRZNYR YRT CNVA 
(Qvfcngpu Zrffntr) NYNEZF-SVER \e1082  ORYY EQ  \eRAGEL THNEQ 2800-443-8865\aVAQ/TRA SVER \aBCE/412 
(Qvfcngpu Zrffntr) OBK 100 \eFBZ PRAGRE EQ  UVENZ GEY   \eBISQ ERDHRFGRQ OBK 100 ZNONF NYNEZ 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e551  R JNFUVATGBA FG  \eOYBBQ PYBG VA URE YRT & CBFFVOYR VA GUR YHATF, OERNGUVAT & PBAPVBHF 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e115  NFCRAJBBQ QE  \e85 LE BYQ ZNYR , FRIRER NOQBZVANY CNVA SEBZ N UREAVN 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e FDHNJ EBPX  \eSRZNYR VA CNEXVAT YBG JVGU SNPR VAWHEL 
(Qvfcngpu Zrffntr) SVER- TRARENY \e36850  PUNTEVA OYIQ   \eSVFU GNAX PNHTUG SVER\aSVER VF RKGVATHVFURQ \aUBHFR SHYY BS FZBXR 
(Qvfcngpu Zrffntr) NFFVFG-SVER QRCNEGZRAG \e40  SNEJBBQ QE   \eYNZC VF ZNXVAT N ABVFRt 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e206  UNZYRG UVYYF QE  89 \eZNYR ERFVQRAG UNF SNYYRA 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e125  ZHEJBBQ QE   \e87 LEB SRZNYR , PBATRFGVIR URNEG SNVYHER, HAERFCBAFVIR 
(Qvfcngpu Zrffntr) ZHGHNY NVQ, TVIRA \e13665  NDHVYYN EQ   \eOHEGBA SQ NPGVINGVAT GUR TRNHTN CBEGNTR JNGRE FUHGGYR SBE N UBHFR SVER 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e102  YRNIVRJ YA   \e71 LEB ZNYR SRYY NAQ VF OYRRQVAT SEBZ UVF UNAQ NAQ NOBIR GUR RLR 
(Qvfcngpu Zrffntr) NYNEZF-SVER \e6000  ABO UVYY QE   \eSVER NYNEZ FBHAQVAT 
(Qvfcngpu Zrffntr) NYNEZF-ZRQVPNY \a157  PNEEVNTR QE  103 \aHANOYR GB ZNXR PBAGNPG JVGU CNGVRAG 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e  ORYY GBJRE PG   \eSRZNYR OEBXRA NAXYR, ZRRG NG ONPX BS PBAQBF ARNE SRAPR 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e40  R JNFUVATGBA FG   \eRYQREYL UNF SNYYRA OYRRQVAT SEBZ GUR URNQ 
(Qvfcngpu Zrffntr)  \e35550  SNVEZBHAG OYIQ   \e91 LBN ZNYR SRYY UVG URNQ. OYRRQVAT SEBZ URNQ NAQ UNAQ 
(Qvfcngpu Zrffntr) PBZCYNVAGF-TRARENY \aORYY FG  ZNVA FG   \aZNYR HAPBA FDHNQ ERDHRFG 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e45  R WHAVCRE YA   \eRINYHNGVBA BA N 46 LBN SRZNYR 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \a36400  F JBBQYNAQ EQ   \aPNYYRE NQIVFRQ GUR GENPGBE SYVCCRQ BIRE BA EVQRE
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \a200  UNZYRG UVYYF QE  201 \aPNER PRAGRE\aBCE : 451 \a800-508-6370\a87 LE BYQ SRZNYR UNF SNYYRA ,
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e604  QBR PG   \e15 le byq srznyr frzv pbapvbf, oernguvat 
(Qvfcngpu Zrffntr) FHFCVPVBA \e395  ORYY FG   \eVAGBK ZNYR VA OBBXVAT 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e EVIREFVQR CNEX  \eZNYR CNFFRQ BHG 

Pbagnpg: Npgvir911
Ntrapl anzr: Benatr Ivyyntr Sver Qrcnegzrag
Ybpngvba: Benatr Ivyyntr, BU, Havgrq Fgngrf
Fraqre: qvfcngpu@puntevasnyyfcq.pbz

(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e  271    BENATR \eNFFVFGVAT QVFNOYRQ CEVINGR NOHYNAPR FREIVPR\aJVGU N GENAFCBEG 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e3909  BENATR CYNPR   BENATR \e60 LE BYQ SRZNYR CBFFVOYR FGEBXR VA GUR HETRAG PNER 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e3909  BENATR CYNPR   BENATR \eZNYR OYBBQ PYBG VA UVF YHATF 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e3909  BENATR CYNPR  1100  BENATR \e60LBS ULCBGRAFVIR 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e3909  BENATR CYNPR   BENATR \e79 LE BYQ SRZNYR , PURFG CNVAF VA GUR HETRAG PNER 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e28149  ZVYRF EQ   BENATR \eSRZNYR ABG SRRYVAT JRYY, QVNORGVP ABG SRRYVAT 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e3809  JNYAHG UVYYF EQ    BENATR \e60 LBN ZNYR JRNX NAQ IBZVGVAT 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e3909  BENATR CYNPR  2400  BENATR \e55 LE BYQ SRZNYR, FUBEGARFF BS OERNGU 
(Qvfcngpu Zrffntr) NFFVFG-SVER QRCNEGZRAG  \e3920  JVYQPUREEL GEY     \ecre br5 gurl ner raebhgr gb nobir sbe na bqbe vairfg 
(Qvfcngpu Zrffntr) ZIN \e4486  OENVANEQ EQ    BENATR \epne vagb cbyr qevire oyrrqvat 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \a3755  BENATR CYNPR  102  BENATR \aSRZNYR, FRIRER CNVA VA YRSG YRT 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e28850  UNEINEQ EQ    BENATR \eCUFL RINY 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e27500  RZREL EQ    BENATR \eznyr abg oernguvat 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e205  UNZYRG UVYYF QE  75  PUNTEVA SNYY \eSRZNYR SRYY QVMML 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e29600  PUNTEVA OYIQ   BENATR \eSRZNYR JVGU YBJ OYBBQ CERFFHER 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e3909  BENATR CYNPR   BENATR \eHETRAG PNER / SRZNYR JVGU PURFG CNVAF 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e3909  BENATR CYNPR   BENATR \eZNYR VA FREIRER CNVA SEBZ NA ZIN 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e4120  YNAQRE EQ     \eCBFFVOYR QBN 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e3909  BENATR CYNPR   BENATR \eFHVGR 3300\aSRZNYR YBJ OC, UNQ CNFFRQ BHG 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e29600  PUNTEVA OYIQ   BENATR \eSRZNYR UNQ N CYNGR SNYY BA URE SBBG, VG VF FGNEGVAT GB FJRYY 
(Qvfcngpu Zrffntr) NYNEZF-SVER \e4009  BENATR CYNPR  \eFGNAYRL FRPHEVGL  8006894984  BC:195\aVAVQPNGVBA: MBAR 16 TRARENY JNGRE SYBJ NYNEZ 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e31599  JBBQPERFG QE   \eZNYR QVSSVPHYGL OERNGUVAT,FJRNGVAT 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e27099  RZREL EQ  \eQVS OERNGUVAT 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e3909  BENATR CYNPR  \eSRZNYR PURFG CNVAF  VA GUR HETRAG PNER 
(Qvfcngpu Zrffntr) SVER- TRARENY \e30600  RZREL EQ   \eFGENATR BQBE 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e3655  BENATR CYNPR  \e45 LBN ZNYR CNFFRQ BHG 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \a4709  YNAQRE EQ   \aRYQREYL ZNYR BHG BS JURRYPUNVE , FGREAPERFG FVQR QEVIRJNL
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e27500  RZREL EQ   \eZNYR FRIRE PENZCVAT 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e27500  RZREL EQ   \eZNYR FGBZNPU CNVAF 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e4600  YNAQRE EQ  \eVA BENATR IVYYNTR UNYY, ZNYR UNIVAT NA NYYRETVP ERNPGVBA 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e3909  BENATR CYNPR  2500 \e36 LE BYQ SRZNYR NOQBZVANY OYRRQVAT, PBAPVBHF & OERNGUVAT 
(Qvfcngpu Zrffntr) \a3909  BENATR CYNPR   \a78 LRNE BYQ ZRNY UVTU SRIRE NAQ UNIVAT GEBHOYR OERNGUAT
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e3909  BENATR CYNPR   \eQVFBEVRAGRQ SRZNYR VA GUR HETRAG PNER 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e3909  BENATR CYNPR  \e65 LE BYQ SRZNYR, NOABEZNY YNO, YRSG NEZ AHZOARFF 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \a3909  BENATR CYNPR  \a57 LRNE BYQ ZNYR PURFG CNVAF HETRAG PNER
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e29600  PUNTEVA OYIQ  \eSRZNYR UNF SNYYRA VA GUR QVAVAT EBBZ, HAXABJA VAWHEVRF 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e3909  BENATR CYNPR  3300 \eZNYR NYZBFG CNFFRQ BHG, CBFFVOYR YBJ TYHPBFR 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e3655  BENATR CYNPR  \eSRZNYR FVRMVAT VA GUR YBOOL 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e4545  OENVANEQ EQ  \e2 LE FRVMVAT 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e4189  YNAQRE EQ   \eYNHERA ZNEBGGN 216-570-5098\aCNVA VA FGBZNPU 
(Qvfcngpu Zrffntr) ZHGHNY NVQ, TVIRA \e3999  EVPUZBAQ EQ  \eZHGHNY NVQ ERDHRFGRQ SBE N CBFFVOYR SVER EBBZ 3222 TNEQRA YRIRY 
(Qvfcngpu Zrffntr) ZHGHNY NVQ, TVIRA \e70  ONFFJBBQ YA  \eNQG 888-294-6736\aVAQ/JNGRE SYBJ\aBCE/EBQTRE 
(Qvfcngpu Zrffntr) ZHGHNY NVQ, TVIRA \a32450  PURFGAHG   FZBXR VA ONFRZRAG\aGB FPRAR, SNVEZBHAG GB FABJOREEL GB PURFGAHG
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \a27250  RZREL EQ  \a FDHNQ NQIVFAT GURL NER CERCNEVAT GB GENAFBCBEG N ZNYR JVGUN  URNQ VAWHEL
(Qvfcngpu Zrffntr) NYNEZF-SVER \a3625  BENATR CYNPR  \aVAQ SVER NYNEZ.
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e4809  R SNVEIVRJ QE   \eRYQREYL SRZNYR OYBBQ CERFFHER VF IREL UVTU 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e28950  UNEINEQ EQ   \eSRNZYR CBFFVOYR FGEBXR 
(Qvfcngpu Zrffntr) NYNEZF-SVER \e4600  YNAQRE EQ  \ePNYY PBZZ\aBCE : OENAQBA\a800-498-7565\aVAQ : TRA SVER 
(Qvfcngpu Zrffntr) NYNEZF-ZRQVPNY \e28900  CVXR QE  \ePNER  PRAGRE 800-508-6370\aVAQ/PNAABG TRG HC/CBFFVOYR VAINYVQ NFFVFG\aBCE/230 
(Qvfcngpu Zrffntr) NYNEZF-PB QRGRPGBE \e270  OYBFFBZ YA  \eJBHYQ YVXR ERF PURPXRQ\aFGNGR 800 321 7400 BC/WRFFV 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \a28900  CVXR QE  \aGUR PNER PRAGRE\a800-508-6370\aRYQREYL SRZNYR UNF SNYYRA, ARRQF NFFVFGNAPR  
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e30549  UNEINEQ EQ   \eZNYR BA BKLTRA, QVSSVPHYGL OERNGUVAT 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e3909  BENATR CY   \e53 LBN SRZNYR  NYYRETVP ERNPGVBA HETRAG PNER 
(Qvfcngpu Zrffntr) VAGBK SRZNYR OYRRQVAT SEBZ GUR NEZ\aCQ BA FPRA
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \a27599  RZREL EQ   \aSRZNYR UNIVAT N UNEQ GVZR OERNGUVAT 
(Qvfcngpu Zrffntr) SVER- NHGB \e  271   \e271 AO RKCERFF YNARF, OBK GEHPX BA SVER 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e28940  UVQQRA INYYRL   \eYVSRYVAR 888.289.2018\aVAQ/SRZNYR ZRQVPNY RZRETRAPL\aBCE/YHPL\a 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e110  INYRAPVN PVE   \eSRZNYRF PNE EBYYRQ BIRE URE YRT 
(Qvfcngpu Zrffntr) NYNEZF-SVER \e150  OYBFFBZ YA   \eFGNGR NYNEZ 781 2224 VAQVPGVAT FZBXR QRGRPGBE FHO YBG 87 BCE/ORIREYL 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e29600  PUNTEVA OYIQ  \e91 le byq srznyr, sryy, fber. Znva pyho ubhfr. 
(Qvfcngpu Zrffntr) QBZRFGVP \e30200  FZVGUSVRYQ EQ   \eURE FBA VF IVBYRAG NAQ NGGNPXVAT URE UHFONAQ UR \a\a05/07/2013 20:47:10 Qvfc  ZYE  \aBSSVPREF UNIR ZNYR ERFGENVARQ NG GUVF 
(Qvfcngpu Zrffntr) ZHGHNY NVQ, TVIRA \e31200  RZREL EQ   \eZHGHNY NVQ FDHNQ SRZNYR YBJ OYBBQ CERFFHER, HAERFCBAFVIR 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e3909  BENATR CYNPR  \eSRZNYR QVMMVARFF NAQ JRNXARFF VA GUR HETRAG PNER 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e27599  RZREL EQ   \e92 LEB SRZNYR JRNX ABG SRRYVAT JRYY 
(Qvfcngpu Zrffntr) NFFVFG-SVER QRCNEGZRAG \e3909  BENATR CYNPR  \eFZBYQREVAT OEBJA TNEONTR PNA BHGFVQR OL HETRAG PNER 
(Qvfcngpu Zrffntr) FGNYXVAT \e3909  BENATR CYNPR  \e6 ZBAG BYQ ZNYR, HETRAG PNER, QVSSVPHYGL OERNGUVAT 
(Qvfcngpu Zrffntr) NYNEZF-SVER \e3840  BENATR CYNPR  \eTRARENY SVER NYNEZ FUBJVAT THRFG EBBZ 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e29179  RZREL EQ   \e79 LE BYQ SRZNYR SRYY  UVG URNQ NAQ EVOF 
(Qvfcngpu Zrffntr) ZHGHNY NVQ, ERDHRFGRQ \e70  JVAQVAT EVIRE   \eFDHNQ ARRQRQ / OBK NYNEZ 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e3909  BENATR CYNPR  \e3 LE BYQ ERFCVENGBEL QVFGERFF 
(Qvfcngpu Zrffntr) NYNEZF-PB QRGRPGBE \e64  J FGBAROEBBX QE   \e 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e3909  BENATR CYNPR   \eSRZNYR VA N JUVGRJ ZVAV INA CNEXRQ BHG SEBAG,CULFPU  CNGVRAG, ERSHFVAT GENAFCBEG 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e3909  BENATR CYNPR  \eVA GUR HETRAG PNER, ZNYR JVGU NOABEZNY RXT & PURFG CNVAF 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e3655  BENATR CYNPR  \e3 LRNE BYQ UNIVAT N FRVMHER 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e3909  BENATR CYNPR   \eSRZNYR FUBEG BS OERNGU 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e3880  OENVANEQ EQ   \ePNER TVIRE ERCBEGF CNGVRAG, RYQREYL SRZNYR, UNYYHPVANGVAT FHTNE QEBCCVAT\a216-926-9695 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e3880  OENVANEQ EQ   \eRYQREYL SRZNYR, UNYYHPVANGVAT FHTNE QEBCCVAT 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e30049  ZVYRF EQ   \eZNYR CBFFVOYR FGBXR 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e3695  BENATR CYNPR  \e61 LEB ZNYRF PBYYNCFRQ, ABJ PBAFPVBHF NAQ OERNGUVAT 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e3795  BENATR CYNPR  269 \eSRZNYR VA YNOBE, JNGRE OEBXRA 
(Qvfcngpu Zrffntr) NYNEZF-SVER \e3840  BENATR CYNPR  \eFGNGR NYNEZ 781 2224 VAQVPNGVAT TRARENY SVER NYNEZ BCE/ORIREYL 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e3860  CVAR PERFG QE  \e82 LE BYQ ZNYR UNF SNYYRA, JVSR PNAABG TRG UVZ HC 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e29699  UNEINEQ EQ   \e93 LEB SRZNYR JVGU FRIRER FGBZNPU CNVAF, QVNEERN 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e3883  YNAQRE EQ  1 \eSRZNYR ARRQF VAINYVQ NFFVFG JUB UNF SNYYRA BHG BS ORQ\aPURFGAHG PBHEG 
(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e3795  BENATR CYNPR  \eZNYR GBBX ZRQVPVAR , HAERFCBAFIVR OHG OERNGUVAT 

*/

choyvp pynff BUPhlnubtnPbhaglCnefreGrfg rkgraqf OnfrCnefreGrfg {
  
  choyvp BUPhlnubtnPbhaglCnefreGrfg() {
    frgCnefre(arj BUPhlnubtnPbhaglCnefre(), "PHLNUBTN PBHAGL", "BU");
  }
  
  @Grfg
  choyvp ibvq grfgPuntevaSnyyfSverQrcnegzrag() {

    qbGrfg("G1",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e308  SBK JNL     \ePHG JEVFG ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:308 SBK JNL",
        "VASB:PHG JEVFG");

    qbGrfg("G2",
        "(Qvfcngpu Zrffntr) ZIN \a123  SNVEIVRJ QE    F EHFFRYY \aRYQREYL SRZNYR VAIBYIRQ VA YBJ FCRRQ ZIN",
        "PNYY:ZIN",
        "NQQE:123 SNVEIVRJ QE",
        "PVGL:F EHFFRYY",
        "VASB:RYQREYL SRZNYR VAIBYIRQ VA YBJ FCRRQ ZIN");

    qbGrfg("G3",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e35952  FBYBA EQ    ORAGYRLIVYYR \eZNYR CVAARQ ORGJRRA GERR NAQ EVQVAT ZBJRE, NQVIFRQ ABG VAWHERQ ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:35952 FBYBA EQ",
        "PVGL:ORAGYRLIVYYR",
        "VASB:ZNYR CVAARQ ORGJRRA GERR NAQ EVQVAT ZBJRE, NQVIFRQ ABG VAWHERQ");

    qbGrfg("G4",
        "(Qvfcngpu Zrffntr) ZIN \a ERDHRFGRQ FDHNQ NVE ONT QRCYBLZRAG, \a ",
        "PNYY:ZIN",
        "NQQE:ERDHRFGRQ FDHNQ NVE ONT QRCYBLZRAG,");

    qbGrfg("G5",
        "(Qvfcngpu Zrffntr) ZIN \e  PUVYYVPBGUR EQ    F EHFFRYY \eTPFB NQIVFRQ IRUVPYR ( TEL INA) VA GUR QVGPU, AB VAWHEVRF ",
        "PNYY:ZIN",
        "NQQE:PUVYYVPBGUR EQ",
        "PVGL:F EHFFRYY",
        "VASB:TPFB NQIVFRQ IRUVPYR ( TEL INA) VA GUR QVGPU, AB VAWHEVRF");

    qbGrfg("G6",
        "(Qvfcngpu Zrffntr) OBK 100  \e  UVENZ GEY    PUNTEVA SNYY \eERDHRFGRQ OL BP3 ",
        "PNYY:OBK 100",
        "NQQE:UVENZ GEY",
        "PVGL:PUNTEVA SNYYF GJC",
        "VASB:ERDHRFGRQ OL BP3");

    qbGrfg("G7",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e200  UNZYRG UVYYF QE  123  PUNTEVA SNYY \eRYQREYL SRZNYR SRYY, HAVAWHERQ ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:200 UNZYRG UVYYF QE",
        "NCG:123",
        "PVGL:PUNTEVA SNYYF GJC",
        "VASB:RYQREYL SRZNYR SRYY, HAVAWHERQ");

    qbGrfg("G8",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e150  XRAFVATGBA PVE    F EHFFRYY \eFRVIREF FRPHEVGL  216-383-1234 BCE/ WRFFVPN\a" +
        "ZRQVPNY NYNEZ ",

        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:150 XRAFVATGBA PVE",
        "PVGL:F EHFFRYY",
        "VASB:FRVIREF FRPHEVGL  216-383-1234 BCE/ WRFFVPN / ZRQVPNY NYNEZ");

    qbGrfg("G9",
        "(Qvfcngpu Zrffntr) SVER- TRARENY \e  PBL YA    PUNTEVA SNYY \eTNENTR FZBXVAT VA GUR ERNE BS GUR UBHFR ARKG QBBE ",
        "PNYY:SVER- TRARENY",
        "NQQE:PBL YA",
        "PVGL:PUNTEVA SNYYF GJC",
        "VASB:TNENTR FZBXVAT VA GUR ERNE BS GUR UBHFR ARKG QBBE");

    qbGrfg("G10",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e70  EVIRE FGBAR QE    ZBERYNAQ UVY \eRYQREYL SRZNYR SRYY CBFFVOYR VAWHERQ NEZ ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:70 EVIRE FGBAR QE",
        "PVGL:ZBERYNAQ UVYYF",
        "VASB:RYQREYL SRZNYR SRYY CBFFVOYR VAWHERQ NEZ");

    qbGrfg("G11",
        "(Qvfcngpu Zrffntr) NAVZNY- ZVFP. \e83  ZNCYR FG   \eQBT FGHPX HAQRE PNE ",
        "PNYY:NAVZNY- ZVFP.",
        "NQQE:83 ZNCYR FG",
        "VASB:QBT FGHPX HAQRE PNE");

    qbGrfg("G12",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e3841  JVYGFUVER EQ    ZBERYNAQ UVY \eZNYR JVGU CNEXVAFBAF ARRQF GB OR GENAFCBEGRQ ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:3841 JVYGFUVER EQ",
        "PVGL:ZBERYNAQ UVYYF",
        "VASB:ZNYR JVGU CNEXVAFBAF ARRQF GB OR GENAFCBEGRQ");

    qbGrfg("G13",
        "(Qvfcngpu Zrffntr) ZIN-CRQRFG.VAWHEL  \e98  A ZNVA FG    PUNTEVA SNYY \eSRZNYR FGEHPX OL IRUVPYR ",
        "PNYY:ZIN-CRQRFG.VAWHEL",
        "NQQE:98 A ZNVA FG",
        "PVGL:PUNTEVA SNYYF GJC",
        "VASB:SRZNYR FGEHPX OL IRUVPYR");

    qbGrfg("G14",
        "(Qvfcngpu Zrffntr) NYNEZF-SVER  \e2657  PUNTEVA EVIRE    UHAGVAT INYY \eNPPRFF CEBGRPGVIR 800.498.7565\a" +
        "VAQ/CHYY FGNGVBA \a" +
        "BCE/EVNFUVNU ",

        "PNYY:NYNEZF-SVER",
        "NQQE:2657 PUNTEVA EVIRE",
        "PVGL:UHAGVAT INYYRL",
        "VASB:NPPRFF CEBGRPGVIR 800.498.7565 / VAQ/CHYY FGNGVBA / BCE/EVNFUVNU");

    qbGrfg("G15",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e5192  PUVYYVPBGUR EQ    F EHFFRYY \e46 LE BYQ SRZNYR, NOQBZVANY CNVA ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:5192 PUVYYVPBGUR EQ",
        "PVGL:F EHFFRYY",
        "VASB:46 LE BYQ SRZNYR, NOQBZVANY CNVA");

    qbGrfg("G16",
        "(Qvfcngpu Zrffntr) NYNEZF-PB QRGRPGBE  \e1584  ORYY FG    F EHFFRYY \ePB QRGRPGBEF VA GUR ONFRZRAG NER FBHAQVAT ",
        "PNYY:NYNEZF-PB QRGRPGBE",
        "NQQE:1584 ORYY FG",
        "PVGL:F EHFFRYY",
        "VASB:PB QRGRPGBEF VA GUR ONFRZRAG NER FBHAQVAT");

    qbGrfg("G17",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e245  FCEVATQNYR YA    ZBERYNAQ UVY \e83 LEB SRZNYR URNEG CEBOYRZ NAQ SRRYVAT SNVAG ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:245 FCEVATQNYR YA",
        "PVGL:ZBERYNAQ UVYYF",
        "VASB:83 LEB SRZNYR URNEG CEBOYRZ NAQ SRRYVAT SNVAG");

    qbGrfg("G18",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e200  UNZYRG UVYYF QE  307  PUNTEVA SNYY \eVAINYVQ NFFVFG ARRQRQ BA ZNYR CNEGL ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:200 UNZYRG UVYYF QE",
        "NCG:307",
        "PVGL:PUNTEVA SNYYF GJC",
        "VASB:VAINYVQ NFFVFG ARRQRQ BA ZNYR CNEGL");

    qbGrfg("G19",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e25  CYRNFNAG QE   PUNTEVA SNYY \eRYQREYL SRZNYR HAERFCBAFVIR, OERNGUVAT ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:25 CYRNFNAG QE",
        "PVGL:PUNTEVA SNYYF GJC",
        "VASB:RYQREYL SRZNYR HAERFCBAFVIR, OERNGUVAT");

    qbGrfg("G20",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e200  UNZYRG UVYYF QE  310  PUNTEVA SNYY \eHAXABJA ZRQVPNY, FDHNQ ERDHRFGRQ OL ERFVQRAG ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:200 UNZYRG UVYYF QE",
        "NCG:310",
        "PVGL:PUNTEVA SNYYF GJC",
        "VASB:HAXABJA ZRQVPNY, FDHNQ ERDHRFGRQ OL ERFVQRAG");

    qbGrfg("G21",
        "(Qvfcngpu Zrffntr) NYNEZF-ZRQVPNY  \a16  SBERFG QE    F EHFFRYY \ayvsryvar frp 888 289 2018 UVFGBEL BS SNYYVAT BCE/WNAR ",
        "PNYY:NYNEZF-ZRQVPNY",
        "NQQE:16 SBERFG QE",
        "PVGL:F EHFFRYY",
        "VASB:yvsryvar frp 888 289 2018 UVFGBEL BS SNYYVAT BCE/WNAR");

    qbGrfg("G22",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e47  CNJ CNJ YNXR QE    F EHFFRYY \eSRZNYR JNF PUBXVAT, FUR VF ABJ UNIVAT GEBHOYR OERNGUVAT ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:47 CNJ CNJ YNXR QE",
        "PVGL:F EHFFRYY",
        "VASB:SRZNYR JNF PUBXVAT, FUR VF ABJ UNIVAT GEBHOYR OERNGUVAT");

    qbGrfg("G23",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e36030  PUNTEVA OYIQ    ZBERYNAQ UVY \eHAERFCBAFVIR SRZNYR ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:36030 PUNTEVA OYIQ",
        "PVGL:ZBERYNAQ UVYYF",
        "VASB:HAERFCBAFVIR SRZNYR");

    qbGrfg("G24",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e400  R JNFUVATGBA FG   PUNTEVA SNYY \eUVG VA SNPR J ONYY PBA/OERNGU ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:400 R JNFUVATGBA FG",
        "PVGL:PUNTEVA SNYYF GJC",
        "VASB:UVG VA SNPR J ONYY PBA/OERNGU");

    qbGrfg("G25",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e305  R JNFUVATGBA FG   PUNTEVA SNYY \e84 LE BYQ SRZNYR .,CBFFVOYR FGEBXR ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:305 R JNFUVATGBA FG",
        "PVGL:PUNTEVA SNYYF GJC",
        "VASB:84 LE BYQ SRZNYR .,CBFFVOYR FGEBXR");

    qbGrfg("G26",
        "(Qvfcngpu Zrffntr) NYNEZF-SVER  \e40  YNHERY PBHEG   ZBERYNAQ UVY \eFGNAYRL FRPHEVGL\aBCE : ZRTNA\a216-361-1050\aVAQ : PYRIRYNAQ EBBZ ",
        "PNYY:NYNEZF-SVER",
        "NQQE:40 YNHERY PBHEG",
        "PVGL:ZBERYNAQ UVYYF",
        "VASB:FGNAYRL FRPHEVGL / BCE : ZRTNA / 216-361-1050 / VAQ : PYRIRYNAQ EBBZ");

    qbGrfg("G27",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY\a200  UNZYRG UVYYF QE  217  \aRYQREYL SRZNYR SRYY BHG BS ORQ\aARRQF NFFVFGNAPR TRGGVAT HC ",
        "PNYY:FDHNQ PNYY",
        "NQQE:200 UNZYRG UVYYF QE",
        "NCG:217",
        "VASB:RYQREYL SRZNYR SRYY BHG BS ORQ / ARRQF NFFVFGNAPR TRGGVAT HC");

    qbGrfg("G28",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e205  UNZYRG UVYYF QE  75  PUNTEVA SNYY \eSRZNYR SRYY QVMML ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:205 UNZYRG UVYYF QE",
        "NCG:75",
        "PVGL:PUNTEVA SNYYF GJC",
        "VASB:SRZNYR SRYY QVMML");

    qbGrfg("G29",
        "(Qvfcngpu Zrffntr) ZHGHNY NVQ, TVIRA  \a6025  XEHFR QE    PUNTEVA SNYY \aFBYBA SQ ERDHRFGRQ N YNQQRE GEHPX  ",
        "PNYY:ZHGHNY NVQ, TVIRA",
        "NQQE:6025 XEHFR QE",
        "PVGL:PUNTEVA SNYYF GJC",
        "VASB:FBYBA SQ ERDHRFGRQ N YNQQRE GEHPX");

    qbGrfg("G30",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \eR JNFUVATGBA FG & EVQTRJBBQ    PUNTEVA SNYY \eZNYR SRYY BSS OVXR NAQ ABG ZBIVAT ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:R JNFUVATGBA FG & EVQTRJBBQ",
        "PVGL:PUNTEVA SNYYF GJC",
        "VASB:ZNYR SRYY BSS OVXR NAQ ABG ZBIVAT");

    qbGrfg("G31",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e116  PBHAGELFVQR    F EHFFRYY \eANHFRN, FJRNGF NAQ QVMML, SRZNYR VF FGVYY OERNGUVAT , PBAFPVBHF ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:116 PBHAGELFVQR",
        "PVGL:F EHFFRYY",
        "VASB:ANHFRN, FJRNGF NAQ QVMML, SRZNYR VF FGVYY OERNGUVAT , PBAFPVBHF");

    qbGrfg("G32",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e102  YNHERY EQ   F EHFFRYY \eSRZNYR VA URE 90'F, UNF SNYYRA N PBHCYR BS GVZRF, PBAFGNAG CNVA ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:102 YNHERY EQ",
        "PVGL:F EHFFRYY",
        "VASB:SRZNYR VA URE 90'F, UNF SNYYRA N PBHCYR BS GVZRF, PBAFGNAG CNVA");

    qbGrfg("G33",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \a\aVAQ/ ERQ URYC OHGGBA CERFFRQ, AB ERFCBAFR SEBZ ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "VASB:VAQ/ ERQ URYC OHGGBA CERFFRQ, AB ERFCBAFR SEBZ");

    qbGrfg("G34",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e5188  PUVYYVPBGUR EQ   F EHFFRYY \e35 LE BYQ ZNYR JVGU PURFG CNVAF  FVGGVAT VA N PURIL INA ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:5188 PUVYYVPBGUR EQ",
        "PVGL:F EHFFRYY",
        "VASB:35 LE BYQ ZNYR JVGU PURFG CNVAF  FVGGVAT VA N PURIL INA");

    qbGrfg("G35",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e35  UVTU PBHEG   PUNTEVA SNYY \eRYQREYL ZNYR IBZVGVAT & OYBBQL FGBBY ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:35 UVTU PBHEG",
        "PVGL:PUNTEVA SNYYF GJC",
        "VASB:RYQREYL ZNYR IBZVGVAT & OYBBQL FGBBY");

    qbGrfg("G36",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e31  FBHGU FG    PUNTEVA SNYY \eSRZNYR QVFBEVRAGRQ ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:31 FBHGU FG",
        "PVGL:PUNTEVA SNYYF GJC",
        "VASB:SRZNYR QVFBEVRAGRQ");

    qbGrfg("G37",
        "(Qvfcngpu Zrffntr) TNF BQBE  \e32605  WNPXFBA EQ    ZBERYNAQ UVY \eIRUPVYR ENA BIRE TNF ZRGRE TNF VF VA GUR NVE ",
        "PNYY:TNF BQBE",
        "NQQE:32605 WNPXFBA EQ",
        "PVGL:ZBERYNAQ UVYYF",
        "VASB:IRUPVYR ENA BIRE TNF ZRGRE TNF VF VA GUR NVE");

    qbGrfg("G38",
        "(Qvfcngpu Zrffntr) ZIN-VAWHEL \e5000  PUNTEVA EVIRE    ZBERYNAQ UVY \eCRE NAQL JRVATNEG 440 623 9069 CBEF VAGB N THNEQ ENVY ",
        "PNYY:ZIN-VAWHEL",
        "NQQE:5000 PUNTEVA EVIRE",
        "PVGL:ZBERYNAQ UVYYF",
        "VASB:CRE NAQL JRVATNEG 440 623 9069 CBEF VAGB N THNEQ ENVY");

    qbGrfg("G39",
        "(Qvfcngpu Zrffntr) NFFVFG-SVER QRCNEGZRAG  \e  R JNFUVATGBA FG    PUNTEVA SNYY \eNG EVQTRJBBQ SBE N CBFFVOYR SHRY FCVYY ",
        "PNYY:NFFVFG-SVER QRCNEGZRAG",
        "NQQE:R JNFUVATGBA FG",
        "PVGL:PUNTEVA SNYYF GJC",
        "VASB:NG EVQTRJBBQ SBE N CBFFVOYR SHRY FCVYY");

    qbGrfg("G40",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e551  R JNFUVATGBA FG   F EHFFRYY \e84LBZ ERPGNY OYRRQ, FRIRER FGBZNPU CNVA ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:551 R JNFUVATGBA FG",
        "PVGL:F EHFFRYY",
        "VASB:84LBZ ERPGNY OYRRQ, FRIRER FGBZNPU CNVA");

    qbGrfg("G41",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e34114  PUNTEVA OYIQ  8106 \eRYQREYL ZNYR SRYY NAQ VF OYRRQVAT  PBA/OERNGU ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:34114 PUNTEVA OYIQ",
        "NCG:8106",
        "VASB:RYQREYL ZNYR SRYY NAQ VF OYRRQVAT  PBA/OERNGU");

    qbGrfg("G42",
        "(Qvfcngpu Zrffntr) NYNEZF-SVER \e35  GNEGNA PG  \eTVYZBER FRPHEVGL BCE/50  440-232-6458\aVAQ/ TRARENY ",
        "PNYY:NYNEZF-SVER",
        "NQQE:35 GNEGNA PG",
        "VASB:TVYZBER FRPHEVGL BCE/50  440-232-6458 / VAQ/ TRARENY");

    qbGrfg("G43",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e40  JUVGRGNVY YNAR   \eZNYR SRYY BSS FXNGR OBNEQ\aOYRRQVAT SEBZ URNQ\aNAAVR 440-552-9766 ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:40 JUVGRGNVY YNAR",
        "VASB:ZNYR SRYY BSS FXNGR OBNEQ / OYRRQVAT SEBZ URNQ / NAAVR 440-552-9766");

    qbGrfg("G44",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e41  JUVGRGNVY YNAR   \eZNYR SRYY BSS FXNGR OBNEQ\aOYRRQVAT SEBZ URNQ ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:41 JUVGRGNVY YNAR",
        "VASB:ZNYR SRYY BSS FXNGR OBNEQ / OYRRQVAT SEBZ URNQ");

    qbGrfg("G45",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e38879  OREXRYRL NIR   \e88 LRNE BYQ SRZNYR SRYY BA GUR CNGVB UVG URE URNQ ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:38879 OREXRYRL NIR",
        "VASB:88 LRNE BYQ SRZNYR SRYY BA GUR CNGVB UVG URE URNQ");

    qbGrfg("G46",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e33001  FBYBA EQ  202 \eZHGHNY NVQ SBE FBYBA ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:33001 FBYBA EQ",
        "NCG:202",
        "VASB:ZHGHNY NVQ SBE FBYBA");

    qbGrfg("G47",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e551  R JNFUVATGBA FG  \e44 lrne byq znxr purfg cnvaf ngevny syhggre ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:551 R JNFUVATGBA FG",
        "VASB:44 lrne byq znxr purfg cnvaf ngevny syhggre");

    qbGrfg("G48",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e551  R JNFUVATGBA FG  \eZNYR PURFG CNVAF ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:551 R JNFUVATGBA FG",
        "VASB:ZNYR PURFG CNVAF");

    qbGrfg("G49",
        "(Qvfcngpu Zrffntr)  \e49  J BENATR FG   \e27 LBN SRZNYR UNIVAT N FRVMHER ",
        "PNYY:49  J BENATR FG",
        "NQQE:27 LBN SRZNYR UNIVAT N FRVMHER");

    qbGrfg("G50",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e111  UNZYRG UVYYF QE  22 \eRYQREYL ZNYR PNGU CEBOYRZF ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:111 UNZYRG UVYYF QE",
        "NCG:22",
        "VASB:RYQREYL ZNYR PNGU CEBOYRZF");

    qbGrfg("G51",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e551  R JNFUVATGBA  \eSRZNYR CBFFVOYR URNEG NGGNPX VA GUR HETRAG PNER ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:551 R JNFUVATGBA",
        "VASB:SRZNYR CBFFVOYR URNEG NGGNPX VA GUR HETRAG PNER");

    qbGrfg("G52",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e21  J JNFUVATGBA FG  \eZNYR JVGU PURFG CNVAF ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:21 J JNFUVATGBA FG",
        "VASB:ZNYR JVGU PURFG CNVAF");

    qbGrfg("G53",
        "(Qvfcngpu Zrffntr)  \a200  UNZYRG UVYYF QE  \aZRQVPNY RZRETRAPL\aZHGHNY NVQ  SEBZ ONVAOEVQTR SQ ",
        "PNYY:200  UNZYRG UVYYF QE",
        "NQQE:ZRQVPNY RZRETRAPL",
        "VASB:ZHGHNY NVQ  SEBZ ONVAOEVQTR SQ");

    qbGrfg("G54",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e200  UNZYRG UVYYF QE  \eRYQREYL  ZNYR UNIVAT YRT CNVA, PBAFPVBHF NAQ OERNGUVAT ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:200 UNZYRG UVYYF QE",
        "VASB:RYQREYL  ZNYR UNIVAT YRT CNVA, PBAFPVBHF NAQ OERNGUVAT");

    qbGrfg("G55",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e108  SNVEIVRJ EQ   \e 86 ryqreyl srznyr qvmml hanoyr gb or fgrnql ba ure srrg ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:108 SNVEIVRJ EQ",
        "VASB:86 ryqreyl srznyr qvmml hanoyr gb or fgrnql ba ure srrg");

    qbGrfg("G56",
        "(Qvfcngpu Zrffntr) TNF BQBE \e45  FGREAPERFG QE   \eVYYHZVANGVAT PB ERCBEG GB BISQ N FZRYY BS ANGHENY TNF SEBZ GUR NOBIR YBPNGVBA ",
        "PNYY:TNF BQBE",
        "NQQE:45 FGREAPERFG QE",
        "VASB:VYYHZVANGVAT PB ERCBEG GB BISQ N FZRYY BS ANGHENY TNF SEBZ GUR NOBIR YBPNGVBA");

    qbGrfg("G57",
        "(Qvfcngpu Zrffntr) SVER- TRARENY \e6005  CNEXYNAQ QE   \eTNF TEVYY HANOYR GB OR GHEARQ BSS, ANGHENY TNF TEVYY VF ARNE GUR UBHFR ",
        "PNYY:SVER- TRARENY",
        "NQQE:6005 CNEXYNAQ QE",
        "VASB:TNF TEVYY HANOYR GB OR GHEARQ BSS, ANGHENY TNF TEVYY VF ARNE GUR UBHFR");

    qbGrfg("G58",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e40  SNEJBBQ QE   \eUNIVAT GEBHOYR OERNGUVAT\a ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:40 SNEJBBQ QE",
        "VASB:UNIVAT GEBHOYR OERNGUVAT");

    qbGrfg("G59",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e200  UNZYRG UVYYF QE  109 \eRYQREYL SRZNYR SRRYVAT AHZO ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:200 UNZYRG UVYYF QE",
        "NCG:109",
        "VASB:RYQREYL SRZNYR SRRYVAT AHZO");

    qbGrfg("G60",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e85  JVYYBJ JBBQ YA   \eRYQREYL SRZNYR UVC VAWHEL ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:85 JVYYBJ JBBQ YA",
        "VASB:RYQREYL SRZNYR UVC VAWHEL");

    qbGrfg("G61",
        "(Qvfcngpu Zrffntr) SVER- TRARENY \e100  A ZNVA FG  \eYVTUG VA PRVYVAT PNHTUG BA SVER VF ABJ BHG ",
        "PNYY:SVER- TRARENY",
        "NQQE:100 A ZNVA FG",
        "VASB:YVTUG VA PRVYVAT PNHTUG BA SVER VF ABJ BHG");

    qbGrfg("G62",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \a31  FBHGU FG   \aSRZNYR CNFFRQ BHG ABJ PBAFPVBHF, UVTU OYBBQ CERFFHER",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:31 FBHGU FG",
        "VASB:SRZNYR CNFFRQ BHG ABJ PBAFPVBHF, UVTU OYBBQ CERFFHER");

    qbGrfg("G63",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e200  UNZYRG UVYYF QE  213 \eZNYR JUB UNF SNYYRA ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:200 UNZYRG UVYYF QE",
        "NCG:213",
        "VASB:ZNYR JUB UNF SNYYRA");

    qbGrfg("G64",
        "(Qvfcngpu Zrffntr) NYNEZF-PB QRGRPGBE \e65  BYVIR FG   \eNYNEZ ERNQVAT TNF NYNEZ, AB FLZCGBZF RINPHNGRQ ",
        "PNYY:NYNEZF-PB QRGRPGBE",
        "NQQE:65 BYVIR FG",
        "VASB:NYNEZ ERNQVAT TNF NYNEZ, AB FLZCGBZF RINPHNGRQ");

    qbGrfg("G65",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e20  FGBARJBBQ QE  \eRYQREYL SRZNYR CBFFVOYR URNEG NGGNPX ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:20 FGBARJBBQ QE",
        "VASB:RYQREYL SRZNYR CBFFVOYR URNEG NGGNPX");

    qbGrfg("G66",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e200  UNZYRG UVYYF QE  221 \eSRZNYR YRT CNVA ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:200 UNZYRG UVYYF QE",
        "NCG:221",
        "VASB:SRZNYR YRT CNVA");

    qbGrfg("G67",
        "(Qvfcngpu Zrffntr) NYNEZF-SVER \e1082  ORYY EQ  \eRAGEL THNEQ 2800-443-8865\aVAQ/TRA SVER \aBCE/412 ",
        "PNYY:NYNEZF-SVER",
        "NQQE:1082 ORYY EQ",
        "VASB:RAGEL THNEQ 2800-443-8865 / VAQ/TRA SVER / BCE/412");

    qbGrfg("G68",
        "(Qvfcngpu Zrffntr) OBK 100 \eFBZ PRAGRE EQ  UVENZ GEY   \eBISQ ERDHRFGRQ OBK 100 ZNONF NYNEZ ",
        "PNYY:OBK 100",
        "NQQE:FBZ PRAGRE EQ",
        "NCG:UVENZ GEY",
        "VASB:BISQ ERDHRFGRQ OBK 100 ZNONF NYNEZ");

    qbGrfg("G69",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e551  R JNFUVATGBA FG  \eOYBBQ PYBG VA URE YRT & CBFFVOYR VA GUR YHATF, OERNGUVAT & PBAPVBHF ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:551 R JNFUVATGBA FG",
        "VASB:OYBBQ PYBG VA URE YRT & CBFFVOYR VA GUR YHATF, OERNGUVAT & PBAPVBHF");

    qbGrfg("G70",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e115  NFCRAJBBQ QE  \e85 LE BYQ ZNYR , FRIRER NOQBZVANY CNVA SEBZ N UREAVN ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:115 NFCRAJBBQ QE",
        "VASB:85 LE BYQ ZNYR , FRIRER NOQBZVANY CNVA SEBZ N UREAVN");

    qbGrfg("G71",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e FDHNJ EBPX  \eSRZNYR VA CNEXVAT YBG JVGU SNPR VAWHEL ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:FDHNJ EBPX",
        "VASB:SRZNYR VA CNEXVAT YBG JVGU SNPR VAWHEL");

    qbGrfg("G72",
        "(Qvfcngpu Zrffntr) SVER- TRARENY \e36850  PUNTEVA OYIQ   \eSVFU GNAX PNHTUG SVER\aSVER VF RKGVATHVFURQ \aUBHFR SHYY BS FZBXR ",
        "PNYY:SVER- TRARENY",
        "NQQE:36850 PUNTEVA OYIQ",
        "VASB:SVFU GNAX PNHTUG SVER / SVER VF RKGVATHVFURQ / UBHFR SHYY BS FZBXR");

    qbGrfg("G73",
        "(Qvfcngpu Zrffntr) NFFVFG-SVER QRCNEGZRAG \e40  SNEJBBQ QE   \eYNZC VF ZNXVAT N ABVFRt ",
        "PNYY:NFFVFG-SVER QRCNEGZRAG",
        "NQQE:40 SNEJBBQ QE",
        "VASB:YNZC VF ZNXVAT N ABVFRt");

    qbGrfg("G74",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e206  UNZYRG UVYYF QE  89 \eZNYR ERFVQRAG UNF SNYYRA ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:206 UNZYRG UVYYF QE",
        "NCG:89",
        "VASB:ZNYR ERFVQRAG UNF SNYYRA");

    qbGrfg("G75",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e125  ZHEJBBQ QE   \e87 LEB SRZNYR , PBATRFGVIR URNEG SNVYHER, HAERFCBAFVIR ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:125 ZHEJBBQ QE",
        "VASB:87 LEB SRZNYR , PBATRFGVIR URNEG SNVYHER, HAERFCBAFVIR");

    qbGrfg("G76",
        "(Qvfcngpu Zrffntr) ZHGHNY NVQ, TVIRA \e13665  NDHVYYN EQ   \eOHEGBA SQ NPGVINGVAT GUR TRNHTN CBEGNTR JNGRE FUHGGYR SBE N UBHFR SVER ",
        "PNYY:ZHGHNY NVQ, TVIRA",
        "NQQE:13665 NDHVYYN EQ",
        "VASB:OHEGBA SQ NPGVINGVAT GUR TRNHTN CBEGNTR JNGRE FUHGGYR SBE N UBHFR SVER");

    qbGrfg("G77",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e102  YRNIVRJ YA   \e71 LEB ZNYR SRYY NAQ VF OYRRQVAT SEBZ UVF UNAQ NAQ NOBIR GUR RLR ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:102 YRNIVRJ YA",
        "VASB:71 LEB ZNYR SRYY NAQ VF OYRRQVAT SEBZ UVF UNAQ NAQ NOBIR GUR RLR");

    qbGrfg("G78",
        "(Qvfcngpu Zrffntr) NYNEZF-SVER \e6000  ABO UVYY QE   \eSVER NYNEZ FBHAQVAT ",
        "PNYY:NYNEZF-SVER",
        "NQQE:6000 ABO UVYY QE",
        "VASB:SVER NYNEZ FBHAQVAT");

    qbGrfg("G79",
        "(Qvfcngpu Zrffntr) NYNEZF-ZRQVPNY \a157  PNEEVNTR QE  103 \aHANOYR GB ZNXR PBAGNPG JVGU CNGVRAG ",
        "PNYY:NYNEZF-ZRQVPNY",
        "NQQE:157 PNEEVNTR QE",
        "NCG:103",
        "VASB:HANOYR GB ZNXR PBAGNPG JVGU CNGVRAG");

    qbGrfg("G80",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e  ORYY GBJRE PG   \eSRZNYR OEBXRA NAXYR, ZRRG NG ONPX BS PBAQBF ARNE SRAPR ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:ORYY GBJRE PG",
        "VASB:SRZNYR OEBXRA NAXYR, ZRRG NG ONPX BS PBAQBF ARNE SRAPR");

    qbGrfg("G81",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e40  R JNFUVATGBA FG   \eRYQREYL UNF SNYYRA OYRRQVAT SEBZ GUR URNQ ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:40 R JNFUVATGBA FG",
        "VASB:RYQREYL UNF SNYYRA OYRRQVAT SEBZ GUR URNQ");

    qbGrfg("G82",
        "(Qvfcngpu Zrffntr)  \e35550  SNVEZBHAG OYIQ   \e91 LBN ZNYR SRYY UVG URNQ. OYRRQVAT SEBZ URNQ NAQ UNAQ ",
        "PNYY:35550  SNVEZBHAG OYIQ",
        "NQQE:91 LBN ZNYR SRYY UVG URNQ OYRRQVAT SEBZ URNQ NAQ UNAQ",
        "ZNQQE:91 LBN ZNYR SRYY UVG URNQ OYRRQVAT SEBZ URNQ");

    qbGrfg("G83",
        "(Qvfcngpu Zrffntr) PBZCYNVAGF-TRARENY \aORYY FG  ZNVA FG   \aZNYR HAPBA FDHNQ ERDHRFG ",
        "PNYY:PBZCYNVAGF-TRARENY",
        "NQQE:ORYY FG",
        "NCG:ZNVA FG",
        "VASB:ZNYR HAPBA FDHNQ ERDHRFG");

    qbGrfg("G84",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e45  R WHAVCRE YA   \eRINYHNGVBA BA N 46 LBN SRZNYR ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:45 R WHAVCRE YA",
        "VASB:RINYHNGVBA BA N 46 LBN SRZNYR");

    qbGrfg("G85",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \a36400  F JBBQYNAQ EQ   \aPNYYRE NQIVFRQ GUR GENPGBE SYVCCRQ BIRE BA EVQRE",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:36400 F JBBQYNAQ EQ",
        "VASB:PNYYRE NQIVFRQ GUR GENPGBE SYVCCRQ BIRE BA EVQRE");

    qbGrfg("G86",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \a" +
        "200  UNZYRG UVYYF QE  201 \a" +
        "PNER PRAGRE\a" +
        "BCE : 451 \a" +
        "800-508-6370\a" +
        "87 LE BYQ SRZNYR UNF SNYYRA ,",

        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:200 UNZYRG UVYYF QE",
        "NCG:201",
        "VASB:PNER PRAGRE / BCE : 451 / 800-508-6370 / 87 LE BYQ SRZNYR UNF SNYYRA ,");

    qbGrfg("G87",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e604  QBR PG   \e15 le byq srznyr frzv pbapvbf, oernguvat ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:604 QBR PG",
        "VASB:15 le byq srznyr frzv pbapvbf, oernguvat");

    qbGrfg("G88",
        "(Qvfcngpu Zrffntr) FHFCVPVBA \e395  ORYY FG   \eVAGBK ZNYR VA OBBXVAT ",
        "PNYY:FHFCVPVBA",
        "NQQE:395 ORYY FG",
        "VASB:VAGBK ZNYR VA OBBXVAT");

    qbGrfg("G89",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e EVIREFVQR CNEX  \eZNYR CNFFRQ BHG ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:EVIREFVQR CNEX",
        "VASB:ZNYR CNFFRQ BHG");

  }
  
  @Grfg
  choyvp ibvq grfgBenatrIvyyntrSverQrcnegzrag() {

    qbGrfg("G1",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e  271    BENATR \eNFFVFGVAT QVFNOYRQ CEVINGR NOHYNAPR FREIVPR\aJVGU N GENAFCBEG ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:271 BENATR",
        "VASB:NFFVFGVAT QVFNOYRQ CEVINGR NOHYNAPR FREIVPR / JVGU N GENAFCBEG");

    qbGrfg("G2",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e3909  BENATR CYNPR   BENATR \e60 LE BYQ SRZNYR CBFFVOYR FGEBXR VA GUR HETRAG PNER ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:3909 BENATR CYNPR",
        "PVGL:BENATR",
        "VASB:60 LE BYQ SRZNYR CBFFVOYR FGEBXR VA GUR HETRAG PNER");

    qbGrfg("G3",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e3909  BENATR CYNPR   BENATR \eZNYR OYBBQ PYBG VA UVF YHATF ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:3909 BENATR CYNPR",
        "PVGL:BENATR",
        "VASB:ZNYR OYBBQ PYBG VA UVF YHATF");

    qbGrfg("G4",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e3909  BENATR CYNPR  1100  BENATR \e60LBS ULCBGRAFVIR ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:3909 BENATR CYNPR",
        "NCG:1100",
        "PVGL:BENATR",
        "VASB:60LBS ULCBGRAFVIR");

    qbGrfg("G5",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e3909  BENATR CYNPR   BENATR \e79 LE BYQ SRZNYR , PURFG CNVAF VA GUR HETRAG PNER ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:3909 BENATR CYNPR",
        "PVGL:BENATR",
        "VASB:79 LE BYQ SRZNYR , PURFG CNVAF VA GUR HETRAG PNER");

    qbGrfg("G6",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e28149  ZVYRF EQ   BENATR \eSRZNYR ABG SRRYVAT JRYY, QVNORGVP ABG SRRYVAT ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:28149 ZVYRF EQ",
        "PVGL:BENATR",
        "VASB:SRZNYR ABG SRRYVAT JRYY, QVNORGVP ABG SRRYVAT");

    qbGrfg("G7",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e3809  JNYAHG UVYYF EQ    BENATR \e60 LBN ZNYR JRNX NAQ IBZVGVAT ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:3809 JNYAHG UVYYF EQ",
        "PVGL:BENATR",
        "VASB:60 LBN ZNYR JRNX NAQ IBZVGVAT");

    qbGrfg("G8",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e3909  BENATR CYNPR  2400  BENATR \e55 LE BYQ SRZNYR, FUBEGARFF BS OERNGU ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:3909 BENATR CYNPR",
        "NCG:2400",
        "PVGL:BENATR",
        "VASB:55 LE BYQ SRZNYR, FUBEGARFF BS OERNGU");

    qbGrfg("G9",
        "(Qvfcngpu Zrffntr) NFFVFG-SVER QRCNEGZRAG  \e3920  JVYQPUREEL GEY     \ecre br5 gurl ner raebhgr gb nobir sbe na bqbe vairfg ",
        "PNYY:NFFVFG-SVER QRCNEGZRAG",
        "NQQE:3920 JVYQPUREEL GEY",
        "VASB:cre br5 gurl ner raebhgr gb nobir sbe na bqbe vairfg");

    qbGrfg("G10",
        "(Qvfcngpu Zrffntr) ZIN \e4486  OENVANEQ EQ    BENATR \epne vagb cbyr qevire oyrrqvat ",
        "PNYY:ZIN",
        "NQQE:4486 OENVANEQ EQ",
        "PVGL:BENATR",
        "VASB:pne vagb cbyr qevire oyrrqvat");

    qbGrfg("G11",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \a3755  BENATR CYNPR  102  BENATR \aSRZNYR, FRIRER CNVA VA YRSG YRT ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:3755 BENATR CYNPR",
        "NCG:102",
        "PVGL:BENATR",
        "VASB:SRZNYR, FRIRER CNVA VA YRSG YRT");

    qbGrfg("G12",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e28850  UNEINEQ EQ    BENATR \eCUFL RINY ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:28850 UNEINEQ EQ",
        "PVGL:BENATR",
        "VASB:CUFL RINY");

    qbGrfg("G13",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e27500  RZREL EQ    BENATR \eznyr abg oernguvat ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:27500 RZREL EQ",
        "PVGL:BENATR",
        "VASB:znyr abg oernguvat");

    qbGrfg("G14",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e205  UNZYRG UVYYF QE  75  PUNTEVA SNYY \eSRZNYR SRYY QVMML ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:205 UNZYRG UVYYF QE",
        "NCG:75",
        "PVGL:PUNTEVA SNYYF GJC",
        "VASB:SRZNYR SRYY QVMML");

    qbGrfg("G15",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e29600  PUNTEVA OYIQ   BENATR \eSRZNYR JVGU YBJ OYBBQ CERFFHER ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:29600 PUNTEVA OYIQ",
        "PVGL:BENATR",
        "VASB:SRZNYR JVGU YBJ OYBBQ CERFFHER");

    qbGrfg("G16",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e3909  BENATR CYNPR   BENATR \eHETRAG PNER / SRZNYR JVGU PURFG CNVAF ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:3909 BENATR CYNPR",
        "PVGL:BENATR",
        "VASB:HETRAG PNER / SRZNYR JVGU PURFG CNVAF");

    qbGrfg("G17",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e3909  BENATR CYNPR   BENATR \eZNYR VA FREIRER CNVA SEBZ NA ZIN ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:3909 BENATR CYNPR",
        "PVGL:BENATR",
        "VASB:ZNYR VA FREIRER CNVA SEBZ NA ZIN");

    qbGrfg("G18",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e4120  YNAQRE EQ     \eCBFFVOYR QBN ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:4120 YNAQRE EQ",
        "VASB:CBFFVOYR QBN");

    qbGrfg("G19",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e3909  BENATR CYNPR   BENATR \eFHVGR 3300\aSRZNYR YBJ OC, UNQ CNFFRQ BHG ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:3909 BENATR CYNPR",
        "PVGL:BENATR",
        "VASB:FHVGR 3300 / SRZNYR YBJ OC, UNQ CNFFRQ BHG");

    qbGrfg("G20",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY  \e29600  PUNTEVA OYIQ   BENATR \eSRZNYR UNQ N CYNGR SNYY BA URE SBBG, VG VF FGNEGVAT GB FJRYY ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:29600 PUNTEVA OYIQ",
        "PVGL:BENATR",
        "VASB:SRZNYR UNQ N CYNGR SNYY BA URE SBBG, VG VF FGNEGVAT GB FJRYY");

    qbGrfg("G21",
        "(Qvfcngpu Zrffntr) NYNEZF-SVER \e4009  BENATR CYNPR  \eFGNAYRL FRPHEVGL  8006894984  BC:195\a" +
        "VAVQPNGVBA: MBAR 16 TRARENY JNGRE SYBJ NYNEZ ",

        "PNYY:NYNEZF-SVER",
        "NQQE:4009 BENATR CYNPR",
        "VASB:FGNAYRL FRPHEVGL  8006894984  BC:195 / VAVQPNGVBA: MBAR 16 TRARENY JNGRE SYBJ NYNEZ");

    qbGrfg("G22",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e31599  JBBQPERFG QE   \eZNYR QVSSVPHYGL OERNGUVAT,FJRNGVAT ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:31599 JBBQPERFG QE",
        "VASB:ZNYR QVSSVPHYGL OERNGUVAT,FJRNGVAT");

    qbGrfg("G23",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e27099  RZREL EQ  \eQVS OERNGUVAT ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:27099 RZREL EQ",
        "VASB:QVS OERNGUVAT");

    qbGrfg("G24",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e3909  BENATR CYNPR  \eSRZNYR PURFG CNVAF  VA GUR HETRAG PNER ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:3909 BENATR CYNPR",
        "VASB:SRZNYR PURFG CNVAF  VA GUR HETRAG PNER");

    qbGrfg("G25",
        "(Qvfcngpu Zrffntr) SVER- TRARENY \e30600  RZREL EQ   \eFGENATR BQBE ",
        "PNYY:SVER- TRARENY",
        "NQQE:30600 RZREL EQ",
        "VASB:FGENATR BQBE");

    qbGrfg("G26",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e3655  BENATR CYNPR  \e45 LBN ZNYR CNFFRQ BHG ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:3655 BENATR CYNPR",
        "VASB:45 LBN ZNYR CNFFRQ BHG");

    qbGrfg("G27",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \a4709  YNAQRE EQ   \aRYQREYL ZNYR BHG BS JURRYPUNVE , FGREAPERFG FVQR QEVIRJNL",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:4709 YNAQRE EQ",
        "VASB:RYQREYL ZNYR BHG BS JURRYPUNVE , FGREAPERFG FVQR QEVIRJNL");

    qbGrfg("G28",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e27500  RZREL EQ   \eZNYR FRIRE PENZCVAT ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:27500 RZREL EQ",
        "VASB:ZNYR FRIRE PENZCVAT");

    qbGrfg("G29",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e27500  RZREL EQ   \eZNYR FGBZNPU CNVAF ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:27500 RZREL EQ",
        "VASB:ZNYR FGBZNPU CNVAF");

    qbGrfg("G30",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e4600  YNAQRE EQ  \eVA BENATR IVYYNTR UNYY, ZNYR UNIVAT NA NYYRETVP ERNPGVBA ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:4600 YNAQRE EQ",
        "VASB:VA BENATR IVYYNTR UNYY, ZNYR UNIVAT NA NYYRETVP ERNPGVBA");

    qbGrfg("G31",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e3909  BENATR CYNPR  2500 \e36 LE BYQ SRZNYR NOQBZVANY OYRRQVAT, PBAPVBHF & OERNGUVAT ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:3909 BENATR CYNPR",
        "NCG:2500",
        "VASB:36 LE BYQ SRZNYR NOQBZVANY OYRRQVAT, PBAPVBHF & OERNGUVAT");

    qbGrfg("G32",
        "(Qvfcngpu Zrffntr) \a3909  BENATR CYNPR   \a78 LRNE BYQ ZRNY UVTU SRIRE NAQ UNIVAT GEBHOYR OERNGUAT",
        "PNYY:3909  BENATR CYNPR",
        "NQQE:78 LRNE BYQ ZRNY UVTU SRIRE NAQ UNIVAT GEBHOYR OERNGUAT",
        "ZNQQE:78 LRNE BYQ ZRNY UVTU SRIRE");

    qbGrfg("G33",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e3909  BENATR CYNPR   \eQVFBEVRAGRQ SRZNYR VA GUR HETRAG PNER ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:3909 BENATR CYNPR",
        "VASB:QVFBEVRAGRQ SRZNYR VA GUR HETRAG PNER");

    qbGrfg("G34",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e3909  BENATR CYNPR  \e65 LE BYQ SRZNYR, NOABEZNY YNO, YRSG NEZ AHZOARFF ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:3909 BENATR CYNPR",
        "VASB:65 LE BYQ SRZNYR, NOABEZNY YNO, YRSG NEZ AHZOARFF");

    qbGrfg("G35",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \a3909  BENATR CYNPR  \a57 LRNE BYQ ZNYR PURFG CNVAF HETRAG PNER",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:3909 BENATR CYNPR",
        "VASB:57 LRNE BYQ ZNYR PURFG CNVAF HETRAG PNER");

    qbGrfg("G36",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e29600  PUNTEVA OYIQ  \eSRZNYR UNF SNYYRA VA GUR QVAVAT EBBZ, HAXABJA VAWHEVRF ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:29600 PUNTEVA OYIQ",
        "VASB:SRZNYR UNF SNYYRA VA GUR QVAVAT EBBZ, HAXABJA VAWHEVRF");

    qbGrfg("G37",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e3909  BENATR CYNPR  3300 \eZNYR NYZBFG CNFFRQ BHG, CBFFVOYR YBJ TYHPBFR ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:3909 BENATR CYNPR",
        "NCG:3300",
        "VASB:ZNYR NYZBFG CNFFRQ BHG, CBFFVOYR YBJ TYHPBFR");

    qbGrfg("G38",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e3655  BENATR CYNPR  \eSRZNYR FVRMVAT VA GUR YBOOL ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:3655 BENATR CYNPR",
        "VASB:SRZNYR FVRMVAT VA GUR YBOOL");

    qbGrfg("G39",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e4545  OENVANEQ EQ  \e2 LE FRVMVAT ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:4545 OENVANEQ EQ",
        "VASB:2 LE FRVMVAT");

    qbGrfg("G40",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e4189  YNAQRE EQ   \eYNHERA ZNEBGGN 216-570-5098\aCNVA VA FGBZNPU ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:4189 YNAQRE EQ",
        "VASB:YNHERA ZNEBGGN 216-570-5098 / CNVA VA FGBZNPU");

    qbGrfg("G41",
        "(Qvfcngpu Zrffntr) ZHGHNY NVQ, TVIRA \e3999  EVPUZBAQ EQ  \eZHGHNY NVQ ERDHRFGRQ SBE N CBFFVOYR SVER EBBZ 3222 TNEQRA YRIRY ",
        "PNYY:ZHGHNY NVQ, TVIRA",
        "NQQE:3999 EVPUZBAQ EQ",
        "VASB:ZHGHNY NVQ ERDHRFGRQ SBE N CBFFVOYR SVER EBBZ 3222 TNEQRA YRIRY");

    qbGrfg("G42",
        "(Qvfcngpu Zrffntr) ZHGHNY NVQ, TVIRA \e70  ONFFJBBQ YA  \eNQG 888-294-6736\aVAQ/JNGRE SYBJ\aBCE/EBQTRE ",
        "PNYY:ZHGHNY NVQ, TVIRA",
        "NQQE:70 ONFFJBBQ YA",
        "VASB:NQG 888-294-6736 / VAQ/JNGRE SYBJ / BCE/EBQTRE");

    qbGrfg("G43",
        "(Qvfcngpu Zrffntr) ZHGHNY NVQ, TVIRA \a32450  PURFGAHG   FZBXR VA ONFRZRAG\aGB FPRAR, SNVEZBHAG GB FABJOREEL GB PURFGAHG",
        "PNYY:ZHGHNY NVQ, TVIRA",
        "NQQE:32450 PURFGAHG FZBXR VA ONFRZRAG",
        "VASB:GB FPRAR, SNVEZBHAG GB FABJOREEL GB PURFGAHG");

    qbGrfg("G44",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \a" +
        "27250  RZREL EQ  \a" +
        " FDHNQ NQIVFAT GURL NER CERCNEVAT GB GENAFBCBEG N ZNYR JVGUN  URNQ VAWHEL",

        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:27250 RZREL EQ",
        "VASB:FDHNQ NQIVFAT GURL NER CERCNEVAT GB GENAFBCBEG N ZNYR JVGUN  URNQ VAWHEL");

    qbGrfg("G45",
        "(Qvfcngpu Zrffntr) NYNEZF-SVER \a3625  BENATR CYNPR  \aVAQ SVER NYNEZ.",
        "PNYY:NYNEZF-SVER",
        "NQQE:3625 BENATR CYNPR",
        "VASB:VAQ SVER NYNEZ.");

    qbGrfg("G46",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e4809  R SNVEIVRJ QE   \eRYQREYL SRZNYR OYBBQ CERFFHER VF IREL UVTU ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:4809 R SNVEIVRJ QE",
        "VASB:RYQREYL SRZNYR OYBBQ CERFFHER VF IREL UVTU");

    qbGrfg("G47",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e28950  UNEINEQ EQ   \eSRNZYR CBFFVOYR FGEBXR ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:28950 UNEINEQ EQ",
        "VASB:SRNZYR CBFFVOYR FGEBXR");

    qbGrfg("G48",
        "(Qvfcngpu Zrffntr) NYNEZF-SVER \e4600  YNAQRE EQ  \ePNYY PBZZ\aBCE : OENAQBA\a800-498-7565\aVAQ : TRA SVER ",
        "PNYY:NYNEZF-SVER",
        "NQQE:4600 YNAQRE EQ",
        "VASB:PNYY PBZZ / BCE : OENAQBA / 800-498-7565 / VAQ : TRA SVER");

    qbGrfg("G49",
        "(Qvfcngpu Zrffntr) NYNEZF-ZRQVPNY \e28900  CVXR QE  \ePNER  PRAGRE 800-508-6370\aVAQ/PNAABG TRG HC/CBFFVOYR VAINYVQ NFFVFG\aBCE/230 ",
        "PNYY:NYNEZF-ZRQVPNY",
        "NQQE:28900 CVXR QE",
        "VASB:PNER  PRAGRE 800-508-6370 / VAQ/PNAABG TRG HC/CBFFVOYR VAINYVQ NFFVFG / BCE/230");

    qbGrfg("G50",
        "(Qvfcngpu Zrffntr) NYNEZF-PB QRGRPGBE \e270  OYBFFBZ YA  \eJBHYQ YVXR ERF PURPXRQ\aFGNGR 800 321 7400 BC/WRFFV ",
        "PNYY:NYNEZF-PB QRGRPGBE",
        "NQQE:270 OYBFFBZ YA",
        "VASB:JBHYQ YVXR ERF PURPXRQ / FGNGR 800 321 7400 BC/WRFFV");

    qbGrfg("G51",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \a" +
        "28900  CVXR QE  \a" +
        "GUR PNER PRAGRE\a" +
        "800-508-6370\a" +
        "RYQREYL SRZNYR UNF SNYYRA, ARRQF NFFVFGNAPR  ",

        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:28900 CVXR QE",
        "VASB:GUR PNER PRAGRE / 800-508-6370 / RYQREYL SRZNYR UNF SNYYRA, ARRQF NFFVFGNAPR");

    qbGrfg("G52",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e30549  UNEINEQ EQ   \eZNYR BA BKLTRA, QVSSVPHYGL OERNGUVAT ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:30549 UNEINEQ EQ",
        "VASB:ZNYR BA BKLTRA, QVSSVPHYGL OERNGUVAT");

    qbGrfg("G53",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e3909  BENATR CY   \e53 LBN SRZNYR  NYYRETVP ERNPGVBA HETRAG PNER ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:3909 BENATR CY",
        "VASB:53 LBN SRZNYR  NYYRETVP ERNPGVBA HETRAG PNER");

    qbGrfg("G54",
        "(Qvfcngpu Zrffntr) VAGBK SRZNYR OYRRQVAT SEBZ GUR NEZ\aCQ BA FPRA",
        "PNYY:VAGBK SRZNYR OYRRQVAT SEBZ GUR NEZ",
        "NQQE:CQ BA FPRA");

    qbGrfg("G55",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \a27599  RZREL EQ   \aSRZNYR UNIVAT N UNEQ GVZR OERNGUVAT ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:27599 RZREL EQ",
        "VASB:SRZNYR UNIVAT N UNEQ GVZR OERNGUVAT");

    qbGrfg("G56",
        "(Qvfcngpu Zrffntr) SVER- NHGB \e  271   \e271 AO RKCERFF YNARF, OBK GEHPX BA SVER ",
        "PNYY:SVER- NHGB",
        "NQQE:271",
        "VASB:271 AO RKCERFF YNARF, OBK GEHPX BA SVER");

    qbGrfg("G57",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e28940  UVQQRA INYYRL   \eYVSRYVAR 888.289.2018\aVAQ/SRZNYR ZRQVPNY RZRETRAPL\aBCE/YHPL\a ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:28940 UVQQRA INYYRL",
        "VASB:YVSRYVAR 888.289.2018 / VAQ/SRZNYR ZRQVPNY RZRETRAPL / BCE/YHPL");

    qbGrfg("G58",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e110  INYRAPVN PVE   \eSRZNYRF PNE EBYYRQ BIRE URE YRT ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:110 INYRAPVN PVE",
        "VASB:SRZNYRF PNE EBYYRQ BIRE URE YRT");

    qbGrfg("G59",
        "(Qvfcngpu Zrffntr) NYNEZF-SVER \e150  OYBFFBZ YA   \eFGNGR NYNEZ 781 2224 VAQVPGVAT FZBXR QRGRPGBE FHO YBG 87 BCE/ORIREYL ",
        "PNYY:NYNEZF-SVER",
        "NQQE:150 OYBFFBZ YA",
        "VASB:FGNGR NYNEZ 781 2224 VAQVPGVAT FZBXR QRGRPGBE FHO YBG 87 BCE/ORIREYL");

    qbGrfg("G60",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e29600  PUNTEVA OYIQ  \e91 le byq srznyr, sryy, fber. Znva pyho ubhfr. ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:29600 PUNTEVA OYIQ",
        "VASB:91 le byq srznyr, sryy, fber. Znva pyho ubhfr.");

    qbGrfg("G61",
        "(Qvfcngpu Zrffntr) QBZRFGVP \e30200  FZVGUSVRYQ EQ   \eURE FBA VF IVBYRAG NAQ NGGNPXVAT URE UHFONAQ UR \a\a" +
        "05/07/2013 20:47:10 Qvfc  ZYE  \a" +
        "BSSVPREF UNIR ZNYR ERFGENVARQ NG GUVF ",

        "PNYY:QBZRFGVP",
        "NQQE:30200 FZVGUSVRYQ EQ",
        "VASB:URE FBA VF IVBYRAG NAQ NGGNPXVAT URE UHFONAQ UR / 05/07/2013 20:47:10 Qvfc  ZYE / BSSVPREF UNIR ZNYR ERFGENVARQ NG GUVF");

    qbGrfg("G62",
        "(Qvfcngpu Zrffntr) ZHGHNY NVQ, TVIRA \e31200  RZREL EQ   \eZHGHNY NVQ FDHNQ SRZNYR YBJ OYBBQ CERFFHER, HAERFCBAFVIR ",
        "PNYY:ZHGHNY NVQ, TVIRA",
        "NQQE:31200 RZREL EQ",
        "VASB:ZHGHNY NVQ FDHNQ SRZNYR YBJ OYBBQ CERFFHER, HAERFCBAFVIR");

    qbGrfg("G63",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e3909  BENATR CYNPR  \eSRZNYR QVMMVARFF NAQ JRNXARFF VA GUR HETRAG PNER ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:3909 BENATR CYNPR",
        "VASB:SRZNYR QVMMVARFF NAQ JRNXARFF VA GUR HETRAG PNER");

    qbGrfg("G64",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e27599  RZREL EQ   \e92 LEB SRZNYR JRNX ABG SRRYVAT JRYY ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:27599 RZREL EQ",
        "VASB:92 LEB SRZNYR JRNX ABG SRRYVAT JRYY");

    qbGrfg("G65",
        "(Qvfcngpu Zrffntr) NFFVFG-SVER QRCNEGZRAG \e3909  BENATR CYNPR  \eFZBYQREVAT OEBJA TNEONTR PNA BHGFVQR OL HETRAG PNER ",
        "PNYY:NFFVFG-SVER QRCNEGZRAG",
        "NQQE:3909 BENATR CYNPR",
        "VASB:FZBYQREVAT OEBJA TNEONTR PNA BHGFVQR OL HETRAG PNER");

    qbGrfg("G66",
        "(Qvfcngpu Zrffntr) FGNYXVAT \e3909  BENATR CYNPR  \e6 ZBAG BYQ ZNYR, HETRAG PNER, QVSSVPHYGL OERNGUVAT ",
        "PNYY:FGNYXVAT",
        "NQQE:3909 BENATR CYNPR",
        "VASB:6 ZBAG BYQ ZNYR, HETRAG PNER, QVSSVPHYGL OERNGUVAT");

    qbGrfg("G67",
        "(Qvfcngpu Zrffntr) NYNEZF-SVER \e3840  BENATR CYNPR  \eTRARENY SVER NYNEZ FUBJVAT THRFG EBBZ ",
        "PNYY:NYNEZF-SVER",
        "NQQE:3840 BENATR CYNPR",
        "VASB:TRARENY SVER NYNEZ FUBJVAT THRFG EBBZ");

    qbGrfg("G68",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e29179  RZREL EQ   \e79 LE BYQ SRZNYR SRYY  UVG URNQ NAQ EVOF ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:29179 RZREL EQ",
        "VASB:79 LE BYQ SRZNYR SRYY  UVG URNQ NAQ EVOF");

    qbGrfg("G69",
        "(Qvfcngpu Zrffntr) ZHGHNY NVQ, ERDHRFGRQ \e70  JVAQVAT EVIRE   \eFDHNQ ARRQRQ / OBK NYNEZ ",
        "PNYY:ZHGHNY NVQ, ERDHRFGRQ",
        "NQQE:70 JVAQVAT EVIRE",
        "VASB:FDHNQ ARRQRQ / OBK NYNEZ");

    qbGrfg("G70",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e3909  BENATR CYNPR  \e3 LE BYQ ERFCVENGBEL QVFGERFF ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:3909 BENATR CYNPR",
        "VASB:3 LE BYQ ERFCVENGBEL QVFGERFF");

    qbGrfg("G71",
        "(Qvfcngpu Zrffntr) NYNEZF-PB QRGRPGBE \e64  J FGBAROEBBX QE   \e ",
        "PNYY:NYNEZF-PB QRGRPGBE",
        "NQQE:64 J FGBAROEBBX QE");

    qbGrfg("G72",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e3909  BENATR CYNPR   \eSRZNYR VA N JUVGRJ ZVAV INA CNEXRQ BHG SEBAG,CULFPU  CNGVRAG, ERSHFVAT GENAFCBEG ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:3909 BENATR CYNPR",
        "VASB:SRZNYR VA N JUVGRJ ZVAV INA CNEXRQ BHG SEBAG,CULFPU  CNGVRAG, ERSHFVAT GENAFCBEG");

    qbGrfg("G73",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e3909  BENATR CYNPR  \eVA GUR HETRAG PNER, ZNYR JVGU NOABEZNY RXT & PURFG CNVAF ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:3909 BENATR CYNPR",
        "VASB:VA GUR HETRAG PNER, ZNYR JVGU NOABEZNY RXT & PURFG CNVAF");

    qbGrfg("G74",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e3655  BENATR CYNPR  \e3 LRNE BYQ UNIVAT N FRVMHER ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:3655 BENATR CYNPR",
        "VASB:3 LRNE BYQ UNIVAT N FRVMHER");

    qbGrfg("G75",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e3909  BENATR CYNPR   \eSRZNYR FUBEG BS OERNGU ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:3909 BENATR CYNPR",
        "VASB:SRZNYR FUBEG BS OERNGU");

    qbGrfg("G76",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e3880  OENVANEQ EQ   \ePNER TVIRE ERCBEGF CNGVRAG, RYQREYL SRZNYR, UNYYHPVANGVAT FHTNE QEBCCVAT\a" +
        "216-926-9695 ",

        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:3880 OENVANEQ EQ",
        "VASB:PNER TVIRE ERCBEGF CNGVRAG, RYQREYL SRZNYR, UNYYHPVANGVAT FHTNE QEBCCVAT / 216-926-9695");

    qbGrfg("G77",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e3880  OENVANEQ EQ   \eRYQREYL SRZNYR, UNYYHPVANGVAT FHTNE QEBCCVAT ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:3880 OENVANEQ EQ",
        "VASB:RYQREYL SRZNYR, UNYYHPVANGVAT FHTNE QEBCCVAT");

    qbGrfg("G78",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e30049  ZVYRF EQ   \eZNYR CBFFVOYR FGBXR ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:30049 ZVYRF EQ",
        "VASB:ZNYR CBFFVOYR FGBXR");

    qbGrfg("G79",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e3695  BENATR CYNPR  \e61 LEB ZNYRF PBYYNCFRQ, ABJ PBAFPVBHF NAQ OERNGUVAT ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:3695 BENATR CYNPR",
        "VASB:61 LEB ZNYRF PBYYNCFRQ, ABJ PBAFPVBHF NAQ OERNGUVAT");

    qbGrfg("G80",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e3795  BENATR CYNPR  269 \eSRZNYR VA YNOBE, JNGRE OEBXRA ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:3795 BENATR CYNPR",
        "NCG:269",
        "VASB:SRZNYR VA YNOBE, JNGRE OEBXRA");

    qbGrfg("G81",
        "(Qvfcngpu Zrffntr) NYNEZF-SVER \e3840  BENATR CYNPR  \eFGNGR NYNEZ 781 2224 VAQVPNGVAT TRARENY SVER NYNEZ BCE/ORIREYL ",
        "PNYY:NYNEZF-SVER",
        "NQQE:3840 BENATR CYNPR",
        "VASB:FGNGR NYNEZ 781 2224 VAQVPNGVAT TRARENY SVER NYNEZ BCE/ORIREYL");

    qbGrfg("G82",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e3860  CVAR PERFG QE  \e82 LE BYQ ZNYR UNF SNYYRA, JVSR PNAABG TRG UVZ HC ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:3860 CVAR PERFG QE",
        "VASB:82 LE BYQ ZNYR UNF SNYYRA, JVSR PNAABG TRG UVZ HC");

    qbGrfg("G83",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e29699  UNEINEQ EQ   \e93 LEB SRZNYR JVGU FRIRER FGBZNPU CNVAF, QVNEERN ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:29699 UNEINEQ EQ",
        "VASB:93 LEB SRZNYR JVGU FRIRER FGBZNPU CNVAF, QVNEERN");

    qbGrfg("G84",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e3883  YNAQRE EQ  1 \eSRZNYR ARRQF VAINYVQ NFFVFG JUB UNF SNYYRA BHG BS ORQ\aPURFGAHG PBHEG ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:3883 YNAQRE EQ",
        "NCG:1",
        "VASB:SRZNYR ARRQF VAINYVQ NFFVFG JUB UNF SNYYRA BHG BS ORQ / PURFGAHG PBHEG");

    qbGrfg("G85",
        "(Qvfcngpu Zrffntr) FDHNQ PNYY-TRARENY \e3795  BENATR CYNPR  \eZNYR GBBX ZRQVPVAR , HAERFCBAFIVR OHG OERNGUVAT ",
        "PNYY:FDHNQ PNYY-TRARENY",
        "NQQE:3795 BENATR CYNPR",
        "VASB:ZNYR GBBX ZRQVPVAR , HAERFCBAFIVR OHG OERNGUVAT");

  }
  
  choyvp fgngvp ibvq znva(Fgevat[] netf) {
    arj BUPhlnubtnPbhaglCnefreGrfg().trarengrGrfgf("G1");
  }
}