cnpxntr arg.narv.pnqcntr.cnefref.BU;

vzcbeg arg.narv.pnqcntr.cnefref.OnfrCnefreGrfg;

vzcbeg bet.whavg.Grfg;

/*
Zrepre Pbhagl, BU 

Pbagnpg: Npgvir911
Ntrapl anzr: Zrepre Pbhagl Furevss'f Bssvpr
Ybpngvba: Pryvan, BU, Havgrq Fgngrf
Fraqre: XUBSSUVA

29 YBPNGVBA: 4835 FG EGR 29 PRYVAN  ORGJRRA FG EGR 118-FBHGU / SYRRGSBBG EQ PBZZRAGF: VAZNGR VA NPGVIR FVRMHER;
29 YBPNGVBA: 801 CEB QE PRYVAN ORGJRRA QRIBAFUVER QE /  TENAQ YNXR EQ PBZZRAGF: QE JUVGRF BSSVPR, ZNYR FHOW CBFF URNEG NGGNPX; HFR ONPX QBBE;
29 YBPNGVBA: 410 TENAQ YNXR EQ PRYVAN  ORGJRRA ZNL FG /  ENVYEBNQ GENPXF PBZZRAGF: FZNFURQ SVATRE, FHOW TBVAT VA NAQ BHG BS PBAPVBHFARFF;
GX YBPNGVBA: 101 A ZNVA FG PRYVAN  ORGJRRA J ZNEXRG FG / J YVIVATFGBA FG PBZZRAGF: GRFG GRFG
GX YBPNGVBA: 4835 FG EGR 29 PRYVAN  ORGJRRA FG EGR 118-FBHGU / SYRRGSBBG EQ PBZZRAGF: GRFG GRFG
GX YBPNGVBA: 4835 FG EGR 29 PRYVAN  ORGJRRA FG EGR 118-FBHGU / SYRRGSBBG EQ PBZZRAGF: GRFG
GX YBPNGVBA: 4835 FG EGR 29 PRYVAN  ORGJRRA FG EGR 118-FBHGU / SYRRGSBBG EQ PBZZRAGF: 48565
20Q YBPNGVBA: 7239 EVYRL EQ PRYVAN  ORGJRRA FG EGR 29 /  BYQGBJA EQ PBZZRAGF: NHT PB GENAF; WNFBA FGRVA VF P24; GUERNGRAVAT;\aCNEGVRF NER FRCNENGRQ;\aPBAGNPGRQ ZHAV PEG CRE 5422; NQI WNFBA FGRVA VF BA CEBONGVBA NAQ JNAGF GB XABJ JUNG
GX YBPNGVBA: 4835 FG EGR 29 PRYVAN  ORGJRRA FG EGR 118-FBHGU / SYRRGSBBG EQ PBZZRAGF: GRFG\aGRFG VASB\aGRFG VASB 2
GX YBPNGVBA: 4835 FG EGR 29 PRYVAN  ORGJRRA FG EGR 118-FBHGU / SYRRGSBBG EQ PBZZRAGF: GRFG\aGRFG VASB
GX YBPNGVBA: 101 A ZNVA FG PRYVAN  ORGJRRA J ZNEXRG FG / J YVIVATFGBA FG PBZZRAGF: GRFG\aGRFG\aGRFG\aGRFG
GX YBPNGVBA: 4835 FG EGR 29 PRYVAN  ORGJRRA FG EGR 118-FBHGU / SYRRGSBBG EQ PBZZRAGF: GRFG\aGRFG\aGRFG\aGRFG
GB: 900\aSEBZ: XUBSSUVA\aZFT: [XUBSSUVA]-- - Angher: Sver - Ybpngvba:     751.00:[XUBSSUVA]-- - Angher: Sver - Ybpngvba: 751.00 QRSBEQ FG Fhvgr:YBG 121 PRYVAN - Pbzzragf: YBA:-084.58120 YNG:+040.53751 PBS: 48290 YBG 121; SRZ NQI'Q GEYE SHYY BS FZBXR;
GB: FD8\aSEBZ: XUBSSUVA\aZFT: [XUBSSUVA]- ANGHER:        4 YBPNGVBA: FG WBUAF EQ:[XUBSSUVA]- ANGHER: 4 YBPNGVBA: FG WBUAF EQ / FG EGR 274 ZNEVN FGRVA PBZZRAGF: YBA:-084.47872 YNG:+040.43679 PBS: 25 GEX UVG CBYR, BHG VAGB SVRYQ, THL VF YNLVAT BA GUR TEBHAQ, PNAABG NQI ERS JUNG GLCR BS VAWHEVRF; QEBIR OL VG NAQ FGBCCRQ R/BS VG; 2AQ PNYYRE 'OERGG' NQI'Q UVTU IBYGNTR YVAR VF QBJA; 1 CXHC, 2 ZNYRF NER BHG JNYXVAT NEBHAQ, JRAG ONPX GB GRYY GURZ GB FGNL NJNL SEBZ GUR YVAR; (PFP) 0952UEF ERP'Q PNYY SEBZ ZNGG OBAABEBAG (419-778-9670) UR NQI GUR QEVIRE JNF ORUVAQ UVZ N
GB: FD3\aSEBZ: XUBSSUVA\aZFT: [XUBSSUVA]- ANGHER:        4 YBPNGVBA: FG WBUAF EQ:[XUBSSUVA]- ANGHER: 4 YBPNGVBA: FG WBUAF EQ / FG EGR 274 ZNEVN FGRVA PBZZRAGF: YBA:-084.47872 YNG:+040.43679 PBS: 25 GEX UVG CBYR, BHG VAGB SVRYQ, THL VF YNLVAT BA GUR TEBHAQ, PNAABG NQI ERS JUNG GLCR BS VAWHEVRF; QEBIR OL VG NAQ FGBCCRQ R/BS VG; 2AQ PNYYRE 'OERGG' NQI'Q UVTU IBYGNTR YVAR VF QBJA; 1 CXHC, 2 ZNYRF NER BHG JNYXVAT NEBHAQ, JRAG ONPX GB GRYY GURZ GB FGNL NJNL SEBZ GUR YVAR; (PFP) 0952UEF ERP'Q PNYY SEBZ ZNGG OBAABEBAG (419-778-9670) UR NQI GUR QEVIRE JNF ORUVAQ UVZ N
GB: FD5\aSEBZ: XUBSSUVA\aZFT: [XUBSSUVA]- ANGHER:       GX YBPNGVBA: 412 F SENAX:[XUBSSUVA]- ANGHER: GX YBPNGVBA: 412 F SENAXYVA FG EBPXSBEQ ORGJRRA SVEFG FG / CNAGURE NYYRL PBZZRAGF: GRFG QNGN NPGVIR911 GRFG QNGN
GB: FD4\aSEBZ: XUBSSUVA\aZFT: [XUBSSUVA]- ANGHER:       GX YBPNGVBA: 412 F SENAX:[XUBSSUVA]- ANGHER: GX YBPNGVBA: 412 F SENAXYVA FG EBPXSBEQ ORGJRRA SVEFG FG / CNAGURE NYYRL PBZZRAGF: GRFG QNGN NPGVIR911 GRFG QNGN
GB: FD9\aSEBZ: XUBSSUVA\aZFT: [XUBSSUVA]- ANGHER:       GX YBPNGVBA: 314 F ZNVA:[XUBSSUVA]- ANGHER: GX YBPNGVBA: 314 F ZNVA FG PRYVAN ORGJRRA JNEERA FG / PRAGRE FG PBZZRAGF: GRFG AHZORE 22
GB: FD6\aSEBZ: XUBSSUVA\aZFT: [XUBSSUVA]- ANGHER:       GX YBPNGVBA: 314 F ZNVA:[XUBSSUVA]- ANGHER: GX YBPNGVBA: 314 F ZNVA FG PRYVAN ORGJRRA JNEERA FG / PRAGRE FG PBZZRAGF: GRFG AHZORE 22
GB: FD2\aSEBZ: XUBSSUVA\aZFT: [XUBSSUVA]- ANGHER:       GX YBPNGVBA: 314 F ZNVA:[XUBSSUVA]- ANGHER: GX YBPNGVBA: 314 F ZNVA FG PRYVAN ORGJRRA JNEERA FG / PRAGRE FG PBZZRAGF: GRFG AHZORE 22
GB: FD1\aSEBZ: XUBSSUVA\aZFT: [XUBSSUVA]- ANGHER:       GX YBPNGVBA: 314 F ZNVA:[XUBSSUVA]- ANGHER: GX YBPNGVBA: 314 F ZNVA FG PRYVAN ORGJRRA JNEERA FG / PRAGRE FG PBZZRAGF: GRFG AHZORE 22
GB: FD9\aSEBZ: XUBSSUVA\aZFT: [XUBSSUVA]- ANGHER:       GX YBPNGVBA: 261 R ZNVA:[XUBSSUVA]- ANGHER: GX YBPNGVBA: 261 R ZNVA FG FG URAEL ORGJRRA F FLPNZBER FG / JNYAHG FG PBZZRAGF: GRFG PNYY ERZBGR CEVAGVAT NAQ NPGVIR911
GB: FD6\aSEBZ: XUBSSUVA\aZFT: [XUBSSUVA]- ANGHER:       GX YBPNGVBA: 261 R ZNVA:[XUBSSUVA]- ANGHER: GX YBPNGVBA: 261 R ZNVA FG FG URAEL ORGJRRA F FLPNZBER FG / JNYAHG FG PBZZRAGF: GRFG PNYY ERZBGR CEVAGVAT NAQ NPGVIR911
GB: FD2\aSEBZ: XUBSSUVA\aZFT: [XUBSSUVA]- ANGHER:       GX YBPNGVBA: 261 R ZNVA:[XUBSSUVA]- ANGHER: GX YBPNGVBA: 261 R ZNVA FG FG URAEL ORGJRRA F FLPNZBER FG / JNYAHG FG PBZZRAGF: GRFG PNYY ERZBGR CEVAGVAT NAQ NPGVIR911
GB: FD1\aSEBZ: XUBSSUVA\aZFT: [XUBSSUVA]- ANGHER:       GX YBPNGVBA: 261 R ZNVA:[XUBSSUVA]- ANGHER: GX YBPNGVBA: 261 R ZNVA FG FG URAEL ORGJRRA F FLPNZBER FG / JNYAHG FG PBZZRAGF: GRFG PNYY ERZBGR CEVAGVAT NAQ NPGVIR911
GB: FD9\aSEBZ: XUBSSUVA\aZFT: [XUBSSUVA]- ANGHER:       GX YBPNGVBA: 800 R JNLAR:[XUBSSUVA]- ANGHER: GX YBPNGVBA: 800 R JNLAR FG PRYVAN ORGJRRA ZRNQBJIVRJ QE / TENAQ YNXR EQ PBZZRAGF: GRFG PNYY; GRFG PNYY; GRFG PNYY; ZNA JVGU ONQ GBBGU
GB: FD6\aSEBZ: XUBSSUVA\aZFT: [XUBSSUVA]- ANGHER:       GX YBPNGVBA: 800 R JNLAR:[XUBSSUVA]- ANGHER: GX YBPNGVBA: 800 R JNLAR FG PRYVAN ORGJRRA ZRNQBJIVRJ QE / TENAQ YNXR EQ PBZZRAGF: GRFG PNYY; GRFG PNYY; GRFG PNYY; ZNA JVGU ONQ GBBGU
GB: FD2\aSEBZ: XUBSSUVA\aZFT: [XUBSSUVA]- ANGHER:       GX YBPNGVBA: 800 R JNLAR:[XUBSSUVA]- ANGHER: GX YBPNGVBA: 800 R JNLAR FG PRYVAN ORGJRRA ZRNQBJIVRJ QE / TENAQ YNXR EQ PBZZRAGF: GRFG PNYY; GRFG PNYY; GRFG PNYY; ZNA JVGU ONQ GBBGU
GB: FD1\aSEBZ: XUBSSUVA\aZFT: [XUBSSUVA]- ANGHER:       GX YBPNGVBA: 800 R JNLAR:[XUBSSUVA]- ANGHER: GX YBPNGVBA: 800 R JNLAR FG PRYVAN ORGJRRA ZRNQBJIVRJ QE / TENAQ YNXR EQ PBZZRAGF: GRFG PNYY; GRFG PNYY; GRFG PNYY; ZNA JVGU ONQ GBBGU
GB: FD5\aSEBZ: XUBSSUVA\aZFT: [XUBSSUVA]- ANGHER:       GX YBPNGVBA: 841 FG EGR:[XUBSSUVA]- ANGHER: GX YBPNGVBA: 841 FG EGR 29 PRYVAN ORGJRRA FG EGR 49 / JNONFU EQ PBZZRAGF: GRFG ZNYR FHOWRPG UHEG UNAQ
GB: FD4\aSEBZ: XUBSSUVA\aZFT: [XUBSSUVA]- ANGHER:       GX YBPNGVBA: 841 FG EGR:[XUBSSUVA]- ANGHER: GX YBPNGVBA: 841 FG EGR 29 PRYVAN ORGJRRA FG EGR 49 / JNONFU EQ PBZZRAGF: GRFG ZNYR FHOWRPG UHEG UNAQ
GB: FD7\aSEBZ: XUBSSUVA\aZFT: [XUBSSUVA]- ANGHER:       GX YBPNGVBA: 700 A FRPBA:[XUBSSUVA]- ANGHER: GX YBPNGVBA: 700 A FRPBAQ FG PBYQJNGRE ORGJRRA UNEQVA FG / ORYY EQ PBZZRAGF: GRFG PNYY
GB: FD10\aSEBZ: XUBSSUVA\aZFT: [XUBSSUVA]- ANGHER:       GX YBPNGVBA: 700 A FRPB:[XUBSSUVA]- ANGHER: GX YBPNGVBA: 700 A FRPBAQ FG PBYQJNGRE ORGJRRA UNEQVA FG / ORYY EQ PBZZRAGF: GRFG PNYY
GB: FD9\aSEBZ: XUBSSUVA\aZFT: [XUBSSUVA]- ANGHER:       GX YBPNGVBA: 1610 VAQHFG:[XUBSSUVA]- ANGHER: GX YBPNGVBA: 1610 VAQHFGEVNY CNEX QE PRYVAN ORGJRRA TENAQ YNXR EQ / UNIRZNAA EQ PBZZRAGF: GRFG PNYY
GB: FD6\aSEBZ: XUBSSUVA\aZFT: [XUBSSUVA]- ANGHER:       GX YBPNGVBA: 1610 VAQHFG:[XUBSSUVA]- ANGHER: GX YBPNGVBA: 1610 VAQHFGEVNY CNEX QE PRYVAN ORGJRRA TENAQ YNXR EQ / UNIRZNAA EQ PBZZRAGF: GRFG PNYY
GB: FD2\aSEBZ: XUBSSUVA\aZFT: [XUBSSUVA]- ANGHER:       GX YBPNGVBA: 1610 VAQHFG:[XUBSSUVA]- ANGHER: GX YBPNGVBA: 1610 VAQHFGEVNY CNEX QE PRYVAN ORGJRRA TENAQ YNXR EQ / UNIRZNAA EQ PBZZRAGF: GRFG PNYY
GB: FD1\aSEBZ: XUBSSUVA\aZFT: [XUBSSUVA]- ANGHER:       GX YBPNGVBA: 1610 VAQHFG:[XUBSSUVA]- ANGHER: GX YBPNGVBA: 1610 VAQHFGEVNY CNEX QE PRYVAN ORGJRRA TENAQ YNXR EQ / UNIRZNAA EQ PBZZRAGF: GRFG PNYY
GB: FD7\aSEBZ: XUBSSUVA\aZFT: [XUBSSUVA]- ANGHER:       GX YBPNGVBA: 5656 ZBAEBR:[XUBSSUVA]- ANGHER: GX YBPNGVBA: 5656 ZBAEBR EQ PRYVAN ORGJRRA ZRLRE EQ / HF EGR 127 PBZZRAGF: GRFG PNYY QNGN SBE FD3
GB: FD10\aSEBZ: XUBSSUVA\aZFT: [XUBSSUVA]- ANGHER:       GX YBPNGVBA: 5656 ZBAEB:[XUBSSUVA]- ANGHER: GX YBPNGVBA: 5656 ZBAEBR EQ PRYVAN ORGJRRA ZRLRE EQ / HF EGR 127 PBZZRAGF: GRFG PNYY QNGN SBE FD3
GB: FD8\aSEBZ: XUBSSUVA\aZFT: [XUBSSUVA]- ANGHER:       GX YBPNGVBA: 5656 ZBAEBR:[XUBSSUVA]- ANGHER: GX YBPNGVBA: 5656 ZBAEBR EQ PRYVAN ORGJRRA ZRLRE EQ / HF EGR 127 PBZZRAGF: GRFG PNYY QNGN SBE FD3
GB: FD3\aSEBZ: XUBSSUVA\aZFT: [XUBSSUVA]- ANGHER:       GX YBPNGVBA: 5656 ZBAEBR:[XUBSSUVA]- ANGHER: GX YBPNGVBA: 5656 ZBAEBR EQ PRYVAN ORGJRRA ZRLRE EQ / HF EGR 127 PBZZRAGF: GRFG PNYY QNGN SBE FD3
GB: FD1\aSEBZ: XUBSSUVA\aZFT: [XUBSSUVA]- ANGHER:       GX YBPNGVBA: 752 WVZ YNP:[XUBSSUVA]- ANGHER: GX YBPNGVBA: 752 WVZ YNPURL QE FG URAEL ORGJRRA F RNFGREA NIR / QRNQ RAQ PBZZRAGF: NYY CNTR GRFG PNYY
GB: FD1\aSEBZ: XUBSSUVA\aZFT: [XUBSSUVA]- ANGHER:       GX YBPNGVBA: 252 J ZNVA:[XUBSSUVA]- ANGHER: GX YBPNGVBA: 252 J ZNVA FG FG URAEL ORGJRRA JRFGREA NI / F FLPNZBER FG PBZZRAGF: SVER QRCG

Pbagnpg: Npgvir911
Ntrapl anzr: Zbagrmhzn SQ
Ybpngvba: Pryvan, BU, Havgrq Fgngrf

29 YBPNGVBA: 202 A ZNVA FG PRYVAN  ORGJRRA R YVIVATFGBA FG / R  SHYGBA FG PBZZRAGF: ZNXVAT EHA SEBZ FGNGVBA;\aCNTRQ HAVGF 2,12,17;
28 YBPNGVBA: 6805 FG EGR 219 PRYVAN  ORGJRRA OEBBXFVQR QE /  ANTL EQ PBZZRAGF: GUVF VF N GRFG RAGEL BAYL;

Pbagnpg: Npgvir911
Ntrapl anzr: Pbyqjngre SQ
Ybpngvba: Pbyqjngre, BU, Havgrq Fgngrf

28 YBPNGVBA: 5087 FG EGR 118 PBYQJNGRE  ORGJRRA ORYY EQ /  OHFPUBE EQ PBZZRAGF: YBA:-084.62873 YNG:+040.49167 PBS:     28\aCBFF ONEA SVER;

Pbagnpg: Npgvir911
Ntrapl anzr: Ebpxsbeq SQ
Ybpngvba: Ebpxsbeq, BU, Havgrq Fgngrf

4 YBPNGVBA: GNZN JRFG BS RENFGHF QHEOVA PBZZRAGF: YBA:-084.71525 YNG:+040.63321 PBS: 16\aPBHYQ URNE SRZNYR NFX VS FBZRBAR UVG URNQ GURA YVAR UHAT HC;\aEBYYRQ PNE; OYH SBEQ SBPHF; BHG BS GUR IRU;\aQEVIRE VF URNGURE NAQ NJNXR; ONPX/AR
29 YBPNGVBA: 201 F ZNVA FG EBPXSBEQ  ORGJRRA CRNEY FG /  FBHGU FG PBZZRAGF: GRFG GRFG GRFG

Pbagnpg: Npgvir911
Ntrapl anzr: Ebpxsbeq RZF (ARRQ CULFVPNY NQQERFF)
Ybpngvba: Ebpxsbeq, BU, Havgrq Fgngrf

29 YBPNGVBA: 10731 FG EGR 118 EBPXSBEQ  ORGJRRA FG EGR 707 /  CHEQL EQ PBZZRAGF: NOQBZVANY CNVA;
29 YBPNGVBA: 105 J PBYHZOVN FG EBPXSBEQ  ORGJRRA A ZNVA FG / A SENAXYVA FG PBZZRAGF: NPGVIR FRVMHER
29 YBPNGVBA: 11900 GBZYVAFBA EQ IRARQBPVN  ORGJRRA UNZVYGBA EQ /  FURYYRL EQ PBZZRAGF: YRTF NER FRNCVAT JNGRE;
GX YBPNGVBA: 10731 FG EGR 118 EBPXSBEQ  ORGJRRA FG EGR 707 /  CHEQL EQ PBZZRAGF: GRFG PNYY SEBZ FB
GX YBPNGVBA: 7561 FG EGR 118 EBPXSBEQ  ORGJRRA PNEZRY PUHEPU EQ /  ZVYYRE EQ PBZZRAGF: GRFG\aGRFG\aGRFG\aGRFG

Pbagnpg: Npgvir911
Ntrapl anzr: Pryvan SQ
Ybpngvba: Pryvan, BU, Havgrq Fgngrf

29 YBPNGVBA: 1506 ZRNQBJIVRJ QE FHVGR: NCG 124 PRYVAN  ORGJRRA ZLREF EQ /  XRAFVATGBA YA PBZZRAGF: IBZVGVAT JVGU UNAQ AHZOARFF;
29 YBPNGVBA: 1209 PNAGREOHEL QE PRYVAN  ORGJRRA XVATFJBBQ QE /  UREVGNTR QE PBZZRAGF: YBA:-084.56039 YNG:+040.56533 PBS:      0 PCS:GJPOY\aQNHTUGRE SRYY BHGFVQR, NAQ VF IREL JRNX,
29 YBPNGVBA: 1123 CEVAPRGBA NI PRYVAN  ORGJRRA ZLREF EQ /  XVATFJBBQ QE PBZZRAGF: YBA:-084.56524 YNG:+040.56203 PBS:     28\aCNVA SEBZ URZEBVQF; UNQ XARR FHETREL YNFG JRRX PNHFVAT N SYNER HC;
29 YBPNGVBA: 139 A ZNVA FG EBPXSBEQ  ORGJRRA ZNEXRG FG /  PBYHZOVN FG PBZZRAGF: YBA:-084.57979 YNG:+040.66758 PBS:  43899\aSVATRE TBG
29Z YBPNGVBA: 618 PHZOREYNAQ QE PRYVAN  ORGJRRA QRIBAFUVER QE / QRIBAFUVER PG PBZZRAGF: YBA:-084.54305 YNG:+040.55895 PBS:      0\aSRZNYR FHOW SRYY VA LNEQ, ARRQF URYC HC;
29 YBPNGVBA: 632 TEBIR FG FHVGR: NCG 8 PRYVAN  ORGJRRA A OENAQBA NI /  QRNQ RAQ PBZZRAGF: YBA:-084.54305 YNG:+040.55895 PBS:      0\a36 LBN SRZNYR UNIVAT UNEQ GVZR OERNGUVAT;\aORRA FVPX GUR CNFG PBHCYR BS QNLF;
PYBFVAT QNGR : 03-18-15 GUEH 03-25-15\a\aQHENGVBA: 7 QNLF\a\aGLCR BS JBEX: OEVQTR ERCNVE;\a\aJBEX OL: PBAGENP
4 YBPNGVBA: FG EGR 29 / FG EGR 49 PRYVAN PBZZRAGF: FBA UNAQ VF OYRRQVAT NAQ ONPX UHEGF; ABEGU BS 29; VF 26 LBN; PURIL RDHVABK OYX;\aNCCEBK 3 ZV ABEGU BS VAGREFRPGVBA;
4 YBPNGVBA: SYRRGSBBG EQ / FG EGR 29 PRYVAN
29Z YBPNGVBA: 1705 R ZNEXRG FG PRYVAN  ORGJRRA ONLIVRJ QE /  YNXRIVRJ QE PBZZRAGF: YBA:-084.52689 YNG:+040.55783 PBS:  48290\aSRZNYR VF QBJA; ABG UHEG OHG VA GUR FABJ;
29 YBPNGVBA: 500 OEHAF NI FHVGR: NCG 36 PRYVAN  ORGJRRA ZVPUNRY NI /  WNZRF QE PBZZRAGF: YBA:-084.52689 YNG:+040.55783 PBS:  43899\aZBZ SRYY NTNVA; HANOYR GB TRG URE HC; ONPX & PURFG NER UHEGVAT;\aHFR GUR ONPX QBBE;
29 YBPNGVBA: 209 R CRNEY FG EBPXSBEQ  ORGJRRA F ZNVA FG /  RNFG FG PBZZRAGF: YBA:-084.57979 YNG:+040.66758 PBS:  43899\a14 LE BYQ FBA VF UNIVAT N FRVMHER; UNFA'G UNQ BAR SBE 7 LEF; UR GNXRF ZRQVPNGVBA;
28 YBPNGVBA: ZVYYRE EQ/  R BS 127 PBZZRAGF: FHOW JNF OHEAVAT TENFF NAQ VG TBG NJNL SEBZ UVZ; SQ TBVAT BHG GB PBAGNVA VG;
29 YBPNGVBA: 729 RYZ FG PRYVAN ORGJRRA FBHGU FG /  CVAR FG PBZZRAGF: YBA:-084.58017 YNG:+040.54190 PBS:      0 PCS:GJPOY\aZBGURE VF UNIVAT CNVA VA NEZF, YNOBERQ OERNGUVAT, UNIR GNXRA 1 AVGEB NAQ AB ZBER CNVAF VA NEZ;
29Z YBPNGVBA: 321 A ZVYY FG PRYVAN  ORGJRRA J SHYGBA FG /  J NAGUBAL FG PBZZRAGF: 91LBN SRZ, YNOBERQ OERNGUVAT NAQ FCRRPU, FBHAQF PBASHFRQ; JVYZN OHEAF;\aERD OHGGBA ERFRG;
29 YBPNGVBA: 500 J JNLAR FG FHVGR: NCG 117 PRYVAN  ORGJRRA ZNPXVANJ FG /  A OENAQBA FG PBZZRAGF: SZ ARRQVAT FDHNQ;
29 YBPNGVBA: PBZZRAGF: SZ ARRQVAT FDHNQ;
4 YBPNGVBA: 8065 FG EGR 197 PRYVAN  ORGJRRA UBJVPX EQ /  UBJVPX EQ PBZZRAGF: 1 IRU VA SEBAG BS UBHFR; UVG CBYR;\aQEVIRE UNFA'G TBGGRA BHG;\aFVY 4Q PNE;
29 YBPNGVBA: 303 J NAGUBAL FG PRYVAN  ORGJRRA A FHTNE FG /  A ZVYY FG PBZZRAGF: YBA:-084.54305 YNG:+040.55895 PBS:      0\aFGBZNPU CNVA
29 YBPNGVBA: 905 PURFGAHG FG PRYVAN  ORGJRRA JVYYBJ FG /  URZYBPX FG PBZZRAGF: ZNYR QBRFA'G SRRY JRYY;

Pbagnpg: Npgvir911
Ntrapl anzr: Pbyqjngre RZF
Ybpngvba: Pbyqjngre, BU, Havgrq Fgngrf

29 YBPNGVBA: 911 A FRIRAGU FG FHVGR: NCG 2 PBYQJNGRE  ORGJRRA OVGGREFJRRG QE /  QRNQ RAQ PBZZRAGF: YBA:-084.62210 YNG:+040.48632 PBS:     28\aCBFF ZVAV FGEBXR;
29 YBPNGVBA: 5301 YNXR QE PRYVAN ORGJRRA ONLIVRJ EQ /  QRNQ RAQ PBZZRAGF: FUBEGARFF BS OERNGU; NOBHG GB CNFF BHG; 95LBN;
29 YBPNGVBA: 100 QBA QRFPU QE PBYQJNGRE  ORGJRRA JBBQIVRJ QE / EBFR QE PBZZRAGF: YBA:-084.61918 YNG:+040.48219 PBS:      0 PCS:GJPOY\aERF UNF YBJ OYBBQ CERFFHER VF NYREG OHG FYRRCL;\aZNVA RAGENAPR NCG 23 VA NFFVFGRQ YVIVAT;
29 YBPNGVBA: 6620 OEHPR EQ FHVGR: YBG 12 PRYVAN  ORGJRRA QRNQ RAQ /  FG EGR 219 PBZZRAGF: YBA:-084.54571 YNG:+040.49559 PBS:    719\aSRRY UBG PYNZL; PNA ABG OERNGU JRYY;
29 YBPNGVBA: 600 A ZVYY FG PBYQJNGRE  ORGJRRA CNEX FG /  QRNQ RAQ PBZZRAGF: YBA:-084.62455 YNG:+040.49073 PBS:      0\a29LBN ZNYR UNIVAT FRVMHER, UNQ BAR 4 LRNEF NTB;
29 YBPNGVBA: 8583 FG EGR 219 FHVGR: YBG 436 PRYVAN  ORGJRRA ORUZ EQ /  ZREPRE NHTYNVMR YA PBZZRAGF: YBA:-084.47106 YNG:+040.49476 PBS:      0 PCS:GJPOY\aSRZNYR SRYY VA FUBJRE NAQ VF VA N FRVMHER;\aVF OERNGUVAT;
29 YBPNGVBA: 8583 FG EGR 219 PRYVAN  ORGJRRA ORUZ EQ /  ZREPRE NHTYNVMR YA PBZZRAGF: YBA:-084.47106 YNG:+040.49476 PBS:      0 PCS:GJPOY\aSRZNYR SRYY VA FUBJRE NAQ VF VA N FRVMHER;
29 YBPNGVBA: 100 QBA QRFPU QE PBYQJNGRE  ORGJRRA JBBQIVRJ QE / EBFR QE PBZZRAGF: YBA:-084.61918 YNG:+040.48219 PBS:      0 PCS:GJPOY\aQBBE #6, ERFQ J/3UE YBAT ABFR OYRRQ;
29 YBPNGVBA: 5477 XNENSVG EQ PRYVAN  ORGJRRA FG EGR 219 /  PBGGBAJBBQ EQ PBZZRAGF: YBA:-084.54305 YNG:+040.55895 PBS:      0\aSRZNYR UNF ORRA YNLVAT GURER NAQ ABG EVTUG;
29 YBPNGVBA: 100 QBA QRFPU QE PBYQJNGRE  ORGJRRA JBBQIVRJ QE / EBFR QE PBZZRAGF: YBA:-084.61918 YNG:+040.48219 PBS:      0 PCS:GJPOY\aERFVQRAG UNIVAT PNEQVNP VFFHRF; CHYFR VF WHZCVAT SEBZ 40'F GB 90'F; WHFG ABG SRRYVAT JRYY; UR VF BA
29 YBPNGVBA: 830 J ZNVA FG FHVGR: EZ 3 PBYQJNGRE  ORGJRRA PRQNE FG /  JBBQIVRJ QE PBZZRAGF: YVAQN JRYYZNA BSSVPR, 65 LRNE BYQ JVGU FUBEGARFF BS OERNGU NAQ PURFG CNVA;\aTB GB ONPX BS OHVYQVAT GB GUR ABEGUREA ZBFG QBBEF;\a(FNF) 0856UEF

Pbagnpg: Npgvir911
Ntrapl anzr: Fg. Urael RZF
Ybpngvba: Fg. Urael, BU, Havgrq Fgngrf

29 YBPNGVBA: 136 J OHGYRE FG SG ERPBIREL  ORGJRRA SBEG FVGR FG /  TRBETR FG PBZZRAGF: ZBZ ARRQF URYC UNF PENZCF VA YRTF NAQ PNAG ZBIR;
29 YBPNGVBA: 1 PBBCRE SNEZ QE FG URAEL  ORGJRRA QRNQ RAQ /  PBBCRE NI PBZZRAGF: YBA:-084.62152 YNG:+040.42702 PBS:      0 PCS:GJPOY\aHAXABJA; TBG UHEG;\aHFR QBBE 1;
29 YBPNGVBA: 232 R PBYHZOHF FG FHVGR: NCG 1 FG URAEL  ORGJRRA BNX FG / F JNYAHG FG PBZZRAGF: PNAPRE CNGVRAG VF IREL JRNX; HANOYR GB FGNAQ;
29 YBPNGVBA: 522 JRFGREA NI FG URAEL  ORGJRRA JNFUVATGBA FG / OHEXRGGFIVYYR FG URAEL EQ PBZZRAGF: YBA:-084.64663 YNG:+040.41950 PBS:      0 PCS:GJPOY\aCBFF OYBBQ PYBG;\aAHEFVAT QBBE;

*/
choyvp pynff BUZreprePbhaglCnefreGrfg rkgraqf OnfrCnefreGrfg {
  
  choyvp BUZreprePbhaglCnefreGrfg() {
    frgCnefre(arj QhzzlCnefre(), "ZREPRE PBHAGL", "BU");
  }
  
  @Grfg
  choyvp ibvq grfgCnefre() {

  }
  
  choyvp fgngvp ibvq znva(Fgevat[] netf) {
    arj BUZreprePbhaglCnefreGrfg().trarengrGrfgf("G1");
  }
}