package net.anei.cadpage.parsers.NJ;

import net.anei.cadpage.parsers.MsgInfo.Data;
import net.anei.cadpage.parsers.dispatch.DispatchA9Parser;

/*
Ocean City County, NJ
Contact: Active911
Agency name: Bayville Fire Company Location: Bayville, NJ 
Sender: Fire_Records  

(Rip and Run Report) Rip and Run Report\n\n~\nLocation Information:\n\nLocation:~33~WOODLAND~RD~\nCommon Name:~ST BARNABAS CHURCH - BERKELEY @ WOODLAND/CHAIN\nVenue:~Berkeley Township\nCross Streets~\nSYLVAN LAKE BLVD / CHAIN BLVD\nQuadrant:~ST17\nDistrict:~SQ13\n~\nCall Information:\n\nCall Number:~91096\nCall Type:~ Fire Information\nSource:~Telephone\nPriority:~ Administrative\nStatus:~In Progress\nCaller:~\nCall Date/Time:~07/12/2012 12:56:40\nDispatch Date/Time:~07/12/2012 12:59:49\nArrive Date/Time:~\nClear Date/Time:~\nEnroute Date/Time:~\nLatest Unit Cleared Date/Time:~\n~\nIncident Number(s)\n~\nUnits Sent:~1\nST17D~\n\nAlerts:\n~\nLocation Alerts\n\nPerson Alerts\n\nVehicle Alerts\n~~\nNarrative:\n\nNarrative Time~Narrative
(Rip and Run Report) Rip and Run Report\n\n~\nLocation Information:\n\nLocation:~445~RT~9~\nCommon Name:~SHOPRITE - BERKELEY\nVenue:~Berkeley Township\nCross Streets~\nFREDERICK DR / KORMAN RD\n OCEAN GATE DR\nQuadrant:~ST17\nDistrict:~SQ13\n~\nCall Information:\n\nCall Number:~91184\nCall Type:~ Landing Zone\nSource:~Telephone\nPriority:~ Low\nStatus:~In Progress\nCaller:~\nCall Date/Time:~07/12/2012 14:24:12\nDispatch Date/Time:~07/12/2012 14:24:46\nArrive Date/Time:~\nClear Date/Time:~\nEnroute Date/Time:~07/12/2012 14:34:16\nLatest Unit Cleared Date/Time:~\n~\nIncident Number(s)\n2012-00000186~~Bayville Fire Department\n2012-00008054~~Paid ALS\n~\nUnits Sent:~2\nMONOC1, F1700~\n\nAlerts:\n~\nLocation Alerts\n\nPerson Alerts\n\nVehicle Alerts\n~~\nNarrative:\n\nNarrative Time~Narrative
(Rip and Run Report) Rip and Run Report\n\n~\nLocation Information:\n\nLocation:~33~KORMAN~RD~APT A12\nVenue:~Berkeley Township\nCross Streets~\nESPLANADE WAY / RT 9\n OCEAN GATE DR\nQuadrant:~ST17\nDistrict:~SQ13\n~\nCall Information:\n\nCall Number:~91504\nCall Type:~ CO Alarm\nSource:~911\nPriority:~ High\nStatus:~In Progress\nCaller:~\nCall Date/Time:~07/12/2012 18:56:54\nDispatch Date/Time:~07/12/2012 18:58:36\nArrive Date/Time:~\nClear Date/Time:~\nEnroute Date/Time:~\nLatest Unit Cleared Date/Time:~\n~\nIncident Number(s)\n2012-00000187~~Bayville Fire Department\n~\nUnits Sent:~1\nST17~\n\nAlerts:\n~\nLocation Alerts\n\nPerson Alerts\n\nVehicle Alerts\n~~\nNarrative:\n\nNarrative Time~Narrative\n07/12/12 18:58:15~Nature Of Call: NO ONE FEELING ILL WAITING OUTSIDE
(Rip and Run Report) Rip and Run Report\n\n~\nLocation Information:\n\nLocation:~445~RT~9~\nCommon Name:~SHOPRITE - BERKELEY\nVenue:~Berkeley Township\nCross Streets~\nFREDERICK DR / KORMAN RD\n OCEAN GATE DR\nQuadrant:~ST17\nDistrict:~SQ13\n~\nCall Information:\n\nCall Number:~92248\nCall Type:~ Vehicle Fire\nSource:~911\nPriority:~ High\nStatus:~In Progress\nCaller:~\nCall Date/Time:~07/13/2012 14:20:45\nDispatch Date/Time:~07/13/2012 14:21:47\nArrive Date/Time:~\nClear Date/Time:~\nEnroute Date/Time:~\nLatest Unit Cleared Date/Time:~\n~\nIncident Number(s)\n2012-00001602~~Bayville EMS\n2012-00000188~~Bayville Fire Department\n~\nUnits Sent:~2\nST17, SQ13~\n\nAlerts:\n~\nLocation Alerts\n\nPerson Alerts\n\nVehicle Alerts\n~~\nNarrative:\n\nNarrative Time~Narrative
(Rip and Run Report) Rip and Run Report\n\n~\nLocation Information:\n\nLocation:~343~ARLINGTON~AVE~\nVenue:~Berkeley Township\nCross Streets~\nMARYLAND AVE / DEAD END\nQuadrant:~ST17\nDistrict:~SQ13\n~\nCall Information:\n\nCall Number:~92497\nCall Type:~ Gas Leak\nSource:~Telephone\nPriority:~ Medium\nStatus:~In Progress\nCaller:~\nCall Date/Time:~07/13/2012 17:16:32\nDispatch Date/Time:~07/13/2012 17:17:43\nArrive Date/Time:~\nClear Date/Time:~\nEnroute Date/Time:~\nLatest Unit Cleared Date/Time:~\n~\nIncident Number(s)\n2012-00000189~~Bayville Fire Department\n~\nUnits Sent:~1\nST17~\n\nAlerts:\n~\nLocation Alerts\n\nPerson Alerts\n\nVehicle Alerts\n~~\nNarrative:\n\nNarrative Time~Narrative
(Rip and Run Report) Rip and Run Report\n\n~\nLocation Information:\n\nLocation:~445~RT~9~\nCommon Name:~SHOPRITE - BERKELEY\nVenue:~Berkeley Township\nCross Streets~\nFREDERICK DR / KORMAN RD\n OCEAN GATE DR\nQuadrant:~ST17\nDistrict:~SQ13\n~\nCall Information:\n\nCall Number:~92561\nCall Type:~ Landing Zone\nSource:~Telephone\nPriority:~ Low\nStatus:~In Progress\nCaller:~\nCall Date/Time:~07/13/2012 18:14:03\nDispatch Date/Time:~07/13/2012 18:14:36\nArrive Date/Time:~\nClear Date/Time:~\nEnroute Date/Time:~\nLatest Unit Cleared Date/Time:~\n~\nIncident Number(s)\n2012-00000190~~Bayville Fire Department\n~\nUnits Sent:~1\nST17~\n\nAlerts:\n~\nLocation Alerts\n\nPerson Alerts\n\nVehicle Alerts\n~~\nNarrative:\n\nNarrative Time~Narrative
(Rip and Run Report) Rip and Run Report\n\n~\nLocation Information:\n\nLocation:~316~BAY~BLVD~\nVenue:~Berkeley Township\nCross Streets~\nCROW AVE / ROBIN AVE\nQuadrant:~ST17\nDistrict:~SQ13\n~\nCall Information:\n\nCall Number:~92833\nCall Type:~ General Weakness\nSource:~911\nPriority:~ Medium\nStatus:~In Progress\nCaller:~\nCall Date/Time:~07/13/2012 23:16:54\nDispatch Date/Time:~07/13/2012 23:18:20\nArrive Date/Time:~07/13/2012 23:30:08\nClear Date/Time:~\nEnroute Date/Time:~07/13/2012 23:26:31\nLatest Unit Cleared Date/Time:~07/13/2012 23:26:34\n~\nIncident Number(s)\n2012-00001605~~Bayville EMS\n2012-00000191~~Bayville Fire Department\n~\nUnits Sent:~3\nST17, SQ13, E136~\n\nAlerts:\n~\nLocation Alerts\n\nPerson Alerts\n\nVehicle Alerts\n~~\nNarrative:\n\nNarrative Time~Narrative\n07/13/12 23:17:53~Nature Of Call: 42YOF\n07/13/12 23:18:02~CELULITIS IN BOTH LEGS\n07/13/12 23:24:15~conf crew
(Rip and Run Report) Rip and Run Report\n\n~\nLocation Information:\n\nLocation:~255~CHELSEA~AVE~\nVenue:~Berkeley Township\nCross Streets~\nCEDARCREST DR / BERKELEY PL\nQuadrant:~ST17\nDistrict:~SQ13\n~\nCall Information:\n\nCall Number:~93543\nCall Type:~ CO Alarm\nSource:~911\nPriority:~ High\nStatus:~In Progress\nCaller:~\nCall Date/Time:~07/14/2012 16:55:39\nDispatch Date/Time:~07/14/2012 16:56:19\nArrive Date/Time:~\nClear Date/Time:~\nEnroute Date/Time:~\nLatest Unit Cleared Date/Time:~\n~\nIncident Number(s)\n2012-00000192~~Bayville Fire Department\n~\nUnits Sent:~1\nST17~\n\nAlerts:\n~\nLocation Alerts\n\nPerson Alerts\n\nVehicle Alerts\n~~\nNarrative:\n\nNarrative Time~Narrative\n07/14/12 16:56:05~Nature Of Call: CO ALM, EVERYONE GETTING OUT
(Rip and Run Report) Rip and Run Report\n\n~\nLocation Information:\n\nLocation:~492~EASTERN~BLVD~\nVenue:~Berkeley Township\nCross Streets~\nLATIMER AVE / NOLAN AVE\nQuadrant:~ST17\nDistrict:~SQ13\n~\nCall Information:\n\nCall Number:~94287\nCall Type:~ Animal Call\nSource:~Telephone\nPriority:~ Administrative\nStatus:~In Progress\nCaller:~\nCall Date/Time:~07/15/2012 11:04:44\nDispatch Date/Time:~07/15/2012 11:09:44\nArrive Date/Time:~\nClear Date/Time:~\nEnroute Date/Time:~\nLatest Unit Cleared Date/Time:~\n~\nIncident Number(s)\n~\nUnits Sent:~1\nST17~\n\nAlerts:\n~\nLocation Alerts\n\nPerson Alerts\n\nVehicle Alerts\n~~\nNarrative:\n\nNarrative Time~Narrative\n07/15/12 11:08:59~Nature Of Call: KITTEN IN TREE / PD REQ FD RESPONE.\n07/15/12 11:09:13~CALLED IN BY BERK PD
(Rip and Run Report) Rip and Run Report\n\n~\nLocation Information:\n\nLocation:~136~CEDAR RUN~RD~\nVenue:~Berkeley Township\nCross Streets~\nDEAD END / SAND RD\nQuadrant:~ST17\nDistrict:~SQ13\n~\nCall Information:\n\nCall Number:~94427\nCall Type:~ Fire Alarm\nSource:~911\nPriority:~ High\nStatus:~In Progress\nCaller:~\nCall Date/Time:~07/15/2012 13:34:22\nDispatch Date/Time:~07/15/2012 13:35:37\nArrive Date/Time:~\nClear Date/Time:~\nEnroute Date/Time:~\nLatest Unit Cleared Date/Time:~\n~\nIncident Number(s)\n2012-00000193~~Bayville Fire Department\n~\nUnits Sent:~1\nST17~\n\nAlerts:\n~\nLocation Alerts\n\nPerson Alerts\n\nVehicle Alerts\n~~\nNarrative:\n\nNarrative Time~Narrative\n07/15/12 13:35:22~Nature Of Call: vacant house  third party nothing showing
(Rip and Run Report) Rip and Run Report\n\n~\nLocation Information:\n\nLocation:~570~EGENOLF~PL~\nVenue:~Berkeley Township\nCross Streets~\nNo Cross Streets Found\nQuadrant:~ST17\nDistrict:~SQ13\n~\nCall Information:\n\nCall Number:~94774\nCall Type:~ Brush Fire\nSource:~Telephone\nPriority:~ High\nStatus:~In Progress\nCaller:~\nCall Date/Time:~07/15/2012 19:46:28\nDispatch Date/Time:~07/15/2012 19:47:46\nArrive Date/Time:~\nClear Date/Time:~\nEnroute Date/Time:~\nLatest Unit Cleared Date/Time:~\n~\nIncident Number(s)\n2012-00000194~~Bayville Fire Department\n2012-00001156~~NJ Forest Fire Service\n~\nUnits Sent:~2\nST17, B7~\n\nAlerts:\n~\nLocation Alerts\n\nPerson Alerts\n\nVehicle Alerts\n~~\nNarrative:\n\nNarrative Time~Narrative
(Rip and Run Report) Rip and Run Report\n\n~\nLocation Information:\n\nLocation:~50~GOOD LUCK~DR~\nVenue:~Berkeley Township\nCross Streets~\nBEACH AVE / DORRANCE DR\nQuadrant:~ST17\nDistrict:~SQ13\n~\nCall Information:\n\nCall Number:~94807\nCall Type:~ Structure Fire\nSource:~911\nPriority:~ High\nStatus:~In Progress\nCaller:~\nCall Date/Time:~07/15/2012 20:26:59\nDispatch Date/Time:~07/15/2012 20:27:43\nArrive Date/Time:~\nClear Date/Time:~\nEnroute Date/Time:~\nLatest Unit Cleared Date/Time:~\n~\nIncident Number(s)\n2012-00001618~~Bayville EMS\n2012-00000195~~Bayville Fire Department\n~\nUnits Sent:~2\nST17, SQ13~\n\nAlerts:\n~\nLocation Alerts\n\nPerson Alerts\n\nVehicle Alerts\n~~\nNarrative:\n\nNarrative Time~Narrative\n07/15/12 20:27:28~Nature Of Call: SMOKE COMING OUT OF HOUSE UNK IF ANYONE IS HOME
(Rip and Run Report) Rip and Run Report\n\n~\nLocation Information:\n\nLocation:~395~LAKESIDE~BLVD~\nCommon Name:~Crystal Lake Convalescent Center - Berkeley\nVenue:~Berkeley Township\nCross Streets~\nHAYDEN ST / MONTGOMERY ST\nQuadrant:~ST17\nDistrict:~SQ13\n~\nCall Information:\n\nCall Number:~94871\nCall Type:~ Fire Alarm\nSource:~Telephone\nPriority:~ High\nStatus:~In Progress\nCaller:~\nCall Date/Time:~07/15/2012 21:23:09\nDispatch Date/Time:~07/15/2012 21:24:10\nArrive Date/Time:~\nClear Date/Time:~\nEnroute Date/Time:~\nLatest Unit Cleared Date/Time:~\n~\nIncident Number(s)\n2012-00000196~~Bayville Fire Department\n~\nUnits Sent:~1\nST17~\n\nAlerts:\n~\nLocation Alerts\n\nPerson Alerts\n\nVehicle Alerts\n~~\nNarrative:\n\nNarrative Time~Narrative\n07/15/12 21:23:59~Nature Of Call: OPER 3684\n07/15/12 21:24:05~Nature Of Call: OPER 3684
(Rip and Run Report) Rip and Run Report\n\n~\nLocation Information:\n\nLocation:~386~VIRGINIA~AVE~\nVenue:~Berkeley Township\nCross Streets~\nHOOVER AVE / WESTERN BLVD\nQuadrant:~ST17\nDistrict:~SQ13\n~\nCall Information:\n\nCall Number:~94963\nCall Type:~ Pole Fire\nSource:~Telephone\nPriority:~ High\nStatus:~In Progress\nCaller:~\nCall Date/Time:~07/15/2012 22:57:26\nDispatch Date/Time:~07/15/2012 22:58:35\nArrive Date/Time:~\nClear Date/Time:~\nEnroute Date/Time:~\nLatest Unit Cleared Date/Time:~\n~\nIncident Number(s)\n2012-00000197~~Bayville Fire Department\n~\nUnits Sent:~1\nST17~\n\nAlerts:\n~\nLocation Alerts\n\nPerson Alerts\n\nVehicle Alerts\n~~\nNarrative:\n\nNarrative Time~Narrative
(Rip and Run Report) Rip and Run Report\n\n~\nLocation Information:\n\nLocation:~18~BUTLER~BLVD~\nCommon Name:~Tallwoods Care Center - Berkeley @ Butler Blvd\nVenue:~Berkeley Township\nCross Streets~\nLAUREL LN / RT 9\n CENTRAL PKWY\nQuadrant:~ST17\nDistrict:~SQ13\n~\nCall Information:\n\nCall Number:~96448\nCall Type:~ Fire Information\nSource:~Telephone\nPriority:~ Administrative\nStatus:~In Progress\nCaller:~\nCall Date/Time:~07/17/2012 12:22:04\nDispatch Date/Time:~07/17/2012 12:23:19\nArrive Date/Time:~\nClear Date/Time:~\nEnroute Date/Time:~\nLatest Unit Cleared Date/Time:~\n~\nIncident Number(s)\n~\nUnits Sent:~1\nST17C~\n\nAlerts:\n~\nLocation Alerts\n\nPerson Alerts\n\nVehicle Alerts\n~~\nNarrative:\n\nNarrative Time~Narrative\n07/17/12 12:22:32~Nature Of Call: WORKING ON FIRE SYSTEM\n07/17/12 12:23:05~WILL CALL BACK WHEN DONE
(Rip and Run Report) Rip and Run Report\n\n~\nLocation Information:\n\nLocation:~120~PATTON~AVE~\nVenue:~Berkeley Township\nCross Streets~\nMIDLAND AVE / DEAD END\nQuadrant:~ST17\nDistrict:~SQ13\n~\nCall Information:\n\nCall Number:~96592\nCall Type:~ CO Alarm\nSource:~911\nPriority:~ High\nStatus:~In Progress\nCaller:~\nCall Date/Time:~07/17/2012 14:34:14\nDispatch Date/Time:~07/17/2012 14:35:01\nArrive Date/Time:~\nClear Date/Time:~\nEnroute Date/Time:~\nLatest Unit Cleared Date/Time:~\n~\nIncident Number(s)\n2012-00000198~~Bayville Fire Department\n~\nUnits Sent:~1\nST17~\n\nAlerts:\n~\nLocation Alerts\n\nPerson Alerts\n\nVehicle Alerts\n~~\nNarrative:\n\nNarrative Time~Narrative
(Rip and Run Report) Rip and Run Report\n\n~\nLocation Information:\n\nLocation:~11~VINE~ST~\nVenue:~Berkeley Township\nCross Streets~\nMARICIEL AVE / CENTRAL PKWY\nQuadrant:~ST17\nDistrict:~SQ13\n~\nCall Information:\n\nCall Number:~97427\nCall Type:~ Odor Investigation\nSource:~Telephone\nPriority:~ Administrative\nStatus:~In Progress\nCaller:~\nCall Date/Time:~07/18/2012 11:00:14\nDispatch Date/Time:~07/18/2012 11:00:57\nArrive Date/Time:~\nClear Date/Time:~\nEnroute Date/Time:~\nLatest Unit Cleared Date/Time:~\n~\nIncident Number(s)\n2012-00000199~~Bayville Fire Department\n~\nUnits Sent:~1\nST17~\n\nAlerts:\n~\nLocation Alerts\n\nPerson Alerts\n\nVehicle Alerts\n~~\nNarrative:\n\nNarrative Time~Narrative\n07/18/12 11:00:43~Nature Of Call: strong smell of smoke

 */


public class NJOceanCountyParser extends DispatchA9Parser {
  
  public NJOceanCountyParser() {
    super(null, "OCEAN COUNTY", "NJ");
  }
  
  @Override
  public String getFilter() {
    return "Fire_Records";
  }
  
  @Override
  protected boolean parseMsg(String body, Data data) {
    if (!super.parseMsg(body, data)) return false;
    
    // Dispatch seems to be storing the station code in the map fields
    data.strSource = data.strMap;
    data.strMap = "";
    return true;
  }
  
  @Override
  public String getProgram() {
    return "SRC " + super.getProgram();
  }
}
