cnpxntr arg.narv.pnqcntr.cnefref.ZB;

vzcbeg arg.narv.pnqcntr.cnefref.OnfrCnefreGrfg;

vzcbeg bet.whavg.Grfg;


/*
Snezvatgba, ZB

Pbagnpg: Npgvir911
Ntrapl anzr: Snezvatgba CQ
Ybpngvba: Snezvatgba, ZB, Havgrq Fgngrf
Fraqre: "QVFCNGPU@SNEZVATGBA.ZB" <QVFCNGPU@SNEZVATGBA.ZB>

1050 W HAXABJA\a222 R PBYHZOVN FG\aA URAEL FG & A YBAT NIR\a\a10-12 SVER UBHFR\a\aBPPHERQ 67 & 32
FGRNYVAT\a1609 J PBYHZOVN FG\aJRFGZBHAG QE & UJL 67
1050 W1\a775 JRORE EQ\aZNCYR INYYRL & XNEFPU\a\aARNE PNGSVFU XRGGYR
QBZRFGVP\a223 FCEHPR FG\aA ZVQQYR FG & A PNEYRGBA FG\a\aZBGURE IF QNHTGURE GRRANTRE.  GRRANTRE BA SBBG F BA PNEYRGBA CVAX \aFUVEG OYX CNAGF JS \a\aZBGURE VF NG ERFVQRAPR.  EC FGNGRQ ZBGURE JNF NFFNHYGVAT QNHTUGRE.  \aFBZRGUVAT NOBHG N FVYIRE WRRC YVOREGL
GERFCNFFVAT\a510 A SENAXYVA FG\aQBFF FG & ABEGU FG\a\aGRNY FUBEG FYRRIR FUVEG FUBEGF NAQ CBALGNVY JZ JNYXRQ VAGB EC
FHFCVPVBHF CREFBA\a705 QRJRL NIR\aOBLPR NIR & XVAMRE FG\a\aINPNAG ERFVQRAPR.  JZ JRNEVAT TEA GNA FUBEGF ONVTR OEB UBBQVR JVGU \aUBBQ HC JNF CRRXVAT VA JVAQBJF NAQ JRAG VAGB GUR PBIRERQ CBEPU \aNERN.
OHETYNEL NYNEZ\aJRORE EQ\aPBYHZOVN FG & PBYYRTR NIR\a\aNHQVOYR NYNEZ FBHAQVAT
FHFCVPVBHF CREFBA\a902 ZVPUVTNA FG\aXNEFPU OYIQ & CVAR FG\a\aJUVGR ZNYR ERQ GRR FUVEG LBHATRE XVQ\aJNYXRQ GUEBHTU PNYYRE'F ONPXLNEQ GBJNEQF ZVQQYR FG\aUR JBHYQA'G YRNIR SBE NYZBFG 5 ZVAHGRF\aJNF JNAGVAT GB HFR GUR CUBAR
OHETYNEL NYNEZ\a301 A JNFUVATGBA FG\aPBYYRTR NIR & CNGGREFBA FG\a\aRIRAG PBQR ABG SBHAQ\a\aWNZRF JVYYVF 756-4810 NAQ 701-2980\aZRTNA ZNEYRE 749-3373 NAQ 330-4139
FHFCVPVBHF CREFBA\aPBAFGEHPGVBA NERN BSS SBEFGRE\a\a111F
FHFCVPVBHF CREFBA\aF SYRZVAT ARNE SBEFGRE\a\a111F\aNGGRZCGVAT GB YBPNGR N FHOWRPG
FHFCVPVBHF IRUVPYR\a1400 NVE CNEX QE\aINETB EQ\a128O\aBHG OL GUR ONFRONYY SVRYQF
NFFVFG NZOHYNAPR\a310 YNHEN NIR\aF N FG & GNLYBE NIR\a\a4 JRRX BYQ ONOL ABG OERNGUVAT
1050 W1\a67AO CNFG WBUA QRRER\a\a111F
QEHT BSSRAFR\a309 FVKGU FG\aF N FG & CREEVAR EQ\a\aGVZ UNEEVF TBG N PNYY GUNG GUVF VF UNCCRAVAT\aEVPX PYNEX VF GURER ABJ PBBXVAT ZRGU VA GUR ONGUEBBZ\aUBHFR ORYBATF GB NATRYN ORAFPBGRE
JNEENAG NEERFG\aWRSS PB\a\a104U\aRAEBHGR GB WRSSREFBA PB SBE JNEENAG CVPX HC
GENSSVP UNMNEQ\a67AO\a\a122Z\aerzbivat vgrzf sebz gur ebnq
FGRNYVAT\a222 R PBYHZOVN FG\aA URAEL FG & A YBAT NIR\a\aFGBYRA CUBAR
FGRNYVAT\a253 TRAQNYR QE\aZRNQBJOEBBX QE & XRAJBBQ QE
QBZRFGVP\a406 CREEVAR EQ\aJ PBYHZOVN FG & OBLPR NIR
1050 W1\a507 CBGBFV FG\aZNCYR FG & XNEFPU OYIQ\a\aerq sbeq gehpx\a\atzp qranyv juvgr va pbybe\a\aab vawhevrf
FGRNYVAT\a684 JNYGBA QE\aZNCYR FG & XNEFPU OYIQ\a\aSNVYHER GB ERGHEA ERAGNY CEBCREGL
NFFNHYG\a1 OYNPX XAVTUG QE\aJ PBYHZOVN & J YVOREGL\a121J\aYBPNGVBA ABGRF:  \aSVEFG FGNGR PBZZHAVGL ONAX OYNPX XAVTUG OENAPU 701-9749 YBPNGVBA VQ \a#14 ERSRE GB FCRPVNY CEBPRQHER SBE ONAX NYNEZF. \aCNFFJBEQ / PHFGBZRE VQ 0009\a\aENQVB QVFCNGPU NF 10-30 AHZORE 14  (GJB HAVGF BAR ORVAT N FHCREIVFBE VS \aNINVYNOYR)\aVS 121 BE 124 NER JBEXVAT QVFCNGPU GURZ FVAPR YBPNGVBA VF UVTU FPUBBY.\a\aQVFCNGPURE ERFCBAFVOYVGVRF\aVs gur eboorel abgvsvpngvba vf znqr ol nynez, gur qvfcngpure funyy, nsgre qvfcngpuvat gjb \ahavgf gb gur fprar, nggrzcg gbpbagnpg gur vafgvghgvba va beqre gb qrgrezvar gur inyvqvgl bs \agur nynez.  Gur pbairefngvba jvyy or nf sbyybjf:\aN.QVFCNGPURE:  "Guvf vf Snezvatgba Cnpxntr Qryvirel.  Qvq lbh\aerprvir gur cnpxntr jr frag lrfgreqnl:"\aO.NAFJREVAT CNEGL:  "Lrf jr qvq.  Vg jnf cnpxntr ahzore____."\aGurve phfgbzre VQ ahzore jvyy or hfrq sbe gur cnpxntr\aahzore.) Guvf erfcbafr vaqvpngrf n snyfr nynez.  Nal bgure\aerfcbafr vaqvpngrf n ubyqhc.  Qvfpbaarpg jvgu gur pnyyre naq\a                                                gura gur Qvfcngpure jvyy abgvsl erfcbaqvat havgf jurgure be \aabg gur \a                                                cebcre pbqr jnf tvira.\a\a                Vs gur qvfcngpure vf abgvsvrq ol gur svanapvny vafgvghgvba gung\ana nynez vf snyfr, be gur cebcre pbqr vf tvira, gur qvfcngpure\afunyy nqivfr gur cnegl gung bssvpref ner raebhgr naq gung\afbzrbar jvyy arrq gb rkvg gur snpvyvgl ng gur sebag qbbe gb zrrg\a gur erfcbaqvat bssvpref.\a\a                                Vs gur eboorel abgvsvpngvba vf erprvirq ol gryrcubar, n pbzcyrgr\aqrfpevcgvba bs gur crecrgengbef funyy or bognvarq sebz gur\apnyyre nybat jvgu nf zhpu nqqvgvbany vasbezngvba nf cbffvoyr;\acnegvphyneyl, jurgure jrncbaf ner vaibyirq, jurgure gur\acrecrgengbe vf ng gur fprar naq, vs abg, uvf qverpgvba naq zbqr\abs geniry naq pbzcyrgr qrfpevcgvba bs nal iruvpyr vaibyirq.\a\a                                GRFG BS NYNEZF\a\aVs gur qvfcngpure erprvirf n pnyy sebz n onax be bgure svanapvny\avafgvghgvba gung gurl jvyy or grfgvat gurve nynez, gur qvfcngpure\afunyy nfx gur pnyyre sbe gurve phfgbzre VQ ahzore.  Vs gur pnyyre\apnaabg cebivqr gur pbeerpg ahzore, bssvpref jvyy or qvfcngpurq gb\agur ybpngvba naq cebprqherf sbe nynez erprvcg (nf bhgyvarq va VVV.N.\anaq VVV.O.) jvyy or vavgvngrq.\a\a\a----------------------------------------
1050 W1\aZNCYR/JNFUVATGBA\a\a\aJUG RAIBL\a\aTEA PNE
P & V QEVIVAT\aR XNEFPU OYIQ\a\a\a18 JURRYRE EHAAVAT IRU BSS GUR EBNQ.  BA UJL 67 GBBX RO XNEFPU RKVG.  \aJUG GENPGBE GENVYRE CHYYVAT N SYNG ORQ GENVYRE.  ZRGNY OHVYQVAT FHCCYL \aSEBZ NEXNAFNF.  CG117798
GENSSVP UNMNEQ\aJ XNEFPU OYIQ\aZNCYR INYYRL\a126O\atebprevrf va gur yrsg ghea ynar
FGRNYVAT\a1440 SBKTYBIR FG\aSBK TYRA QE & TERL SBK\a\aGURSG BS ZRQVPNGVBA
OHETYNEL NYNEZ\a612 JNYZNEG QE\aJNYGBA QE & CBGBFV FG\a\aERNE ZBGVBA
OHETYNEL NYNEZ\a763 ZNCYR INYYRL QE\aZNCYR FG & ZNEXRG FG\a\aUNYY ZBGVBA, SEBAG NAQ CVG ZBGVBA.\a\aPBYYVA BA FVGR JBEXF GURER QBRF ABG UNIR PBQRF BE CNFFJBEQ.
OEBNQPNFG ZRFFNTR\a310 FGR TRARIVRIR NIR\aA ZNVA FG & F PNEYRGBA FG\a\aFRAG GB PRX4, PFRZ\a\a****BSSVPRE FNSRGL****\a****NEZRQ FHOWRPG****\a\aFHOWRPG NEZRQ JVGU 9ZZ CVFGBY\a\aOERAQN QNIVF, JUVGR SRZNYR, 19621028, QEVIVAT N OYNPX 2000 RKGRAQRQ \aPNO, QBQTR \aENZ GEHPX JVGU QNZNTR ORUVAQ GUR QEVIREF FVQR QBBE, ZVFFBHEV CYNGR \a0LO794.\aCBCYNE OYHSS CBYVPR QRCNEZRAG UNF ERPRVIRQ VASBEZNGVBA GUNG QNIVF \aUNF GNXRA\aZHYGVCYR ANEPBGVPF, NAQ VF GUERNGRAVAT FHVPVQR. YNFG FRRA VA CBCYNE \aOYHSS NG\aNCCEBKVZNGRYL 0230 UBHEF, RAEBHGR GB NA HAXABJA YBPNGVBA.\a\a\a/F/YRJVF, UBYYL\aCBCYNE OYHSS CQ      20150518      0313\a\a\aZEV: 22636332 VA: PRX4 29 NG 18ZNL2015 03:26:23\aBHG: P262 32 NG 18ZNL2015 03:26:23
PURPX GUR JRYY ORVAT\a857 CBGBFV FG\aZNCYR INYYRL QE & YBT PNOVA YA\a\aWRERZL FGERRG CBFF GNXRA CVYYF \aPNYYRE FGNGRQ GUNG UR FNJ BA FHOWRPGF SNPR OBBX GUNG UR UNQ GNXRA \a80 NGNINA\aPNCR PURPXRQ NAQ PNA'G SVAQ NA NQQERFF VA GURER BAYL NQQERFF URER
QVFGHEONAPR\a201 ULYRE QE\aJ PBYHZOVN FG\a\aZNYR FHOWRPG PUNFVAT N SRZNYR \aPNE SBYYBJVAT GNA BE FVYIRE
FHFCVPVBHF IRUVPYR\a775 JRORE EQ\aZNCYR INYYRL & XNEFPU\a\aGEHPX NAQ N WRRC HAX PBYBE  CBFF N ERQ IRUVPYR \aVA GUR ONPX  CNEXVAT YBG\aFNLF GURL FUBHYQ OR PYBFRQ YBBXF FHFCVPVBHF
FHFCVPVBHF IRUVPYR\a909 R XNEFPU OYIQ\aXERV NIR & FGR TRARIVRIR NIR\a\aPNQVYYNP PGF \aJUVGR \aHAX CYNGR \aQEVIVAT NEBHAQ GUR CNEXVAT YBG BS FGBENTR FURQF \aJ XNEFPU GBJNEQ UJL 67
1055 FHOWRPG\a838 INYYRL PERRX QE\aZNCYR INYYRL QE & ZNEXRG FG\a\aNATEL NAQ LRYYVAT ZNYR UNQ CNFFRQ BHG,VA GUR YBOOL, ERSHFVAT RZF, \aUBJRIRE OYHR FUVEG NAQ WRNAF. EC VF 3EQ CNEGL. FUR VF HAFHER VS UR UNF \aN ZRQVPNY PBAQVGVBA BE VF 1055. ZNL OR BHGFVQR GUR GURNGRE.
P & V QEVIVAT\a67FO/ZNCYR\a\a\aL85X1U ERQ PNZNEB NYY BIRE GUR EBNQJNL. SNVYHER GB ZNVAGNVA N YNAR
OHETYNEL NYNEZ\a902 CEBTERFF QE\aJ PBYHZOVN FG & QBHORG EQ\a\aRAGEL RKVG OHETYNEL. \a\aBHGFVQR NYNEZ PBZCNAL UNF ABG ORRA NOYR GB ZNXR PBAGNPG JVGU \aXRLUBYQREF LRG  160598560 ERSRERAPR BCRENGBE S465
1050 W1\a775 JRORE EQ\aZNCYR INYYRL & XNEFPU
FGRNYVAT\a222 R PBYHZOVN FG\aA URAEL FG & A YBAT NIR\a\aOYO FGBENTR
1050 W HAXABJA\a538 WBUA QNIVQ QE\aQNYR QE & FGBARTNGR FG\a\a1 IRUVPYR VAGB N CBYR NAQ ZNVYOBK, SVER NAQ RZF RAEBHGR.
1055 QEVIR\a221 ARNE EUBQRF 101\a\a\aPBZVAT VAGB SNEZVATGBA SEBZ QBR EHA, CNFFVAT ARJ NOHAQNAG SNZVYL \aPUHEPU, SNVYHER GB ZNVAGNVA N YNAR, SBEQ GNHEHF, FVYIRE 4 QBBE FRQNA, \aJR2S8Z
1050 W1\a222 R PBYHZOVN FG\aA URAEL FG & A YBAT NIR\a\aYRNIVAT GUR FPRAR\a\aBPPHERQ NG JNYZNEG LRFGREQFNL
OHETYNEL NYNEZ\a1 OYNPX XAVTUG QE\aJ PBYHZOVN & J YVOREGL\a\aBSSVPR ERNE QBBE\a\a\aWBUA XENHFR 631-1009
OHETYNEL NYNEZ\a140 JRFGZBHAG QE\aJ YVOREGL FG & J PBYHZOVN FG\a\apryy onpx hc\aYBAT UNYY\a\aWBUA 7566968\a7604140\aNAGBA 7608697\aCNZ 7560548
QVFGHEONAPR\a796 ZNCYR INYYRL QE\aZNEXRG FG & XNEFPU OYIQ\a\a4-5 ZNYRF NCCRNE GUNG GURL ZVTUG FGNEG SVTUGVAT\aGNYY FYRRIRYRFF FUVEG
JNEENAG NEERFG\a310 FGR TRARIVRIR NIR\aA ZNVA FG & F PNEYRGBA FG\a133Z
NFFNHYG\a200 J SVEFG FG\aF SENAXYVA FG & F N FG
P & V QEVIVAT\aCEBTERFF QE\a\a\a04-06 4Q QBQTR PHZZVATF \aQBVAT QBAHGF VA GUR FBPPRE SVRYQ\aYVTUGF BS \aGBBX UJL 67 FBHGU GBJNEQ SERQREVPXGBJA
OHETYNEL NYNEZ\a509 LBFRZVGR PG\aFURANAQBNU QE\a\aOBAVGN SERRZNA ERFVQRAPR\a\aONFRZRAG ZBGVBA\a\aHANOYR GB ERNPU XRLUBYQRE\a\aBCRE/
GENSSVP UNMNEQ\aN/ZNCYR\a\a104U
NFFVFG NZOHYNAPR\a206 R UVYYFVQR QE\aZRNQBJOEBBX QE & XRAJBBQ QE\a\aSNGURE VF UNIVAT PURFG CNVA\a\aUNF GNXRA 3 AVGEB JVGU AB ERYVRS\a\aVFA'G JNAG GB TB GB UBFCVGNY\a\aJBHYQ YVXR BSSVPRE GB NFFVFG VA PNFR GURER VF N CEBOYRZ
OEBNQPNFG ZRFFNTR\a310 FGR TRARIVRIR NIR\aA ZNVA FG & F PNEYRGBA FG\a\aGBC NAQ UBYQ JNAGRQ SBE GURSG\a\aQRAAVF PBBX QBO:19661215 J Z \aFHOWRPG QEVIVAT N OYNPX 1991 SBE ENATRE ZB YVP 5JT970\aFHOWRPG VF JNAGRQ SBE GURSG BS N JNYYRG SEBZ QBYYNE TRARENY \aVA GREER QH YNP BA 05/15/2015. HAXABJA QVERPGVBA BS GENIRY.\a\aVS FHOWRPG VF YBPNGRQ FGBC NAQ UBYQ\a\aNHGUBEVGL GREER QH YNP CQ 804-CEVPR\a\a\a/F/EVPUNEQ, NFUYRL Z\aFG SENAPBVF PB WBVAG PBZZ PRAGRE      20150516
P & V QEVIVAT\a715 J YVOREGL FG\aWBFVR YA & A NYRKNAQRE NIR\a\aTERRA NAQ ERQ FGERRG OVXRF\a\aQBVAT JURRYVRF NAQ FCRRQVAT\a\aVA GUR NERN BS ZPPBEZVPX NAQ GURA GB CBGBFV\a\aPNYYRE QBRFA'G JNAG PBAGNPGRQ\a\aYNFG FRRA TBVAT GBJNEQF CBGBFV BA YVOREGL
OHETYNEL NYNEZ\a1 OYNPX XAVTUG QE\aJ PBYHZOVN & J YVOREGL\a\aOHET GRYREBBZ ZBGVBA\a\aXRLUBYQREF: WBUA 631-1009   760-9423\a\aANGUNA 417-230-5802\a\aWNZVR 756-8123    701-5322\a\aEBL 380-2130
QEHT BSSRAFR\a5 NIN PG\aF URAEL FG\a104U, 122Z\aFBZRBAR VF FZBXVAT BHG BS N PYRNE TYNFF CVCR NG 7 NIN\a\aBA GUR ONPX CBEPU\a\aGUERR OBLF \a\aERQ FUVEG, TENL FJRNGFUVEG, UNG\a\aJNAGF PBAGNPGRQ OL NA BSSVPRE, VF JVYYVAT GB FVTA N PBZCYNVAG\aAB ARRQ SBE SHEGURE CRE 104\ahasbhaqrq\aQvfcbfvgvba: AEA
1058\aXNEFPU/ZNCYR INYYRL\a\a\aAB EBNQ OYBPX\a\aRNFG OBHAQ
FGRNYVAT\a707 JNYGBA QE\aZNCYR FG & XNEFPU OYIQ\a\aOYNPX UBBQVR VAFVQR VF ERQ F
1050 W1\a707 JNYGBA QE\aZNCYR FG & XNEFPU OYIQ\a\aZNEXRG FVQR, 3EQ EBJ BIRE, TENL TZP GREENVA IF OYHR TZP FVREEN \aGEHPX
JNEENAG NEERFG\a20 FG SENAPBVF NIR\aXNEFPU OYIQ & JNONFU NIR\a117P\aYBBXVAT SBE GUVF IRUVPYR, JNF NG RNTYR FGBC ER NAVZNY PNYY. \a\a* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * \a JNAGRQ CREFBA  *** NPGVIR PNFR ***\a                         **** ZHYRF BAYL ****\a  *CREFBA VASB:   ANZR:ABOYR,PNFFVR ZNEVR\a   FRK: S ENPR:J QBO: 06-27-1988 NTR:  26 URVTUG: 501 JRVTUG: 110\a  *PHEE FBP:  595062272\a   UNVE: KKK RLR: OYH\a  *PHEE BYA:  Z050242016            BYL: 2017      BYF: ZB\a\a  *BSSRAFR VASBEZNGVBA: \a   PBQR: 5015  SNVYHER GB NCCRNE  SNVYHER GB NCCRNE\a    PNFR #: 15-007452\a      JNEENAG #: 007452  JNEENAG QNGR: 04-16-2015\a    JVYY RKGENQVGR NQWBVAVAT PBHAGVRF    FHEEBHAQVAT FG SENAPBVF \aPBHAGL\a    WHEVFQVPGVBA:   YBPNY / PVGL BEQVANAPR\a    PBHEG BEV: ZB094031W  PLPYR #:   BEVT BSS: 5499  GENSSVP BSSRAFR\a    OBAQ: $514-00     PNFU BAYL\a\a  *ZVFPRYYNARBHF VASB: FHOWRPG PUNETRQ JVGU SNVYHER GB NCCRNE GB \aNAFJRE\a                        BEVTVANY PUNETR BS SNVYHER GB ERTVFGRE IRUVPYR JVGUQBE\a  *PHEE YVL: 2015  YVF: ZB  YVG: CP  YVP: JW2U7Z\a  *BJARE VASB* ANZR: ABOYR PNFFVR & ENGPYVSS QHFGNA\a   NQQE: 216  QNXBGN PBHEG  SNEZVATGBA  ZB 63640\a  *ILE: 2002  IZN: BYQF  IZB: NYB  IFG: 4Q  \a  *IGC: C  IVA: 1T3AY52R62P136945  \a  *PHEERAG XABJA NQQERFFRF UBZR/JBEX/FPUBBY/SERDHRAGRQ/ZNVYVAT:\a   UBZR: 216 QNXBGN PG  SNEZVATGBA, ZB 63640\a     PBHAGL: 094 FG. SENAPBVF\a   UBZR: 100 ZPPYNL IVYYNTR QE  FNVAG CRGREF, ZB 63376\a   UBZR: 418 F PNQVYYNP QE  FG PUNEYRF, ZB 63301\a OEBNQPNFG GREZVANYF: \a  *VZZRQVNGRYL PBASVEZ JVGU BEV:\a    PNFR BEV VASBEZNGVBA: ZB0940600  SNEZVATGBA CQ                      \a    RAGREVAT BEV VASBEZNGVBA: ZB0940600  SNEZVATGBA CQ                      \a    FUC: 150417-204519\a    BPN: 15-007452\a\a**** PBASVQRAGVNY QNGN ERFGEVPGRQ GB PEVZVANY WHFGVPR NTRAPVRF ****\a*** RAQ BS ERPBEQ ***\a \a\a\aZEV: 22125624 VA: USFD1 29681 NG 16ZNL2015 15:32:30\aBHG: PUW3 51 NG 16ZNL2015 15:32:31 \a \aSEBZ-APVP       QNGR: 05/16/2015 GVZR: 15:32:31 QRFG GREZ: PUW3      \aDIE.YVP/JW2U7Z.YVL/2015.\a \a\a1Y0101BI,ZE22125620\a\aZ00940600\aAB ERPBEQ YVP/JW2U7Z\a\aZEV: 22125623 VA: APVP 33670 NG 16ZNL2015 15:32:30\aBHG: PUW3 50 NG 16ZNL2015 15:32:31\a   \a \a\aSEBZ-ERIRAHR     QNGR: 05/16/2015  GVZR: 15:32:30 QRFG GREZ: JP00SBKV\aQBE.TE40JW2U7Z15\a*E04 - GVGYR & ERTVFG\a****  GUVF ERPBEQ ERFGEVPGRQ HAQRE QEVIREF CEVINPL CEBGRPGVBA NPG  ****\a LRNE:02 ZNXR:BYQF  FGLYR:SBQBE XVAQ BS IRU:C IVA:1T3AY52R62P136945\a  BJARE ANZR:ABOYR PNFFVR & ENGPYVSS QHFGNA          PBHAGL:FG. SENAPBVF\a  NQQERFF:216 QNXBGN PBHEG     SNEZVATGBA      ZB 63640\a  PLY:   FREVRF:N/T NKYRF:  SHRY:T UBEFR CBJRE:24\a YVP:JW2U7Z RKCVENGVBA:ABI 15 YVG:CP GNO AB:000000000 VFFHR:101514\a  GVGYR:GJX93733 GLCR:BEVTVANY   QNGR:101614 BQBZ:0000000 ARJ/HFRQ:HFRQ \aBHGFG\a \aZEV: 22125622 VA: ZHYRF 42515 NG 16ZNL2015 15:32:30\aBHG: PUW3 49 NG 16ZNL2015 15:32:3
P & V QEVIVAT\a32SEBZ FGR TRA PBHAGL YVAR. \a\a\a32 SEBZ GUR FGR TRA PBHAGL YVAR JUVGR PURIL CVPXHC, VY CYNGRF, SNVYHER \aGB ZNVAGNVA N YNAR.
OHETYNEL NYNEZ\a2000 CEBTERFF QE\aQBHORG EQ & BIRENYY EQ\a\aQBBE 29\a\aTRBETR, 747.5323\aEBPXL 330.7343\aGREEL 631.2464\aQNAAL 915.6137
1058\aZNCYR/NYRKNAQRE\a\a\aEC VF N CNFFREOL   FNJ N ZNYR FHOWRPG'F JUBFR PNE VF OEBXRA QBJA, \aZNCYR& NYRKNAQRE. EC VF PBAPREARQ GUNG FBZRBAR JVYY EHA VAGB GUR \aONPX BS GUR PNE NAQ EHA GUR ZNYR FHOWRPG BIRE. AB IRUVPYR \aQRFPEVCGVBA, GUVAXF VG ZNL OR FVYIRE, VF HAFHER. ZNLOR UR ARRQF PBARF \aBE FBZRGUVAT GB FUBJ UR VF GURER.
PURPX GUR JRYY ORVAT\a1050 IREABA NIR\aNYQRETNGR FG & NCNEGZRAG PBZCYRK\a\aWBR/WBFRCU CREXVAF, 108'F AVRPR'F UHFONAQ, UR QVQA'G FUBJ HC SBE JBEX. \aPURPX UVF JRYY ORVAT, PBAGNPG 108 JVGU ERFHYGF CYRNFR.
GENSSVP UNMNEQ\a780 ZNCYR INYYRL QE\aZNEXRG FG & XNEFPU OYIQ\a\aZNYR FHOWRPG QNEX UNVE, 5'10 FYVZ OHVYQ ERQ WNPXRG CNAUNAQYVAT VA GUR \aEBNQJNL PNHFVAT IRUVPYRF GB QRGBHE NEBHAQ UVZ.
GENSSVP UNMNEQ\aJ CVAR FG\a\a\aONPX ORUVAQ NHGBMBAR ARNE GUR FRAVBE NCNEGZRAGF, ZNEBBA FHI VF \aCNEXRQ BA J CVAR OYBPXVAT EBNQJNL.
FGRNYVAT\a222 R PBYHZOVN FG\aA URAEL FG & A YBAT NIR\a\a10-12  SEBZ 508 PRAGRE FGERRG ARRQF GB QEBC BSS YVFG BS VGRZF SBE 129
OHETYNEL NYNEZ\a806 ORAG PERRX QE\aUHAG EQ & TERRA OEVNE QE\a\anppvqragnyyl frg bss gur nynez--pnyyrq naq tnir cebcre pbqr cre prageny--fnyg jngre.
1050 W1\aXNEFPU/ZVQQYR\a\a119J\aZBCRQ FHOWRPG YNLVAT BA GUR TEBHAQ
SVTUG\a200 J SVEFG FG\aF SENAXYVA FG & F N FG
FHFCVPVBHF NPGVIVGL\aYVOREGL FG\a\a\agjb zra naf n jbzna\aJNYXVAT VA GUR ZHQ NG GUR ARJ YVOENEL\aJUVGR FUVEG NAQ CNAGF
NFFVFG NZOHYNAPR\a1015 FGR TRARIVRIR NIR\aIRGRENAF QE & IVREFR QE\a\aRZF ABG NAFJREVAT FRPHEVGL PURPXF\a\aGURER SBE NA RYQREYL SRZNYR JUB SRYY
1055 QEVIR\aUJL 32 JRFGOBHAQ \a\a\aSEBZ ZVQJNL ONE NAQ TEVYY\aFRZV FVYIRE GENVYRE CNEGVNYYL PBIRERQ JVGU GNEC
FHFCVPVBHF NPGVIVGL\a915 A JNFUVATGBA FG\aXNEFPU OYIQ & CVAR FG\a\aCNEXVAT YBG \aCRBCYR UNATVAT BHG VA GUR CNEXVAT YBG\aZNYR VA N FZNYY FVYIRE FHI FYHZCRQ BIRE FGRREVAT JURRY\aFBZRBAR NFXRQ UVZ VS ARRQRQ URYC\aFHOWRPG VA QNEX UBBQVR UNATVAT NEBHAQ VA SEBAG BS GUR QBBE
OHETYNEL NYNEZ\a1101 J YVOREGL FG\aJ YVOREGL FG & CNEXYNAQ QE\a\aCUNEZNPL VI ZBGVBA\a\aUBYQ HC NYNEZ\a\a\a\a\aYBPNGVBA ABGRF:  \aN.  Cnexynaq Urnygu Pragre qrirybcrq n fvyrag nynez cbyvpl gb raunapr frphevgl.\aENQVB QVFCNGPU NF 10-30 AHZORE 13 GB GJB CBYVPR HAVGF BAR ORVAT GUR \aFHCREIVFBE, VS NINVYNOYR.\a\aN fvyrag nynez jvyy or cynprq va gur sbyybjvat nernf bs gur snpvyvgl:\a\a1.  Uhzna Erfbheprf Qverpgbe'f Bssvpr\a2.  Uhzna Erfbheprf Erprcgvbavfg'f Qrfx\a3.  Rzretrapl Qrcnegzrag Qrfx\a4.  Phfgbzre Freivpr Qrfx\a5.  Nqzvggvat Ebbz #1\a6.  Zrqvpngvba Ebbz va BO\a7.  Ahefrel va BO\a8.  Pnfuvre'f Qrfx\a9.  Ahefvat Qrfx VPH\a   10.  Enqvbybtl (erzbgr jveryrff)\a   11.  Cuneznpl\a   12.  Vagrafvir Pner\a\aO.  Gur fvyrag nynez jvyy or hgvyvmrq va gur rirag gung n cngvrag, ivfvgbe, rzcyblrr, be zrzore \abs zrqvpny fgnss vf cynprq vagb gur cbfvgvba bs orvat fhowrpgrq gb culfvpny qnatre, jvgu gur \arkgerzr cbgragvny bs npghny hfr bs ivbyrapr ntnvafg gurve crefba naq gur fvghngvba vf frevbhf \arabhtu va angher gb erdhver rkgreany nffvfgnapr sebz gur cbyvpr, ohg abezny gryrcubar \apbagnpg vf vzcenpgvpny be vzcehqrag.\a\aP.  Pbzzhavpngvbaf Bssvpref\a\aHcba erprvivat gur rzretrapl abgvsvpngvba guebhtu gur nynez flfgrz, gur \apbzzhavpngvbaf bssvpre jvyy vzzrqvngryl qvfcngpu na bssvpre gb gur Urnygu Pragre ol hfvat \agur 10-pbqr, 10-30 ng #13.  Gur pbzzhavpngvbaf bssvpre jvyy gura abgvsl gur Urnygu Pragre'f \abcrengbe (756-6451)gung na nynez unf orra chfurq naq gur ybpngvba bs gur nynez.  Vs gur \abcrengbe vf hanoyr gb nafjre gur pnyy cebzcgyl, gur pbzzhavpngvbaf bssvpre jvyy abgvsl gur \aZrqvpny Fhetvpny sybbe (756-8200) jvgu gur fnzr vasbezngvba.\a\aQ.  Bssvpref\a\aVg vf gur erfcbafvovyvgl bs gur Snpvyvgvrf Znantrzrag Qrcnegzrag, be gur Frphevgl \aBssvpre gb erfcbaq naq zrrg gur neevivat cbyvpr bssvpre ng gur fbhgurnfg sver rkvg, fgnvejryy \aO,vasbez gur bssvpre nf gb gur fvghngvba ng unaq, naq gb nppbzcnal gur bssvpre gb gur \aybpngvba bs gur nynez.  Gur bssvpre jvyy gura unaqyr gur fvghngvba ubjrire ur qrrzf \aarprffnel, gbc cevbevgl orvat, fnsrgl sbe rirelbar vaibyirq.\a\aS.  Grfgvat bs gur Fvyrag Nynez\a\aFrphevgl/Snpvyvgvrf Znantrzrag bs gur Cnexynaq Urnygu Pragre jvyy pbagnpg bhe \apbzzhavpngvbaf qvivfvba gb grfg gurve fvyrag nynezf ba na naahny onfvf.\a\aGur grfg jvyy or pneevrq bhg ol n zrzore sebz rnpu nynez fvgr pbagnpgvat qvfcngpu \aol gryrcubar, naq erdhrfgvat n grfg.  N zrzore sebz rnpu nynez fvgr jvyy npgvingr gur fvyrag \anynez, naq gur ybpngvba jvyy nccrne ba bhe nynez flfgrz ng gur cbyvpr qrcnegzrag.  Gur \aqvfcngpure jvyy pbasvez gur ybpngvba bs gur nynez.  Vs n ceboyrz rkvfgf, gur qvfcngpure jvyy \avasbez gur zrzore sebz gur nynez fvgr fb gur vasbezngvba pna or sbejneqrq gb Eboregf \aNynez Flfgrzf sbe ercnve.\a\a\aR.  Frr nggnpurq Cbyvpl sebz Cnexynaq Urnygu Pragre.\aFrr nggnpurq sybbe cyna bs ohvyqvat sbe ybpngvbaf bs nynezf, naq \agur ragenapr sbe gur cbyvpr (fbhgurnfg sver rkvg, fgnvejryy O)\a\a\a\a----------------------------------------
OHETYNEL NYNEZ\a205 R XNEFPU OYIQ\aA JNFUVATGBA FG NAQ A ZVQQYR FG\a\aJVGU CEBTNHEQ\a\aTYNFF OERNXNTR
FHFCVPVBHF NPGVIVGL\aURAEL FG\a\a\aJUVGR PNE CR2M9N \aGNA PNE  PBZCNPG GLCR HAX VASBEZNGVBA \a\aEHAVVAT NEBHAQ PRZRGREL\a8 WHIRAVYRF
FHFCVPVBHF NPGVIVGL\a615 ZNCYR INYYRL QE\aUNMRY YA & ZNCYR FG\a\aVA GUR CNEXVAT YBG SHYY BS WHIRAVYRF\a\aGENFUVAT GUR CNEXVAT YBG\a\aQEVIVAT P&V
OHETYNEL NYNEZ\a2 FHZZVG QE\aA JNFUVATGBA FG & JRFGJBBQ QE\a\aBCRE/ OBO\a\aQHERFF NYNEZ\a\aANAPL EVPR\a\aAB PBAGNPG ZNQR
GERFCNFFVAT\a502 XERV NIR\aDHNEEL FG & R XNEFPU OYIQ\a\aARVTUOBE PUVYQERA UNIR ORRA VA GUR PERRX JUVPU VF CEVINGR CEBCREGL\a\aPNYYRE'F 13 LE BYQ QNHTUGRE GBYQ GURZ GB YRNIR; GURA GUR PUVYQERA'F \aZBGURE GBYQ QNHTUGRE VG JBHYQ OR BX SBE GURZ GB OR GURER FVAPR VG'F \aCHOYVP\a\a\aPNYYRE VF ABG BA FPRAR
FHFCVPVBHF CREFBA\a1301 FHAFUVAR YA\aSBHE FRNFBAF QE\a\aFHFC ZNYR JNYXVAT NEBHAQ RNEYVRE GBQNL.\a\aJZ OYX UBBQVR NAQ OYHR WRNAF, OYX AVXR FUBRF\a\a1FG GENVYRE BA YRSG ONPX QBBE VF JVQR.  ABG FHER VS INPNAG GENVYRE BE \aABG.
QVFGHEONAPR\a1 OYNPX XAVTUG QE\aJ PBYHZOVN & J YVOREGL\a\aPBHAPVYVAT PRAGRE HAFHER BS VFFHR
P & V QEVIVAT\a32 NYZBFG GB PVGL YVZGF\a\a\aJUVGR YVAPBYA PBAGRAGNY OYNPX GBC\a\aNYY BIRE GUR EBNQ\a\aAB CYNGRF
1050 W1\a748 J XNEFPU OYIQ\aJNYGBA & ZNCYR INYYRL \a\a3 PNEF\a\aPURIL VZCNYN JUVGR\aPURIL PNINYVRE TBYQ\aSBEQ RFPNCR BENATR\a\aW3
FGRNYVAT\a820 RYRPGEVP FG\aJRORE EQ & CBGBFV FG\a\aUBHFR AHZORE 1 NZOHYNAPR \a\a2 YNCGBCF FGBYRA\a\aGENVAVAT PRAGRE NERN BSS BS RYRPGEVP FG
QVFGHEONAPR\a2 A JNFUVATGBA FG\aPBYHZOVN FG & YVOREGL FG\a\aPHFGBZRE JNF ORVAT QVFGEHCGVIR\a\aPNYYRE QVQ NQIVFR GUNG UR JNF YRNIVAT
QEHT BSSRAFR\a1040 SBEFGRE FG\aF SYRZVAT NIR & JNYGRE FG
FHFCVPVBHF NPGVIVGL\a102 EBOOL YA\aA JNFUVATGBA FG & UVYYFOBEB EQ\a\aJZ UNG CBFF ERQ NAQ GNA FUBEGF NAQ JNYXRQ VAGB GUR ERFVQRAPR
OHETYNEL NYNEZ\a218 J YVOREGL FG\aA SENAXYVA FG & A N FG\a\aPBMRNA PERZRGBEL ONL QBBE NAQ ONPX RAGEL QBBE
OHETYNEL NYNEZ\a443 FURANAQBNU QE\aTENAQ PNALBA QE & UVYYFOBEB EQ\a\aFVYRAG CNAVP NYNEZ\a\a\aZNYR BA GUR FPRAR JVGU AB CNFF JBEQ\a\aTNEL RYYRE
1050 W1\a614 JNYZNEG QE\aJNYGBA QE & CBGBFV FG\a\aOYNPX UBAQN CI\aJUVGR PVGL BS SNEZVATGBA JBEX GEHPX\a\aORUVAQ GUR OHVYQVAT
OHETYNEL NYNEZ\a1100 FGR TRARIVRIR NIR\aIVREFR QE & XNEFPU OYIQ\a\aAB FCRPVSVP YBPNGVBA  OHETYNEL ZBGVBA
QVFGHEONAPR\a510 F SENAXYVA FG\aSBHEGU FG & FRIRAGU FG\a124U
QVFGHEONAPR\a920 IREABA NIR\aLNYR NIR & NYQRETNGR FG\a\aEBANYQ ZHYYVANK VF VA GUR UBHFR NAQ JVYY ABG YRNIR\a45 LRNE BYQ ZNYR
FHFCVPVBHF NPGVIVGL\a67 FO SEBZ SNVETEBHAQF\a\a\a67 FO SEBZ SNVE TEBHAQF\a\aJUVGR QHNYYL SYNG ORQ\a\aQBT GVRQ GB SYNG ORQ
FHFCVPVBHF CREFBA\a209 A PNEYRGBA FG\aFGR TRARIVRIR NIR & R PBYYRTR NIR\a\aGUR TERRA BYQRE ZBQRY ZHFPYR PNE\a\aNG GUR QNL PNER
1050 W1\a1609 J PBYHZOVN FG\aJRFGZBHAG QE & UJL 67\a\aPUNEGRE INA CNEXRQ ARNE GUR CHZCF
OHETYNEL NYNEZ\a3 A WRSSREFBA FG\aJ PBYHZOVN FG & J PBYYRTR NIR\a\aZVQPBZ\a\aPBQR 3131 SEBAG QBBE\a\aXRVGU CRGGL 7479598\aZNEFUN CRGGL 7479578\aNAQL CRGGL 3300205
1050 W1\a1609 J PBYHZOVN FG\aJRFGZBHAG QE & UJL 67\a\aW3\a2009 ULHAQNV FNAGN SR NAQ N 2005 QHENATB
OHETYNEL NYNEZ\a140 JRFGZBHAG QE\aJ YVOREGL FG & J PBYHZOVN FG\a\apryy onpxhc\a\awbua svgm 756-6968 naq 760-4140\anagbar orgun 760-8697\acnz xraarql 756-0548\aqrr yhrxrgzrlre 756-8392
PURPX GUR JRYY ORVAT\a316 F WRSSREFBA FG\aJ SVEFG FG & GUVEQ FG\a\airebavpn qnygba 25 lb srznyr\afhssref sebz qrcerffvba\afnvq fur jnf ba gur cubar jvgu fhvpvqr ubgyvar\apnyyre vf gur sngure, pnyyvat sebz Trbetvn\asngure erdhrfgrq ur or pbagnpgrq nsgre gur pnyy cyrnfr

*/

choyvp pynff ZBSnezvatgbaCnefreGrfg rkgraqf OnfrCnefreGrfg {
  
  choyvp ZBSnezvatgbaCnefreGrfg() {
    frgCnefre(arj ZBSnezvatgbaCnefre(), "SNEZVATGBA", "ZB");
  }

  @Grfg
  choyvp ibvq grfgSnezvatgbaCQ() {

    qbGrfg("G1",
        "1050 W HAXABJA\a222 R PBYHZOVN FG\aA URAEL FG & A YBAT NIR\a\a10-12 SVER UBHFR\a\aBPPHERQ 67 & 32",
        "PNYY:1050 W HAXABJA",
        "NQQE:222 R PBYHZOVN FG",
        "K:A URAEL FG & A YBAT NIR",
        "VASB:10-12 SVER UBHFR\aBPPHERQ 67 & 32");

    qbGrfg("G2",
        "FGRNYVAT\a1609 J PBYHZOVN FG\aJRFGZBHAG QE & UJL 67",
        "PNYY:FGRNYVAT",
        "NQQE:1609 J PBYHZOVN FG",
        "K:JRFGZBHAG QE & UJL 67");

    qbGrfg("G3",
        "1050 W1\a775 JRORE EQ\aZNCYR INYYRL & XNEFPU\a\aARNE PNGSVFU XRGGYR",
        "PNYY:1050 W1",
        "NQQE:775 JRORE EQ",
        "K:ZNCYR INYYRL & XNEFPU",
        "VASB:ARNE PNGSVFU XRGGYR");

    qbGrfg("G4",
        "QBZRFGVP\a" +
        "223 FCEHPR FG\a" +
        "A ZVQQYR FG & A PNEYRGBA FG\a\a" +
        "ZBGURE IF QNHTGURE GRRANTRE.  GRRANTRE BA SBBG F BA PNEYRGBA CVAX \a" +
        "FUVEG OYX CNAGF JS \a\a" +
        "ZBGURE VF NG ERFVQRAPR.  EC FGNGRQ ZBGURE JNF NFFNHYGVAT QNHTUGRE.  \a" +
        "FBZRGUVAT NOBHG N FVYIRE WRRC YVOREGL",

        "PNYY:QBZRFGVP",
        "NQQE:223 FCEHPR FG",
        "K:A ZVQQYR FG & A PNEYRGBA FG",
        "VASB:ZBGURE IF QNHTGURE GRRANTRE.  GRRANTRE BA SBBG F BA PNEYRGBA CVAX\aFUVEG OYX CNAGF JS\aZBGURE VF NG ERFVQRAPR.  EC FGNGRQ ZBGURE JNF NFFNHYGVAT QNHTUGRE.\aFBZRGUVAT NOBHG N FVYIRE WRRC YVOREGL");

    qbGrfg("G5",
        "GERFCNFFVAT\a510 A SENAXYVA FG\aQBFF FG & ABEGU FG\a\aGRNY FUBEG FYRRIR FUVEG FUBEGF NAQ CBALGNVY JZ JNYXRQ VAGB EC",
        "PNYY:GERFCNFFVAT",
        "NQQE:510 A SENAXYVA FG",
        "K:QBFF FG & ABEGU FG",
        "VASB:GRNY FUBEG FYRRIR FUVEG FUBEGF NAQ CBALGNVY JZ JNYXRQ VAGB EC");

    qbGrfg("G6",
        "FHFCVPVBHF CREFBA\a" +
        "705 QRJRL NIR\a" +
        "OBLPR NIR & XVAMRE FG\a\a" +
        "INPNAG ERFVQRAPR.  JZ JRNEVAT TEA GNA FUBEGF ONVTR OEB UBBQVR JVGU \a" +
        "UBBQ HC JNF CRRXVAT VA JVAQBJF NAQ JRAG VAGB GUR PBIRERQ CBEPU \a" +
        "NERN.",

        "PNYY:FHFCVPVBHF CREFBA",
        "NQQE:705 QRJRL NIR",
        "K:OBLPR NIR & XVAMRE FG",
        "VASB:INPNAG ERFVQRAPR.  JZ JRNEVAT TEA GNA FUBEGF ONVTR OEB UBBQVR JVGU\aUBBQ HC JNF CRRXVAT VA JVAQBJF NAQ JRAG VAGB GUR PBIRERQ CBEPU\aNERN.");

    qbGrfg("G7",
        "OHETYNEL NYNEZ\aJRORE EQ\aPBYHZOVN FG & PBYYRTR NIR\a\aNHQVOYR NYNEZ FBHAQVAT",
        "PNYY:OHETYNEL NYNEZ",
        "NQQE:JRORE EQ",
        "ZNQQE:JRORE EQ & PBYHZOVN FG", //qbrf abg znc
        "K:PBYHZOVN FG & PBYYRTR NIR",
        "VASB:NHQVOYR NYNEZ FBHAQVAT");

    qbGrfg("G8",
        "FHFCVPVBHF CREFBA\a" +
        "902 ZVPUVTNA FG\a" +
        "XNEFPU OYIQ & CVAR FG\a\a" +
        "JUVGR ZNYR ERQ GRR FUVEG LBHATRE XVQ\a" +
        "JNYXRQ GUEBHTU PNYYRE'F ONPXLNEQ GBJNEQF ZVQQYR FG\a" +
        "UR JBHYQA'G YRNIR SBE NYZBFG 5 ZVAHGRF\a" +
        "JNF JNAGVAT GB HFR GUR CUBAR",

        "PNYY:FHFCVPVBHF CREFBA",
        "NQQE:902 ZVPUVTNA FG",
        "K:XNEFPU OYIQ & CVAR FG",
        "VASB:JUVGR ZNYR ERQ GRR FUVEG LBHATRE XVQ\aJNYXRQ GUEBHTU PNYYRE'F ONPXLNEQ GBJNEQF ZVQQYR FG\aUR JBHYQA'G YRNIR SBE NYZBFG 5 ZVAHGRF\aJNF JNAGVAT GB HFR GUR CUBAR");

    qbGrfg("G9",
        "OHETYNEL NYNEZ\a" +
        "301 A JNFUVATGBA FG\a" +
        "PBYYRTR NIR & CNGGREFBA FG\a\a" +
        "RIRAG PBQR ABG SBHAQ\a\a" +
        "WNZRF JVYYVF 756-4810 NAQ 701-2980\a" +
        "ZRTNA ZNEYRE 749-3373 NAQ 330-4139",

        "PNYY:OHETYNEL NYNEZ",
        "NQQE:301 A JNFUVATGBA FG",
        "K:PBYYRTR NIR & CNGGREFBA FG",
        "VASB:RIRAG PBQR ABG SBHAQ\aWNZRF JVYYVF 756-4810 NAQ 701-2980\aZRTNA ZNEYRE 749-3373 NAQ 330-4139");

    qbGrfg("G10",
        "FHFCVPVBHF CREFBA\aPBAFGEHPGVBA NERN BSS SBEFGRE\a\a111F",
        "PNYY:FHFCVPVBHF CREFBA",
        "NQQE:PBAFGEHPGVBA NERN BSS SBEFGRE",
        "ZNQQE:PBAFGEHPGVBA NERN & SBEFGRE",
        "VASB:111F");

    qbGrfg("G11",
        "FHFCVPVBHF CREFBA\aF SYRZVAT ARNE SBEFGRE\a\a111F\aNGGRZCGVAT GB YBPNGR N FHOWRPG",
        "PNYY:FHFCVPVBHF CREFBA",
        "NQQE:F SYRZVAT",
        "CYNPR:ARNE SBEFGRE",
        "VASB:111F\aNGGRZCGVAT GB YBPNGR N FHOWRPG");

    qbGrfg("G12",
        "FHFCVPVBHF IRUVPYR\a1400 NVE CNEX QE\aINETB EQ\a128O\aBHG OL GUR ONFRONYY SVRYQF",
        "PNYY:FHFCVPVBHF IRUVPYR",
        "NQQE:1400 NVE CNEX QE",
        "K:INETB EQ",
        "VASB:128O\aBHG OL GUR ONFRONYY SVRYQF");

    qbGrfg("G13",
        "NFFVFG NZOHYNAPR\a310 YNHEN NIR\aF N FG & GNLYBE NIR\a\a4 JRRX BYQ ONOL ABG OERNGUVAT",
        "PNYY:NFFVFG NZOHYNAPR",
        "NQQE:310 YNHEN NIR",
        "K:F N FG & GNLYBE NIR",
        "VASB:4 JRRX BYQ ONOL ABG OERNGUVAT");

    qbGrfg("G14",
        "1050 W1\a67AO CNFG WBUA QRRER\a\a111F",
        "PNYY:1050 W1",
        "NQQE:67AO CNFG WBUA QRRER", //qbrf abg znc
        "ZNQQE:67 CNFG WBUA QRRER",
        "VASB:111F");

    qbGrfg("G15",
        "QEHT BSSRAFR\a" +
        "309 FVKGU FG\a" +
        "F N FG & CREEVAR EQ\a\a" +
        "GVZ UNEEVF TBG N PNYY GUNG GUVF VF UNCCRAVAT\a" +
        "EVPX PYNEX VF GURER ABJ PBBXVAT ZRGU VA GUR ONGUEBBZ\a" +
        "UBHFR ORYBATF GB NATRYN ORAFPBGRE",

        "PNYY:QEHT BSSRAFR",
        "NQQE:309 FVKGU FG",
        "K:F N FG & CREEVAR EQ",
        "VASB:GVZ UNEEVF TBG N PNYY GUNG GUVF VF UNCCRAVAT\aEVPX PYNEX VF GURER ABJ PBBXVAT ZRGU VA GUR ONGUEBBZ\aUBHFR ORYBATF GB NATRYN ORAFPBGRE");

    qbGrfg("G16",
        "JNEENAG NEERFG\aWRSS PB\a\a104U\aRAEBHGR GB WRSSREFBA PB SBE JNEENAG CVPX HC",
        "PNYY:JNEENAG NEERFG",
        "NQQE:WRSS PB",
        "VASB:104U\aRAEBHGR GB WRSSREFBA PB SBE JNEENAG CVPX HC");

    qbGrfg("G17",
        "GENSSVP UNMNEQ\a67AO\a\a122Z\aerzbivat vgrzf sebz gur ebnq",
        "PNYY:GENSSVP UNMNEQ",
        "NQQE:67AO",
        "ZNQQE:67",
        "VASB:122Z\aerzbivat vgrzf sebz gur ebnq");

    qbGrfg("G18",
        "FGRNYVAT\a222 R PBYHZOVN FG\aA URAEL FG & A YBAT NIR\a\aFGBYRA CUBAR",
        "PNYY:FGRNYVAT",
        "NQQE:222 R PBYHZOVN FG",
        "K:A URAEL FG & A YBAT NIR",
        "VASB:FGBYRA CUBAR");

    qbGrfg("G19",
        "FGRNYVAT\a253 TRAQNYR QE\aZRNQBJOEBBX QE & XRAJBBQ QE",
        "PNYY:FGRNYVAT",
        "NQQE:253 TRAQNYR QE",
        "K:ZRNQBJOEBBX QE & XRAJBBQ QE");

    qbGrfg("G20",
        "QBZRFGVP\a406 CREEVAR EQ\aJ PBYHZOVN FG & OBLPR NIR",
        "PNYY:QBZRFGVP",
        "NQQE:406 CREEVAR EQ",
        "K:J PBYHZOVN FG & OBLPR NIR");

    qbGrfg("G21",
        "1050 W1\a507 CBGBFV FG\aZNCYR FG & XNEFPU OYIQ\a\aerq sbeq gehpx\a\atzp qranyv juvgr va pbybe\a\aab vawhevrf",
        "PNYY:1050 W1",
        "NQQE:507 CBGBFV FG",
        "K:ZNCYR FG & XNEFPU OYIQ",
        "VASB:erq sbeq gehpx\atzp qranyv juvgr va pbybe\aab vawhevrf");

    qbGrfg("G22",
        "FGRNYVAT\a684 JNYGBA QE\aZNCYR FG & XNEFPU OYIQ\a\aSNVYHER GB ERGHEA ERAGNY CEBCREGL",
        "PNYY:FGRNYVAT",
        "NQQE:684 JNYGBA QE",
        "K:ZNCYR FG & XNEFPU OYIQ",
        "VASB:SNVYHER GB ERGHEA ERAGNY CEBCREGL");

    qbGrfg("G1",
        "NFFNHYG\a" +
        "1 OYNPX XAVTUG QE\a" +
        "J PBYHZOVN & J YVOREGL\a" +
        "121J\a" +
        "YBPNGVBA ABGRF:  \a" +
        "SVEFG FGNGR PBZZHAVGL ONAX OYNPX XAVTUG OENAPU 701-9749 YBPNGVBA VQ \a" +
        "#14 ERSRE GB FCRPVNY CEBPRQHER SBE ONAX NYNEZF. \a" +
        "CNFFJBEQ / PHFGBZRE VQ 0009\a\a" +
        "ENQVB QVFCNGPU NF 10-30 AHZORE 14  (GJB HAVGF BAR ORVAT N FHCREIVFBE VS \a" +
        "NINVYNOYR)\a" +
        "VS 121 BE 124 NER JBEXVAT QVFCNGPU GURZ FVAPR YBPNGVBA VF UVTU FPUBBY.\a\a" +
        "QVFCNGPURE ERFCBAFVOYVGVRF\a" +
        "Vs gur eboorel abgvsvpngvba vf znqr ol nynez, gur qvfcngpure funyy, nsgre qvfcngpuvat gjb \a" +
        "havgf gb gur fprar, nggrzcg gbpbagnpg gur vafgvghgvba va beqre gb qrgrezvar gur inyvqvgl bs \a" +
        "gur nynez.  Gur pbairefngvba jvyy or nf sbyybjf:\a" +
        "N.QVFCNGPURE:  \"Guvf vf Snezvatgba Cnpxntr Qryvirel.  Qvq lbh\a" +
        "erprvir gur cnpxntr jr frag lrfgreqnl:\"\a" +
        "O.NAFJREVAT CNEGL:  \"Lrf jr qvq.  Vg jnf cnpxntr ahzore____.\"\a" +
        "Gurve phfgbzre VQ ahzore jvyy or hfrq sbe gur cnpxntr\a" +
        "ahzore.) Guvf erfcbafr vaqvpngrf n snyfr nynez.  Nal bgure\a" +
        "erfcbafr vaqvpngrf n ubyqhc.  Qvfpbaarpg jvgu gur pnyyre naq\a" +
        "                                                gura gur Qvfcngpure jvyy abgvsl erfcbaqvat havgf jurgure be \a" +
        "abg gur \a" +
        "                                                cebcre pbqr jnf tvira.\a\a" +
        "                Vs gur qvfcngpure vf abgvsvrq ol gur svanapvny vafgvghgvba gung\a" +
        "na nynez vf snyfr, be gur cebcre pbqr vf tvira, gur qvfcngpure\a" +
        "funyy nqivfr gur cnegl gung bssvpref ner raebhgr naq gung\a" +
        "fbzrbar jvyy arrq gb rkvg gur snpvyvgl ng gur sebag qbbe gb zrrg\a" +
        " gur erfcbaqvat bssvpref.\a\a" +
        "                                Vs gur eboorel abgvsvpngvba vf erprvirq ol gryrcubar, n pbzcyrgr\a" +
        "qrfpevcgvba bs gur crecrgengbef funyy or bognvarq sebz gur\a" +
        "pnyyre nybat jvgu nf zhpu nqqvgvbany vasbezngvba nf cbffvoyr;\a" +
        "cnegvphyneyl, jurgure jrncbaf ner vaibyirq, jurgure gur\a" +
        "crecrgengbe vf ng gur fprar naq, vs abg, uvf qverpgvba naq zbqr\a" +
        "bs geniry naq pbzcyrgr qrfpevcgvba bs nal iruvpyr vaibyirq.\a\a" +
        "                                GRFG BS NYNEZF\a\a" +
        "Vs gur qvfcngpure erprvirf n pnyy sebz n onax be bgure svanapvny\a" +
        "vafgvghgvba gung gurl jvyy or grfgvat gurve nynez, gur qvfcngpure\a" +
        "funyy nfx gur pnyyre sbe gurve phfgbzre VQ ahzore.  Vs gur pnyyre\a" +
        "pnaabg cebivqr gur pbeerpg ahzore, bssvpref jvyy or qvfcngpurq gb\a" +
        "gur ybpngvba naq cebprqherf sbe nynez erprvcg (nf bhgyvarq va VVV.N.\a" +
        "naq VVV.O.) jvyy or vavgvngrq.\a\a\a" +
        "----------------------------------------",

        "PNYY:NFFNHYG",
        "NQQE:1 OYNPX XAVTUG QE",
        "K:J PBYHZOVN & J YVOREGL",
        "VASB:121J\aYBPNGVBA ABGRF:\aSVEFG FGNGR PBZZHAVGL ONAX OYNPX XAVTUG OENAPU 701-9749 YBPNGVBA VQ\a#14 ERSRE GB FCRPVNY CEBPRQHER SBE ONAX NYNEZF.\aCNFFJBEQ / PHFGBZRE VQ 0009\aENQVB QVFCNGPU NF 10-30 AHZORE 14  (GJB HAVGF BAR ORVAT N FHCREIVFBE VS\aNINVYNOYR)\aVS 121 BE 124 NER JBEXVAT QVFCNGPU GURZ FVAPR YBPNGVBA VF UVTU FPUBBY.\aQVFCNGPURE ERFCBAFVOYVGVRF\aVs gur eboorel abgvsvpngvba vf znqr ol nynez, gur qvfcngpure funyy, nsgre qvfcngpuvat gjb\ahavgf gb gur fprar, nggrzcg gbpbagnpg gur vafgvghgvba va beqre gb qrgrezvar gur inyvqvgl bs\agur nynez.  Gur pbairefngvba jvyy or nf sbyybjf:\aN.QVFCNGPURE:  \"Guvf vf Snezvatgba Cnpxntr Qryvirel.  Qvq lbh\aerprvir gur cnpxntr jr frag lrfgreqnl:\"\aO.NAFJREVAT CNEGL:  \"Lrf jr qvq.  Vg jnf cnpxntr ahzore____.\"\aGurve phfgbzre VQ ahzore jvyy or hfrq sbe gur cnpxntr\aahzore.) Guvf erfcbafr vaqvpngrf n snyfr nynez.  Nal bgure\aerfcbafr vaqvpngrf n ubyqhc.  Qvfpbaarpg jvgu gur pnyyre naq\agura gur Qvfcngpure jvyy abgvsl erfcbaqvat havgf jurgure be\aabg gur\acebcre pbqr jnf tvira.\aVs gur qvfcngpure vf abgvsvrq ol gur svanapvny vafgvghgvba gung\ana nynez vf snyfr, be gur cebcre pbqr vf tvira, gur qvfcngpure\afunyy nqivfr gur cnegl gung bssvpref ner raebhgr naq gung\afbzrbar jvyy arrq gb rkvg gur snpvyvgl ng gur sebag qbbe gb zrrg\agur erfcbaqvat bssvpref.\aVs gur eboorel abgvsvpngvba vf erprvirq ol gryrcubar, n pbzcyrgr\aqrfpevcgvba bs gur crecrgengbef funyy or bognvarq sebz gur\apnyyre nybat jvgu nf zhpu nqqvgvbany vasbezngvba nf cbffvoyr;\acnegvphyneyl, jurgure jrncbaf ner vaibyirq, jurgure gur\acrecrgengbe vf ng gur fprar naq, vs abg, uvf qverpgvba naq zbqr\abs geniry naq pbzcyrgr qrfpevcgvba bs nal iruvpyr vaibyirq.\aGRFG BS NYNEZF\aVs gur qvfcngpure erprvirf n pnyy sebz n onax be bgure svanapvny\avafgvghgvba gung gurl jvyy or grfgvat gurve nynez, gur qvfcngpure\afunyy nfx gur pnyyre sbe gurve phfgbzre VQ ahzore.  Vs gur pnyyre\apnaabg cebivqr gur pbeerpg ahzore, bssvpref jvyy or qvfcngpurq gb\agur ybpngvba naq cebprqherf sbe nynez erprvcg (nf bhgyvarq va VVV.N.\anaq VVV.O.) jvyy or vavgvngrq.\a----------------------------------------");

    qbGrfg("G24",
        "1050 W1\aZNCYR/JNFUVATGBA\a\a\aJUG RAIBL\a\aTEA PNE",
        "PNYY:1050 W1",
        "NQQE:ZNCYR & JNFUVATGBA",
        "VASB:JUG RAIBL\aTEA PNE");

    qbGrfg("G25",
        "P & V QEVIVAT\a" +
        "R XNEFPU OYIQ\a\a\a" +
        "18 JURRYRE EHAAVAT IRU BSS GUR EBNQ.  BA UJL 67 GBBX RO XNEFPU RKVG.  \a" +
        "JUG GENPGBE GENVYRE CHYYVAT N SYNG ORQ GENVYRE.  ZRGNY OHVYQVAT FHCCYL \a" +
        "SEBZ NEXNAFNF.  CG117798",

        "PNYY:P & V QEVIVAT",
        "NQQE:R XNEFPU OYIQ",
        "VASB:18 JURRYRE EHAAVAT IRU BSS GUR EBNQ.  BA UJL 67 GBBX RO XNEFPU RKVG.\aJUG GENPGBE GENVYRE CHYYVAT N SYNG ORQ GENVYRE.  ZRGNY OHVYQVAT FHCCYL\aSEBZ NEXNAFNF.  CG117798");

    qbGrfg("G26",
        "GENSSVP UNMNEQ\aJ XNEFPU OYIQ\aZNCYR INYYRL\a126O\atebprevrf va gur yrsg ghea ynar",
        "PNYY:GENSSVP UNMNEQ",
        "NQQE:J XNEFPU OYIQ",
        "ZNQQE:J XNEFPU OYIQ & ZNCYR INYYRL",
        "K:ZNCYR INYYRL",
        "VASB:126O\atebprevrf va gur yrsg ghea ynar");

    qbGrfg("G27",
        "FGRNYVAT\a1440 SBKTYBIR FG\aSBK TYRA QE & TERL SBK\a\aGURSG BS ZRQVPNGVBA",
        "PNYY:FGRNYVAT",
        "NQQE:1440 SBKTYBIR FG",
        "K:SBK TYRA QE & TERL SBK",
        "VASB:GURSG BS ZRQVPNGVBA");

    qbGrfg("G28",
        "OHETYNEL NYNEZ\a612 JNYZNEG QE\aJNYGBA QE & CBGBFV FG\a\aERNE ZBGVBA",
        "PNYY:OHETYNEL NYNEZ",
        "NQQE:612 JNYZNEG QE",
        "K:JNYGBA QE & CBGBFV FG",
        "VASB:ERNE ZBGVBA");

    qbGrfg("G29",
        "OHETYNEL NYNEZ\a" +
        "763 ZNCYR INYYRL QE\a" +
        "ZNCYR FG & ZNEXRG FG\a\a" +
        "UNYY ZBGVBA, SEBAG NAQ CVG ZBGVBA.\a\a" +
        "PBYYVA BA FVGR JBEXF GURER QBRF ABG UNIR PBQRF BE CNFFJBEQ.",

        "PNYY:OHETYNEL NYNEZ",
        "NQQE:763 ZNCYR INYYRL QE",
        "K:ZNCYR FG & ZNEXRG FG",
        "VASB:UNYY ZBGVBA, SEBAG NAQ CVG ZBGVBA.\aPBYYVA BA FVGR JBEXF GURER QBRF ABG UNIR PBQRF BE CNFFJBEQ.");

    qbGrfg("G30",
        "OEBNQPNFG ZRFFNTR\a" +
        "310 FGR TRARIVRIR NIR\a" +
        "A ZNVA FG & F PNEYRGBA FG\a\a" +
        "FRAG GB PRX4, PFRZ\a\a" +
        "****BSSVPRE FNSRGL****\a" +
        "****NEZRQ FHOWRPG****\a\a" +
        "FHOWRPG NEZRQ JVGU 9ZZ CVFGBY\a\a" +
        "OERAQN QNIVF, JUVGR SRZNYR, 19621028, QEVIVAT N OYNPX 2000 RKGRAQRQ \a" +
        "PNO, QBQTR \a" +
        "ENZ GEHPX JVGU QNZNTR ORUVAQ GUR QEVIREF FVQR QBBE, ZVFFBHEV CYNGR \a" +
        "0LO794.\a" +
        "CBCYNE OYHSS CBYVPR QRCNEZRAG UNF ERPRVIRQ VASBEZNGVBA GUNG QNIVF \a" +
        "UNF GNXRA\a" +
        "ZHYGVCYR ANEPBGVPF, NAQ VF GUERNGRAVAT FHVPVQR. YNFG FRRA VA CBCYNE \a" +
        "OYHSS NG\a" +
        "NCCEBKVZNGRYL 0230 UBHEF, RAEBHGR GB NA HAXABJA YBPNGVBA.\a\a\a" +
        "/F/YRJVF, UBYYL\a" +
        "CBCYNE OYHSS CQ      20150518      0313\a\a\a" +
        "ZEV: 22636332 VA: PRX4 29 NG 18ZNL2015 03:26:23\a" +
        "BHG: P262 32 NG 18ZNL2015 03:26:23",

        "PNYY:OEBNQPNFG ZRFFNTR",
        "NQQE:310 FGR TRARIVRIR NIR",
        "K:A ZNVA FG & F PNEYRGBA FG",
        "VASB:FRAG GB PRX4, PFRZ\a****BSSVPRE FNSRGL****\a****NEZRQ FHOWRPG****\aFHOWRPG NEZRQ JVGU 9ZZ CVFGBY\aOERAQN QNIVF, JUVGR SRZNYR, 19621028, QEVIVAT N OYNPX 2000 RKGRAQRQ\aPNO, QBQTR\aENZ GEHPX JVGU QNZNTR ORUVAQ GUR QEVIREF FVQR QBBE, ZVFFBHEV CYNGR\a0LO794.\aCBCYNE OYHSS CBYVPR QRCNEZRAG UNF ERPRVIRQ VASBEZNGVBA GUNG QNIVF\aUNF GNXRA\aZHYGVCYR ANEPBGVPF, NAQ VF GUERNGRAVAT FHVPVQR. YNFG FRRA VA CBCYNE\aOYHSS NG\aNCCEBKVZNGRYL 0230 UBHEF, RAEBHGR GB NA HAXABJA YBPNGVBA.\a/F/YRJVF, UBYYL\aCBCYNE OYHSS CQ      20150518      0313\aZEV: 22636332 VA: PRX4 29 NG 18ZNL2015 03:26:23\aBHG: P262 32 NG 18ZNL2015 03:26:23");

    qbGrfg("G31",
        "PURPX GUR JRYY ORVAT\a" +
        "857 CBGBFV FG\a" +
        "ZNCYR INYYRL QE & YBT PNOVA YA\a\a" +
        "WRERZL FGERRG CBFF GNXRA CVYYF \a" +
        "PNYYRE FGNGRQ GUNG UR FNJ BA FHOWRPGF SNPR OBBX GUNG UR UNQ GNXRA \a" +
        "80 NGNINA\a" +
        "PNCR PURPXRQ NAQ PNA'G SVAQ NA NQQERFF VA GURER BAYL NQQERFF URER",

        "PNYY:PURPX GUR JRYY ORVAT",
        "NQQE:857 CBGBFV FG",
        "K:ZNCYR INYYRL QE & YBT PNOVA YA",
        "VASB:WRERZL FGERRG CBFF GNXRA CVYYF\aPNYYRE FGNGRQ GUNG UR FNJ BA FHOWRPGF SNPR OBBX GUNG UR UNQ GNXRA\a80 NGNINA\aPNCR PURPXRQ NAQ PNA'G SVAQ NA NQQERFF VA GURER BAYL NQQERFF URER");

    qbGrfg("G32",
        "QVFGHEONAPR\a201 ULYRE QE\aJ PBYHZOVN FG\a\aZNYR FHOWRPG PUNFVAT N SRZNYR \aPNE SBYYBJVAT GNA BE FVYIRE",
        "PNYY:QVFGHEONAPR",
        "NQQE:201 ULYRE QE",
        "K:J PBYHZOVN FG",
        "VASB:ZNYR FHOWRPG PUNFVAT N SRZNYR\aPNE SBYYBJVAT GNA BE FVYIRE");

    qbGrfg("G33",
        "FHFCVPVBHF IRUVPYR\a" +
        "775 JRORE EQ\a" +
        "ZNCYR INYYRL & XNEFPU\a\a" +
        "GEHPX NAQ N WRRC HAX PBYBE  CBFF N ERQ IRUVPYR \a" +
        "VA GUR ONPX  CNEXVAT YBG\a" +
        "FNLF GURL FUBHYQ OR PYBFRQ YBBXF FHFCVPVBHF",

        "PNYY:FHFCVPVBHF IRUVPYR",
        "NQQE:775 JRORE EQ",
        "K:ZNCYR INYYRL & XNEFPU",
        "VASB:GEHPX NAQ N WRRC HAX PBYBE  CBFF N ERQ IRUVPYR\aVA GUR ONPX  CNEXVAT YBG\aFNLF GURL FUBHYQ OR PYBFRQ YBBXF FHFCVPVBHF");

    qbGrfg("G34",
        "FHFCVPVBHF IRUVPYR\a" +
        "909 R XNEFPU OYIQ\a" +
        "XERV NIR & FGR TRARIVRIR NIR\a\a" +
        "PNQVYYNP PGF \a" +
        "JUVGR \a" +
        "HAX CYNGR \a" +
        "QEVIVAT NEBHAQ GUR CNEXVAT YBG BS FGBENTR FURQF \a" +
        "J XNEFPU GBJNEQ UJL 67",

        "PNYY:FHFCVPVBHF IRUVPYR",
        "NQQE:909 R XNEFPU OYIQ",
        "K:XERV NIR & FGR TRARIVRIR NIR",
        "VASB:PNQVYYNP PGF\aJUVGR\aHAX CYNGR\aQEVIVAT NEBHAQ GUR CNEXVAT YBG BS FGBENTR FURQF\aJ XNEFPU GBJNEQ UJL 67");

    qbGrfg("G35",
        "1055 FHOWRPG\a" +
        "838 INYYRL PERRX QE\a" +
        "ZNCYR INYYRL QE & ZNEXRG FG\a\a" +
        "NATEL NAQ LRYYVAT ZNYR UNQ CNFFRQ BHG,VA GUR YBOOL, ERSHFVAT RZF, \a" +
        "UBJRIRE OYHR FUVEG NAQ WRNAF. EC VF 3EQ CNEGL. FUR VF HAFHER VS UR UNF \a" +
        "N ZRQVPNY PBAQVGVBA BE VF 1055. ZNL OR BHGFVQR GUR GURNGRE.",

        "PNYY:1055 FHOWRPG",
        "NQQE:838 INYYRL PERRX QE",
        "K:ZNCYR INYYRL QE & ZNEXRG FG",
        "VASB:NATEL NAQ LRYYVAT ZNYR UNQ CNFFRQ BHG,VA GUR YBOOL, ERSHFVAT RZF,\aUBJRIRE OYHR FUVEG NAQ WRNAF. EC VF 3EQ CNEGL. FUR VF HAFHER VS UR UNF\aN ZRQVPNY PBAQVGVBA BE VF 1055. ZNL OR BHGFVQR GUR GURNGRE.");

    qbGrfg("G36",
        "P & V QEVIVAT\a67FO/ZNCYR\a\a\aL85X1U ERQ PNZNEB NYY BIRE GUR EBNQJNL. SNVYHER GB ZNVAGNVA N YNAR",
        "PNYY:P & V QEVIVAT",
        "NQQE:67FO & ZNCYR",
        "ZNQQE:67 & ZNCYR",
        "VASB:L85X1U ERQ PNZNEB NYY BIRE GUR EBNQJNL. SNVYHER GB ZNVAGNVA N YNAR");

    qbGrfg("G37",
        "OHETYNEL NYNEZ\a" +
        "902 CEBTERFF QE\a" +
        "J PBYHZOVN FG & QBHORG EQ\a\a" +
        "RAGEL RKVG OHETYNEL. \a\a" +
        "BHGFVQR NYNEZ PBZCNAL UNF ABG ORRA NOYR GB ZNXR PBAGNPG JVGU \a" +
        "XRLUBYQREF LRG  160598560 ERSRERAPR BCRENGBE S465",

        "PNYY:OHETYNEL NYNEZ",
        "NQQE:902 CEBTERFF QE",
        "K:J PBYHZOVN FG & QBHORG EQ",
        "VASB:RAGEL RKVG OHETYNEL.\aBHGFVQR NYNEZ PBZCNAL UNF ABG ORRA NOYR GB ZNXR PBAGNPG JVGU\aXRLUBYQREF LRG  160598560 ERSRERAPR BCRENGBE S465");

    qbGrfg("G38",
        "1050 W1\a775 JRORE EQ\aZNCYR INYYRL & XNEFPU",
        "PNYY:1050 W1",
        "NQQE:775 JRORE EQ",
        "K:ZNCYR INYYRL & XNEFPU");

    qbGrfg("G39",
        "FGRNYVAT\a222 R PBYHZOVN FG\aA URAEL FG & A YBAT NIR\a\aOYO FGBENTR",
        "PNYY:FGRNYVAT",
        "NQQE:222 R PBYHZOVN FG",
        "K:A URAEL FG & A YBAT NIR",
        "VASB:OYO FGBENTR");

    qbGrfg("G40",
        "1050 W HAXABJA\a538 WBUA QNIVQ QE\aQNYR QE & FGBARTNGR FG\a\a1 IRUVPYR VAGB N CBYR NAQ ZNVYOBK, SVER NAQ RZF RAEBHGR.",
        "PNYY:1050 W HAXABJA",
        "NQQE:538 WBUA QNIVQ QE",
        "K:QNYR QE & FGBARTNGR FG",
        "VASB:1 IRUVPYR VAGB N CBYR NAQ ZNVYOBK, SVER NAQ RZF RAEBHGR.");

    qbGrfg("G41",
        "1055 QEVIR\a" +
        "221 ARNE EUBQRF 101\a\a\a" +
        "PBZVAT VAGB SNEZVATGBA SEBZ QBR EHA, CNFFVAT ARJ NOHAQNAG SNZVYL \a" +
        "PUHEPU, SNVYHER GB ZNVAGNVA N YNAR, SBEQ GNHEHF, FVYIRE 4 QBBE FRQNA, \a" +
        "JR2S8Z",

        "PNYY:1055 QEVIR",
        "NQQE:221 ARNE EUBQRF 101",
        "ZNQQE:221 & EUBQRF 101",
        "VASB:PBZVAT VAGB SNEZVATGBA SEBZ QBR EHA, CNFFVAT ARJ NOHAQNAG SNZVYL\aPUHEPU, SNVYHER GB ZNVAGNVA N YNAR, SBEQ GNHEHF, FVYIRE 4 QBBE FRQNA,\aJR2S8Z");

    qbGrfg("G42",
        "1050 W1\a222 R PBYHZOVN FG\aA URAEL FG & A YBAT NIR\a\aYRNIVAT GUR FPRAR\a\aBPPHERQ NG JNYZNEG LRFGREQFNL",
        "PNYY:1050 W1",
        "NQQE:222 R PBYHZOVN FG",
        "K:A URAEL FG & A YBAT NIR",
        "VASB:YRNIVAT GUR FPRAR\aBPPHERQ NG JNYZNEG LRFGREQFNL");

    qbGrfg("G43",
        "OHETYNEL NYNEZ\a1 OYNPX XAVTUG QE\aJ PBYHZOVN & J YVOREGL\a\aBSSVPR ERNE QBBE\a\a\aWBUA XENHFR 631-1009",
        "PNYY:OHETYNEL NYNEZ",
        "NQQE:1 OYNPX XAVTUG QE",
        "K:J PBYHZOVN & J YVOREGL",
        "VASB:BSSVPR ERNE QBBE\aWBUA XENHFR 631-1009");

    qbGrfg("G44",
        "OHETYNEL NYNEZ\a" +
        "140 JRFGZBHAG QE\a" +
        "J YVOREGL FG & J PBYHZOVN FG\a\a" +
        "pryy onpx hc\a" +
        "YBAT UNYY\a\a" +
        "WBUA 7566968\a" +
        "7604140\a" +
        "NAGBA 7608697\a" +
        "CNZ 7560548",

        "PNYY:OHETYNEL NYNEZ",
        "NQQE:140 JRFGZBHAG QE",
        "K:J YVOREGL FG & J PBYHZOVN FG",
        "VASB:pryy onpx hc\aYBAT UNYY\aWBUA 7566968\a7604140\aNAGBA 7608697\aCNZ 7560548");

    qbGrfg("G45",
        "QVFGHEONAPR\a796 ZNCYR INYYRL QE\aZNEXRG FG & XNEFPU OYIQ\a\a4-5 ZNYRF NCCRNE GUNG GURL ZVTUG FGNEG SVTUGVAT\aGNYY FYRRIRYRFF FUVEG",
        "PNYY:QVFGHEONAPR",
        "NQQE:796 ZNCYR INYYRL QE",
        "K:ZNEXRG FG & XNEFPU OYIQ",
        "VASB:4-5 ZNYRF NCCRNE GUNG GURL ZVTUG FGNEG SVTUGVAT\aGNYY FYRRIRYRFF FUVEG");

    qbGrfg("G46",
        "JNEENAG NEERFG\a310 FGR TRARIVRIR NIR\aA ZNVA FG & F PNEYRGBA FG\a133Z",
        "PNYY:JNEENAG NEERFG",
        "NQQE:310 FGR TRARIVRIR NIR",
        "K:A ZNVA FG & F PNEYRGBA FG",
        "VASB:133Z");

    qbGrfg("G47",
        "NFFNHYG\a200 J SVEFG FG\aF SENAXYVA FG & F N FG",
        "PNYY:NFFNHYG",
        "NQQE:200 J SVEFG FG",
        "K:F SENAXYVA FG & F N FG");

    qbGrfg("G48",
        "P & V QEVIVAT\a" +
        "CEBTERFF QE\a\a\a" +
        "04-06 4Q QBQTR PHZZVATF \a" +
        "QBVAT QBAHGF VA GUR FBPPRE SVRYQ\a" +
        "YVTUGF BS \a" +
        "GBBX UJL 67 FBHGU GBJNEQ SERQREVPXGBJA",

        "PNYY:P & V QEVIVAT",
        "NQQE:CEBTERFF QE",
        "VASB:04-06 4Q QBQTR PHZZVATF\aQBVAT QBAHGF VA GUR FBPPRE SVRYQ\aYVTUGF BS\aGBBX UJL 67 FBHGU GBJNEQ SERQREVPXGBJA");

    qbGrfg("G49",
        "OHETYNEL NYNEZ\a509 LBFRZVGR PG\aFURANAQBNU QE\a\aOBAVGN SERRZNA ERFVQRAPR\a\aONFRZRAG ZBGVBA\a\aHANOYR GB ERNPU XRLUBYQRE\a\aBCRE/",
        "PNYY:OHETYNEL NYNEZ",
        "NQQE:509 LBFRZVGR PG",
        "K:FURANAQBNU QE",
        "VASB:OBAVGN SERRZNA ERFVQRAPR\aONFRZRAG ZBGVBA\aHANOYR GB ERNPU XRLUBYQRE\aBCRE/");

    qbGrfg("G50",
        "GENSSVP UNMNEQ\aN/ZNCYR\a\a104U",
        "PNYY:GENSSVP UNMNEQ",
        "NQQE:N & ZNCYR",
        "VASB:104U");

    qbGrfg("G51",
        "NFFVFG NZOHYNAPR\a" +
        "206 R UVYYFVQR QE\a" +
        "ZRNQBJOEBBX QE & XRAJBBQ QE\a\a" +
        "SNGURE VF UNIVAT PURFG CNVA\a\a" +
        "UNF GNXRA 3 AVGEB JVGU AB ERYVRS\a\a" +
        "VFA'G JNAG GB TB GB UBFCVGNY\a\a" +
        "JBHYQ YVXR BSSVPRE GB NFFVFG VA PNFR GURER VF N CEBOYRZ",

        "PNYY:NFFVFG NZOHYNAPR",
        "NQQE:206 R UVYYFVQR QE",
        "K:ZRNQBJOEBBX QE & XRAJBBQ QE",
        "VASB:SNGURE VF UNIVAT PURFG CNVA\aUNF GNXRA 3 AVGEB JVGU AB ERYVRS\aVFA'G JNAG GB TB GB UBFCVGNY\aJBHYQ YVXR BSSVPRE GB NFFVFG VA PNFR GURER VF N CEBOYRZ");

    qbGrfg("G52",
        "OEBNQPNFG ZRFFNTR\a" +
        "310 FGR TRARIVRIR NIR\a" +
        "A ZNVA FG & F PNEYRGBA FG\a\a" +
        "GBC NAQ UBYQ JNAGRQ SBE GURSG\a\a" +
        "QRAAVF PBBX QBO:19661215 J Z \a" +
        "FHOWRPG QEVIVAT N OYNPX 1991 SBE ENATRE ZB YVP 5JT970\a" +
        "FHOWRPG VF JNAGRQ SBE GURSG BS N JNYYRG SEBZ QBYYNE TRARENY \a" +
        "VA GREER QH YNP BA 05/15/2015. HAXABJA QVERPGVBA BS GENIRY.\a\a" +
        "VS FHOWRPG VF YBPNGRQ FGBC NAQ UBYQ\a\a" +
        "NHGUBEVGL GREER QH YNP CQ 804-CEVPR\a\a\a" +
        "/F/EVPUNEQ, NFUYRL Z\a" +
        "FG SENAPBVF PB WBVAG PBZZ PRAGRE      20150516",

        "PNYY:OEBNQPNFG ZRFFNTR",
        "NQQE:310 FGR TRARIVRIR NIR",
        "K:A ZNVA FG & F PNEYRGBA FG",
        "VASB:GBC NAQ UBYQ JNAGRQ SBE GURSG\aQRAAVF PBBX QBO:19661215 J Z\aFHOWRPG QEVIVAT N OYNPX 1991 SBE ENATRE ZB YVP 5JT970\aFHOWRPG VF JNAGRQ SBE GURSG BS N JNYYRG SEBZ QBYYNE TRARENY\aVA GREER QH YNP BA 05/15/2015. HAXABJA QVERPGVBA BS GENIRY.\aVS FHOWRPG VF YBPNGRQ FGBC NAQ UBYQ\aNHGUBEVGL GREER QH YNP CQ 804-CEVPR\a/F/EVPUNEQ, NFUYRL Z\aFG SENAPBVF PB WBVAG PBZZ PRAGRE      20150516");

    qbGrfg("G53",
        "P & V QEVIVAT\a" +
        "715 J YVOREGL FG\a" +
        "WBFVR YA & A NYRKNAQRE NIR\a\a" +
        "TERRA NAQ ERQ FGERRG OVXRF\a\a" +
        "QBVAT JURRYVRF NAQ FCRRQVAT\a\a" +
        "VA GUR NERN BS ZPPBEZVPX NAQ GURA GB CBGBFV\a\a" +
        "PNYYRE QBRFA'G JNAG PBAGNPGRQ\a\a" +
        "YNFG FRRA TBVAT GBJNEQF CBGBFV BA YVOREGL",

        "PNYY:P & V QEVIVAT",
        "NQQE:715 J YVOREGL FG",
        "K:WBFVR YA & A NYRKNAQRE NIR",
        "VASB:TERRA NAQ ERQ FGERRG OVXRF\aQBVAT JURRYVRF NAQ FCRRQVAT\aVA GUR NERN BS ZPPBEZVPX NAQ GURA GB CBGBFV\aPNYYRE QBRFA'G JNAG PBAGNPGRQ\aYNFG FRRA TBVAT GBJNEQF CBGBFV BA YVOREGL");

    qbGrfg("G54",
        "OHETYNEL NYNEZ\a" +
        "1 OYNPX XAVTUG QE\a" +
        "J PBYHZOVN & J YVOREGL\a\a" +
        "OHET GRYREBBZ ZBGVBA\a\a" +
        "XRLUBYQREF: WBUA 631-1009   760-9423\a\a" +
        "ANGUNA 417-230-5802\a\a" +
        "WNZVR 756-8123    701-5322\a\a" +
        "EBL 380-2130",

        "PNYY:OHETYNEL NYNEZ",
        "NQQE:1 OYNPX XAVTUG QE",
        "K:J PBYHZOVN & J YVOREGL",
        "VASB:OHET GRYREBBZ ZBGVBA\aXRLUBYQREF: WBUA 631-1009   760-9423\aANGUNA 417-230-5802\aWNZVR 756-8123    701-5322\aEBL 380-2130");

    qbGrfg("G1",
        "QEHT BSSRAFR\a" +
        "5 NIN PG\a" +
        "F URAEL FG\a" +
        "104U, 122Z\a" +
        "FBZRBAR VF FZBXVAT BHG BS N PYRNE TYNFF CVCR NG 7 NIN\a\a" +
        "BA GUR ONPX CBEPU\a\a" +
        "GUERR OBLF \a\a" +
        "ERQ FUVEG, TENL FJRNGFUVEG, UNG\a\a" +
        "JNAGF PBAGNPGRQ OL NA BSSVPRE, VF JVYYVAT GB FVTA N PBZCYNVAG\a" +
        "AB ARRQ SBE SHEGURE CRE 104\a" +
        "hasbhaqrq\a" +
        "Qvfcbfvgvba: AEA",

        "PNYY:QEHT BSSRAFR",
        "NQQE:5 NIN PG",
        "K:F URAEL FG",
        "VASB:104U, 122Z\aFBZRBAR VF FZBXVAT BHG BS N PYRNE TYNFF CVCR NG 7 NIN\aBA GUR ONPX CBEPU\aGUERR OBLF\aERQ FUVEG, TENL FJRNGFUVEG, UNG\aJNAGF PBAGNPGRQ OL NA BSSVPRE, VF JVYYVAT GB FVTA N PBZCYNVAG\aAB ARRQ SBE SHEGURE CRE 104\ahasbhaqrq\aQvfcbfvgvba: AEA");

    qbGrfg("G56",
        "1058\aXNEFPU/ZNCYR INYYRL\a\a\aAB EBNQ OYBPX\a\aRNFG OBHAQ",
        "PNYY:1058",
        "NQQE:XNEFPU & ZNCYR INYYRL",
        "VASB:AB EBNQ OYBPX\aRNFG OBHAQ");

    qbGrfg("G57",
        "FGRNYVAT\a707 JNYGBA QE\aZNCYR FG & XNEFPU OYIQ\a\aOYNPX UBBQVR VAFVQR VF ERQ F",
        "PNYY:FGRNYVAT",
        "NQQE:707 JNYGBA QE",
        "K:ZNCYR FG & XNEFPU OYIQ",
        "VASB:OYNPX UBBQVR VAFVQR VF ERQ F");

    qbGrfg("G58",
        "1050 W1\a707 JNYGBA QE\aZNCYR FG & XNEFPU OYIQ\a\aZNEXRG FVQR, 3EQ EBJ BIRE, TENL TZP GREENVA IF OYHR TZP FVREEN \aGEHPX",
        "PNYY:1050 W1",
        "NQQE:707 JNYGBA QE",
        "K:ZNCYR FG & XNEFPU OYIQ",
        "VASB:ZNEXRG FVQR, 3EQ EBJ BIRE, TENL TZP GREENVA IF OYHR TZP FVREEN\aGEHPX");

    qbGrfg("G1",
        "JNEENAG NEERFG\a" +
        "20 FG SENAPBVF NIR\a" +
        "XNEFPU OYIQ & JNONFU NIR\a" +
        "117P\a" +
        "YBBXVAT SBE GUVF IRUVPYR, JNF NG RNTYR FGBC ER NAVZNY PNYY. \a\a" +
        "* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * \a" +
        " JNAGRQ CREFBA  *** NPGVIR PNFR ***\a" +
        "                         **** ZHYRF BAYL ****\a" +
        "  *CREFBA VASB:   ANZR:ABOYR,PNFFVR ZNEVR\a" +
        "   FRK: S ENPR:J QBO: 06-27-1988 NTR:  26 URVTUG: 501 JRVTUG: 110\a" +
        "  *PHEE FBP:  595062272\a" +
        "   UNVE: KKK RLR: OYH\a" +
        "  *PHEE BYA:  Z050242016            BYL: 2017      BYF: ZB\a\a" +
        "  *BSSRAFR VASBEZNGVBA: \a" +
        "   PBQR: 5015  SNVYHER GB NCCRNE  SNVYHER GB NCCRNE\a" +
        "    PNFR #: 15-007452\a" +
        "      JNEENAG #: 007452  JNEENAG QNGR: 04-16-2015\a" +
        "    JVYY RKGENQVGR NQWBVAVAT PBHAGVRF    FHEEBHAQVAT FG SENAPBVF \a" +
        "PBHAGL\a" +
        "    WHEVFQVPGVBA:   YBPNY / PVGL BEQVANAPR\a" +
        "    PBHEG BEV: ZB094031W  PLPYR #:   BEVT BSS: 5499  GENSSVP BSSRAFR\a" +
        "    OBAQ: $514-00     PNFU BAYL\a\a" +
        "  *ZVFPRYYNARBHF VASB: FHOWRPG PUNETRQ JVGU SNVYHER GB NCCRNE GB \a" +
        "NAFJRE\a" +
        "                        BEVTVANY PUNETR BS SNVYHER GB ERTVFGRE IRUVPYR JVGUQBE\a" +
        "  *PHEE YVL: 2015  YVF: ZB  YVG: CP  YVP: JW2U7Z\a" +
        "  *BJARE VASB* ANZR: ABOYR PNFFVR & ENGPYVSS QHFGNA\a" +
        "   NQQE: 216  QNXBGN PBHEG  SNEZVATGBA  ZB 63640\a" +
        "  *ILE: 2002  IZN: BYQF  IZB: NYB  IFG: 4Q  \a" +
        "  *IGC: C  IVA: 1T3AY52R62P136945  \a" +
        "  *PHEERAG XABJA NQQERFFRF UBZR/JBEX/FPUBBY/SERDHRAGRQ/ZNVYVAT:\a" +
        "   UBZR: 216 QNXBGN PG  SNEZVATGBA, ZB 63640\a" +
        "     PBHAGL: 094 FG. SENAPBVF\a" +
        "   UBZR: 100 ZPPYNL IVYYNTR QE  FNVAG CRGREF, ZB 63376\a" +
        "   UBZR: 418 F PNQVYYNP QE  FG PUNEYRF, ZB 63301\a" +
        " OEBNQPNFG GREZVANYF: \a" +
        "  *VZZRQVNGRYL PBASVEZ JVGU BEV:\a" +
        "    PNFR BEV VASBEZNGVBA: ZB0940600  SNEZVATGBA CQ                      \a" +
        "    RAGREVAT BEV VASBEZNGVBA: ZB0940600  SNEZVATGBA CQ                      \a" +
        "    FUC: 150417-204519\a" +
        "    BPN: 15-007452\a\a" +
        "**** PBASVQRAGVNY QNGN ERFGEVPGRQ GB PEVZVANY WHFGVPR NTRAPVRF ****\a" +
        "*** RAQ BS ERPBEQ ***\a" +
        " \a\a\a" +
        "ZEV: 22125624 VA: USFD1 29681 NG 16ZNL2015 15:32:30\a" +
        "BHG: PUW3 51 NG 16ZNL2015 15:32:31 \a" +
        " \a" +
        "SEBZ-APVP       QNGR: 05/16/2015 GVZR: 15:32:31 QRFG GREZ: PUW3      \a" +
        "DIE.YVP/JW2U7Z.YVL/2015.\a" +
        " \a\a" +
        "1Y0101BI,ZE22125620\a\a" +
        "Z00940600\a" +
        "AB ERPBEQ YVP/JW2U7Z\a\a" +
        "ZEV: 22125623 VA: APVP 33670 NG 16ZNL2015 15:32:30\a" +
        "BHG: PUW3 50 NG 16ZNL2015 15:32:31\a" +
        "   \a" +
        " \a\a" +
        "SEBZ-ERIRAHR     QNGR: 05/16/2015  GVZR: 15:32:30 QRFG GREZ: JP00SBKV\a" +
        "QBE.TE40JW2U7Z15\a" +
        "*E04 - GVGYR & ERTVFG\a" +
        "****  GUVF ERPBEQ ERFGEVPGRQ HAQRE QEVIREF CEVINPL CEBGRPGVBA NPG  ****\a" +
        " LRNE:02 ZNXR:BYQF  FGLYR:SBQBE XVAQ BS IRU:C IVA:1T3AY52R62P136945\a" +
        "  BJARE ANZR:ABOYR PNFFVR & ENGPYVSS QHFGNA          PBHAGL:FG. SENAPBVF\a" +
        "  NQQERFF:216 QNXBGN PBHEG     SNEZVATGBA      ZB 63640\a" +
        "  PLY:   FREVRF:N/T NKYRF:  SHRY:T UBEFR CBJRE:24\a" +
        " YVP:JW2U7Z RKCVENGVBA:ABI 15 YVG:CP GNO AB:000000000 VFFHR:101514\a" +
        "  GVGYR:GJX93733 GLCR:BEVTVANY   QNGR:101614 BQBZ:0000000 ARJ/HFRQ:HFRQ \a" +
        "BHGFG\a" +
        " \a" +
        "ZEV: 22125622 VA: ZHYRF 42515 NG 16ZNL2015 15:32:30\a" +
        "BHG: PUW3 49 NG 16ZNL2015 15:32:3",

        "PNYY:JNEENAG NEERFG",
        "NQQE:20 FG SENAPBVF NIR",
        "K:XNEFPU OYIQ & JNONFU NIR",
        "VASB:117P\aYBBXVAT SBE GUVF IRUVPYR, JNF NG RNTYR FGBC ER NAVZNY PNYY.\a* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *\aJNAGRQ CREFBA  *** NPGVIR PNFR ***\a**** ZHYRF BAYL ****\a*CREFBA VASB:   ANZR:ABOYR,PNFFVR ZNEVR\aFRK: S ENPR:J QBO: 06-27-1988 NTR:  26 URVTUG: 501 JRVTUG: 110\a*PHEE FBP:  595062272\aUNVE: KKK RLR: OYH\a*PHEE BYA:  Z050242016            BYL: 2017      BYF: ZB\a*BSSRAFR VASBEZNGVBA:\aPBQR: 5015  SNVYHER GB NCCRNE  SNVYHER GB NCCRNE\aPNFR #: 15-007452\aJNEENAG #: 007452  JNEENAG QNGR: 04-16-2015\aJVYY RKGENQVGR NQWBVAVAT PBHAGVRF    FHEEBHAQVAT FG SENAPBVF\aPBHAGL\aWHEVFQVPGVBA:   YBPNY / PVGL BEQVANAPR\aPBHEG BEV: ZB094031W  PLPYR #:   BEVT BSS: 5499  GENSSVP BSSRAFR\aOBAQ: $514-00     PNFU BAYL\a*ZVFPRYYNARBHF VASB: FHOWRPG PUNETRQ JVGU SNVYHER GB NCCRNE GB\aNAFJRE\aBEVTVANY PUNETR BS SNVYHER GB ERTVFGRE IRUVPYR JVGUQBE\a*PHEE YVL: 2015  YVF: ZB  YVG: CP  YVP: JW2U7Z\a*BJARE VASB* ANZR: ABOYR PNFFVR & ENGPYVSS QHFGNA\aNQQE: 216  QNXBGN PBHEG  SNEZVATGBA  ZB 63640\a*ILE: 2002  IZN: BYQF  IZB: NYB  IFG: 4Q\a*IGC: C  IVA: 1T3AY52R62P136945\a*PHEERAG XABJA NQQERFFRF UBZR/JBEX/FPUBBY/SERDHRAGRQ/ZNVYVAT:\aUBZR: 216 QNXBGN PG  SNEZVATGBA, ZB 63640\aPBHAGL: 094 FG. SENAPBVF\aUBZR: 100 ZPPYNL IVYYNTR QE  FNVAG CRGREF, ZB 63376\aUBZR: 418 F PNQVYYNP QE  FG PUNEYRF, ZB 63301\aOEBNQPNFG GREZVANYF:\a*VZZRQVNGRYL PBASVEZ JVGU BEV:\aPNFR BEV VASBEZNGVBA: ZB0940600  SNEZVATGBA CQ\aRAGREVAT BEV VASBEZNGVBA: ZB0940600  SNEZVATGBA CQ\aFUC: 150417-204519\aBPN: 15-007452\a**** PBASVQRAGVNY QNGN ERFGEVPGRQ GB PEVZVANY WHFGVPR NTRAPVRF ****\a*** RAQ BS ERPBEQ ***\aZEV: 22125624 VA: USFD1 29681 NG 16ZNL2015 15:32:30\aBHG: PUW3 51 NG 16ZNL2015 15:32:31\aSEBZ-APVP       QNGR: 05/16/2015 GVZR: 15:32:31 QRFG GREZ: PUW3\aDIE.YVP/JW2U7Z.YVL/2015.\a1Y0101BI,ZE22125620\aZ00940600\aAB ERPBEQ YVP/JW2U7Z\aZEV: 22125623 VA: APVP 33670 NG 16ZNL2015 15:32:30\aBHG: PUW3 50 NG 16ZNL2015 15:32:31\aSEBZ-ERIRAHR     QNGR: 05/16/2015  GVZR: 15:32:30 QRFG GREZ: JP00SBKV\aQBE.TE40JW2U7Z15\a*E04 - GVGYR & ERTVFG\a****  GUVF ERPBEQ ERFGEVPGRQ HAQRE QEVIREF CEVINPL CEBGRPGVBA NPG  ****\aLRNE:02 ZNXR:BYQF  FGLYR:SBQBE XVAQ BS IRU:C IVA:1T3AY52R62P136945\aBJARE ANZR:ABOYR PNFFVR & ENGPYVSS QHFGNA          PBHAGL:FG. SENAPBVF\aNQQERFF:216 QNXBGN PBHEG     SNEZVATGBA      ZB 63640\aPLY:   FREVRF:N/T NKYRF:  SHRY:T UBEFR CBJRE:24\aYVP:JW2U7Z RKCVENGVBA:ABI 15 YVG:CP GNO AB:000000000 VFFHR:101514\aGVGYR:GJX93733 GLCR:BEVTVANY   QNGR:101614 BQBZ:0000000 ARJ/HFRQ:HFRQ\aBHGFG\aZEV: 22125622 VA: ZHYRF 42515 NG 16ZNL2015 15:32:30\aBHG: PUW3 49 NG 16ZNL2015 15:32:3");

    qbGrfg("G60",
        "P & V QEVIVAT\a" +
        "32SEBZ FGR TRA PBHAGL YVAR. \a\a\a" +
        "32 SEBZ GUR FGR TRA PBHAGL YVAR JUVGR PURIL CVPXHC, VY CYNGRF, SNVYHER \a" +
        "GB ZNVAGNVA N YNAR.",

        "PNYY:P & V QEVIVAT",
        "NQQE:32SEBZ FGR TRA PBHAGL YVAR",
        "VASB:32 SEBZ GUR FGR TRA PBHAGL YVAR JUVGR PURIL CVPXHC, VY CYNGRF, SNVYHER\aGB ZNVAGNVA N YNAR.");

    qbGrfg("G61",
        "OHETYNEL NYNEZ\a2000 CEBTERFF QE\aQBHORG EQ & BIRENYY EQ\a\aQBBE 29\a\aTRBETR, 747.5323\aEBPXL 330.7343\aGREEL 631.2464\aQNAAL 915.6137",
        "PNYY:OHETYNEL NYNEZ",
        "NQQE:2000 CEBTERFF QE",
        "K:QBHORG EQ & BIRENYY EQ",
        "VASB:QBBE 29\aTRBETR, 747.5323\aEBPXL 330.7343\aGREEL 631.2464\aQNAAL 915.6137");

    qbGrfg("G62",
        "1058\a" +
        "ZNCYR/NYRKNAQRE\a\a\a" +
        "EC VF N CNFFREOL   FNJ N ZNYR FHOWRPG'F JUBFR PNE VF OEBXRA QBJA, \a" +
        "ZNCYR& NYRKNAQRE. EC VF PBAPREARQ GUNG FBZRBAR JVYY EHA VAGB GUR \a" +
        "ONPX BS GUR PNE NAQ EHA GUR ZNYR FHOWRPG BIRE. AB IRUVPYR \a" +
        "QRFPEVCGVBA, GUVAXF VG ZNL OR FVYIRE, VF HAFHER. ZNLOR UR ARRQF PBARF \a" +
        "BE FBZRGUVAT GB FUBJ UR VF GURER.",

        "PNYY:1058",
        "NQQE:ZNCYR & NYRKNAQRE",
        "VASB:EC VF N CNFFREOL   FNJ N ZNYR FHOWRPG'F JUBFR PNE VF OEBXRA QBJA,\aZNCYR& NYRKNAQRE. EC VF PBAPREARQ GUNG FBZRBAR JVYY EHA VAGB GUR\aONPX BS GUR PNE NAQ EHA GUR ZNYR FHOWRPG BIRE. AB IRUVPYR\aQRFPEVCGVBA, GUVAXF VG ZNL OR FVYIRE, VF HAFHER. ZNLOR UR ARRQF PBARF\aBE FBZRGUVAT GB FUBJ UR VF GURER.");

    qbGrfg("G63",
        "PURPX GUR JRYY ORVAT\a" +
        "1050 IREABA NIR\a" +
        "NYQRETNGR FG & NCNEGZRAG PBZCYRK\a\a" +
        "WBR/WBFRCU CREXVAF, 108'F AVRPR'F UHFONAQ, UR QVQA'G FUBJ HC SBE JBEX. \a" +
        "PURPX UVF JRYY ORVAT, PBAGNPG 108 JVGU ERFHYGF CYRNFR.",

        "PNYY:PURPX GUR JRYY ORVAT",
        "NQQE:1050 IREABA NIR",
        "K:NYQRETNGR FG & NCNEGZRAG PBZCYRK",
        "VASB:WBR/WBFRCU CREXVAF, 108'F AVRPR'F UHFONAQ, UR QVQA'G FUBJ HC SBE JBEX.\aPURPX UVF JRYY ORVAT, PBAGNPG 108 JVGU ERFHYGF CYRNFR.");

    qbGrfg("G64",
        "GENSSVP UNMNEQ\a" +
        "780 ZNCYR INYYRL QE\a" +
        "ZNEXRG FG & XNEFPU OYIQ\a\a" +
        "ZNYR FHOWRPG QNEX UNVE, 5'10 FYVZ OHVYQ ERQ WNPXRG CNAUNAQYVAT VA GUR \a" +
        "EBNQJNL PNHFVAT IRUVPYRF GB QRGBHE NEBHAQ UVZ.",

        "PNYY:GENSSVP UNMNEQ",
        "NQQE:780 ZNCYR INYYRL QE",
        "K:ZNEXRG FG & XNEFPU OYIQ",
        "VASB:ZNYR FHOWRPG QNEX UNVE, 5'10 FYVZ OHVYQ ERQ WNPXRG CNAUNAQYVAT VA GUR\aEBNQJNL PNHFVAT IRUVPYRF GB QRGBHE NEBHAQ UVZ.");

    qbGrfg("G65",
        "GENSSVP UNMNEQ\aJ CVAR FG\a\a\aONPX ORUVAQ NHGBMBAR ARNE GUR FRAVBE NCNEGZRAGF, ZNEBBA FHI VF \aCNEXRQ BA J CVAR OYBPXVAT EBNQJNL.",
        "PNYY:GENSSVP UNMNEQ",
        "NQQE:J CVAR FG",
        "VASB:ONPX ORUVAQ NHGBMBAR ARNE GUR FRAVBE NCNEGZRAGF, ZNEBBA FHI VF\aCNEXRQ BA J CVAR OYBPXVAT EBNQJNL.");

    qbGrfg("G66",
        "FGRNYVAT\a222 R PBYHZOVN FG\aA URAEL FG & A YBAT NIR\a\a10-12  SEBZ 508 PRAGRE FGERRG ARRQF GB QEBC BSS YVFG BS VGRZF SBE 129",
        "PNYY:FGRNYVAT",
        "NQQE:222 R PBYHZOVN FG",
        "K:A URAEL FG & A YBAT NIR",
        "VASB:10-12  SEBZ 508 PRAGRE FGERRG ARRQF GB QEBC BSS YVFG BS VGRZF SBE 129");

    qbGrfg("G67",
        "OHETYNEL NYNEZ\a" +
        "806 ORAG PERRX QE\a" +
        "UHAG EQ & TERRA OEVNE QE\a\a" +
        "nppvqragnyyl frg bss gur nynez--pnyyrq naq tnir cebcre pbqr cre prageny--fnyg jngre.",

        "PNYY:OHETYNEL NYNEZ",
        "NQQE:806 ORAG PERRX QE",
        "K:UHAG EQ & TERRA OEVNE QE",
        "VASB:nppvqragnyyl frg bss gur nynez--pnyyrq naq tnir cebcre pbqr cre prageny--fnyg jngre.");

    qbGrfg("G68",
        "1050 W1\aXNEFPU/ZVQQYR\a\a119J\aZBCRQ FHOWRPG YNLVAT BA GUR TEBHAQ",
        "PNYY:1050 W1",
        "NQQE:XNEFPU & ZVQQYR",
        "VASB:119J\aZBCRQ FHOWRPG YNLVAT BA GUR TEBHAQ");

    qbGrfg("G69",
        "SVTUG\a200 J SVEFG FG\aF SENAXYVA FG & F N FG",
        "PNYY:SVTUG",
        "NQQE:200 J SVEFG FG",
        "K:F SENAXYVA FG & F N FG");

    qbGrfg("G70",
        "FHFCVPVBHF NPGVIVGL\aYVOREGL FG\a\a\agjb zra naf n jbzna\aJNYXVAT VA GUR ZHQ NG GUR ARJ YVOENEL\aJUVGR FUVEG NAQ CNAGF",
        "PNYY:FHFCVPVBHF NPGVIVGL",
        "NQQE:YVOREGL FG",
        "VASB:gjb zra naf n jbzna\aJNYXVAT VA GUR ZHQ NG GUR ARJ YVOENEL\aJUVGR FUVEG NAQ CNAGF");

    qbGrfg("G71",
        "NFFVFG NZOHYNAPR\a" +
        "1015 FGR TRARIVRIR NIR\a" +
        "IRGRENAF QE & IVREFR QE\a\a" +
        "RZF ABG NAFJREVAT FRPHEVGL PURPXF\a\a" +
        "GURER SBE NA RYQREYL SRZNYR JUB SRYY",

        "PNYY:NFFVFG NZOHYNAPR",
        "NQQE:1015 FGR TRARIVRIR NIR",
        "K:IRGRENAF QE & IVREFR QE",
        "VASB:RZF ABG NAFJREVAT FRPHEVGL PURPXF\aGURER SBE NA RYQREYL SRZNYR JUB SRYY");

    qbGrfg("G72",
        "1055 QEVIR\aUJL 32 JRFGOBHAQ \a\a\aSEBZ ZVQJNL ONE NAQ TEVYY\aFRZV FVYIRE GENVYRE CNEGVNYYL PBIRERQ JVGU GNEC",
        "PNYY:1055 QEVIR",
        "NQQE:UJL 32 JRFGOBHAQ",
        "ZNQQE:UJL 32",
        "VASB:SEBZ ZVQJNL ONE NAQ TEVYY\aFRZV FVYIRE GENVYRE CNEGVNYYL PBIRERQ JVGU GNEC");

    qbGrfg("G73",
        "FHFCVPVBHF NPGVIVGL\a" +
        "915 A JNFUVATGBA FG\a" +
        "XNEFPU OYIQ & CVAR FG\a\a" +
        "CNEXVAT YBG \a" +
        "CRBCYR UNATVAT BHG VA GUR CNEXVAT YBG\a" +
        "ZNYR VA N FZNYY FVYIRE FHI FYHZCRQ BIRE FGRREVAT JURRY\a" +
        "FBZRBAR NFXRQ UVZ VS ARRQRQ URYC\a" +
        "FHOWRPG VA QNEX UBBQVR UNATVAT NEBHAQ VA SEBAG BS GUR QBBE",

        "PNYY:FHFCVPVBHF NPGVIVGL",
        "NQQE:915 A JNFUVATGBA FG",
        "K:XNEFPU OYIQ & CVAR FG",
        "VASB:CNEXVAT YBG\aCRBCYR UNATVAT BHG VA GUR CNEXVAT YBG\aZNYR VA N FZNYY FVYIRE FHI FYHZCRQ BIRE FGRREVAT JURRY\aFBZRBAR NFXRQ UVZ VS ARRQRQ URYC\aFHOWRPG VA QNEX UBBQVR UNATVAT NEBHAQ VA SEBAG BS GUR QBBE");

    qbGrfg("G74",
        "OHETYNEL NYNEZ\a" +
        "1101 J YVOREGL FG\a" +
        "J YVOREGL FG & CNEXYNAQ QE\a\a" +
        "CUNEZNPL VI ZBGVBA\a\a" +
        "UBYQ HC NYNEZ\a\a\a\a\a" +
        "YBPNGVBA ABGRF:  \a" +
        "N.  Cnexynaq Urnygu Pragre qrirybcrq n fvyrag nynez cbyvpl gb raunapr frphevgl.\a" +
        "ENQVB QVFCNGPU NF 10-30 AHZORE 13 GB GJB CBYVPR HAVGF BAR ORVAT GUR \a" +
        "FHCREIVFBE, VS NINVYNOYR.\a\a" +
        "N fvyrag nynez jvyy or cynprq va gur sbyybjvat nernf bs gur snpvyvgl:\a\a" +
        "1.  Uhzna Erfbheprf Qverpgbe'f Bssvpr\a" +
        "2.  Uhzna Erfbheprf Erprcgvbavfg'f Qrfx\a" +
        "3.  Rzretrapl Qrcnegzrag Qrfx\a" +
        "4.  Phfgbzre Freivpr Qrfx\a" +
        "5.  Nqzvggvat Ebbz #1\a" +
        "6.  Zrqvpngvba Ebbz va BO\a" +
        "7.  Ahefrel va BO\a" +
        "8.  Pnfuvre'f Qrfx\a" +
        "9.  Ahefvat Qrfx VPH\a" +
        "   10.  Enqvbybtl (erzbgr jveryrff)\a" +
        "   11.  Cuneznpl\a" +
        "   12.  Vagrafvir Pner\a\a" +
        "O.  Gur fvyrag nynez jvyy or hgvyvmrq va gur rirag gung n cngvrag, ivfvgbe, rzcyblrr, be zrzore \a" +
        "bs zrqvpny fgnss vf cynprq vagb gur cbfvgvba bs orvat fhowrpgrq gb culfvpny qnatre, jvgu gur \a" +
        "rkgerzr cbgragvny bs npghny hfr bs ivbyrapr ntnvafg gurve crefba naq gur fvghngvba vf frevbhf \a" +
        "rabhtu va angher gb erdhver rkgreany nffvfgnapr sebz gur cbyvpr, ohg abezny gryrcubar \a" +
        "pbagnpg vf vzcenpgvpny be vzcehqrag.\a\a" +
        "P.  Pbzzhavpngvbaf Bssvpref\a\a" +
        "Hcba erprvivat gur rzretrapl abgvsvpngvba guebhtu gur nynez flfgrz, gur \a" +
        "pbzzhavpngvbaf bssvpre jvyy vzzrqvngryl qvfcngpu na bssvpre gb gur Urnygu Pragre ol hfvat \a" +
        "gur 10-pbqr, 10-30 ng #13.  Gur pbzzhavpngvbaf bssvpre jvyy gura abgvsl gur Urnygu Pragre'f \a" +
        "bcrengbe (756-6451)gung na nynez unf orra chfurq naq gur ybpngvba bs gur nynez.  Vs gur \a" +
        "bcrengbe vf hanoyr gb nafjre gur pnyy cebzcgyl, gur pbzzhavpngvbaf bssvpre jvyy abgvsl gur \a" +
        "Zrqvpny Fhetvpny sybbe (756-8200) jvgu gur fnzr vasbezngvba.\a\a" +
        "Q.  Bssvpref\a\a" +
        "Vg vf gur erfcbafvovyvgl bs gur Snpvyvgvrf Znantrzrag Qrcnegzrag, be gur Frphevgl \a" +
        "Bssvpre gb erfcbaq naq zrrg gur neevivat cbyvpr bssvpre ng gur fbhgurnfg sver rkvg, fgnvejryy \a" +
        "O,vasbez gur bssvpre nf gb gur fvghngvba ng unaq, naq gb nppbzcnal gur bssvpre gb gur \a" +
        "ybpngvba bs gur nynez.  Gur bssvpre jvyy gura unaqyr gur fvghngvba ubjrire ur qrrzf \a" +
        "arprffnel, gbc cevbevgl orvat, fnsrgl sbe rirelbar vaibyirq.\a\a" +
        "S.  Grfgvat bs gur Fvyrag Nynez\a\a" +
        "Frphevgl/Snpvyvgvrf Znantrzrag bs gur Cnexynaq Urnygu Pragre jvyy pbagnpg bhe \a" +
        "pbzzhavpngvbaf qvivfvba gb grfg gurve fvyrag nynezf ba na naahny onfvf.\a\a" +
        "Gur grfg jvyy or pneevrq bhg ol n zrzore sebz rnpu nynez fvgr pbagnpgvat qvfcngpu \a" +
        "ol gryrcubar, naq erdhrfgvat n grfg.  N zrzore sebz rnpu nynez fvgr jvyy npgvingr gur fvyrag \a" +
        "nynez, naq gur ybpngvba jvyy nccrne ba bhe nynez flfgrz ng gur cbyvpr qrcnegzrag.  Gur \a" +
        "qvfcngpure jvyy pbasvez gur ybpngvba bs gur nynez.  Vs n ceboyrz rkvfgf, gur qvfcngpure jvyy \a" +
        "vasbez gur zrzore sebz gur nynez fvgr fb gur vasbezngvba pna or sbejneqrq gb Eboregf \a" +
        "Nynez Flfgrzf sbe ercnve.\a\a\a" +
        "R.  Frr nggnpurq Cbyvpl sebz Cnexynaq Urnygu Pragre.\a" +
        "Frr nggnpurq sybbe cyna bs ohvyqvat sbe ybpngvbaf bs nynezf, naq \a" +
        "gur ragenapr sbe gur cbyvpr (fbhgurnfg sver rkvg, fgnvejryy O)\a\a\a\a" +
        "----------------------------------------",

        "PNYY:OHETYNEL NYNEZ",
        "NQQE:1101 J YVOREGL FG",
        "K:J YVOREGL FG & CNEXYNAQ QE",
        "VASB:CUNEZNPL VI ZBGVBA\aUBYQ HC NYNEZ\aYBPNGVBA ABGRF:\aN.  Cnexynaq Urnygu Pragre qrirybcrq n fvyrag nynez cbyvpl gb raunapr frphevgl.\aENQVB QVFCNGPU NF 10-30 AHZORE 13 GB GJB CBYVPR HAVGF BAR ORVAT GUR\aFHCREIVFBE, VS NINVYNOYR.\aN fvyrag nynez jvyy or cynprq va gur sbyybjvat nernf bs gur snpvyvgl:\a1.  Uhzna Erfbheprf Qverpgbe'f Bssvpr\a2.  Uhzna Erfbheprf Erprcgvbavfg'f Qrfx\a3.  Rzretrapl Qrcnegzrag Qrfx\a4.  Phfgbzre Freivpr Qrfx\a5.  Nqzvggvat Ebbz #1\a6.  Zrqvpngvba Ebbz va BO\a7.  Ahefrel va BO\a8.  Pnfuvre'f Qrfx\a9.  Ahefvat Qrfx VPH\a10.  Enqvbybtl (erzbgr jveryrff)\a11.  Cuneznpl\a12.  Vagrafvir Pner\aO.  Gur fvyrag nynez jvyy or hgvyvmrq va gur rirag gung n cngvrag, ivfvgbe, rzcyblrr, be zrzore\abs zrqvpny fgnss vf cynprq vagb gur cbfvgvba bs orvat fhowrpgrq gb culfvpny qnatre, jvgu gur\arkgerzr cbgragvny bs npghny hfr bs ivbyrapr ntnvafg gurve crefba naq gur fvghngvba vf frevbhf\arabhtu va angher gb erdhver rkgreany nffvfgnapr sebz gur cbyvpr, ohg abezny gryrcubar\apbagnpg vf vzcenpgvpny be vzcehqrag.\aP.  Pbzzhavpngvbaf Bssvpref\aHcba erprvivat gur rzretrapl abgvsvpngvba guebhtu gur nynez flfgrz, gur\apbzzhavpngvbaf bssvpre jvyy vzzrqvngryl qvfcngpu na bssvpre gb gur Urnygu Pragre ol hfvat\agur 10-pbqr, 10-30 ng #13.  Gur pbzzhavpngvbaf bssvpre jvyy gura abgvsl gur Urnygu Pragre'f\abcrengbe (756-6451)gung na nynez unf orra chfurq naq gur ybpngvba bs gur nynez.  Vs gur\abcrengbe vf hanoyr gb nafjre gur pnyy cebzcgyl, gur pbzzhavpngvbaf bssvpre jvyy abgvsl gur\aZrqvpny Fhetvpny sybbe (756-8200) jvgu gur fnzr vasbezngvba.\aQ.  Bssvpref\aVg vf gur erfcbafvovyvgl bs gur Snpvyvgvrf Znantrzrag Qrcnegzrag, be gur Frphevgl\aBssvpre gb erfcbaq naq zrrg gur neevivat cbyvpr bssvpre ng gur fbhgurnfg sver rkvg, fgnvejryy\aO,vasbez gur bssvpre nf gb gur fvghngvba ng unaq, naq gb nppbzcnal gur bssvpre gb gur\aybpngvba bs gur nynez.  Gur bssvpre jvyy gura unaqyr gur fvghngvba ubjrire ur qrrzf\aarprffnel, gbc cevbevgl orvat, fnsrgl sbe rirelbar vaibyirq.\aS.  Grfgvat bs gur Fvyrag Nynez\aFrphevgl/Snpvyvgvrf Znantrzrag bs gur Cnexynaq Urnygu Pragre jvyy pbagnpg bhe\apbzzhavpngvbaf qvivfvba gb grfg gurve fvyrag nynezf ba na naahny onfvf.\aGur grfg jvyy or pneevrq bhg ol n zrzore sebz rnpu nynez fvgr pbagnpgvat qvfcngpu\aol gryrcubar, naq erdhrfgvat n grfg.  N zrzore sebz rnpu nynez fvgr jvyy npgvingr gur fvyrag\anynez, naq gur ybpngvba jvyy nccrne ba bhe nynez flfgrz ng gur cbyvpr qrcnegzrag.  Gur\aqvfcngpure jvyy pbasvez gur ybpngvba bs gur nynez.  Vs n ceboyrz rkvfgf, gur qvfcngpure jvyy\avasbez gur zrzore sebz gur nynez fvgr fb gur vasbezngvba pna or sbejneqrq gb Eboregf\aNynez Flfgrzf sbe ercnve.\aR.  Frr nggnpurq Cbyvpl sebz Cnexynaq Urnygu Pragre.\aFrr nggnpurq sybbe cyna bs ohvyqvat sbe ybpngvbaf bs nynezf, naq\agur ragenapr sbe gur cbyvpr (fbhgurnfg sver rkvg, fgnvejryy O)\a----------------------------------------");

    qbGrfg("G75",
        "OHETYNEL NYNEZ\a205 R XNEFPU OYIQ\aA JNFUVATGBA FG NAQ A ZVQQYR FG\a\aJVGU CEBTNHEQ\a\aTYNFF OERNXNTR",
        "PNYY:OHETYNEL NYNEZ",
        "NQQE:205 R XNEFPU OYIQ",
        "K:A JNFUVATGBA FG NAQ A ZVQQYR FG",
        "VASB:JVGU CEBTNHEQ\aTYNFF OERNXNTR");

    qbGrfg("G76",
        "FHFCVPVBHF NPGVIVGL\aURAEL FG\a\a\aJUVGR PNE CR2M9N \aGNA PNE  PBZCNPG GLCR HAX VASBEZNGVBA \a\aEHAVVAT NEBHAQ PRZRGREL\a8 WHIRAVYRF",
        "PNYY:FHFCVPVBHF NPGVIVGL",
        "NQQE:URAEL FG",
        "VASB:JUVGR PNE CR2M9N\aGNA PNE  PBZCNPG GLCR HAX VASBEZNGVBA\aEHAVVAT NEBHAQ PRZRGREL\a8 WHIRAVYRF");

    qbGrfg("G77",
        "FHFCVPVBHF NPGVIVGL\a" +
        "615 ZNCYR INYYRL QE\a" +
        "UNMRY YA & ZNCYR FG\a\a" +
        "VA GUR CNEXVAT YBG SHYY BS WHIRAVYRF\a\a" +
        "GENFUVAT GUR CNEXVAT YBG\a\a" +
        "QEVIVAT P&V",

        "PNYY:FHFCVPVBHF NPGVIVGL",
        "NQQE:615 ZNCYR INYYRL QE",
        "K:UNMRY YA & ZNCYR FG",
        "VASB:VA GUR CNEXVAT YBG SHYY BS WHIRAVYRF\aGENFUVAT GUR CNEXVAT YBG\aQEVIVAT P&V");

    qbGrfg("G78",
        "OHETYNEL NYNEZ\a2 FHZZVG QE\aA JNFUVATGBA FG & JRFGJBBQ QE\a\aBCRE/ OBO\a\aQHERFF NYNEZ\a\aANAPL EVPR\a\aAB PBAGNPG ZNQR",
        "PNYY:OHETYNEL NYNEZ",
        "NQQE:2 FHZZVG QE",
        "K:A JNFUVATGBA FG & JRFGJBBQ QE",
        "VASB:BCRE/ OBO\aQHERFF NYNEZ\aANAPL EVPR\aAB PBAGNPG ZNQR");

    qbGrfg("G79",
        "GERFCNFFVAT\a" +
        "502 XERV NIR\a" +
        "DHNEEL FG & R XNEFPU OYIQ\a\a" +
        "ARVTUOBE PUVYQERA UNIR ORRA VA GUR PERRX JUVPU VF CEVINGR CEBCREGL\a\a" +
        "PNYYRE'F 13 LE BYQ QNHTUGRE GBYQ GURZ GB YRNIR; GURA GUR PUVYQERA'F \a" +
        "ZBGURE GBYQ QNHTUGRE VG JBHYQ OR BX SBE GURZ GB OR GURER FVAPR VG'F \a" +
        "CHOYVP\a\a\a" +
        "PNYYRE VF ABG BA FPRAR",

        "PNYY:GERFCNFFVAT",
        "NQQE:502 XERV NIR",
        "K:DHNEEL FG & R XNEFPU OYIQ",
        "VASB:ARVTUOBE PUVYQERA UNIR ORRA VA GUR PERRX JUVPU VF CEVINGR CEBCREGL\aPNYYRE'F 13 LE BYQ QNHTUGRE GBYQ GURZ GB YRNIR; GURA GUR PUVYQERA'F\aZBGURE GBYQ QNHTUGRE VG JBHYQ OR BX SBE GURZ GB OR GURER FVAPR VG'F\aCHOYVP\aPNYYRE VF ABG BA FPRAR");

    qbGrfg("G80",
        "FHFCVPVBHF CREFBA\a" +
        "1301 FHAFUVAR YA\a" +
        "SBHE FRNFBAF QE\a\a" +
        "FHFC ZNYR JNYXVAT NEBHAQ RNEYVRE GBQNL.\a\a" +
        "JZ OYX UBBQVR NAQ OYHR WRNAF, OYX AVXR FUBRF\a\a" +
        "1FG GENVYRE BA YRSG ONPX QBBE VF JVQR.  ABG FHER VS INPNAG GENVYRE BE \a" +
        "ABG.",

        "PNYY:FHFCVPVBHF CREFBA",
        "NQQE:1301 FHAFUVAR YA",
        "K:SBHE FRNFBAF QE",
        "VASB:FHFC ZNYR JNYXVAT NEBHAQ RNEYVRE GBQNL.\aJZ OYX UBBQVR NAQ OYHR WRNAF, OYX AVXR FUBRF\a1FG GENVYRE BA YRSG ONPX QBBE VF JVQR.  ABG FHER VS INPNAG GENVYRE BE\aABG.");

    qbGrfg("G81",
        "QVFGHEONAPR\a1 OYNPX XAVTUG QE\aJ PBYHZOVN & J YVOREGL\a\aPBHAPVYVAT PRAGRE HAFHER BS VFFHR",
        "PNYY:QVFGHEONAPR",
        "NQQE:1 OYNPX XAVTUG QE",
        "K:J PBYHZOVN & J YVOREGL",
        "VASB:PBHAPVYVAT PRAGRE HAFHER BS VFFHR");

    qbGrfg("G82",
        "P & V QEVIVAT\a32 NYZBFG GB PVGL YVZGF\a\a\aJUVGR YVAPBYA PBAGRAGNY OYNPX GBC\a\aNYY BIRE GUR EBNQ\a\aAB CYNGRF",
        "PNYY:P & V QEVIVAT",
        "NQQE:32 NYZBFG GB PVGL YVZGF",
        "VASB:JUVGR YVAPBYA PBAGRAGNY OYNPX GBC\aNYY BIRE GUR EBNQ\aAB CYNGRF");

    qbGrfg("G83",
        "1050 W1\a748 J XNEFPU OYIQ\aJNYGBA & ZNCYR INYYRL \a\a3 PNEF\a\aPURIL VZCNYN JUVGR\aPURIL PNINYVRE TBYQ\aSBEQ RFPNCR BENATR\a\aW3",
        "PNYY:1050 W1",
        "NQQE:748 J XNEFPU OYIQ",
        "K:JNYGBA & ZNCYR INYYRL",
        "VASB:3 PNEF\aPURIL VZCNYN JUVGR\aPURIL PNINYVRE TBYQ\aSBEQ RFPNCR BENATR\aW3");

    qbGrfg("G84",
        "FGRNYVAT\a" +
        "820 RYRPGEVP FG\a" +
        "JRORE EQ & CBGBFV FG\a\a" +
        "UBHFR AHZORE 1 NZOHYNAPR \a\a" +
        "2 YNCGBCF FGBYRA\a\a" +
        "GENVAVAT PRAGRE NERN BSS BS RYRPGEVP FG",

        "PNYY:FGRNYVAT",
        "NQQE:820 RYRPGEVP FG",
        "K:JRORE EQ & CBGBFV FG",
        "VASB:UBHFR AHZORE 1 NZOHYNAPR\a2 YNCGBCF FGBYRA\aGENVAVAT PRAGRE NERN BSS BS RYRPGEVP FG");

    qbGrfg("G85",
        "QVFGHEONAPR\a2 A JNFUVATGBA FG\aPBYHZOVN FG & YVOREGL FG\a\aPHFGBZRE JNF ORVAT QVFGEHCGVIR\a\aPNYYRE QVQ NQIVFR GUNG UR JNF YRNIVAT",
        "PNYY:QVFGHEONAPR",
        "NQQE:2 A JNFUVATGBA FG",
        "K:PBYHZOVN FG & YVOREGL FG",
        "VASB:PHFGBZRE JNF ORVAT QVFGEHCGVIR\aPNYYRE QVQ NQIVFR GUNG UR JNF YRNIVAT");

    qbGrfg("G86",
        "QEHT BSSRAFR\a1040 SBEFGRE FG\aF SYRZVAT NIR & JNYGRE FG",
        "PNYY:QEHT BSSRAFR",
        "NQQE:1040 SBEFGRE FG",
        "K:F SYRZVAT NIR & JNYGRE FG");

    qbGrfg("G87",
        "FHFCVPVBHF NPGVIVGL\a102 EBOOL YA\aA JNFUVATGBA FG & UVYYFOBEB EQ\a\aJZ UNG CBFF ERQ NAQ GNA FUBEGF NAQ JNYXRQ VAGB GUR ERFVQRAPR",
        "PNYY:FHFCVPVBHF NPGVIVGL",
        "NQQE:102 EBOOL YA",
        "K:A JNFUVATGBA FG & UVYYFOBEB EQ",
        "VASB:JZ UNG CBFF ERQ NAQ GNA FUBEGF NAQ JNYXRQ VAGB GUR ERFVQRAPR");

    qbGrfg("G88",
        "OHETYNEL NYNEZ\a218 J YVOREGL FG\aA SENAXYVA FG & A N FG\a\aPBMRNA PERZRGBEL ONL QBBE NAQ ONPX RAGEL QBBE",
        "PNYY:OHETYNEL NYNEZ",
        "NQQE:218 J YVOREGL FG",
        "K:A SENAXYVA FG & A N FG",
        "VASB:PBMRNA PERZRGBEL ONL QBBE NAQ ONPX RAGEL QBBE");

    qbGrfg("G89",
        "OHETYNEL NYNEZ\a" +
        "443 FURANAQBNU QE\a" +
        "TENAQ PNALBA QE & UVYYFOBEB EQ\a\a" +
        "FVYRAG CNAVP NYNEZ\a\a\a" +
        "ZNYR BA GUR FPRAR JVGU AB CNFF JBEQ\a\a" +
        "TNEL RYYRE",

        "PNYY:OHETYNEL NYNEZ",
        "NQQE:443 FURANAQBNU QE",
        "K:TENAQ PNALBA QE & UVYYFOBEB EQ",
        "VASB:FVYRAG CNAVP NYNEZ\aZNYR BA GUR FPRAR JVGU AB CNFF JBEQ\aTNEL RYYRE");

    qbGrfg("G90",
        "1050 W1\a614 JNYZNEG QE\aJNYGBA QE & CBGBFV FG\a\aOYNPX UBAQN CI\aJUVGR PVGL BS SNEZVATGBA JBEX GEHPX\a\aORUVAQ GUR OHVYQVAT",
        "PNYY:1050 W1",
        "NQQE:614 JNYZNEG QE",
        "K:JNYGBA QE & CBGBFV FG",
        "VASB:OYNPX UBAQN CI\aJUVGR PVGL BS SNEZVATGBA JBEX GEHPX\aORUVAQ GUR OHVYQVAT");

    qbGrfg("G91",
        "OHETYNEL NYNEZ\a1100 FGR TRARIVRIR NIR\aIVREFR QE & XNEFPU OYIQ\a\aAB FCRPVSVP YBPNGVBA  OHETYNEL ZBGVBA",
        "PNYY:OHETYNEL NYNEZ",
        "NQQE:1100 FGR TRARIVRIR NIR",
        "K:IVREFR QE & XNEFPU OYIQ",
        "VASB:AB FCRPVSVP YBPNGVBA  OHETYNEL ZBGVBA");

    qbGrfg("G92",
        "QVFGHEONAPR\a510 F SENAXYVA FG\aSBHEGU FG & FRIRAGU FG\a124U",
        "PNYY:QVFGHEONAPR",
        "NQQE:510 F SENAXYVA FG",
        "K:SBHEGU FG & FRIRAGU FG",
        "VASB:124U");

    qbGrfg("G93",
        "QVFGHEONAPR\a920 IREABA NIR\aLNYR NIR & NYQRETNGR FG\a\aEBANYQ ZHYYVANK VF VA GUR UBHFR NAQ JVYY ABG YRNIR\a45 LRNE BYQ ZNYR",
        "PNYY:QVFGHEONAPR",
        "NQQE:920 IREABA NIR",
        "K:LNYR NIR & NYQRETNGR FG",
        "VASB:EBANYQ ZHYYVANK VF VA GUR UBHFR NAQ JVYY ABG YRNIR\a45 LRNE BYQ ZNYR");

    qbGrfg("G94",
        "FHFCVPVBHF NPGVIVGL\a67 FO SEBZ SNVETEBHAQF\a\a\a67 FO SEBZ SNVE TEBHAQF\a\aJUVGR QHNYYL SYNG ORQ\a\aQBT GVRQ GB SYNG ORQ",
        "PNYY:FHFCVPVBHF NPGVIVGL",
        "NQQE:67 FO SEBZ SNVETEBHAQF",
        "ZNQQE:67 SEBZ SNVETEBHAQF",
        "VASB:67 FO SEBZ SNVE TEBHAQF\aJUVGR QHNYYL SYNG ORQ\aQBT GVRQ GB SYNG ORQ");

    qbGrfg("G95",
        "FHFCVPVBHF CREFBA\a209 A PNEYRGBA FG\aFGR TRARIVRIR NIR & R PBYYRTR NIR\a\aGUR TERRA BYQRE ZBQRY ZHFPYR PNE\a\aNG GUR QNL PNER",
        "PNYY:FHFCVPVBHF CREFBA",
        "NQQE:209 A PNEYRGBA FG",
        "K:FGR TRARIVRIR NIR & R PBYYRTR NIR",
        "VASB:GUR TERRA BYQRE ZBQRY ZHFPYR PNE\aNG GUR QNL PNER");

    qbGrfg("G96",
        "1050 W1\a1609 J PBYHZOVN FG\aJRFGZBHAG QE & UJL 67\a\aPUNEGRE INA CNEXRQ ARNE GUR CHZCF",
        "PNYY:1050 W1",
        "NQQE:1609 J PBYHZOVN FG",
        "K:JRFGZBHAG QE & UJL 67",
        "VASB:PUNEGRE INA CNEXRQ ARNE GUR CHZCF");

    qbGrfg("G97",
        "OHETYNEL NYNEZ\a" +
        "3 A WRSSREFBA FG\a" +
        "J PBYHZOVN FG & J PBYYRTR NIR\a\a" +
        "ZVQPBZ\a\a" +
        "PBQR 3131 SEBAG QBBE\a\a" +
        "XRVGU CRGGL 7479598\a" +
        "ZNEFUN CRGGL 7479578\a" +
        "NAQL CRGGL 3300205",

        "PNYY:OHETYNEL NYNEZ",
        "NQQE:3 A WRSSREFBA FG",
        "K:J PBYHZOVN FG & J PBYYRTR NIR",
        "VASB:ZVQPBZ\aPBQR 3131 SEBAG QBBE\aXRVGU CRGGL 7479598\aZNEFUN CRGGL 7479578\aNAQL CRGGL 3300205");

    qbGrfg("G98",
        "1050 W1\a1609 J PBYHZOVN FG\aJRFGZBHAG QE & UJL 67\a\aW3\a2009 ULHAQNV FNAGN SR NAQ N 2005 QHENATB",
        "PNYY:1050 W1",
        "NQQE:1609 J PBYHZOVN FG",
        "K:JRFGZBHAG QE & UJL 67",
        "VASB:W3\a2009 ULHAQNV FNAGN SR NAQ N 2005 QHENATB");

    qbGrfg("G99",
        "OHETYNEL NYNEZ\a" +
        "140 JRFGZBHAG QE\a" +
        "J YVOREGL FG & J PBYHZOVN FG\a\a" +
        "pryy onpxhc\a\a" +
        "wbua svgm 756-6968 naq 760-4140\a" +
        "nagbar orgun 760-8697\a" +
        "cnz xraarql 756-0548\a" +
        "qrr yhrxrgzrlre 756-8392",

        "PNYY:OHETYNEL NYNEZ",
        "NQQE:140 JRFGZBHAG QE",
        "K:J YVOREGL FG & J PBYHZOVN FG",
        "VASB:pryy onpxhc\awbua svgm 756-6968 naq 760-4140\anagbar orgun 760-8697\acnz xraarql 756-0548\aqrr yhrxrgzrlre 756-8392");

    qbGrfg("G100",
        "PURPX GUR JRYY ORVAT\a" +
        "316 F WRSSREFBA FG\a" +
        "J SVEFG FG & GUVEQ FG\a\a" +
        "irebavpn qnygba 25 lb srznyr\a" +
        "fhssref sebz qrcerffvba\a" +
        "fnvq fur jnf ba gur cubar jvgu fhvpvqr ubgyvar\a" +
        "pnyyre vf gur sngure, pnyyvat sebz Trbetvn\a" +
        "sngure erdhrfgrq ur or pbagnpgrq nsgre gur pnyy cyrnfr",

        "PNYY:PURPX GUR JRYY ORVAT",
        "NQQE:316 F WRSSREFBA FG",
        "K:J SVEFG FG & GUVEQ FG",
        "VASB:irebavpn qnygba 25 lb srznyr\afhssref sebz qrcerffvba\afnvq fur jnf ba gur cubar jvgu fhvpvqr ubgyvar\apnyyre vf gur sngure, pnyyvat sebz Trbetvn\asngure erdhrfgrq ur or pbagnpgrq nsgre gur pnyy cyrnfr");

  }
 
  choyvp fgngvp ibvq znva(Fgevat[] netf) {
    arj ZBSnezvatgbaCnefreGrfg().trarengrGrfgf("G1");
  }
}