cnpxntr arg.narv.pnqcntr.cnefref.AP;

vzcbeg arg.narv.pnqcntr.cnefref.OnfrCnefreGrfg;

vzcbeg bet.whavg.Grfg;

/* 
Ohapbzor pbhagl, AP
Pbagnpg: "qrna.pnfgnyqb@ngg.arg" <qrna.pnfgnyqb@ngg.arg>
Pbagnpg: Uneel ZpYnhtuyva WE <uneelzwe@tznvy.pbz>
Fraqre: PNQ@ohapbzorpbhagl.bet <Sebz%3NPNQ@ohapbzorpbhagl.bet>

PNQ:433 YBAT FUBNYF EQ;O21H;FHOWRPG FGVYY QBJA;RQTNE OHYYHPX;SNYYF;YRQORGGRE EQ;PYNLGBA EQ
PNQ:1 UNZOL QE;O9;(SE) FGEHPGHER SVER;BJRAOL PBIR EQ
PNQ:411 CBPBAB PG;O21H;RTREGBA, ANAPL;PURFG CNVA;EBPXL ZBHAGNVA JNL
PNQ:3055 FJRRGRA PERRX EQ;FZBXR QRG/;CRPUVARL CYNFGVP CNPXNTVA;NQG;(SE) SVER NYNEZ;JRFYRL QE;SNE UBEVMBAF YA;10015419
PNQ:206 EBLNY CVARF QE;O21;GNLYBE, EBOREG R;HAPBAFPVBHF/ SNVAGVAT;FJRRGRA PERRX EQ;NCCVNA JNL
PNQ:345 V26 J;8283372724 QVFG: 1003.28 SG;IREVMBA JVERYRFF;PURFG CNVA;V26 J GB OERINEQ EQ;10015456
PNQ:59 FZBXRZBAG QE;O21H;ORLRE,WNZRF;URNEG CEBOYRZF;ORNE CNJ YA;OBHAQNEL GERR CNFF
PNQ:100 BNX GRE;O21;GERR QBJA VA CBJREYVARF;IREVMBA;(SE) YVARF QBJA;A BNX GRE;EBLNY CVARF QE
PNQ:16 OYHR UREBA QE;O213;ORPXUNZ, YVAQN & ZNYNPUL;SNYYF;EVIRE PNAR QE
PNQ:OPSE NFFVFGNAPR ERDHRFGRQ;32 ZPVAGLER QE;NF03;Rirag fcnjarq sebz NFFVFG YNJ RASBEPRZRAG.  [12/23/10 16:54:46 UBARLPW] [YNJ] PBZC VF ERD RZF PBZR GB PURPX URE  [12/23/10 16:54:08 OENQYRLP]\aRirag fcnjarq sebz QBZRFGVP QVFGHEONAPR.  [12/23
PNQ:2147 OERINEQ EQ;O21H;NCG 4;URNEG CEBOYRZF;PNEYNAQ QE;TYRAA OEVQTR EQ
PNQ:1849 OERINEQ EQ;O212;OBET JNEARE;(SE) IRUVPYR SVER;CYNGVAHZ PG;UBYYL NPERF YA
PNQ:245 PRQNE YA;O21;XNYBTRENXVF, NEABYQ F;NOQBZVANY CNVAF / CEBOYRZF;FJRRGRA PERRX EQ;ZNCYR PG
PNQ:183 JRFGBA EQ;O21;IREVMBA;(M)ZBGBE IRU NPPVQRAG HAXABJA;GNZCN PVE;GNZCN PVE
PNQ:579-OYX ZVYYF TNC EQ;O213;8287720618 QVFG: 107.57 SG;IREVMBA;(M)ZBGBE IRU NPPVQRAG HAXABJA;PRAGENY CNEX QE;QENXRF ZRNQBJ YA
PNQ:357 V26 R;O21;IREVMBA;(M)ZBGBE IRU NPPVQRAG HAXABJA;V26 R GB YBAT FUBNYF EQ
PNQ:365 V26 J;O21;(M)ZBGBE IRU NPPVQRAG HAXABJA;YBAT FUBNYF EQ GB V26 J
PNQ:375 V26 J;O21;IREVMBA;(M)ZBGBE IRU NPPVQRAG HAXABJA;V26 J GB YBAT FUBNYF EQ;NVECBEG EQ GB V26 J
PNQ:275 ZVYYF TNC EQ;O213;IREVMBA;(M)ZBGBE IRU NPPVQRAG VAWHEL;CVAAREF PBIR EQ;FHEERL EHA
PNQ:355 V26 J;O21;IREVMBA;(M)ZBGBE IRU NPPVQRAG HAXABJA;YBAT FUBNYF EQ GB V26 J
NQ:900-OYX PNAR PERRX EQ;O213;FUC;(SE)GERR QBJA;SNVE BNXF RFG;EVIRE PNAR QE
PNQ:33 GUBEBHTUOERQ PVE;O21;NFFVFG BSS SYBBE;(SE) FREIVPR NAL GLCR;FNQQYRJBBQ YA;JNGFBA EQ
PNQ:354 V26 J;O21;IREVMBA;(SE)GERR QBJA;YBAT FUBNYF EQ GB V26 J
PNQ:244 JVYYVF JNL;O21;Ohapbzor Pbhagl;OERNGUVAT CEBOYRZF
PNQ:8 QNAFSBEQ YA;O21H;ZNESYNX, WBUA & NZORE;SNYYF;JRYOBHEA JNL
PNQ:31 URLJBBQ EQ;O21;QVFG: 1.51 SG;(M)ZBGBE IRU NPPVQRAG HAXABJA;URAQREFBAIVYYR EQ;BYQ URLJBBQ EQ
PNQ:11 FNOEVAN QE;O21H;FZBXR VA ERFVQRAPR;ZVYYRE, WNZRF N;(SE) FGEHPGHER SVER;REVXN YA
PNQ:475 ZVYYF TNC EQ;O213;8289892954 QVFG: 27.37 sg;IREVMBA;(SE)GERR QBJA;PRAGENY CNEX QE;SBHE BNXF QE
PNQ:862 PNAR PERRX EQ/PEBFF PERRX SNEZ EQ;O213;(SE)GERR QBJA
PNQ:29 UVTUOEVQTR KVAT;TRARENY SN;QRRESVRYQ NFFVFGRQ YVIVAT;FVZCYRK;(SE) SVER NYNEZ;YNZORGU QE;FNYVFOHEL QE;10015610
PNQ:226-O GNZCN PVE;O21;IREVMBA;URZBEEUNTR / YNPRENGVBA;JRFGBA EQ;JRFGBA EQ
PNQ:35 NVECBEG EQ;PBZ. YVSR PRAGRE;NEQRA FRIRAGU QNL NQIRAGVFG;QNAVRYF;(SE) SVER NYNEZ;BYQ FUBNYF EQ;JRYYVATGBA QE;10015618
PNQ:20 TYRAA OEVQTR EQ;O21;8286990135;UHOORYY;UNLARF;(SE) SVER NYNEZ;URAQREFBAIVYYR EQ;JNYQRA QE
PNQ:4 JNYQRA EVQTR QE;TRARENY NYNEZ;FVZCYRK;(SE) SVER NYNEZ;URAQREFBAIVYYR EQ;10015640
PNQ:50 CVARUHEFG PVE;O21;TRARENY NYNEZ;TYRA NEQRA RYRZRAGNEL FPUBBY;FVZCYRK;(SE) SVER NYNEZ;FNVAG WBUAF FG
PNQ:1 URAQREFBA PBHAGL UJL;O21;710 YVAQFRL YBBC EQ;(SE) ZHGHNY NVQ;URAQREFBAIVYYR EQ
PNQ:202 FBHGUJNL TNEQRA EQ;O21;SNYYF;FJRRGRA PERRX EQ
PNQ:1845 OERINEQ EQ;O212;YHAPUEBBZ;PCH VAP;PBAIHYFVBAF / FRVMHERF;PBZZREPR JNL;CYNGVAHZ PG
PNQ:50-OYX PBAPBEQ EQ;O213;NFFG FGENAQRQ ZBGBEVFG;ENVARL, NNEBA;(SE) FREIVPR NAL GLCR;YNHERYGBA YA;JNYFU GEPR
PNQ:2251 URAQREFBAIVYYR EQ;O21;ZBHAGNVA RARETL;NOQBZVANY CNVAF / CEBOYRZF;SBERFG YA F;EBLNY CVARF QE
PNQ:331 PRQNE YA;O21;FJNVA, W JRNIRE;QVNORGVP CEBOYRZF;ZNCYR PG;ZBFF YA
PNQ:25 BYQ FUBNYF EQ;FVZCYRK;(SE) SVER NYNEZ;QBJAVAT QE;TYRAA OEVQTR EQ;10015691
PNQ:277 ZVYYF TNC EQ;O213;FZBXR QRGRPGBE;PCV;(SE) SVER NYNEZ;CVAAREF PBIR EQ;FHEERL EHA
PNQ:156 YBJRE PUEVFG FPUBBY EQ/ONYQJVA EQ;O213;IREVMBA;(M)ZBGBE IRU NPPVQRAG HAXABJA
PNQ:280 ONYY TNC EQ;O212;NFFVFG EGF;WRSS NG SVTUG JNGPU;(SE) FREIVPR NAL GLCR;YNXBGN GEY;OERINEQ EQ
PNQ:2607 URAQREFBAIVYYR EQ;O21;BBO TB TEBPREL;FJNA,WBUA;(SE) NFFVFG YNJ RASBEPRZRAG;F CNEX PG;JNGFBA EQ
PNQ:280 ONYY TNC EQ;O212;NFFVFG CNG HAYBNQVAT;EGF;(SE) FREIVPR NAL GLCR;YNXBGN GEY;OERINEQ EQ
PNQ:100-OYX YRQORGGRE EQ;O21H;(M)ZBGBE IRU NPPVQRAG HAXABJA;YNEX UY;PNIR YA
PNQ:14 SBHE BNXF QE;O213;(SE) FGEHPGHER SVER;ZVYYF TNC EQ
PNQ:75 JUVGR CVAR QE;O213;JNGRE URNGRE PNHTUG BA SVER;(SE) VAIRFGVTNGVBA;ZNCYR FG;GEBL UVYY QE
PNQ:37 SBKOREEL QE;O21;NFVFG JVGU JNGRE FUHG BSS;(SE) FREIVPR NAL GLCR;ARJ EBPXJBBQ EQ;FCEVAT UVYY QE
PNQ:503 NIREL PERRX EQ;O21H;NFFVFG FHOW HC;ZPPYHER,EBANYQ;(SE) FREIVPR NAL GLCR;ARJZNA PBIR EQ;BJRAOL YA
PNQ:32 UBYYL NPERF YA;O212;(SE) FREIVPR NAL GLCR;OERINEQ EQ
PNQ:162 PNEBYVAN OYHR OVEQ YBBC;O212;PYBFR,QNA & ZNEVR;HAXABJA CEBOYRZ;NFUYRL JBBQF QE
PNQ:600 ONEERGG YA;NQZVA BSSVPRF;TVIRAF RFGNGR URNYGU PRAGRE;TVIRAF RFGNGRF - URNYGU PRAGRE;(SE) SVER NYNEZ;JRFYRL QE;URZYBPX QE;11000026
PNQ:1310 SNAAVAT OEVQTR EQ;RYRPGEBYHK;NQG;(SE) SVER NYNEZ;HAQREJBBQ EQ;ARJ NVECBEG EQ;10015794
PNQ:1301 SNAAVAT OEVQTR EQ;O21;FGNAQOL;JAP NTEVPHYGHENY PRAGRE;(SE) FREIVPR NAL GLCR;HAQREJBBQ EQ;ARJ NVECBEG EQ
PNQ:208 ZVYYF TNC EQ;O213;PURPX B2 BA GBQYRE;(SE) FREIVPR NAL GLCR;FBHGUFVQR IVYYNTR QE;CVAAREF PBIR EQ
PNQ:9 FUNQL BNX YA;O21H;NFFVFG JVGU  FZBXR QRGRPGBE;FCEVAG CPF;(SE) FREIVPR NAL GLCR;OERINEQ EQ
PNQ:210 FHZZRETYRA QE;O212;PNAABA, TYRAQN;HAPBAFPVBHF/ SNVAGVAT;PNFGYREBPX QE;QBAALOEBBX QE
PNQ:615 CBYR PERNFZNA EQ;O212;FVZF, ORGGL;OERNGUVAT CEBOYRZF;UBYYL YA;UNLRF TERRA EQ
PNQ:2533 URAQREFBAIVYYR EQ;O21;NCG 102;PERFPRAG IVRJ;PERFPRAG IVRJ;HAPBAFPVBHF/ SNVAGVAT;HCCRE YNHERY QE;ARFOVGG QE
PNQ:347 V26 R;O21;8282169743;G-Zbovyr HFN;(M)ZBGBE IRU NPPVQRAG VAWHEL;V26 R GB YBAT FUBNYF EQ
PNQ:103 NCCNYNPUVNA OYIQ;O212;EZ 309;URNGURE TYRA NG NEQRA JBBQF;URNGURE TYRA NG NEQRAJBBQF;OERNGUVAT CEBOYRZF;EBPXL ZBHAGNVA JNL
PNQ:2533 URAQREFBAIVYYR EQ;O21;EZ 242;PERFPRAG IVRJ;PERFPRAG IVRJ;HAPBAFPVBHF/ SNVAGVAT;HCCRE YNHERY QE;ARFOVGG QE
PNQ:122 RQTRJBBQ QE;OBGFSBEQ , ONEOREN;YVSR-YVAR;SNYYF;QBJAVAT QE;QBJAVAT QE;11000163
PNQ:342 QBAALOEBBX QE;O212;FZRYY BS TNF VA GUR NERN;OBO NAQREFBA;(SE) VAIRFGVTNGVBA;NHOHEAQNYR QE
PNQ:2400 NCCNYNPUVNA OYIQ;O212;PYHOUBHFR QVAVAT EZ;NEQRAJBBQF - PYHO UBHFR;NEQRAJBBQF ERGVERZRAG PBZZHAVG;PUBXVAT;EBPXL ZBHAGNVA JNL
PNQ:30 UHAGRE QE;O21H;FGEBXR;FYRRCL TNC EQ
PNQ:202 FHZZRETYRA QE;O212;BARVYY FGRCURA NAQ YRFN;SNYYF;ORAG PERRX ENAPU EQ;PNFGYREBPX QE
PNQ:424 ZVYYF TNC EQ;O213;THGVREERM, EBFRAQB;PURFG CNVA;JRFGBA EQ;OENR OHEA QE
PNQ:7 FNVAG NAQERJF EQ;O213;WRSSEVRF,QBA;SNYYF;PUVCCVAT TERRA QE;SBERFG EVQTR QE
PNQ:13 ZPXRAAN EQ;ZNEFUNYYF;(SE) SVER NYNEZ;11000217
PNQ:12 OREYVAF IJ;O102;8287120800;IREVMBA;(SE) FGEHPGHER SVER;A YHGURE EQ
PNQ:206 EBLNY CVARF QE;O21;GNLYBE, EBOREG R;OERNGUVAT CEBOYRZF;FJRRGRA PERRX EQ;NCCVNA JNL
PNQ:10 ORAAVATGBA PG;O21;FZVGU, NAA & OVYY;URNEG CEBOYRZF;BIREYBBX EQ
PNQ:800 ZVYYF TNC EQ;O213;VAFVQR GUR FGBER;ZBYYLF ZNEXRG;ZBYYL`F ZNEXRG,;URNEG CEBOYRZF;PNAR PERRX EQ;CRAYRL EQ
PNQ:100 SERQREVPX YNJ BYZFGRQ JNL;O212;NEOBERGHZ;Ohapbzor Pbhagl;(M)ZBGBE IRU NPPVQRAG VAWHEL;TERRAUBHFR JNL
PNQ:280 ONYY TNC EQ;O212;NFFVFG EGF YBNQVAT N CNGVRAG;(SE) FREIVPR NAL GLCR;YNXBGN GEY;OERINEQ EQ
PNQ:53 QEVSGFGBAR PVE;O212;JRRENFVEV,QBA;(SE) UNMNEQBHF ZNGREVNY;EVIREPERFG OYIQ;EVIREPERFG OYIQ
PNQ:2 ORAG BNX YA;FVMRZBER, R;(SE) FGEHPGHER SVER;BIREYBBX EQ;QRREUNIRA YA;11000280
PNQ:25 BYQ FUBNYF EQ;JNGRE SYBJ MBAR Z-123;SYVAG TEBHC;FVZCYRK;(SE) SVER NYNEZ;QBJAVAT QE;TYRAA OEVQTR EQ;11000292
PNQ:49 UVTUOEVQTR KVAT;EZ 4101/NFFVFG FHO. BSS SYBBE;QRRESVRYQ FXVYYRQ PNER;QRRESVRYQ ERGVERZRAG;(SE) FREIVPR NAL GLCR;YNZORGU QE;FNYVFOHEL QE;11000293
PNQ:100 IVFGN OYIQ;O212;ALCEB;(M)ZBGBE IRU NPPVQRAG VAWHEL;OERINEQ EQ;GEVQRAG QE
PNQ:607 CNEX FBHGU OYIQ;O212;(SE) FREIVPR NAL GLCR;OERINEQ EQ;CNEX FBHGU PG
PNQ:2533 URAQREFBAIVYYR EQ;O21;EZ 321;PERFPRAG IVRJ;PERFPRAG IVRJ;SNYYF;HCCRE YNHERY QE;ARFOVGG QE
PNQ:92 SNVE BNXF EQ;O21;YVSRYVAR;HAXABJA CEBOYRZ;EBLNY BNXF EQ;A SNVE BNXF EQ
PNQ:4 UVPXBEL GERR EQ;O11;IREVMBA;(M)ZBGBE IRU NPPVQRAG VAWHEL;YBJRE TENFFL OENAPU EQ;WHYVNAAR CY

Pbagnpg: Obo furejbbq <zrzcuvfznqzna@tznvy.pbz>
F: Z:PNQ:25 ERLABYQF ZBHAGNVA OYIQ;O20;EZ 126-N;RZRENYQ EVQTR;RZRENYQ EVQTR ERUNO NAQ PNER P;NYYRETVRF / ERNPGVBAF;JRNIREIVYYR EQ
F:PNQ:111 BYQ JRNIREIVYYR EQ;O20;OYNMRE, EHGU;HAPBAFPVBHF/ SNVAGVAT Z: 

Pbagnpg: Qnivq Evpr <pqevpr15@tznvy.pbz>
F: Z:PNQ:656 A SBEX EQ;O15;7654131974 QVFG: 231.30 SG;Ohapbzor Pbhagl;PURFG CNVA
F: Z:PNQ:503 CNVAG SBEX EQ;O15;8287780508;Ohapbzor Pbhagl;FGEBXR;EBPXL YA;UNEJBBQ EQ

Pbagnpg: Obool Qnivf <obooleqnivf@tznvy.pbz>
PNQ:110-1/2 FHZZRE FG;O6;IREVMBA;(SE) FGEHPGHER SVER;CNEXRE QE;NYRKNAQRE NIR

Pbagnpg: Wbfuhn Nqryy <wbfuhnnqryy@tznvy.pbz>
Fraqre: PNQ@ohapbzorpbhagl.bet
PNQ:34 JNYY FG;SF1;MBAR TRARENY SVER;FRYS URYC PERQVG HAVBA;FVZCYRK;(SE) SVER NYNEZ;ONGGREL CNEX NIR;BGVF FG;12002186

Pbagnpg: Npgvir911
[] PNQ:329 ZREEVZBA NIR;O8;OEVNA PRAGRE;GBGNY ERANY PNER;FVPX CREFBA;TNEEVFBA EQ;FGBARL XABO EQ\e\a\a
[] PNQ:120-OYX RQTRJBBQ EQ F;SF5;FCEVAG ARKGRY-PQZN;(SE)GERR QBJA;YR NA UHEFG EQ;PVZNEEBA QE;12011446\e\a\a
[] PNQ:94-1/2 FNEQVF EQ;O10;URNGBA,NAVGN;FVPX CREFBA;ENZRL UVYY QE;SBEQOEBBX EQ;12011447\e\a\a
[] PNQ:SLV: ;31 PUNEYBGGR FG/JBBQSVA CY;SF1;8282169182;G-ZBOVYR HFN;(M)ZBGBE IRU NPPVQRAG HAXABJA;12011448\e\a\a
[] PNQ:31 PUNEYBGGR FG/JBBQSVA CY;SF1;8282169182;G-ZBOVYR HFN;(M)ZBGBE IRU NPPVQRAG HAXABJA;12011448\e\a\a
[] PNQ:Punatrq Angher sebz (M)ZBGBE IRU NPPVQRAG HAXABJA gb (M)ZBGBE IRU NPPVQRAG VAWHEL;31 PUNEYBGGR FG/JBBQSVA CY; NF01;8282169182\e\a\a
[] PNQ:SLV: ;20 FXLIVRJ GRE;SF3;NFFVFG FHO HC VA SEBAG LNEQ;PUVYQERFF, Z Y;(SE) FREIVPR NAL GLCR;A YBHVFVNAN NIR;FGNEZBHAG QE;12011449\e\a\a
[] PNQ:20 FXLIVRJ GRE;SF3;NFFVFG FHO HC VA SEBAG LNEQ;PUVYQERFF, Z Y;(SE) FREIVPR NAL GLCR;A YBHVFVNAN NIR;FGNEZBHAG QE;12011449\e\a\a
[] PNQ:780 URAQREFBAIVYYR EQ;SF5;C-YBG;VATYRF;VATYRF ZNEXRGF;SNYYF;WRSSERFF NIR;OHFORR EQ;12011450\e\a\a
[] PNQ:1345 URAQREFBAIVYYR EQ;SF5;NG GUR TLZ;PNEBYVAN QNL FPUBBY;HF Pryyhyne;GENZNGVP VAWHEVRF;EVQTRSVRYQ CY;OYHR EVQTR CXJL;12011451\e\a\a
[] PNQ:31 FPURAPX CXJL;SF4;8287776867;ERV ERPERNGVBANY RDHVCZRAG;IREVMBA;GENZNGVP VAWHEVRF;R FPURAPX PERF;GBJA FDHNER OYIQ;12011452\e\a\a
[] PNQ:58-N XYBAQLXR NIR;SF1;YVAX GB YVSR;HAXABJA CEBOYRZ;XYBAQLXR CY;ZBAGSBEQ NIR;12011453\e\a\a
[] PNQ:SLV: ;20 FXLIVRJ GRE;SF3;NFFVFG FHO HC;CBJRYY, NZOEBFR & TNVY;(SE) FREIVPR NAL GLCR;A YBHVFVNAN NIR;FGNEZBHAG QE;12011454\e\a\a
[] PNQ:20 FXLIVRJ GRE;SF3;NFFVFG FHO HC;CBJRYY, NZOEBFR & TNVY;(SE) FREIVPR NAL GLCR;A YBHVFVNAN NIR;FGNEZBHAG QE;12011454\e\a\a
[] PNQ:81-N XYBAQLXR NIR;SF1;HF Pryyhyne;SNYYF;XYBAQLXR CY;ZBAGSBEQ NIR;12011455\e\a\a
[] PNQ:79 NFURYNAQ NIR;SF1;UBG FCBG;136;NFFNHYG / FRKHNY NFFNHYG;CNGGBA NIR;UVYYVNEQ NIR;12011456\e\a\a
[] PNQ:SLV: ;25 ENYRVTU EQ;SF9;NCG N;ERQSREA, NQEVRAAR;(SE) SVER NYNEZ;FPUBBY EQ R;YVAPBYA NIR;12012206\e\a\a
[] PNQ:9091 IREQR IVFGN PVE;SF9;SY4,SFDQ1,SZ10,SPNE3,SR2,SR8,SY8,SR9,SONG1,SONG3;NCG 5117;IREVMBA;(SE) FGEHPGHER SVER;EVIRE SBEQ CXJL;12012204\e\a\a
[] PNQ:25 ENYRVTU EQ;SF9;SD5,SR1,SR4;NCG N;ERQSREA, NQEVRAAR;(SE) SVER NYNEZ;FPUBBY EQ R;YVAPBYA NIR;12012206\e\a\a
[] PNQ:9091 IREQR IVFGN PVE;SF9;SY4,SFDQ1,SZ10,SPNE3,SR2,SR8,SY8,SR9,SPUS4,SONG1,SONG3;NCG 5117;IREVMBA;(SE) FGEHPGHER SVER;EVIRE SBEQ CXJL;12012204\e\a\a
[] PNQ:SLV: ;97 F YRKVATGBA NIR;SF1;SZ21;OHVYQVAT QNZNTR;PUHPXF JRYQVAT FREIVPR;SZ-21;(SE) VAIRFGVTNGVBA;NFGBA FG;UVYYVNEQ NIR\e\a\a
[] PNQ:173 SNLRGGRIVYYR FG;SF3;SR6;8287130209;IREVMBA;NOQBZVANY CNVAF / CEBOYRZF;GRKNF FG;BUVB FG;12012208\e\a\a
[] PNQ:2 OEBNQJNL FG GB V240 J;SF1;SR1,SY1;HAXABJA CEBOYRZ;A YRKVATGBA NIR;V240 J;12012209\e\a\a

Pbagnpg: Npgvir911
[] PNQ:557 QRNIREIVRJ EQ;O5;8282808178;FCEVAG ARKGRY-PQZN;ONPX CNVA (ABA-ERPRAG);YBIR VG YA;PNAQYRE XABO EQ\e\a\a
[] PNQ:219 BYQ AP 20 UJL;O2;JNYFU,QRAVFR;FVPX CREFBA;FHA INYYRL QE;QNYR GURYZN ZRZBEVNY QE\e\a\a
[] PNQ:101 YVBAF JNL;O2;EBBZ 124;ZNEWBEVR ZPPHAR PRAGRE;ZNEWBEVR ZPPHAR ZRZBEVNY PRAGR;NOQBZVANY CNVAF / CEBOYRZF;YVBARFF QE\e\a\a
[] PNQ:78 JRNIRE OYIQ;O2;EBBZ 310 // ORQ - 2;OEVNA PRAGRE;OEVNA PRAGRE;FVPX CREFBA;PYVAGBA FG;V26 J GB JRNIRE OYIQ\e\a\a
[] PNQ:91 F GHAARY EQ;SF9;QVFG: 14.41 SG;JNYTERRAF;IREVMBA JVERYRFF;(M)ZBGBE IRU NPPVQRAG VAWHEL;ARJ UNJ PERRX YA;FJNAANABN EVIRE EQ\e\a\a
[] PNQ:380 OERINEQ EQ;O2;EBBZ 312 // ORQ -N;NFGBA CNEX URNYGU PNER;QVKBA UHTURF - NFGBA CNEX URNY;OERNGUVAT CEBOYRZF;UVTU PBHEG RAGENAPR;FURYOHEAR EQ\e\a\a
[] PNQ:3667 FJRRGRA PERRX EQ;O21;NCG E-1;ULQR, OEVNA;FVPX CREFBA;PUREEL FG;EBLNY CVARF QE\e\a\a
[] PNQ:31 R FGNEARF PBIR EQ;SF10;OENMVYYR, O R;FVPX CREFBA;P Z QBNA YA;ZLEN CY\e\a\a
[] PNQ:210 WBUAFGBA OYIQ;SF6;YBG 19;GBJA NAQ PBHAGEL ZUC;IREVMBA JVERYRFF;NOQBZVANY CNVAF / CEBOYRZF;A ORNE PERRX EQ;VBAN PVE\e\a\a
[] PNQ:89 JRQTRSVRYQ CY;O10;UNAQ VAWHEL;FVPX CREFBA;GREENVAR YA\e\a\a
[] PNQ:367 A YBHVFVNAN NIR;SF3;ENZFRL ZBOVYR UBZR CNEGF;(M)VAPBZCYRGR 911;CNGGBA NIR;UNMRY ZVYY EQ\e\a\a
[] PNQ:95 UBYPBZOR PBIR EQ;O2;EZ 201;CVFTNU ZNABE;CVFTNU ZNABE;CFLPUVNGEVP CEBOYRZF;CNEXIVRJ QE;CNEXIVRJ QE\e\a\a
[] PNQ:115 SNVEIVRJ EQ;O2;GUR FPERRA QBBE;SNYYF;YBAQBA EQ;JRFGIVRJ NIR\e\a\a
[] PNQ:600 WHYVNA YA;O2;FHVGR 630;NFURIVYYR ZRQVPVAR & CRQ;NFURIVYYR ZRQVPVAR & CRQ;ONPX CNVA (ABA-ERPRAG);YBAT FUBNYF EQ\e\a\a
[] PNQ:9091 IREQR IVFGN PVE;SF9;NCG 5117;IREVMBA;(SE) FGEHPGHER SVER;EVIRE SBEQ CXJL\e\a\a
[] PNQ:78 RQTRZBAG EQ;O2;SNYYF;UBYZJBBQ EQ;YNGEBOR FG\e\a\a
[] PNQ:1201 CNGGBA NIR;O2;EBBZ 7;FVFGREF BS ZREPL HETRAG PNER;FVFGRE`F BS ZREPL HETRAG PNER;ONPX CNVA (ABA-ERPRAG);ARJ YRVPRFGRE UJL;QEHVQ QE\e\a\a
[] PNQ:1 UNLJBBQ PBHAGL UJL;O2;ZC 417 OYHR EVQTR CEXJ;UNLBBQ RBP;(SE) ZVFFVAT CREFBA FRNEPU;FZBXRL CNEX UJL\e\a\a

Pbagnpg: Npgvir911
Ntrapl anzr: Nfurivyyr Sver Qrcnegzrag
Ybpngvba: Nfurivyyr, AP, Havgrq Fgngrf
Pbagnpg: Npgvir911

PNQ:10 NYRKNAQRE QE;SF1;SY1;NCG 525 JRYSNER PURPX;JBBQOREEL NCGF;(SE) FREIVPR NAL GLCR;A FXLYBSG QE;NEQZVBA CNEX;12012614\e\a
PNQ:304 YVIVATFGBA FG;SF2;SR2;NCG O;HF Pryyhyne;PBAIHYFVBAF / FRVMHERF;QRCBG FG;12012613\e\a
PNQ:100 UVTUYNAQ PRAGRE OYIQ;SF10;SD10;JRFGREA PNEBYVAN SERVTUG YVARE;IREVMBA JVERYRFF;SNYYF;OEHPR EQ;12012612\e\a
PNQ:275 QRNIREIVRJ EQ;SF6;SE3;NCG 4-P;QRNIREIVRJ NCNEGZRAGF;ZVYYF, TYNQLF;QVNORGVP CEBOYRZF;A ORNE PERRX EQ;JRFGZBER QE;12012611\e\a
PNQ:13 ERLABYQF EQ;SF3;SR6;FZBXR QRPGBE & B2 QRPGBE;(SE) FREIVPR NAL GLCR;YBTNA NIR;TRBETVN FG;12012610\e\a
PNQ:391 F SERAPU OEBNQ NIR;SF2;SR2;HAVGRQ FREIVPRF PERQVG;QVNORGVP CEBOYRZF;PUBPGNJ FG;ENYCU FG;12012609\e\a
PNQ:70 V240 J;SF1;SR1,SY1,SR8,SFNS10;(M)ZBGBE IRU NPPVQRAG HAXABJA;GHAARY EQ GB V240 J;V240 J GB PUHAAF PBIR EQ;12012607\e\a
PNQ:4 PBIRJBBQ EQ/PBIRJBBQ YA;SF1;SFDQ1;FZBXR VA NERN;JVYYRGG,WRAAVSRE;(SE) VAIRFGVTNGVBA;12012608\e\a
PNQ:50 V240 J;SF1;SR1,SY1,SFNS10;(M)ZBGBE IRU NPPVQRAG HAXABJA;OEBNQJNL FG GB V240 J;OEBNQJNL FG GB V240 J;12012607\e\a
PNQ:50 V240 J;SF1;SR1,SY1,SFNS10;(M)ZBGBE IRU NPPVQRAG HAXABJA;OEBNQJNL FG GB V240 J;OEBNQJNL FG GB V240 J;12012607\e\a

*/

choyvp pynff APOhapbzorPbhaglCnefreGrfg rkgraqf OnfrCnefreGrfg {
  
  choyvp APOhapbzorPbhaglCnefreGrfg() {
    frgCnefre(arj APOhapbzorPbhaglCnefre(), "OHAPBZOR PBHAGL", "AP");
  }
  
  @Grfg
  choyvp ibvq grfgCnefre() {

    qbGrfg("G1",
        "PNQ:433 YBAT FUBNYF EQ;O21H;FHOWRPG FGVYY QBJA;RQTNE OHYYHPX;SNYYF;YRQORGGRE EQ;PYNLGBA EQ",
        "NQQE:433 YBAT FUBNYF EQ",
        "HAVG:O21H",
        "PNYY:SNYYF",
        "VASB:FHOWRPG FGVYY QBJA / RQTNE OHYYHPX",
        "K:YRQORGGRE EQ & PYNLGBA EQ");

    qbGrfg("G2",
        "PNQ:1 UNZOL QE;O9;(SE) FGEHPGHER SVER;BJRAOL PBIR EQ",
        "NQQE:1 UNZOL QE",
        "HAVG:O9",
        "PNYY:(SE) FGEHPGHER SVER",
        "K:BJRAOL PBIR EQ");

    qbGrfg("G3",
        "PNQ:411 CBPBAB PG;O21H;RTREGBA, ANAPL;PURFG CNVA;EBPXL ZBHAGNVA JNL",
        "NQQE:411 CBPBAB PG",
        "HAVG:O21H",
        "PNYY:PURFG CNVA",
        "ANZR:RTREGBA, ANAPL",
        "K:EBPXL ZBHAGNVA JNL");

    qbGrfg("G4",
        "PNQ:3055 FJRRGRA PERRX EQ;FZBXR QRG/;CRPUVARL CYNFGVP CNPXNTVA;NQG;(SE) SVER NYNEZ;JRFYRL QE;SNE UBEVMBAF YA;10015419",
        "NQQE:3055 FJRRGRA PERRX EQ",
        "PNYY:FZBXR QRG/ / (SE) SVER NYNEZ",
        "VASB:CRPUVARL CYNFGVP CNPXNTVA / NQG",
        "K:JRFYRL QE & SNE UBEVMBAF YA",
        "VQ:10015419");

    qbGrfg("G5",
        "PNQ:206 EBLNY CVARF QE;O21;GNLYBE, EBOREG R;HAPBAFPVBHF/ SNVAGVAT;FJRRGRA PERRX EQ;NCCVNA JNL",
        "NQQE:206 EBLNY CVARF QE",
        "HAVG:O21",
        "PNYY:HAPBAFPVBHF/ SNVAGVAT",
        "ANZR:GNLYBE, EBOREG R",
        "K:FJRRGRA PERRX EQ & NCCVNA JNL");

    qbGrfg("G6",
        "PNQ:345 V26 J;8283372724 QVFG: 1003.28 SG;IREVMBA JVERYRFF;PURFG CNVA;V26 J GB OERINEQ EQ;10015456",
        "NQQE:345 V26 J",
        "ZNQQE:345 V 26 J",
        "PNYY:PURFG CNVA",
        "VASB:V26 J GB OERINEQ EQ",
        "VQ:10015456");

    qbGrfg("G7",
        "PNQ:59 FZBXRZBAG QE;O21H;ORLRE,WNZRF;URNEG CEBOYRZF;ORNE CNJ YA;OBHAQNEL GERR CNFF",
        "NQQE:59 FZBXRZBAG QE",
        "HAVG:O21H",
        "PNYY:URNEG CEBOYRZF",
        "ANZR:ORLRE,WNZRF",
        "K:ORNE CNJ YA & OBHAQNEL GERR CNFF");

    qbGrfg("G8",
        "PNQ:100 BNX GRE;O21;GERR QBJA VA CBJREYVARF;IREVMBA;(SE) YVARF QBJA;A BNX GRE;EBLNY CVARF QE",
        "NQQE:100 BNX GRE",
        "HAVG:O21",
        "PNYY:(SE) YVARF QBJA",
        "VASB:GERR QBJA VA CBJREYVARF",
        "K:A BNX GRE & EBLNY CVARF QE");

    qbGrfg("G9",
        "PNQ:16 OYHR UREBA QE;O213;ORPXUNZ, YVAQN & ZNYNPUL;SNYYF;EVIRE PNAR QE",
        "NQQE:16 OYHR UREBA QE",
        "HAVG:O213",
        "PNYY:SNYYF",
        "ANZR:ORPXUNZ, YVAQN & ZNYNPUL",
        "K:EVIRE PNAR QE");

    qbGrfg("G10",
        "PNQ:OPSE NFFVFGNAPR ERDHRFGRQ;32 ZPVAGLER QE;NF03;Rirag fcnjarq sebz NFFVFG YNJ RASBEPRZRAG.  [12/23/10 16:54:46 UBARLPW] [YNJ] PBZC VF ERD RZF PBZR GB PURPX URE  [12/23/10 16:54:08 OENQYRLP]\aRirag fcnjarq sebz QBZRFGVP QVFGHEONAPR.  [12/23",
        "NQQE:32 ZPVAGLER QE",
        "PNYY:OPSE NFFVFGNAPR ERDHRFGRQ",
        "QNGR:12/23/10",
        "GVZR:16:54:46",
        "HAVG:NF03",
        "VASB:Rirag fcnjarq sebz NFFVFG YNJ RASBEPRZRAG. / PBZC VF ERD RZF PBZR GB PURPX URE / Rirag fcnjarq sebz QBZRFGVP QVFGHEONAPR.");

    qbGrfg("G11",
        "PNQ:2147 OERINEQ EQ;O21H;NCG 4;URNEG CEBOYRZF;PNEYNAQ QE;TYRAA OEVQTR EQ",
        "NQQE:2147 OERINEQ EQ",
        "HAVG:O21H",
        "NCG:4",
        "PNYY:URNEG CEBOYRZF",
        "K:PNEYNAQ QE & TYRAA OEVQTR EQ");

    qbGrfg("G12",
        "PNQ:1849 OERINEQ EQ;O212;OBET JNEARE;(SE) IRUVPYR SVER;CYNGVAHZ PG;UBYYL NPERF YA",
        "NQQE:1849 OERINEQ EQ",
        "HAVG:O212",
        "PNYY:(SE) IRUVPYR SVER",
        "VASB:OBET JNEARE",
        "K:CYNGVAHZ PG & UBYYL NPERF YA");

    qbGrfg("G13",
        "PNQ:245 PRQNE YA;O21;XNYBTRENXVF, NEABYQ F;NOQBZVANY CNVAF / CEBOYRZF;FJRRGRA PERRX EQ;ZNCYR PG",
        "NQQE:245 PRQNE YA",
        "HAVG:O21",
        "PNYY:NOQBZVANY CNVAF / CEBOYRZF",
        "ANZR:XNYBTRENXVF, NEABYQ F",
        "K:FJRRGRA PERRX EQ & ZNCYR PG");

    qbGrfg("G14",
        "PNQ:183 JRFGBA EQ;O21;IREVMBA;(M)ZBGBE IRU NPPVQRAG HAXABJA;GNZCN PVE;GNZCN PVE",
        "NQQE:183 JRFGBA EQ",
        "HAVG:O21",
        "PNYY:(M)ZBGBE IRU NPPVQRAG HAXABJA",
        "K:GNZCN PVE & GNZCN PVE");

    qbGrfg("G15",
        "PNQ:579-OYX ZVYYF TNC EQ;O213;8287720618 QVFG: 107.57 SG;IREVMBA;(M)ZBGBE IRU NPPVQRAG HAXABJA;PRAGENY CNEX QE;QENXRF ZRNQBJ YA",
        "NQQE:579-OYX ZVYYF TNC EQ",
        "ZNQQE:579 ZVYYF TNC EQ",
        "HAVG:O213",
        "PNYY:(M)ZBGBE IRU NPPVQRAG HAXABJA",
        "K:PRAGENY CNEX QE & QENXRF ZRNQBJ YA");

    qbGrfg("G16",
        "PNQ:357 V26 R;O21;IREVMBA;(M)ZBGBE IRU NPPVQRAG HAXABJA;V26 R GB YBAT FUBNYF EQ",
        "NQQE:357 V26 R",
        "ZNQQE:357 V 26 R",
        "HAVG:O21",
        "PNYY:(M)ZBGBE IRU NPPVQRAG HAXABJA",
        "VASB:V26 R GB YBAT FUBNYF EQ");

    qbGrfg("G17",
        "PNQ:365 V26 J;O21;(M)ZBGBE IRU NPPVQRAG HAXABJA;YBAT FUBNYF EQ GB V26 J",
        "NQQE:365 V26 J",
        "ZNQQE:365 V 26 J",
        "HAVG:O21",
        "PNYY:(M)ZBGBE IRU NPPVQRAG HAXABJA",
        "VASB:YBAT FUBNYF EQ GB V26 J");

    qbGrfg("G18",
        "PNQ:375 V26 J;O21;IREVMBA;(M)ZBGBE IRU NPPVQRAG HAXABJA;V26 J GB YBAT FUBNYF EQ;NVECBEG EQ GB V26 J",
        "NQQE:375 V26 J",
        "ZNQQE:375 V 26 J",
        "HAVG:O21",
        "PNYY:(M)ZBGBE IRU NPPVQRAG HAXABJA",
        "VASB:V26 J GB YBAT FUBNYF EQ / NVECBEG EQ GB V26 J");

    qbGrfg("G19",
        "PNQ:275 ZVYYF TNC EQ;O213;IREVMBA;(M)ZBGBE IRU NPPVQRAG VAWHEL;CVAAREF PBIR EQ;FHEERL EHA",
        "NQQE:275 ZVYYF TNC EQ",
        "HAVG:O213",
        "PNYY:(M)ZBGBE IRU NPPVQRAG VAWHEL",
        "K:CVAAREF PBIR EQ & FHEERL EHA");

    qbGrfg("G20",
        "PNQ:355 V26 J;O21;IREVMBA;(M)ZBGBE IRU NPPVQRAG HAXABJA;YBAT FUBNYF EQ GB V26 J",
        "NQQE:355 V26 J",
        "ZNQQE:355 V 26 J",
        "HAVG:O21",
        "PNYY:(M)ZBGBE IRU NPPVQRAG HAXABJA",
        "VASB:YBAT FUBNYF EQ GB V26 J");

    qbGrfg("G21",
        "PNQ:900-OYX PNAR PERRX EQ;O213;FUC;(SE)GERR QBJA;SNVE BNXF RFG;EVIRE PNAR QE",
        "NQQE:900-OYX PNAR PERRX EQ",
        "ZNQQE:900 PNAR PERRX EQ",
        "HAVG:O213",
        "PNYY:(SE)GERR QBJA",
        "K:SNVE BNXF RFG & EVIRE PNAR QE",
        "VASB:FUC");

    qbGrfg("G22",
        "PNQ:33 GUBEBHTUOERQ PVE;O21;NFFVFG BSS SYBBE;(SE) FREIVPR NAL GLCR;FNQQYRJBBQ YA;JNGFBA EQ",
        "NQQE:33 GUBEBHTUOERQ PVE",
        "HAVG:O21",
        "PNYY:(SE) FREIVPR NAL GLCR",
        "VASB:NFFVFG BSS SYBBE",
        "K:FNQQYRJBBQ YA & JNGFBA EQ");

    qbGrfg("G23",
        "PNQ:354 V26 J;O21;IREVMBA;(SE)GERR QBJA;YBAT FUBNYF EQ GB V26 J",
        "NQQE:354 V26 J",
        "ZNQQE:354 V 26 J",
        "HAVG:O21",
        "PNYY:(SE)GERR QBJA",
        "VASB:YBAT FUBNYF EQ GB V26 J");

    qbGrfg("G24",
        "PNQ:244 JVYYVF JNL;O21;Ohapbzor Pbhagl;OERNGUVAT CEBOYRZF",
        "NQQE:244 JVYYVF JNL",
        "HAVG:O21",
        "PNYY:OERNGUVAT CEBOYRZF",
        "VASB:Ohapbzor Pbhagl");

    qbGrfg("G25",
        "PNQ:8 QNAFSBEQ YA;O21H;ZNESYNX, WBUA & NZORE;SNYYF;JRYOBHEA JNL",
        "NQQE:8 QNAFSBEQ YA",
        "HAVG:O21H",
        "PNYY:SNYYF",
        "ANZR:ZNESYNX, WBUA & NZORE",
        "K:JRYOBHEA JNL");

    qbGrfg("G26",
        "PNQ:31 URLJBBQ EQ;O21;QVFG: 1.51 SG;(M)ZBGBE IRU NPPVQRAG HAXABJA;URAQREFBAIVYYR EQ;BYQ URLJBBQ EQ",
        "NQQE:31 URLJBBQ EQ",
        "HAVG:O21",
        "PNYY:(M)ZBGBE IRU NPPVQRAG HAXABJA",
        "K:URAQREFBAIVYYR EQ & BYQ URLJBBQ EQ");

    qbGrfg("G27",
        "PNQ:11 FNOEVAN QE;O21H;FZBXR VA ERFVQRAPR;ZVYYRE, WNZRF N;(SE) FGEHPGHER SVER;REVXN YA",
        "NQQE:11 FNOEVAN QE",
        "HAVG:O21H",
        "PNYY:(SE) FGEHPGHER SVER",
        "ANZR:ZVYYRE, WNZRF N",
        "VASB:FZBXR VA ERFVQRAPR",
        "K:REVXN YA");

    qbGrfg("G28",
        "PNQ:475 ZVYYF TNC EQ;O213;8289892954 QVFG: 27.37 sg;IREVMBA;(SE)GERR QBJA;PRAGENY CNEX QE;SBHE BNXF QE",
        "NQQE:475 ZVYYF TNC EQ",
        "HAVG:O213",
        "PNYY:(SE)GERR QBJA",
        "K:PRAGENY CNEX QE & SBHE BNXF QE");

    qbGrfg("G29",
        "PNQ:862 PNAR PERRX EQ/PEBFF PERRX SNEZ EQ;O213;(SE)GERR QBJA",
        "NQQE:862 PNAR PERRX EQ & PEBFF PERRX SNEZ EQ",
        "ZNQQE:862 PNAR PERRX EQ",
        "HAVG:O213",
        "PNYY:(SE)GERR QBJA");

    qbGrfg("G30",
        "PNQ:29 UVTUOEVQTR KVAT;TRARENY SN;QRRESVRYQ NFFVFGRQ YVIVAT;FVZCYRK;(SE) SVER NYNEZ;YNZORGU QE;FNYVFOHEL QE;10015610",
        "NQQE:29 UVTUOEVQTR KVAT",
        "PNYY:(SE) SVER NYNEZ",
        "VASB:TRARENY SN / QRRESVRYQ NFFVFGRQ YVIVAT / FVZCYRK",
        "K:YNZORGU QE & FNYVFOHEL QE",
        "VQ:10015610");

    qbGrfg("G31",
        "PNQ:226-O GNZCN PVE;O21;IREVMBA;URZBEEUNTR / YNPRENGVBA;JRFGBA EQ;JRFGBA EQ",
        "NQQE:226-O GNZCN PVE",
        "ZNQQE:226 GNZCN PVE",
        "HAVG:O21",
        "PNYY:URZBEEUNTR / YNPRENGVBA",
        "K:JRFGBA EQ & JRFGBA EQ");

    qbGrfg("G32",
        "PNQ:35 NVECBEG EQ;PBZ. YVSR PRAGRE;NEQRA FRIRAGU QNL NQIRAGVFG;QNAVRYF;(SE) SVER NYNEZ;BYQ FUBNYF EQ;JRYYVATGBA QE;10015618",
        "NQQE:35 NVECBEG EQ",
        "PNYY:(SE) SVER NYNEZ",
        "VASB:PBZ. YVSR PRAGRE / NEQRA FRIRAGU QNL NQIRAGVFG / QNAVRYF",
        "K:BYQ FUBNYF EQ & JRYYVATGBA QE",
        "VQ:10015618");

    qbGrfg("G33",
        "PNQ:20 TYRAA OEVQTR EQ;O21;8286990135;UHOORYY;UNLARF;(SE) SVER NYNEZ;URAQREFBAIVYYR EQ;JNYQRA QE",
        "NQQE:20 TYRAA OEVQTR EQ",
        "HAVG:O21",
        "PNYY:(SE) SVER NYNEZ",
        "CUBAR:8286990135",
        "VASB:UHOORYY / UNLARF",
        "K:URAQREFBAIVYYR EQ & JNYQRA QE");

    qbGrfg("G34",
        "PNQ:4 JNYQRA EVQTR QE;TRARENY NYNEZ;FVZCYRK;(SE) SVER NYNEZ;URAQREFBAIVYYR EQ;10015640",
        "NQQE:4 JNYQRA EVQTR QE",
        "PNYY:(SE) SVER NYNEZ",
        "VASB:TRARENY NYNEZ / FVZCYRK",
        "K:URAQREFBAIVYYR EQ",
        "VQ:10015640");

    qbGrfg("G35",
        "PNQ:50 CVARUHEFG PVE;O21;TRARENY NYNEZ;TYRA NEQRA RYRZRAGNEL FPUBBY;FVZCYRK;(SE) SVER NYNEZ;FNVAG WBUAF FG",
        "NQQE:50 CVARUHEFG PVE",
        "HAVG:O21",
        "PNYY:(SE) SVER NYNEZ",
        "VASB:TRARENY NYNEZ / TYRA NEQRA RYRZRAGNEL FPUBBY / FVZCYRK",
        "K:FNVAG WBUAF FG");

    qbGrfg("G36",
        "PNQ:1 URAQREFBA PBHAGL UJL;O21;710 YVAQFRL YBBC EQ;(SE) ZHGHNY NVQ;URAQREFBAIVYYR EQ",
        "NQQE:1 URAQREFBA PBHAGL UJL",
        "HAVG:O21",
        "PNYY:(SE) ZHGHNY NVQ",
        "VASB:710 YVAQFRL YBBC EQ",
        "K:URAQREFBAIVYYR EQ");

    qbGrfg("G37",
        "PNQ:202 FBHGUJNL TNEQRA EQ;O21;SNYYF;FJRRGRA PERRX EQ",
        "NQQE:202 FBHGUJNL TNEQRA EQ",
        "HAVG:O21",
        "PNYY:SNYYF",
        "K:FJRRGRA PERRX EQ");

    qbGrfg("G38",
        "PNQ:1845 OERINEQ EQ;O212;YHAPUEBBZ;PCH VAP;PBAIHYFVBAF / FRVMHERF;PBZZREPR JNL;CYNGVAHZ PG",
        "NQQE:1845 OERINEQ EQ",
        "HAVG:O212",
        "PNYY:PBAIHYFVBAF / FRVMHERF",
        "VASB:YHAPUEBBZ / PCH VAP",
        "K:PBZZREPR JNL & CYNGVAHZ PG");

    qbGrfg("G39",
        "PNQ:50-OYX PBAPBEQ EQ;O213;NFFG FGENAQRQ ZBGBEVFG;ENVARL, NNEBA;(SE) FREIVPR NAL GLCR;YNHERYGBA YA;JNYFU GEPR",
        "NQQE:50-OYX PBAPBEQ EQ",
        "ZNQQE:50 PBAPBEQ EQ",
        "HAVG:O213",
        "PNYY:(SE) FREIVPR NAL GLCR",
        "ANZR:ENVARL, NNEBA",
        "VASB:NFFG FGENAQRQ ZBGBEVFG",
        "K:YNHERYGBA YA & JNYFU GEPR");

    qbGrfg("G40",
        "PNQ:2251 URAQREFBAIVYYR EQ;O21;ZBHAGNVA RARETL;NOQBZVANY CNVAF / CEBOYRZF;SBERFG YA F;EBLNY CVARF QE",
        "NQQE:2251 URAQREFBAIVYYR EQ",
        "HAVG:O21",
        "PNYY:NOQBZVANY CNVAF / CEBOYRZF",
        "VASB:ZBHAGNVA RARETL",
        "K:SBERFG YA F & EBLNY CVARF QE");

    qbGrfg("G41",
        "PNQ:331 PRQNE YA;O21;FJNVA, W JRNIRE;QVNORGVP CEBOYRZF;ZNCYR PG;ZBFF YA",
        "NQQE:331 PRQNE YA",
        "HAVG:O21",
        "PNYY:QVNORGVP CEBOYRZF",
        "ANZR:FJNVA, W JRNIRE",
        "K:ZNCYR PG & ZBFF YA");

    qbGrfg("G42",
        "PNQ:25 BYQ FUBNYF EQ;FVZCYRK;(SE) SVER NYNEZ;QBJAVAT QE;TYRAA OEVQTR EQ;10015691",
        "NQQE:25 BYQ FUBNYF EQ",
        "PNYY:(SE) SVER NYNEZ",
        "VASB:FVZCYRK",
        "K:QBJAVAT QE & TYRAA OEVQTR EQ",
        "VQ:10015691");

    qbGrfg("G43",
        "PNQ:277 ZVYYF TNC EQ;O213;FZBXR QRGRPGBE;PCV;(SE) SVER NYNEZ;CVAAREF PBIR EQ;FHEERL EHA",
        "NQQE:277 ZVYYF TNC EQ",
        "HAVG:O213",
        "PNYY:(SE) SVER NYNEZ",
        "VASB:FZBXR QRGRPGBE / PCV",
        "K:CVAAREF PBIR EQ & FHEERL EHA");

    qbGrfg("G44",
        "PNQ:156 YBJRE PUEVFG FPUBBY EQ/ONYQJVA EQ;O213;IREVMBA;(M)ZBGBE IRU NPPVQRAG HAXABJA",
        "NQQE:156 YBJRE PUEVFG FPUBBY EQ & ONYQJVA EQ",
        "ZNQQE:156 YBJRE PUEVFG FPUBBY EQ",
        "HAVG:O213",
        "PNYY:(M)ZBGBE IRU NPPVQRAG HAXABJA");

    qbGrfg("G45",
        "PNQ:280 ONYY TNC EQ;O212;NFFVFG EGF;WRSS NG SVTUG JNGPU;(SE) FREIVPR NAL GLCR;YNXBGN GEY;OERINEQ EQ",
        "NQQE:280 ONYY TNC EQ",
        "HAVG:O212",
        "PNYY:(SE) FREIVPR NAL GLCR",
        "VASB:NFFVFG EGF / WRSS NG SVTUG JNGPU",
        "K:YNXBGN GEY & OERINEQ EQ");

    qbGrfg("G46",
        "PNQ:2607 URAQREFBAIVYYR EQ;O21;BBO TB TEBPREL;FJNA,WBUA;(SE) NFFVFG YNJ RASBEPRZRAG;F CNEX PG;JNGFBA EQ",
        "NQQE:2607 URAQREFBAIVYYR EQ",
        "HAVG:O21",
        "PNYY:(SE) NFFVFG YNJ RASBEPRZRAG",
        "VASB:BBO TB TEBPREL",
        "ANZR:FJNA,WBUA",
        "K:F CNEX PG & JNGFBA EQ");

    qbGrfg("G47",
        "PNQ:280 ONYY TNC EQ;O212;NFFVFG CNG HAYBNQVAT;EGF;(SE) FREIVPR NAL GLCR;YNXBGN GEY;OERINEQ EQ",
        "NQQE:280 ONYY TNC EQ",
        "HAVG:O212",
        "PNYY:(SE) FREIVPR NAL GLCR",
        "VASB:NFFVFG CNG HAYBNQVAT / EGF",
        "K:YNXBGN GEY & OERINEQ EQ");

    qbGrfg("G48",
        "PNQ:100-OYX YRQORGGRE EQ;O21H;(M)ZBGBE IRU NPPVQRAG HAXABJA;YNEX UY;PNIR YA",
        "NQQE:100-OYX YRQORGGRE EQ",
        "ZNQQE:100 YRQORGGRE EQ",
        "HAVG:O21H",
        "PNYY:(M)ZBGBE IRU NPPVQRAG HAXABJA",
        "VASB:YNEX UY",
        "K:PNIR YA");

    qbGrfg("G49",
        "PNQ:14 SBHE BNXF QE;O213;(SE) FGEHPGHER SVER;ZVYYF TNC EQ",
        "NQQE:14 SBHE BNXF QE",
        "HAVG:O213",
        "PNYY:(SE) FGEHPGHER SVER",
        "K:ZVYYF TNC EQ");

    qbGrfg("G50",
        "PNQ:75 JUVGR CVAR QE;O213;JNGRE URNGRE PNHTUG BA SVER;(SE) VAIRFGVTNGVBA;ZNCYR FG;GEBL UVYY QE",
        "NQQE:75 JUVGR CVAR QE",
        "HAVG:O213",
        "PNYY:JNGRE URNGRE PNHTUG BA SVER / (SE) VAIRFGVTNGVBA",
        "K:ZNCYR FG & GEBL UVYY QE");

    qbGrfg("G51",
        "PNQ:37 SBKOREEL QE;O21;NFVFG JVGU JNGRE FUHG BSS;(SE) FREIVPR NAL GLCR;ARJ EBPXJBBQ EQ;FCEVAT UVYY QE",
        "NQQE:37 SBKOREEL QE",
        "HAVG:O21",
        "PNYY:(SE) FREIVPR NAL GLCR",
        "VASB:NFVFG JVGU JNGRE FUHG BSS",
        "K:ARJ EBPXJBBQ EQ & FCEVAT UVYY QE");

    qbGrfg("G52",
        "PNQ:503 NIREL PERRX EQ;O21H;NFFVFG FHOW HC;ZPPYHER,EBANYQ;(SE) FREIVPR NAL GLCR;ARJZNA PBIR EQ;BJRAOL YA",
        "NQQE:503 NIREL PERRX EQ",
        "HAVG:O21H",
        "PNYY:(SE) FREIVPR NAL GLCR",
        "VASB:NFFVFG FHOW HC",
        "ANZR:ZPPYHER,EBANYQ",
        "K:ARJZNA PBIR EQ & BJRAOL YA");

    qbGrfg("G53",
        "PNQ:32 UBYYL NPERF YA;O212;(SE) FREIVPR NAL GLCR;OERINEQ EQ",
        "NQQE:32 UBYYL NPERF YA",
        "HAVG:O212",
        "PNYY:(SE) FREIVPR NAL GLCR",
        "K:OERINEQ EQ");

    qbGrfg("G54",
        "PNQ:162 PNEBYVAN OYHR OVEQ YBBC;O212;PYBFR,QNA & ZNEVR;HAXABJA CEBOYRZ;NFUYRL JBBQF QE",
        "NQQE:162 PNEBYVAN OYHR OVEQ YBBC",
        "HAVG:O212",
        "PNYY:HAXABJA CEBOYRZ",
        "ANZR:PYBFR,QNA & ZNEVR",
        "K:NFUYRL JBBQF QE");

    qbGrfg("G55",
        "PNQ:600 ONEERGG YA;NQZVA BSSVPRF;TVIRAF RFGNGR URNYGU PRAGRE;TVIRAF RFGNGRF - URNYGU PRAGRE;(SE) SVER NYNEZ;JRFYRL QE;URZYBPX QE;11000026",
        "NQQE:600 ONEERGG YA",
        "PNYY:(SE) SVER NYNEZ",
        "VASB:NQZVA BSSVPRF / TVIRAF RFGNGR URNYGU PRAGRE / TVIRAF RFGNGRF - URNYGU PRAGRE",
        "K:JRFYRL QE & URZYBPX QE",
        "VQ:11000026");

    qbGrfg("G56",
        "PNQ:1310 SNAAVAT OEVQTR EQ;RYRPGEBYHK;NQG;(SE) SVER NYNEZ;HAQREJBBQ EQ;ARJ NVECBEG EQ;10015794",
        "NQQE:1310 SNAAVAT OEVQTR EQ",
        "PNYY:(SE) SVER NYNEZ",
        "VASB:RYRPGEBYHK / NQG",
        "K:HAQREJBBQ EQ & ARJ NVECBEG EQ",
        "VQ:10015794");

    qbGrfg("G57",
        "PNQ:1301 SNAAVAT OEVQTR EQ;O21;FGNAQOL;JAP NTEVPHYGHENY PRAGRE;(SE) FREIVPR NAL GLCR;HAQREJBBQ EQ;ARJ NVECBEG EQ",
        "NQQE:1301 SNAAVAT OEVQTR EQ",
        "HAVG:O21",
        "PNYY:(SE) FREIVPR NAL GLCR",
        "VASB:FGNAQOL / JAP NTEVPHYGHENY PRAGRE",
        "K:HAQREJBBQ EQ & ARJ NVECBEG EQ");

    qbGrfg("G58",
        "PNQ:208 ZVYYF TNC EQ;O213;PURPX B2 BA GBQYRE;(SE) FREIVPR NAL GLCR;FBHGUFVQR IVYYNTR QE;CVAAREF PBIR EQ",
        "NQQE:208 ZVYYF TNC EQ",
        "HAVG:O213",
        "PNYY:(SE) FREIVPR NAL GLCR",
        "VASB:PURPX B2 BA GBQYRE",
        "K:FBHGUFVQR IVYYNTR QE & CVAAREF PBIR EQ");

    qbGrfg("G59",
        "PNQ:9 FUNQL BNX YA;O21H;NFFVFG JVGU  FZBXR QRGRPGBE;FCEVAG CPF;(SE) FREIVPR NAL GLCR;OERINEQ EQ",
        "NQQE:9 FUNQL BNX YA",
        "HAVG:O21H",
        "PNYY:(SE) FREIVPR NAL GLCR",
        "VASB:NFFVFG JVGU  FZBXR QRGRPGBE",
        "K:OERINEQ EQ");

    qbGrfg("G60",
        "PNQ:210 FHZZRETYRA QE;O212;PNAABA, TYRAQN;HAPBAFPVBHF/ SNVAGVAT;PNFGYREBPX QE;QBAALOEBBX QE",
        "NQQE:210 FHZZRETYRA QE",
        "HAVG:O212",
        "PNYY:HAPBAFPVBHF/ SNVAGVAT",
        "ANZR:PNAABA, TYRAQN",
        "K:PNFGYREBPX QE & QBAALOEBBX QE");

    qbGrfg("G61",
        "PNQ:615 CBYR PERNFZNA EQ;O212;FVZF, ORGGL;OERNGUVAT CEBOYRZF;UBYYL YA;UNLRF TERRA EQ",
        "NQQE:615 CBYR PERNFZNA EQ",
        "HAVG:O212",
        "PNYY:OERNGUVAT CEBOYRZF",
        "ANZR:FVZF, ORGGL",
        "K:UBYYL YA & UNLRF TERRA EQ");

    qbGrfg("G62",
        "PNQ:2533 URAQREFBAIVYYR EQ;O21;NCG 102;PERFPRAG IVRJ;PERFPRAG IVRJ;HAPBAFPVBHF/ SNVAGVAT;HCCRE YNHERY QE;ARFOVGG QE",
        "NQQE:2533 URAQREFBAIVYYR EQ",
        "HAVG:O21",
        "NCG:102",
        "PNYY:HAPBAFPVBHF/ SNVAGVAT",
        "VASB:PERFPRAG IVRJ / PERFPRAG IVRJ",
        "K:HCCRE YNHERY QE & ARFOVGG QE");

    qbGrfg("G63",
        "PNQ:347 V26 R;O21;8282169743;G-Zbovyr HFN;(M)ZBGBE IRU NPPVQRAG VAWHEL;V26 R GB YBAT FUBNYF EQ",
        "NQQE:347 V26 R",
        "ZNQQE:347 V 26 R",
        "HAVG:O21",
        "PNYY:(M)ZBGBE IRU NPPVQRAG VAWHEL",
        "CUBAR:8282169743",
        "VASB:V26 R GB YBAT FUBNYF EQ");

    qbGrfg("G64",
        "PNQ:103 NCCNYNPUVNA OYIQ;O212;EZ 309;URNGURE TYRA NG NEQRA JBBQF;URNGURE TYRA NG NEQRAJBBQF;OERNGUVAT CEBOYRZF;EBPXL ZBHAGNVA JNL",
        "NQQE:103 NCCNYNPUVNA OYIQ",
        "HAVG:O212",
        "PNYY:OERNGUVAT CEBOYRZF",
        "VASB:EZ 309 / URNGURE TYRA NG NEQRA JBBQF / URNGURE TYRA NG NEQRAJBBQF",
        "K:EBPXL ZBHAGNVA JNL");

    qbGrfg("G65",
        "PNQ:2533 URAQREFBAIVYYR EQ;O21;EZ 242;PERFPRAG IVRJ;PERFPRAG IVRJ;HAPBAFPVBHF/ SNVAGVAT;HCCRE YNHERY QE;ARFOVGG QE",
        "NQQE:2533 URAQREFBAIVYYR EQ",
        "HAVG:O21",
        "PNYY:HAPBAFPVBHF/ SNVAGVAT",
        "VASB:EZ 242 / PERFPRAG IVRJ / PERFPRAG IVRJ",
        "K:HCCRE YNHERY QE & ARFOVGG QE");

    qbGrfg("G66",
        "PNQ:122 RQTRJBBQ QE;OBGFSBEQ , ONEOREN;YVSR-YVAR;SNYYF;QBJAVAT QE;QBJAVAT QE;11000163",
        "NQQE:122 RQTRJBBQ QE",
        "PNYY:SNYYF",
        "ANZR:OBGFSBEQ , ONEOREN",
        "VASB:YVSR-YVAR",
        "K:QBJAVAT QE & QBJAVAT QE",
        "VQ:11000163");

    qbGrfg("G67",
        "PNQ:342 QBAALOEBBX QE;O212;FZRYY BS TNF VA GUR NERN;OBO NAQREFBA;(SE) VAIRFGVTNGVBA;NHOHEAQNYR QE",
        "NQQE:342 QBAALOEBBX QE",
        "HAVG:O212",
        "PNYY:(SE) VAIRFGVTNGVBA",
        "VASB:FZRYY BS TNF VA GUR NERN / OBO NAQREFBA",
        "K:NHOHEAQNYR QE");

    qbGrfg("G68",
        "PNQ:2400 NCCNYNPUVNA OYIQ;O212;PYHOUBHFR QVAVAT EZ;NEQRAJBBQF - PYHO UBHFR;NEQRAJBBQF ERGVERZRAG PBZZHAVG;PUBXVAT;EBPXL ZBHAGNVA JNL",
        "NQQE:2400 NCCNYNPUVNA OYIQ",
        "HAVG:O212",
        "PNYY:PUBXVAT",
        "VASB:PYHOUBHFR QVAVAT EZ / NEQRAJBBQF - PYHO UBHFR / NEQRAJBBQF ERGVERZRAG PBZZHAVG",
        "K:EBPXL ZBHAGNVA JNL");

    qbGrfg("G69",
        "PNQ:30 UHAGRE QE;O21H;FGEBXR;FYRRCL TNC EQ",
        "NQQE:30 UHAGRE QE",
        "HAVG:O21H",
        "PNYY:FGEBXR",
        "K:FYRRCL TNC EQ");

    qbGrfg("G70",
        "PNQ:202 FHZZRETYRA QE;O212;BARVYY FGRCURA NAQ YRFN;SNYYF;ORAG PERRX ENAPU EQ;PNFGYREBPX QE",
        "NQQE:202 FHZZRETYRA QE",
        "HAVG:O212",
        "PNYY:SNYYF",
        "VASB:BARVYY FGRCURA NAQ YRFN",
        "K:ORAG PERRX ENAPU EQ & PNFGYREBPX QE");

    qbGrfg("G71",
        "PNQ:424 ZVYYF TNC EQ;O213;THGVREERM, EBFRAQB;PURFG CNVA;JRFGBA EQ;OENR OHEA QE",
        "NQQE:424 ZVYYF TNC EQ",
        "HAVG:O213",
        "PNYY:PURFG CNVA",
        "ANZR:THGVREERM, EBFRAQB",
        "K:JRFGBA EQ & OENR OHEA QE");

    qbGrfg("G72",
        "PNQ:7 FNVAG NAQERJF EQ;O213;WRSSEVRF,QBA;SNYYF;PUVCCVAT TERRA QE;SBERFG EVQTR QE",
        "NQQE:7 FNVAG NAQERJF EQ",
        "HAVG:O213",
        "PNYY:SNYYF",
        "ANZR:WRSSEVRF,QBA",
        "K:PUVCCVAT TERRA QE & SBERFG EVQTR QE");

    qbGrfg("G73",
        "PNQ:13 ZPXRAAN EQ;ZNEFUNYYF;(SE) SVER NYNEZ;11000217",
        "NQQE:13 ZPXRAAN EQ",
        "PNYY:(SE) SVER NYNEZ",
        "VASB:ZNEFUNYYF",
        "VQ:11000217");

    qbGrfg("G74",
        "PNQ:12 OREYVAF IJ;O102;8287120800;IREVMBA;(SE) FGEHPGHER SVER;A YHGURE EQ",
        "NQQE:12 OREYVAF IJ",
        "HAVG:O102",
        "PNYY:(SE) FGEHPGHER SVER",
        "CUBAR:8287120800",
        "K:A YHGURE EQ");

    qbGrfg("G75",
        "PNQ:206 EBLNY CVARF QE;O21;GNLYBE, EBOREG R;OERNGUVAT CEBOYRZF;FJRRGRA PERRX EQ;NCCVNA JNL",
        "NQQE:206 EBLNY CVARF QE",
        "HAVG:O21",
        "PNYY:OERNGUVAT CEBOYRZF",
        "ANZR:GNLYBE, EBOREG R",
        "K:FJRRGRA PERRX EQ & NCCVNA JNL");

    qbGrfg("G76",
        "PNQ:10 ORAAVATGBA PG;O21;FZVGU, NAA & OVYY;URNEG CEBOYRZF;BIREYBBX EQ",
        "NQQE:10 ORAAVATGBA PG",
        "HAVG:O21",
        "PNYY:URNEG CEBOYRZF",
        "ANZR:FZVGU, NAA & OVYY",
        "K:BIREYBBX EQ");

    qbGrfg("G77",
        "PNQ:800 ZVYYF TNC EQ;O213;VAFVQR GUR FGBER;ZBYYLF ZNEXRG;ZBYYL`F ZNEXRG,;URNEG CEBOYRZF;PNAR PERRX EQ;CRAYRL EQ",
        "NQQE:800 ZVYYF TNC EQ",
        "HAVG:O213",
        "PNYY:URNEG CEBOYRZF",
        "VASB:VAFVQR GUR FGBER / ZBYYLF ZNEXRG",
        "ANZR:ZBYYL`F ZNEXRG,",
        "K:PNAR PERRX EQ & CRAYRL EQ");

    qbGrfg("G78",
        "PNQ:100 SERQREVPX YNJ BYZFGRQ JNL;O212;NEOBERGHZ;Ohapbzor Pbhagl;(M)ZBGBE IRU NPPVQRAG VAWHEL;TERRAUBHFR JNL",
        "NQQE:100 SERQREVPX YNJ BYZFGRQ JNL",
        "HAVG:O212",
        "PNYY:(M)ZBGBE IRU NPPVQRAG VAWHEL",
        "VASB:NEOBERGHZ / Ohapbzor Pbhagl",
        "K:TERRAUBHFR JNL");

    qbGrfg("G79",
        "PNQ:280 ONYY TNC EQ;O212;NFFVFG EGF YBNQVAT N CNGVRAG;(SE) FREIVPR NAL GLCR;YNXBGN GEY;OERINEQ EQ",
        "NQQE:280 ONYY TNC EQ",
        "HAVG:O212",
        "PNYY:(SE) FREIVPR NAL GLCR",
        "VASB:NFFVFG EGF YBNQVAT N CNGVRAG",
        "K:YNXBGN GEY & OERINEQ EQ");

    qbGrfg("G80",
        "PNQ:53 QEVSGFGBAR PVE;O212;JRRENFVEV,QBA;(SE) UNMNEQBHF ZNGREVNY;EVIREPERFG OYIQ;EVIREPERFG OYIQ",
        "NQQE:53 QEVSGFGBAR PVE",
        "HAVG:O212",
        "PNYY:(SE) UNMNEQBHF ZNGREVNY",
        "ANZR:JRRENFVEV,QBA",
        "K:EVIREPERFG OYIQ & EVIREPERFG OYIQ");

    qbGrfg("G81",
        "PNQ:2 ORAG BNX YA;FVMRZBER, R;(SE) FGEHPGHER SVER;BIREYBBX EQ;QRREUNIRA YA;11000280",
        "NQQE:2 ORAG BNX YA",
        "PNYY:(SE) FGEHPGHER SVER",
        "ANZR:FVMRZBER, R",
        "K:BIREYBBX EQ & QRREUNIRA YA",
        "VQ:11000280");

    qbGrfg("G82",
        "PNQ:25 BYQ FUBNYF EQ;JNGRE SYBJ MBAR Z-123;SYVAG TEBHC;FVZCYRK;(SE) SVER NYNEZ;QBJAVAT QE;TYRAA OEVQTR EQ;11000292",
        "NQQE:25 BYQ FUBNYF EQ",
        "PNYY:(SE) SVER NYNEZ",
        "VASB:JNGRE SYBJ MBAR Z-123 / SYVAG TEBHC / FVZCYRK",
        "K:QBJAVAT QE & TYRAA OEVQTR EQ",
        "VQ:11000292");

    qbGrfg("G83",
        "PNQ:49 UVTUOEVQTR KVAT;EZ 4101/NFFVFG FHO. BSS SYBBE;QRRESVRYQ FXVYYRQ PNER;QRRESVRYQ ERGVERZRAG;(SE) FREIVPR NAL GLCR;YNZORGU QE;FNYVFOHEL QE;11000293",
        "NQQE:49 UVTUOEVQTR KVAT",
        "PNYY:EZ 4101/NFFVFG FHO. BSS SYBBE / (SE) FREIVPR NAL GLCR",
        "VASB:QRRESVRYQ FXVYYRQ PNER / QRRESVRYQ ERGVERZRAG",
        "K:YNZORGU QE & FNYVFOHEL QE",
        "VQ:11000293");

    qbGrfg("G84",
        "PNQ:100 IVFGN OYIQ;O212;ALCEB;(M)ZBGBE IRU NPPVQRAG VAWHEL;OERINEQ EQ;GEVQRAG QE",
        "NQQE:100 IVFGN OYIQ",
        "HAVG:O212",
        "PNYY:(M)ZBGBE IRU NPPVQRAG VAWHEL",
        "VASB:ALCEB",
        "K:OERINEQ EQ & GEVQRAG QE");

    qbGrfg("G85",
        "PNQ:607 CNEX FBHGU OYIQ;O212;(SE) FREIVPR NAL GLCR;OERINEQ EQ;CNEX FBHGU PG",
        "NQQE:607 CNEX FBHGU OYIQ",
        "HAVG:O212",
        "PNYY:(SE) FREIVPR NAL GLCR",
        "K:OERINEQ EQ & CNEX FBHGU PG");

    qbGrfg("G86",
        "PNQ:2533 URAQREFBAIVYYR EQ;O21;EZ 321;PERFPRAG IVRJ;PERFPRAG IVRJ;SNYYF;HCCRE YNHERY QE;ARFOVGG QE",
        "NQQE:2533 URAQREFBAIVYYR EQ",
        "HAVG:O21",
        "PNYY:SNYYF",
        "VASB:EZ 321 / PERFPRAG IVRJ / PERFPRAG IVRJ",
        "K:HCCRE YNHERY QE & ARFOVGG QE");

    qbGrfg("G87",
        "PNQ:92 SNVE BNXF EQ;O21;YVSRYVAR;HAXABJA CEBOYRZ;EBLNY BNXF EQ;A SNVE BNXF EQ",
        "NQQE:92 SNVE BNXF EQ",
        "HAVG:O21",
        "PNYY:HAXABJA CEBOYRZ",
        "VASB:YVSRYVAR",
        "K:EBLNY BNXF EQ & A SNVE BNXF EQ");

    qbGrfg("G88",
        "PNQ:4 UVPXBEL GERR EQ;O11;IREVMBA;(M)ZBGBE IRU NPPVQRAG VAWHEL;YBJRE TENFFL OENAPU EQ;WHYVNAAR CY",
        "NQQE:4 UVPXBEL GERR EQ",
        "HAVG:O11",
        "PNYY:(M)ZBGBE IRU NPPVQRAG VAWHEL",
        "K:YBJRE TENFFL OENAPU EQ & WHYVNAAR CY");

    qbGrfg("G89",
        "F:PNQ:111 BYQ JRNIREIVYYR EQ;O20;OYNMRE, EHGU;HAPBAFPVBHF/ SNVAGVAT Z:",
        "NQQE:111 BYQ JRNIREIVYYR EQ",
        "HAVG:O20",
        "PNYY:HAPBAFPVBHF/ SNVAGVAT",
        "ANZR:OYNMRE, EHGU");

    qbGrfg("G90",
        "F: Z:PNQ:656 A SBEX EQ;O15;7654131974 QVFG: 231.30 SG;Ohapbzor Pbhagl;PURFG CNVA",
        "NQQE:656 A SBEX EQ",
        "HAVG:O15",
        "PNYY:PURFG CNVA",
        "VASB:Ohapbzor Pbhagl");

    qbGrfg("G91",
        "F: Z:PNQ:503 CNVAG SBEX EQ;O15;8287780508;Ohapbzor Pbhagl;FGEBXR;EBPXL YA;UNEJBBQ EQ",
        "NQQE:503 CNVAG SBEX EQ",
        "HAVG:O15",
        "PNYY:FGEBXR",
        "CUBAR:8287780508",
        "VASB:Ohapbzor Pbhagl",
        "K:EBPXL YA & UNEJBBQ EQ");

    qbGrfg("G92",
        "PNQ:110-1/2 FHZZRE FG;O6;IREVMBA;(SE) FGEHPGHER SVER;CNEXRE QE;NYRKNAQRE NIR",
        "NQQE:110-1/2 FHZZRE FG",
        "ZNQQE:110 FHZZRE FG",
        "HAVG:O6",
        "PNYY:(SE) FGEHPGHER SVER",
        "K:CNEXRE QE & NYRKNAQRE NIR");

    qbGrfg("G93",
        "PNQ:34 JNYY FG;SF1;MBAR TRARENY SVER;FRYS URYC PERQVG HAVBA;FVZCYRK;(SE) SVER NYNEZ;ONGGREL CNEX NIR;BGVF FG;12002186",
        "NQQE:34 JNYY FG",
        "FEP:SF1",
        "PNYY:MBAR TRARENY SVER / (SE) SVER NYNEZ",
        "VASB:FRYS URYC PERQVG HAVBA / FVZCYRK",
        "K:ONGGREL CNEX NIR & BGVF FG",
        "VQ:12002186");
    
  }
  
  @Grfg
  choyvp ibvq grfgNpgvir911N() {

    qbGrfg("G1",
        "[] PNQ:329 ZREEVZBA NIR;O8;OEVNA PRAGRE;GBGNY ERANY PNER;FVPX CREFBA;TNEEVFBA EQ;FGBARL XABO EQ\e\a\a",
        "NQQE:329 ZREEVZBA NIR",
        "HAVG:O8",
        "PNYY:FVPX CREFBA",
        "VASB:OEVNA PRAGRE / GBGNY ERANY PNER",
        "K:TNEEVFBA EQ & FGBARL XABO EQ");

    qbGrfg("G2",
        "[] PNQ:120-OYX RQTRJBBQ EQ F;SF5;FCEVAG ARKGRY-PQZN;(SE)GERR QBJA;YR NA UHEFG EQ;PVZNEEBA QE;12011446\e\a\a",
        "NQQE:120-OYX RQTRJBBQ EQ F",
        "ZNQQE:120 RQTRJBBQ EQ F",
        "FEP:SF5",
        "PNYY:(SE)GERR QBJA",
        "K:YR NA UHEFG EQ & PVZNEEBA QE",
        "VQ:12011446");

    qbGrfg("G3",
        "[] PNQ:94-1/2 FNEQVF EQ;O10;URNGBA,NAVGN;FVPX CREFBA;ENZRL UVYY QE;SBEQOEBBX EQ;12011447\e\a\a",
        "NQQE:94-1/2 FNEQVF EQ",
        "ZNQQE:94 FNEQVF EQ",
        "HAVG:O10",
        "PNYY:FVPX CREFBA",
        "ANZR:URNGBA,NAVGN",
        "K:ENZRL UVYY QE & SBEQOEBBX EQ",
        "VQ:12011447");

    qbGrfg("G4",
        "[] PNQ:SLV: ;31 PUNEYBGGR FG/JBBQSVA CY;SF1;8282169182;G-ZBOVYR HFN;(M)ZBGBE IRU NPPVQRAG HAXABJA;12011448\e\a\a",
        "NQQE:31 PUNEYBGGR FG & JBBQSVA CY",
        "ZNQQE:31 PUNEYBGGR FG",
        "FEP:SF1",
        "PNYY:(M)ZBGBE IRU NPPVQRAG HAXABJA",
        "CUBAR:8282169182",
        "VQ:12011448");

    qbGrfg("G5",
        "[] PNQ:31 PUNEYBGGR FG/JBBQSVA CY;SF1;8282169182;G-ZBOVYR HFN;(M)ZBGBE IRU NPPVQRAG HAXABJA;12011448\e\a\a",
        "NQQE:31 PUNEYBGGR FG & JBBQSVA CY",
        "ZNQQE:31 PUNEYBGGR FG",
        "FEP:SF1",
        "PNYY:(M)ZBGBE IRU NPPVQRAG HAXABJA",
        "CUBAR:8282169182",
        "VQ:12011448");

    qbGrfg("G6",
        "[] PNQ:Punatrq Angher sebz (M)ZBGBE IRU NPPVQRAG HAXABJA gb (M)ZBGBE IRU NPPVQRAG VAWHEL;31 PUNEYBGGR FG/JBBQSVA CY; NF01;8282169182\e\a\a",
        "NQQE:31 PUNEYBGGR FG & JBBQSVA CY",
        "ZNQQE:31 PUNEYBGGR FG",
        "HAVG:NF01",
        "PNYY:(M)ZBGBE IRU NPPVQRAG VAWHEL",
        "CUBAR:8282169182");

    qbGrfg("G7",
        "[] PNQ:SLV: ;20 FXLIVRJ GRE;SF3;NFFVFG FHO HC VA SEBAG LNEQ;PUVYQERFF, Z Y;(SE) FREIVPR NAL GLCR;A YBHVFVNAN NIR;FGNEZBHAG QE;12011449\e\a\a",
        "NQQE:20 FXLIVRJ GRE",
        "FEP:SF3",
        "PNYY:(SE) FREIVPR NAL GLCR",
        "ANZR:PUVYQERFF, Z Y",
        "VASB:NFFVFG FHO HC VA SEBAG LNEQ",
        "K:A YBHVFVNAN NIR & FGNEZBHAG QE",
        "VQ:12011449");

    qbGrfg("G8",
        "[] PNQ:20 FXLIVRJ GRE;SF3;NFFVFG FHO HC VA SEBAG LNEQ;PUVYQERFF, Z Y;(SE) FREIVPR NAL GLCR;A YBHVFVNAN NIR;FGNEZBHAG QE;12011449\e\a\a",
        "NQQE:20 FXLIVRJ GRE",
        "FEP:SF3",
        "PNYY:(SE) FREIVPR NAL GLCR",
        "ANZR:PUVYQERFF, Z Y",
        "VASB:NFFVFG FHO HC VA SEBAG LNEQ",
        "K:A YBHVFVNAN NIR & FGNEZBHAG QE",
        "VQ:12011449");

    qbGrfg("G9",
        "[] PNQ:780 URAQREFBAIVYYR EQ;SF5;C-YBG;VATYRF;VATYRF ZNEXRGF;SNYYF;WRSSERFF NIR;OHFORR EQ;12011450\e\a\a",
        "NQQE:780 URAQREFBAIVYYR EQ",
        "FEP:SF5",
        "PNYY:SNYYF",
        "VASB:C-YBG / VATYRF / VATYRF ZNEXRGF",
        "K:WRSSERFF NIR & OHFORR EQ",
        "VQ:12011450");

    qbGrfg("G10",
        "[] PNQ:1345 URAQREFBAIVYYR EQ;SF5;NG GUR TLZ;PNEBYVAN QNL FPUBBY;HF Pryyhyne;GENZNGVP VAWHEVRF;EVQTRSVRYQ CY;OYHR EVQTR CXJL;12011451\e\a\a",
        "NQQE:1345 URAQREFBAIVYYR EQ",
        "FEP:SF5",
        "PNYY:GENZNGVP VAWHEVRF",
        "VASB:NG GUR TLZ / PNEBYVAN QNL FPUBBY",
        "K:EVQTRSVRYQ CY & OYHR EVQTR CXJL",
        "VQ:12011451");

    qbGrfg("G11",
        "[] PNQ:31 FPURAPX CXJL;SF4;8287776867;ERV ERPERNGVBANY RDHVCZRAG;IREVMBA;GENZNGVP VAWHEVRF;R FPURAPX PERF;GBJA FDHNER OYIQ;12011452\e\a\a",
        "NQQE:31 FPURAPX CXJL",
        "FEP:SF4",
        "PNYY:GENZNGVP VAWHEVRF",
        "CUBAR:8287776867",
        "VASB:ERV ERPERNGVBANY RDHVCZRAG / R FPURAPX PERF",
        "K:GBJA FDHNER OYIQ",
        "VQ:12011452");

    qbGrfg("G12",
        "[] PNQ:58-N XYBAQLXR NIR;SF1;YVAX GB YVSR;HAXABJA CEBOYRZ;XYBAQLXR CY;ZBAGSBEQ NIR;12011453\e\a\a",
        "NQQE:58-N XYBAQLXR NIR",
        "ZNQQE:58 XYBAQLXR NIR",
        "FEP:SF1",
        "PNYY:HAXABJA CEBOYRZ",
        "VASB:YVAX GB YVSR",
        "K:XYBAQLXR CY & ZBAGSBEQ NIR",
        "VQ:12011453");

    qbGrfg("G13",
        "[] PNQ:SLV: ;20 FXLIVRJ GRE;SF3;NFFVFG FHO HC;CBJRYY, NZOEBFR & TNVY;(SE) FREIVPR NAL GLCR;A YBHVFVNAN NIR;FGNEZBHAG QE;12011454\e\a\a",
        "NQQE:20 FXLIVRJ GRE",
        "FEP:SF3",
        "PNYY:(SE) FREIVPR NAL GLCR",
        "ANZR:CBJRYY, NZOEBFR & TNVY",
        "VASB:NFFVFG FHO HC",
        "K:A YBHVFVNAN NIR & FGNEZBHAG QE",
        "VQ:12011454");

    qbGrfg("G14",
        "[] PNQ:20 FXLIVRJ GRE;SF3;NFFVFG FHO HC;CBJRYY, NZOEBFR & TNVY;(SE) FREIVPR NAL GLCR;A YBHVFVNAN NIR;FGNEZBHAG QE;12011454\e\a\a",
        "NQQE:20 FXLIVRJ GRE",
        "FEP:SF3",
        "PNYY:(SE) FREIVPR NAL GLCR",
        "ANZR:CBJRYY, NZOEBFR & TNVY",
        "VASB:NFFVFG FHO HC",
        "K:A YBHVFVNAN NIR & FGNEZBHAG QE",
        "VQ:12011454");

    qbGrfg("G15",
        "[] PNQ:81-N XYBAQLXR NIR;SF1;HF Pryyhyne;SNYYF;XYBAQLXR CY;ZBAGSBEQ NIR;12011455\e\a\a",
        "NQQE:81-N XYBAQLXR NIR",
        "ZNQQE:81 XYBAQLXR NIR",
        "FEP:SF1",
        "PNYY:SNYYF",
        "K:XYBAQLXR CY & ZBAGSBEQ NIR",
        "VQ:12011455");

    qbGrfg("G16",
        "[] PNQ:79 NFURYNAQ NIR;SF1;UBG FCBG;136;NFFNHYG / FRKHNY NFFNHYG;CNGGBA NIR;UVYYVNEQ NIR;12011456\e\a\a",
        "NQQE:79 NFURYNAQ NIR",
        "FEP:SF1",
        "PNYY:NFFNHYG / FRKHNY NFFNHYG",
        "VASB:UBG FCBG / 136",
        "K:CNGGBA NIR & UVYYVNEQ NIR",
        "VQ:12011456");

    qbGrfg("G17",
        "[] PNQ:SLV: ;25 ENYRVTU EQ;SF9;NCG N;ERQSREA, NQEVRAAR;(SE) SVER NYNEZ;FPUBBY EQ R;YVAPBYA NIR;12012206\e\a\a",
        "NQQE:25 ENYRVTU EQ",
        "NCG:N",
        "FEP:SF9",
        "PNYY:(SE) SVER NYNEZ",
        "ANZR:ERQSREA, NQEVRAAR",
        "K:FPUBBY EQ R & YVAPBYA NIR",
        "VQ:12012206");

    qbGrfg("G18",
        "[] PNQ:9091 IREQR IVFGN PVE;SF9;SY4,SFDQ1,SZ10,SPNE3,SR2,SR8,SY8,SR9,SONG1,SONG3;NCG 5117;IREVMBA;(SE) FGEHPGHER SVER;EVIRE SBEQ CXJL;12012204\e\a\a",
        "NQQE:9091 IREQR IVFGN PVE",
        "NCG:5117",
        "FEP:SF9",
        "HAVG:SY4,SFDQ1,SZ10,SPNE3,SR2,SR8,SY8,SR9,SONG1,SONG3",
        "PNYY:(SE) FGEHPGHER SVER",
        "K:EVIRE SBEQ CXJL",
        "VQ:12012204");

    qbGrfg("G19",
        "[] PNQ:25 ENYRVTU EQ;SF9;SD5,SR1,SR4;NCG N;ERQSREA, NQEVRAAR;(SE) SVER NYNEZ;FPUBBY EQ R;YVAPBYA NIR;12012206\e\a\a",
        "NQQE:25 ENYRVTU EQ",
        "NCG:N",
        "FEP:SF9",
        "HAVG:SD5,SR1,SR4",
        "PNYY:(SE) SVER NYNEZ",
        "ANZR:ERQSREA, NQEVRAAR",
        "K:FPUBBY EQ R & YVAPBYA NIR",
        "VQ:12012206");

    qbGrfg("G20",
        "[] PNQ:9091 IREQR IVFGN PVE;SF9;SY4,SFDQ1,SZ10,SPNE3,SR2,SR8,SY8,SR9,SPUS4,SONG1,SONG3;NCG 5117;IREVMBA;(SE) FGEHPGHER SVER;EVIRE SBEQ CXJL;12012204\e\a\a",
        "NQQE:9091 IREQR IVFGN PVE",
        "NCG:5117",
        "FEP:SF9",
        "HAVG:SY4,SFDQ1,SZ10,SPNE3,SR2,SR8,SY8,SR9,SPUS4,SONG1,SONG3",
        "PNYY:(SE) FGEHPGHER SVER",
        "K:EVIRE SBEQ CXJL",
        "VQ:12012204");

    qbGrfg("G21",
        "[] PNQ:SLV: ;97 F YRKVATGBA NIR;SF1;SZ21;OHVYQVAT QNZNTR;PUHPXF JRYQVAT FREIVPR;SZ-21;(SE) VAIRFGVTNGVBA;NFGBA FG;UVYYVNEQ NIR\e\a\a",
        "NQQE:97 F YRKVATGBA NIR",
        "FEP:SF1",
        "HAVG:SZ21",
        "PNYY:OHVYQVAT QNZNTR / (SE) VAIRFGVTNGVBA",
        "VASB:PUHPXF JRYQVAT FREIVPR / SZ-21",
        "K:NFGBA FG & UVYYVNEQ NIR");

    qbGrfg("G22",
        "[] PNQ:173 SNLRGGRIVYYR FG;SF3;SR6;8287130209;IREVMBA;NOQBZVANY CNVAF / CEBOYRZF;GRKNF FG;BUVB FG;12012208\e\a\a",
        "NQQE:173 SNLRGGRIVYYR FG",
        "FEP:SF3",
        "HAVG:SR6",
        "PNYY:NOQBZVANY CNVAF / CEBOYRZF",
        "CUBAR:8287130209",
        "K:GRKNF FG & BUVB FG",
        "VQ:12012208");

    qbGrfg("G23",
        "[] PNQ:2 OEBNQJNL FG GB V240 J;SF1;SR1,SY1;HAXABJA CEBOYRZ;A YRKVATGBA NIR;V240 J;12012209\e\a\a",
        "NQQE:2 OEBNQJNL FG GB V240 J",
        "ZNQQE:2 OEBNQJNL FG GB V 240 J",
        "FEP:SF1",
        "HAVG:SR1,SY1",
        "PNYY:HAXABJA CEBOYRZ",
        "K:A YRKVATGBA NIR & V240 J",
        "VQ:12012209");

  }
  
  @Grfg
  choyvp ibvq grfgNpgvir911O() {

    qbGrfg("G1",
        "[] PNQ:557 QRNIREIVRJ EQ;O5;8282808178;FCEVAG ARKGRY-PQZN;ONPX CNVA (ABA-ERPRAG);YBIR VG YA;PNAQYRE XABO EQ\e\a\a",
        "NQQE:557 QRNIREIVRJ EQ",
        "HAVG:O5",
        "PNYY:ONPX CNVA (ABA-ERPRAG)",
        "CUBAR:8282808178",
        "K:YBIR VG YA & PNAQYRE XABO EQ");

    qbGrfg("G2",
        "[] PNQ:219 BYQ AP 20 UJL;O2;JNYFU,QRAVFR;FVPX CREFBA;FHA INYYRL QE;QNYR GURYZN ZRZBEVNY QE\e\a\a",
        "NQQE:219 BYQ AP 20 UJL",
        "ZNQQE:219 BYQ FGNGR 20",
        "HAVG:O2",
        "PNYY:FVPX CREFBA",
        "ANZR:JNYFU,QRAVFR",
        "K:FHA INYYRL QE & QNYR GURYZN ZRZBEVNY QE");

    qbGrfg("G3",
        "[] PNQ:101 YVBAF JNL;O2;EBBZ 124;ZNEWBEVR ZPPHAR PRAGRE;ZNEWBEVR ZPPHAR ZRZBEVNY PRAGR;NOQBZVANY CNVAF / CEBOYRZF;YVBARFF QE\e\a\a",
        "NQQE:101 YVBAF JNL",
        "HAVG:O2",
        "PNYY:NOQBZVANY CNVAF / CEBOYRZF",
        "VASB:EBBZ 124 / ZNEWBEVR ZPPHAR PRAGRE / ZNEWBEVR ZPPHAR ZRZBEVNY PRAGR",
        "K:YVBARFF QE");

    qbGrfg("G4",
        "[] PNQ:78 JRNIRE OYIQ;O2;EBBZ 310 // ORQ - 2;OEVNA PRAGRE;OEVNA PRAGRE;FVPX CREFBA;PYVAGBA FG;V26 J GB JRNIRE OYIQ\e\a\a",
        "NQQE:78 JRNIRE OYIQ",
        "HAVG:O2",
        "PNYY:EBBZ 310 // ORQ - 2 / FVPX CREFBA",
        "VASB:OEVNA PRAGRE / OEVNA PRAGRE / V26 J GB JRNIRE OYIQ",
        "K:PYVAGBA FG");

    qbGrfg("G5",
        "[] PNQ:91 F GHAARY EQ;SF9;QVFG: 14.41 SG;JNYTERRAF;IREVMBA JVERYRFF;(M)ZBGBE IRU NPPVQRAG VAWHEL;ARJ UNJ PERRX YA;FJNAANABN EVIRE EQ\e\a\a",
        "NQQE:91 F GHAARY EQ",
        "FEP:SF9",
        "PNYY:(M)ZBGBE IRU NPPVQRAG VAWHEL",
        "VASB:JNYTERRAF",
        "K:ARJ UNJ PERRX YA & FJNAANABN EVIRE EQ");

    qbGrfg("G6",
        "[] PNQ:380 OERINEQ EQ;O2;EBBZ 312 // ORQ -N;NFGBA CNEX URNYGU PNER;QVKBA UHTURF - NFGBA CNEX URNY;OERNGUVAT CEBOYRZF;UVTU PBHEG RAGENAPR;FURYOHEAR EQ\e\a\a",
        "NQQE:380 OERINEQ EQ",
        "HAVG:O2",
        "PNYY:EBBZ 312 // ORQ -N / OERNGUVAT CEBOYRZF",
        "VASB:NFGBA CNEX URNYGU PNER / QVKBA UHTURF - NFGBA CNEX URNY / UVTU PBHEG RAGENAPR",
        "K:FURYOHEAR EQ");

    qbGrfg("G7",
        "[] PNQ:3667 FJRRGRA PERRX EQ;O21;NCG E-1;ULQR, OEVNA;FVPX CREFBA;PUREEL FG;EBLNY CVARF QE\e\a\a",
        "NQQE:3667 FJRRGRA PERRX EQ",
        "NCG:E-1",
        "HAVG:O21",
        "PNYY:FVPX CREFBA",
        "ANZR:ULQR, OEVNA",
        "K:PUREEL FG & EBLNY CVARF QE");

    qbGrfg("G8",
        "[] PNQ:31 R FGNEARF PBIR EQ;SF10;OENMVYYR, O R;FVPX CREFBA;P Z QBNA YA;ZLEN CY\e\a\a",
        "NQQE:31 R FGNEARF PBIR EQ",
        "FEP:SF10",
        "PNYY:FVPX CREFBA",
        "ANZR:OENMVYYR, O R",
        "K:P Z QBNA YA & ZLEN CY");

    qbGrfg("G9",
        "[] PNQ:210 WBUAFGBA OYIQ;SF6;YBG 19;GBJA NAQ PBHAGEL ZUC;IREVMBA JVERYRFF;NOQBZVANY CNVAF / CEBOYRZF;A ORNE PERRX EQ;VBAN PVE\e\a\a",
        "NQQE:210 WBUAFGBA OYIQ",
        "FEP:SF6",
        "PNYY:NOQBZVANY CNVAF / CEBOYRZF",
        "VASB:YBG 19 / GBJA NAQ PBHAGEL ZUC",
        "K:A ORNE PERRX EQ & VBAN PVE");

    qbGrfg("G10",
        "[] PNQ:89 JRQTRSVRYQ CY;O10;UNAQ VAWHEL;FVPX CREFBA;GREENVAR YA\e\a\a",
        "NQQE:89 JRQTRSVRYQ CY",
        "HAVG:O10",
        "PNYY:UNAQ VAWHEL / FVPX CREFBA",
        "K:GREENVAR YA");

    qbGrfg("G11",
        "[] PNQ:367 A YBHVFVNAN NIR;SF3;ENZFRL ZBOVYR UBZR CNEGF;(M)VAPBZCYRGR 911;CNGGBA NIR;UNMRY ZVYY EQ\e\a\a",
        "NQQE:367 A YBHVFVNAN NIR",
        "FEP:SF3",
        "PNYY:(M)VAPBZCYRGR 911",
        "VASB:ENZFRL ZBOVYR UBZR CNEGF",
        "K:CNGGBA NIR & UNMRY ZVYY EQ");

    qbGrfg("G12",
        "[] PNQ:95 UBYPBZOR PBIR EQ;O2;EZ 201;CVFTNU ZNABE;CVFTNU ZNABE;CFLPUVNGEVP CEBOYRZF;CNEXIVRJ QE;CNEXIVRJ QE\e\a\a",
        "NQQE:95 UBYPBZOR PBIR EQ",
        "HAVG:O2",
        "PNYY:CFLPUVNGEVP CEBOYRZF",
        "VASB:EZ 201 / CVFTNU ZNABE / CVFTNU ZNABE",
        "K:CNEXIVRJ QE & CNEXIVRJ QE");

    qbGrfg("G13",
        "[] PNQ:115 SNVEIVRJ EQ;O2;GUR FPERRA QBBE;SNYYF;YBAQBA EQ;JRFGIVRJ NIR\e\a\a",
        "NQQE:115 SNVEIVRJ EQ",
        "HAVG:O2",
        "PNYY:SNYYF",
        "VASB:GUR FPERRA QBBE",
        "K:YBAQBA EQ & JRFGIVRJ NIR");

    qbGrfg("G14",
        "[] PNQ:600 WHYVNA YA;O2;FHVGR 630;NFURIVYYR ZRQVPVAR & CRQ;NFURIVYYR ZRQVPVAR & CRQ;ONPX CNVA (ABA-ERPRAG);YBAT FUBNYF EQ\e\a\a",
        "NQQE:600 WHYVNA YA",
        "HAVG:O2",
        "PNYY:ONPX CNVA (ABA-ERPRAG)",
        "VASB:FHVGR 630 / NFURIVYYR ZRQVPVAR & CRQ / NFURIVYYR ZRQVPVAR & CRQ",
        "K:YBAT FUBNYF EQ");

    qbGrfg("G15",
        "[] PNQ:9091 IREQR IVFGN PVE;SF9;NCG 5117;IREVMBA;(SE) FGEHPGHER SVER;EVIRE SBEQ CXJL\e\a\a",
        "NQQE:9091 IREQR IVFGN PVE",  // Tbbtyr abg znccvat
        "NCG:5117",
        "FEP:SF9",
        "PNYY:(SE) FGEHPGHER SVER",
        "K:EVIRE SBEQ CXJL");

    qbGrfg("G16",
        "[] PNQ:78 RQTRZBAG EQ;O2;SNYYF;UBYZJBBQ EQ;YNGEBOR FG\e\a\a",
        "NQQE:78 RQTRZBAG EQ",
        "HAVG:O2",
        "PNYY:SNYYF",
        "K:UBYZJBBQ EQ & YNGEBOR FG");

    qbGrfg("G17",
        "[] PNQ:1201 CNGGBA NIR;O2;EBBZ 7;FVFGREF BS ZREPL HETRAG PNER;FVFGRE`F BS ZREPL HETRAG PNER;ONPX CNVA (ABA-ERPRAG);ARJ YRVPRFGRE UJL;QEHVQ QE\e\a\a",
        "NQQE:1201 CNGGBA NIR",
        "HAVG:O2",
        "PNYY:ONPX CNVA (ABA-ERPRAG)",
        "VASB:EBBZ 7 / FVFGREF BS ZREPL HETRAG PNER / FVFGRE`F BS ZREPL HETRAG PNER",
        "K:ARJ YRVPRFGRE UJL & QEHVQ QE");

    qbGrfg("G18",
        "[] PNQ:1 UNLJBBQ PBHAGL UJL;O2;ZC 417 OYHR EVQTR CEXJ;UNLBBQ RBP;(SE) ZVFFVAT CREFBA FRNEPU;FZBXRL CNEX UJL\e\a\a",
        "NQQE:1 UNLJBBQ PBHAGL UJL",  // Abg znccvat
        "HAVG:O2",
        "PNYY:(SE) ZVFFVAT CREFBA FRNEPU",
        "VASB:ZC 417 OYHR EVQTR CEXJ / UNLBBQ RBP",
        "K:FZBXRL CNEX UJL");

  }
  
  @Grfg
  choyvp ibvq grfgNpgvir911P() {

    qbGrfg("G1",
        "PNQ:10 NYRKNAQRE QE;SF1;SY1;NCG 525 JRYSNER PURPX;JBBQOREEL NCGF;(SE) FREIVPR NAL GLCR;A FXLYBSG QE;NEQZVBA CNEX;12012614\e\a",
        "NQQE:10 NYRKNAQRE QE",
        "FEP:SF1",
        "HAVG:SY1",
        "PNYY:(SE) FREIVPR NAL GLCR",
        "VASB:NCG 525 JRYSNER PURPX / JBBQOREEL NCGF / NEQZVBA CNEX",
        "K:A FXLYBSG QE",
        "VQ:12012614");

    qbGrfg("G2",
        "PNQ:304 YVIVATFGBA FG;SF2;SR2;NCG O;HF Pryyhyne;PBAIHYFVBAF / FRVMHERF;QRCBG FG;12012613\e\a",
        "NQQE:304 YVIVATFGBA FG",
        "NCG:O",
        "FEP:SF2",
        "HAVG:SR2",
        "PNYY:PBAIHYFVBAF / FRVMHERF",
        "K:QRCBG FG",
        "VQ:12012613");

    qbGrfg("G3",
        "PNQ:100 UVTUYNAQ PRAGRE OYIQ;SF10;SD10;JRFGREA PNEBYVAN SERVTUG YVARE;IREVMBA JVERYRFF;SNYYF;OEHPR EQ;12012612\e\a",
        "NQQE:100 UVTUYNAQ PRAGRE OYIQ",
        "FEP:SF10",
        "HAVG:SD10",
        "PNYY:SNYYF",
        "VASB:JRFGREA PNEBYVAN SERVTUG YVARE",
        "K:OEHPR EQ",
        "VQ:12012612");

    qbGrfg("G4",
        "PNQ:275 QRNIREIVRJ EQ;SF6;SE3;NCG 4-P;QRNIREIVRJ NCNEGZRAGF;ZVYYF, TYNQLF;QVNORGVP CEBOYRZF;A ORNE PERRX EQ;JRFGZBER QE;12012611\e\a",
        "NQQE:275 QRNIREIVRJ EQ",
        "NCG:4-P",
        "FEP:SF6",
        "HAVG:SE3",
        "PNYY:QVNORGVP CEBOYRZF",
        "ANZR:ZVYYF, TYNQLF",
        "VASB:QRNIREIVRJ NCNEGZRAGF",
        "K:A ORNE PERRX EQ & JRFGZBER QE",
        "VQ:12012611");

    qbGrfg("G5",
        "PNQ:13 ERLABYQF EQ;SF3;SR6;FZBXR QRPGBE & B2 QRPGBE;(SE) FREIVPR NAL GLCR;YBTNA NIR;TRBETVN FG;12012610\e\a",
        "NQQE:13 ERLABYQF EQ",
        "FEP:SF3",
        "HAVG:SR6",
        "PNYY:(SE) FREIVPR NAL GLCR",
        "VASB:FZBXR QRPGBE & B2 QRPGBE",
        "K:YBTNA NIR & TRBETVN FG",
        "VQ:12012610");

    qbGrfg("G6",
        "PNQ:391 F SERAPU OEBNQ NIR;SF2;SR2;HAVGRQ FREIVPRF PERQVG;QVNORGVP CEBOYRZF;PUBPGNJ FG;ENYCU FG;12012609\e\a",
        "NQQE:391 F SERAPU OEBNQ NIR",
        "FEP:SF2",
        "HAVG:SR2",
        "PNYY:QVNORGVP CEBOYRZF",
        "VASB:HAVGRQ FREIVPRF PERQVG",
        "K:PUBPGNJ FG & ENYCU FG",
        "VQ:12012609");

    qbGrfg("G7",
        "PNQ:70 V240 J;SF1;SR1,SY1,SR8,SFNS10;(M)ZBGBE IRU NPPVQRAG HAXABJA;GHAARY EQ GB V240 J;V240 J GB PUHAAF PBIR EQ;12012607\e\a",
        "NQQE:70 V240 J",
        "ZNQQE:70 V 240 J",
        "FEP:SF1",
        "HAVG:SR1,SY1,SR8,SFNS10",
        "PNYY:(M)ZBGBE IRU NPPVQRAG HAXABJA",
        "VASB:GHAARY EQ GB V240 J / V240 J GB PUHAAF PBIR EQ",
        "VQ:12012607");

    qbGrfg("G8",
        "PNQ:4 PBIRJBBQ EQ/PBIRJBBQ YA;SF1;SFDQ1;FZBXR VA NERN;JVYYRGG,WRAAVSRE;(SE) VAIRFGVTNGVBA;12012608\e\a",
        "NQQE:4 PBIRJBBQ EQ & PBIRJBBQ YA",
        "ZNQQE:4 PBIRJBBQ EQ",
        "FEP:SF1",
        "HAVG:SFDQ1",
        "PNYY:(SE) VAIRFGVTNGVBA",
        "ANZR:JVYYRGG,WRAAVSRE",
        "VASB:FZBXR VA NERN",
        "VQ:12012608");

    qbGrfg("G9",
        "PNQ:50 V240 J;SF1;SR1,SY1,SFNS10;(M)ZBGBE IRU NPPVQRAG HAXABJA;OEBNQJNL FG GB V240 J;OEBNQJNL FG GB V240 J;12012607\e\a",
        "NQQE:50 V240 J",
        "ZNQQE:50 V 240 J",
        "FEP:SF1",
        "HAVG:SR1,SY1,SFNS10",
        "PNYY:(M)ZBGBE IRU NPPVQRAG HAXABJA",
        "VASB:OEBNQJNL FG GB V240 J / OEBNQJNL FG GB V240 J",
        "VQ:12012607");

    qbGrfg("G10",
        "PNQ:50 V240 J;SF1;SR1,SY1,SFNS10;(M)ZBGBE IRU NPPVQRAG HAXABJA;OEBNQJNL FG GB V240 J;OEBNQJNL FG GB V240 J;12012607\e\a",
        "NQQE:50 V240 J",
        "ZNQQE:50 V 240 J",
        "FEP:SF1",
        "HAVG:SR1,SY1,SFNS10",
        "PNYY:(M)ZBGBE IRU NPPVQRAG HAXABJA",
        "VASB:OEBNQJNL FG GB V240 J / OEBNQJNL FG GB V240 J",
        "VQ:12012607");

  }
  

  choyvp fgngvp ibvq znva(Fgevat[] netf) {
    arj APOhapbzorPbhaglCnefreGrfg().trarengrGrfgf("G1");
  }
}
