cnpxntr arg.narv.pnqcntr.cnefref.AP;

vzcbeg arg.narv.pnqcntr.cnefref.OnfrCnefreGrfg;

vzcbeg bet.whavg.Grfg;

/* 
PYrirynaq Pbhagl, AP (O)

Pbagnpg: Npgvir911
Ntrapl anzr: Furyol CQ
Ybpngvba: Furyol, AP, Havgrq Fgngrf
Fraqre: <PNQ@pvglbsfuryol.pbz>

{Grkg Zrffntr} PNQ:NYY BGURE;311 F YNSNLRGGR FG
{Grkg Zrffntr} PNQ:PBZZVGZRAG CNCREF;201 R TEBIRE FG
{Grkg Zrffntr} PNQ:FHFCVPVBHF CREFBA;953 NVECBEG EQ/JRAQBIRE URVTUGF QE
{Grkg Zrffntr} PNQ:SBYYBJ HC;1020 R QVKBA OYIQ
{Grkg Zrffntr} PNQ:SENHQ;919 F YNSNLRGGR FG
{Grkg Zrffntr} PNQ:QVFGHEONAPR;709 A JNFUVATGBA FG
{Grkg Zrffntr} PNQ:PUVYQ NOHFR;1502 ABEZNAQL YA
{Grkg Zrffntr} PNQ:NGGRZCGRQ FHVPVQR;919 F YNSNLRGGR FG
{Grkg Zrffntr} PNQ:FHFCVPVBHF CREFBA;411 J TENUNZ FG
{Grkg Zrffntr} PNQ:GERRF/JVERF QBJA;1042 PHZOREYNAQ QE
{Grkg Zrffntr} PNQ:FHFCVPVBHF IRUVPYR;314 OHSSNYB FG
{Grkg Zrffntr} PNQ:FHFCVPVBHF CREFBA;503 JBBQFVQR QE
{Grkg Zrffntr} PNQ:SBYYBJ HC;203 YVARORETRE FG
{Grkg Zrffntr} PNQ:PBZZHAVPNGVAT GUERNGF;311 F YNSNLRGGR FG
{Grkg Zrffntr} PNQ:PBZZHAVGL BEVRAGRQ CBYVPVAT;ORFG FG NCNEGZRAGF
{Grkg Zrffntr} PNQ:NFFVFG PVGVMRA;1600 SNYYFGBA EQ
{Grkg Zrffntr} PNQ:SBYYBJ HC;119 A CBFGBA FG
{Grkg Zrffntr} PNQ:OHFVARFF NYNEZ;2001 R QVKBA OYIQ
{Grkg Zrffntr} PNQ:NFFNHYG;210 TVQARL FG
{Grkg Zrffntr} PNQ:GERRF/JVERF QBJA;866 J ZNEVBA FG
{Grkg Zrffntr} PNQ:FHFCVPVBHF IRUVPYR;1141 R ZNEVBA FG
{Grkg Zrffntr} PNQ:R-911 PNYY;915 XRNEARL QE
{Grkg Zrffntr} PNQ:FHFCVPVBHF IRUVPYR;911 SNYYFGBA EQ
{Grkg Zrffntr} PNQ:FGENAQRQ ZBGBEVFG;706 R QVKBA OYIQ
{Grkg Zrffntr} PNQ:NPPVQRAG CQ;206 R QVKBA OYIQ
{Grkg Zrffntr} PNQ:NFFVFG PVGVMRA;311 F YNSNLRGGR FG
{Grkg Zrffntr} PNQ:NFFVFG PVGVMRA;1100 OHSSNYB FG
{Grkg Zrffntr} PNQ:IRUVPYR FGBC;230 R QVKBA OYIQ
{Grkg Zrffntr} PNQ:OHFVARFF NYNEZ;935 JLXR EQ
{Grkg Zrffntr} PNQ:FGENAQRQ ZBGBEVFG;1777 R QVKBA OYIQ/F CBFG EQ
{Grkg Zrffntr} PNQ:OHFVARFF PURPX;1200 R ZNEVBA FG
{Grkg Zrffntr} PNQ:PNERYRFF NAQ ERPXYRFF QEVIVAT;2001 R QVKBA OYIQ
{Grkg Zrffntr} PNQ:CNEXVAT IVBYNGVBA;2001 R QVKBA OYIQ
{Grkg Zrffntr} PNQ:PVGL BEQVANAPR IVBYNGVBA;902 RYVMNORGU EQ
{Grkg Zrffntr} PNQ:OHFVARFF NYNEZ;513 F QRXNYO FG
{Grkg Zrffntr} PNQ:QVFGHEONAPR;402 UVTUYNAQ NI
{Grkg Zrffntr} PNQ:FHFCVPVBHF IRUVPYR;1146 PBHAGL UBZR EQ
{Grkg Zrffntr} PNQ:IRUVPYR FGBC;1505 R QVKBA OYIQ
{Grkg Zrffntr} PNQ:NFFNHYG;700 R QVKBA OYIQ
{Grkg Zrffntr} PNQ:IRUVPYR FGBC;1206 R QVKBA OYIQ
{Grkg Zrffntr} PNQ:ERFVQRAGVNY NYNEZ;708 RNEY EQ
{Grkg Zrffntr} PNQ:OHFVARFF NYNEZ;809 UBYYL BNX QE
{Grkg Zrffntr} PNQ:FHFCVPVBHF CREFBA;703 R QVKBA OYIQ
{Grkg Zrffntr} PNQ:FREIR FHOCBRAN;111 FUHYY FG
{Grkg Zrffntr} PNQ:FREIR FHOCBRAN;907 A YNSNLRGGR FG
{Grkg Zrffntr} PNQ:FREIR FHOCBRAN;904 YVAARL YA
{Grkg Zrffntr} PNQ:FREIR FHOCBRAN;1049 LNAPRL FG
{Grkg Zrffntr} PNQ:FREIR FHOCBRAN;125 PBYYRTR NI
{Grkg Zrffntr} PNQ:FREIR FHOCBRAN;1367 NYNQQVA FG
{Grkg Zrffntr} PNQ:FREIR FHOCBRAN;116 OBJZNA FG
{Grkg Zrffntr} PNQ:FREIR FHOCBRAN;306 ZPOENLRE FG
{Grkg Zrffntr} PNQ:FREIR FHOCBRAN;508 ABEGUREA FG
{Grkg Zrffntr} PNQ:OHFVARFF NYNEZ;515 F YNSNLRGGR FG
{Grkg Zrffntr} PNQ:FREIR FHOCBRAN;229 LBHAT FG
{Grkg Zrffntr} PNQ:OHFVARFF NYNEZ;218 J JNEERA FG
{Grkg Zrffntr} PNQ:OHFVARFF PURPX;919 F YNSNLRGGR FG
{Grkg Zrffntr} PNQ:FREIR FHOCBRAN;705 PNYINEL FG
{Grkg Zrffntr} PNQ:ERFVQRAGVNY NYNEZ;217 TBYQ FG
{Grkg Zrffntr} PNQ:FHFCVPVBHF CREFBA;1200 A JNFUVATGBA FG
{Grkg Zrffntr} PNQ:ERFVQRAGVNY NYNEZ;231 YVYL FG
{Grkg Zrffntr} PNQ:NFFVFG PVGVMRA;205 J QVKBA OYIQ
{Grkg Zrffntr} PNQ:QBZRFGVP QVFCHGR;311 ZNEGVA FG
{Grkg Zrffntr} PNQ:OHFVARFF NYNEZ;818 ZPTBJNA EQ
{Grkg Zrffntr} PNQ:SBHAQ CEBCREGL;113 F YNSNLRGGR FG/J JNEERA FG
{Grkg Zrffntr} PNQ:RFPBEG;401 A ZBETNA FG
{Grkg Zrffntr} PNQ:JNEENAG;908 FCEVAT TNEQRA QE
{Grkg Zrffntr} PNQ:FREIR FHOCBRAN;918 NVEYVAR NI RKG
{Grkg Zrffntr} PNQ:FREIR FHOCBRAN;417 ZNHARL YA
{Grkg Zrffntr} PNQ:FREIR FHOCBRAN;308 SVERSYL CG
{Grkg Zrffntr} PNQ:ERFVQRAGVNY NYNEZ;438 PBHAGEL PYHO PG
{Grkg Zrffntr} PNQ:OHFVARFF NYNEZ;1016 A YNSNLRGGR FG
{Grkg Zrffntr} PNQ:IRUVPYR FGBC;1151 F QRXNYO FG/YNJERAPR FG
{Grkg Zrffntr} PNQ:FHFCVPVBHF IRUVPYR;846 J JNEERA FG
{Grkg Zrffntr} PNQ:FHFCVPVBHF CREFBA;319 R ZNEVBA FG
{Grkg Zrffntr} PNQ:PBZZHAVGL BEVRAGRQ CBYVPVAT;ORFG FG
{Grkg Zrffntr} PNQ:NGGRZCGRQ FHVPVQR;618 JNER EQ
{Grkg Zrffntr} PNQ:OHFVARFF PURPX;1528 F YNSNLRGGR FG
{Grkg Zrffntr} PNQ:NFFVFG BGURE NTRAPL;1400 XVATF EQ
{Grkg Zrffntr} PNQ:OHFVARFF NYNEZ;1108 R QVKBA OYIQ
{Grkg Zrffntr} PNQ:QNZNTR GB CEBCREGL;837 YBTNA FG
{Grkg Zrffntr} PNQ:NYY BGURE;1808 R QVKBA OYIQ
{Grkg Zrffntr} PNQ:NYY BGURE;1020 R QVKBA OYIQ
{Grkg Zrffntr} PNQ:PVGL BEQVANAPR IVBYNGVBA;910 SBKPEBSG PVE
{Grkg Zrffntr} PNQ:PVGL BEQVANAPR IVBYNGVBA;215 ORFG FG
{Grkg Zrffntr} PNQ:R-911 PNYY;1321 F YNSNLRGGR FG
{Grkg Zrffntr} PNQ:UVG NAQ EHA;1020 QBQQ FG
{Grkg Zrffntr} PNQ:NFFNHYG;J JNEERA FG/ZNEGVA FG
{Grkg Zrffntr} PNQ:FHFCVPVBHF CREFBA;219 ZPOENLRE FG/J TENUNZ FG
{Grkg Zrffntr} PNQ:NFFNHYG;729 J JNEERA FG/JUVFANAG FG
{Grkg Zrffntr} PNQ:IRUVPYR FGBC;1614 J QVKBA OYIQ/J ZNEVBA FG
{Grkg Zrffntr} PNQ:FHFCVPVBHF CREFBA;706 R QVKBA OYIQ
{Grkg Zrffntr} PNQ:YNEPRAL;211 F YNSNLRGGR FG
{Grkg Zrffntr} PNQ:FHFCVPVBHF IRUVPYR;850 J FHZGRE FG
{Grkg Zrffntr} PNQ:YNETR PEBJQ;613 J RYZ FG/PNYINEL FG
{Grkg Zrffntr} PNQ:YNETR PEBJQ;500 PNYINEL FG/TNEQARE FG
{Grkg Zrffntr} PNQ:ERFVQRAPR PURPX;509 JUVFANAG FG

*/

choyvp pynff APPyrirynaqPbhaglOCnefreGrfg rkgraqf OnfrCnefreGrfg {
  
  choyvp APPyrirynaqPbhaglOCnefreGrfg() {
    frgCnefre(arj APPyrirynaqPbhaglOCnefre(), "PYRIRYNAQ PBHAGL", "AP");
  }

  @Grfg
  choyvp ibvq grfgFuryolCQ() {

    qbGrfg("G1",
        "{Grkg Zrffntr} PNQ:NYY BGURE;311 F YNSNLRGGR FG",
        "PNYY:NYY BGURE",
        "NQQE:311 F YNSNLRGGR FG");

    qbGrfg("G2",
        "{Grkg Zrffntr} PNQ:PBZZVGZRAG CNCREF;201 R TEBIRE FG",
        "PNYY:PBZZVGZRAG CNCREF",
        "NQQE:201 R TEBIRE FG");

    qbGrfg("G3",
        "{Grkg Zrffntr} PNQ:FHFCVPVBHF CREFBA;953 NVECBEG EQ/JRAQBIRE URVTUGF QE",
        "PNYY:FHFCVPVBHF CREFBA",
        "NQQE:953 NVECBEG EQ & JRAQBIRE URVTUGF QE",
        "ZNQQE:953 NVECBEG EQ");

    qbGrfg("G4",
        "{Grkg Zrffntr} PNQ:SBYYBJ HC;1020 R QVKBA OYIQ",
        "PNYY:SBYYBJ HC",
        "NQQE:1020 R QVKBA OYIQ");

    qbGrfg("G5",
        "{Grkg Zrffntr} PNQ:SENHQ;919 F YNSNLRGGR FG",
        "PNYY:SENHQ",
        "NQQE:919 F YNSNLRGGR FG");

    qbGrfg("G6",
        "{Grkg Zrffntr} PNQ:QVFGHEONAPR;709 A JNFUVATGBA FG",
        "PNYY:QVFGHEONAPR",
        "NQQE:709 A JNFUVATGBA FG");

    qbGrfg("G7",
        "{Grkg Zrffntr} PNQ:PUVYQ NOHFR;1502 ABEZNAQL YA",
        "PNYY:PUVYQ NOHFR",
        "NQQE:1502 ABEZNAQL YA");

    qbGrfg("G8",
        "{Grkg Zrffntr} PNQ:NGGRZCGRQ FHVPVQR;919 F YNSNLRGGR FG",
        "PNYY:NGGRZCGRQ FHVPVQR",
        "NQQE:919 F YNSNLRGGR FG");

    qbGrfg("G9",
        "{Grkg Zrffntr} PNQ:FHFCVPVBHF CREFBA;411 J TENUNZ FG",
        "PNYY:FHFCVPVBHF CREFBA",
        "NQQE:411 J TENUNZ FG");

    qbGrfg("G10",
        "{Grkg Zrffntr} PNQ:GERRF/JVERF QBJA;1042 PHZOREYNAQ QE",
        "PNYY:GERRF/JVERF QBJA",
        "NQQE:1042 PHZOREYNAQ QE");

    qbGrfg("G11",
        "{Grkg Zrffntr} PNQ:FHFCVPVBHF IRUVPYR;314 OHSSNYB FG",
        "PNYY:FHFCVPVBHF IRUVPYR",
        "NQQE:314 OHSSNYB FG");

    qbGrfg("G12",
        "{Grkg Zrffntr} PNQ:FHFCVPVBHF CREFBA;503 JBBQFVQR QE",
        "PNYY:FHFCVPVBHF CREFBA",
        "NQQE:503 JBBQFVQR QE");

    qbGrfg("G13",
        "{Grkg Zrffntr} PNQ:SBYYBJ HC;203 YVARORETRE FG",
        "PNYY:SBYYBJ HC",
        "NQQE:203 YVARORETRE FG");

    qbGrfg("G14",
        "{Grkg Zrffntr} PNQ:PBZZHAVPNGVAT GUERNGF;311 F YNSNLRGGR FG",
        "PNYY:PBZZHAVPNGVAT GUERNGF",
        "NQQE:311 F YNSNLRGGR FG");

    qbGrfg("G15",
        "{Grkg Zrffntr} PNQ:PBZZHAVGL BEVRAGRQ CBYVPVAT;ORFG FG NCNEGZRAGF",
        "PNYY:PBZZHAVGL BEVRAGRQ CBYVPVAT",
        "NQQE:ORFG FG NCNEGZRAGF");

    qbGrfg("G16",
        "{Grkg Zrffntr} PNQ:NFFVFG PVGVMRA;1600 SNYYFGBA EQ",
        "PNYY:NFFVFG PVGVMRA",
        "NQQE:1600 SNYYFGBA EQ");

    qbGrfg("G17",
        "{Grkg Zrffntr} PNQ:SBYYBJ HC;119 A CBFGBA FG",
        "PNYY:SBYYBJ HC",
        "NQQE:119 A CBFGBA FG");

    qbGrfg("G18",
        "{Grkg Zrffntr} PNQ:OHFVARFF NYNEZ;2001 R QVKBA OYIQ",
        "PNYY:OHFVARFF NYNEZ",
        "NQQE:2001 R QVKBA OYIQ");

    qbGrfg("G19",
        "{Grkg Zrffntr} PNQ:NFFNHYG;210 TVQARL FG",
        "PNYY:NFFNHYG",
        "NQQE:210 TVQARL FG");

    qbGrfg("G20",
        "{Grkg Zrffntr} PNQ:GERRF/JVERF QBJA;866 J ZNEVBA FG",
        "PNYY:GERRF/JVERF QBJA",
        "NQQE:866 J ZNEVBA FG");

    qbGrfg("G21",
        "{Grkg Zrffntr} PNQ:FHFCVPVBHF IRUVPYR;1141 R ZNEVBA FG",
        "PNYY:FHFCVPVBHF IRUVPYR",
        "NQQE:1141 R ZNEVBA FG");

    qbGrfg("G22",
        "{Grkg Zrffntr} PNQ:R-911 PNYY;915 XRNEARL QE",
        "PNYY:R-911 PNYY",
        "NQQE:915 XRNEARL QE");

    qbGrfg("G23",
        "{Grkg Zrffntr} PNQ:FHFCVPVBHF IRUVPYR;911 SNYYFGBA EQ",
        "PNYY:FHFCVPVBHF IRUVPYR",
        "NQQE:911 SNYYFGBA EQ");

    qbGrfg("G24",
        "{Grkg Zrffntr} PNQ:FGENAQRQ ZBGBEVFG;706 R QVKBA OYIQ",
        "PNYY:FGENAQRQ ZBGBEVFG",
        "NQQE:706 R QVKBA OYIQ");

    qbGrfg("G25",
        "{Grkg Zrffntr} PNQ:NPPVQRAG CQ;206 R QVKBA OYIQ",
        "PNYY:NPPVQRAG CQ",
        "NQQE:206 R QVKBA OYIQ");

    qbGrfg("G26",
        "{Grkg Zrffntr} PNQ:NFFVFG PVGVMRA;311 F YNSNLRGGR FG",
        "PNYY:NFFVFG PVGVMRA",
        "NQQE:311 F YNSNLRGGR FG");

    qbGrfg("G27",
        "{Grkg Zrffntr} PNQ:NFFVFG PVGVMRA;1100 OHSSNYB FG",
        "PNYY:NFFVFG PVGVMRA",
        "NQQE:1100 OHSSNYB FG");

    qbGrfg("G28",
        "{Grkg Zrffntr} PNQ:IRUVPYR FGBC;230 R QVKBA OYIQ",
        "PNYY:IRUVPYR FGBC",
        "NQQE:230 R QVKBA OYIQ");

    qbGrfg("G29",
        "{Grkg Zrffntr} PNQ:OHFVARFF NYNEZ;935 JLXR EQ",
        "PNYY:OHFVARFF NYNEZ",
        "NQQE:935 JLXR EQ");

    qbGrfg("G30",
        "{Grkg Zrffntr} PNQ:FGENAQRQ ZBGBEVFG;1777 R QVKBA OYIQ/F CBFG EQ",
        "PNYY:FGENAQRQ ZBGBEVFG",
        "NQQE:1777 R QVKBA OYIQ & F CBFG EQ",
        "ZNQQE:1777 R QVKBA OYIQ");

    qbGrfg("G31",
        "{Grkg Zrffntr} PNQ:OHFVARFF PURPX;1200 R ZNEVBA FG",
        "PNYY:OHFVARFF PURPX",
        "NQQE:1200 R ZNEVBA FG");

    qbGrfg("G32",
        "{Grkg Zrffntr} PNQ:PNERYRFF NAQ ERPXYRFF QEVIVAT;2001 R QVKBA OYIQ",
        "PNYY:PNERYRFF NAQ ERPXYRFF QEVIVAT",
        "NQQE:2001 R QVKBA OYIQ");

    qbGrfg("G33",
        "{Grkg Zrffntr} PNQ:CNEXVAT IVBYNGVBA;2001 R QVKBA OYIQ",
        "PNYY:CNEXVAT IVBYNGVBA",
        "NQQE:2001 R QVKBA OYIQ");

    qbGrfg("G34",
        "{Grkg Zrffntr} PNQ:PVGL BEQVANAPR IVBYNGVBA;902 RYVMNORGU EQ",
        "PNYY:PVGL BEQVANAPR IVBYNGVBA",
        "NQQE:902 RYVMNORGU EQ");

    qbGrfg("G35",
        "{Grkg Zrffntr} PNQ:OHFVARFF NYNEZ;513 F QRXNYO FG",
        "PNYY:OHFVARFF NYNEZ",
        "NQQE:513 F QRXNYO FG");

    qbGrfg("G36",
        "{Grkg Zrffntr} PNQ:QVFGHEONAPR;402 UVTUYNAQ NI",
        "PNYY:QVFGHEONAPR",
        "NQQE:402 UVTUYNAQ NI",
        "ZNQQE:402 UVTUYNAQ NIR");

    qbGrfg("G37",
        "{Grkg Zrffntr} PNQ:FHFCVPVBHF IRUVPYR;1146 PBHAGL UBZR EQ",
        "PNYY:FHFCVPVBHF IRUVPYR",
        "NQQE:1146 PBHAGL UBZR EQ");

    qbGrfg("G38",
        "{Grkg Zrffntr} PNQ:IRUVPYR FGBC;1505 R QVKBA OYIQ",
        "PNYY:IRUVPYR FGBC",
        "NQQE:1505 R QVKBA OYIQ");

    qbGrfg("G39",
        "{Grkg Zrffntr} PNQ:NFFNHYG;700 R QVKBA OYIQ",
        "PNYY:NFFNHYG",
        "NQQE:700 R QVKBA OYIQ");

    qbGrfg("G40",
        "{Grkg Zrffntr} PNQ:IRUVPYR FGBC;1206 R QVKBA OYIQ",
        "PNYY:IRUVPYR FGBC",
        "NQQE:1206 R QVKBA OYIQ");

    qbGrfg("G41",
        "{Grkg Zrffntr} PNQ:ERFVQRAGVNY NYNEZ;708 RNEY EQ",
        "PNYY:ERFVQRAGVNY NYNEZ",
        "NQQE:708 RNEY EQ");

    qbGrfg("G42",
        "{Grkg Zrffntr} PNQ:OHFVARFF NYNEZ;809 UBYYL BNX QE",
        "PNYY:OHFVARFF NYNEZ",
        "NQQE:809 UBYYL BNX QE");

    qbGrfg("G43",
        "{Grkg Zrffntr} PNQ:FHFCVPVBHF CREFBA;703 R QVKBA OYIQ",
        "PNYY:FHFCVPVBHF CREFBA",
        "NQQE:703 R QVKBA OYIQ");

    qbGrfg("G44",
        "{Grkg Zrffntr} PNQ:FREIR FHOCBRAN;111 FUHYY FG",
        "PNYY:FREIR FHOCBRAN",
        "NQQE:111 FUHYY FG");

    qbGrfg("G45",
        "{Grkg Zrffntr} PNQ:FREIR FHOCBRAN;907 A YNSNLRGGR FG",
        "PNYY:FREIR FHOCBRAN",
        "NQQE:907 A YNSNLRGGR FG");

    qbGrfg("G46",
        "{Grkg Zrffntr} PNQ:FREIR FHOCBRAN;904 YVAARL YA",
        "PNYY:FREIR FHOCBRAN",
        "NQQE:904 YVAARL YA");

    qbGrfg("G47",
        "{Grkg Zrffntr} PNQ:FREIR FHOCBRAN;1049 LNAPRL FG",
        "PNYY:FREIR FHOCBRAN",
        "NQQE:1049 LNAPRL FG");

    qbGrfg("G48",
        "{Grkg Zrffntr} PNQ:FREIR FHOCBRAN;125 PBYYRTR NI",
        "PNYY:FREIR FHOCBRAN",
        "NQQE:125 PBYYRTR NI",
        "ZNQQE:125 PBYYRTR NIR");

    qbGrfg("G49",
        "{Grkg Zrffntr} PNQ:FREIR FHOCBRAN;1367 NYNQQVA FG",
        "PNYY:FREIR FHOCBRAN",
        "NQQE:1367 NYNQQVA FG");

    qbGrfg("G50",
        "{Grkg Zrffntr} PNQ:FREIR FHOCBRAN;116 OBJZNA FG",
        "PNYY:FREIR FHOCBRAN",
        "NQQE:116 OBJZNA FG");

    qbGrfg("G51",
        "{Grkg Zrffntr} PNQ:FREIR FHOCBRAN;306 ZPOENLRE FG",
        "PNYY:FREIR FHOCBRAN",
        "NQQE:306 ZPOENLRE FG");

    qbGrfg("G52",
        "{Grkg Zrffntr} PNQ:FREIR FHOCBRAN;508 ABEGUREA FG",
        "PNYY:FREIR FHOCBRAN",
        "NQQE:508 ABEGUREA FG");

    qbGrfg("G53",
        "{Grkg Zrffntr} PNQ:OHFVARFF NYNEZ;515 F YNSNLRGGR FG",
        "PNYY:OHFVARFF NYNEZ",
        "NQQE:515 F YNSNLRGGR FG");

    qbGrfg("G54",
        "{Grkg Zrffntr} PNQ:FREIR FHOCBRAN;229 LBHAT FG",
        "PNYY:FREIR FHOCBRAN",
        "NQQE:229 LBHAT FG");

    qbGrfg("G55",
        "{Grkg Zrffntr} PNQ:OHFVARFF NYNEZ;218 J JNEERA FG",
        "PNYY:OHFVARFF NYNEZ",
        "NQQE:218 J JNEERA FG");

    qbGrfg("G56",
        "{Grkg Zrffntr} PNQ:OHFVARFF PURPX;919 F YNSNLRGGR FG",
        "PNYY:OHFVARFF PURPX",
        "NQQE:919 F YNSNLRGGR FG");

    qbGrfg("G57",
        "{Grkg Zrffntr} PNQ:FREIR FHOCBRAN;705 PNYINEL FG",
        "PNYY:FREIR FHOCBRAN",
        "NQQE:705 PNYINEL FG");

    qbGrfg("G58",
        "{Grkg Zrffntr} PNQ:ERFVQRAGVNY NYNEZ;217 TBYQ FG",
        "PNYY:ERFVQRAGVNY NYNEZ",
        "NQQE:217 TBYQ FG");

    qbGrfg("G59",
        "{Grkg Zrffntr} PNQ:FHFCVPVBHF CREFBA;1200 A JNFUVATGBA FG",
        "PNYY:FHFCVPVBHF CREFBA",
        "NQQE:1200 A JNFUVATGBA FG");

    qbGrfg("G60",
        "{Grkg Zrffntr} PNQ:ERFVQRAGVNY NYNEZ;231 YVYL FG",
        "PNYY:ERFVQRAGVNY NYNEZ",
        "NQQE:231 YVYL FG");

    qbGrfg("G61",
        "{Grkg Zrffntr} PNQ:NFFVFG PVGVMRA;205 J QVKBA OYIQ",
        "PNYY:NFFVFG PVGVMRA",
        "NQQE:205 J QVKBA OYIQ");

    qbGrfg("G62",
        "{Grkg Zrffntr} PNQ:QBZRFGVP QVFCHGR;311 ZNEGVA FG",
        "PNYY:QBZRFGVP QVFCHGR",
        "NQQE:311 ZNEGVA FG");

    qbGrfg("G63",
        "{Grkg Zrffntr} PNQ:OHFVARFF NYNEZ;818 ZPTBJNA EQ",
        "PNYY:OHFVARFF NYNEZ",
        "NQQE:818 ZPTBJNA EQ");

    qbGrfg("G64",
        "{Grkg Zrffntr} PNQ:SBHAQ CEBCREGL;113 F YNSNLRGGR FG/J JNEERA FG",
        "PNYY:SBHAQ CEBCREGL",
        "NQQE:113 F YNSNLRGGR FG & J JNEERA FG",
        "ZNQQE:113 F YNSNLRGGR FG");

    qbGrfg("G65",
        "{Grkg Zrffntr} PNQ:RFPBEG;401 A ZBETNA FG",
        "PNYY:RFPBEG",
        "NQQE:401 A ZBETNA FG");

    qbGrfg("G66",
        "{Grkg Zrffntr} PNQ:JNEENAG;908 FCEVAT TNEQRA QE",
        "PNYY:JNEENAG",
        "NQQE:908 FCEVAT TNEQRA QE");

    qbGrfg("G67",
        "{Grkg Zrffntr} PNQ:FREIR FHOCBRAN;918 NVEYVAR NI RKG",
        "PNYY:FREIR FHOCBRAN",
        "NQQE:918 NVEYVAR NI RKG",
        "ZNQQE:918 NVEYVAR NIR RKG");

    qbGrfg("G68",
        "{Grkg Zrffntr} PNQ:FREIR FHOCBRAN;417 ZNHARL YA",
        "PNYY:FREIR FHOCBRAN",
        "NQQE:417 ZNHARL YA");

    qbGrfg("G69",
        "{Grkg Zrffntr} PNQ:FREIR FHOCBRAN;308 SVERSYL CG",
        "PNYY:FREIR FHOCBRAN",
        "NQQE:308 SVERSYL CG");

    qbGrfg("G70",
        "{Grkg Zrffntr} PNQ:ERFVQRAGVNY NYNEZ;438 PBHAGEL PYHO PG",
        "PNYY:ERFVQRAGVNY NYNEZ",
        "NQQE:438 PBHAGEL PYHO PG");

    qbGrfg("G71",
        "{Grkg Zrffntr} PNQ:OHFVARFF NYNEZ;1016 A YNSNLRGGR FG",
        "PNYY:OHFVARFF NYNEZ",
        "NQQE:1016 A YNSNLRGGR FG");

    qbGrfg("G72",
        "{Grkg Zrffntr} PNQ:IRUVPYR FGBC;1151 F QRXNYO FG/YNJERAPR FG",
        "PNYY:IRUVPYR FGBC",
        "NQQE:1151 F QRXNYO FG & YNJERAPR FG",
        "ZNQQE:1151 F QRXNYO FG");

    qbGrfg("G73",
        "{Grkg Zrffntr} PNQ:FHFCVPVBHF IRUVPYR;846 J JNEERA FG",
        "PNYY:FHFCVPVBHF IRUVPYR",
        "NQQE:846 J JNEERA FG");

    qbGrfg("G74",
        "{Grkg Zrffntr} PNQ:FHFCVPVBHF CREFBA;319 R ZNEVBA FG",
        "PNYY:FHFCVPVBHF CREFBA",
        "NQQE:319 R ZNEVBA FG");

    qbGrfg("G75",
        "{Grkg Zrffntr} PNQ:PBZZHAVGL BEVRAGRQ CBYVPVAT;ORFG FG",
        "PNYY:PBZZHAVGL BEVRAGRQ CBYVPVAT",
        "NQQE:ORFG FG");

    qbGrfg("G76",
        "{Grkg Zrffntr} PNQ:NGGRZCGRQ FHVPVQR;618 JNER EQ",
        "PNYY:NGGRZCGRQ FHVPVQR",
        "NQQE:618 JNER EQ");

    qbGrfg("G77",
        "{Grkg Zrffntr} PNQ:OHFVARFF PURPX;1528 F YNSNLRGGR FG",
        "PNYY:OHFVARFF PURPX",
        "NQQE:1528 F YNSNLRGGR FG");

    qbGrfg("G78",
        "{Grkg Zrffntr} PNQ:NFFVFG BGURE NTRAPL;1400 XVATF EQ",
        "PNYY:NFFVFG BGURE NTRAPL",
        "NQQE:1400 XVATF EQ");

    qbGrfg("G79",
        "{Grkg Zrffntr} PNQ:OHFVARFF NYNEZ;1108 R QVKBA OYIQ",
        "PNYY:OHFVARFF NYNEZ",
        "NQQE:1108 R QVKBA OYIQ");

    qbGrfg("G80",
        "{Grkg Zrffntr} PNQ:QNZNTR GB CEBCREGL;837 YBTNA FG",
        "PNYY:QNZNTR GB CEBCREGL",
        "NQQE:837 YBTNA FG");

    qbGrfg("G81",
        "{Grkg Zrffntr} PNQ:NYY BGURE;1808 R QVKBA OYIQ",
        "PNYY:NYY BGURE",
        "NQQE:1808 R QVKBA OYIQ");

    qbGrfg("G82",
        "{Grkg Zrffntr} PNQ:NYY BGURE;1020 R QVKBA OYIQ",
        "PNYY:NYY BGURE",
        "NQQE:1020 R QVKBA OYIQ");

    qbGrfg("G83",
        "{Grkg Zrffntr} PNQ:PVGL BEQVANAPR IVBYNGVBA;910 SBKPEBSG PVE",
        "PNYY:PVGL BEQVANAPR IVBYNGVBA",
        "NQQE:910 SBKPEBSG PVE");

    qbGrfg("G84",
        "{Grkg Zrffntr} PNQ:PVGL BEQVANAPR IVBYNGVBA;215 ORFG FG",
        "PNYY:PVGL BEQVANAPR IVBYNGVBA",
        "NQQE:215 ORFG FG");

    qbGrfg("G85",
        "{Grkg Zrffntr} PNQ:R-911 PNYY;1321 F YNSNLRGGR FG",
        "PNYY:R-911 PNYY",
        "NQQE:1321 F YNSNLRGGR FG");

    qbGrfg("G86",
        "{Grkg Zrffntr} PNQ:UVG NAQ EHA;1020 QBQQ FG",
        "PNYY:UVG NAQ EHA",
        "NQQE:1020 QBQQ FG");

    qbGrfg("G87",
        "{Grkg Zrffntr} PNQ:NFFNHYG;J JNEERA FG/ZNEGVA FG",
        "PNYY:NFFNHYG",
        "NQQE:J JNEERA FG & ZNEGVA FG");

    qbGrfg("G88",
        "{Grkg Zrffntr} PNQ:FHFCVPVBHF CREFBA;219 ZPOENLRE FG/J TENUNZ FG",
        "PNYY:FHFCVPVBHF CREFBA",
        "NQQE:219 ZPOENLRE FG & J TENUNZ FG",
        "ZNQQE:219 ZPOENLRE FG");

    qbGrfg("G89",
        "{Grkg Zrffntr} PNQ:NFFNHYG;729 J JNEERA FG/JUVFANAG FG",
        "PNYY:NFFNHYG",
        "NQQE:729 J JNEERA FG & JUVFANAG FG",
        "ZNQQE:729 J JNEERA FG");

    qbGrfg("G90",
        "{Grkg Zrffntr} PNQ:IRUVPYR FGBC;1614 J QVKBA OYIQ/J ZNEVBA FG",
        "PNYY:IRUVPYR FGBC",
        "NQQE:1614 J QVKBA OYIQ & J ZNEVBA FG",
        "ZNQQE:1614 J QVKBA OYIQ");

    qbGrfg("G91",
        "{Grkg Zrffntr} PNQ:FHFCVPVBHF CREFBA;706 R QVKBA OYIQ",
        "PNYY:FHFCVPVBHF CREFBA",
        "NQQE:706 R QVKBA OYIQ");

    qbGrfg("G92",
        "{Grkg Zrffntr} PNQ:YNEPRAL;211 F YNSNLRGGR FG",
        "PNYY:YNEPRAL",
        "NQQE:211 F YNSNLRGGR FG");

    qbGrfg("G93",
        "{Grkg Zrffntr} PNQ:FHFCVPVBHF IRUVPYR;850 J FHZGRE FG",
        "PNYY:FHFCVPVBHF IRUVPYR",
        "NQQE:850 J FHZGRE FG");

    qbGrfg("G94",
        "{Grkg Zrffntr} PNQ:YNETR PEBJQ;613 J RYZ FG/PNYINEL FG",
        "PNYY:YNETR PEBJQ",
        "NQQE:613 J RYZ FG & PNYINEL FG",
        "ZNQQE:613 J RYZ FG");

    qbGrfg("G95",
        "{Grkg Zrffntr} PNQ:YNETR PEBJQ;500 PNYINEL FG/TNEQARE FG",
        "PNYY:YNETR PEBJQ",
        "NQQE:500 PNYINEL FG & TNEQARE FG",
        "ZNQQE:500 PNYINEL FG");

    qbGrfg("G96",
        "{Grkg Zrffntr} PNQ:ERFVQRAPR PURPX;509 JUVFANAG FG",
        "PNYY:ERFVQRAPR PURPX",
        "NQQE:509 JUVFANAG FG");

  }

  choyvp fgngvp ibvq znva(Fgevat[] netf) {
    arj APPyrirynaqPbhaglOCnefreGrfg().trarengrGrfgf("G1");
  }
}
