package net.anei.cadpage.parsers.OH;

import net.anei.cadpage.parsers.BaseParserTest;

import org.junit.Test;

/*
Cuyahoga County, OH
Contact: Active911
Agency name: Chagrin Falls Fire Dept.
Location: Chagrin Falls, OH, United States
Sender: dispatch@chagrinfallspd.com

(Dispatch Message) SQUAD CALL-GENERAL  \r308  FOX WAY     \rCUT WRIST 
(Dispatch Message) MVA \n123  FAIRVIEW DR    S RUSSELL \nELDERLY FEMALE INVOLVED IN LOW SPEED MVA
(Dispatch Message) SQUAD CALL-GENERAL  \r35952  SOLON RD    BENTLEYVILLE \rMALE PINNED BETWEEN TREE AND RIDING MOWER, ADIVSED NOT INJURED 
(Dispatch Message) MVA \n REQUESTED SQUAD AIR BAG DEPLOYMENT, \n 
(Dispatch Message) MVA \r  CHILLICOTHE RD    S RUSSELL \rGCSO ADVISED VEHICLE ( GRY VAN) IN THE DITCH, NO INJURIES 
(Dispatch Message) BOX 100  \r  HIRAM TRL    CHAGRIN FALL \rREQUESTED BY OC3 
(Dispatch Message) SQUAD CALL-GENERAL \r200  HAMLET HILLS DR  123  CHAGRIN FALL \rELDERLY FEMALE FELL, UNINJURED 
(Dispatch Message) SQUAD CALL-GENERAL  \r150  KENSINGTON CIR    S RUSSELL \rSEIVERS SECURITY  216-383-1234 OPR/ JESSICA\nMEDICAL ALARM 
(Dispatch Message) FIRE- GENERAL \r  COY LN    CHAGRIN FALL \rGARAGE SMOKING IN THE REAR OF THE HOUSE NEXT DOOR 
(Dispatch Message) SQUAD CALL-GENERAL  \r70  RIVER STONE DR    MORELAND HIL \rELDERLY FEMALE FELL POSSIBLE INJURED ARM 
(Dispatch Message) ANIMAL- MISC. \r83  MAPLE ST   \rDOG STUCK UNDER CAR 
(Dispatch Message) SQUAD CALL-GENERAL  \r3841  WILTSHIRE RD    MORELAND HIL \rMALE WITH PARKINSONS NEEDS TO BE TRANSPORTED 
(Dispatch Message) MVA-PEDEST.INJURY  \r98  N MAIN ST    CHAGRIN FALL \rFEMALE STRUCK BY VEHICLE 
(Dispatch Message) ALARMS-FIRE  \r2657  CHAGRIN RIVER    HUNTING VALL \rACCESS PROTECTIVE 800.498.7565\nIND/PULL STATION \nOPR/RIASHIAH 
(Dispatch Message) ON SOM AT BERNWOOD... DRIVER POSSIBLE DIABETIC REACTION
(Dispatch Message) SQUAD CALL-GENERAL  \r5192  CHILLICOTHE RD    S RUSSELL \r46 YR OLD FEMALE, ABDOMINAL PAIN 
(Dispatch Message) ALARMS-CO DETECTOR  \r1584  BELL ST    S RUSSELL \rCO DETECTORS IN THE BASEMENT ARE SOUNDING 
(Dispatch Message) SQUAD CALL-GENERAL  \r245  SPRINGDALE LN    MORELAND HIL \r83 YRO FEMALE HEART PROBLEM AND FEELING FAINT 
(Dispatch Message) SQUAD CALL-GENERAL  \r200  HAMLET HILLS DR  307  CHAGRIN FALL \rINVALID ASSIST NEEDED ON MALE PARTY 
(Dispatch Message) SQUAD CALL-GENERAL  \r25  PLEASANT DR   CHAGRIN FALL \rELDERLY FEMALE UNRESPONSIVE, BREATHING 
(Dispatch Message) SQUAD CALL-GENERAL  \r200  HAMLET HILLS DR  310  CHAGRIN FALL \rUNKNOWN MEDICAL, SQUAD REQUESTED BY RESIDENT 
(Dispatch Message) ALARMS-MEDICAL  \n16  FOREST DR    S RUSSELL \nlifeline sec 888 289 2018 HISTORY OF FALLING OPR/JANE 
(Dispatch Message)   S WOODLAND RD     UTILITY POLE SMOKING AT TOP, NORTH SIDE OF 87. W/B JUST WEST OF RIVER BRIDGE 
(Dispatch Message) SQUAD CALL-GENERAL  \r47  PAW PAW LAKE DR    S RUSSELL \rFEMALE WAS CHOKING, SHE IS NOW HAVING TROUBLE BREATHING 
(Dispatch Message) SQUAD CALL-GENERAL  \r36030  CHAGRIN BLVD    MORELAND HIL \rUNRESPONSIVE FEMALE 
(Dispatch Message) SQUAD CALL-GENERAL  \r400  E WASHINGTON ST   CHAGRIN FALL \rHIT IN FACE W BALL CON/BREATH 
(Dispatch Message) SQUAD CALL-GENERAL  \r305  E WASHINGTON ST   CHAGRIN FALL \r84 YR OLD FEMALE .,POSSIBLE STROKE 
(Dispatch Message) ALARMS-FIRE  \r40  LAUREL COURT   MORELAND HIL \rSTANLEY SECURITY\nOPR : MEGAN\n216-361-1050\nIND : CLEVELAND ROOM 
(Dispatch Message) SQUAD CALL\n200  HAMLET HILLS DR  217  \nELDERLY FEMALE FELL OUT OF BED\nNEEDS ASSISTANCE GETTING UP 
(Dispatch Message) SQUAD CALL-GENERAL \r205  HAMLET HILLS DR  75  CHAGRIN FALL \rFEMALE FELL DIZZY 
(Dispatch Message) MUTUAL AID, GIVEN  \n6025  KRUSE DR    CHAGRIN FALL \nSOLON FD REQUESTED A LADDER TRUCK  
(Dispatch Message) SQUAD CALL-GENERAL  \rE WASHINGTON ST & RIDGEWOOD    CHAGRIN FALL \rMALE FELL OFF BIKE AND NOT MOVING 
(Dispatch Message) SQUAD CALL-GENERAL  \r116  COUNTRYSIDE    S RUSSELL \rNAUSEA, SWEATS AND DIZZY, FEMALE IS STILL BREATHING , CONSCIOUS 
(Dispatch Message) SQUAD CALL-GENERAL  \r102  LAUREL RD   S RUSSELL \rFEMALE IN HER 90'S, HAS FALLEN A COUPLE OF TIMES, CONSTANT PAIN 
(Dispatch Message) SQUAD CALL-GENERAL  \n\nIND/ RED HELP BUTTON PRESSED, NO RESPONSE FROM 
(Dispatch Message) SQUAD CALL-GENERAL  \r5188  CHILLICOTHE RD   S RUSSELL \r35 YR OLD MALE WITH CHEST PAINS  SITTING IN A CHEVY VAN 
(Dispatch Message) SQUAD CALL-GENERAL  \r35  HIGH COURT   CHAGRIN FALL \rELDERLY MALE VOMITING & BLOODY STOOL 
(Dispatch Message) SQUAD CALL-GENERAL  \r31  SOUTH ST    CHAGRIN FALL \rFEMALE DISORIENTED 
(Dispatch Message) GAS ODOR  \r32605  JACKSON RD    MORELAND HIL \rVEHCILE RAN OVER GAS METER GAS IS IN THE AIR 
(Dispatch Message) MVA-INJURY \r5000  CHAGRIN RIVER    MORELAND HIL \rPER ANDY WEINGART 440 623 9069 PORS INTO A GUARD RAIL 
(Dispatch Message) ASSIST-FIRE DEPARTMENT  \r  E WASHINGTON ST    CHAGRIN FALL \rAT RIDGEWOOD FOR A POSSIBLE FUEL SPILL 
(Dispatch Message) SQUAD CALL-GENERAL  \r551  E WASHINGTON ST   S RUSSELL \r84YOM RECTAL BLEED, SEVERE STOMACH PAIN 
(Dispatch Message) SQUAD CALL-GENERAL \r34114  CHAGRIN BLVD  8106 \rELDERLY MALE FELL AND IS BLEEDING  CON/BREATH 
(Dispatch Message) ALARMS-FIRE \r35  TARTAN CT  \rGILMORE SECURITY OPR/50  440-232-6458\nIND/ GENERAL 
(Dispatch Message) SQUAD CALL-GENERAL \r40  WHITETAIL LANE   \rMALE FELL OFF SKATE BOARD\nBLEEDING FROM HEAD\nANNIE 440-552-9766 
(Dispatch Message) SQUAD CALL-GENERAL \r41  WHITETAIL LANE   \rMALE FELL OFF SKATE BOARD\nBLEEDING FROM HEAD 
(Dispatch Message) SQUAD CALL-GENERAL \r38879  BERKELEY AVE   \r88 YEAR OLD FEMALE FELL ON THE PATIO HIT HER HEAD 
(Dispatch Message) SQUAD CALL-GENERAL \r33001  SOLON RD  202 \rMUTUAL AID FOR SOLON 
(Dispatch Message) SQUAD CALL-GENERAL \r551  E WASHINGTON ST  \r44 year old make chest pains atrial flutter 
(Dispatch Message) SQUAD CALL-GENERAL \r551  E WASHINGTON ST  \rMALE CHEST PAINS 
(Dispatch Message)  \r49  W ORANGE ST   \r27 YOA FEMALE HAVING A SEIZURE 
(Dispatch Message) SQUAD CALL-GENERAL \r111  HAMLET HILLS DR  22 \rELDERLY MALE CATH PROBLEMS 
(Dispatch Message) SQUAD CALL-GENERAL \r551  E WASHINGTON  \rFEMALE POSSIBLE HEART ATTACK IN THE URGENT CARE 
(Dispatch Message) SQUAD CALL-GENERAL \r21  W WASHINGTON ST  \rMALE WITH CHEST PAINS 
(Dispatch Message)  \n200  HAMLET HILLS DR  \nMEDICAL EMERGENCY\nMUTUAL AID  FROM BAINBRIDGE FD 
(Dispatch Message) SQUAD CALL-GENERAL \r200  HAMLET HILLS DR  \rELDERLY  MALE HAVING LEG PAIN, CONSCIOUS AND BREATHING 
(Dispatch Message) SQUAD CALL-GENERAL \r108  FAIRVIEW RD   \r 86 elderly female dizzy unable to be steady on her feet 
(Dispatch Message) GAS ODOR \r45  STERNCREST DR   \rILLUMINATING CO REPORT TO OVFD A SMELL OF NATURAL GAS FROM THE ABOVE LOCATION 
(Dispatch Message) FIRE- GENERAL \r6005  PARKLAND DR   \rGAS GRILL UNABLE TO BE TURNED OFF, NATURAL GAS GRILL IS NEAR THE HOUSE 
(Dispatch Message) SQUAD CALL-GENERAL \r40  FARWOOD DR   \rHAVING TROUBLE BREATHING\n 
(Dispatch Message) SQUAD CALL-GENERAL \r200  HAMLET HILLS DR  109 \rELDERLY FEMALE FEELING NUMB 
(Dispatch Message) SQUAD CALL-GENERAL \r85  WILLOW WOOD LN   \rELDERLY FEMALE HIP INJURY 
(Dispatch Message) FIRE- GENERAL \r100  N MAIN ST  \rLIGHT IN CEILING CAUGHT ON FIRE IS NOW OUT 
(Dispatch Message) SQUAD CALL-GENERAL \n31  SOUTH ST   \nFEMALE PASSED OUT NOW CONSCIOUS, HIGH BLOOD PRESSURE
(Dispatch Message) SQUAD CALL-GENERAL \r200  HAMLET HILLS DR  213 \rMALE WHO HAS FALLEN 
(Dispatch Message) ALARMS-CO DETECTOR \r65  OLIVE ST   \rALARM READING GAS ALARM, NO SYMPTOMS EVACUATED 
(Dispatch Message) SQUAD CALL-GENERAL \r20  STONEWOOD DR  \rELDERLY FEMALE POSSIBLE HEART ATTACK 
(Dispatch Message) SQUAD CALL-GENERAL \r200  HAMLET HILLS DR  221 \rFEMALE LEG PAIN 
(Dispatch Message) ALARMS-FIRE \r1082  BELL RD  \rENTRY GUARD 2800-443-8865\nIND/GEN FIRE \nOPR/412 
(Dispatch Message) BOX 100 \rSOM CENTER RD  HIRAM TRL   \rOVFD REQUESTED BOX 100 MABAS ALARM 
(Dispatch Message) SQUAD CALL-GENERAL \r551  E WASHINGTON ST  \rBLOOD CLOT IN HER LEG & POSSIBLE IN THE LUNGS, BREATHING & CONCIOUS 
(Dispatch Message) SQUAD CALL-GENERAL \r115  ASPENWOOD DR  \r85 YR OLD MALE , SEVERE ABDOMINAL PAIN FROM A HERNIA 
(Dispatch Message) SQUAD CALL-GENERAL \r SQUAW ROCK  \rFEMALE IN PARKING LOT WITH FACE INJURY 
(Dispatch Message) FIRE- GENERAL \r36850  CHAGRIN BLVD   \rFISH TANK CAUGHT FIRE\nFIRE IS EXTINGUISHED \nHOUSE FULL OF SMOKE 
(Dispatch Message) ASSIST-FIRE DEPARTMENT \r40  FARWOOD DR   \rLAMP IS MAKING A NOISEg 
(Dispatch Message) SQUAD CALL-GENERAL \r206  HAMLET HILLS DR  89 \rMALE RESIDENT HAS FALLEN 
(Dispatch Message) SQUAD CALL-GENERAL \r125  MURWOOD DR   \r87 YRO FEMALE , CONGESTIVE HEART FAILURE, UNRESPONSIVE 
(Dispatch Message) MUTUAL AID, GIVEN \r13665  AQUILLA RD   \rBURTON FD ACTIVATING THE GEAUGA PORTAGE WATER SHUTTLE FOR A HOUSE FIRE 
(Dispatch Message) SQUAD CALL-GENERAL \r102  LEAVIEW LN   \r71 YRO MALE FELL AND IS BLEEDING FROM HIS HAND AND ABOVE THE EYE 
(Dispatch Message) ALARMS-FIRE \r6000  NOB HILL DR   \rFIRE ALARM SOUNDING 
(Dispatch Message) ALARMS-MEDICAL \n157  CARRIAGE DR  103 \nUNABLE TO MAKE CONTACT WITH PATIENT 
(Dispatch Message) SQUAD CALL-GENERAL \r  BELL TOWER CT   \rFEMALE BROKEN ANKLE, MEET AT BACK OF CONDOS NEAR FENCE 
(Dispatch Message) SQUAD CALL-GENERAL \r40  E WASHINGTON ST   \rELDERLY HAS FALLEN BLEEDING FROM THE HEAD 
(Dispatch Message)  \r35550  FAIRMOUNT BLVD   \r91 YOA MALE FELL HIT HEAD. BLEEDING FROM HEAD AND HAND 
(Dispatch Message) COMPLAINTS-GENERAL \nBELL ST  MAIN ST   \nMALE UNCON SQUAD REQUEST 
(Dispatch Message) SQUAD CALL-GENERAL \r45  E JUNIPER LN   \rEVALUATION ON A 46 YOA FEMALE 
(Dispatch Message) SQUAD CALL-GENERAL \n36400  S WOODLAND RD   \nCALLER ADVISED THE TRACTOR FLIPPED OVER ON RIDER
(Dispatch Message) SQUAD CALL-GENERAL \n200  HAMLET HILLS DR  201 \nCARE CENTER\nOPR : 451 \n800-508-6370\n87 YR OLD FEMALE HAS FALLEN ,
(Dispatch Message) SQUAD CALL-GENERAL \r604  DOE CT   \r15 yr old female semi concios, breathing 
(Dispatch Message) SUSPICION \r395  BELL ST   \rINTOX MALE IN BOOKING 
(Dispatch Message) SQUAD CALL-GENERAL \r RIVERSIDE PARK  \rMALE PASSED OUT 

Contact: Active911
Agency name: Orange Village Fire Department
Location: Orange Village, OH, United States
Sender: dispatch@chagrinfallspd.com

(Dispatch Message) SQUAD CALL-GENERAL  \r  271    ORANGE \rASSISTING DISABLED PRIVATE ABULANCE SERVICE\nWITH A TRANSPORT 
(Dispatch Message) SQUAD CALL-GENERAL \r3909  ORANGE PLACE   ORANGE \r60 YR OLD FEMALE POSSIBLE STROKE IN THE URGENT CARE 
(Dispatch Message) SQUAD CALL-GENERAL  \r3909  ORANGE PLACE   ORANGE \rMALE BLOOD CLOT IN HIS LUNGS 
(Dispatch Message) MANPOWER PAGE, DOUBLE SQUAD CALL. MANPOWER TO STATION
(Dispatch Message) SQUAD CALL-GENERAL  \r3909  ORANGE PLACE  1100  ORANGE \r60YOF HYPOTENSIVE 
(Dispatch Message) SQUAD CALL-GENERAL  \r3909  ORANGE PLACE   ORANGE \r79 YR OLD FEMALE , CHEST PAINS IN THE URGENT CARE 
(Dispatch Message) SQUAD CALL-GENERAL  \r28149  MILES RD   ORANGE \rFEMALE NOT FEELING WELL, DIABETIC NOT FEELING 
(Dispatch Message) SQUAD CALL-GENERAL  \r3809  WALNUT HILLS RD    ORANGE \r60 YOA MALE WEAK AND VOMITING 
(Dispatch Message)   \r       \r60 YOA MALE WEAK AND VOMITING 
(Dispatch Message) SQUAD CALL-GENERAL  \r3909  ORANGE PLACE  2400  ORANGE \r55 YR OLD FEMALE, SHORTNESS OF BREATH 
(Dispatch Message) ASSIST-FIRE DEPARTMENT  \r3920  WILDCHERRY TRL     \rper oe5 they are enroute to above for an odor invest 
(Dispatch Message) MVA \r4486  BRAINARD RD    ORANGE \rcar into pole driver bleeding 
(Dispatch Message) SQUAD CALL-GENERAL  \n3755  ORANGE PLACE  102  ORANGE \nFEMALE, SEVERE PAIN IN LEFT LEG 
(Dispatch Message) SQUAD CALL-GENERAL  \r28850  HARVARD RD    ORANGE \rPHSY EVAL 
(Dispatch Message) SQUAD CALL-GENERAL  \r27500  EMERY RD    ORANGE \rmale not breathing 
(Dispatch Message) SQUAD CALL-GENERAL  \r205  HAMLET HILLS DR  75  CHAGRIN FALL \rFEMALE FELL DIZZY 
(Dispatch Message) SQUAD CALL-GENERAL  \r29600  CHAGRIN BLVD   ORANGE \rFEMALE WITH LOW BLOOD PRESSURE 
(Dispatch Message) SQUAD CALL-GENERAL  \r3909  ORANGE PLACE   ORANGE \rURGENT CARE / FEMALE WITH CHEST PAINS 
(Dispatch Message) SQUAD CALL-GENERAL  \r3909  ORANGE PLACE   ORANGE \rMALE IN SERVERE PAIN FROM AN MVA 
(Dispatch Message) SQUAD CALL-GENERAL  \r4120  LANDER RD     \rPOSSIBLE DOA 
(Dispatch Message) SQUAD CALL-GENERAL  \r3909  ORANGE PLACE   ORANGE \rSUITE 3300\nFEMALE LOW BP, HAD PASSED OUT 
(Dispatch Message) SQUAD CALL-GENERAL  \r29600  CHAGRIN BLVD   ORANGE \rFEMALE HAD A PLATE FALL ON HER FOOT, IT IS STARTING TO SWELL 
(Dispatch Message) ALARMS-FIRE \r4009  ORANGE PLACE  \rSTANLEY SECURITY  8006894984  OP:195\nINIDCATION: ZONE 16 GENERAL WATER FLOW ALARM 
(Dispatch Message) SQUAD CALL-GENERAL \r31599  WOODCREST DR   \rMALE DIFFICULTY BREATHING,SWEATING 
(Dispatch Message) SQUAD CALL-GENERAL \r27099  EMERY RD  \rDIF BREATHING 
(Dispatch Message) SQUAD CALL-GENERAL \r3909  ORANGE PLACE  \rFEMALE CHEST PAINS  IN THE URGENT CARE 
(Dispatch Message) FIRE- GENERAL \r30600  EMERY RD   \rSTRANGE ODOR 
(Dispatch Message) SQUAD CALL-GENERAL \r3655  ORANGE PLACE  \r45 YOA MALE PASSED OUT 
(Dispatch Message) SQUAD CALL-GENERAL \n4709  LANDER RD   \nELDERLY MALE OUT OF WHEELCHAIR , STERNCREST SIDE DRIVEWAY
(Dispatch Message) SQUAD CALL-GENERAL \r27500  EMERY RD   \rMALE SEVER CRAMPING 
(Dispatch Message) SQUAD CALL-GENERAL \r27500  EMERY RD   \rMALE STOMACH PAINS 
(Dispatch Message) SQUAD CALL-GENERAL \r4600  LANDER RD  \rIN ORANGE VILLAGE HALL, MALE HAVING AN ALLERGIC REACTION 
(Dispatch Message) SQUAD CALL-GENERAL \r3909  ORANGE PLACE  2500 \r36 YR OLD FEMALE ABDOMINAL BLEEDING, CONCIOUS & BREATHING 
(Dispatch Message) \n3909  ORANGE PLACE   \n78 YEAR OLD MEAL HIGH FEVER AND HAVING TROUBLE BREATHNG
(Dispatch Message) SQUAD CALL-GENERAL \r3909  ORANGE PLACE   \rDISORIENTED FEMALE IN THE URGENT CARE 
(Dispatch Message) SQUAD CALL-GENERAL \r3909  ORANGE PLACE  \r65 YR OLD FEMALE, ABNORMAL LAB, LEFT ARM NUMBNESS 
(Dispatch Message) SQUAD CALL-GENERAL \n3909  ORANGE PLACE  \n57 YEAR OLD MALE CHEST PAINS URGENT CARE
(Dispatch Message) SQUAD CALL-GENERAL \r29600  CHAGRIN BLVD  \rFEMALE HAS FALLEN IN THE DINING ROOM, UNKNOWN INJURIES 
(Dispatch Message) SQUAD CALL-GENERAL \r3909  ORANGE PLACE  3300 \rMALE ALMOST PASSED OUT, POSSIBLE LOW GLUCOSE 
(Dispatch Message) SQUAD CALL-GENERAL \r3655  ORANGE PLACE  \rFEMALE SIEZING IN THE LOBBY 
(Dispatch Message) SQUAD CALL-GENERAL \r4545  BRAINARD RD  \r2 YR SEIZING 
(Dispatch Message) SQUAD CALL-GENERAL \r4189  LANDER RD   \rLAUREN MAROTTA 216-570-5098\nPAIN IN STOMACH 
(Dispatch Message) MUTUAL AID, GIVEN \r3999  RICHMOND RD  \rMUTUAL AID REQUESTED FOR A POSSIBLE FIRE ROOM 3222 GARDEN LEVEL 
(Dispatch Message) MUTUAL AID, GIVEN \r70  BASSWOOD LN  \rADT 888-294-6736\nIND/WATER FLOW\nOPR/RODGER 
(Dispatch Message) MUTUAL AID, GIVEN \n32450  CHESTNUT   SMOKE IN BASEMENT\nTO SCENE, FAIRMOUNT TO SNOWBERRY TO CHESTNUT
(Dispatch Message) SQUAD CALL-GENERAL \n27250  EMERY RD  \n SQUAD ADVISNG THEY ARE PREPARING TO TRANSOPORT A MALE WITHA  HEAD INJURY
(Dispatch Message) ALARMS-FIRE \n3625  ORANGE PLACE  \nIND FIRE ALARM.
(Dispatch Message) SQUAD CALL-GENERAL \r4809  E FAIRVIEW DR   \rELDERLY FEMALE BLOOD PRESSURE IS VERY HIGH 
(Dispatch Message) SQUAD CALL-GENERAL \r28950  HARVARD RD   \rFEAMLE POSSIBLE STROKE 
(Dispatch Message) ALARMS-FIRE \r4600  LANDER RD  \rCALL COMM\nOPR : BRANDON\n800-498-7565\nIND : GEN FIRE 
(Dispatch Message) ALARMS-MEDICAL \r28900  PIKE DR  \rCARE  CENTER 800-508-6370\nIND/CANNOT GET UP/POSSIBLE INVALID ASSIST\nOPR/230 
(Dispatch Message) ALARMS-CO DETECTOR \r270  BLOSSOM LN  \rWOULD LIKE RES CHECKED\nSTATE 800 321 7400 OP/JESSI 
(Dispatch Message) SQUAD CALL-GENERAL \n28900  PIKE DR  \nTHE CARE CENTER\n800-508-6370\nELDERLY FEMALE HAS FALLEN, NEEDS ASSISTANCE  
(Dispatch Message) SQUAD CALL-GENERAL \r30549  HARVARD RD   \rMALE ON OXYGEN, DIFFICULTY BREATHING 
(Dispatch Message) SQUAD CALL-GENERAL \r3909  ORANGE PL   \r53 YOA FEMALE  ALLERGIC REACTION URGENT CARE 
(Dispatch Message) INTOX FEMALE BLEEDING FROM THE ARM\nPD ON SCEN
(Dispatch Message) SQUAD CALL-GENERAL \n27599  EMERY RD   \nFEMALE HAVING A HARD TIME BREATHING 
(Dispatch Message) FIRE- AUTO \r  271   \r271 NB EXPRESS LANES, BOX TRUCK ON FIRE 
(Dispatch Message) SQUAD CALL-GENERAL \r28940  HIDDEN VALLEY   \rLIFELINE 888.289.2018\nIND/FEMALE MEDICAL EMERGENCY\nOPR/LUCY\n 
(Dispatch Message) SQUAD CALL-GENERAL \r110  VALENCIA CIR   \rFEMALES CAR ROLLED OVER HER LEG 
(Dispatch Message) ALARMS-FIRE \r150  BLOSSOM LN   \rSTATE ALARM 781 2224 INDICTING SMOKE DETECTOR SUB LOT 87 OPR/BEVERLY 
(Dispatch Message) SQUAD CALL-GENERAL \r29600  CHAGRIN BLVD  \r91 yr old female, fell, sore. Main club house. 
(Dispatch Message) DOMESTIC \r30200  SMITHFIELD RD   \rHER SON IS VIOLENT AND ATTACKING HER HUSBAND HE \n\n05/07/2013 20:47:10 Disp  MLR  \nOFFICERS HAVE MALE RESTRAINED AT THIS 
(Dispatch Message) MUTUAL AID, GIVEN \r31200  EMERY RD   \rMUTUAL AID SQUAD FEMALE LOW BLOOD PRESSURE, UNRESPONSIVE 
(Dispatch Message) SQUAD CALL-GENERAL \r3909  ORANGE PLACE  \rFEMALE DIZZINESS AND WEAKNESS IN THE URGENT CARE 
(Dispatch Message) SQUAD CALL-GENERAL \r27599  EMERY RD   \r92 YRO FEMALE WEAK NOT FEELING WELL 
(Dispatch Message) ASSIST-FIRE DEPARTMENT \r3909  ORANGE PLACE  \rSMOLDERING BROWN GARBAGE CAN OUTSIDE BY URGENT CARE 
(Dispatch Message) STALKING \r3909  ORANGE PLACE  \r6 MONT OLD MALE, URGENT CARE, DIFFICULTY BREATHING 
(Dispatch Message) ALARMS-FIRE \r3840  ORANGE PLACE  \rGENERAL FIRE ALARM SHOWING GUEST ROOM 
(Dispatch Message) SQUAD CALL-GENERAL \r29179  EMERY RD   \r79 YR OLD FEMALE FELL  HIT HEAD AND RIBS 
(Dispatch Message) MUTUAL AID, REQUESTED \r70  WINDING RIVER   \rSQUAD NEEDED / BOX ALARM 
(Dispatch Message) SQUAD CALL-GENERAL \r3909  ORANGE PLACE  \r3 YR OLD RESPIRATORY DISTRESS 
(Dispatch Message) ALARMS-CO DETECTOR \r64  W STONEBROOK DR   \r 
(Dispatch Message) SQUAD CALL-GENERAL \r3909  ORANGE PLACE   \rFEMALE IN A WHITEW MINI VAN PARKED OUT FRONT,PHYSCH  PATIENT, REFUSING TRANSPORT 
(Dispatch Message) SQUAD CALL-GENERAL \r3909  ORANGE PLACE  \rIN THE URGENT CARE, MALE WITH ABNORMAL EKG & CHEST PAINS 
(Dispatch Message) SQUAD CALL-GENERAL \r3655  ORANGE PLACE  \r3 YEAR OLD HAVING A SEIZURE 
(Dispatch Message) SQUAD CALL-GENERAL \r3909  ORANGE PLACE   \rFEMALE SHORT OF BREATH 
(Dispatch Message) SQUAD CALL-GENERAL \r3880  BRAINARD RD   \rCARE GIVER REPORTS PATIENT, ELDERLY FEMALE, HALLUCINATING SUGAR DROPPING\n216-926-9695 
(Dispatch Message) SQUAD CALL-GENERAL \r3880  BRAINARD RD   \rELDERLY FEMALE, HALLUCINATING SUGAR DROPPING 
(Dispatch Message) SQUAD CALL-GENERAL \r30049  MILES RD   \rMALE POSSIBLE STOKE 
(Dispatch Message) SQUAD CALL-GENERAL \r3695  ORANGE PLACE  \r61 YRO MALES COLLAPSED, NOW CONSCIOUS AND BREATHING 
(Dispatch Message) SQUAD CALL-GENERAL \r3795  ORANGE PLACE  269 \rFEMALE IN LABOR, WATER BROKEN 
(Dispatch Message) ALARMS-FIRE \r3840  ORANGE PLACE  \rSTATE ALARM 781 2224 INDICATING GENERAL FIRE ALARM OPR/BEVERLY 
(Dispatch Message) SQUAD CALL-GENERAL \r3860  PINE CREST DR  \r82 YR OLD MALE HAS FALLEN, WIFE CANNOT GET HIM UP 
(Dispatch Message) SQUAD CALL-GENERAL \r29699  HARVARD RD   \r93 YRO FEMALE WITH SEVERE STOMACH PAINS, DIARREA 
(Dispatch Message) SQUAD CALL-GENERAL \r3883  LANDER RD  1 \rFEMALE NEEDS INVALID ASSIST WHO HAS FALLEN OUT OF BED\nCHESTNUT COURT 
(Dispatch Message) SQUAD CALL-GENERAL \r3795  ORANGE PLACE  \rMALE TOOK MEDICINE , UNRESPONSVIE BUT BREATHING 

*/

public class OHCuyahogaCountyParserTest extends BaseParserTest {
  
  public OHCuyahogaCountyParserTest() {
    setParser(new DummyParser(), "CUYAHOGA COUNTY", "OH");
  }
  
  @Test
  public void testParser() {

   
  }
  
  public static void main(String[] args) {
    new OHCuyahogaCountyParserTest().generateTests("T1");
  }
}