cnpxntr arg.narv.pnqcntr.cnefref.MAM;

vzcbeg arg.narv.pnqcntr.cnefref.OnfrCnefreGrfg;

vzcbeg bet.whavg.Grfg;

/*
Arj Mrnynaq

Pbagnpg: Npgvir911
Ntrapl anzr: XNZB IBYHAGRRE SVER OEVTNQR
Ybpngvba: Junatnerv, Abeguynaq, Arj Mrnynaq
Fraqre: fvyi@ibqnsbar.pb.am

(XNZB191, XNZB192, JUNA124) CBYVPR-FGEH (Obk -19-04) UHEHCNXV FPUBBY 20 QVC EQ XNZB. (KFge GUERR ZVYR OHFU EQ/VGV FG) .EBBS SVER. #S1269133
(XNZB192) 111-ZVA 58 RQRA GPR XNZB. (KFge ZNEVCBFN CY/YBTNA CY) .PNECBEG BA SVER CERFFHZRQ BHG BCC. #S1269009
(XNZB191) 111-ZVA (Obk -P) ZREEVINYR ERFG UBZR 1 JVATRE PE XNZB. (KFge TERNG ABEGU EQ/) .NYNEZF FBHAQVAT AFBS. #S1268810
(XNZB191) 111-ZVA FGNGVBA EQ XNZB. (KFge PBYRAFB FG/RQRA GPR) .EHOOVFU SVER. #S1268584
(XNZB191) FRPHEVGL-ZVA SVER FGNGVBA XNZB 591 XNZB EQ XNZB. (KFge FGNGVBA EQ/ZRYQEHZ FG) .FRPHEVGL NYNEZ NPGVINGVBA. #S1267278
(XNZB192) 111-IRT SVER FGNGVBA XNZB 591 XNZB EQ XNZB. (KFge FGNGVBA EQ/ZRYQEHZ FG) .PNA FRR FZBXR BA UVYY ORUVAQ SVER FGNGVBA. #S1265742
(XNZB191) 111-ZVA 23N PENJSBEQ PE XNZB. (KFge JRAGJBEGU CY/VGV FG) .SYBBQVAT. #S1265475
(XNZB192) 111-ZVA 9 SERRUBYQ YN XNZB. (KFge CNEXYNAQ PE/) .NYNEZ FBHAQVAT ..... FBH. #S1264144
(XNZB191) CBYVPR-IRT (Obk -19-9) JUNATNERV TBYS PYHO HAXA0001 QRAOL PE GVXVCHATN. (KFge ZNELYNAQ CY/JNANXN FG) .GERR SVER CBYVPR BA FPRAR. #S1264023
(XNZB192) 111-ZVA TERNG ABEGU EQ XNZB. (KFge JVATRE PE/) .FZBXR VA IVPVAVGL. #S1263510
(XNZB191) 111CZP-ZVA 3456 CVCVJNV EQ CVCVJNV. (KFge URANER EQ/CNGHGNUV EQ) .NYNEZ NPGVINGVBA - ERFVQRAGVNY. #S1260433

Pbagnpg: Npgvir911
Ntrapl anzr: Sver Freivpr
Ybpngvba: Ubofbaivyyr, Nhpxynaq, Arj Mrnynaq
Fraqre: cntre@sverubhfr.pb.am

(GRNG664, GRNG662, JNVG671) 111-FGEH URAQREFBA. (KFge HAVIREFNY QE/ENGUTNE EQ) .JNYX JNL OEVQTR BA SVER. #S1269217
(JNVG672) 111-ZVA 65 TNEGBA QE ZNFFRL. (KFge YNAUNZ YN/OEBNQSVRYQ FG) .GENAFSBEZRE BA SVER . #S1268928
(JNVG671, JNVG672, GRNG664) CSN-FCEAXYE (Nynez Glcr GUREZNY/FZ) (Obk -P67-4) JRFGOEVQTR ERFVQRAGVNY FPUBBY 488R QBA OHPX EQ ZNFFRL. ARNE ORNHPUNZC EQ. (KFge ORNHPUNZC QE/EHFU PERRX QE) #S1268862
(JNVG671, JNVG672) 111-FGEH UBOFBAIVYYR NVESBEPR ONFR AHYY UBOFBAIVYYR. (KFge OHPXYRL NI/FHAQREYNAQ NI) .NYNEZ NPGVINGVBA NG FHAQREYNAQ UNATRE. #S1268724
(JNVG671) 111-SVERGRFG SVER FGNGVBA JNVGRZNGN 21 UBOFBAIVYYR EQ JRFG UNEOBHE. (KFge UBOFBAIVYYR EQ BA-ENZC/BERVY NI) .FVERA NAQ CNTRE GRFG BAYL QB ABG ERFCBAQ. #S1268365
(URAQ657, JNVG671) 111-ERFP (Obk -P67-9) ZNFFRL UVTU FPUBBY 274 QBA OHPX EQ ZNFFRL. (KFge TNYYBAL NI/PUREEL GERR CY) .2 PNE ZIN EBNQ PYRNA HC. #S1268228
(JNVG671, NYON851) CSN-FCEAXYE (Nynez Glcr ZNAHNY) (Obk -P67-24) FBIRERVTA LNPUGF AM HAXA0002 OBHAQNEL EQ UBOFBAIVYYR. (KFge ZNEYOBEBHTU PE/VEBDHBVF CY) #S1267945
(JNVG671) 111-ZVA GEVNATYR EQ ZNFFRL. (KFge ZNXBEN EQ/YVAPBYA CNEX NI) .FZRYY BS TNF. #S1267692
(GRNG664, GRNG662, JNVG671) CSN-FGEH (Nynez Glcr FCEVAXYRE) (Obk -P) FNVAG ZNETNERGF UBFCVGNY 52-60 ORNPU EQ GR NGNGH CRAVAFHYN. (KFge QHEUNZ FG/JNXNEBN NI) #S1267678
(URAQ657, JNVG671) 111-ERFP JRFG UNEOBHE FPUBBY BERVY NI JRFG UNEOBHE. (KFge SVGMUREOREG NI/FHZVPU CY) .PUVYQ SVATREF FGHPX . #S1267479
(NYON851, JNVG671) CSN-FCEAXYE (Nynez Glcr FCEVAXYRE) (Obk -P) PBZZHAVGL UBHFVAT 60 GR JUNENH QE TERRAUVGUR. (KFge BEJRYY EQ/ZBAXGBA PY) #S1267009
(GRNG664, JNVG671) CSN-FCEAXYE (Nynez Glcr FCEVAXYRE) (Obk -P) GNFGV CEBQHPGF 25-41 GBGNEN EQ GR NGNGH CRAVAFHYN. (KFge GR NGNGH EQ/UVXHENATV FG) #S1266925
(XHZR867, XHZR861, JNVG671) 111-ERFP 53 SNEENAQ EQ XHZRH. (KFge FZVGU EQ/NPPRFF EQ) .UBEFR FGHPX VA PERRX. #S1266671
(URAQ657, JNVG671) CUBAR-ERFP SERQ GNLYBE QE ZNFFRL. (KFge UBOFBAIVYYR EQ/SREAUVYY QE) .ZIN PNE I PNE. #S1266438
(NHPX2016, GRNG664, JNVG671, NHPX207) 111-UNM UVERCBBY YVAPBYA 166 PRAGENY CNEX QE URAQREFBA. (KFge PBYYNEQ CY/YVAPBYA EQ) .ZNWBE QRVFRY FCVYY. #S1266090
(NHPX2016, GRNG664, JNVG671, NHPX207) 111-UNM UVERCBBY YVAPBYA 166 PRAGENY CNEX QE URAQREFBA. (KFge PBYYNEQ CY/YVAPBYA EQ) .ZNWBE QRVFRY FCVYY. #S1266090
(GRNG664, JNVG671) CSN-FGEH (Nynez Glcr ZNAHNY) JNVGNXRER PVGL PBHAPVY ERPLPYVAT CYNAG 50 GUR PBAPBHEFR URAQREFBA. (KFge FRYJBBQ EQ/) #S1265765
(JNVG671) 111-ZVA EVIREYRN EQ JURAHNCNV. (KFge QNYR EQ/EBCR EQ) .OBA SVER PNHFVAT PBAPREA. #S1265053
(JNVG671) 111-ZVA ZBVER CNEX TENAIVYYR QE ZNFFRL. .CYNLTEBHAQ BA SVER. #S1264625
(JNVG671) 111-FGEH 751 FU 16 XHZRH. (KFge SBFGRE EQ/WBLPR NQNZF CY) .HAXABJA SVER BCCBFVGR NQQERFF. #S1264169
(JNVG671, JNVG672) 111-FGEH CNGVRAPR JNL ZNFFRL. (KFge GEVNATYR EQ/) .NYNEZ FBHAQVAT. #S1263555
(URAQ657, URAQ651, JNVG671) 111CZP-FGEH QBA OHPX FPUBBY 124 QBA OHPX EQ ZNFFRL. ARNE MVGN ZNEVN QE. (KFge NYQREA EQ/WRMREB QE) .FZBXR NYNEZ NPGVINGVBA EBBZ 11. #S1263547
(JNVG671, JNVG672, GRNG664) 111-FGEH 144 GEVNATYR EQ ZNFFRL. (KFge ZNXBEN EQ/YVAPBYA CNEX NI) .OHVYQVAT SVER NG PNYGRK. #S1262483
(JNVG671) 111-ZVA WBFRCU QHAFGNA QE GNHCNXV. (KFge GNHCNXV EQ/) .FZBXR VA IVPVAVGL. #S1261652
(JNVG671) CBYVPR-ZVA 11 GEHFPBGG CY JRFG UNEOBHE. (KFge SVGMUREOREG NI/) .FZBXR VA IVPVAVGL. #S1261529
(JNVG671) 111-ZVA ZPPYVAGBPX EQ ZNFFRL. (KFge GEVNATYR EQ/) .FZBXR NAQ SVER FUBJVAT NG RAQ BS EBNQ. #S1260977
(JNVG671, URAQ657) CSN-FCEAXYE (Nynez Glcr FCEVAXYRE) ANGHEVRF URNYGU CEBQHPGF 6 GBAL FG URAQREFBA. (KFge PRAGENY CNEX QE/) #S1260850
(ESBNHPXAGU, JNVG7771, JNVG7772, JNVG672, URAQ657) 111CZP-FGEH (Obk -77-6550) GRYRPBZ RKPUNATR JNVGNXRER 10 ZPRAGRR EQ JNVGNXRER. (KFge GBJAFUVC EQ/ABEGUSVRYQ EQ) .NYNEZ NPGVINGVBA. #S1259455
(GRNG664, GRNG662, JNVG671) 111CZP-FGEH (Obk -66-54) GRYRPBZ RKPUNATR GR NGNGH ABEGU 410 BYQ GR NGNGH EQ GR NGNGH CRAVAFHYN. (KFge GBEH FG/CNEXINYR TE) .NYNEZ NPGVINGVBA. #S1259454
(JNVG671, GRNG664) 111-FGEH 11 CNGVRAPR JNL ZNFFRL. (KFge GEVNATYR EQ/) .UBHFR SVER. #S1259309
(XHZR861, XHZR867, JNVG671) CSN-FGEH (Nynez Glcr FZBXR) (Obk -P86-13) PBAFGRYYNGVBA AM PBZCYRK 45 FGNGVBA EQ UHNCNV. (KFge ZNVA EQ/ABOVYB EQ) #S1258539
(URAQ657, JNVG671) 111-FGEH GUR JNERUBHFR YVAPBYA PRAGER 111 YVAPBYA EQ URAQREFBA. (KFge JBBQSBEQ NI/SNVEQRAR NI) .FZBXR PBZVAT SEBZ YVTUG. #S1258213
(JNVG671) 111-ANG JRFG UNEOBHE YBQTR 499 QBA OHPX EQ ZNFFRL. (KFge ORNHPUNZC QE/EHFU PERRX QE) .GERR NPEBFF QEVIRJNL. #S1257608
(JNVG671) 111-ANG 19 OEVQTRURNQ PBIR JRFG UNEOBHE. (KFge UNEOBHE YVTUGF PY/) .EBBS YVSGVAT. #S1257545
(JNVG7771, JNVG671) 111-ANG 91 JNVGNXRER EQ JNVGNXRER. (KFge ABEGUSVRYQ EQ/GBJAFUVC EQ) .GERR BAGB UBHFR . #S1257341
(JNVG672) 111-ANG UBOFBAIVYYR EQ JRFG UNEOBHE. (KFge UBOFBAIVYYR EQ BA-ENZC/) .GERR QBJA RKVG ENZC JRFG TNGR. #S1257250
(JNVG671) ENQVB-ZVA 90 BEVRY NI JRFG UNEOBHE. (KFge FHZVPU CY/ZBVER EQ) .BVY FCVYY. #S1257095
(JNVG671) 111CZP-ZVA 2 CEVAPRFF ZNEVN CY ZNFFRL. (KFge DHRRA ANGNYVR CY/) .NYNEZ NPGVINGVBA - ERFVQRAGVNY. #S1257093
(JNVG671) 111-ZVA SVER FGNGVBA JNVGRZNGN 21 UBOFBAIVYYR EQ JRFG UNEOBHE. (KFge UBOFBAIVYYR EQ BA-ENZC/BERVY NI) .YNETR SVER VA ERNE BS LNEQ. #S1256968
(JNVG671, GRNG664) 111-FGEH 195R QBA OHPX EQ ZNFFRL. (KFge PUNZOREYNVA EQ/QBABINA NI) .FGBIR BA SVER . #S1255305
(XHZR867, XHZR861, JNVG671) 111-ERFP XHZRH. (KFge FU 16/EVIREURNQ EQ) .ZIN . #S1255174

*/

choyvp pynff MAMArjMrnynaqCnefreGrfg rkgraqf OnfrCnefreGrfg {
  
  choyvp MAMArjMrnynaqCnefreGrfg() {
    frgCnefre(arj MAMArjMrnynaqCnefre(), "", "");
  }
  
  @Grfg
  choyvp ibvq grfgXnzbSver() {

    qbGrfg("G1",
        "(XNZB191, XNZB192, JUNA124) CBYVPR-FGEH (Obk -19-04) UHEHCNXV FPUBBY 20 QVC EQ XNZB. (KFge GUERR ZVYR OHFU EQ/VGV FG) .EBBS SVER. #S1269133",
        "HAVG:XNZB191, XNZB192, JUNA124",
        "PBQR:CBYVPR-FGEH",
        "OBK:-19-04",
        "CYNPR:UHEHCNXV FPUBBY",
        "NQQE:20 QVC EQ",
        "PVGL:XNZB",
        "K:GUERR ZVYR OHFU EQ/VGV FG",
        "PNYY:EBBS SVER",
        "VQ:S1269133");

    qbGrfg("G2",
        "(XNZB192) 111-ZVA 58 RQRA GPR XNZB. (KFge ZNEVCBFN CY/YBTNA CY) .PNECBEG BA SVER CERFFHZRQ BHG BCC. #S1269009",
        "HAVG:XNZB192",
        "PBQR:111-ZVA",
        "NQQE:58 RQRA GPR",
        "PVGL:XNZB",
        "K:ZNEVCBFN CY/YBTNA CY",
        "PNYY:PNECBEG BA SVER CERFFHZRQ BHG BCC",
        "VQ:S1269009");

    qbGrfg("G3",
        "(XNZB191) 111-ZVA (Obk -P) ZREEVINYR ERFG UBZR 1 JVATRE PE XNZB. (KFge TERNG ABEGU EQ/) .NYNEZF FBHAQVAT AFBS. #S1268810",
        "HAVG:XNZB191",
        "PBQR:111-ZVA",
        "OBK:-P",
        "CYNPR:ZREEVINYR ERFG UBZR",
        "NQQE:1 JVATRE PE",
        "ZNQQE:1 JVATRE PERF",
        "PVGL:XNZB",
        "K:TERNG ABEGU EQ",
        "PNYY:NYNEZF FBHAQVAT AFBS",
        "VQ:S1268810");

    qbGrfg("G4",
        "(XNZB191) 111-ZVA FGNGVBA EQ XNZB. (KFge PBYRAFB FG/RQRA GPR) .EHOOVFU SVER. #S1268584",
        "HAVG:XNZB191",
        "PBQR:111-ZVA",
        "NQQE:FGNGVBA EQ",
        "ZNQQE:FGNGVBA EQ & PBYRAFB FG",  // Abg znccvat
        "PVGL:XNZB",
        "K:PBYRAFB FG/RQRA GPR",
        "PNYY:EHOOVFU SVER",
        "VQ:S1268584");

    qbGrfg("G5",
        "(XNZB191) FRPHEVGL-ZVA SVER FGNGVBA XNZB 591 XNZB EQ XNZB. (KFge FGNGVBA EQ/ZRYQEHZ FG) .FRPHEVGL NYNEZ NPGVINGVBA. #S1267278",
        "HAVG:XNZB191",
        "PBQR:FRPHEVGL-ZVA",
        "CYNPR:SVER FGNGVBA XNZB",
        "NQQE:591 XNZB EQ",
        "PVGL:XNZB",
        "K:FGNGVBA EQ/ZRYQEHZ FG",
        "PNYY:FRPHEVGL NYNEZ NPGVINGVBA",
        "VQ:S1267278");

    qbGrfg("G6",
        "(XNZB192) 111-IRT SVER FGNGVBA XNZB 591 XNZB EQ XNZB. (KFge FGNGVBA EQ/ZRYQEHZ FG) .PNA FRR FZBXR BA UVYY ORUVAQ SVER FGNGVBA. #S1265742",
        "HAVG:XNZB192",
        "PBQR:111-IRT",
        "CYNPR:SVER FGNGVBA XNZB",
        "NQQE:591 XNZB EQ",
        "PVGL:XNZB",
        "K:FGNGVBA EQ/ZRYQEHZ FG",
        "PNYY:PNA FRR FZBXR BA UVYY ORUVAQ SVER FGNGVBA",
        "VQ:S1265742");

    qbGrfg("G7",
        "(XNZB191) 111-ZVA 23N PENJSBEQ PE XNZB. (KFge JRAGJBEGU CY/VGV FG) .SYBBQVAT. #S1265475",
        "HAVG:XNZB191",
        "PBQR:111-ZVA",
        "NQQE:23N PENJSBEQ PE",
        "ZNQQE:23N PENJSBEQ PERF",
        "PVGL:XNZB",
        "K:JRAGJBEGU CY/VGV FG",
        "PNYY:SYBBQVAT",
        "VQ:S1265475");

    qbGrfg("G8",
        "(XNZB192) 111-ZVA 9 SERRUBYQ YN XNZB. (KFge CNEXYNAQ PE/) .NYNEZ FBHAQVAT ..... FBH. #S1264144",
        "HAVG:XNZB192",
        "PBQR:111-ZVA",
        "NQQE:9 SERRUBYQ YN",
        "ZNQQE:9 SERRUBYQ YA",
        "PVGL:XNZB",
        "K:CNEXYNAQ PE",
        "PNYY:NYNEZ FBHAQVAT ..... FBH",
        "VQ:S1264144");

    qbGrfg("G9",
        "(XNZB191) CBYVPR-IRT (Obk -19-9) JUNATNERV TBYS PYHO HAXA0001 QRAOL PE GVXVCHATN. (KFge ZNELYNAQ CY/JNANXN FG) .GERR SVER CBYVPR BA FPRAR. #S1264023",
        "HAVG:XNZB191",
        "PBQR:CBYVPR-IRT",
        "OBK:-19-9",
        "CYNPR:JUNATNERV TBYS PYHO HAXA0001",
        "NQQE:QRAOL PE",
        "ZNQQE:QRAOL PERF & ZNELYNAQ CY", // Abg znccvat - Ercbegrq gb Tbbtyr
        "PVGL:GVXVCHATN",
        "K:ZNELYNAQ CY/JNANXN FG",
        "PNYY:GERR SVER CBYVPR BA FPRAR",
        "VQ:S1264023");

    qbGrfg("G10",
        "(XNZB192) 111-ZVA TERNG ABEGU EQ XNZB. (KFge JVATRE PE/) .FZBXR VA IVPVAVGL. #S1263510",
        "HAVG:XNZB192",
        "PBQR:111-ZVA",
        "NQQE:TERNG ABEGU EQ",
        "ZNQQE:TERNG ABEGU EQ & JVATRE PERF", // Abg znccvat
        "PVGL:XNZB",
        "K:JVATRE PE",
        "PNYY:FZBXR VA IVPVAVGL",
        "VQ:S1263510");

    qbGrfg("G11",
        "(XNZB191) 111CZP-ZVA 3456 CVCVJNV EQ CVCVJNV. (KFge URANER EQ/CNGHGNUV EQ) .NYNEZ NPGVINGVBA - ERFVQRAGVNY. #S1260433",
        "HAVG:XNZB191",
        "PBQR:111CZP-ZVA",
        "NQQE:3456 CVCVJNV EQ",
        "PVGL:CVCVJNV",
        "K:URANER EQ/CNGHGNUV EQ",
        "PNYY:NYNEZ NPGVINGVBA - ERFVQRAGVNY",
        "VQ:S1260433");

  }
  
  @Grfg
  choyvp ibvq grfgUbofbaivyyrSver() {

    qbGrfg("G1",
        "(GRNG664, GRNG662, JNVG671) 111-FGEH URAQREFBA. (KFge HAVIREFNY QE/ENGUTNE EQ) .JNYX JNL OEVQTR BA SVER. #S1269217",
        "HAVG:GRNG664, GRNG662, JNVG671",
        "PBQR:111-FGEH",
        "NQQE:HAVIREFNY QE & ENGUTNE EQ",
        "PVGL:URAQREFBA",
        "PNYY:JNYX JNL OEVQTR BA SVER",
        "VQ:S1269217");

    qbGrfg("G2",
        "(JNVG672) 111-ZVA 65 TNEGBA QE ZNFFRL. (KFge YNAUNZ YN/OEBNQSVRYQ FG) .GENAFSBEZRE BA SVER . #S1268928",
        "HAVG:JNVG672",
        "PBQR:111-ZVA",
        "NQQE:65 TNEGBA QE",
        "PVGL:ZNFFRL",
        "K:YNAUNZ YN/OEBNQSVRYQ FG",
        "PNYY:GENAFSBEZRE BA SVER",
        "VQ:S1268928");

    qbGrfg("G3",
        "(JNVG671, JNVG672, GRNG664) CSN-FCEAXYE (Nynez Glcr GUREZNY/FZ) (Obk -P67-4) JRFGOEVQTR ERFVQRAGVNY FPUBBY 488R QBA OHPX EQ ZNFFRL. ARNE ORNHPUNZC EQ. (KFge ORNHPUNZC QE/EHFU PERRX QE) #S1268862",
        "HAVG:JNVG671, JNVG672, GRNG664",
        "PBQR:CSN-FCEAXYE",
        "OBK:-P67-4",
        "CYNPR:JRFGOEVQTR ERFVQRAGVNY FPUBBY ARNE ORNHPUNZC EQ",
        "NQQE:488R QBA OHPX EQ",
        "PVGL:ZNFFRL",
        "K:ORNHPUNZC QE/EHFU PERRX QE",
        "PNYY:Nynez Glcr GUREZNY/FZ",
        "VQ:S1268862");

    qbGrfg("G4",
        "(JNVG671, JNVG672) 111-FGEH UBOFBAIVYYR NVESBEPR ONFR AHYY UBOFBAIVYYR. (KFge OHPXYRL NI/FHAQREYNAQ NI) .NYNEZ NPGVINGVBA NG FHAQREYNAQ UNATRE. #S1268724",
        "HAVG:JNVG671, JNVG672",
        "PBQR:111-FGEH",
        "CYNPR:UBOFBAIVYYR NVESBEPR ONFR AHYY",
        "NQQE:OHPXYRL NI & FHAQREYNAQ NI",
        "ZNQQE:OHPXYRL NIR & FHAQREYNAQ NIR",
        "PVGL:UBOFBAIVYYR",
        "PNYY:NYNEZ NPGVINGVBA NG FHAQREYNAQ UNATRE",
        "VQ:S1268724");

    qbGrfg("G5",
        "(JNVG671) 111-SVERGRFG SVER FGNGVBA JNVGRZNGN 21 UBOFBAIVYYR EQ JRFG UNEOBHE. (KFge UBOFBAIVYYR EQ BA-ENZC/BERVY NI) .FVERA NAQ CNTRE GRFG BAYL QB ABG ERFCBAQ. #S1268365",
        "HAVG:JNVG671",
        "PBQR:111-SVERGRFG",
        "CYNPR:SVER FGNGVBA JNVGRZNGN",
        "NQQE:21 UBOFBAIVYYR EQ",
        "PVGL:JRFG UNEOBHE",
        "K:UBOFBAIVYYR EQ BA-ENZC/BERVY NI",
        "PNYY:FVERA NAQ CNTRE GRFG BAYL QB ABG ERFCBAQ",
        "VQ:S1268365");

    qbGrfg("G6",
        "(URAQ657, JNVG671) 111-ERFP (Obk -P67-9) ZNFFRL UVTU FPUBBY 274 QBA OHPX EQ ZNFFRL. (KFge TNYYBAL NI/PUREEL GERR CY) .2 PNE ZIN EBNQ PYRNA HC. #S1268228",
        "HAVG:URAQ657, JNVG671",
        "PBQR:111-ERFP",
        "OBK:-P67-9",
        "CYNPR:ZNFFRL UVTU FPUBBY",
        "NQQE:274 QBA OHPX EQ",
        "PVGL:ZNFFRL",
        "K:TNYYBAL NI/PUREEL GERR CY",
        "PNYY:2 PNE ZIN EBNQ PYRNA HC",
        "VQ:S1268228");

    qbGrfg("G7",
        "(JNVG671, NYON851) CSN-FCEAXYE (Nynez Glcr ZNAHNY) (Obk -P67-24) FBIRERVTA LNPUGF AM HAXA0002 OBHAQNEL EQ UBOFBAIVYYR. (KFge ZNEYOBEBHTU PE/VEBDHBVF CY) #S1267945",
        "HAVG:JNVG671, NYON851",
        "PBQR:CSN-FCEAXYE",
        "OBK:-P67-24",
        "CYNPR:FBIRERVTA LNPUGF AM HAXA0002",
        "NQQE:OBHAQNEL EQ",
        "ZNQQE:OBHAQNEL EQ & ZNEYOBEBHTU PERF",
        "PVGL:UBOFBAIVYYR",
        "K:ZNEYOBEBHTU PE/VEBDHBVF CY",
        "PNYY:Nynez Glcr ZNAHNY",
        "VQ:S1267945");

    qbGrfg("G8",
        "(JNVG671) 111-ZVA GEVNATYR EQ ZNFFRL. (KFge ZNXBEN EQ/YVAPBYA CNEX NI) .FZRYY BS TNF. #S1267692",
        "HAVG:JNVG671",
        "PBQR:111-ZVA",
        "NQQE:GEVNATYR EQ",
        "ZNQQE:GEVNATYR EQ & ZNXBEN EQ",
        "PVGL:ZNFFRL",
        "K:ZNXBEN EQ/YVAPBYA CNEX NI",
        "PNYY:FZRYY BS TNF",
        "VQ:S1267692");

    qbGrfg("G9",
        "(GRNG664, GRNG662, JNVG671) CSN-FGEH (Nynez Glcr FCEVAXYRE) (Obk -P) FNVAG ZNETNERGF UBFCVGNY 52-60 ORNPU EQ GR NGNGH CRAVAFHYN. (KFge QHEUNZ FG/JNXNEBN NI) #S1267678",
        "HAVG:GRNG664, GRNG662, JNVG671",
        "PBQR:CSN-FGEH",
        "OBK:-P",
        "CYNPR:FNVAG ZNETNERGF UBFCVGNY",
        "NQQE:52-60 ORNPU EQ",
        "ZNQQE:52 ORNPU EQ",
        "PVGL:GR NGNGH CRAVAFHYN",
        "K:QHEUNZ FG/JNXNEBN NI",
        "PNYY:Nynez Glcr FCEVAXYRE",
        "VQ:S1267678");

    qbGrfg("G10",
        "(URAQ657, JNVG671) 111-ERFP JRFG UNEOBHE FPUBBY BERVY NI JRFG UNEOBHE. (KFge SVGMUREOREG NI/FHZVPU CY) .PUVYQ SVATREF FGHPX . #S1267479",
        "HAVG:URAQ657, JNVG671",
        "PBQR:111-ERFP",
        "CYNPR:JRFG UNEOBHE FPUBBY",
        "NQQE:BERVY NI",
        "ZNQQE:BERVY NIR & SVGMUREOREG NIR",
        "PVGL:JRFG UNEOBHE",
        "K:SVGMUREOREG NI/FHZVPU CY",
        "PNYY:PUVYQ SVATREF FGHPX",
        "VQ:S1267479");

    qbGrfg("G11",
        "(NYON851, JNVG671) CSN-FCEAXYE (Nynez Glcr FCEVAXYRE) (Obk -P) PBZZHAVGL UBHFVAT 60 GR JUNENH QE TERRAUVGUR. (KFge BEJRYY EQ/ZBAXGBA PY) #S1267009",
        "HAVG:NYON851, JNVG671",
        "PBQR:CSN-FCEAXYE",
        "OBK:-P",
        "CYNPR:PBZZHAVGL UBHFVAT",
        "NQQE:60 GR JUNENH QE",
        "PVGL:TERRAUVGUR",
        "K:BEJRYY EQ/ZBAXGBA PY",
        "PNYY:Nynez Glcr FCEVAXYRE",
        "VQ:S1267009");

    qbGrfg("G12",
        "(GRNG664, JNVG671) CSN-FCEAXYE (Nynez Glcr FCEVAXYRE) (Obk -P) GNFGV CEBQHPGF 25-41 GBGNEN EQ GR NGNGH CRAVAFHYN. (KFge GR NGNGH EQ/UVXHENATV FG) #S1266925",
        "HAVG:GRNG664, JNVG671",
        "PBQR:CSN-FCEAXYE",
        "OBK:-P",
        "CYNPR:GNFGV CEBQHPGF",
        "NQQE:25-41 GBGNEN EQ",
        "ZNQQE:25 GBGNEN EQ",
        "PVGL:GR NGNGH CRAVAFHYN",
        "K:GR NGNGH EQ/UVXHENATV FG",
        "PNYY:Nynez Glcr FCEVAXYRE",
        "VQ:S1266925");

    qbGrfg("G13",
        "(XHZR867, XHZR861, JNVG671) 111-ERFP 53 SNEENAQ EQ XHZRH. (KFge FZVGU EQ/NPPRFF EQ) .UBEFR FGHPX VA PERRX. #S1266671",
        "HAVG:XHZR867, XHZR861, JNVG671",
        "PBQR:111-ERFP",
        "NQQE:53 SNEENAQ EQ",
        "PVGL:XHZRH",
        "K:FZVGU EQ/NPPRFF EQ",
        "PNYY:UBEFR FGHPX VA PERRX",
        "VQ:S1266671");

    qbGrfg("G14",
        "(URAQ657, JNVG671) CUBAR-ERFP SERQ GNLYBE QE ZNFFRL. (KFge UBOFBAIVYYR EQ/SREAUVYY QE) .ZIN PNE I PNE. #S1266438",
        "HAVG:URAQ657, JNVG671",
        "PBQR:CUBAR-ERFP",
        "CYNPR:SERQ",
        "NQQE:GNLYBE QE",  // Tbbtyr xabjf guvf nf Serq Gnlybe Qe
        "ZNQQE:GNLYBE QE & UBOFBAIVYYR EQ",
        "PVGL:ZNFFRL",
        "K:UBOFBAIVYYR EQ/SREAUVYY QE",
        "PNYY:ZIN PNE I PNE",
        "VQ:S1266438");

    qbGrfg("G15",
        "(NHPX2016, GRNG664, JNVG671, NHPX207) 111-UNM UVERCBBY YVAPBYA 166 PRAGENY CNEX QE URAQREFBA. (KFge PBYYNEQ CY/YVAPBYA EQ) .ZNWBE QRVFRY FCVYY. #S1266090",
        "HAVG:NHPX2016, GRNG664, JNVG671, NHPX207",
        "PBQR:111-UNM",
        "CYNPR:UVERCBBY YVAPBYA",
        "NQQE:166 PRAGENY CNEX QE",
        "PVGL:URAQREFBA",
        "K:PBYYNEQ CY/YVAPBYA EQ",
        "PNYY:ZNWBE QRVFRY FCVYY",
        "VQ:S1266090");

    qbGrfg("G16",
        "(NHPX2016, GRNG664, JNVG671, NHPX207) 111-UNM UVERCBBY YVAPBYA 166 PRAGENY CNEX QE URAQREFBA. (KFge PBYYNEQ CY/YVAPBYA EQ) .ZNWBE QRVFRY FCVYY. #S1266090",
        "HAVG:NHPX2016, GRNG664, JNVG671, NHPX207",
        "PBQR:111-UNM",
        "CYNPR:UVERCBBY YVAPBYA",
        "NQQE:166 PRAGENY CNEX QE",
        "PVGL:URAQREFBA",
        "K:PBYYNEQ CY/YVAPBYA EQ",
        "PNYY:ZNWBE QRVFRY FCVYY",
        "VQ:S1266090");

    qbGrfg("G17",
        "(GRNG664, JNVG671) CSN-FGEH (Nynez Glcr ZNAHNY) JNVGNXRER PVGL PBHAPVY ERPLPYVAT CYNAG 50 GUR PBAPBHEFR URAQREFBA. (KFge FRYJBBQ EQ/) #S1265765",
        "HAVG:GRNG664, JNVG671",
        "PBQR:CSN-FGEH",
        "CYNPR:JNVGNXRER PVGL PBHAPVY ERPLPYVAT CYNAG",
        "NQQE:50 GUR PBAPBHEFR",
        "PVGL:URAQREFBA",
        "K:FRYJBBQ EQ",
        "PNYY:Nynez Glcr ZNAHNY",
        "VQ:S1265765");

    qbGrfg("G18",
        "(JNVG671) 111-ZVA EVIREYRN EQ JURAHNCNV. (KFge QNYR EQ/EBCR EQ) .OBA SVER PNHFVAT PBAPREA. #S1265053",
        "HAVG:JNVG671",
        "PBQR:111-ZVA",
        "NQQE:EVIREYRN EQ",
        "ZNQQE:EVIREYRN EQ & QNYR EQ",
        "PVGL:JURAHNCNV",
        "K:QNYR EQ/EBCR EQ",
        "PNYY:OBA SVER PNHFVAT PBAPREA",
        "VQ:S1265053");

    qbGrfg("G19",
        "(JNVG671) 111-ZVA ZBVER CNEX TENAIVYYR QE ZNFFRL. .CYNLTEBHAQ BA SVER. #S1264625",
        "HAVG:JNVG671",
        "PBQR:111-ZVA",
        "CYNPR:ZBVER CNEX",
        "NQQE:TENAIVYYR QE",
        "ZNQQE:ZBVER CNEX,TENAIVYYR QE",
        "PVGL:ZNFFRL",
        "PNYY:CYNLTEBHAQ BA SVER",
        "VQ:S1264625");

    qbGrfg("G20",
        "(JNVG671) 111-FGEH 751 FU 16 XHZRH. (KFge SBFGRE EQ/WBLPR NQNZF CY) .HAXABJA SVER BCCBFVGR NQQERFF. #S1264169",
        "HAVG:JNVG671",
        "PBQR:111-FGEH",
        "NQQE:751 FU 16",
        "ZNQQE:751 FGNGR 16",
        "PVGL:XHZRH",
        "K:SBFGRE EQ/WBLPR NQNZF CY",
        "PNYY:HAXABJA SVER BCCBFVGR NQQERFF",
        "VQ:S1264169");

    qbGrfg("G21",
        "(JNVG671, JNVG672) 111-FGEH CNGVRAPR JNL ZNFFRL. (KFge GEVNATYR EQ/) .NYNEZ FBHAQVAT. #S1263555",
        "HAVG:JNVG671, JNVG672",
        "PBQR:111-FGEH",
        "NQQE:CNGVRAPR JNL",
        "ZNQQE:CNGVRAPR JNL & GEVNATYR EQ",
        "PVGL:ZNFFRL",
        "K:GEVNATYR EQ",
        "PNYY:NYNEZ FBHAQVAT",
        "VQ:S1263555");

    qbGrfg("G22",
        "(URAQ657, URAQ651, JNVG671) 111CZP-FGEH QBA OHPX FPUBBY 124 QBA OHPX EQ ZNFFRL. ARNE MVGN ZNEVN QE. (KFge NYQREA EQ/WRMREB QE) .FZBXR NYNEZ NPGVINGVBA EBBZ 11. #S1263547",
        "HAVG:URAQ657, URAQ651, JNVG671",
        "PBQR:111CZP-FGEH",
        "CYNPR:QBA OHPX FPUBBY ARNE MVGN ZNEVN QE",
        "NQQE:124 QBA OHPX EQ",
        "PVGL:ZNFFRL",
        "K:NYQREA EQ/WRMREB QE",
        "PNYY:FZBXR NYNEZ NPGVINGVBA EBBZ 11",
        "VQ:S1263547");

    qbGrfg("G23",
        "(JNVG671, JNVG672, GRNG664) 111-FGEH 144 GEVNATYR EQ ZNFFRL. (KFge ZNXBEN EQ/YVAPBYA CNEX NI) .OHVYQVAT SVER NG PNYGRK. #S1262483",
        "HAVG:JNVG671, JNVG672, GRNG664",
        "PBQR:111-FGEH",
        "NQQE:144 GEVNATYR EQ",
        "PVGL:ZNFFRL",
        "K:ZNXBEN EQ/YVAPBYA CNEX NI",
        "PNYY:OHVYQVAT SVER NG PNYGRK",
        "VQ:S1262483");

    qbGrfg("G24",
        "(JNVG671) 111-ZVA WBFRCU QHAFGNA QE GNHCNXV. (KFge GNHCNXV EQ/) .FZBXR VA IVPVAVGL. #S1261652",
        "HAVG:JNVG671",
        "PBQR:111-ZVA",
        "CYNPR:WBFRCU",
        "NQQE:QHAFGNA QE",  // Tbbtyr xabjf guvf nf Wbfrcu Qhfgna Qe
        "ZNQQE:QHAFGNA QE & GNHCNXV EQ",
        "PVGL:GNHCNXV",
        "K:GNHCNXV EQ",
        "PNYY:FZBXR VA IVPVAVGL",
        "VQ:S1261652");

    qbGrfg("G25",
        "(JNVG671) CBYVPR-ZVA 11 GEHFPBGG CY JRFG UNEOBHE. (KFge SVGMUREOREG NI/) .FZBXR VA IVPVAVGL. #S1261529",
        "HAVG:JNVG671",
        "PBQR:CBYVPR-ZVA",
        "NQQE:11 GEHFPBGG CY",
        "PVGL:JRFG UNEOBHE",
        "K:SVGMUREOREG NI",
        "PNYY:FZBXR VA IVPVAVGL",
        "VQ:S1261529");

    qbGrfg("G26",
        "(JNVG671) 111-ZVA ZPPYVAGBPX EQ ZNFFRL. (KFge GEVNATYR EQ/) .FZBXR NAQ SVER FUBJVAT NG RAQ BS EBNQ. #S1260977",
        "HAVG:JNVG671",
        "PBQR:111-ZVA",
        "NQQE:ZPPYVAGBPX EQ",
        "ZNQQE:ZPPYVAGBPX EQ & GEVNATYR EQ",
        "PVGL:ZNFFRL",
        "K:GEVNATYR EQ",
        "PNYY:FZBXR NAQ SVER FUBJVAT NG RAQ BS EBNQ",
        "VQ:S1260977");

    qbGrfg("G27",
        "(JNVG671, URAQ657) CSN-FCEAXYE (Nynez Glcr FCEVAXYRE) ANGHEVRF URNYGU CEBQHPGF 6 GBAL FG URAQREFBA. (KFge PRAGENY CNEX QE/) #S1260850",
        "HAVG:JNVG671, URAQ657",
        "PBQR:CSN-FCEAXYE",
        "CYNPR:ANGHEVRF URNYGU CEBQHPGF",
        "NQQE:6 GBAL FG",
        "PVGL:URAQREFBA",
        "K:PRAGENY CNEX QE",
        "PNYY:Nynez Glcr FCEVAXYRE",
        "VQ:S1260850");

    qbGrfg("G28",
        "(ESBNHPXAGU, JNVG7771, JNVG7772, JNVG672, URAQ657) 111CZP-FGEH (Obk -77-6550) GRYRPBZ RKPUNATR JNVGNXRER 10 ZPRAGRR EQ JNVGNXRER. (KFge GBJAFUVC EQ/ABEGUSVRYQ EQ) .NYNEZ NPGVINGVBA. #S1259455",
        "HAVG:ESBNHPXAGU, JNVG7771, JNVG7772, JNVG672, URAQ657",
        "PBQR:111CZP-FGEH",
        "OBK:-77-6550",
        "CYNPR:GRYRPBZ RKPUNATR JNVGNXRER",
        "NQQE:10 ZPRAGRR EQ",
        "PVGL:JNVGNXRER",
        "K:GBJAFUVC EQ/ABEGUSVRYQ EQ",
        "PNYY:NYNEZ NPGVINGVBA",
        "VQ:S1259455");

    qbGrfg("G29",
        "(GRNG664, GRNG662, JNVG671) 111CZP-FGEH (Obk -66-54) GRYRPBZ RKPUNATR GR NGNGH ABEGU 410 BYQ GR NGNGH EQ GR NGNGH CRAVAFHYN. (KFge GBEH FG/CNEXINYR TE) .NYNEZ NPGVINGVBA. #S1259454",
        "HAVG:GRNG664, GRNG662, JNVG671",
        "PBQR:111CZP-FGEH",
        "OBK:-66-54",
        "CYNPR:GRYRPBZ RKPUNATR GR NGNGH ABEGU",
        "NQQE:410 BYQ GR NGNGH EQ",
        "PVGL:GR NGNGH CRAVAFHYN",
        "K:GBEH FG/CNEXINYR TE",
        "PNYY:NYNEZ NPGVINGVBA",
        "VQ:S1259454");

    qbGrfg("G30",
        "(JNVG671, GRNG664) 111-FGEH 11 CNGVRAPR JNL ZNFFRL. (KFge GEVNATYR EQ/) .UBHFR SVER. #S1259309",
        "HAVG:JNVG671, GRNG664",
        "PBQR:111-FGEH",
        "NQQE:11 CNGVRAPR JNL",  // Abg znccvat
        "PVGL:ZNFFRL",
        "K:GEVNATYR EQ",
        "PNYY:UBHFR SVER",
        "VQ:S1259309");

    qbGrfg("G31",
        "(XHZR861, XHZR867, JNVG671) CSN-FGEH (Nynez Glcr FZBXR) (Obk -P86-13) PBAFGRYYNGVBA AM PBZCYRK 45 FGNGVBA EQ UHNCNV. (KFge ZNVA EQ/ABOVYB EQ) #S1258539",
        "HAVG:XHZR861, XHZR867, JNVG671",
        "PBQR:CSN-FGEH",
        "OBK:-P86-13",
        "CYNPR:PBAFGRYYNGVBA AM PBZCYRK",
        "NQQE:45 FGNGVBA EQ",
        "PVGL:UHNCNV",
        "K:ZNVA EQ/ABOVYB EQ",
        "PNYY:Nynez Glcr FZBXR",
        "VQ:S1258539");

    qbGrfg("G32",
        "(URAQ657, JNVG671) 111-FGEH GUR JNERUBHFR YVAPBYA PRAGER 111 YVAPBYA EQ URAQREFBA. (KFge JBBQSBEQ NI/SNVEQRAR NI) .FZBXR PBZVAT SEBZ YVTUG. #S1258213",
        "HAVG:URAQ657, JNVG671",
        "PBQR:111-FGEH",
        "CYNPR:GUR JNERUBHFR YVAPBYA PRAGER",
        "NQQE:111 YVAPBYA EQ",
        "PVGL:URAQREFBA",
        "K:JBBQSBEQ NI/SNVEQRAR NI",
        "PNYY:FZBXR PBZVAT SEBZ YVTUG",
        "VQ:S1258213");

    qbGrfg("G33",
        "(JNVG671) 111-ANG JRFG UNEOBHE YBQTR 499 QBA OHPX EQ ZNFFRL. (KFge ORNHPUNZC QE/EHFU PERRX QE) .GERR NPEBFF QEVIRJNL. #S1257608",
        "HAVG:JNVG671",
        "PBQR:111-ANG",
        "CYNPR:JRFG UNEOBHE YBQTR",
        "NQQE:499 QBA OHPX EQ",
        "PVGL:ZNFFRL",
        "K:ORNHPUNZC QE/EHFU PERRX QE",
        "PNYY:GERR NPEBFF QEVIRJNL",
        "VQ:S1257608");

    qbGrfg("G34",
        "(JNVG671) 111-ANG 19 OEVQTRURNQ PBIR JRFG UNEOBHE. (KFge UNEOBHE YVTUGF PY/) .EBBS YVSGVAT. #S1257545",
        "HAVG:JNVG671",
        "PBQR:111-ANG",
        "NQQE:19 OEVQTRURNQ PBIR",
        "PVGL:JRFG UNEOBHE",
        "K:UNEOBHE YVTUGF PY",
        "PNYY:EBBS YVSGVAT",
        "VQ:S1257545");

    qbGrfg("G35",
        "(JNVG7771, JNVG671) 111-ANG 91 JNVGNXRER EQ JNVGNXRER. (KFge ABEGUSVRYQ EQ/GBJAFUVC EQ) .GERR BAGB UBHFR . #S1257341",
        "HAVG:JNVG7771, JNVG671",
        "PBQR:111-ANG",
        "NQQE:91 JNVGNXRER EQ",
        "PVGL:JNVGNXRER",
        "K:ABEGUSVRYQ EQ/GBJAFUVC EQ",
        "PNYY:GERR BAGB UBHFR",
        "VQ:S1257341");

    qbGrfg("G36",
        "(JNVG672) 111-ANG UBOFBAIVYYR EQ JRFG UNEOBHE. (KFge UBOFBAIVYYR EQ BA-ENZC/) .GERR QBJA RKVG ENZC JRFG TNGR. #S1257250",
        "HAVG:JNVG672",
        "PBQR:111-ANG",
        "NQQE:UBOFBAIVYYR EQ",
        "ZNQQE:UBOFBAIVYYR EQ & UBOFBAIVYYR EQ BA-ENZC",
        "PVGL:JRFG UNEOBHE",
        "K:UBOFBAIVYYR EQ BA-ENZC",
        "PNYY:GERR QBJA RKVG ENZC JRFG TNGR",
        "VQ:S1257250");

    qbGrfg("G37",
        "(JNVG671) ENQVB-ZVA 90 BEVRY NI JRFG UNEOBHE. (KFge FHZVPU CY/ZBVER EQ) .BVY FCVYY. #S1257095",
        "HAVG:JNVG671",
        "PBQR:ENQVB-ZVA",
        "NQQE:90 BEVRY NI", // Abg znccvat
        "ZNQQE:90 BEVRY NIR",
        "PVGL:JRFG UNEOBHE",
        "K:FHZVPU CY/ZBVER EQ",
        "PNYY:BVY FCVYY",
        "VQ:S1257095");

    qbGrfg("G38",
        "(JNVG671) 111CZP-ZVA 2 CEVAPRFF ZNEVN CY ZNFFRL. (KFge DHRRA ANGNYVR CY/) .NYNEZ NPGVINGVBA - ERFVQRAGVNY. #S1257093",
        "HAVG:JNVG671",
        "PBQR:111CZP-ZVA",
        "NQQE:2 CEVAPRFF ZNEVN CY",
        "PVGL:ZNFFRL",
        "K:DHRRA ANGNYVR CY",
        "PNYY:NYNEZ NPGVINGVBA - ERFVQRAGVNY",
        "VQ:S1257093");

    qbGrfg("G39",
        "(JNVG671) 111-ZVA SVER FGNGVBA JNVGRZNGN 21 UBOFBAIVYYR EQ JRFG UNEOBHE. (KFge UBOFBAIVYYR EQ BA-ENZC/BERVY NI) .YNETR SVER VA ERNE BS LNEQ. #S1256968",
        "HAVG:JNVG671",
        "PBQR:111-ZVA",
        "CYNPR:SVER FGNGVBA JNVGRZNGN",
        "NQQE:21 UBOFBAIVYYR EQ",
        "PVGL:JRFG UNEOBHE",
        "K:UBOFBAIVYYR EQ BA-ENZC/BERVY NI",
        "PNYY:YNETR SVER VA ERNE BS LNEQ",
        "VQ:S1256968");

    qbGrfg("G40",
        "(JNVG671, GRNG664) 111-FGEH 195R QBA OHPX EQ ZNFFRL. (KFge PUNZOREYNVA EQ/QBABINA NI) .FGBIR BA SVER . #S1255305",
        "HAVG:JNVG671, GRNG664",
        "PBQR:111-FGEH",
        "NQQE:195R QBA OHPX EQ",
        "PVGL:ZNFFRL",
        "K:PUNZOREYNVA EQ/QBABINA NI",
        "PNYY:FGBIR BA SVER",
        "VQ:S1255305");

    qbGrfg("G41",
        "(XHZR867, XHZR861, JNVG671) 111-ERFP XHZRH. (KFge FU 16/EVIREURNQ EQ) .ZIN . #S1255174",
        "HAVG:XHZR867, XHZR861, JNVG671",
        "PBQR:111-ERFP",
        "NQQE:FU 16 & EVIREURNQ EQ",
        "ZNQQE:FGNGR 16 & EVIREURNQ EQ",
        "PVGL:XHZRH",
        "PNYY:ZIN",
        "VQ:S1255174");

  }
  
  choyvp fgngvp ibvq znva(Fgevat[] netf) {
    arj MAMArjMrnynaqCnefreGrfg().trarengrGrfgf("G1", "HAVG PBQR OBK CYNPR NQQE NCG PVGL K PNYY VQ");
  }
}