package net.anei.cadpage.parsers.WI;

import java.util.Properties;

import net.anei.cadpage.parsers.dispatch.DispatchPrintrakParser;

/*
Calumet County, WI
Contact: Brian Schwalbach <schwally77@gmail.com>
Sender: Admin.Foxcomm@co.calumet.wi.us <From%3AAdmin.Foxcomm@co.calumet.wi.us>
HAFR       PRI: 1 INC: FHA110114000008 TYP: RESCUE ADVANCED LIFE AD: N8016 PIGEON RD CTY: CMSV CN: BRUSE CMT1: 11 MONTH OLD INFANT WITH SOMETHING STUCK I
BUFD       PRI: 1 INC: FBU110115000010 TYP: ACCIDENT - C AD: CTY TK CE&OUTAGAMIE RD CTY: BUCT CN: KARNER,BEN CMT1: ***IF 2191 OR 2192 IS RESPONDING ALSO
HAFR       PRI: 1 INC: FHA110116000010 TYP: RESCUE ADVANCED LIFE AD: W5872 EASTER LILY DR CTY: CMTH CN: SWEERE, SHANNON CMT1: 13YOA FEMALE BAD
HAFR       PRI: 1 INC: FHA110123000017 TYP: VEHICLE ACCIDENT AD: W7170 HWY 114 CTY: CMTH CN: VANDEHEY, FRANCIS CMT1: **POINT TO POINT TO OUSO TO DISPATCH
HAFR       PRI: 1 INC: FHA110123000016 TYP: RESCUE ADVANCED LIFE AD: N9664 EMERALD LN CTY: CMTH CN: HELLINGSON KATIE CMT1: 60YOA FEMALE DIFFICULTY BREATH
HAFR       PRI: 1 INC: FHA110125000019 TYP: RESCUE ADVANCED LIFE AD: N9085 N COOP RD CTY: CMTH LOC: WOODLAND SCHOOL CN: WOODLAND SCHOOL CMT1: Original Lo
HAFR       PRI: 1 INC: FHA110126000021 TYP: RESCUE ADVANCED LIFE AD: N9114 NOE RD CTY: CMTH CN: COLE, KATHY CMT1: HAND INJURY TIME: 19:22 GAGCA1 HAM321 X
HAFR       PRI: 1 INC: FHA110117000011 TYP: RESCUE ADVANCED LIFE AD: CTY TK KK&NOE RD CTY: CMTH CN: TAUS,ANNETTE CMT1: 44 YR OLD FEMALE WITH CHEST PAINS
HAFR       PRI: 1 INC: FHA110127000023 TYP: STRUCTURE FIRE AD: W2825 EMMONS CTY: BUCT CN: BUCHANAN FIRE CMT1: **POINT TO POINT TO OUSO TO DISPATCH BUCHAN
HAFR       PRI: 1 INC: FHA110130000024 TYP: RESCUE ADVANCED LIFE AD: W5095 GOLF COURSE RD CTY: CMSV LOC: HIGH CLIFF SUPPER CL CMT1: Original Location : H
 */


public class WICalumetCountyParser extends DispatchPrintrakParser {
  
  private static final Properties CITY_TABLE = buildCodeTable(new String[]{
      // Brown County
      "ASHW", "ASHWAUBENON",
      "CGB",  "GREEN BAY",
      "TGB",  "BROWN COUNTY", // "GREEN BAY TWP",
      "DENM", "DENMARK",
      "NEWD", "NEW DENMARK",
      "VWRI", "WRIGHTSTOWN",
      "TWRI", "BROWN COUNTY", // "WRIGHTSTOWN TWP",
      "ROCK", "ROCKLAND",
      "DEPE", "DEPERE",
      "PULA", "PULASKI",
      "LEDG", "LEDGEVIEW",
      "HOWA", "HOWARD",
      "HOBA", "HOBART",
      "SCOT", "SCOTT",
      "EATO", "EATON",
      "PITT", "PITTSVILLE",
      "BELL", "BELLEVEUE",
      "HUMB", "HUMBOLDT",
      "ALLO", "ALLOUEZ",
      "SUAM", "SUAMICO",
      "LAWR", "LAWRENCE",
      "GLEN", "GLENMORE",
      "HOLL", "HOLLAND",
      "MORR", "MORRISON",
      
      // Calumet County
      "CMBT", "CALAUMET COUNTY",  // "BROTHERTON",
      "CMCB", "BRILLION",
      "CMCC", "CHILTON",
      "CMCK", "KIEL",
      "CMCN", "NEW HOLSTEIN",
      "CMCT", "CALAUMET COUNTY",  // "CHARLESTOWN TWP",
      "CMTB", "CALAUMET COUNTY",  // "BRILLION TWP",
      "CMSV", "CALAUMET COUNTY",  // "SHERWOOD TWP",
      "CMTH", "CALAUMET COUNTY",  // "HARRISON TWP",
      "CMTN", "CALAUMET COUNTY",  // "NEW HOLSTEIN TWP",
      "CMTR", "CALAUMET COUNTY",  // "RANTOUL TWP",
      "CMTS", "CALAUMET COUNTY",  // "STOCKBRIDGE TWP",
      "CMTW", "CALAUMET COUNTY",  // "WOODVILLE TWP",
      "CMVH", "HILBERT",
      "CMVP", "POTTER",
      "CMVS", "STOCKBRIDGE",
      
      // Outagamie County
      "APPL", "APPLETON",
      "KAUC", "KAUKAUNA",
      "SEYC", "SEYMOUR",
      "NEWL", "NEW LONDON",
      "BLCT", "OUTAGAMIE COUNTY", // "BLACK CREEK TWP",
      "BUCT", "OUTAGAMIE COUNTY", // "BUCHANAN TWP",
      "CENT", "OUTAGAMIE COUNTY", // "CENTER TWP",
      "COLV", "COMBINED LOCKS",
      "DALT", "OUTAGAMIE COUNTY", // "DALE TWP",
      "DRCT", "OUTAGAMIE COUNTY", // "DEER CREEK TWP",
      "ELLT", "OUTAGAMIE COUNTY", // "ELLINGTON TWP",
      "FRET", "OUTAGAMIE COUNTY", // "FREEDOM TWP",
      "GRCT", "OUTAGAMIE COUNTY", // "GRAND CHUTE TWP",
      "GRVT", "OUTAGAMIE COUNTY", // "GREENVILLE TWP",
      "HORT", "OUTAGAMIE COUNTY", // "HORTONVILLE TWP",
      "HORV", "HORTONVILLE",
      "KAUT", "OUTAGAMIE COUNTY", // "KAUKAUNA TWP",
      "KIMV", "KIMBERLY",
      "LIBT", "OUTAGAMIE COUNTY", // "LIBERTY TWP",
      "LTCV", "LITTLE CHUTE", 
      "MPCT", "OUTAGAMIE COUNTY", // "MAPLE CREEK TWP",
      "ONET", "ONEIDA",
      "OSBT", "OUTAGAMIE COUNTY", // "OSBORN TWP",
      "SEYT", "OUTAGAMIE COUNTY", // "SEYMOUR TWP",
      "VANT", "OUTAGAMIE COUNTY", // "VANDENBROEK TWP",
      
      // Winnebago County
      "WALG", "WINNEBAGO COUNTY", // "ALOGMA TWP",
      "WBLA", "WINNEBAGO COUNTY", // "BLACK WOLF TWP",
      "WCLA", "WINNEBAGO COUNTY", // "CLAYTON TWP",
      "WCME", "MENASHA",
      "WMEN", "MENASHA",
      "WNEE", "NEENAH",
      "WNEK", "WINNEBAGO COUNTY", // "NEKIMI TWP",
      "WNEP", "WINNEBAGO COUNTY", // "NEPEUSKUN TWP",
      "WOMR", "OMRO",
      "WOSH", "OSHKOSH",
      "WPOY", "WINNEBAGO COUNTY", // "POYGAN TWP",
      "WRUS", "WINNEBAGO COUNTY", // "RUSHFORD TWP",
      "WTME", "WINNEBAGO COUNTY", // "MENASHA TWP",
      "WTNE", "WINNEBAGO COUNTY", // "NEENAH TWP",
      "WTOM", "WINNEBAGO COUNTY", // "OMRO TWP",
      "WTOS", "WINNEBAGO COUNTY", // "OSHKOSH TWP",
      "WTWN", "WINNEBAGO COUNTY", // "WINNECONNE TWP",
      "WUTI", "WINNEBAGO COUNTY", // "UTICA TWP",
      "WVIN", "WINNEBAGO COUNTY", // "VINLAND TWP",
      "WWCR", "WINNEBAGO COUNTY", // "WINCHESTER TWP",
      "WWNE", "WINNEBAGO COUNTY", // "WINNECONNE TWP",
      "WWOL", "WINNEBAGO COUNTY", // "WOLF RIVER TWP"
  });
  
  public WICalumetCountyParser() {
    super(CITY_TABLE, "CALUMET COUNTY", "WI");
  }
  
  @Override
  public String getFilter() {
    return "Admin.Foxcomm@co.calumet.wi.us";
  }
}
