cnpxntr arg.narv.pnqcntr.cnefref.GK;

vzcbeg arg.narv.pnqcntr.cnefref.OnfrCnefreGrfg;

vzcbeg bet.whavg.Grfg;

/*
Zvffbhev Pvgl, GK

Pbagnpg: Npgvir911
Ntrapl anzr: Zvffbhev Pvgl Cbyvpr naq SQ
Ybpngvba: Zvffbhev Pvgl, GK, Havgrq Fgngrf
Fraqre: <PNQ@zvffbhevpvglgk.tbi>

PNQ:HAX ZNW/ZVABE PBHAGL;UJL 59 / 762;Rirag fcnjarq sebz NPPVQRAG ZVABE. [02/23/201
PNQ:ZNWBE NPPVQRAG;13099 F TRFFARE EQ/PENIRAF EQ;ZNYR FHOW PBZCY BS ARPX NAQ OX CNVA
PNQ:ZRQVPNY PNYY;9000 FVRAAN ENAPU EQ;14LBZ AB SRRYVAT VA YRTF / SRIRE / PUVYYF [02
PNQ:ZRQVPNY PNYY;4710 YRKVATGBA OYIQ;86LBZ QVSS OERNGUVAT / [02/23/15 11:36:41 YYS1
PNQ:HAXABJA ZNWBE ZVABE NPPVQRAG;9699 FU 6/YNXR FUBER UNEOBHE OYIQ;2015000018320
PNQ:FGNGVBA ZBIR HC;6226 NHTHFG TERRA;ONPX VA NFFVTAZRAG GB EBFRAORET FGNGVBA 3 / KF
PNQ:FGNGVBA ZBIR HC;112 WNPXFBA FG;PEBFF FGERRG VF UJL 90/F FRPBAQ / XRL ZNC VF 605P
PNQ:ZRQVPNY PNYY;12626 NYQREJBBQ QE;71 LBZ CBFF FGEBXR//PBAPVBHF NAQ OERNGUVAT [02/
PNQ:ZRQVPNY PNYY;4225 FVRAAN CXJL;ORYBATF GB VAQRCRAQ YVIVAT [02/22/15 20:52:49 YLP
PNQ:ZRQVPNY PNYY;4327 UBNGMVA PG;SRZNYR... SYH FLZCGBAF, QVSS OERNGUVAT [02/22/15 2
PNQ:ZRQVPNY PNYY;2805 PNZOEVQTR YA;ZRQVP 3 PBZVAT BHG BS QVFGEVPG [02/22/15 18:45:1
PNQ:ZRQVPNY PNYY;11814 F CREEL NIR;ZNYR NYYRETVP ERNPGVBA.... FJRNYYVAT, HANOYR GB J
PNQ:ZRQVPNY PNYY;3334 PBASRQRENGR QE;59 LB ZNYR PURFG CNVA [02/22/15 18:29:43 YLP29
PNQ:ZRQVPNY PNYY;2350 SZ 1092 EQ;CNGVRAG VF VA EBBZ #410 [02/22/15 18:08:59 NRF237]
PNQ:ZRQVPNY PNYY;3611 UNJXVAF PVE;OEBXRA NAXYR, 47 LB SRZNYR [02/22/15 15:11:54 YLP
PNQ:NYNEZ SVER;47 RZORE OENAPU QE;NHQ/CBN TRARENY FZBXR QRGRPGBE/WNSEV ERF 718-715-5
PNQ:ZRQVPNY PNYY;6131 FU 6;OYX YRKHF EK350/53 LBS PURFG CNVAF [02/22/15 13:02:37 GT
PNQ:ZRQVPNY PNYY;2019 OEVTUG ZRNQBJF QE;60LBS QVSS OERNGUVAT / JVYY OR YBP VA PUNVE
PNQ:ZRQVPNY PNYY;854 GHEGYR PERRX QE;[YNJ] (K792) VZ BHG [02/22/15 10:46:17 YYS117]
PNQ:ZRQVPNY PNYY;4506 OYNXRF EVQTR FG;SNGURE UNF ORRA FVPX NYY AVTUG NAQ UNF ORRA CN
PNQ:ZRQVPNY PNYY;10014-526 F FNZ UBHFGBA CXJL J;66 LBS JVGU PURFG CNVAF/FUBEGARFF BS
PNQ:ZRQVPNY PNYY;12043 ZPYNVA OYIQ;[YNJ] (P415) JR JVYY OR BHG NG R UNZCGBA/F XNGUL
PNQ:ZRQVPNY PNYY;3640 UNZCGBA QE;RYQREYL SRZNYR / UVTU OC/FYVTUGYL VAPBURERAG/VA GUR
PNQ:ZRQVPNY PNYY;12043 ZPYNVA OYIQ;ERD FCNAVFU FCRNXVAT BSSVPRE ERDHRFGRQ [02/22/15
PNQ:ZNWBE NPPVQRAG;2410 YN DHVAGN QE;26LBZ PBAFPVBHF NAQ OERNGUVAT// NQI UR JNF ENA
PNQ:TNF BQBE VAFVQR;2930 ANAPL ORYYR YA;PBZCY NQI UR GHEARQ BA GUR URNG NAQ ABJ UR F
PNQ:ZRQVPNY PNYY;1511-214 5GU FG;20LBS PBAFPVBHF NAQ OERNGUVAT// VGPUVAT CEBOYRZF//
PNQ:ZRQVPNY PNYY;10014-428 F FNZ UBHFGBA CXJL J;BYQRE ZNYR UNIVAT GEBHOYR OERNGUVAT
PNQ:ZRQVPNY PNYY;2411 PERRX ZRNQBJF QE;[YNJ] SOPB ERD CQ NF JRYY [02/21/15 22:31:10
PNQ:ZRQVPNY PNYY;2411 PERRX ZRNQBJF QE;ZNYR FHOW GUNG FZBXRQ FLAGURGVP ZNEVWHNAN/ AB
PNQ:ZRQVPNY PNYY;3311 PUREEL PERRX QE;76LBZ VEERTHYNE URNEG ORNGU UNIVAT GEBHOYR OER
PNQ:ZHGHNY NVQ ZVFP YBPNGVBA;3100 XVEOL QE;Rirag fcnjarq sebz NFFVFG BGURE NTRAPL.
PNQ:ZRQVPNY PNYY;1930 YNHERA CY;34lbz pbafpvbhf naq oernguvat uvtu oybbq cerffher jv
PNQ:ZRQVPNY PNYY;2527 IVYYNTR FDHNER QE;ZNYR FHOW YNLVAT BA GUR TEBHAQ NQI UR VF FR
PNQ:NYNEZ SVER;1611 CNEXIVRJ YA;NHQ / CBN TRARENY SVER NYNEZ 281 835 3350 # NG GUR
PNQ:FREIVPR PNYY NFFVFG;2022 INYYRL ZNABE QE;74 LB ZNYR / ARRQF URYC SEBZ PUNATVAT S
PNQ:NYNEZ SVER;3803 A SVGMTRENYQ PG;CBN FZBXR QRGRPGBE. VCCBYVGV, QNIVQ 281 778 8815
PNQ:ZRQVPNY PNYY;1971 GRKNF CXJL;13 LB SRZNYR SNVAGRQ/ NYREG NAQ OERNGUVAT / [02/21
PNQ:ZRQVPNY PNYY;3849 PNEGJEVTUG EQ;2015000017769
PNQ:ZRQVPNY PNYY;4106 SERRQBZ GERR QE;28lbs JVGU UVFGBEL BS FRVMHERF// ABG PHEERAGYL
PNQ:ZRQVPNY PNYY;1107 ZBFFEVQTR QE;70 LBZ CNFFRQ BHG/ SBNZVAT BHG BS GUR ZBHGU/ ABG
PNQ:NYNEZ SVER;3807 JVPXFBA ZAE;NHQ/CBN FZBXR QRGRPGBE/ AJBOBQB, WBR NAQ RQVGU/CF AH
PNQ:ZRQVPNY PNYY;4723 NHGHZA YXF;62LBS URNEG ENPVAT// PBAFPVBHF NAQ OERNGUVAT [02/2
PNQ:ZNWBE NPPVQRAG PBHAGL;3399 FVRAAN CXJL/FPNAYNA GEPR;IRU JENCCRQ NEBHAQ N GERR//Z
PNQ:NYNEZ ZRQVPNY;4611 EVIRETYNQR PG;ZRQ 4 BHG BS QVFGEVPG/ HANOYR ZNXR PBAG J XRLUB
PNQ:ZRQVPNY PNYY;2919 QEVSGJBBQ ORAQ QE;1 LBZ UNIVAT FRVMHERF/ OERNGUVAT URNIVYL NG
PNQ:ZRQVPNY PNYY;3514 ORAWNZVA SENAXYVA YA;SOPB NQI CBFF FGEBXR [02/20/15 19:56:48
PNQ:NYNEZ SVER;3902 RZRENYQ YNXR QE;CBN URNG QRGRPGBE XVGPURA / XVMMRR, PUEVFGVAN ER
PNQ:NFFVFG CBYVPR;1899 HF 90N/ZNEGVA YA;BA NA ZVABE/ ERD CQ/ NAQ BAR JERPXRE/ AB VAW
PNQ:ZRQVPNY PNYY;2193 GRKNF CXJL;NQI FVFGRE VA YNJ JNF WHFG VA NA NPPVQRAG [02/20/1
PNQ:ZRQVPNY PNYY;4422 EVIREFGBAR OYIQ;78 LB ZNYR QVNORGVP CEBOYRZF. ZRQVP 10 PBZVAT
PNQ:ZRQVPNY PNYY;2707 CNEX BNX PG;76 LB SRZNYR NEZ CNVA/ PBZCY NQI GUNG SRZNYR JNF T
PNQ:ZRQVPNY PNYY;2319 RQTRQNYR QE;73 LB SRZNYR J QVSS OERNGUVAT [02/20/15 13:56:55
PNQ:FGEHPGHER SVER;3310 PBHAGEL PYHO OYIQ;KFG QHYYRF BE PURFGRESVRYQ. XRL ZNC 569W.
PNQ:SLV: ;FGEHPGHER SVER;3310 PBHAGEL PYHO OYIQ;KFG QHYYRF BE PURFGRESVRYQ. XRL ZNC
PNQ:ZRQVPNY PNYY;2831 TYRAA YNXRF YA;69 LB ZNYR QVNORGVP/ ZRQ 3 BHG BS QVFGEVPG / [
PNQ:ZRQVPNY PNYY;3810 NHOHEA TEBIR PVE;ERD OL ZRQ HAVGF HAX ERNFBA GURL NER VA QVFGE
PNQ:ZRQVPNY PNYY;3438 5GU FG;ZNYR FHOIW NYFB PUBXVAT [02/20/15 10:17:44 NZQ704] 90
PNQ:ZRQVPNY PNYY;3035 UHPXYROREEL;45 LB ZNYR ONPX CNVA [02/20/15 07:45:49 NZQ704] 4
PNQ:ZRQVPNY PNYY;1707 TYRATERRA QE;ABG NYREG [02/20/15 07:11:35 NZQ704] 65 LB ZNYR
PNQ:ZRQVPNY PNYY;2711 J CROOYR ORNPU QE;69 LB ZNYR CBFF QBN, PBZCY HANOYR GB JNXR UV
PNQ:ZRQVPNY PNYY;1927 JBBQ FUNQBJF QE;30LBS JVGU PURFG CNVAF// YVGGYR GEBHOYR OERNGU
PNQ:TNF BQBE VAFVQR;1903 TENL FYNGR QE;ERPRAGYL CHEPUNFRQ N JNGRE URNGRE [02/19/15
PNQ:ZRQVPNY PNYY;4422 EVIREFGBAR OYIQ;90LBZ 312 ABG PBAFPVBHF ABG ERFCBAFVIR OHG UR
PNQ:ZRQVPNY PNYY;1219 GJVAVAT BNXF YA;BAR ZBAGU BYQ ZNYR QVSSVPHYGL OERNGUVAT/GHEAVA
PNQ:ZRQVPNY PNYY;3454 UNIREFUVER QE;87 LBS / VA NAQ BHG PBAFPVBHFARFF / AB QVSSVPHYG
PNQ:NYNEZ PNEOBA ZBABKVQR;5942 FGBEL OBBX GEY;NHQ/ CBN PNEOBAQ ZBABKVQR QRGRPGBE [0
PNQ:ZRQVPNY PNYY;2815-2201 PLCERFF CBVAG QE;RYQREYL SRZNYR SNYY IVPGVZ/WNZZRQ ARPX N
PNQ:TNF BQBE VAFVQR;6706 FHGGREF PERRX GEY;PBZCY NQI JURA FUR TBG UBZR FZRYYF FGEBAT
PNQ:YBPX VA;5744 FU 6;PBZCY NQI GUVF IRU VF ABG UREF NAQ PUVYQ VF NYBAR [02/19/15 1
PNQ:ZRQVPNY PNYY;2326 EVQTRZBAG QE;60 LB SRZNYR QVSS OERNGUVAT [02/19/15 12:16:48 E
PNQ:NYNEZ SVER;8717 FPNAYNA GEPR;NHQ / CBN TRARENY / 281 778 0366 [02/19/15 10:36:4
PNQ:ZRQVPNY PNYY;3102 BNXYRNS PG;46 LBS / UNIVAT QVSS OERNGUVAT NAQ FRRV / HANOYR GB
PNQ:FREIVPR PNYY NFFVFG;3806 PELFGNY SNYYF QE;83 LBZ / SNYY IVP / AB VAWHEVRF / ARRQ
PNQ:HAQRGREZVARQ GLCR PNYY;11818 F ZVPUNRY PVE;SBBQ VF VA GUR BIRA PBBXVAT NAQ GUR B
PNQ:NYNEZ SVER;3223 EBOVAFBA EQ;CBN TRARENY ERFVQRAGVNY / ZBEEVF, EQ 281 437 7926 [
PNQ:ZNWBE NPPVQRAG;TRFFARE OJ 8 RO RAG ENZC/F FNZ UBHFGBA CXJL J;GBLG PBEBYYN NAQ JU
PNQ:ZRQVPNY PNYY;3331 PUVZREN YA;34 LBZ / NOQBZVANY CNVA / ZRQVP 5 BA FPRAR ERD SVEF
PNQ:ZRQVPNY PNYY;510 FGRCUNAVR QE;95 LBS / QVSS OERNGUVAT NAQ SRRYVAT IREL VYY [02/
PNQ:ZRQVPNY PNYY;1926 DHNVY INYYRL RNFG QE;PBZCY NQI OEBGURE WHFG ZNQR YBP/ NAQ JVYY
PNQ:NYNEZ SVER;2922 SVIR BNXF QE;Rirag fcnjarq sebz NYNEZ ERFVQRAGVNY. [02/18/2015
PNQ:HAXABJA ZNWBE ZVABE NPPVQRAG;13450 F TRFFARE EQ;NPPVQRAG VA GUR ZRQVNA/ HAX VAWH
PNQ:NYNEZ SVER;4200 PNEGJEVTUG EQ;NHQ/CBN TRARENY NYNEZ MBAR 1 [02/18/15 15:28:17 G
PNQ:FREIVPR PNYY NFFVFG;1711 CNZRYN YA;68LBS SNYY IVPGVZ / ABG VAWHERQ [02/18/15 14

*/

choyvp pynff GKZvffbhevPvglCnefreGrfg rkgraqf OnfrCnefreGrfg {
  
  choyvp GKZvffbhevPvglCnefreGrfg() {
    frgCnefre(arj GKZvffbhevPvglCnefre(), "ZVFFBHEV PVGL", "GK");
  }

  @Grfg
  choyvp ibvq grfgZvffbhevPvglCbyvprNaqSQ() {

    qbGrfg("G1",
        "PNQ:HAX ZNW/ZVABE PBHAGL;UJL 59 / 762;Rirag fcnjarq sebz NPPVQRAG ZVABE. [02/23/201",
        "PNYY:HAX ZNW/ZVABE PBHAGL",
        "NQQE:UJL 59 & 762",
        "VASB:Rirag fcnjarq sebz NPPVQRAG ZVABE.");

    qbGrfg("G2",
        "PNQ:ZNWBE NPPVQRAG;13099 F TRFFARE EQ/PENIRAF EQ;ZNYR FHOW PBZCY BS ARPX NAQ OX CNVA",
        "PNYY:ZNWBE NPPVQRAG",
        "NQQE:13099 F TRFFARE EQ & PENIRAF EQ",
        "ZNQQE:13099 F TRFFARE EQ",
        "VASB:ZNYR FHOW PBZCY BS ARPX NAQ OX CNVA");

    qbGrfg("G3",
        "PNQ:ZRQVPNY PNYY;9000 FVRAAN ENAPU EQ;14LBZ AB SRRYVAT VA YRTF / SRIRE / PUVYYF [02",
        "PNYY:ZRQVPNY PNYY",
        "NQQE:9000 FVRAAN ENAPU EQ",
        "VASB:14LBZ AB SRRYVAT VA YRTF / SRIRE / PUVYYF");

    qbGrfg("G4",
        "PNQ:ZRQVPNY PNYY;4710 YRKVATGBA OYIQ;86LBZ QVSS OERNGUVAT / [02/23/15 11:36:41 YYS1",
        "PNYY:ZRQVPNY PNYY",
        "NQQE:4710 YRKVATGBA OYIQ",
        "VASB:86LBZ QVSS OERNGUVAT /",
        "QNGR:02/23/15",
        "GVZR:11:36:41");

    qbGrfg("G5",
        "PNQ:HAXABJA ZNWBE ZVABE NPPVQRAG;9699 FU 6/YNXR FUBER UNEOBHE OYIQ;2015000018320",
        "PNYY:HAXABJA ZNWBE ZVABE NPPVQRAG",
        "NQQE:9699 FU 6 & YNXR FUBER UNEOBHE OYIQ",
        "ZNQQE:9699 GK 6",
        "VASB:2015000018320");

    qbGrfg("G6",
        "PNQ:FGNGVBA ZBIR HC;6226 NHTHFG TERRA;ONPX VA NFFVTAZRAG GB EBFRAORET FGNGVBA 3 / KF",
        "PNYY:FGNGVBA ZBIR HC",
        "NQQE:6226 NHTHFG TERRA",
        "VASB:ONPX VA NFFVTAZRAG GB EBFRAORET FGNGVBA 3 / KF");

    qbGrfg("G7",
        "PNQ:FGNGVBA ZBIR HC;112 WNPXFBA FG;PEBFF FGERRG VF UJL 90/F FRPBAQ / XRL ZNC VF 605P",
        "PNYY:FGNGVBA ZBIR HC",
        "NQQE:112 WNPXFBA FG",
        "VASB:PEBFF FGERRG VF UJL 90/F FRPBAQ / XRL ZNC VF 605P");

    qbGrfg("G8",
        "PNQ:ZRQVPNY PNYY;12626 NYQREJBBQ QE;71 LBZ CBFF FGEBXR//PBAPVBHF NAQ OERNGUVAT [02/",
        "PNYY:ZRQVPNY PNYY",
        "NQQE:12626 NYQREJBBQ QE",
        "VASB:71 LBZ CBFF FGEBXR//PBAPVBHF NAQ OERNGUVAT");

    qbGrfg("G9",
        "PNQ:ZRQVPNY PNYY;4225 FVRAAN CXJL;ORYBATF GB VAQRCRAQ YVIVAT [02/22/15 20:52:49 YLP",
        "PNYY:ZRQVPNY PNYY",
        "NQQE:4225 FVRAAN CXJL",
        "VASB:ORYBATF GB VAQRCRAQ YVIVAT",
        "QNGR:02/22/15",
        "GVZR:20:52:49");

    qbGrfg("G10",
        "PNQ:ZRQVPNY PNYY;4327 UBNGMVA PG;SRZNYR... SYH FLZCGBAF, QVSS OERNGUVAT [02/22/15 2",
        "PNYY:ZRQVPNY PNYY",
        "NQQE:4327 UBNGMVA PG",
        "VASB:SRZNYR... SYH FLZCGBAF, QVSS OERNGUVAT");

    qbGrfg("G11",
        "PNQ:ZRQVPNY PNYY;2805 PNZOEVQTR YA;ZRQVP 3 PBZVAT BHG BS QVFGEVPG [02/22/15 18:45:1",
        "PNYY:ZRQVPNY PNYY",
        "NQQE:2805 PNZOEVQTR YA",
        "VASB:ZRQVP 3 PBZVAT BHG BS QVFGEVPG");

    qbGrfg("G12",
        "PNQ:ZRQVPNY PNYY;11814 F CREEL NIR;ZNYR NYYRETVP ERNPGVBA.... FJRNYYVAT, HANOYR GB J",
        "PNYY:ZRQVPNY PNYY",
        "NQQE:11814 F CREEL NIR",
        "VASB:ZNYR NYYRETVP ERNPGVBA.... FJRNYYVAT, HANOYR GB J");

    qbGrfg("G13",
        "PNQ:ZRQVPNY PNYY;3334 PBASRQRENGR QE;59 LB ZNYR PURFG CNVA [02/22/15 18:29:43 YLP29",
        "PNYY:ZRQVPNY PNYY",
        "NQQE:3334 PBASRQRENGR QE",
        "VASB:59 LB ZNYR PURFG CNVA",
        "QNGR:02/22/15",
        "GVZR:18:29:43");

    qbGrfg("G14",
        "PNQ:ZRQVPNY PNYY;2350 SZ 1092 EQ;CNGVRAG VF VA EBBZ #410 [02/22/15 18:08:59 NRF237]",
        "PNYY:ZRQVPNY PNYY",
        "NQQE:2350 SZ 1092 EQ",
        "ZNQQE:2350 SNEZ-GB-ZNEXRG 1092",
        "VASB:CNGVRAG VF VA EBBZ #410",
        "QNGR:02/22/15",
        "GVZR:18:08:59");

    qbGrfg("G15",
        "PNQ:ZRQVPNY PNYY;3611 UNJXVAF PVE;OEBXRA NAXYR, 47 LB SRZNYR [02/22/15 15:11:54 YLP",
        "PNYY:ZRQVPNY PNYY",
        "NQQE:3611 UNJXVAF PVE",
        "VASB:OEBXRA NAXYR, 47 LB SRZNYR",
        "QNGR:02/22/15",
        "GVZR:15:11:54");

    qbGrfg("G16",
        "PNQ:NYNEZ SVER;47 RZORE OENAPU QE;NHQ/CBN TRARENY FZBXR QRGRPGBE/WNSEV ERF 718-715-5",
        "PNYY:NYNEZ SVER",
        "NQQE:47 RZORE OENAPU QE",
        "VASB:NHQ/CBN TRARENY FZBXR QRGRPGBE/WNSEV ERF 718-715-5");

    qbGrfg("G17",
        "PNQ:ZRQVPNY PNYY;6131 FU 6;OYX YRKHF EK350/53 LBS PURFG CNVAF [02/22/15 13:02:37 GT",
        "PNYY:ZRQVPNY PNYY",
        "NQQE:6131 FU 6",
        "ZNQQE:6131 GK 6",
        "VASB:OYX YRKHF EK350/53 LBS PURFG CNVAF",
        "QNGR:02/22/15",
        "GVZR:13:02:37");

    qbGrfg("G18",
        "PNQ:ZRQVPNY PNYY;2019 OEVTUG ZRNQBJF QE;60LBS QVSS OERNGUVAT / JVYY OR YBP VA PUNVE",
        "PNYY:ZRQVPNY PNYY",
        "NQQE:2019 OEVTUG ZRNQBJF QE",
        "VASB:60LBS QVSS OERNGUVAT / JVYY OR YBP VA PUNVE");

    qbGrfg("G19",
        "PNQ:ZRQVPNY PNYY;854 GHEGYR PERRX QE;[YNJ] (K792) VZ BHG [02/22/15 10:46:17 YYS117]",
        "PNYY:ZRQVPNY PNYY",
        "NQQE:854 GHEGYR PERRX QE",
        "VASB:(K792) VZ BHG",
        "QNGR:02/22/15",
        "GVZR:10:46:17");

    qbGrfg("G20",
        "PNQ:ZRQVPNY PNYY;4506 OYNXRF EVQTR FG;SNGURE UNF ORRA FVPX NYY AVTUG NAQ UNF ORRA CN",
        "PNYY:ZRQVPNY PNYY",
        "NQQE:4506 OYNXRF EVQTR FG",
        "VASB:SNGURE UNF ORRA FVPX NYY AVTUG NAQ UNF ORRA CN");

    qbGrfg("G21",
        "PNQ:ZRQVPNY PNYY;10014-526 F FNZ UBHFGBA CXJL J;66 LBS JVGU PURFG CNVAF/FUBEGARFF BS",
        "PNYY:ZRQVPNY PNYY",
        "NQQE:10014-526 F FNZ UBHFGBA CXJL J",
        "ZNQQE:10014 F FNZ UBHFGBA CXJL J",
        "VASB:66 LBS JVGU PURFG CNVAF/FUBEGARFF BS");

    qbGrfg("G22",
        "PNQ:ZRQVPNY PNYY;12043 ZPYNVA OYIQ;[YNJ] (P415) JR JVYY OR BHG NG R UNZCGBA/F XNGUL",
        "PNYY:ZRQVPNY PNYY",
        "NQQE:12043 ZPYNVA OYIQ",
        "VASB:(P415) JR JVYY OR BHG NG R UNZCGBA/F XNGUL");

    qbGrfg("G23",
        "PNQ:ZRQVPNY PNYY;3640 UNZCGBA QE;RYQREYL SRZNYR / UVTU OC/FYVTUGYL VAPBURERAG/VA GUR",
        "PNYY:ZRQVPNY PNYY",
        "NQQE:3640 UNZCGBA QE",
        "VASB:RYQREYL SRZNYR / UVTU OC/FYVTUGYL VAPBURERAG/VA GUR");

    qbGrfg("G24",
        "PNQ:ZRQVPNY PNYY;12043 ZPYNVA OYIQ;ERD FCNAVFU FCRNXVAT BSSVPRE ERDHRFGRQ [02/22/15",
        "PNYY:ZRQVPNY PNYY",
        "NQQE:12043 ZPYNVA OYIQ",
        "VASB:ERD FCNAVFU FCRNXVAT BSSVPRE ERDHRFGRQ");

    qbGrfg("G25",
        "PNQ:ZNWBE NPPVQRAG;2410 YN DHVAGN QE;26LBZ PBAFPVBHF NAQ OERNGUVAT// NQI UR JNF ENA",
        "PNYY:ZNWBE NPPVQRAG",
        "NQQE:2410 YN DHVAGN QE",
        "ZNQQE:2410 YA DHVAGN QE",
        "VASB:26LBZ PBAFPVBHF NAQ OERNGUVAT// NQI UR JNF ENA");

    qbGrfg("G26",
        "PNQ:TNF BQBE VAFVQR;2930 ANAPL ORYYR YA;PBZCY NQI UR GHEARQ BA GUR URNG NAQ ABJ UR F",
        "PNYY:TNF BQBE VAFVQR",
        "NQQE:2930 ANAPL ORYYR YA",
        "VASB:PBZCY NQI UR GHEARQ BA GUR URNG NAQ ABJ UR F");

    qbGrfg("G27",
        "PNQ:ZRQVPNY PNYY;1511-214 5GU FG;20LBS PBAFPVBHF NAQ OERNGUVAT// VGPUVAT CEBOYRZF//",
        "PNYY:ZRQVPNY PNYY",
        "NQQE:1511-214 5GU FG",
        "ZNQQE:1511 5GU FG",
        "VASB:20LBS PBAFPVBHF NAQ OERNGUVAT// VGPUVAT CEBOYRZF//");

    qbGrfg("G28",
        "PNQ:ZRQVPNY PNYY;10014-428 F FNZ UBHFGBA CXJL J;BYQRE ZNYR UNIVAT GEBHOYR OERNGUVAT",
        "PNYY:ZRQVPNY PNYY",
        "NQQE:10014-428 F FNZ UBHFGBA CXJL J",
        "ZNQQE:10014 F FNZ UBHFGBA CXJL J",
        "VASB:BYQRE ZNYR UNIVAT GEBHOYR OERNGUVAT");

    qbGrfg("G29",
        "PNQ:ZRQVPNY PNYY;2411 PERRX ZRNQBJF QE;[YNJ] SOPB ERD CQ NF JRYY [02/21/15 22:31:10",
        "PNYY:ZRQVPNY PNYY",
        "NQQE:2411 PERRX ZRNQBJF QE",
        "VASB:SOPB ERD CQ NF JRYY",
        "QNGR:02/21/15",
        "GVZR:22:31:10");

    qbGrfg("G30",
        "PNQ:ZRQVPNY PNYY;2411 PERRX ZRNQBJF QE;ZNYR FHOW GUNG FZBXRQ FLAGURGVP ZNEVWHNAN/ AB",
        "PNYY:ZRQVPNY PNYY",
        "NQQE:2411 PERRX ZRNQBJF QE",
        "VASB:ZNYR FHOW GUNG FZBXRQ FLAGURGVP ZNEVWHNAN/ AB");

    qbGrfg("G31",
        "PNQ:ZRQVPNY PNYY;3311 PUREEL PERRX QE;76LBZ VEERTHYNE URNEG ORNGU UNIVAT GEBHOYR OER",
        "PNYY:ZRQVPNY PNYY",
        "NQQE:3311 PUREEL PERRX QE",
        "VASB:76LBZ VEERTHYNE URNEG ORNGU UNIVAT GEBHOYR OER");

    qbGrfg("G32",
        "PNQ:ZHGHNY NVQ ZVFP YBPNGVBA;3100 XVEOL QE;Rirag fcnjarq sebz NFFVFG BGURE NTRAPL.",
        "PNYY:ZHGHNY NVQ ZVFP YBPNGVBA",
        "NQQE:3100 XVEOL QE",
        "VASB:Rirag fcnjarq sebz NFFVFG BGURE NTRAPL.");

    qbGrfg("G33",
        "PNQ:ZRQVPNY PNYY;1930 YNHERA CY;34lbz pbafpvbhf naq oernguvat uvtu oybbq cerffher jv",
        "PNYY:ZRQVPNY PNYY",
        "NQQE:1930 YNHERA CY",
        "VASB:34lbz pbafpvbhf naq oernguvat uvtu oybbq cerffher jv");

    qbGrfg("G34",
        "PNQ:ZRQVPNY PNYY;2527 IVYYNTR FDHNER QE;ZNYR FHOW YNLVAT BA GUR TEBHAQ NQI UR VF FR",
        "PNYY:ZRQVPNY PNYY",
        "NQQE:2527 IVYYNTR FDHNER QE",
        "VASB:ZNYR FHOW YNLVAT BA GUR TEBHAQ NQI UR VF FR");

    qbGrfg("G35",
        "PNQ:NYNEZ SVER;1611 CNEXIVRJ YA;NHQ / CBN TRARENY SVER NYNEZ 281 835 3350 # NG GUR",
        "PNYY:NYNEZ SVER",
        "NQQE:1611 CNEXIVRJ YA",
        "VASB:NHQ / CBN TRARENY SVER NYNEZ 281 835 3350 # NG GUR");

    qbGrfg("G36",
        "PNQ:FREIVPR PNYY NFFVFG;2022 INYYRL ZNABE QE;74 LB ZNYR / ARRQF URYC SEBZ PUNATVAT S",
        "PNYY:FREIVPR PNYY NFFVFG",
        "NQQE:2022 INYYRL ZNABE QE",
        "VASB:74 LB ZNYR / ARRQF URYC SEBZ PUNATVAT S");

    qbGrfg("G37",
        "PNQ:NYNEZ SVER;3803 A SVGMTRENYQ PG;CBN FZBXR QRGRPGBE. VCCBYVGV, QNIVQ 281 778 8815",
        "PNYY:NYNEZ SVER",
        "NQQE:3803 A SVGMTRENYQ PG",
        "VASB:CBN FZBXR QRGRPGBE. VCCBYVGV, QNIVQ 281 778 8815");

    qbGrfg("G38",
        "PNQ:ZRQVPNY PNYY;1971 GRKNF CXJL;13 LB SRZNYR SNVAGRQ/ NYREG NAQ OERNGUVAT / [02/21",
        "PNYY:ZRQVPNY PNYY",
        "NQQE:1971 GRKNF CXJL",
        "VASB:13 LB SRZNYR SNVAGRQ/ NYREG NAQ OERNGUVAT /");

    qbGrfg("G39",
        "PNQ:ZRQVPNY PNYY;3849 PNEGJEVTUG EQ;2015000017769",
        "PNYY:ZRQVPNY PNYY",
        "NQQE:3849 PNEGJEVTUG EQ",
        "VASB:2015000017769");

    qbGrfg("G40",
        "PNQ:ZRQVPNY PNYY;4106 SERRQBZ GERR QE;28lbs JVGU UVFGBEL BS FRVMHERF// ABG PHEERAGYL",
        "PNYY:ZRQVPNY PNYY",
        "NQQE:4106 SERRQBZ GERR QE",
        "VASB:28lbs JVGU UVFGBEL BS FRVMHERF// ABG PHEERAGYL");

    qbGrfg("G41",
        "PNQ:ZRQVPNY PNYY;1107 ZBFFEVQTR QE;70 LBZ CNFFRQ BHG/ SBNZVAT BHG BS GUR ZBHGU/ ABG",
        "PNYY:ZRQVPNY PNYY",
        "NQQE:1107 ZBFFEVQTR QE",
        "VASB:70 LBZ CNFFRQ BHG/ SBNZVAT BHG BS GUR ZBHGU/ ABG");

    qbGrfg("G42",
        "PNQ:NYNEZ SVER;3807 JVPXFBA ZAE;NHQ/CBN FZBXR QRGRPGBE/ AJBOBQB, WBR NAQ RQVGU/CF AH",
        "PNYY:NYNEZ SVER",
        "NQQE:3807 JVPXFBA ZAE",
        "VASB:NHQ/CBN FZBXR QRGRPGBE/ AJBOBQB, WBR NAQ RQVGU/CF AH");

    qbGrfg("G43",
        "PNQ:ZRQVPNY PNYY;4723 NHGHZA YXF;62LBS URNEG ENPVAT// PBAFPVBHF NAQ OERNGUVAT [02/2",
        "PNYY:ZRQVPNY PNYY",
        "NQQE:4723 NHGHZA YXF",
        "VASB:62LBS URNEG ENPVAT// PBAFPVBHF NAQ OERNGUVAT");

    qbGrfg("G44",
        "PNQ:ZNWBE NPPVQRAG PBHAGL;3399 FVRAAN CXJL/FPNAYNA GEPR;IRU JENCCRQ NEBHAQ N GERR//Z",
        "PNYY:ZNWBE NPPVQRAG PBHAGL",
        "NQQE:3399 FVRAAN CXJL & FPNAYNA GEPR",
        "ZNQQE:3399 FVRAAN CXJL",
        "VASB:IRU JENCCRQ NEBHAQ N GERR//Z");

    qbGrfg("G45",
        "PNQ:NYNEZ ZRQVPNY;4611 EVIRETYNQR PG;ZRQ 4 BHG BS QVFGEVPG/ HANOYR ZNXR PBAG J XRLUB",
        "PNYY:NYNEZ ZRQVPNY",
        "NQQE:4611 EVIRETYNQR PG",
        "VASB:ZRQ 4 BHG BS QVFGEVPG/ HANOYR ZNXR PBAG J XRLUB");

    qbGrfg("G46",
        "PNQ:ZRQVPNY PNYY;2919 QEVSGJBBQ ORAQ QE;1 LBZ UNIVAT FRVMHERF/ OERNGUVAT URNIVYL NG",
        "PNYY:ZRQVPNY PNYY",
        "NQQE:2919 QEVSGJBBQ ORAQ QE",
        "VASB:1 LBZ UNIVAT FRVMHERF/ OERNGUVAT URNIVYL NG");

    qbGrfg("G47",
        "PNQ:ZRQVPNY PNYY;3514 ORAWNZVA SENAXYVA YA;SOPB NQI CBFF FGEBXR [02/20/15 19:56:48",
        "PNYY:ZRQVPNY PNYY",
        "NQQE:3514 ORAWNZVA SENAXYVA YA",
        "VASB:SOPB NQI CBFF FGEBXR",
        "QNGR:02/20/15",
        "GVZR:19:56:48");

    qbGrfg("G48",
        "PNQ:NYNEZ SVER;3902 RZRENYQ YNXR QE;CBN URNG QRGRPGBE XVGPURA / XVMMRR, PUEVFGVAN ER",
        "PNYY:NYNEZ SVER",
        "NQQE:3902 RZRENYQ YNXR QE",
        "VASB:CBN URNG QRGRPGBE XVGPURA / XVMMRR, PUEVFGVAN ER");

    qbGrfg("G49",
        "PNQ:NFFVFG CBYVPR;1899 HF 90N/ZNEGVA YA;BA NA ZVABE/ ERD CQ/ NAQ BAR JERPXRE/ AB VAW",
        "PNYY:NFFVFG CBYVPR",
        "NQQE:1899 HF 90N & ZNEGVA YA",
        "ZNQQE:1899 HF 90N",
        "VASB:BA NA ZVABE/ ERD CQ/ NAQ BAR JERPXRE/ AB VAW");

    qbGrfg("G50",
        "PNQ:ZRQVPNY PNYY;2193 GRKNF CXJL;NQI FVFGRE VA YNJ JNF WHFG VA NA NPPVQRAG [02/20/1",
        "PNYY:ZRQVPNY PNYY",
        "NQQE:2193 GRKNF CXJL",
        "VASB:NQI FVFGRE VA YNJ JNF WHFG VA NA NPPVQRAG");

    qbGrfg("G51",
        "PNQ:ZRQVPNY PNYY;4422 EVIREFGBAR OYIQ;78 LB ZNYR QVNORGVP CEBOYRZF. ZRQVP 10 PBZVAT",
        "PNYY:ZRQVPNY PNYY",
        "NQQE:4422 EVIREFGBAR OYIQ",
        "VASB:78 LB ZNYR QVNORGVP CEBOYRZF. ZRQVP 10 PBZVAT");

    qbGrfg("G52",
        "PNQ:ZRQVPNY PNYY;2707 CNEX BNX PG;76 LB SRZNYR NEZ CNVA/ PBZCY NQI GUNG SRZNYR JNF T",
        "PNYY:ZRQVPNY PNYY",
        "NQQE:2707 CNEX BNX PG",
        "VASB:76 LB SRZNYR NEZ CNVA/ PBZCY NQI GUNG SRZNYR JNF T");

    qbGrfg("G53",
        "PNQ:ZRQVPNY PNYY;2319 RQTRQNYR QE;73 LB SRZNYR J QVSS OERNGUVAT [02/20/15 13:56:55",
        "PNYY:ZRQVPNY PNYY",
        "NQQE:2319 RQTRQNYR QE",
        "VASB:73 LB SRZNYR J QVSS OERNGUVAT",
        "QNGR:02/20/15",
        "GVZR:13:56:55");

    qbGrfg("G54",
        "PNQ:FGEHPGHER SVER;3310 PBHAGEL PYHO OYIQ;KFG QHYYRF BE PURFGRESVRYQ. XRL ZNC 569W.",
        "PNYY:FGEHPGHER SVER",
        "NQQE:3310 PBHAGEL PYHO OYIQ",
        "VASB:KFG QHYYRF BE PURFGRESVRYQ. XRL ZNC 569W.");

    qbGrfg("G55",
        "PNQ:SLV: ;FGEHPGHER SVER;3310 PBHAGEL PYHO OYIQ;KFG QHYYRF BE PURFGRESVRYQ. XRL ZNC",
        "PNYY:FGEHPGHER SVER",
        "NQQE:3310 PBHAGEL PYHO OYIQ",
        "VASB:KFG QHYYRF BE PURFGRESVRYQ. XRL ZNC");

    qbGrfg("G56",
        "PNQ:ZRQVPNY PNYY;2831 TYRAA YNXRF YA;69 LB ZNYR QVNORGVP/ ZRQ 3 BHG BS QVFGEVPG / [",
        "PNYY:ZRQVPNY PNYY",
        "NQQE:2831 TYRAA YNXRF YA",
        "VASB:69 LB ZNYR QVNORGVP/ ZRQ 3 BHG BS QVFGEVPG /");

    qbGrfg("G57",
        "PNQ:ZRQVPNY PNYY;3810 NHOHEA TEBIR PVE;ERD OL ZRQ HAVGF HAX ERNFBA GURL NER VA QVFGE",
        "PNYY:ZRQVPNY PNYY",
        "NQQE:3810 NHOHEA TEBIR PVE",
        "VASB:ERD OL ZRQ HAVGF HAX ERNFBA GURL NER VA QVFGE");

    qbGrfg("G58",
        "PNQ:ZRQVPNY PNYY;3438 5GU FG;ZNYR FHOIW NYFB PUBXVAT [02/20/15 10:17:44 NZQ704] 90",
        "PNYY:ZRQVPNY PNYY",
        "NQQE:3438 5GU FG",
        "VASB:ZNYR FHOIW NYFB PUBXVAT / 90",
        "QNGR:02/20/15",
        "GVZR:10:17:44");

    qbGrfg("G59",
        "PNQ:ZRQVPNY PNYY;3035 UHPXYROREEL;45 LB ZNYR ONPX CNVA [02/20/15 07:45:49 NZQ704] 4",
        "PNYY:ZRQVPNY PNYY",
        "NQQE:3035 UHPXYROREEL",
        "VASB:45 LB ZNYR ONPX CNVA / 4",
        "QNGR:02/20/15",
        "GVZR:07:45:49");

    qbGrfg("G60",
        "PNQ:ZRQVPNY PNYY;1707 TYRATERRA QE;ABG NYREG [02/20/15 07:11:35 NZQ704] 65 LB ZNYR",
        "PNYY:ZRQVPNY PNYY",
        "NQQE:1707 TYRATERRA QE",
        "VASB:ABG NYREG / 65 LB ZNYR",
        "QNGR:02/20/15",
        "GVZR:07:11:35");

    qbGrfg("G61",
        "PNQ:ZRQVPNY PNYY;2711 J CROOYR ORNPU QE;69 LB ZNYR CBFF QBN, PBZCY HANOYR GB JNXR UV",
        "PNYY:ZRQVPNY PNYY",
        "NQQE:2711 J CROOYR ORNPU QE",
        "VASB:69 LB ZNYR CBFF QBN, PBZCY HANOYR GB JNXR UV");

    qbGrfg("G62",
        "PNQ:ZRQVPNY PNYY;1927 JBBQ FUNQBJF QE;30LBS JVGU PURFG CNVAF// YVGGYR GEBHOYR OERNGU",
        "PNYY:ZRQVPNY PNYY",
        "NQQE:1927 JBBQ FUNQBJF QE",
        "VASB:30LBS JVGU PURFG CNVAF// YVGGYR GEBHOYR OERNGU");

    qbGrfg("G63",
        "PNQ:TNF BQBE VAFVQR;1903 TENL FYNGR QE;ERPRAGYL CHEPUNFRQ N JNGRE URNGRE [02/19/15",
        "PNYY:TNF BQBE VAFVQR",
        "NQQE:1903 TENL FYNGR QE",
        "VASB:ERPRAGYL CHEPUNFRQ N JNGRE URNGRE");

    qbGrfg("G64",
        "PNQ:ZRQVPNY PNYY;4422 EVIREFGBAR OYIQ;90LBZ 312 ABG PBAFPVBHF ABG ERFCBAFVIR OHG UR",
        "PNYY:ZRQVPNY PNYY",
        "NQQE:4422 EVIREFGBAR OYIQ",
        "VASB:90LBZ 312 ABG PBAFPVBHF ABG ERFCBAFVIR OHG UR");

    qbGrfg("G65",
        "PNQ:ZRQVPNY PNYY;1219 GJVAVAT BNXF YA;BAR ZBAGU BYQ ZNYR QVSSVPHYGL OERNGUVAT/GHEAVA",
        "PNYY:ZRQVPNY PNYY",
        "NQQE:1219 GJVAVAT BNXF YA",
        "VASB:BAR ZBAGU BYQ ZNYR QVSSVPHYGL OERNGUVAT/GHEAVA");

    qbGrfg("G66",
        "PNQ:ZRQVPNY PNYY;3454 UNIREFUVER QE;87 LBS / VA NAQ BHG PBAFPVBHFARFF / AB QVSSVPHYG",
        "PNYY:ZRQVPNY PNYY",
        "NQQE:3454 UNIREFUVER QE",
        "VASB:87 LBS / VA NAQ BHG PBAFPVBHFARFF / AB QVSSVPHYG");

    qbGrfg("G67",
        "PNQ:NYNEZ PNEOBA ZBABKVQR;5942 FGBEL OBBX GEY;NHQ/ CBN PNEOBAQ ZBABKVQR QRGRPGBE [0",
        "PNYY:NYNEZ PNEOBA ZBABKVQR",
        "NQQE:5942 FGBEL OBBX GEY",
        "VASB:NHQ/ CBN PNEOBAQ ZBABKVQR QRGRPGBE");

    qbGrfg("G68",
        "PNQ:ZRQVPNY PNYY;2815-2201 PLCERFF CBVAG QE;RYQREYL SRZNYR SNYY IVPGVZ/WNZZRQ ARPX N",
        "PNYY:ZRQVPNY PNYY",
        "NQQE:2815-2201 PLCERFF CBVAG QE",
        "ZNQQE:2815 PLCERFF CBVAG QE",
        "VASB:RYQREYL SRZNYR SNYY IVPGVZ/WNZZRQ ARPX N");

    qbGrfg("G69",
        "PNQ:TNF BQBE VAFVQR;6706 FHGGREF PERRX GEY;PBZCY NQI JURA FUR TBG UBZR FZRYYF FGEBAT",
        "PNYY:TNF BQBE VAFVQR",
        "NQQE:6706 FHGGREF PERRX GEY",
        "VASB:PBZCY NQI JURA FUR TBG UBZR FZRYYF FGEBAT");

    qbGrfg("G70",
        "PNQ:YBPX VA;5744 FU 6;PBZCY NQI GUVF IRU VF ABG UREF NAQ PUVYQ VF NYBAR [02/19/15 1",
        "PNYY:YBPX VA",
        "NQQE:5744 FU 6",
        "ZNQQE:5744 GK 6",
        "VASB:PBZCY NQI GUVF IRU VF ABG UREF NAQ PUVYQ VF NYBAR");

    qbGrfg("G71",
        "PNQ:ZRQVPNY PNYY;2326 EVQTRZBAG QE;60 LB SRZNYR QVSS OERNGUVAT [02/19/15 12:16:48 E",
        "PNYY:ZRQVPNY PNYY",
        "NQQE:2326 EVQTRZBAG QE",
        "VASB:60 LB SRZNYR QVSS OERNGUVAT",
        "QNGR:02/19/15",
        "GVZR:12:16:48");

    qbGrfg("G72",
        "PNQ:NYNEZ SVER;8717 FPNAYNA GEPR;NHQ / CBN TRARENY / 281 778 0366 [02/19/15 10:36:4",
        "PNYY:NYNEZ SVER",
        "NQQE:8717 FPNAYNA GEPR",
        "VASB:NHQ / CBN TRARENY / 281 778 0366");

    qbGrfg("G73",
        "PNQ:ZRQVPNY PNYY;3102 BNXYRNS PG;46 LBS / UNIVAT QVSS OERNGUVAT NAQ FRRV / HANOYR GB",
        "PNYY:ZRQVPNY PNYY",
        "NQQE:3102 BNXYRNS PG",
        "VASB:46 LBS / UNIVAT QVSS OERNGUVAT NAQ FRRV / HANOYR GB");

    qbGrfg("G74",
        "PNQ:FREIVPR PNYY NFFVFG;3806 PELFGNY SNYYF QE;83 LBZ / SNYY IVP / AB VAWHEVRF / ARRQ",
        "PNYY:FREIVPR PNYY NFFVFG",
        "NQQE:3806 PELFGNY SNYYF QE",
        "VASB:83 LBZ / SNYY IVP / AB VAWHEVRF / ARRQ");

    qbGrfg("G75",
        "PNQ:HAQRGREZVARQ GLCR PNYY;11818 F ZVPUNRY PVE;SBBQ VF VA GUR BIRA PBBXVAT NAQ GUR B",
        "PNYY:HAQRGREZVARQ GLCR PNYY",
        "NQQE:11818 F ZVPUNRY PVE",
        "VASB:SBBQ VF VA GUR BIRA PBBXVAT NAQ GUR B");

    qbGrfg("G76",
        "PNQ:NYNEZ SVER;3223 EBOVAFBA EQ;CBN TRARENY ERFVQRAGVNY / ZBEEVF, EQ 281 437 7926 [",
        "PNYY:NYNEZ SVER",
        "NQQE:3223 EBOVAFBA EQ",
        "VASB:CBN TRARENY ERFVQRAGVNY / ZBEEVF, EQ 281 437 7926");

    qbGrfg("G77",
        "PNQ:ZNWBE NPPVQRAG;TRFFARE OJ 8 RO RAG ENZC/F FNZ UBHFGBA CXJL J;GBLG PBEBYYN NAQ JU",
        "PNYY:ZNWBE NPPVQRAG",
        "NQQE:TRFFARE OJ 8 RO RAG ENZC & F FNZ UBHFGBA CXJL J",
        "ZNQQE:TRFFARE OJ 8 RAG ENZC & F FNZ UBHFGBA CXJL J",
        "VASB:GBLG PBEBYYN NAQ JU");

    qbGrfg("G78",
        "PNQ:ZRQVPNY PNYY;3331 PUVZREN YA;34 LBZ / NOQBZVANY CNVA / ZRQVP 5 BA FPRAR ERD SVEF",
        "PNYY:ZRQVPNY PNYY",
        "NQQE:3331 PUVZREN YA",
        "VASB:34 LBZ / NOQBZVANY CNVA / ZRQVP 5 BA FPRAR ERD SVEF");

    qbGrfg("G79",
        "PNQ:ZRQVPNY PNYY;510 FGRCUNAVR QE;95 LBS / QVSS OERNGUVAT NAQ SRRYVAT IREL VYY [02/",
        "PNYY:ZRQVPNY PNYY",
        "NQQE:510 FGRCUNAVR QE",
        "VASB:95 LBS / QVSS OERNGUVAT NAQ SRRYVAT IREL VYY");

    qbGrfg("G80",
        "PNQ:ZRQVPNY PNYY;1926 DHNVY INYYRL RNFG QE;PBZCY NQI OEBGURE WHFG ZNQR YBP/ NAQ JVYY",
        "PNYY:ZRQVPNY PNYY",
        "NQQE:1926 DHNVY INYYRL RNFG QE",
        "VASB:PBZCY NQI OEBGURE WHFG ZNQR YBP/ NAQ JVYY");

    qbGrfg("G81",
        "PNQ:NYNEZ SVER;2922 SVIR BNXF QE;Rirag fcnjarq sebz NYNEZ ERFVQRAGVNY. [02/18/2015",
        "PNYY:NYNEZ SVER",
        "NQQE:2922 SVIR BNXF QE",
        "VASB:Rirag fcnjarq sebz NYNEZ ERFVQRAGVNY.");

    qbGrfg("G82",
        "PNQ:HAXABJA ZNWBE ZVABE NPPVQRAG;13450 F TRFFARE EQ;NPPVQRAG VA GUR ZRQVNA/ HAX VAWH",
        "PNYY:HAXABJA ZNWBE ZVABE NPPVQRAG",
        "NQQE:13450 F TRFFARE EQ",
        "VASB:NPPVQRAG VA GUR ZRQVNA/ HAX VAWH");

    qbGrfg("G83",
        "PNQ:NYNEZ SVER;4200 PNEGJEVTUG EQ;NHQ/CBN TRARENY NYNEZ MBAR 1 [02/18/15 15:28:17 G",
        "PNYY:NYNEZ SVER",
        "NQQE:4200 PNEGJEVTUG EQ",
        "VASB:NHQ/CBN TRARENY NYNEZ MBAR 1",
        "QNGR:02/18/15",
        "GVZR:15:28:17");

    qbGrfg("G84",
        "PNQ:FREIVPR PNYY NFFVFG;1711 CNZRYN YA;68LBS SNYY IVPGVZ / ABG VAWHERQ [02/18/15 14",
        "PNYY:FREIVPR PNYY NFFVFG",
        "NQQE:1711 CNZRYN YA",
        "VASB:68LBS SNYY IVPGVZ / ABG VAWHERQ");

  }

  choyvp fgngvp ibvq znva(Fgevat[] netf) {
    arj GKZvffbhevPvglCnefreGrfg().trarengrGrfgf("G1");
  }
}