cnpxntr arg.narv.pnqcntr.cnefref.GK;

vzcbeg arg.narv.pnqcntr.cnefref.OnfrCnefreGrfg;

vzcbeg bet.whavg.Grfg;

/*
Gneenag Pbhagl, GK
Pbagnpg: "Wreevgg Tvqrba" <w.tvqrba@gpsvernynez.pbz>
Fraqre:gneenagpglqfc@erqazkpnq.pbz

GENHZN, TEBHAQ YIY SNYY: RZF SNYY 99 LB/Z  ng 5604 A FPUVYQRE QE, EVIRE BNXF  p/f: JNYGRE QE Obk: 61F . . 10:12:42
FGEHPGHER SVER, Qhcyrk/ Pbaqb ng 117 FG PYNER QE, GNEENAG PBHAGL p/f FG RYVMNORGU QE Obk 101H.. 23:57:40
ZRQVPNY, Pneqvnp Ceboyrz: 45 LB/S P&O, UNIVAT CNYCVGNGVBAF ng 5130 ORA QNL ZHEEVA EQ YBG 725, GNEENAG PBHAGL p/f: UJL 377 F Obk: 99G. . 19:00:18
Z I N, Haxabja: QHZC GEHPX IF FHI, CBFF QVFZRZOREZRAG ng 7936 PBASRQRENGR CNEX EQ, GNEENAG PBHAGL p/f: FVYIRE PERRX NMYR EQ Obk: 49C. . 17:25:51
TENFF SVER, Fvatyr Fgngvba: ERCBEGRQ FZNYY TENFF SVER ng 12100 BYQ TENAOHEL EQ, GNEENAG PBHAGL p/f: SYBLQ UNZCGBA EQ Obk: 116K. . 17:30:33
GENHZN, TEBHAQ YIY SNYY: 80 LB/Z SNYY. UVC CNVA. P/O ng 300 A BYQ QRPNGHE EQ, FNTVANJ p/f: J ZPYREBL OYIQ Obk: 33K B: SVEFG ONCGVFG PUHEPU. . 10:52:00
ZRQVPNY, ZRQVPNY NYNEZ: AB NAFJRE BA PNYY ONPX ng 5913 RQ PBNQL EQ, RQTRPYVSS IVYYNTR p/f: FLPNZBER PERRX EQ Obk: 90M. . 03:02:46

Pbagnpg: Npgvir911
Ntrapl anzr: Rqtrpyvss Ivyyntr Sver Qrcg.
Ybpngvba: Rqtrpyvss Ivyyntr, GK, Havgrq Fgngrf
Fraqre: nyregf@gpsvernynez.pbz

GENHZN, URNQ VAWHEL: UVG VA SNPR JVGU ZRGNY ORQSENZR   Pbafpvbhf:  Oernguvat \a  ng 2100 NYGNZRFN OYIQ, RQTRPYVSS IVYYNTR  p/f: PEBJYRL EQ Obk: 104O   B: TBBQJVYY VAQHFGEVRF VAP . . 09:29:30
ZRQVPNY, FVPX CREFBA: 45 L/B ZNYR   Pbafpvbhf:  Oernguvat \a  ng 8 GNYYJBBQ YA, RQTRPYVSS IVYYNTR  p/f: PUREELEVQTR QE Obk: 90M . . 14:37:41
GENHZN, NEZ / YRT SENPGHER: 85 LBS PBAPVBHF NAQ OERNGUVAT   Pbafpvbhf:  Oernguvat \a  ng 1628 YNZCYVTUGRE YA, RQTRPYVSS IVYYNTR  p/f: JVAA QE Obk: 104P . . 10:04:24
ZRQVPNY, Pneqvnp Ceboyrz ng 2017 ZVAT QE, RQTRPYVSS IVYYNTR  p/f: PEBJYRL EQ Obk: 90L . . 07:01:58
ZRQVPNY, NOQBZVANY CNVA ng 1201 LBEX QE, RQTRPYVSS IVYYNTR  p/f: ZRERQVGU YA Obk: 90M . . 03:42:54
ZRQVPNY, ZRQVPNY NYNEZ ng 1412 YVZRFGBAR GEY, RQTRPYVSS IVYYNTR  p/f: PNZRYBG EQ Obk: 104P . . 20:25:00
TENFF / OEHFU SVER, YRFF GUNA 1 NPER ng 685 WBUA O FVNF ZRZBEVNY CXJL, RQTRPYVSS IVYYNTR  p/f: URZCUVYY FG Obk: 91F   B: SBEG JBEGU FGNE-GRYRTENZ QVFGEVOHGVBA PRAGRE . . 19:24:21
ZRQVPNY, Oernguvat Ceboyrz ng 1313 LBEX QE, RQTRPYVSS IVYYNTR  p/f: FLPNZBER QE Obk: 90M . . 22:16:46
NTRAPL NFFVFG, FGNGVBA PBIRENTR ng 400 J RABA NIR, RIREZNA  p/f: F UNAFONETRE Obk: 106W   B: RIREZNA SVER QRCNEGZRAG . . 09:22:54
FGEHPGHER SVER, Fvatyr Snzvyl ng 304 GUBZNF CY, RIREZNA  p/f: QRNQ RAQ Obk: 106C . . 06:07:45
UNMZNG, Cvcryvar Ehcgher: TNF YVAR PHG VA GUR ONPX LNEQ ng 3 LBEX QE, RQTRPYVSS IVYYNTR  p/f: PEBJYRL EQ Obk: 90L . . 12:03:49
NYNEZ - Erfvqragvny, Fzbxr Qrgrpgbe: NYNEZ CNARY ng 24 PURYFRN QE, RQTRPYVSS IVYYNTR  p/f: OERAGBA EQ Obk: 90L . . 08:08:56
ZRQVPNY, FRVMHERF / PBAIHYFVBAF ng 11 GNYYJBBQ YA, RQTRPYVSS IVYYNTR  p/f: PUREELEVQTR QE Obk: 90M . . 17:22:03
VAIRFG, Haxabja Glcr Sver: OBK BA SVER VA GUR EBNQ JNL ng 6017 FLPNZBER PERRX EQ, RQTRPYVSS IVYYNTR  p/f: PYVSS PG Obk: 90M . . 03:30:28
ZRQVPNY, URZBEEUNTR / OYRRQ: 20 L/B ZNYR; ERPGNY OYRRQVAT ng 4913 BUVB TNEQRA EQ, EVIRE BNXF  p/f: XRVGU CHZCURERL QE Obk: 61C   B: OENHZF . . 14:28:39
ZRQVPNY, HAERFCBAFVIR CREFBA: 28 L/B SRZNYR, ABG OERNGUVAT TBBQ ng 2008 PYVSSFVQR QE, RQTRPYVSS IVYYNTR  p/f: PEBJYRL EQ Obk: 90L . . 13:03:12
GENHZN, YNPRENGVBA: 4 L/B ZNYR PNB YBPNGRQ VA GUR SEBAG CNGEXVAT YBG ng 4900 EVIRE BNXF OYIQ, EVIRE BNXF  p/f: TYRAJVPX QE Obk: 61X   B: EVIRE BNXF ZHAVPVCNY PBZCYRK . . 12:40:10
NTRAPL NFFVFG, FGNGVBA PBIRENTR ng 4900 EVIRE BNXF OYIQ, EVIRE BNXF  p/f: TYRAJVPX QE Obk: 61X   B: EVIRE BNXF ZHAVPVCNY PBZCYRK . . 06:32:42
ZRQVPNY, FRVMHERF / PBAIHYFVBAF: AB CNGVRAG VASB ng 2 PURYFRN QE, RQTRPYVSS IVYYNTR  p/f: PEBJYRL EQ Obk: 90L . . 14:17:19
ZRQVPNY, Oernguvat Ceboyrz: 71 LBZ ng 2 PURYFRN QE, RQTRPYVSS IVYYNTR  p/f: PEBJYRL EQ Obk: 90L . . 12:53:55
FGEHPGHER SVER, Fvatyr Snzvyl: SVER EBBS ng 1904 EBPXZBBE QE, RQTRPYVSS IVYYNTR  p/f: YHANE QE Obk: 90L . . 18:29:10
ZRQVPNY, PUBXVAT: 90 LBN SRZNYR PBAF OERNGUVAT  ng 2 PURYFRN QE, RQTRPYVSS IVYYNTR  p/f: PEBJYRL EQ Obk: 90L . . 01:15:05
Z I N, Pne / Cvpx-hc: 2 IRUVPYRF. P35 BA FPRAR ng 6600 PEBJYRL EQ, RQTRPYVSS IVYYNTR  p/f: YVZRFGBAR GEY Obk: 104P . . 18:16:37
ZRQVPNY, FVPX CREFBA: 80 L/B SRZNYR PBAFPVBHF NAQ OERNGUVAT ng 2021 ZVAT QE, RQTRPYVSS IVYYNTR  p/f: PEBJYRL EQ Obk: 90L . . 10:23:30
ERFPHR, Puvyq Ybpxrq va Iruvpyr: vasnag ng 15 GNYYJBBQ YA, RQTRPYVSS IVYYNTR  p/f: PUREELEVQTR QE Obk: 90M . . 12:21:34
ZRQVPNY, FRVMHERF / PBAIHYFVBAF: 47 LBN ZNYR  ng 2 PURYFRN QE, RQTRPYVSS IVYYNTR  p/f: PEBJYRL EQ Obk: 90L . . 16:16:35
ZRQVPNY, FRVMHERF / PBAIHYFVBAF: 33 L/B ZNYR ng 2121 GVCCL GRE, RQTRPYVSS IVYYNTR  p/f: SNZVYL CY Obk: 90L . . 05:32:06
ZRQVPNY: haxabja ntr srznyr qvffbevragrq ng 3 PURYFRN QE, RQTRPYVSS IVYYNTR  p/f: PEBJYRL EQ Obk: 90L . . 17:23:50
CHOYVP NFFVFG, Yvsg Uryc ng 34 PURYFRN QE, RQTRPYVSS IVYYNTR  p/f: OERAGBA EQ Obk: 90L . . 13:27:20
ZRQVPNY, QVNORGVP CEBOYRZ: 60 L/B ZNYR PBAFPVBHF NAQ OERNGUVAT ng 2012 THZZ EQ, RQTRPYVSS IVYYNTR  p/f: SNZVYL CY Obk: 104O . . 19:22:01
ZRQVPNY, Oernguvat Ceboyrz: 73 L/B SZNYR ng 5928 JRFGPERFG QE R, RQTRPYVSS IVYYNTR  p/f: PURYFRN QE Obk: 90L . . 18:00:48
GENHZN, NFFNHYG: HAX NTR SRZNYR VAWHERQ FRPBAQNEL GB NFFNHYG  ng 2100 NYGNZRFN OYIQ, RQTRPYVSS IVYYNTR  p/f: PEBJYRL EQ Obk: 104O   B: TBBQJVYY VAQHFGEVRF VAP . . 17:38:52
Arkg Nynez sbe 10412 OENATHF QE Abgr: Fnzr Pnyy Glcr . . 21:58:06
ZRQVPNY, FRVMHERF / PBAIHYFVBAF: 32 L/B Z ng 2121 GVCCL GRE, RQTRPYVSS IVYYNTR  p/f: SNZVYL CY Obk: 90L . . 10:46:06
ZRQVPNY, FVPX CREFBA: 11 L/B SRZNYR QVMML  ng 5920 JRFGPERFG QE J, RQTRPYVSS IVYYNTR  p/f: PURYFRN QE Obk: 90L . . 22:34:43
ZRQVPNY, ZRQVPNY NYNEZ ng 5912 JRFGPERFG QE, RQTRPYVSS IVYYNTR  p/f: PURYFRN QE Obk: 90L . . 21:28:35
CHOYVP NFFVFG, Jrysner / Ivgnyf Purpx: 73 L/B SRZNYR ng 6300 PYVSSFVQR QE, RQTRPYVSS IVYYNTR  p/f: ZVAT QE Obk: 90L . . 14:41:42
ZRQVPNY, Hapbafpvbhf / Snvagvat Crefba: HAX NTR SRZNYR CNFFRQ BHG VA QNEX OYH  QBQTR C/H ng 2100 NYGNZRFN OYIQ, RQTRPYVSS IVYYNTR  p/f: PEBJYRL EQ Obk: 104O   B: TBBQJVYY VAQHFGEVRF VAP . . 10:51:08
ZRQVPNY, Purfg Cnva: 85 LBS PBAPVBHF NAQ OERNGUVAT ng 2108 ZVAT QE, RQTRPYVSS IVYYNTR  p/f: PEBJYRL EQ Obk: 90K . . 08:22:32
ZRQVPNY, Purfg Cnva: 49 LBN SRZNYR PURFG CNVAF  ng 51 ORRPUPERRX QE, RQTRPYVSS IVYYNTR  p/f: GNYYJBBQ EQ Obk: 90M . . 21:21:47
CHOYVP NFFVFG, Yvsg Uryc: 75 LBS ERS 14324592 YBPX OBK 3413 ng 15 ORRPUPERRX QE, RQTRPYVSS IVYYNTR  p/f: OYHR CVAR QE Obk: 90M . . 02:32:17
GENHZN, TEBHAQ YIY SNYY: 85 LBN ZNYR CBFFVOYR VAWHEVRF SEBZ TEBHAQ YRIRY SNYY  ng 1412 YVZRFGBAR GEY, RQTRPYVSS IVYYNTR  p/f: PNZRYBG EQ Obk: 104P . . 18:34:28
ZRQVPNY: 41 LBS QEVAXVAT NYY JRRXRAQ/ P+O+ ng 2009 ZVAT QE, RQTRPYVSS IVYYNTR  p/f: PEBJYRL EQ Obk: 90L . . 15:29:30
GENHZN, YNPRENGVBA: 24 ng 1304 EBPXZBBE QE, RQTRPYVSS IVYYNTR  p/f: RQ PBNQL EQ Obk: 90M . . 21:24:28
GENHZN, TEBHAQ YIY SNYY: 75 L/B SRZNYR; BHGFVQR ng 1717 YVZRFGBAR GEY, RQTRPYVSS IVYYNTR  p/f: YLEVP Obk: 104P . . 14:58:25
GENHZN, TEBHAQ YIY SNYY: HAXABJA CG VASB  ng 2125 YVCCF QE, RQTRPYVSS IVYYNTR  p/f: PEBJYRL EQ Obk: 90L . . 07:52:58
ZRQVPNY, Hapbafpvbhf / Snvagvat Crefba ng 2105 PURYFRN QE, RQTRPYVSS IVYYNTR  p/f: JRFGPERFG QE R Obk: 90L . . 15:22:06
ZRQVPNY, QVNORGVP CEBOYRZ: 78 L/B S SRRYF YVXR TBVAT GB CNFF BHG. ng 6520 YNINAB QE, RQTRPYVSS IVYYNTR  p/f: EBPXZBBE QE Obk: 104P . . 23:51:40
NYNEZ - Erfvqragvny, Fzbxr Qrgrpgbe: MBAR 5 FZBXR QRGRPGBE ng 2112 GVCCL GRE, RQTRPYVSS IVYYNTR  p/f: SNZVYL CY Obk: 90L . . 14:03:27
CHOYVP NFFVFG, Yvsg Uryc: 73 L/B SRZNYR ARRQF YVSG NFFVFGNAPR ng 6300 PYVSSFVQR QE, RQTRPYVSS IVYYNTR  p/f: ZVAT QE Obk: 90L . . 04:51:32
ZRQVPNY, Oernguvat Ceboyrz: 69 LBN SRZNYR HAXA CEBOYRZF QVSS OERNGUVAT  ng 5933 JRFGPERFG QE R, RQTRPYVSS IVYYNTR  p/f: PURYFRN QE Obk: 90L . . 10:07:01
Z I N, Pne / Cvpx-hc ng 6300 PEBJYRL EQ, RQTRPYVSS IVYYNTR  p/f: ZVAT QE Obk: 90L . . 13:22:52
UNMZNG, Fzryy bs Tnf Vafvqr: URNEF TNF YRNXVAT VA UVF UBHFR ng 6 ORRPUPERRX QE, RQTRPYVSS IVYYNTR  p/f: OYHR CVAR QE Obk: 90M . . 23:00:22
ZRQVPNY, Purfg Cnva: 56 L/B S  ng 6305 NEGUHE QE, RQTRPYVSS IVYYNTR  p/f: EBPXZBBE QE Obk: 90L . . 05:40:48
ZRQVPNY, QVNORGVP CEBOYRZ: 72 LBS  ng 15 ORRPUPERRX QE, RQTRPYVSS IVYYNTR  p/f: OYHR CVAR QE Obk: 90M . . 15:29:55
ZRQVPNY, Oernguvat Ceboyrz: 41 LBN SRZNYR VAWHEVRF SEBZ TEBHAQ YRIRY SNYY QVSS OERNGUVAT CBFF OEBXRA EVO  ng 2009 ZVAT QE, RQTRPYVSS IVYYNTR  p/f: PEBJYRL EQ Obk: 90L . . 06:54:51
ZRQVPNY, FRVMHERF / PBAIHYFVBAF: 67 L/B ZNYR ng 1 ORRPUPERRX QE, RQTRPYVSS IVYYNTR  p/f: TYRA PEBFFVAT EQ Obk: 90M . . 14:50:44
ZRQVPNY, Hapbafpvbhf / Snvagvat Crefba: SRRYVAT YVTUGURNQRQ. ng 1800 EBPXZBBE QE, RQTRPYVSS IVYYNTR  p/f: NEGUHE QE Obk: 90L . . 13:36:14
FGEHPGHER SVER, YRFF GUNA 1 NPER: PNYYRE ERCBEGF N YNETR SVER ORUVAQ UVZ, UR ORYVRIRF VG GB OR N OEHFU SVER.\a\aNQQVGVBANY PNYYREF FHTTRFG N FGE SVER ng 3700 OHEYRFBA ERGGN EQ, GNEENAG PBHAGL  p/f: FHAAL YA Obk: 120I . . 06:56:07
ZRQVPNY, PUBXVAT: 10 LBN ZNYR PUBPXVAT ABG PUBPXVAT NALZBER  ng 5 ORRPUPERRX QE, RQTRPYVSS IVYYNTR  p/f: TYRA PEBFFVAT EQ Obk: 90M . . 19:42:46
BHGFVQR SVER, GENFU CVYR: VA GUR QEVIRJNL GENFU ONT ng 6408 YNINAB QE, RQTRPYVSS IVYYNTR  p/f: EBPXZBBE QE Obk: 90L . . 08:11:19
ZRQVPNY, NYYRETVRF / RAIRABZNGVBAF: 2 L/B ZNYR PBAFPVBHF NAQ OERNGUVAT ng 2017 WRFFVR CY, RQTRPYVSS IVYYNTR  p/f: SNZVYL CY Obk: 104P . . 20:38:17
Z I N, Crqrfgevna: 16 L/B SRZNYR PBAFPVBHF NAQ OERNGUVAT ng 5 FGBARTNGR QE, RQTRPYVSS IVYYNTR  p/f: IVYYNTR CXJL Obk: 90M . . 17:44:40
CHOYVP NFFVFG, Yvsg Uryc: 84 L/B ZNYR  ng 6101 RQ PBNQL EQ, RQTRPYVSS IVYYNTR  p/f: LBEX QE Obk: 90M . . 17:17:20
ZRQVPNY, HAXBJA CEBOYRZ: 69 L/B SRZNYR, QVFBEVRAGRQ NAQ PBASHFRQ ng 1420 YVAJBBQ YA, RQTRPYVSS IVYYNTR  p/f: JVAA QE Obk: 90M . . 11:43:10
ZRQVPNY, BIREQBFR / CBVFBAVAT: 28 L/B SRZNYR, CBFF QENAX QENAB; CBFF NGGRZCG FHVPVQR ng 1617 YVZRFGBAR GEY, RQTRPYVSS IVYYNTR  p/f: YLEVP Obk: 104P . . 10:23:46
ZRQVPNY, Oernguvat Ceboyrz: 88 L/B SRZNYR PBAFPVBHF NAQ OERNGUVAT ng 2005 PYVSSFVQR QE, RQTRPYVSS IVYYNTR  p/f: PEBJYRL EQ Obk: 90L . . 17:26:14
ZRQVPNY, FVPX CREFBA ng 6321 YYNAB QE, RQTRPYVSS IVYYNTR  p/f: EBPXZBBE QE Obk: 90L . . 07:52:31
FGEHPGHER SVER, Ynetr Pbzzrepvny ng 1220 R S Z EQ 1187, PEBJYRL Obk:  . . 18:41:50
GENHZN, HAX GLCR VAWHEL: 46 LBZ  ng 408 PUEVFGVR NIR, RIREZNA  p/f: INQRA Obk: 106W . . 18:12:47
NTRAPL NFFVFG, FGNGVBA PBIRENTR: PBIRE NFFVTAZRAG ng 400 J RABA NIR, RIREZNA  p/f: F UNAFONETRE Obk: 106W   B: RIREZNA SVER QRCNEGZRAG . . 16:49:20
GENHZN, TEBHAQ YIY SNYY: 21 LBZ YBAT OBNEQVAT ng 5100 OEBJA YA, GNEENAG PBHAGL  p/f: FURYOL EQ Obk: 107F . . 16:21:33
TENFF / OEHFU SVER, 1 GB 2 NPERF: FYBJ ZBIVAT PEBJYRL FVQR BS GUR GENVA GENPX. ng 10300 BYQ TENAOHEL EQ, GNEENAG PBHAGL  p/f: FGRJNEG SRYGM EQ Obk: 116N . . 15:34:19
CHOYVP NFFVFG, Yvsg Uryc: 74 L/B SRZNYR, YVSG URYC BAYL. AB VAWHEVRF. ng 6500 YNINAB QE, RQTRPYVSS IVYYNTR  p/f: EBPXZBBE QE Obk: 104P . . 10:00:11
ZRQVPNY, CFLPUVNGEVP RZRETRAPL: 20 LB/S  ng 2013 GVCCL GRE, RQTRPYVSS IVYYNTR  p/f: SNZVYL CY Obk: 90L . . 01:58:10
FGEHPGHER SVER, Fvatyr Snzvyl: ERCBEG BS CBFFVOYR FGEHPGHER SVER HAXA VS NALBAR VF VA GUR UBHFR  ng 2021 LBEX QE, RQTRPYVSS IVYYNTR  p/f: PEBJYRL EQ Obk: 90L . . 19:42:02
ZRQVPNY, Oernguvat Ceboyrz: 86 LBS ng 1412 YVZRFGBAR GEY, RQTRPYVSS IVYYNTR  p/f: PNZRYBG EQ Obk: 104P . . 19:25:13
ZRQVPNY, Hapbafpvbhf / Snvagvat Crefba: 41 L/B ZNYR ng 8 PURYFRN QE, RQTRPYVSS IVYYNTR  p/f: PEBJYRL EQ Obk: 90L . . 04:09:41
ZRQVPNY, Purfg Cnva: 47 LBZ ng 2 PURYFRN QE, RQTRPYVSS IVYYNTR  p/f: PEBJYRL EQ Obk: 90L . . 19:06:47
ZRQVPNY, Purfg Cnva: HAXABJA NTR ZNYR  ng 24 PURYFRN QE, RQTRPYVSS IVYYNTR  p/f: OERAGBA EQ Obk: 90L . . 18:52:55
ZRQVPNY, FVPX CREFBA: 40 L/B S QG'F P/B YBJ OC. ng 2009 ZVAT QE, RQTRPYVSS IVYYNTR  p/f: PEBJYRL EQ Obk: 90L . . 02:46:49
GENHZN, TEBHAQ YIY SNYY: HAXA NTR ZNYR ng 1605 RQTRPYVSS EQ, RQTRPYVSS IVYYNTR  p/f: OERAGBA EQ Obk: 90J   B: RQTRPYVSS IVYYNTR ZHAVPVCNY PBZCYRK . . 15:29:22
ZRQVPNY, FVPX CREFBA: 92 L/B SRZNYR PBAFPVBHF NAQ OERNGUVAT ng 5916 JRFGPERFG QE, RQTRPYVSS IVYYNTR  p/f: PURYFRN QE Obk: 90L . . 18:48:54
ZRQVPNY, FVPX CREFBA: 85 L/B SRZNYR PBAFPVBHF NAQ OERNGUVAT ng 1412 YVZRFGBAR GE, RQTRPYVSS IVYYNTR  p/f: PNZRYBG EQ Obk: 104P . . 08:56:33
GENHZN, NFFNHYG: HAXABJA NTR SRZNYR  ng 2100 GVCCL GRE, RQTRPYVSS IVYYNTR  p/f: SNZVYL CY Obk: 90L . . 02:49:22
GENHZN, TEBHAQ YIY SNYY: 79 LBN SRZNYR VAWHEVRF SEBZ TEBHAQ YRIRY SNE  ng 2013 THZZ EQ, RQTRPYVSS IVYYNTR  p/f: SNZVYL CY Obk: 104O . . 02:07:41
UNMZNG ng 77 YHPNF YA, RQTRPYVSS IVYYNTR  p/f: YVAJBBQ YA Obk: 90M . . 15:46:27
ZRQVPNY, Fgebxr / PIN: AB CG VASB TVIRA ng 2013 PYVSSFVQR QE, RQTRPYVSS IVYYNTR  p/f: PEBJYRL EQ Obk: 90L . . 13:16:03
ZRQVPNY, Oernguvat Ceboyrz: 84 LBS ng 2108 ZVAT QE, RQTRPYVSS IVYYNTR  p/f: PEBJYRL EQ Obk: 90K . . 01:25:51

*/

choyvp pynff GKGneenagPbhaglCnefreGrfg rkgraqf OnfrCnefreGrfg {
  
  choyvp GKGneenagPbhaglCnefreGrfg() {
    frgCnefre(arj GKGneenagPbhaglCnefre(), "GNEENAG PBHAGL", "GK");
  }
  
  @Grfg
  choyvp ibvq grfgCnefre() {

    qbGrfg("G1",
        "GENHZN, TEBHAQ YIY SNYY: RZF SNYY 99 LB/Z  ng 5604 A FPUVYQRE QE, EVIRE BNXF  p/f: JNYGRE QE Obk: 61F . . 10:12:42",
        "PNYY:GENHZN, TEBHAQ YIY SNYY",
        "VASB:RZF SNYY 99 LB/Z",
        "NQQE:5604 A FPUVYQRE QE",
        "PVGL:EVIRE BNXF",
        "K:JNYGRE QE",
        "OBK:61F",
        "GVZR:10:12:42");

    qbGrfg("G2",
        "FGEHPGHER SVER, Qhcyrk/ Pbaqb ng 117 FG PYNER QE, GNEENAG PBHAGL p/f FG RYVMNORGU QE Obk 101H.. 23:57:40",
        "PNYY:FGEHPGHER SVER, Qhcyrk/ Pbaqb",
        "NQQE:117 FG PYNER QE",
        "PVGL:GNEENAG PBHAGL",
        "K:FG RYVMNORGU QE",
        "OBK:101H",
        "GVZR:23:57:40");

    qbGrfg("G3",
        "ZRQVPNY, Pneqvnp Ceboyrz: 45 LB/S P&O, UNIVAT CNYCVGNGVBAF ng 5130 ORA QNL ZHEEVA EQ YBG 725, GNEENAG PBHAGL p/f: UJL 377 F Obk: 99G. . 19:00:18",
        "PNYY:ZRQVPNY, Pneqvnp Ceboyrz",
        "VASB:45 LB/S P&O, UNIVAT CNYCVGNGVBAF",
        "NQQE:5130 ORA QNL ZHEEVA EQ",
        "NCG:725",
        "PVGL:GNEENAG PBHAGL",
        "K:UJL 377 F",
        "OBK:99G",
        "GVZR:19:00:18");

    qbGrfg("G4",
        "Z I N, Haxabja: QHZC GEHPX IF FHI, CBFF QVFZRZOREZRAG ng 7936 PBASRQRENGR CNEX EQ, GNEENAG PBHAGL p/f: FVYIRE PERRX NMYR EQ Obk: 49C. . 17:25:51",
        "PNYY:Z I N, Haxabja",
        "VASB:QHZC GEHPX IF FHI, CBFF QVFZRZOREZRAG",
        "NQQE:7936 PBASRQRENGR CNEX EQ",
        "PVGL:GNEENAG PBHAGL",
        "K:FVYIRE PERRX NMYR EQ",
        "OBK:49C",
        "GVZR:17:25:51");

    qbGrfg("G5",
        "TENFF SVER, Fvatyr Fgngvba: ERCBEGRQ FZNYY TENFF SVER ng 12100 BYQ TENAOHEL EQ, GNEENAG PBHAGL p/f: SYBLQ UNZCGBA EQ Obk: 116K. . 17:30:33",
        "PNYY:TENFF SVER, Fvatyr Fgngvba",
        "VASB:ERCBEGRQ FZNYY TENFF SVER",
        "NQQE:12100 BYQ TENAOHEL EQ",
        "PVGL:GNEENAG PBHAGL",
        "K:SYBLQ UNZCGBA EQ",
        "OBK:116K",
        "GVZR:17:30:33");

    qbGrfg("G6",
        "GENHZN, TEBHAQ YIY SNYY: 80 LB/Z SNYY. UVC CNVA. P/O ng 300 A BYQ QRPNGHE EQ, FNTVANJ p/f: J ZPYREBL OYIQ Obk: 33K B: SVEFG ONCGVFG PUHEPU. . 10:52:00",
        "PNYY:GENHZN, TEBHAQ YIY SNYY",
        "VASB:80 LB/Z SNYY. UVC CNVA. P/O",
        "NQQE:300 A BYQ QRPNGHE EQ",
        "PVGL:FNTVANJ",
        "K:J ZPYREBL OYIQ",
        "OBK:33K",
        "CYNPR:SVEFG ONCGVFG PUHEPU",
        "GVZR:10:52:00");

    qbGrfg("G7",
        "ZRQVPNY, ZRQVPNY NYNEZ: AB NAFJRE BA PNYY ONPX ng 5913 RQ PBNQL EQ, RQTRPYVSS IVYYNTR p/f: FLPNZBER PERRX EQ Obk: 90M. . 03:02:46",
        "PNYY:ZRQVPNY, ZRQVPNY NYNEZ",
        "VASB:AB NAFJRE BA PNYY ONPX",
        "NQQE:5913 RQ PBNQL EQ",
        "PVGL:RQTRPYVSS IVYYNTR",
        "K:FLPNZBER PERRX EQ",
        "OBK:90M",
        "GVZR:03:02:46");

  }
  
  @Grfg
  choyvp ibvq grfgRqtrpyvssIvyyntrSverQrcg() {

    qbGrfg("G1",
        "GENHZN, URNQ VAWHEL: UVG VA SNPR JVGU ZRGNY ORQSENZR   Pbafpvbhf:  Oernguvat \a" +
        "  ng 2100 NYGNZRFN OYIQ, RQTRPYVSS IVYYNTR  p/f: PEBJYRL EQ Obk: 104O   B: TBBQJVYY VAQHFGEVRF VAP . . 09:29:30",

        "PNYY:GENHZN, URNQ VAWHEL",
        "VASB:UVG VA SNPR JVGU ZRGNY ORQSENZR Pbafpvbhf: Oernguvat",
        "NQQE:2100 NYGNZRFN OYIQ",
        "PVGL:RQTRPYVSS IVYYNTR",
        "OBK:104O",
        "K:PEBJYRL EQ",
        "CYNPR:TBBQJVYY VAQHFGEVRF VAP",
        "GVZR:09:29:30");

    qbGrfg("G2",
        "ZRQVPNY, FVPX CREFBA: 45 L/B ZNYR   Pbafpvbhf:  Oernguvat \a" +
        "  ng 8 GNYYJBBQ YA, RQTRPYVSS IVYYNTR  p/f: PUREELEVQTR QE Obk: 90M . . 14:37:41",

        "PNYY:ZRQVPNY, FVPX CREFBA",
        "VASB:45 L/B ZNYR Pbafpvbhf: Oernguvat",
        "NQQE:8 GNYYJBBQ YA",
        "PVGL:RQTRPYVSS IVYYNTR",
        "OBK:90M",
        "K:PUREELEVQTR QE",
        "GVZR:14:37:41");

    qbGrfg("G3",
        "GENHZN, NEZ / YRT SENPGHER: 85 LBS PBAPVBHF NAQ OERNGUVAT   Pbafpvbhf:  Oernguvat \a" +
        "  ng 1628 YNZCYVTUGRE YA, RQTRPYVSS IVYYNTR  p/f: JVAA QE Obk: 104P . . 10:04:24",

        "PNYY:GENHZN, NEZ / YRT SENPGHER",
        "VASB:85 LBS PBAPVBHF NAQ OERNGUVAT Pbafpvbhf: Oernguvat",
        "NQQE:1628 YNZCYVTUGRE YA",
        "PVGL:RQTRPYVSS IVYYNTR",
        "OBK:104P",
        "K:JVAA QE",
        "GVZR:10:04:24");

    qbGrfg("G4",
        "ZRQVPNY, Pneqvnp Ceboyrz ng 2017 ZVAT QE, RQTRPYVSS IVYYNTR  p/f: PEBJYRL EQ Obk: 90L . . 07:01:58",
        "PNYY:ZRQVPNY, Pneqvnp Ceboyrz",
        "NQQE:2017 ZVAT QE",
        "PVGL:RQTRPYVSS IVYYNTR",
        "OBK:90L",
        "K:PEBJYRL EQ",
        "GVZR:07:01:58");

    qbGrfg("G5",
        "ZRQVPNY, NOQBZVANY CNVA ng 1201 LBEX QE, RQTRPYVSS IVYYNTR  p/f: ZRERQVGU YA Obk: 90M . . 03:42:54",
        "PNYY:ZRQVPNY, NOQBZVANY CNVA",
        "NQQE:1201 LBEX QE",
        "PVGL:RQTRPYVSS IVYYNTR",
        "OBK:90M",
        "K:ZRERQVGU YA",
        "GVZR:03:42:54");

    qbGrfg("G6",
        "ZRQVPNY, ZRQVPNY NYNEZ ng 1412 YVZRFGBAR GEY, RQTRPYVSS IVYYNTR  p/f: PNZRYBG EQ Obk: 104P . . 20:25:00",
        "PNYY:ZRQVPNY, ZRQVPNY NYNEZ",
        "NQQE:1412 YVZRFGBAR GEY",
        "PVGL:RQTRPYVSS IVYYNTR",
        "OBK:104P",
        "K:PNZRYBG EQ",
        "GVZR:20:25:00");

    qbGrfg("G7",
        "TENFF / OEHFU SVER, YRFF GUNA 1 NPER ng 685 WBUA O FVNF ZRZBEVNY CXJL, RQTRPYVSS IVYYNTR  p/f: URZCUVYY FG Obk: 91F   B: SBEG JBEGU FGNE-GRYRTENZ QVFGEVOHGVBA PRAGRE . . 19:24:21",
        "PNYY:TENFF / OEHFU SVER, YRFF GUNA 1 NPER",
        "NQQE:685 WBUA O FVNF ZRZBEVNY CXJL",
        "PVGL:RQTRPYVSS IVYYNTR",
        "OBK:91F",
        "K:URZCUVYY FG",
        "CYNPR:SBEG JBEGU FGNE-GRYRTENZ QVFGEVOHGVBA PRAGRE",
        "GVZR:19:24:21");

    qbGrfg("G8",
        "ZRQVPNY, Oernguvat Ceboyrz ng 1313 LBEX QE, RQTRPYVSS IVYYNTR  p/f: FLPNZBER QE Obk: 90M . . 22:16:46",
        "PNYY:ZRQVPNY, Oernguvat Ceboyrz",
        "NQQE:1313 LBEX QE",
        "PVGL:RQTRPYVSS IVYYNTR",
        "OBK:90M",
        "K:FLPNZBER QE",
        "GVZR:22:16:46");

    qbGrfg("G9",
        "NTRAPL NFFVFG, FGNGVBA PBIRENTR ng 400 J RABA NIR, RIREZNA  p/f: F UNAFONETRE Obk: 106W   B: RIREZNA SVER QRCNEGZRAG . . 09:22:54",
        "PNYY:NTRAPL NFFVFG, FGNGVBA PBIRENTR",
        "NQQE:400 J RABA NIR",
        "PVGL:RIREZNA",
        "OBK:106W",
        "K:F UNAFONETRE",
        "CYNPR:RIREZNA SVER QRCNEGZRAG",
        "GVZR:09:22:54");

    qbGrfg("G10",
        "FGEHPGHER SVER, Fvatyr Snzvyl ng 304 GUBZNF CY, RIREZNA  p/f: QRNQ RAQ Obk: 106C . . 06:07:45",
        "PNYY:FGEHPGHER SVER, Fvatyr Snzvyl",
        "NQQE:304 GUBZNF CY",
        "PVGL:RIREZNA",
        "OBK:106C",
        "K:QRNQ RAQ",
        "GVZR:06:07:45");

    qbGrfg("G11",
        "UNMZNG, Cvcryvar Ehcgher: TNF YVAR PHG VA GUR ONPX LNEQ ng 3 LBEX QE, RQTRPYVSS IVYYNTR  p/f: PEBJYRL EQ Obk: 90L . . 12:03:49",
        "PNYY:UNMZNG, Cvcryvar Ehcgher",
        "VASB:TNF YVAR PHG VA GUR ONPX LNEQ",
        "NQQE:3 LBEX QE",
        "PVGL:RQTRPYVSS IVYYNTR",
        "OBK:90L",
        "K:PEBJYRL EQ",
        "GVZR:12:03:49");

    qbGrfg("G12",
        "NYNEZ - Erfvqragvny, Fzbxr Qrgrpgbe: NYNEZ CNARY ng 24 PURYFRN QE, RQTRPYVSS IVYYNTR  p/f: OERAGBA EQ Obk: 90L . . 08:08:56",
        "PNYY:NYNEZ - Erfvqragvny, Fzbxr Qrgrpgbe",
        "VASB:NYNEZ CNARY",
        "NQQE:24 PURYFRN QE",
        "PVGL:RQTRPYVSS IVYYNTR",
        "OBK:90L",
        "K:OERAGBA EQ",
        "GVZR:08:08:56");

    qbGrfg("G13",
        "ZRQVPNY, FRVMHERF / PBAIHYFVBAF ng 11 GNYYJBBQ YA, RQTRPYVSS IVYYNTR  p/f: PUREELEVQTR QE Obk: 90M . . 17:22:03",
        "PNYY:ZRQVPNY, FRVMHERF / PBAIHYFVBAF",
        "NQQE:11 GNYYJBBQ YA",
        "PVGL:RQTRPYVSS IVYYNTR",
        "OBK:90M",
        "K:PUREELEVQTR QE",
        "GVZR:17:22:03");

    qbGrfg("G14",
        "VAIRFG, Haxabja Glcr Sver: OBK BA SVER VA GUR EBNQ JNL ng 6017 FLPNZBER PERRX EQ, RQTRPYVSS IVYYNTR  p/f: PYVSS PG Obk: 90M . . 03:30:28",
        "PNYY:VAIRFG, Haxabja Glcr Sver",
        "VASB:OBK BA SVER VA GUR EBNQ JNL",
        "NQQE:6017 FLPNZBER PERRX EQ",
        "PVGL:RQTRPYVSS IVYYNTR",
        "OBK:90M",
        "K:PYVSS PG",
        "GVZR:03:30:28");

    qbGrfg("G15",
        "ZRQVPNY, URZBEEUNTR / OYRRQ: 20 L/B ZNYR; ERPGNY OYRRQVAT ng 4913 BUVB TNEQRA EQ, EVIRE BNXF  p/f: XRVGU CHZCURERL QE Obk: 61C   B: OENHZF . . 14:28:39",
        "PNYY:ZRQVPNY, URZBEEUNTR / OYRRQ",
        "VASB:20 L/B ZNYR; ERPGNY OYRRQVAT",
        "NQQE:4913 BUVB TNEQRA EQ",
        "PVGL:EVIRE BNXF",
        "OBK:61C",
        "K:XRVGU CHZCURERL QE",
        "CYNPR:OENHZF",
        "GVZR:14:28:39");

    qbGrfg("G16",
        "ZRQVPNY, HAERFCBAFVIR CREFBA: 28 L/B SRZNYR, ABG OERNGUVAT TBBQ ng 2008 PYVSSFVQR QE, RQTRPYVSS IVYYNTR  p/f: PEBJYRL EQ Obk: 90L . . 13:03:12",
        "PNYY:ZRQVPNY, HAERFCBAFVIR CREFBA",
        "VASB:28 L/B SRZNYR, ABG OERNGUVAT TBBQ",
        "NQQE:2008 PYVSSFVQR QE",
        "PVGL:RQTRPYVSS IVYYNTR",
        "OBK:90L",
        "K:PEBJYRL EQ",
        "GVZR:13:03:12");

    qbGrfg("G17",
        "GENHZN, YNPRENGVBA: 4 L/B ZNYR PNB YBPNGRQ VA GUR SEBAG CNGEXVAT YBG ng 4900 EVIRE BNXF OYIQ, EVIRE BNXF  p/f: TYRAJVPX QE Obk: 61X   B: EVIRE BNXF ZHAVPVCNY PBZCYRK . . 12:40:10",
        "PNYY:GENHZN, YNPRENGVBA",
        "VASB:4 L/B ZNYR PNB YBPNGRQ VA GUR SEBAG CNGEXVAT YBG",
        "NQQE:4900 EVIRE BNXF OYIQ",
        "PVGL:EVIRE BNXF",
        "OBK:61X",
        "K:TYRAJVPX QE",
        "CYNPR:EVIRE BNXF ZHAVPVCNY PBZCYRK",
        "GVZR:12:40:10");

    qbGrfg("G18",
        "NTRAPL NFFVFG, FGNGVBA PBIRENTR ng 4900 EVIRE BNXF OYIQ, EVIRE BNXF  p/f: TYRAJVPX QE Obk: 61X   B: EVIRE BNXF ZHAVPVCNY PBZCYRK . . 06:32:42",
        "PNYY:NTRAPL NFFVFG, FGNGVBA PBIRENTR",
        "NQQE:4900 EVIRE BNXF OYIQ",
        "PVGL:EVIRE BNXF",
        "OBK:61X",
        "K:TYRAJVPX QE",
        "CYNPR:EVIRE BNXF ZHAVPVCNY PBZCYRK",
        "GVZR:06:32:42");

    qbGrfg("G19",
        "ZRQVPNY, FRVMHERF / PBAIHYFVBAF: AB CNGVRAG VASB ng 2 PURYFRN QE, RQTRPYVSS IVYYNTR  p/f: PEBJYRL EQ Obk: 90L . . 14:17:19",
        "PNYY:ZRQVPNY, FRVMHERF / PBAIHYFVBAF",
        "VASB:AB CNGVRAG VASB",
        "NQQE:2 PURYFRN QE",
        "PVGL:RQTRPYVSS IVYYNTR",
        "OBK:90L",
        "K:PEBJYRL EQ",
        "GVZR:14:17:19");

    qbGrfg("G20",
        "ZRQVPNY, Oernguvat Ceboyrz: 71 LBZ ng 2 PURYFRN QE, RQTRPYVSS IVYYNTR  p/f: PEBJYRL EQ Obk: 90L . . 12:53:55",
        "PNYY:ZRQVPNY, Oernguvat Ceboyrz",
        "VASB:71 LBZ",
        "NQQE:2 PURYFRN QE",
        "PVGL:RQTRPYVSS IVYYNTR",
        "OBK:90L",
        "K:PEBJYRL EQ",
        "GVZR:12:53:55");

    qbGrfg("G21",
        "FGEHPGHER SVER, Fvatyr Snzvyl: SVER EBBS ng 1904 EBPXZBBE QE, RQTRPYVSS IVYYNTR  p/f: YHANE QE Obk: 90L . . 18:29:10",
        "PNYY:FGEHPGHER SVER, Fvatyr Snzvyl",
        "VASB:SVER EBBS",
        "NQQE:1904 EBPXZBBE QE",
        "PVGL:RQTRPYVSS IVYYNTR",
        "OBK:90L",
        "K:YHANE QE",
        "GVZR:18:29:10");

    qbGrfg("G22",
        "ZRQVPNY, PUBXVAT: 90 LBN SRZNYR PBAF OERNGUVAT  ng 2 PURYFRN QE, RQTRPYVSS IVYYNTR  p/f: PEBJYRL EQ Obk: 90L . . 01:15:05",
        "PNYY:ZRQVPNY, PUBXVAT",
        "VASB:90 LBN SRZNYR PBAF OERNGUVAT",
        "NQQE:2 PURYFRN QE",
        "PVGL:RQTRPYVSS IVYYNTR",
        "OBK:90L",
        "K:PEBJYRL EQ",
        "GVZR:01:15:05");

    qbGrfg("G23",
        "Z I N, Pne / Cvpx-hc: 2 IRUVPYRF. P35 BA FPRAR ng 6600 PEBJYRL EQ, RQTRPYVSS IVYYNTR  p/f: YVZRFGBAR GEY Obk: 104P . . 18:16:37",
        "PNYY:Z I N, Pne / Cvpx-hc",
        "VASB:2 IRUVPYRF. P35 BA FPRAR",
        "NQQE:6600 PEBJYRL EQ",
        "PVGL:RQTRPYVSS IVYYNTR",
        "OBK:104P",
        "K:YVZRFGBAR GEY",
        "GVZR:18:16:37");

    qbGrfg("G24",
        "ZRQVPNY, FVPX CREFBA: 80 L/B SRZNYR PBAFPVBHF NAQ OERNGUVAT ng 2021 ZVAT QE, RQTRPYVSS IVYYNTR  p/f: PEBJYRL EQ Obk: 90L . . 10:23:30",
        "PNYY:ZRQVPNY, FVPX CREFBA",
        "VASB:80 L/B SRZNYR PBAFPVBHF NAQ OERNGUVAT",
        "NQQE:2021 ZVAT QE",
        "PVGL:RQTRPYVSS IVYYNTR",
        "OBK:90L",
        "K:PEBJYRL EQ",
        "GVZR:10:23:30");

    qbGrfg("G25",
        "ERFPHR, Puvyq Ybpxrq va Iruvpyr: vasnag ng 15 GNYYJBBQ YA, RQTRPYVSS IVYYNTR  p/f: PUREELEVQTR QE Obk: 90M . . 12:21:34",
        "PNYY:ERFPHR, Puvyq Ybpxrq va Iruvpyr",
        "VASB:vasnag",
        "NQQE:15 GNYYJBBQ YA",
        "PVGL:RQTRPYVSS IVYYNTR",
        "OBK:90M",
        "K:PUREELEVQTR QE",
        "GVZR:12:21:34");

    qbGrfg("G26",
        "ZRQVPNY, FRVMHERF / PBAIHYFVBAF: 47 LBN ZNYR  ng 2 PURYFRN QE, RQTRPYVSS IVYYNTR  p/f: PEBJYRL EQ Obk: 90L . . 16:16:35",
        "PNYY:ZRQVPNY, FRVMHERF / PBAIHYFVBAF",
        "VASB:47 LBN ZNYR",
        "NQQE:2 PURYFRN QE",
        "PVGL:RQTRPYVSS IVYYNTR",
        "OBK:90L",
        "K:PEBJYRL EQ",
        "GVZR:16:16:35");

    qbGrfg("G27",
        "ZRQVPNY, FRVMHERF / PBAIHYFVBAF: 33 L/B ZNYR ng 2121 GVCCL GRE, RQTRPYVSS IVYYNTR  p/f: SNZVYL CY Obk: 90L . . 05:32:06",
        "PNYY:ZRQVPNY, FRVMHERF / PBAIHYFVBAF",
        "VASB:33 L/B ZNYR",
        "NQQE:2121 GVCCL GRE",
        "PVGL:RQTRPYVSS IVYYNTR",
        "OBK:90L",
        "K:SNZVYL CY",
        "GVZR:05:32:06");

    qbGrfg("G28",
        "ZRQVPNY: haxabja ntr srznyr qvffbevragrq ng 3 PURYFRN QE, RQTRPYVSS IVYYNTR  p/f: PEBJYRL EQ Obk: 90L . . 17:23:50",
        "PNYY:ZRQVPNY",
        "VASB:haxabja ntr srznyr qvffbevragrq",
        "NQQE:3 PURYFRN QE",
        "PVGL:RQTRPYVSS IVYYNTR",
        "OBK:90L",
        "K:PEBJYRL EQ",
        "GVZR:17:23:50");

    qbGrfg("G29",
        "CHOYVP NFFVFG, Yvsg Uryc ng 34 PURYFRN QE, RQTRPYVSS IVYYNTR  p/f: OERAGBA EQ Obk: 90L . . 13:27:20",
        "PNYY:CHOYVP NFFVFG, Yvsg Uryc",
        "NQQE:34 PURYFRN QE",
        "PVGL:RQTRPYVSS IVYYNTR",
        "OBK:90L",
        "K:OERAGBA EQ",
        "GVZR:13:27:20");

    qbGrfg("G30",
        "ZRQVPNY, QVNORGVP CEBOYRZ: 60 L/B ZNYR PBAFPVBHF NAQ OERNGUVAT ng 2012 THZZ EQ, RQTRPYVSS IVYYNTR  p/f: SNZVYL CY Obk: 104O . . 19:22:01",
        "PNYY:ZRQVPNY, QVNORGVP CEBOYRZ",
        "VASB:60 L/B ZNYR PBAFPVBHF NAQ OERNGUVAT",
        "NQQE:2012 THZZ EQ",
        "PVGL:RQTRPYVSS IVYYNTR",
        "OBK:104O",
        "K:SNZVYL CY",
        "GVZR:19:22:01");

  }
  
  choyvp fgngvp ibvq znva(Fgevat[] netf) {
    arj GKGneenagPbhaglCnefreGrfg().trarengrGrfgf("G1");
  }
}