package net.anei.cadpage.parsers.VA;

import net.anei.cadpage.parsers.BaseParserTest;

import org.junit.Test;

/*
Wight County, VA
Contact: "G.B. Wills III" <gbwillsiii@gmail.com>
Sender: CAD@isleofwightUS.net

11365 CENTRAL HILL RD;S CAROLINA AVE;COURTHOUSE HWY;FIRE ALARM;smoke detector zone 16 res last name babb 757-353-0490 [06/20/11 19:01:18 MPMARSH] 
YELLOW HAMMER RD/FIRE TOWER RD;1050;[LAW] {37} ONE FINGER AND JAW/ SEC CONCUSION [06/22/11 04:02:28 SHILL] {37} HAVE INJURIES [06/22/11 04:02:04 SHILL] VSP AD: 
23352 COURTHOUSE HWY;CONSULATE HEALTH CARE WINDSOR;KENSINGTON CT;JOYNER TOWN LN;FIRE ALARM;[LAW] WILL TRY TO CONTACT KEYHOLDER [06/22/11 12:20:01 MDUNN] zone
77 CASTLE ST;LIBERTY AVE;BELLMONT ST;FIRE OTHER NOT LISTED;microwave hot and not in use [06/23/11 09:59:22 JTEMPLETON].   
W WINDSOR BLVD/N PRINCE BLVD;ACCIDENT WITH INJURIES;supreme prking lot. 2 veh. chryslter pt cruiser vs dodge ram piick up [06/23/11 13:13:34 JTEMPLETON]

Contact: Larry Regula <fshook03@gmail.com>
Sender: CAD@isleofwightus.net
CAD:1207 CARRSVILLE HWY;6D;SPRINGDALE APARTMENTS;FALLS AND RELATED INJURIES;JAMESTOWN LN;LEES MILL RD;99 yo female--has fallen, home nurse is unable to gain a

Contact: carolyn seeds <cjseeds@gmail.com>
Sender: cad@isleofwightus.net
7466 MAPLE HALL LN;FALLS AND RELATED INJURIES;BEALE PLACE DR;58 yr male fall and is disoriented - fell on 10 m\n

Contact: Active911
Agency name: Isle of Wight Volunteer Rescue Squad
Location: Isle of Wight, VA, United States
Sender: cad@isleofwightus.net

(Message Forwarded by PageGate) 301 WATSON DR;ACCIDENT UNKNOWN INJURIES;MOONEFIELD DR;AZALEA DR;VEHICLE IN THE RAVINE AT THIS LOCATION\nUNKN FURTHER  [12/29/12 20:15:17 KROBERTS]
(Message Forwarded by PageGate) FYI: ;301 WATSON DR;ACCIDENT UNKNOWN INJURIES;MOONEFIELD DR;AZALEA DR;VEHICLE IN THE RAVINE AT THIS LOCATION\nUNKN FURTHER  [12/29/12 20:15:17 KROBERTS]
(Message Forwarded by PageGate) 735 WRENN RD;APT C;SICK / ILL / PUBLIC ASSIST;W MAIN ST;1 YO MALE\nCONS/BREA  [12/29/12 17:50:43 KROBERTS]
(Message Forwarded by PageGate) FYI: ;23179 CATFISH ST;LOT 85;UNCONSCIOUS OR FAINTING;TWIN PONDS DR;BEALE DR;35 YO FEMALE\nBREA\nUNCON IN THE BATHROOM  [12/29/12 17:13:27 KROBERTS]
(Message Forwarded by PageGate) 200 LUMAR RD;ROOM 44;RIVERSIDE CONVALESCENT CENTER;SICK / ILL / PUBLIC ASSIST;MOONEFIELD DR;slow response  [12/29/12 10:50:15 BPRESSON]\n84 yo m, low blood pressure, dipharetic  [12/29/12 10:50:09 BPRESSON]
(Message Forwarded by PageGate) 6504 MILL SWAMP RD;UNCONSCIOUS OR FAINTING;WHITE HILL TRL;GREEN LEVEL RD;TURNING PURPLE  [12/29/12 10:31:13 BHUGHES]\n81 YEAR OLD FEMALE COLLAPSED IN FLOOR. CALLER STATES THAT SHE HAS TAKEN A BREATH  [12/29/12 10:31:02 BHUGHES]
(Message Forwarded by PageGate) FYI: ;6504 MILL SWAMP RD;UNCONSCIOUS OR FAINTING;WHITE HILL TRL;GREEN LEVEL RD
(Message Forwarded by PageGate) 207 MONTICELLO CT;DIST: 1010.14 FT;PAIN;BERKELEY ST;70 YEAR OLD FEMALE WHO IS COMP OF RECTUM PAIN, PT IS IN WHEEL CHAIR  [12/29/12 10:16:48 BHUGHES]
(Message Forwarded by PageGate) 305 CANTEBERRY LN;STRUCTURE FIRE;HUNTINGTON WY;BUCKINGHAM WY;ELECTRICAL FIRE  [12/29/12 08:56:27 BHUGHES]
(Message Forwarded by PageGate) FYI: ;305 CANTEBERRY LN;STRUCTURE FIRE;HUNTINGTON WY;BUCKINGHAM WY;ELECTRICAL FIRE  [12/29/12 08:56:27 BHUGHES]
(Message Forwarded by PageGate) 5140 JAMES WY;PAIN;44 Y/O M IN PAIN  [12/29/12 06:48:08 CHEDGEPETH]
(Message Forwarded by PageGate) 18155 BOB WHITE RD;DIST: 1294.00 FT;DIFFICULTY BREATHING;BOWLING GREEN RD;RESTLESS HEART RD;42 Y/O F DIFF BREATHING CHEST PAINS  [12/29/12 06:42:12 CHEDGEPETH]
(Message Forwarded by PageGate) 104 CROATAN CT;STRUCTURE FIRE;JOHN ROLFE DR
(Message Forwarded by PageGate) FYI: ;104 CROATAN CT;STRUCTURE FIRE;JOHN ROLFE DR
(Message Forwarded by PageGate) 513 CEDAR ST;B2;DIFFICULTY BREATHING;UNDERWOOD LN;COVENANT PL;CHEIF DEIFFICULTY BREATHING  TIGHT CHEST ...... IN THE BACKGROUND CAN HEAR HER CRYING  [12/28/12 21:06:57 CGONZALEZ]
(Message Forwarded by PageGate) 735 WRENN RD;APT C;SICK OR ILL OTHER RESCUE;W MAIN ST;18 MNT OLD FEVER IS 102.3  AND SHAKING  [12/28/12 19:49:15 CGONZALEZ]
(Message Forwarded by PageGate) 1804 S CHURCH ST;SMITHFIELD VOL FIRE DEPT (NEW);DIFFICULTY BREATHING;SMITHFIELD BLVD;MOORE AVE
(Message Forwarded by PageGate) Update: ;24236 KNOXVILLE RD;OVERDOSE;WILLIE ROBERTS RD;she is responsive at this time  ....... has been going on for 3-4 hrs  [12/28/12 16:19:07 CGONZALEZ]\nhx of overdosing and eplicitic  [12/28/12 16:18:22 CGONZALEZ]\nabrams  f  48 y/o   possible 10 96  [12/28/12 16:18:01 CGONZALEZ]\ncaller states his mother has a headache weak dizzyness , and not very responsive  [12/28/12 16:16:31 CGONZALEZ]
(Message Forwarded by PageGate) 107 COCKES LN;ABDOMINAL PAIN;MAIN ST;CEDAR ST;54 y/o female etopic pregnancy having severe abdominal pain  [12/28/12 11:09:03 KBAKER]
(Message Forwarded by PageGate) 101 JOHN ROLFE DR;RM 125;MAGNOLIA MANOR;CHEST PAIN OR HEART ATTACK;BREANN CT;ANDREWS XING;87 y/o female with chest pain and shortness of breath  [12/28/12 08:25:15 KBAKER]
(Message Forwarded by PageGate) 11259 CINDALE DR;DIFFICULTY BREATHING;BETHEL CHURCH LN;BLAIRS CREEK DR;58 YEAR OLD DIFFICULTY BREATHING HX: DIABETES COPD SOCADOCSIS . CONSCIOUS ALERT  [12/28/12 07:13:53 BHUGHES]
(Message Forwarded by PageGate) 126 HOLLOWAY DR;LIFT ASSIST;OLIVER DR;81 yr old female slid off the bed. she is fine just need lift assist.  [12/28/12 00:59:18 SHILL]
(Message Forwarded by PageGate) 505 VIRGINIA AVE;FALLS AND RELATED INJURIES;PAGAN RD;LAWNE ST;85 YEARS OLD FELL BATHROOM HIT HER HEAD.  [12/27/12 20:12:31 MZERICK]
(Message Forwarded by PageGate) FYI: ;21475 WIGWAM CIR;UNCONSCIOUS OR FAINTING;AUCKLAND CT;40 YEARS OLD MALE  PASSED OUT  IN THE HOUSE.  HE IS BREATHING.  [12/27/12 18:21:30 MZERICK]
(Message Forwarded by PageGate) Update: ;903 GATLING POINTE PKWY;GATLING POINTE YACHT CLUB;UNNAMED;JAMES LANDING CIR;ASSIST BOATER;Event spawned for SFD Event ID:201281644  [12/27/12 17:40:38 MZERICK]\nEvent spawned from SUSPICIOUS PERS./VEH./ACTIVITY.  [12/27/2012 17:38:41 CGONZALEZ]\ncoast guard has made contact with the subject who shot off the flare and is working the situation\nwill call back if they need assistance  [12/27/12 17:32:03 KROBERTS]\ncontacting coast guard to see if they have recieved any reports  [12/27/12 17:29
(Message Forwarded by PageGate) 751-A WRENN RD;DIST: 138.71 FT;SICK OR ILL OTHER RESCUE;W MAIN ST;7 month old with congestion  [12/27/12 11:58:04 KBAKER]
(Message Forwarded by PageGate) 20212 OLDE TOWNE CT;DIST: 416.13 FT;POSSIBLE DOA OR FULL ARREST;OLDE TOWNE PL;OLDE TOWNE PL;FEMALE DENIES TRYING CPR STATES HE IS GONE  [12/27/12 07:15:17 KBAKER]\n58 MALE COLD TO TOUCH NOT BREATHING  [12/27/12 07:14:27 KBAKER]
(Message Forwarded by PageGate) FYI: ;20212 OLDE TOWNE CT;DIST: 416.13 FT;POSSIBLE DOA OR FULL ARREST;OLDE TOWNE PL;OLDE TOWNE PL;58 MALE COLD TO TOUCH NOT BREATHING  [12/27/12 07:14:27 KBAKER]
(Message Forwarded by PageGate) 114 TALBOT DR;SICK OR ILL OTHER RESCUE;WILSON RD;MAGRUDER RD;90 Y/O DIAB THROWING UP AND UNABLE WALK  [12/27/12 05:43:48 SDALTON]
(Message Forwarded by PageGate) 3407 LONGWOOD DR;STROKE;PINE CIR;POSSIBLE STROKE, 64 YR OLD MALE. 93/58 BP. BLOOD SUGAR 315  [12/26/12 21:10:20 DJONES]
(Message Forwarded by PageGate) FYI: ;OLD MYRTLE RD/FREEMAN DR;DIST: 589.55 FT;ACCIDENT WITH INJURIES;she daughter has flipped her veh ---  [12/26/12 20:21:53 KHEWITT]\nshe is on old myrtle near  [12/26/12 20:20:46 KHEWITT]
(Message Forwarded by PageGate) 101 JOHN ROLFE DR;RM 112;MAGNOLIA MANOR;SICK OR ILL OTHER RESCUE;BREANN CT;ANDREWS XING;96-F ---- change in mental status and elavated bp  [12/26/12 19:39:38 KHEWITT]
(Message Forwarded by PageGate) 16030 CARROLL BRIDGE RD;DIST: 56.69 FT;FALLS AND RELATED INJURIES;WEBB LN;BOWLING GREEN RD;78-m --- fall from standing position --- poss broken hip ---  [12/26/12 17:45:18 KHEWITT]
(Message Forwarded by PageGate) 107 COCKES LN;DIST: 311.49 FT;ABDOMINAL PAIN;MAIN ST;CEDAR ST;54-F --- severe abdominal pains -- hx of diabetes and high blood pressure  [12/26/12 17:01:43 KHEWITT]
(Message Forwarded by PageGate) 16566 BOWLING GREEN RD;LIFT ASSIST;CARROLL BRIDGE RD;FULGHAM LN;NEEDS ASSISTANCE LIFTING HER MOTHER. SHE IS 80 YO. SHE FELL WHILE TRYING TO GET IN HER SEAT  [12/26/12 11:58:38 AGOODWYN]
(Message Forwarded by PageGate) 1941 S CHURCH ST;FOOD LION;ACCIDENT UNKNOWN INJURIES;MOORE AVE;ROUTE 10 BYPASS;[FIRE] 2ND CALL BLEEDING FROM THE NOSE OR MOUTH AND HAND  [12/26/12 11:00:23 AGOODWYN]\nLEFT FOOD LION IN WRONG LANE AND HIT A TREE  [12/26/12 11:00:24 BKING]\nSOMEONE  [12/26/12 10:59:58 BKING]
(Message Forwarded by PageGate) FYI: ;1941 S CHURCH ST;FOOD LION;ACCIDENT UNKNOWN INJURIES;MOORE AVE;ROUTE 10 BYPASS;LEFT FOOD LION IN WRONG LANE AND HIT A TREE  [12/26/12 11:00:24 BKING]\nSOMEONE  [12/26/12 10:59:58 BKING]
(Message Forwarded by PageGate) 601 CEDAR ST;APT 501;COVENANT PLACE;SICK OR ILL OTHER RESCUE;ACACIA CIR;UNDERWOOD LN;70 years old female  doesnt feel good.  [12/26/12 10:48:22 MZERICK]\nThis address [601 CEDAR ST] is currently missing from the map centerline and was verified using tabular street records.  [12/26/12 10:47:38 MZERICK]
(Message Forwarded by PageGate) 12593 NIKE PARK RD;STRUCTURE FIRE;PALEO POINT LN;WATERVIEW TRL;CALLER STATES HER STOVE IS ON FIRE.  [12/26/12 07:39:04 AGOODWYN]
(Message Forwarded by PageGate) FYI: ;12593 NIKE PARK RD;STRUCTURE FIRE;PALEO POINT LN;WATERVIEW TRL;CALLER STATES HER STOVE IS ON FIRE.  [12/26/12 07:39:04 AGOODWYN]
(Message Forwarded by PageGate) 315 EAST ST;SICK OR ILL OTHER RESCUE;W VIRGINIA AVE;27 YO F FEELS LIKE SHE MIGHT PASS OUT. HAS NOT BEEN SICK  [12/26/12 06:21:39 JESSICAB]
(Message Forwarded by PageGate) 313 GRANDVILLE ARCH;BACK PAIN OR INJURY;SOUTHAMPTON CT;QUEEN CT;FEMALE  [12/26/12 04:53:57 SHILL]\nback pain, cant move, 71 yrs old.  [12/26/12 04:53:30 SHILL]
(Message Forwarded by PageGate) 646 WESTMINSTER RCH;DIFFICULTY BREATHING;GRANDVILLE ARCH;BRISTOL ST;8 yr old male asthmatic, having a hard time breathing. just woke up.  [12/26/12 03:42:38 SHILL]
(Message Forwarded by PageGate) 24 RIVERSIDE DR;FRACTURES OR BROKEN BONES;WILDERNESS LN;WATERVIEW CIR;77 yr old male fallen possible broken right arm.  [12/26/12 00:33:57 SHILL]
(Message Forwarded by PageGate) 646 WESTMINSTER RCH;DIST: 1010.14 FT;DIFFICULTY BREATHING;GRANDVILLE ARCH;BRISTOL ST;8 M  [12/25/12 22:29:51 ADEBARGE]\n8 ASTHMA ATTACK  [12/25/12 22:29:42 ADEBARGE]
(Message Forwarded by PageGate) 14065 BLACK OAK DR;LIFT ASSIST;LAUREL OAK DR;WATER OAK DR;68 F  FELL OUT OF WALKER AND NEEDS HELP GETTING UP ON THE FRONT PORCH  [12/25/12 21:15:26 ADEBARGE]
(Message Forwarded by PageGate) FYI: ;7651 WHISPERING PINES TRL;BIG BEAR CAMPGROUND;POSSIBLE DOA OR FULL ARREST;BEALE PLACE DR;CENTRAL HILL RD;22 YEARS OLD MALE  COLD TO THE TOUCH.  [12/25/12 18:40:03 MZERICK]
(Message Forwarded by PageGate) 105 LANE CRES;CHEST PAIN OR HEART ATTACK;KENDALL HVN;believes to be having another heart attack  [12/25/12 14:47:49 ADEBARGE]\n46 m  [12/25/12 14:47:37 ADEBARGE]
(Message Forwarded by PageGate) Update: ;9141 WINDSOR BLVD;ACCIDENT UNKNOWN INJURIES;STAVE MILL RD;[FIRE] 717 to station  [12/25/12 13:01:12 KHEWITT]\n[FIRE] 408 responding  [12/25/12 13:00:53 KHEWITT]\n[LAW] BETWEEN WINDSOR AND ZUNI  [12/25/12 12:58:53 AGOODWYN]\n[LAW] FLIPPED - MAN IS OUT  [12/25/12 12:59:29 JEDMONDS]\n[LAW] CAR IS OVERTURNED. WHITE IS THE ONLY DESCRIPTION SHE CAN GIVE.  [12/25/12 12:57:57 AGOODWYN]
(Message Forwarded by PageGate) FYI: ;WINDSOR BLVD/YELLOW HAMMER RD;ACCIDENT UNKNOWN INJURIES
(Message Forwarded by PageGate) FYI: ;WINDSOR BLVD/YELLOW HAMMER RD;ACCIDENT UNKNOWN INJURIES
(Message Forwarded by PageGate) 312 WEST ST;CHEST PAIN OR HEART ATTACK;W VIRGINIA AVE;55 YO MALE. IS HAVING A SEIZURE OR HEART ATTACK  [12/25/12 08:36:00 AGOODWYN]
(Message Forwarded by PageGate) 20711 CREEKSIDE DR;CHEST PAIN OR HEART ATTACK;GATLING POINTE PKWY S;RIVERS BEND PL;77 yo m having chest pains. no diff breathing. is conc and breathing. history of a-fib.  [12/25/12 05:59:12 JESSICAB]
(Message Forwarded by PageGate) 16566 BOWLING GREEN RD;DIST: 99.41 FT;LIFT ASSIST;CARROLL BRIDGE RD;FULGHAM LN;80 yo f fell out of bed. daughter is unable to lift her. she is not hurt just needs lift asst.  [12/25/12 02:33:45 JESSICAB]
(Message Forwarded by PageGate) 302 CANTEBERRY LN;SEIZURE;HUNTINGTON WY;BUCKINGHAM WY;YR OLD FEMALE , ON THE FLOOR  [12/25/12 00:10:09 SHILL]\n32  [12/25/12 00:09:54 SHILL]
(Message Forwarded by PageGate) 1804 S CHURCH ST;DIST: 180.85 FT;SMITHFIELD VOL FIRE DEPT (NEW);CHEST PAIN OR HEART ATTACK;SMITHFIELD BLVD;MOORE AVE;52 yr old male having chest pains and numbness in his left arm and hand.  [12/25/12 00:06:05 SHILL]
(Message Forwarded by PageGate) 14016 BLACK OAK DR;LIFT ASSIST;RED OAK DR;LAUREL OAK DR;72 YEAR OLD FEMALE HAS SLID OFF HER CHAIR AND HUSBAND NEEDS ASSISTANCE GETTING HER BACK UP  [12/24/12 22:46:12 BHUGHES]
(Message Forwarded by PageGate) 18 PINEWOOD COURT;APT 160;SUBWAY;RESCUE MUTUAL AID;44 YEAR OLD FEMALE GROUND LEVEL FALL, HURT WRIST AND WRITST IS SWELLING  [12/24/12 21:25:57 BHUGHES]
(Message Forwarded by PageGate) Update: ;18 PINEWOOD COURT;APT 160;RESCUE MUTUAL AID;44 YEAR OLD FEMALE GROUND LEVEL FALL, HURT WRIST AND WRITST IS SWELLING  [12/24/12 21:25:57 BHUGHES]
(Message Forwarded by PageGate) FYI: ;18 PINEWOOD CT;APT 160;RESCUE MUTUAL AID;44 YEAR OLD FEMALE GROUND LEVEL FALL, HURT WRIST AND WRITST IS SWELLING  [12/24/12 21:25:57 BHUGHES]
(Message Forwarded by PageGate) 724 W MAIN ST;DIST: 1001.01 FT;BLEEDING OR HEMORRHAGING;BURTON DR;HEARN DR;74 YEAR OLD MALE AND HIS CATHERTHER IS BLEEDING  [12/24/12 21:11:55 BHUGHES]
(Message Forwarded by PageGate) 115 BOONE CT;DIST: 63.56 FT;FALLS AND RELATED INJURIES;MINTON WY;56-M --- he is not hurt -- he just needs help from to the help to the chairi  [12/24/12 20:22:48 KHEWITT]
(Message Forwarded by PageGate) 6284 OLD STAGE HWY;DIFFICULTY BREATHING;THOMPSON LN;GREEN RUN LN;ASTHMA ATTACK HX OF THEM  [12/24/12 19:55:03 ADEBARGE]\n59 F  [12/24/12 19:54:35 ADEBARGE]
(Message Forwarded by PageGate) 748 WRENN RD;C;STRUCTURE FIRE;W MAIN ST;STOVE IS ON FIRE  [12/24/12 17:25:06 BHUGHES]
(Message Forwarded by PageGate) FYI: ;748 WRENN RD;C;STRUCTURE FIRE;W MAIN ST;STOVE IS ON FIRE  [12/24/12 17:25:06 BHUGHES]
(Message Forwarded by PageGate) 4688 OLD STAGE HWY;DIFFICULTY BREATHING;JAMES WY;FORT HUGER DR;68 YO MALE\nOXY AT 72\nDIFFICULTY BREA\nCONS/NO ALERT  [12/24/12 11:08:42 KROBERTS]
(Message Forwarded by PageGate) 611 HILLCREST DR;UNCONSCIOUS OR FAINTING;QUAIL ST;SPRING DR;76 YO FEMALE\nFELL UNCONS IN THE HALLWAY\nUNRESPONSIVE\nBREA  [12/24/12 10:36:29 KROBERTS]
(Message Forwarded by PageGate) FYI: ;611 HILLCREST DR;UNCONSCIOUS OR FAINTING;QUAIL ST;SPRING DR;76 YO FEMALE\nFELL UNCONS IN THE HALLWAY\nUNRESPONSIVE\nBREA  [12/24/12 10:36:29 KROBERTS]
(Message Forwarded by PageGate) 1812 S CHURCH ST;RENAL ADVANTAGE DIALYSIS;SICK OR ILL OTHER RESCUE;MOORE AVE;ROUTE 10 BYPASS;51 YO FEMALE\nSICK, DIZZY AND CONFUSED\nCONS/BREA  [12/24/12 09:22:24 KROBERTS]
(Message Forwarded by PageGate) 200 LUMAR RD;ROOM 40;RIVERSIDE CONVALESCENT CENTER;BLEEDING OR HEMORRHAGING;MOONEFIELD DR;73 YO MALE THROWING UP BLOOD  [12/24/12 08:09:43 AGOODWYN]
(Message Forwarded by PageGate) 5078 JAMES WY;MEDICAL ALARM;71 yo f severe arthritis pressed alert medical button but is not answering the care center.......annie jones 757-357-6689...  [12/24/12 00:01:34 CTILLMANN]
(Message Forwarded by PageGate) 603 W MAIN ST;DIST: 138.71 FT;SEVEN ELEVEN;FALLS AND RELATED INJURIES;GREAT SPRING RD;MIDDLE ST;M FALL INTOX HIT HIS HEAD IS BLEEDING FROM THE HEAD. IS NOT CONC. IS BREATHING  [12/23/12 23:00:46 JESSICAB]
(Message Forwarded by PageGate) 13457 MELISSA DR;SICK OR ILL OTHER RESCUE;W BYRON DR;breathing is slow  [12/23/12 22:54:03 KBAKER]\n6 month old female temp of 104.5,  [12/23/12 22:53:33 KBAKER]
(Message Forwarded by PageGate) 14052 WATER OAK DR;DIST: 28.64 FT;OVERDOSE;ENGLISH OAK DR;BLACK OAK DR;[M63-TRANSPORT] {M63} Beg Mileage: 26379  [12/23/12 22:07:52 BHUGHES]\nCALLER WANTS TO MOVE HIM TO ANOTHER ADDRESS SO THAT THE RESIDENTS DO NOT GET INTO TROUBLE  [12/23/12 21:45:45 BHUGHES]\nHARD TIME BREATHING. CALLER SAYS HE CANNOT KEEP HIS EYES OPEN  [12/23/12 21:44:08 BHUGHES]\n16 YEAR OLD MALE HAS TAKEN MULTIPLE BOXES OF COLD MEDICINE  [12/23/12 21:43:24 BHUGHES]
(Message Forwarded by PageGate) FYI: ;14052 WATER OAK DR;DIST: 28.64 FT;OVERDOSE;ENGLISH OAK DR;BLACK OAK DR;16 YEAR OLD MALE HAS TAKEN MULTIPLE BOXES OF COLD MEDICINE  [12/23/12 21:43:24 BHUGHES]
(Message Forwarded by PageGate) 222 APPALOOSA WY;SICK OR ILL OTHER RESCUE;54 y/o female arms tingling and loosing muscle control in her arms  [12/23/12 17:34:08 KBAKER]
(Message Forwarded by PageGate) 108 SUNRISE BLUFF CT;PSYCHIATRIC PROBLEMS;SUNRISE BLUFF LN;[LAW] CALLER WOULD LIKE SOMEONE TO CHECK ON HIS WIFE. SHE HAS BOTTLES OF PILLS. UNSURE IF SHE TOOK THEM  [12/23/12 11:29:56 AGOODWYN]
(Message Forwarded by PageGate) Update: ;108 SUNRISE BLUFF CT;PSYCHIATRIC PROBLEMS;SUNRISE BLUFF LN
(Message Forwarded by PageGate) FYI: ;108 SUNRISE BLUFF CT;SUICIDE;SUNRISE BLUFF LN
(Message Forwarded by PageGate) 735 WRENN RD;APT C;PAIN;W MAIN ST;tooth ache and vomitting\n24 yo female\ncons/brea  [12/23/12 10:30:06 KROBERTS]
(Message Forwarded by PageGate) 304 EAST ST;DIFFICULTY BREATHING;W VIRGINIA AVE;80 YO FEMALE HAVING A HARD TIME BREATHING  [12/23/12 09:39:18 AGOODWYN]
(Message Forwarded by PageGate) FYI: ;ASHBY WY W/BRITT WY;ACCIDENT UNKNOWN INJURIES
(Message Forwarded by PageGate) 101 JOHN ROLFE DR;RM 112;MAGNOLIA MANOR;FALLS AND RELATED INJURIES;BREANN CT;ANDREWS XING;95 YO FEMALE FELL AND IS COMPLAINING OF PAIN IN LOWER HIP.  NOT COOPERATIVE. SENDING OUT FOR PAIN AND MENTAL STATUS CHANGE. POSSIBLE CONCUSSION. IS NOW NAUSEATED. PREFERENCE IS RIVERSIDE  [12/23/12 08:10:57 AGOODWYN]
(Message Forwarded by PageGate) FYI: ;13 LIBERTY AVE;DIST: 64.87 FT;UNCONSCIOUS OR FAINTING;BELLMONT AVE;MARTLETTE ST;Event spawned from CITIZEN ASSIST.  [12/23/2012 04:26:58 CHEDGEPETH]\n{802W} HAVE MEDIC RESPOND HE IS UNRESPONSIVE  [12/23/12 04:26:40 CHEDGEPETH]\nIS UNABLE TO GET HER HUSBAND TO OPEN THE BEDROOM DOOR. ADVISED THEY HAD A VERBAL ARGUEMENT EARLIER AND HE WENT IN THE BEDROOM AND LOCKED THE DOOR. NOW HE WILL NOT ANSWER THE CALLER OR OPEN THE DOOR.  [12/23/12 04:11:07 JESSICAB]
(Message Forwarded by PageGate) Update: ;OLD STAGE HWY/BURWELLS BAY RD;DIST: 1134.26 FT;ACCIDENT UNKNOWN INJURIES;[LAW] CALLER STATED THERE WAS INJURIES  [12/22/12 18:02:01 BHUGHES]\n[LAW] MR.BAILEY ADVISED IT WAS PAST THE OASIS  [12/22/12 18:01:50 BHUGHES]\n[EMS] 517 IN ROUTE  [12/22/12 18:01:19 KHEWITT]\n[LAW] 1/2 MILE NEAR WHERE THE PICKET FENCE STARTS  [12/22/12 18:00:13 BHUGHES]\n[LAW] CALLER STATED THAT IT WAS ABOUT 1 MILE WEST OF OLD WRENNS MILL RD  [12/22/12 18:00:00 BHUGHES]\n[LAW] CLOSE TO THE WHITE PICKET FENCE THERE VEH
(Message Forwarded by PageGate) OLD STAGE HWY/WRENNS MILL RD;DIST: 1134.26 FT;ACCIDENT UNKNOWN INJURIES

Agency name: Windsor Volunteer Fire Dept
Location: Windsor, VA, United States
Contact: Active911

(Message Forwarded by PageGate) 23352 COURTHOUSE HWY;CONSULATE HEALTH CARE WINDSOR;KENSINGTON CT;JOYNER TOWN LN;SMELL OR ODOR OF SMOKE;caller advised that there is a smoke inside the back side of the building near the laundry room. caller cant find where its coming from.  [12/27/12 23:29:46 SHILL]
(Message Forwarded by PageGate) WALTERS HWY/DOUBLETREE LN;DIST: 1001.01 FT;1050;OWNER HAS CALLED BRINKLEYS WRECKER SERVICE FROM SUFFOLK, ETA LESS THAN 30 MINUTE. CAN BE REACHED AT 539-5511.  [12/26/12 15:47:05 DJONES]\nveh flipped --- driver is fine and refusing to have a medic -- no airbags  [12/26/12 15:36:10 KHEWITT]\n;FIRE
(Message Forwarded by PageGate) WINDSOR BLVD/YELLOW HAMMER RD;ACCIDENT UNKNOWN INJURIES;[LAW] CAR IS OVERTURNED. WHITE IS THE ONLY DESCRIPTION SHE CAN GIVE.  [12/25/12 12:57:57 AGOODWYN]

 */

public class VAIsleOfWightCountyParserTest extends BaseParserTest {
  
  public VAIsleOfWightCountyParserTest() {
    setParser(new VAIsleOfWightCountyParser(), "ISLE OF WIGHT COUNTY", "VA");
  }
  
  @Test
  public void testParser() {

    doTest("T1",
        "11365 CENTRAL HILL RD;S CAROLINA AVE;COURTHOUSE HWY;FIRE ALARM;smoke detector zone 16 res last name babb 757-353-0490 [06/20/11 19:01:18 MPMARSH] ",
        "ADDR:11365 CENTRAL HILL RD",
        "X:S CAROLINA AVE & COURTHOUSE HWY",
        "CALL:FIRE ALARM",
        "INFO:smoke detector zone 16 res last name babb 757-353-0490",
        "DATE:06/20/11",
        "TIME:19:01:18");

    doTest("T2",
        "YELLOW HAMMER RD/FIRE TOWER RD;1050;[LAW] {37} ONE FINGER AND JAW/ SEC CONCUSION [06/22/11 04:02:28 SHILL] {37} HAVE INJURIES [06/22/11 04:02:04 SHILL] VSP AD: ",
        "ADDR:YELLOW HAMMER RD & FIRE TOWER RD",
        "CALL:1050",
        "INFO:{37} ONE FINGER AND JAW/ SEC CONCUSION / {37} HAVE INJURIES / VSP AD:",
        "DATE:06/22/11",
        "TIME:04:02:28");

    doTest("T3",
        "23352 COURTHOUSE HWY;CONSULATE HEALTH CARE WINDSOR;KENSINGTON CT;JOYNER TOWN LN;FIRE ALARM;[LAW] WILL TRY TO CONTACT KEYHOLDER [06/22/11 12:20:01 MDUNN] zone",
        "ADDR:23352 COURTHOUSE HWY",
        "CALL:CONSULATE HEALTH CARE WINDSOR",
        "X:KENSINGTON CT & JOYNER TOWN LN",
        "INFO:FIRE ALARM / WILL TRY TO CONTACT KEYHOLDER / zone",
        "DATE:06/22/11",
        "TIME:12:20:01");

    doTest("T4",
        "77 CASTLE ST;LIBERTY AVE;BELLMONT ST;FIRE OTHER NOT LISTED;microwave hot and not in use [06/23/11 09:59:22 JTEMPLETON].   ",
        "ADDR:77 CASTLE ST",
        "X:LIBERTY AVE & BELLMONT ST",
        "CALL:FIRE OTHER NOT LISTED",
        "INFO:microwave hot and not in use / .",
        "DATE:06/23/11",
        "TIME:09:59:22");

    doTest("T5",
        "W WINDSOR BLVD/N PRINCE BLVD;ACCIDENT WITH INJURIES;supreme prking lot. 2 veh. chryslter pt cruiser vs dodge ram piick up [06/23/11 13:13:34 JTEMPLETON]",
        "ADDR:W WINDSOR BLVD & N PRINCE BLVD",
        "CALL:ACCIDENT WITH INJURIES",
        "INFO:supreme prking lot. 2 veh. chryslter pt cruiser vs dodge ram piick up",
        "DATE:06/23/11",
        "TIME:13:13:34");
  }
  
  @Test
  public void testLaryRegula() {

    doTest("T1",
        "CAD:1207 CARRSVILLE HWY;6D;SPRINGDALE APARTMENTS;FALLS AND RELATED INJURIES;JAMESTOWN LN;LEES MILL RD;99 yo female--has fallen, home nurse is unable to gain a",
        "ADDR:1207 CARRSVILLE HWY",
        "APT:6D",
        "PLACE:SPRINGDALE APARTMENTS",
        "CALL:FALLS AND RELATED INJURIES",
        "X:JAMESTOWN LN & LEES MILL RD",
        "INFO:99 yo female--has fallen, home nurse is unable to gain a");

  }
  
  @Test
  public void testCaraolynSeeds() {

    doTest("T1",
        "7466 MAPLE HALL LN;FALLS AND RELATED INJURIES;BEALE PLACE DR;58 yr male fall and is disoriented - fell on 10 m\n",
        "ADDR:7466 MAPLE HALL LN",
        "CALL:FALLS AND RELATED INJURIES",
        "X:BEALE PLACE DR",
        "INFO:58 yr male fall and is disoriented - fell on 10 m");
        

  }
  
  @Test
  public void testIsleOfWightVolunteerRescueSquad() {

    doTest("T1",
        "(Message Forwarded by PageGate) 301 WATSON DR;ACCIDENT UNKNOWN INJURIES;MOONEFIELD DR;AZALEA DR;VEHICLE IN THE RAVINE AT THIS LOCATION\n" +
        "UNKN FURTHER  [12/29/12 20:15:17 KROBERTS]",

        "ADDR:301 WATSON DR",
        "X:MOONEFIELD DR & AZALEA DR",
        "CALL:ACCIDENT UNKNOWN INJURIES",
        "INFO:VEHICLE IN THE RAVINE AT THIS LOCATION UNKN FURTHER",
        "DATE:12/29/12",
        "TIME:20:15:17");

    doTest("T2",
        "(Message Forwarded by PageGate) FYI: ;301 WATSON DR;ACCIDENT UNKNOWN INJURIES;MOONEFIELD DR;AZALEA DR;VEHICLE IN THE RAVINE AT THIS LOCATION\n" +
        "UNKN FURTHER  [12/29/12 20:15:17 KROBERTS]",

        "ADDR:301 WATSON DR",
        "X:MOONEFIELD DR & AZALEA DR",
        "CALL:ACCIDENT UNKNOWN INJURIES",
        "INFO:VEHICLE IN THE RAVINE AT THIS LOCATION UNKN FURTHER",
        "DATE:12/29/12",
        "TIME:20:15:17");

    doTest("T3",
        "(Message Forwarded by PageGate) 735 WRENN RD;APT C;SICK / ILL / PUBLIC ASSIST;W MAIN ST;1 YO MALE\n" +
        "CONS/BREA  [12/29/12 17:50:43 KROBERTS]",

        "ADDR:735 WRENN RD",
        "APT:C",
        "X:W MAIN ST",
        "CALL:SICK / ILL / PUBLIC ASSIST",
        "INFO:1 YO MALE CONS/BREA",
        "DATE:12/29/12",
        "TIME:17:50:43");

    doTest("T4",
        "(Message Forwarded by PageGate) FYI: ;23179 CATFISH ST;LOT 85;UNCONSCIOUS OR FAINTING;TWIN PONDS DR;BEALE DR;35 YO FEMALE\n" +
        "BREA\n" +
        "UNCON IN THE BATHROOM  [12/29/12 17:13:27 KROBERTS]",

        "ADDR:23179 CATFISH ST",
        "X:TWIN PONDS DR & BEALE DR",
        "CALL:UNCONSCIOUS OR FAINTING",
        "APT:LOT 85",
        "INFO:35 YO FEMALE BREA UNCON IN THE BATHROOM",
        "DATE:12/29/12",
        "TIME:17:13:27");

    doTest("T5",
        "(Message Forwarded by PageGate) 200 LUMAR RD;ROOM 44;RIVERSIDE CONVALESCENT CENTER;SICK / ILL / PUBLIC ASSIST;MOONEFIELD DR;slow response  [12/29/12 10:50:15 BPRESSON]\n" +
        "84 yo m, low blood pressure, dipharetic  [12/29/12 10:50:09 BPRESSON]",

        "ADDR:200 LUMAR RD",
        "APT:44",
        "X:MOONEFIELD DR",
        "CALL:SICK / ILL / PUBLIC ASSIST",
        "PLACE:RIVERSIDE CONVALESCENT CENTER",
        "INFO:slow response / 84 yo m, low blood pressure, dipharetic",
        "DATE:12/29/12",
        "TIME:10:50:15");

    doTest("T6",
        "(Message Forwarded by PageGate) 6504 MILL SWAMP RD;UNCONSCIOUS OR FAINTING;WHITE HILL TRL;GREEN LEVEL RD;TURNING PURPLE  [12/29/12 10:31:13 BHUGHES]\n" +
        "81 YEAR OLD FEMALE COLLAPSED IN FLOOR. CALLER STATES THAT SHE HAS TAKEN A BREATH  [12/29/12 10:31:02 BHUGHES]",

        "ADDR:6504 MILL SWAMP RD",
        "X:WHITE HILL TRL & GREEN LEVEL RD",
        "CALL:UNCONSCIOUS OR FAINTING",
        "INFO:TURNING PURPLE / 81 YEAR OLD FEMALE COLLAPSED IN FLOOR. CALLER STATES THAT SHE HAS TAKEN A BREATH",
        "DATE:12/29/12",
        "TIME:10:31:13");

    doTest("T7",
        "(Message Forwarded by PageGate) FYI: ;6504 MILL SWAMP RD;UNCONSCIOUS OR FAINTING;WHITE HILL TRL;GREEN LEVEL RD",
        "ADDR:6504 MILL SWAMP RD",
        "X:WHITE HILL TRL & GREEN LEVEL RD",
        "CALL:UNCONSCIOUS OR FAINTING");

    doTest("T8",
        "(Message Forwarded by PageGate) 207 MONTICELLO CT;DIST: 1010.14 FT;PAIN;BERKELEY ST;70 YEAR OLD FEMALE WHO IS COMP OF RECTUM PAIN, PT IS IN WHEEL CHAIR  [12/29/12 10:16:48 BHUGHES]",
        "ADDR:207 MONTICELLO CT",
        "X:BERKELEY ST",
        "CALL:PAIN",
        "PLACE:DIST: 1010.14 FT",
        "INFO:70 YEAR OLD FEMALE WHO IS COMP OF RECTUM PAIN, PT IS IN WHEEL CHAIR",
        "DATE:12/29/12",
        "TIME:10:16:48");

    doTest("T9",
        "(Message Forwarded by PageGate) 305 CANTEBERRY LN;STRUCTURE FIRE;HUNTINGTON WY;BUCKINGHAM WY;ELECTRICAL FIRE  [12/29/12 08:56:27 BHUGHES]",
        "ADDR:305 CANTEBERRY LN",
        "X:HUNTINGTON WY & BUCKINGHAM WY",
        "CALL:STRUCTURE FIRE",
        "INFO:ELECTRICAL FIRE",
        "DATE:12/29/12",
        "TIME:08:56:27");

    doTest("T10",
        "(Message Forwarded by PageGate) FYI: ;305 CANTEBERRY LN;STRUCTURE FIRE;HUNTINGTON WY;BUCKINGHAM WY;ELECTRICAL FIRE  [12/29/12 08:56:27 BHUGHES]",
        "ADDR:305 CANTEBERRY LN",
        "X:HUNTINGTON WY & BUCKINGHAM WY",
        "CALL:STRUCTURE FIRE",
        "INFO:ELECTRICAL FIRE",
        "DATE:12/29/12",
        "TIME:08:56:27");

    doTest("T11",
        "(Message Forwarded by PageGate) 5140 JAMES WY;PAIN;44 Y/O M IN PAIN  [12/29/12 06:48:08 CHEDGEPETH]",
        "ADDR:5140 JAMES WY",
        "CALL:PAIN",
        "INFO:44 Y/O M IN PAIN",
        "DATE:12/29/12",
        "TIME:06:48:08");

    doTest("T12",
        "(Message Forwarded by PageGate) 18155 BOB WHITE RD;DIST: 1294.00 FT;DIFFICULTY BREATHING;BOWLING GREEN RD;RESTLESS HEART RD;42 Y/O F DIFF BREATHING CHEST PAINS  [12/29/12 06:42:12 CHEDGEPETH]",
        "ADDR:18155 BOB WHITE RD",
        "X:BOWLING GREEN RD & RESTLESS HEART RD",
        "CALL:DIFFICULTY BREATHING",
        "PLACE:DIST: 1294.00 FT",
        "INFO:42 Y/O F DIFF BREATHING CHEST PAINS",
        "DATE:12/29/12",
        "TIME:06:42:12");

    doTest("T13",
        "(Message Forwarded by PageGate) 104 CROATAN CT;STRUCTURE FIRE;JOHN ROLFE DR",
        "ADDR:104 CROATAN CT",
        "X:JOHN ROLFE DR",
        "CALL:STRUCTURE FIRE");

    doTest("T14",
        "(Message Forwarded by PageGate) FYI: ;104 CROATAN CT;STRUCTURE FIRE;JOHN ROLFE DR",
        "ADDR:104 CROATAN CT",
        "X:JOHN ROLFE DR",
        "CALL:STRUCTURE FIRE");

    doTest("T15",
        "(Message Forwarded by PageGate) 513 CEDAR ST;B2;DIFFICULTY BREATHING;UNDERWOOD LN;COVENANT PL;CHEIF DEIFFICULTY BREATHING  TIGHT CHEST ...... IN THE BACKGROUND CAN HEAR HER CRYING  [12/28/12 21:06:57 CGONZALEZ]",
        "ADDR:513 CEDAR ST",
        "X:UNDERWOOD LN & COVENANT PL",
        "CALL:DIFFICULTY BREATHING",
        "APT:B2",
        "INFO:CHEIF DEIFFICULTY BREATHING  TIGHT CHEST ...... IN THE BACKGROUND CAN HEAR HER CRYING",
        "DATE:12/28/12",
        "TIME:21:06:57");

    doTest("T16",
        "(Message Forwarded by PageGate) 735 WRENN RD;APT C;SICK OR ILL OTHER RESCUE;W MAIN ST;18 MNT OLD FEVER IS 102.3  AND SHAKING  [12/28/12 19:49:15 CGONZALEZ]",
        "ADDR:735 WRENN RD",
        "APT:C",
        "X:W MAIN ST",
        "CALL:SICK OR ILL OTHER RESCUE",
        "INFO:18 MNT OLD FEVER IS 102.3  AND SHAKING",
        "DATE:12/28/12",
        "TIME:19:49:15");

    doTest("T17",
        "(Message Forwarded by PageGate) 1804 S CHURCH ST;SMITHFIELD VOL FIRE DEPT (NEW);DIFFICULTY BREATHING;SMITHFIELD BLVD;MOORE AVE",
        "ADDR:1804 S CHURCH ST",
        "X:SMITHFIELD BLVD & MOORE AVE",
        "CALL:DIFFICULTY BREATHING",
        "PLACE:SMITHFIELD VOL FIRE DEPT (NEW)");

    doTest("T18",
        "(Message Forwarded by PageGate) Update: ;24236 KNOXVILLE RD;OVERDOSE;WILLIE ROBERTS RD;she is responsive at this time  ....... has been going on for 3-4 hrs  [12/28/12 16:19:07 CGONZALEZ]\n" +
        "hx of overdosing and eplicitic  [12/28/12 16:18:22 CGONZALEZ]\n" +
        "abrams  f  48 y/o   possible 10 96  [12/28/12 16:18:01 CGONZALEZ]\n" +
        "caller states his mother has a headache weak dizzyness , and not very responsive  [12/28/12 16:16:31 CGONZALEZ]",

        "ADDR:24236 KNOXVILLE RD",
        "X:WILLIE ROBERTS RD",
        "CALL:OVERDOSE",
        "INFO:she is responsive at this time  ....... has been going on for 3-4 hrs / hx of overdosing and eplicitic / abrams  f  48 y/o   possible 10 96 / caller states his mother has a headache weak dizzyness , and not very responsive",
        "DATE:12/28/12",
        "TIME:16:19:07");

    doTest("T19",
        "(Message Forwarded by PageGate) 107 COCKES LN;ABDOMINAL PAIN;MAIN ST;CEDAR ST;54 y/o female etopic pregnancy having severe abdominal pain  [12/28/12 11:09:03 KBAKER]",
        "ADDR:107 COCKES LN",
        "X:MAIN ST & CEDAR ST",
        "CALL:ABDOMINAL PAIN",
        "INFO:54 y/o female etopic pregnancy having severe abdominal pain",
        "DATE:12/28/12",
        "TIME:11:09:03");

    doTest("T20",
        "(Message Forwarded by PageGate) 101 JOHN ROLFE DR;RM 125;MAGNOLIA MANOR;CHEST PAIN OR HEART ATTACK;BREANN CT;ANDREWS XING;87 y/o female with chest pain and shortness of breath  [12/28/12 08:25:15 KBAKER]",
        "ADDR:101 JOHN ROLFE DR",
        "APT:125",
        "X:BREANN CT",
        "CALL:CHEST PAIN OR HEART ATTACK",
        "PLACE:MAGNOLIA MANOR",
        "INFO:ANDREWS XING / 87 y/o female with chest pain and shortness of breath",
        "DATE:12/28/12",
        "TIME:08:25:15");

    doTest("T21",
        "(Message Forwarded by PageGate) 11259 CINDALE DR;DIFFICULTY BREATHING;BETHEL CHURCH LN;BLAIRS CREEK DR;58 YEAR OLD DIFFICULTY BREATHING HX: DIABETES COPD SOCADOCSIS . CONSCIOUS ALERT  [12/28/12 07:13:53 BHUGHES]",
        "ADDR:11259 CINDALE DR",
        "X:BETHEL CHURCH LN & BLAIRS CREEK DR",
        "CALL:DIFFICULTY BREATHING",
        "INFO:58 YEAR OLD DIFFICULTY BREATHING HX: DIABETES COPD SOCADOCSIS . CONSCIOUS ALERT",
        "DATE:12/28/12",
        "TIME:07:13:53");

    doTest("T22",
        "(Message Forwarded by PageGate) 126 HOLLOWAY DR;LIFT ASSIST;OLIVER DR;81 yr old female slid off the bed. she is fine just need lift assist.  [12/28/12 00:59:18 SHILL]",
        "ADDR:126 HOLLOWAY DR",
        "X:OLIVER DR",
        "CALL:LIFT ASSIST",
        "INFO:81 yr old female slid off the bed. she is fine just need lift assist.",
        "DATE:12/28/12",
        "TIME:00:59:18");

    doTest("T23",
        "(Message Forwarded by PageGate) 505 VIRGINIA AVE;FALLS AND RELATED INJURIES;PAGAN RD;LAWNE ST;85 YEARS OLD FELL BATHROOM HIT HER HEAD.  [12/27/12 20:12:31 MZERICK]",
        "ADDR:505 VIRGINIA AVE",
        "X:PAGAN RD & LAWNE ST",
        "CALL:FALLS AND RELATED INJURIES",
        "INFO:85 YEARS OLD FELL BATHROOM HIT HER HEAD.",
        "DATE:12/27/12",
        "TIME:20:12:31");

    doTest("T24",
        "(Message Forwarded by PageGate) FYI: ;21475 WIGWAM CIR;UNCONSCIOUS OR FAINTING;AUCKLAND CT;40 YEARS OLD MALE  PASSED OUT  IN THE HOUSE.  HE IS BREATHING.  [12/27/12 18:21:30 MZERICK]",
        "ADDR:21475 WIGWAM CIR",
        "X:AUCKLAND CT",
        "CALL:UNCONSCIOUS OR FAINTING",
        "INFO:40 YEARS OLD MALE  PASSED OUT  IN THE HOUSE.  HE IS BREATHING.",
        "DATE:12/27/12",
        "TIME:18:21:30");

    doTest("T25",
        "(Message Forwarded by PageGate) Update: ;903 GATLING POINTE PKWY;GATLING POINTE YACHT CLUB;UNNAMED;JAMES LANDING CIR;ASSIST BOATER;Event spawned for SFD Event ID:201281644  [12/27/12 17:40:38 MZERICK]\n" +
        "Event spawned from SUSPICIOUS PERS./VEH./ACTIVITY.  [12/27/2012 17:38:41 CGONZALEZ]\n" +
        "coast guard has made contact with the subject who shot off the flare and is working the situation\n" +
        "will call back if they need assistance  [12/27/12 17:32:03 KROBERTS]\n" +
        "contacting coast guard to see if they have recieved any reports  [12/27/12 17:29",

        "ADDR:903 GATLING POINTE PKWY",
        "X:JAMES LANDING CIR",
        "CALL:UNNAMED",
        "PLACE:GATLING POINTE YACHT CLUB",
        "INFO:ASSIST BOATER / Event spawned for SFD Event ID:201281644 / Event spawned from SUSPICIOUS PERS./VEH./ACTIVITY. / coast guard has made contact with the subject who shot off the flare and is working the situation will call back if they need assistance / contacting coast guard to see if they have recieved any reports",
        "DATE:12/27/12",
        "TIME:17:40:38");

    doTest("T26",
        "(Message Forwarded by PageGate) 751-A WRENN RD;DIST: 138.71 FT;SICK OR ILL OTHER RESCUE;W MAIN ST;7 month old with congestion  [12/27/12 11:58:04 KBAKER]",
        "ADDR:751-A WRENN RD",
        "MADDR:751 WRENN RD",
        "X:W MAIN ST",
        "CALL:SICK OR ILL OTHER RESCUE",
        "PLACE:DIST: 138.71 FT",
        "INFO:7 month old with congestion",
        "DATE:12/27/12",
        "TIME:11:58:04");

    doTest("T27",
        "(Message Forwarded by PageGate) 20212 OLDE TOWNE CT;DIST: 416.13 FT;POSSIBLE DOA OR FULL ARREST;OLDE TOWNE PL;OLDE TOWNE PL;FEMALE DENIES TRYING CPR STATES HE IS GONE  [12/27/12 07:15:17 KBAKER]\n" +
        "58 MALE COLD TO TOUCH NOT BREATHING  [12/27/12 07:14:27 KBAKER]",

        "ADDR:20212 OLDE TOWNE CT",
        "X:OLDE TOWNE PL & OLDE TOWNE PL",
        "CALL:POSSIBLE DOA OR FULL ARREST",
        "PLACE:DIST: 416.13 FT",
        "INFO:FEMALE DENIES TRYING CPR STATES HE IS GONE / 58 MALE COLD TO TOUCH NOT BREATHING",
        "DATE:12/27/12",
        "TIME:07:15:17");

    doTest("T28",
        "(Message Forwarded by PageGate) FYI: ;20212 OLDE TOWNE CT;DIST: 416.13 FT;POSSIBLE DOA OR FULL ARREST;OLDE TOWNE PL;OLDE TOWNE PL;58 MALE COLD TO TOUCH NOT BREATHING  [12/27/12 07:14:27 KBAKER]",
        "ADDR:20212 OLDE TOWNE CT",
        "X:OLDE TOWNE PL & OLDE TOWNE PL",
        "CALL:POSSIBLE DOA OR FULL ARREST",
        "PLACE:DIST: 416.13 FT",
        "INFO:58 MALE COLD TO TOUCH NOT BREATHING",
        "DATE:12/27/12",
        "TIME:07:14:27");

    doTest("T29",
        "(Message Forwarded by PageGate) 114 TALBOT DR;SICK OR ILL OTHER RESCUE;WILSON RD;MAGRUDER RD;90 Y/O DIAB THROWING UP AND UNABLE WALK  [12/27/12 05:43:48 SDALTON]",
        "ADDR:114 TALBOT DR",
        "X:WILSON RD & MAGRUDER RD",
        "CALL:SICK OR ILL OTHER RESCUE",
        "INFO:90 Y/O DIAB THROWING UP AND UNABLE WALK",
        "DATE:12/27/12",
        "TIME:05:43:48");

    doTest("T30",
        "(Message Forwarded by PageGate) 3407 LONGWOOD DR;STROKE;PINE CIR;POSSIBLE STROKE, 64 YR OLD MALE. 93/58 BP. BLOOD SUGAR 315  [12/26/12 21:10:20 DJONES]",
        "ADDR:3407 LONGWOOD DR",
        "X:PINE CIR",
        "CALL:STROKE",
        "INFO:POSSIBLE STROKE, 64 YR OLD MALE. 93/58 BP. BLOOD SUGAR 315",
        "DATE:12/26/12",
        "TIME:21:10:20");

    doTest("T31",
        "(Message Forwarded by PageGate) FYI: ;OLD MYRTLE RD/FREEMAN DR;DIST: 589.55 FT;ACCIDENT WITH INJURIES;she daughter has flipped her veh ---  [12/26/12 20:21:53 KHEWITT]\n" +
        "she is on old myrtle near  [12/26/12 20:20:46 KHEWITT]",

        "ADDR:OLD MYRTLE RD & FREEMAN DR",
        "PLACE:DIST: 589.55 FT",
        "CALL:ACCIDENT WITH INJURIES",
        "INFO:she daughter has flipped her veh --- / she is on old myrtle near",
        "DATE:12/26/12",
        "TIME:20:21:53");

    doTest("T32",
        "(Message Forwarded by PageGate) 101 JOHN ROLFE DR;RM 112;MAGNOLIA MANOR;SICK OR ILL OTHER RESCUE;BREANN CT;ANDREWS XING;96-F ---- change in mental status and elavated bp  [12/26/12 19:39:38 KHEWITT]",
        "ADDR:101 JOHN ROLFE DR",
        "APT:112",
        "X:BREANN CT",
        "CALL:SICK OR ILL OTHER RESCUE",
        "PLACE:MAGNOLIA MANOR",
        "INFO:ANDREWS XING / 96-F ---- change in mental status and elavated bp",
        "DATE:12/26/12",
        "TIME:19:39:38");

    doTest("T33",
        "(Message Forwarded by PageGate) 16030 CARROLL BRIDGE RD;DIST: 56.69 FT;FALLS AND RELATED INJURIES;WEBB LN;BOWLING GREEN RD;78-m --- fall from standing position --- poss broken hip ---  [12/26/12 17:45:18 KHEWITT]",
        "ADDR:16030 CARROLL BRIDGE RD",
        "X:WEBB LN & BOWLING GREEN RD",
        "CALL:FALLS AND RELATED INJURIES",
        "PLACE:DIST: 56.69 FT",
        "INFO:78-m --- fall from standing position --- poss broken hip ---",
        "DATE:12/26/12",
        "TIME:17:45:18");

    doTest("T34",
        "(Message Forwarded by PageGate) 107 COCKES LN;DIST: 311.49 FT;ABDOMINAL PAIN;MAIN ST;CEDAR ST;54-F --- severe abdominal pains -- hx of diabetes and high blood pressure  [12/26/12 17:01:43 KHEWITT]",
        "ADDR:107 COCKES LN",
        "X:MAIN ST & CEDAR ST",
        "CALL:ABDOMINAL PAIN",
        "PLACE:DIST: 311.49 FT",
        "INFO:54-F --- severe abdominal pains -- hx of diabetes and high blood pressure",
        "DATE:12/26/12",
        "TIME:17:01:43");

    doTest("T35",
        "(Message Forwarded by PageGate) 16566 BOWLING GREEN RD;LIFT ASSIST;CARROLL BRIDGE RD;FULGHAM LN;NEEDS ASSISTANCE LIFTING HER MOTHER. SHE IS 80 YO. SHE FELL WHILE TRYING TO GET IN HER SEAT  [12/26/12 11:58:38 AGOODWYN]",
        "ADDR:16566 BOWLING GREEN RD",
        "X:CARROLL BRIDGE RD & FULGHAM LN",
        "CALL:LIFT ASSIST",
        "INFO:NEEDS ASSISTANCE LIFTING HER MOTHER. SHE IS 80 YO. SHE FELL WHILE TRYING TO GET IN HER SEAT",
        "DATE:12/26/12",
        "TIME:11:58:38");

    doTest("T36",
        "(Message Forwarded by PageGate) 1941 S CHURCH ST;FOOD LION;ACCIDENT UNKNOWN INJURIES;MOORE AVE;ROUTE 10 BYPASS;[FIRE] 2ND CALL BLEEDING FROM THE NOSE OR MOUTH AND HAND  [12/26/12 11:00:23 AGOODWYN]\n" +
        "LEFT FOOD LION IN WRONG LANE AND HIT A TREE  [12/26/12 11:00:24 BKING]\n" +
        "SOMEONE  [12/26/12 10:59:58 BKING]",

        "ADDR:1941 S CHURCH ST",
        "X:MOORE AVE & ROUTE 10 BYPASS",
        "CALL:ACCIDENT UNKNOWN INJURIES",
        "PLACE:FOOD LION",
        "INFO:2ND CALL BLEEDING FROM THE NOSE OR MOUTH AND HAND / LEFT FOOD LION IN WRONG LANE AND HIT A TREE / SOMEONE",
        "DATE:12/26/12",
        "TIME:11:00:23");

    doTest("T37",
        "(Message Forwarded by PageGate) FYI: ;1941 S CHURCH ST;FOOD LION;ACCIDENT UNKNOWN INJURIES;MOORE AVE;ROUTE 10 BYPASS;LEFT FOOD LION IN WRONG LANE AND HIT A TREE  [12/26/12 11:00:24 BKING]\n" +
        "SOMEONE  [12/26/12 10:59:58 BKING]",

        "ADDR:1941 S CHURCH ST",
        "X:MOORE AVE & ROUTE 10 BYPASS",
        "CALL:ACCIDENT UNKNOWN INJURIES",
        "PLACE:FOOD LION",
        "INFO:LEFT FOOD LION IN WRONG LANE AND HIT A TREE / SOMEONE",
        "DATE:12/26/12",
        "TIME:11:00:24");

    doTest("T38",
        "(Message Forwarded by PageGate) 601 CEDAR ST;APT 501;COVENANT PLACE;SICK OR ILL OTHER RESCUE;ACACIA CIR;UNDERWOOD LN;70 years old female  doesnt feel good.  [12/26/12 10:48:22 MZERICK]\n" +
        "This address [601 CEDAR ST] is currently missing from the map centerline and was verified using tabular street records.  [12/26/12 10:47:38 MZERICK]",

        "ADDR:601 CEDAR ST",
        "APT:501",
        "PLACE:COVENANT PLACE",
        "CALL:SICK OR ILL OTHER RESCUE",
        "X:ACACIA CIR & UNDERWOOD LN",
        "INFO:70 years old female  doesnt feel good. / This address / is currently missing from the map centerline and was verified using tabular street records.",
        "DATE:12/26/12",
        "TIME:10:48:22");

    doTest("T39",
        "(Message Forwarded by PageGate) 12593 NIKE PARK RD;STRUCTURE FIRE;PALEO POINT LN;WATERVIEW TRL;CALLER STATES HER STOVE IS ON FIRE.  [12/26/12 07:39:04 AGOODWYN]",
        "ADDR:12593 NIKE PARK RD",
        "X:PALEO POINT LN & WATERVIEW TRL",
        "CALL:STRUCTURE FIRE",
        "INFO:CALLER STATES HER STOVE IS ON FIRE.",
        "DATE:12/26/12",
        "TIME:07:39:04");

    doTest("T40",
        "(Message Forwarded by PageGate) FYI: ;12593 NIKE PARK RD;STRUCTURE FIRE;PALEO POINT LN;WATERVIEW TRL;CALLER STATES HER STOVE IS ON FIRE.  [12/26/12 07:39:04 AGOODWYN]",
        "ADDR:12593 NIKE PARK RD",
        "X:PALEO POINT LN & WATERVIEW TRL",
        "CALL:STRUCTURE FIRE",
        "INFO:CALLER STATES HER STOVE IS ON FIRE.",
        "DATE:12/26/12",
        "TIME:07:39:04");

    doTest("T41",
        "(Message Forwarded by PageGate) 315 EAST ST;SICK OR ILL OTHER RESCUE;W VIRGINIA AVE;27 YO F FEELS LIKE SHE MIGHT PASS OUT. HAS NOT BEEN SICK  [12/26/12 06:21:39 JESSICAB]",
        "ADDR:315 EAST ST",
        "X:W VIRGINIA AVE",
        "CALL:SICK OR ILL OTHER RESCUE",
        "INFO:27 YO F FEELS LIKE SHE MIGHT PASS OUT. HAS NOT BEEN SICK",
        "DATE:12/26/12",
        "TIME:06:21:39");

    doTest("T42",
        "(Message Forwarded by PageGate) 313 GRANDVILLE ARCH;BACK PAIN OR INJURY;SOUTHAMPTON CT;QUEEN CT;FEMALE  [12/26/12 04:53:57 SHILL]\n" +
        "back pain, cant move, 71 yrs old.  [12/26/12 04:53:30 SHILL]",

        "ADDR:313 GRANDVILLE ARCH",
        "X:SOUTHAMPTON CT & QUEEN CT",
        "CALL:BACK PAIN OR INJURY",
        "INFO:FEMALE / back pain, cant move, 71 yrs old.",
        "DATE:12/26/12",
        "TIME:04:53:57");

    doTest("T43",
        "(Message Forwarded by PageGate) 646 WESTMINSTER RCH;DIFFICULTY BREATHING;GRANDVILLE ARCH;BRISTOL ST;8 yr old male asthmatic, having a hard time breathing. just woke up.  [12/26/12 03:42:38 SHILL]",
        "ADDR:646 WESTMINSTER RCH",
        "MADDR:646 WESTMINSTER REACH",
        "X:GRANDVILLE ARCH & BRISTOL ST",
        "CALL:DIFFICULTY BREATHING",
        "INFO:8 yr old male asthmatic, having a hard time breathing. just woke up.",
        "DATE:12/26/12",
        "TIME:03:42:38");

    doTest("T44",
        "(Message Forwarded by PageGate) 24 RIVERSIDE DR;FRACTURES OR BROKEN BONES;WILDERNESS LN;WATERVIEW CIR;77 yr old male fallen possible broken right arm.  [12/26/12 00:33:57 SHILL]",
        "ADDR:24 RIVERSIDE DR",
        "X:WILDERNESS LN & WATERVIEW CIR",
        "CALL:FRACTURES OR BROKEN BONES",
        "INFO:77 yr old male fallen possible broken right arm.",
        "DATE:12/26/12",
        "TIME:00:33:57");

    doTest("T45",
        "(Message Forwarded by PageGate) 646 WESTMINSTER RCH;DIST: 1010.14 FT;DIFFICULTY BREATHING;GRANDVILLE ARCH;BRISTOL ST;8 M  [12/25/12 22:29:51 ADEBARGE]\n" +
        "8 ASTHMA ATTACK  [12/25/12 22:29:42 ADEBARGE]",

        "ADDR:646 WESTMINSTER RCH",
        "MADDR:646 WESTMINSTER REACH",
        "PLACE:DIST: 1010.14 FT",
        "CALL:DIFFICULTY BREATHING",
        "X:GRANDVILLE ARCH & BRISTOL ST",
        "INFO:8 M / 8 ASTHMA ATTACK",
        "DATE:12/25/12",
        "TIME:22:29:51");

    doTest("T46",
        "(Message Forwarded by PageGate) 14065 BLACK OAK DR;LIFT ASSIST;LAUREL OAK DR;WATER OAK DR;68 F  FELL OUT OF WALKER AND NEEDS HELP GETTING UP ON THE FRONT PORCH  [12/25/12 21:15:26 ADEBARGE]",
        "ADDR:14065 BLACK OAK DR",
        "X:LAUREL OAK DR & WATER OAK DR",
        "CALL:LIFT ASSIST",
        "INFO:68 F  FELL OUT OF WALKER AND NEEDS HELP GETTING UP ON THE FRONT PORCH",
        "DATE:12/25/12",
        "TIME:21:15:26");

    doTest("T47",
        "(Message Forwarded by PageGate) FYI: ;7651 WHISPERING PINES TRL;BIG BEAR CAMPGROUND;POSSIBLE DOA OR FULL ARREST;BEALE PLACE DR;CENTRAL HILL RD;22 YEARS OLD MALE  COLD TO THE TOUCH.  [12/25/12 18:40:03 MZERICK]",
        "ADDR:7651 WHISPERING PINES TRL",
        "X:BEALE PLACE DR & CENTRAL HILL RD",
        "CALL:POSSIBLE DOA OR FULL ARREST",
        "PLACE:BIG BEAR CAMPGROUND",
        "INFO:22 YEARS OLD MALE  COLD TO THE TOUCH.",
        "DATE:12/25/12",
        "TIME:18:40:03");

    doTest("T48",
        "(Message Forwarded by PageGate) 105 LANE CRES;CHEST PAIN OR HEART ATTACK;KENDALL HVN;believes to be having another heart attack  [12/25/12 14:47:49 ADEBARGE]\n" +
        "46 m  [12/25/12 14:47:37 ADEBARGE]",

        "ADDR:105 LANE CRES",
        "CALL:CHEST PAIN OR HEART ATTACK",
        "INFO:KENDALL HVN / believes to be having another heart attack / 46 m",
        "DATE:12/25/12",
        "TIME:14:47:49");

    doTest("T49",
        "(Message Forwarded by PageGate) Update: ;9141 WINDSOR BLVD;ACCIDENT UNKNOWN INJURIES;STAVE MILL RD;[FIRE] 717 to station  [12/25/12 13:01:12 KHEWITT]\n" +
        "[FIRE] 408 responding  [12/25/12 13:00:53 KHEWITT]\n" +
        "[LAW] BETWEEN WINDSOR AND ZUNI  [12/25/12 12:58:53 AGOODWYN]\n" +
        "[LAW] FLIPPED - MAN IS OUT  [12/25/12 12:59:29 JEDMONDS]\n" +
        "[LAW] CAR IS OVERTURNED. WHITE IS THE ONLY DESCRIPTION SHE CAN GIVE.  [12/25/12 12:57:57 AGOODWYN]",

        "ADDR:9141 WINDSOR BLVD",
        "X:STAVE MILL RD",
        "CALL:ACCIDENT UNKNOWN INJURIES",
        "INFO:717 to station / 408 responding / BETWEEN WINDSOR AND ZUNI / FLIPPED - MAN IS OUT / CAR IS OVERTURNED. WHITE IS THE ONLY DESCRIPTION SHE CAN GIVE.",
        "DATE:12/25/12",
        "TIME:13:01:12");

    doTest("T50",
        "(Message Forwarded by PageGate) FYI: ;WINDSOR BLVD/YELLOW HAMMER RD;ACCIDENT UNKNOWN INJURIES",
        "ADDR:WINDSOR BLVD & YELLOW HAMMER RD",
        "CALL:ACCIDENT UNKNOWN INJURIES");

    doTest("T51",
        "(Message Forwarded by PageGate) FYI: ;WINDSOR BLVD/YELLOW HAMMER RD;ACCIDENT UNKNOWN INJURIES",
        "ADDR:WINDSOR BLVD & YELLOW HAMMER RD",
        "CALL:ACCIDENT UNKNOWN INJURIES");

    doTest("T52",
        "(Message Forwarded by PageGate) 312 WEST ST;CHEST PAIN OR HEART ATTACK;W VIRGINIA AVE;55 YO MALE. IS HAVING A SEIZURE OR HEART ATTACK  [12/25/12 08:36:00 AGOODWYN]",
        "ADDR:312 WEST ST",
        "X:W VIRGINIA AVE",
        "CALL:CHEST PAIN OR HEART ATTACK",
        "INFO:55 YO MALE. IS HAVING A SEIZURE OR HEART ATTACK",
        "DATE:12/25/12",
        "TIME:08:36:00");

    doTest("T53",
        "(Message Forwarded by PageGate) 20711 CREEKSIDE DR;CHEST PAIN OR HEART ATTACK;GATLING POINTE PKWY S;RIVERS BEND PL;77 yo m having chest pains. no diff breathing. is conc and breathing. history of a-fib.  [12/25/12 05:59:12 JESSICAB]",
        "ADDR:20711 CREEKSIDE DR",
        "X:GATLING POINTE PKWY S & RIVERS BEND PL",
        "CALL:CHEST PAIN OR HEART ATTACK",
        "INFO:77 yo m having chest pains. no diff breathing. is conc and breathing. history of a-fib.",
        "DATE:12/25/12",
        "TIME:05:59:12");

    doTest("T54",
        "(Message Forwarded by PageGate) 16566 BOWLING GREEN RD;DIST: 99.41 FT;LIFT ASSIST;CARROLL BRIDGE RD;FULGHAM LN;80 yo f fell out of bed. daughter is unable to lift her. she is not hurt just needs lift asst.  [12/25/12 02:33:45 JESSICAB]",
        "ADDR:16566 BOWLING GREEN RD",
        "X:CARROLL BRIDGE RD & FULGHAM LN",
        "CALL:LIFT ASSIST",
        "PLACE:DIST: 99.41 FT",
        "INFO:80 yo f fell out of bed. daughter is unable to lift her. she is not hurt just needs lift asst.",
        "DATE:12/25/12",
        "TIME:02:33:45");

    doTest("T55",
        "(Message Forwarded by PageGate) 302 CANTEBERRY LN;SEIZURE;HUNTINGTON WY;BUCKINGHAM WY;YR OLD FEMALE , ON THE FLOOR  [12/25/12 00:10:09 SHILL]\n" +
        "32  [12/25/12 00:09:54 SHILL]",

        "ADDR:302 CANTEBERRY LN",
        "X:HUNTINGTON WY & BUCKINGHAM WY",
        "CALL:SEIZURE",
        "INFO:YR OLD FEMALE , ON THE FLOOR / 32",
        "DATE:12/25/12",
        "TIME:00:10:09");

    doTest("T56",
        "(Message Forwarded by PageGate) 1804 S CHURCH ST;DIST: 180.85 FT;SMITHFIELD VOL FIRE DEPT (NEW);CHEST PAIN OR HEART ATTACK;SMITHFIELD BLVD;MOORE AVE;52 yr old male having chest pains and numbness in his left arm and hand.  [12/25/12 00:06:05 SHILL]",
        "ADDR:1804 S CHURCH ST",
        "PLACE:SMITHFIELD VOL FIRE DEPT (NEW) - DIST: 180.85 FT",
        "CALL:CHEST PAIN OR HEART ATTACK",
        "X:SMITHFIELD BLVD & MOORE AVE",
        "INFO:52 yr old male having chest pains and numbness in his left arm and hand.",
        "DATE:12/25/12",
        "TIME:00:06:05");

    doTest("T57",
        "(Message Forwarded by PageGate) 14016 BLACK OAK DR;LIFT ASSIST;RED OAK DR;LAUREL OAK DR;72 YEAR OLD FEMALE HAS SLID OFF HER CHAIR AND HUSBAND NEEDS ASSISTANCE GETTING HER BACK UP  [12/24/12 22:46:12 BHUGHES]",
        "ADDR:14016 BLACK OAK DR",
        "X:RED OAK DR & LAUREL OAK DR",
        "CALL:LIFT ASSIST",
        "INFO:72 YEAR OLD FEMALE HAS SLID OFF HER CHAIR AND HUSBAND NEEDS ASSISTANCE GETTING HER BACK UP",
        "DATE:12/24/12",
        "TIME:22:46:12");

    doTest("T58",
        "(Message Forwarded by PageGate) 18 PINEWOOD COURT;APT 160;SUBWAY;RESCUE MUTUAL AID;44 YEAR OLD FEMALE GROUND LEVEL FALL, HURT WRIST AND WRITST IS SWELLING  [12/24/12 21:25:57 BHUGHES]",
        "ADDR:18 PINEWOOD COURT",
        "APT:160",
        "CALL:SUBWAY",
        "INFO:RESCUE MUTUAL AID / 44 YEAR OLD FEMALE GROUND LEVEL FALL, HURT WRIST AND WRITST IS SWELLING",
        "DATE:12/24/12",
        "TIME:21:25:57");

    doTest("T59",
        "(Message Forwarded by PageGate) Update: ;18 PINEWOOD COURT;APT 160;RESCUE MUTUAL AID;44 YEAR OLD FEMALE GROUND LEVEL FALL, HURT WRIST AND WRITST IS SWELLING  [12/24/12 21:25:57 BHUGHES]",
        "ADDR:18 PINEWOOD COURT",
        "APT:160",
        "CALL:RESCUE MUTUAL AID",
        "INFO:44 YEAR OLD FEMALE GROUND LEVEL FALL, HURT WRIST AND WRITST IS SWELLING",
        "DATE:12/24/12",
        "TIME:21:25:57");

    doTest("T60",
        "(Message Forwarded by PageGate) FYI: ;18 PINEWOOD CT;APT 160;RESCUE MUTUAL AID;44 YEAR OLD FEMALE GROUND LEVEL FALL, HURT WRIST AND WRITST IS SWELLING  [12/24/12 21:25:57 BHUGHES]",
        "ADDR:18 PINEWOOD CT",
        "APT:160",
        "CALL:RESCUE MUTUAL AID",
        "INFO:44 YEAR OLD FEMALE GROUND LEVEL FALL, HURT WRIST AND WRITST IS SWELLING",
        "DATE:12/24/12",
        "TIME:21:25:57");

    doTest("T61",
        "(Message Forwarded by PageGate) 724 W MAIN ST;DIST: 1001.01 FT;BLEEDING OR HEMORRHAGING;BURTON DR;HEARN DR;74 YEAR OLD MALE AND HIS CATHERTHER IS BLEEDING  [12/24/12 21:11:55 BHUGHES]",
        "ADDR:724 W MAIN ST",
        "X:BURTON DR & HEARN DR",
        "CALL:BLEEDING OR HEMORRHAGING",
        "PLACE:DIST: 1001.01 FT",
        "INFO:74 YEAR OLD MALE AND HIS CATHERTHER IS BLEEDING",
        "DATE:12/24/12",
        "TIME:21:11:55");

    doTest("T62",
        "(Message Forwarded by PageGate) 115 BOONE CT;DIST: 63.56 FT;FALLS AND RELATED INJURIES;MINTON WY;56-M --- he is not hurt -- he just needs help from to the help to the chairi  [12/24/12 20:22:48 KHEWITT]",
        "ADDR:115 BOONE CT",
        "X:MINTON WY",
        "CALL:FALLS AND RELATED INJURIES",
        "PLACE:DIST: 63.56 FT",
        "INFO:56-M --- he is not hurt -- he just needs help from to the help to the chairi",
        "DATE:12/24/12",
        "TIME:20:22:48");

    doTest("T63",
        "(Message Forwarded by PageGate) 6284 OLD STAGE HWY;DIFFICULTY BREATHING;THOMPSON LN;GREEN RUN LN;ASTHMA ATTACK HX OF THEM  [12/24/12 19:55:03 ADEBARGE]\n" +
        "59 F  [12/24/12 19:54:35 ADEBARGE]",

        "ADDR:6284 OLD STAGE HWY",
        "X:THOMPSON LN & GREEN RUN LN",
        "CALL:DIFFICULTY BREATHING",
        "INFO:ASTHMA ATTACK HX OF THEM / 59 F",
        "DATE:12/24/12",
        "TIME:19:55:03");

    doTest("T64",
        "(Message Forwarded by PageGate) 748 WRENN RD;C;STRUCTURE FIRE;W MAIN ST;STOVE IS ON FIRE  [12/24/12 17:25:06 BHUGHES]",
        "ADDR:748 WRENN RD",
        "X:W MAIN ST",
        "CALL:STRUCTURE FIRE",
        "APT:C",
        "INFO:STOVE IS ON FIRE",
        "DATE:12/24/12",
        "TIME:17:25:06");

    doTest("T65",
        "(Message Forwarded by PageGate) FYI: ;748 WRENN RD;C;STRUCTURE FIRE;W MAIN ST;STOVE IS ON FIRE  [12/24/12 17:25:06 BHUGHES]",
        "ADDR:748 WRENN RD",
        "X:W MAIN ST",
        "CALL:STRUCTURE FIRE",
        "APT:C",
        "INFO:STOVE IS ON FIRE",
        "DATE:12/24/12",
        "TIME:17:25:06");

    doTest("T66",
        "(Message Forwarded by PageGate) 4688 OLD STAGE HWY;DIFFICULTY BREATHING;JAMES WY;FORT HUGER DR;68 YO MALE\n" +
        "OXY AT 72\n" +
        "DIFFICULTY BREA\n" +
        "CONS/NO ALERT  [12/24/12 11:08:42 KROBERTS]",

        "ADDR:4688 OLD STAGE HWY",
        "X:JAMES WY & FORT HUGER DR",
        "CALL:DIFFICULTY BREATHING",
        "INFO:68 YO MALE OXY AT 72 DIFFICULTY BREA CONS/NO ALERT",
        "DATE:12/24/12",
        "TIME:11:08:42");

    doTest("T67",
        "(Message Forwarded by PageGate) 611 HILLCREST DR;UNCONSCIOUS OR FAINTING;QUAIL ST;SPRING DR;76 YO FEMALE\n" +
        "FELL UNCONS IN THE HALLWAY\n" +
        "UNRESPONSIVE\n" +
        "BREA  [12/24/12 10:36:29 KROBERTS]",

        "ADDR:611 HILLCREST DR",
        "X:QUAIL ST & SPRING DR",
        "CALL:UNCONSCIOUS OR FAINTING",
        "INFO:76 YO FEMALE FELL UNCONS IN THE HALLWAY UNRESPONSIVE BREA",
        "DATE:12/24/12",
        "TIME:10:36:29");

    doTest("T68",
        "(Message Forwarded by PageGate) FYI: ;611 HILLCREST DR;UNCONSCIOUS OR FAINTING;QUAIL ST;SPRING DR;76 YO FEMALE\n" +
        "FELL UNCONS IN THE HALLWAY\n" +
        "UNRESPONSIVE\n" +
        "BREA  [12/24/12 10:36:29 KROBERTS]",

        "ADDR:611 HILLCREST DR",
        "X:QUAIL ST & SPRING DR",
        "CALL:UNCONSCIOUS OR FAINTING",
        "INFO:76 YO FEMALE FELL UNCONS IN THE HALLWAY UNRESPONSIVE BREA",
        "DATE:12/24/12",
        "TIME:10:36:29");

    doTest("T69",
        "(Message Forwarded by PageGate) 1812 S CHURCH ST;RENAL ADVANTAGE DIALYSIS;SICK OR ILL OTHER RESCUE;MOORE AVE;ROUTE 10 BYPASS;51 YO FEMALE\n" +
        "SICK, DIZZY AND CONFUSED\n" +
        "CONS/BREA  [12/24/12 09:22:24 KROBERTS]",

        "ADDR:1812 S CHURCH ST",
        "X:MOORE AVE & ROUTE 10 BYPASS",
        "CALL:SICK OR ILL OTHER RESCUE",
        "PLACE:RENAL ADVANTAGE DIALYSIS",
        "INFO:51 YO FEMALE SICK, DIZZY AND CONFUSED CONS/BREA",
        "DATE:12/24/12",
        "TIME:09:22:24");

    doTest("T70",
        "(Message Forwarded by PageGate) 200 LUMAR RD;ROOM 40;RIVERSIDE CONVALESCENT CENTER;BLEEDING OR HEMORRHAGING;MOONEFIELD DR;73 YO MALE THROWING UP BLOOD  [12/24/12 08:09:43 AGOODWYN]",
        "ADDR:200 LUMAR RD",
        "APT:40",
        "X:MOONEFIELD DR",
        "CALL:BLEEDING OR HEMORRHAGING",
        "PLACE:RIVERSIDE CONVALESCENT CENTER",
        "INFO:73 YO MALE THROWING UP BLOOD",
        "DATE:12/24/12",
        "TIME:08:09:43");

    doTest("T71",
        "(Message Forwarded by PageGate) 5078 JAMES WY;MEDICAL ALARM;71 yo f severe arthritis pressed alert medical button but is not answering the care center.......annie jones 757-357-6689...  [12/24/12 00:01:34 CTILLMANN]",
        "ADDR:5078 JAMES WY",
        "CALL:MEDICAL ALARM",
        "INFO:71 yo f severe arthritis pressed alert medical button but is not answering the care center.......annie jones 757-357-6689...",
        "DATE:12/24/12",
        "TIME:00:01:34");

    doTest("T72",
        "(Message Forwarded by PageGate) 603 W MAIN ST;DIST: 138.71 FT;SEVEN ELEVEN;FALLS AND RELATED INJURIES;GREAT SPRING RD;MIDDLE ST;M FALL INTOX HIT HIS HEAD IS BLEEDING FROM THE HEAD. IS NOT CONC. IS BREATHING  [12/23/12 23:00:46 JESSICAB]",
        "ADDR:603 W MAIN ST",
        "PLACE:SEVEN ELEVEN - DIST: 138.71 FT",
        "CALL:FALLS AND RELATED INJURIES",
        "X:GREAT SPRING RD & MIDDLE ST",
        "INFO:M FALL INTOX HIT HIS HEAD IS BLEEDING FROM THE HEAD. IS NOT CONC. IS BREATHING",
        "DATE:12/23/12",
        "TIME:23:00:46");

    doTest("T73",
        "(Message Forwarded by PageGate) 13457 MELISSA DR;SICK OR ILL OTHER RESCUE;W BYRON DR;breathing is slow  [12/23/12 22:54:03 KBAKER]\n" +
        "6 month old female temp of 104.5,  [12/23/12 22:53:33 KBAKER]",

        "ADDR:13457 MELISSA DR",
        "X:W BYRON DR",
        "CALL:SICK OR ILL OTHER RESCUE",
        "INFO:breathing is slow / 6 month old female temp of 104.5,",
        "DATE:12/23/12",
        "TIME:22:54:03");

    doTest("T74",
        "(Message Forwarded by PageGate) 14052 WATER OAK DR;DIST: 28.64 FT;OVERDOSE;ENGLISH OAK DR;BLACK OAK DR;[M63-TRANSPORT] {M63} Beg Mileage: 26379  [12/23/12 22:07:52 BHUGHES]\n" +
        "CALLER WANTS TO MOVE HIM TO ANOTHER ADDRESS SO THAT THE RESIDENTS DO NOT GET INTO TROUBLE  [12/23/12 21:45:45 BHUGHES]\n" +
        "HARD TIME BREATHING. CALLER SAYS HE CANNOT KEEP HIS EYES OPEN  [12/23/12 21:44:08 BHUGHES]\n" +
        "16 YEAR OLD MALE HAS TAKEN MULTIPLE BOXES OF COLD MEDICINE  [12/23/12 21:43:24 BHUGHES]",

        "ADDR:14052 WATER OAK DR",
        "X:ENGLISH OAK DR & BLACK OAK DR",
        "CALL:OVERDOSE",
        "PLACE:DIST: 28.64 FT",
        "INFO:{M63} Beg Mileage: 26379 / CALLER WANTS TO MOVE HIM TO ANOTHER ADDRESS SO THAT THE RESIDENTS DO NOT GET INTO TROUBLE / HARD TIME BREATHING. CALLER SAYS HE CANNOT KEEP HIS EYES OPEN / 16 YEAR OLD MALE HAS TAKEN MULTIPLE BOXES OF COLD MEDICINE",
        "DATE:12/23/12",
        "TIME:22:07:52");

    doTest("T75",
        "(Message Forwarded by PageGate) FYI: ;14052 WATER OAK DR;DIST: 28.64 FT;OVERDOSE;ENGLISH OAK DR;BLACK OAK DR;16 YEAR OLD MALE HAS TAKEN MULTIPLE BOXES OF COLD MEDICINE  [12/23/12 21:43:24 BHUGHES]",
        "ADDR:14052 WATER OAK DR",
        "X:ENGLISH OAK DR & BLACK OAK DR",
        "CALL:OVERDOSE",
        "PLACE:DIST: 28.64 FT",
        "INFO:16 YEAR OLD MALE HAS TAKEN MULTIPLE BOXES OF COLD MEDICINE",
        "DATE:12/23/12",
        "TIME:21:43:24");

    doTest("T76",
        "(Message Forwarded by PageGate) 222 APPALOOSA WY;SICK OR ILL OTHER RESCUE;54 y/o female arms tingling and loosing muscle control in her arms  [12/23/12 17:34:08 KBAKER]",
        "ADDR:222 APPALOOSA WY",
        "CALL:SICK OR ILL OTHER RESCUE",
        "INFO:54 y/o female arms tingling and loosing muscle control in her arms",
        "DATE:12/23/12",
        "TIME:17:34:08");

    doTest("T77",
        "(Message Forwarded by PageGate) 108 SUNRISE BLUFF CT;PSYCHIATRIC PROBLEMS;SUNRISE BLUFF LN;[LAW] CALLER WOULD LIKE SOMEONE TO CHECK ON HIS WIFE. SHE HAS BOTTLES OF PILLS. UNSURE IF SHE TOOK THEM  [12/23/12 11:29:56 AGOODWYN]",
        "ADDR:108 SUNRISE BLUFF CT",
        "X:SUNRISE BLUFF LN",
        "CALL:PSYCHIATRIC PROBLEMS",
        "INFO:CALLER WOULD LIKE SOMEONE TO CHECK ON HIS WIFE. SHE HAS BOTTLES OF PILLS. UNSURE IF SHE TOOK THEM",
        "DATE:12/23/12",
        "TIME:11:29:56");

    doTest("T78",
        "(Message Forwarded by PageGate) Update: ;108 SUNRISE BLUFF CT;PSYCHIATRIC PROBLEMS;SUNRISE BLUFF LN",
        "ADDR:108 SUNRISE BLUFF CT",
        "X:SUNRISE BLUFF LN",
        "CALL:PSYCHIATRIC PROBLEMS");

    doTest("T79",
        "(Message Forwarded by PageGate) FYI: ;108 SUNRISE BLUFF CT;SUICIDE;SUNRISE BLUFF LN",
        "ADDR:108 SUNRISE BLUFF CT",
        "X:SUNRISE BLUFF LN",
        "CALL:SUICIDE");

    doTest("T80",
        "(Message Forwarded by PageGate) 735 WRENN RD;APT C;PAIN;W MAIN ST;tooth ache and vomitting\n" +
        "24 yo female\n" +
        "cons/brea  [12/23/12 10:30:06 KROBERTS]",

        "ADDR:735 WRENN RD",
        "APT:C",
        "X:W MAIN ST",
        "CALL:PAIN",
        "INFO:tooth ache and vomitting 24 yo female cons/brea",
        "DATE:12/23/12",
        "TIME:10:30:06");

    doTest("T81",
        "(Message Forwarded by PageGate) 304 EAST ST;DIFFICULTY BREATHING;W VIRGINIA AVE;80 YO FEMALE HAVING A HARD TIME BREATHING  [12/23/12 09:39:18 AGOODWYN]",
        "ADDR:304 EAST ST",
        "X:W VIRGINIA AVE",
        "CALL:DIFFICULTY BREATHING",
        "INFO:80 YO FEMALE HAVING A HARD TIME BREATHING",
        "DATE:12/23/12",
        "TIME:09:39:18");

    doTest("T82",
        "(Message Forwarded by PageGate) FYI: ;ASHBY WY W/BRITT WY;ACCIDENT UNKNOWN INJURIES",
        "ADDR:ASHBY WY W & BRITT WY",
        "CALL:ACCIDENT UNKNOWN INJURIES");

    doTest("T83",
        "(Message Forwarded by PageGate) 101 JOHN ROLFE DR;RM 112;MAGNOLIA MANOR;FALLS AND RELATED INJURIES;BREANN CT;ANDREWS XING;95 YO FEMALE FELL AND IS COMPLAINING OF PAIN IN LOWER HIP.  NOT COOPERATIVE. SENDING OUT FOR PAIN AND MENTAL STATUS CHANGE. POSSIBLE CONCUSSION. IS NOW NAUSEATED. PREFERENCE IS RIVERSIDE  [12/23/12 08:10:57 AGOODWYN]",
        "ADDR:101 JOHN ROLFE DR",
        "APT:112",
        "X:BREANN CT",
        "CALL:FALLS AND RELATED INJURIES",
        "PLACE:MAGNOLIA MANOR",
        "INFO:ANDREWS XING / 95 YO FEMALE FELL AND IS COMPLAINING OF PAIN IN LOWER HIP.  NOT COOPERATIVE. SENDING OUT FOR PAIN AND MENTAL STATUS CHANGE. POSSIBLE CONCUSSION. IS NOW NAUSEATED. PREFERENCE IS RIVERSIDE",
        "DATE:12/23/12",
        "TIME:08:10:57");

    doTest("T84",
        "(Message Forwarded by PageGate) FYI: ;13 LIBERTY AVE;DIST: 64.87 FT;UNCONSCIOUS OR FAINTING;BELLMONT AVE;MARTLETTE ST;Event spawned from CITIZEN ASSIST.  [12/23/2012 04:26:58 CHEDGEPETH]\n" +
        "{802W} HAVE MEDIC RESPOND HE IS UNRESPONSIVE  [12/23/12 04:26:40 CHEDGEPETH]\n" +
        "IS UNABLE TO GET HER HUSBAND TO OPEN THE BEDROOM DOOR. ADVISED THEY HAD A VERBAL ARGUEMENT EARLIER AND HE WENT IN THE BEDROOM AND LOCKED THE DOOR. NOW HE WILL NOT ANSWER THE CALLER OR OPEN THE DOOR.  [12/23/12 04:11:07 JESSICAB]",

        "ADDR:13 LIBERTY AVE",
        "X:BELLMONT AVE & MARTLETTE ST",
        "CALL:UNCONSCIOUS OR FAINTING",
        "PLACE:DIST: 64.87 FT",
        "INFO:Event spawned from CITIZEN ASSIST. / {802W} HAVE MEDIC RESPOND HE IS UNRESPONSIVE / IS UNABLE TO GET HER HUSBAND TO OPEN THE BEDROOM DOOR. ADVISED THEY HAD A VERBAL ARGUEMENT EARLIER AND HE WENT IN THE BEDROOM AND LOCKED THE DOOR. NOW HE WILL NOT ANSWER THE CALLER OR OPEN THE DOOR.",
        "DATE:12/23/2012",
        "TIME:04:26:58");

    doTest("T85",
        "(Message Forwarded by PageGate) Update: ;OLD STAGE HWY/BURWELLS BAY RD;DIST: 1134.26 FT;ACCIDENT UNKNOWN INJURIES;[LAW] CALLER STATED THERE WAS INJURIES  [12/22/12 18:02:01 BHUGHES]\n" +
        "[LAW] MR.BAILEY ADVISED IT WAS PAST THE OASIS  [12/22/12 18:01:50 BHUGHES]\n" +
        "[EMS] 517 IN ROUTE  [12/22/12 18:01:19 KHEWITT]\n" +
        "[LAW] 1/2 MILE NEAR WHERE THE PICKET FENCE STARTS  [12/22/12 18:00:13 BHUGHES]\n" +
        "[LAW] CALLER STATED THAT IT WAS ABOUT 1 MILE WEST OF OLD WRENNS MILL RD  [12/22/12 18:00:00 BHUGHES]\n" +
        "[LAW] CLOSE TO THE WHITE PICKET FENCE THERE VEH",

        "ADDR:OLD STAGE HWY & BURWELLS BAY RD",
        "PLACE:DIST: 1134.26 FT",
        "CALL:ACCIDENT UNKNOWN INJURIES",
        "INFO:CALLER STATED THERE WAS INJURIES / MR.BAILEY ADVISED IT WAS PAST THE OASIS / 517 IN ROUTE / 1/2 MILE NEAR WHERE THE PICKET FENCE STARTS / CALLER STATED THAT IT WAS ABOUT 1 MILE WEST OF OLD WRENNS MILL RD / CLOSE TO THE WHITE PICKET FENCE THERE VEH",
        "DATE:12/22/12",
        "TIME:18:02:01");

    doTest("T86",
        "(Message Forwarded by PageGate) OLD STAGE HWY/WRENNS MILL RD;DIST: 1134.26 FT;ACCIDENT UNKNOWN INJURIES",
        "ADDR:OLD STAGE HWY & WRENNS MILL RD",
        "PLACE:DIST: 1134.26 FT",
        "CALL:ACCIDENT UNKNOWN INJURIES");
 
  }
  
  @Test
  public void testWindsorFire() {

    doTest("T1",
        "(Message Forwarded by PageGate) 23352 COURTHOUSE HWY;CONSULATE HEALTH CARE WINDSOR;KENSINGTON CT;JOYNER TOWN LN;SMELL OR ODOR OF SMOKE;caller advised that there is a smoke inside the back side of the building near the laundry room. caller cant find where its coming from.  [12/27/12 23:29:46 SHILL]",
        "ADDR:23352 COURTHOUSE HWY",
        "X:KENSINGTON CT & JOYNER TOWN LN",
        "CALL:CONSULATE HEALTH CARE WINDSOR",
        "INFO:SMELL OR ODOR OF SMOKE / caller advised that there is a smoke inside the back side of the building near the laundry room. caller cant find where its coming from.",
        "DATE:12/27/12",
        "TIME:23:29:46");

    doTest("T2",
        "(Message Forwarded by PageGate) WALTERS HWY/DOUBLETREE LN;DIST: 1001.01 FT;1050;OWNER HAS CALLED BRINKLEYS WRECKER SERVICE FROM SUFFOLK, ETA LESS THAN 30 MINUTE. CAN BE REACHED AT 539-5511.  [12/26/12 15:47:05 DJONES]\n" +
        "veh flipped --- driver is fine and refusing to have a medic -- no airbags  [12/26/12 15:36:10 KHEWITT]\n" +
        ";FIRE",

        "ADDR:WALTERS HWY & DOUBLETREE LN",
        "CALL:1050",
        "PLACE:DIST: 1001.01 FT",
        "INFO:OWNER HAS CALLED BRINKLEYS WRECKER SERVICE FROM SUFFOLK, ETA LESS THAN 30 MINUTE. CAN BE REACHED AT 539-5511. / veh flipped --- driver is fine and refusing to have a medic -- no airbags / FIRE",
        "DATE:12/26/12",
        "TIME:15:47:05");

    doTest("T3",
        "(Message Forwarded by PageGate) WINDSOR BLVD/YELLOW HAMMER RD;ACCIDENT UNKNOWN INJURIES;[LAW] CAR IS OVERTURNED. WHITE IS THE ONLY DESCRIPTION SHE CAN GIVE.  [12/25/12 12:57:57 AGOODWYN]",
        "ADDR:WINDSOR BLVD & YELLOW HAMMER RD",
        "CALL:ACCIDENT UNKNOWN INJURIES",
        "INFO:CAR IS OVERTURNED. WHITE IS THE ONLY DESCRIPTION SHE CAN GIVE.",
        "DATE:12/25/12",
        "TIME:12:57:57");

  }
  
  public static void main(String[] args) {
    new VAIsleOfWightCountyParserTest().generateTests("T1");
  }
}