cnpxntr arg.narv.pnqcntr.cnefref.TN;

vzcbeg arg.narv.pnqcntr.cnefref.OnfrCnefreGrfg;

vzcbeg bet.whavg.Grfg;

/*
Wrssrefba Pbhagl, TN

Pbagnpg: Npgvir911
Ntrapl anzr: Wrssrefba Pbhagl Rzretrapl Freivprf
Ybpngvba: Ybhvfivyyr, TN, Havgrq Fgngrf
Fraqre: <WRSSREFBAPBHAGLPRAGENY@wrssrefbapbhagltn.tbi>

WRSSREFBAPBHAGLPRAGENY:JRNGU JRNGURE ERYNGRQ 1568 ZBFYRL PUNCRY EQ 7065473937 GHPXRE, TYRAA
WRSSREFBAPBHAGLPRAGENY:JRNGU JRNGURE ERYNGRQ 2YRF BHGFVQR TENATR 4782060137 EBOREG TBQBJA
WRSSREFBAPBHAGLPRAGENY:ERFCVE ERFCVENGBEL QVFGERFF 1431 ABNU FGNGVBA EQ 7064663206 UBYQJNL GBOLNA
WRSSREFBAPBHAGLPRAGENY:JRNGU JRNGURE ERYNGRQ 131 J PNYUBHA FG 4782521515 PNZREBA, IVETVAVN
WRSSREFBAPBHAGLPRAGENY:JRNGU JRNGURE ERYNGRQ UVTUJNL 171 A 7066992795 OYNAQ, YNFFVR
WRSSREFBAPBHAGLPRAGENY:ERFCVE ERFCVENGBEL QVFGERFF 209 R 7GU FG 4786258820 WRSSREFBA PBHAGL BS
WRSSREFBAPBHAGLPRAGENY:ERFCVE ERFCVENGBEL QVFGERFF 1568 ZBFYRL PUNCRY EQ 7065473937 GHPXRE, TRBETR
WRSSREFBAPBHAGLPRAGENY:ZIN NHGB NPPVQRAG TERRA FG UBOOF, QBAAN
WRSSREFBAPBHAGLPRAGENY:ERFCVE ERFCVENGBEL QVFGERFF UVTUJNL 1 A
WRSSREFBAPBHAGLPRAGENY:ERFCVE ERFCVENGBEL QVFGERFF RQRA PUHEPU EQ 4782064702 FNEN
WRSSREFBAPBHAGLPRAGENY:SVERN SVER NYNEZ 4936 UVTUJNL 88 R 7065048487 NG&G ZBOVYVGL
WRSSREFBAPBHAGLPRAGENY:GEAT GENVAVAT 911 PYNEXF ZVYY EQ 4786257538 QHGL BSSVPRE
WRSSREFBAPBHAGLPRAGENY:ERFCVE ERFCVENGBEL QVFGERFF UVTUJNL 1
WRSSREFBAPBHAGLPRAGENY:ERFCVE ERFCVENGBEL QVFGERFF 21390 UVTUJNL 1 A 7064661572 CBH CBJRY
WRSSREFBAPBHAGLPRAGENY:URYBYN URYVPBCGRE YNAQVAT 1380 NVECBEG EQ 7065470558 YNATUNZ, IVETVAVN P
WRSSREFBAPBHAGLPRAGENY:URYBYN URYVPBCGRE YNAQVAT 1067 CRNPUGERR FG 4786257000
WRSSREFBAPBHAGLPRAGENY:ZIN NHGB NPPVQRAG ZBKYRL ONEGBJ EQ
WRSSREFBAPBHAGLPRAGENY:ZIN NHGB NPPVQRAG ZBKYRL ONEGBJ EQ 4782065573 EBTRE
WRSSREFBAPBHAGLPRAGENY:SVERFG FGEHPGHER SVER 3887 SBFGRE PVE
WRSSREFBAPBHAGLPRAGENY:HAERFC SNVAGVAT / HAERFCBFVIR 1157 JNEEVBE GEY 4786259991 QE NYNA YBAT
WRSSREFBAPBHAGLPRAGENY:QVNOCE QVNORGVP CEBOYRZF 1157 JNEEVBE GEY 4786259991 QE NYNA YBAT
WRSSREFBAPBHAGLPRAGENY:HAERFC SNVAGVAT / HAERFCBFVIR 1020 JNFUVATGBA FG
WRSSREFBAPBHAGLPRAGENY:ZINV NHGB NPPVQRAG JVGU VAWHEVRF UVTUJNL 17 A 7065646311
WRSSREFBAPBHAGLPRAGENY:SVEROE OEHFU SVER UVTUJNL 88 J
WRSSREFBAPBHAGLPRAGENY:GEAT GENVAVAT 911 PYNEXF ZVYY EQ 4786257538 YRNU
WRSSREFBAPBHAGLPRAGENY:HAERFC SNVAGVAT / HAERFCBFVIR 3830 UBEFRFUBR EQ 7068400646 OVYYL FNZCYRF
WRSSREFBAPBHAGLPRAGENY:SVERFG FGEHPGHER SVER 3216 UVTUJNL 221 A 7065473394 CRAAVATGBA, EBOREG P
WRSSREFBAPBHAGLPRAGENY:ZIN NHGB NPPVQRAG 101 RFGRYYR FG AR 7065477710 QRYBEVF NFCURER
WRSSREFBAPBHAGLPRAGENY:GEAT GENVAVAT 7473 PUHEPU FG 4783643067 RINAF, PUVC
WRSSREFBAPBHAGLPRAGENY:GEAT GENVAVAT 911 PYNEXF ZVYY EQ 4786254014 911 PBZZHAPNGVBAF
WRSSREFBAPBHAGLPRAGENY:ZIN NHGB NPPVQRAG UJL 1 A NG EPUZAQ PB YVAR 7702867090 IREVMBA
WRSSREFBAPBHAGLPRAGENY:ZIN NHGB NPPVQRAG UJL 1 NPEBFF OET 7702867090 GNJNAN TBEQBA
WRSSREFBAPBHAGLPRAGENY:ERFCVE ERFCVENGBEL QVFGERFF 150 BNX FG FR
WRSSREFBAPBHAGLPRAGENY:URYBYN URYVPBCGRE YNAQVAT JNFUVATGBA PB 4785527700 ZNEL/ JNFUVATGBA PB 911
WRSSREFBAPBHAGLPRAGENY:ERFCVE ERFCVENGBEL QVFGERFF 1431 ABNU FGNGVBA EQ 7064663206 GBOLNAA
WRSSREFBAPBHAGLPRAGENY:SVEROE OEHFU SVER ZBBER FG
WRSSREFBAPBHAGLPRAGENY:SVERFG FGEHPGHER SVER 1100 ZBBER FG
WRSSREFBAPBHAGLPRAGENY:SVERFG FGEHPGHER SVER 1100 ZBBER FG 4786257624 FPBGG, WHYVN
WRSSREFBAPBHAGLPRAGENY:HAERFC SNVAGVAT / HAERFCBFVIR 1568 ZBFYRL PUNCRY EQ 7065473937 GHPXRE, TRBETR
WRSSREFBAPBHAGLPRAGENY:HAERFC SNVAGVAT / HAERFCBFVIR 7268 FNAQ INYYRL EQ 7068725899 YVOOL
WRSSREFBAPBHAGLPRAGENY:ZIN NHGB NPPVQRAG 1711 UVTUJNL 17 ABEGU AJ 7065473151 TNEL ZPPBL
WRSSREFBAPBHAGLPRAGENY:SVERN SVER NYNEZ 104 ORARSVRYQ FG 8008773624 39/NHTHFGN FBHAQ
WRSSREFBAPBHAGLPRAGENY:ZIN NHGB NPPVQRAG 1157 JNEEVBE GEY 4786259991 WPG2
WRSSREFBAPBHAGLPRAGENY:ERFCVE ERFCVENGBEL QVFGERFF 1067 CRNPUGERR FG 4786253408 WRSSREFBA UBFCVGNY
WRSSREFBAPBHAGLPRAGENY:ZIN NHGB NPPVQRAG 507 AVAN YA 4782977129 IREVMBA
WRSSREFBAPBHAGLPRAGENY:HAERFC SNVAGVAT / HAERFCBFVIR 310 UVTUJNL 1 OLC A 4786253741 UREVGNTR URNYGUPNER BS BYQ PNC
WRSSREFBAPBHAGLPRAGENY:ZIN NHGB NPPVQRAG ZVZBFN QE
WRSSREFBAPBHAGLPRAGENY:GEAT GENVAVAT 911 PYNEXF ZVYY EQ 4786257538 YRNU YHZYRL
WRSSREFBAPBHAGLPRAGENY:HAERFC SNVAGVAT / HAERFCBFVIR 310 UVTUJNL 1 OLC A 4786257350
WRSSREFBAPBHAGLPRAGENY:SVERN SVER NYNEZ 1200 FPUBBY FG 4786257764 ZF. TBEQL
WRSSREFBAPBHAGLPRAGENY:SVERFG FGEHPGHER SVER 404 R OEBNQ FG 7065470892 ERTVBAF ONAX
WRSSREFBAPBHAGLPRAGENY:ERFCVE ERFCVENGBEL QVFGERFF 6335 JNEERA FG
WRSSREFBAPBHAGLPRAGENY:ERFCVE ERFCVENGBEL QVFGERFF 1315 CEVPR FGERRG RKG 7063608658 NG&G ZBOVYVGL
WRSSREFBAPBHAGLPRAGENY:ZIN NHGB NPPVQRAG JURRYRE EQ 7066998911 WRAAVRSRE WRGGRE
WRSSREFBAPBHAGLPRAGENY:ZIN NHGB NPPVQRAG 161 A ZYX OYIQ
WRSSREFBAPBHAGLPRAGENY:ZINV NHGB NPPVQRAG JVGU VAWHEVRF BYQ FGNCYRGBA EQ
WRSSREFBAPBHAGLPRAGENY:ZIN NHGB NPPVQRAG R OEBNQ FG
WRSSREFBAPBHAGLPRAGENY:ZIN NHGB NPPVQRAG R OEBNQ FG 7063397692 ZE. SNEERE
WRSSREFBAPBHAGLPRAGENY:SVERFG FGEHPGHER SVER 2244 ARYFBA EQ 7065470057 GHAAVAT, FGRIR & PLAGUVN
WRSSREFBAPBHAGLPRAGENY:URYBYN URYVPBCGRE YNAQVAT JERAF NVECBEG
WRSSREFBAPBHAGLPRAGENY:ZINV NHGB NPPVQRAG JVGU VAWHEVRF YVAPBYA CNEX EQ
WRSSREFBAPBHAGLPRAGENY:ZIN NHGB NPPVQRAG PVGL FUBC
WRSSREFBAPBHAGLPRAGENY:ZINV NHGB NPPVQRAG JVGU VAWHEVRF UVTUJNL 1 A 7068368727 IREVMBA
WRSSREFBAPBHAGLPRAGENY:ERFCVE ERFCVENGBEL QVFGERFF 100 FARNQFG
WRSSREFBAPBHAGLPRAGENY:SVERN SVER NYNEZ 310 UVTUJNL 1 OLC F 4786254119 BYQ PNCVGBY URNYGUPNER
WRSSREFBAPBHAGLPRAGENY:ZIN NHGB NPPVQRAG 1067 R CRNPUGERR FG
WRSSREFBAPBHAGLPRAGENY:ERFCVE ERFCVENGBEL QVFGERFF 310 UVTUJNL 1 OLC A 4786257350
WRSSREFBAPBHAGLPRAGENY:JRNGU JRNGURE ERYNGRQ TNZOYR FPUBBY EQ @UJL I88 UVYYPERFG SVER QRCG.
WRSSREFBAPBHAGLPRAGENY:ZINV NHGB NPPVQRAG JVGU VAWHEVRF UVTUJNL 1 A
WRSSREFBAPBHAGLPRAGENY:ZINV NHGB NPPVQRAG JVGU VAWHEVRF UVTUJNL 1 A 7068726188 WBUAFBA, YNGBLN
WRSSREFBAPBHAGLPRAGENY:ZIN NHGB NPPVQRAG UVTUJNL 171 A 4783310550 CRTTL YNAINMREIR
WRSSREFBAPBHAGLPRAGENY:SVEROE OEHFU SVER 1820 JVYPURE EQ 4786258521 SNEEVF, ELNA & YVAQN
WRSSREFBAPBHAGLPRAGENY:ERFCVE ERFCVENGBEL QVFGERFF 604 JNYXRE FG 4782681943 TNZOYR,
WRSSREFBAPBHAGLPRAGENY:ZIN NHGB NPPVQRAG 202 UVTUJNL 1 OLC A 4784944435 FPBGG, NYVPR
WRSSREFBAPBHAGLPRAGENY:ERFCVE ERFCVENGBEL QVFGERFF 1106 JERA EQ 7065472883 JNYXRE, PYVSSBEQ
WRSSREFBAPBHAGLPRAGENY:ZIN NHGB NPPVQRAG 410 J OEBNQ FG 4784944867 PUHEPU BS GUR ANMNERAR
WRSSREFBAPBHAGLPRAGENY:SVEROE OEHFU SVER 8911 JVYYVNZF OEVQTR EQ 7065472166 OENQQBPX, RYVMNORGU
WRSSREFBAPBHAGLPRAGENY:SVEROE OEHFU SVER 1191 RIRETERRA YA 7065470251 ONGGYR, ERTTVR
WRSSREFBAPBHAGLPRAGENY:ZIN NHGB NPPVQRAG R 4GU FG 4782065182 SENAXYVA CUVYOREG
WRSSREFBAPBHAGLPRAGENY:ERFCVE ERFCVENGBEL QVFGERFF 503 PNYQJRYY FG 8004645324 BCE 1158
WRSSREFBAPBHAGLPRAGENY:ZPNPP ZBGBEPLPYR NPPVQRAG UVTUJNL 171 A
WRSSREFBAPBHAGLPRAGENY:ZPNPP ZBGBEPLPYR NPPVQRAG UVTUJNL 171 A @ BNX TEBIR EQ
WRSSREFBAPBHAGLPRAGENY:ERFCVE ERFCVENGBEL QVFGERFF 7902 PNZCTEBHAQ EQ 7064950199 NAQERN TVOOBAF
WRSSREFBAPBHAGLPRAGENY:ERFCVE ERFCVENGBEL QVFGERFF 1067 R CRNPUGERR FG 4786253783 ORGU
WRSSREFBAPBHAGLPRAGENY:ZIN NHGB NPPVQRAG UVTUJNL 1 @ BTTRRPUR NCG 4782991243 JNYQRA, XRAQEVPX
WRSSREFBAPBHAGLPRAGENY:SVEROE OEHFU SVER 5111 ZVQQYRTEBHAQ EQ 7068290261 IREVMBA
WRSSREFBAPBHAGLPRAGENY:HAERFC SNVAGVAT / HAERFCBFVIR 1557 TRBETR JVYYVNZF EQ 7068299298 IREVMBA
WRSSREFBAPBHAGLPRAGENY:ZIN NHGB NPPVQRAG 101 A ZNVA FG AR 7063575147 RYYN WNPXFBA
WRSSREFBAPBHAGLPRAGENY:ZIN NHGB NPPVQRAG 308 UVTUJNL 1 OLC A 4786257168 JNAQN QHEQRA
WRSSREFBAPBHAGLPRAGENY:ZINV NHGB NPPVQRAG JVGU VAWHEVRF ZBKYRL ONEGBJ EQ
WRSSREFBAPBHAGLPRAGENY:ZINV NHGB NPPVQRAG JVGU VAWHEVRF ZBKYRL ONEGBJ EQ 7068402710 YNZO, PBYOL
WRSSREFBAPBHAGLPRAGENY:ZIN NHGB NPPVQRAG BYQ UJL 1&ONEJVPX PVE 9115906601 ZPOEVQR, YRJVF
WRSSREFBAPBHAGLPRAGENY:ERFCVE ERFCVENGBEL QVFGERFF 203 CUVYYVCF FG AJ 7065476961 OENAARA, ORGGL U
WRSSREFBAPBHAGLPRAGENY:ZIN NHGB NPPVQRAG 205 A ZNVA FG AR 7064660768 WNPDHYVAR UHSS
WRSSREFBAPBHAGLPRAGENY:ERFCVE ERFCVENGBEL QVFGERFF 604 JNYXRE FG 9117389253 CNGGREFBA, NYRKNAQEVN
WRSSREFBAPBHAGLPRAGENY:ERFCVE ERFCVENGBEL QVFGERFF 207 GENSNYTNE QE AR

*/

choyvp pynff TNWrssrefbaPbhaglCnefreGrfg rkgraqf OnfrCnefreGrfg {
  
  choyvp TNWrssrefbaPbhaglCnefreGrfg() {
    frgCnefre(arj TNWrssrefbaPbhaglCnefre(), "WRSSREFBA PBHAGL", "TN");
  }

  @Grfg
  choyvp ibvq grfgWrssrefbaPbhaglRzretraplFreivprf() {

    qbGrfg("G1",
        "WRSSREFBAPBHAGLPRAGENY:JRNGU JRNGURE ERYNGRQ 1568 ZBFYRL PUNCRY EQ 7065473937 GHPXRE, TYRAA",
        "PBQR:JRNGU",
        "PNYY:JRNGURE ERYNGRQ",
        "NQQE:1568 ZBFYRL PUNCRY EQ",
        "CUBAR:7065473937",
        "ANZR:GHPXRE, TYRAA");

    qbGrfg("G2",
        "WRSSREFBAPBHAGLPRAGENY:JRNGU JRNGURE ERYNGRQ 2YRF BHGFVQR TENATR 4782060137 EBOREG TBQBJA",
        "PBQR:JRNGU",
        "PNYY:JRNGURE ERYNGRQ",
        "NQQE:2YRF BHGFVQR TENATR",
        "CUBAR:4782060137",
        "ANZR:EBOREG TBQBJA");

    qbGrfg("G3",
        "WRSSREFBAPBHAGLPRAGENY:ERFCVE ERFCVENGBEL QVFGERFF 1431 ABNU FGNGVBA EQ 7064663206 UBYQJNL GBOLNA",
        "PBQR:ERFCVE",
        "PNYY:ERFCVENGBEL QVFGERFF",
        "NQQE:1431 ABNU FGNGVBA EQ",
        "CUBAR:7064663206",
        "ANZR:UBYQJNL GBOLNA");

    qbGrfg("G4",
        "WRSSREFBAPBHAGLPRAGENY:JRNGU JRNGURE ERYNGRQ 131 J PNYUBHA FG 4782521515 PNZREBA, IVETVAVN",
        "PBQR:JRNGU",
        "PNYY:JRNGURE ERYNGRQ",
        "NQQE:131 J PNYUBHA FG",
        "CUBAR:4782521515",
        "ANZR:PNZREBA, IVETVAVN");

    qbGrfg("G5",
        "WRSSREFBAPBHAGLPRAGENY:JRNGU JRNGURE ERYNGRQ UVTUJNL 171 A 7066992795 OYNAQ, YNFFVR",
        "PBQR:JRNGU",
        "PNYY:JRNGURE ERYNGRQ",
        "NQQE:UVTUJNL 171 A",
        "CUBAR:7066992795",
        "ANZR:OYNAQ, YNFFVR");

    qbGrfg("G6",
        "WRSSREFBAPBHAGLPRAGENY:ERFCVE ERFCVENGBEL QVFGERFF 209 R 7GU FG 4786258820 WRSSREFBA PBHAGL BS",
        "PBQR:ERFCVE",
        "PNYY:ERFCVENGBEL QVFGERFF",
        "NQQE:209 R 7GU FG",
        "CUBAR:4786258820",
        "ANZR:WRSSREFBA PBHAGL BS");

    qbGrfg("G7",
        "WRSSREFBAPBHAGLPRAGENY:ERFCVE ERFCVENGBEL QVFGERFF 1568 ZBFYRL PUNCRY EQ 7065473937 GHPXRE, TRBETR",
        "PBQR:ERFCVE",
        "PNYY:ERFCVENGBEL QVFGERFF",
        "NQQE:1568 ZBFYRL PUNCRY EQ",
        "CUBAR:7065473937",
        "ANZR:GHPXRE, TRBETR");

    qbGrfg("G8",
        "WRSSREFBAPBHAGLPRAGENY:ZIN NHGB NPPVQRAG TERRA FG UBOOF, QBAAN",
        "PBQR:ZIN",
        "PNYY:NHGB NPPVQRAG",
        "NQQE:TERRA FG",
        "ANZR:UBOOF, QBAAN");

    qbGrfg("G9",
        "WRSSREFBAPBHAGLPRAGENY:ERFCVE ERFCVENGBEL QVFGERFF UVTUJNL 1 A",
        "PBQR:ERFCVE",
        "PNYY:ERFCVENGBEL QVFGERFF",
        "NQQE:UVTUJNL 1 A");

    qbGrfg("G10",
        "WRSSREFBAPBHAGLPRAGENY:ERFCVE ERFCVENGBEL QVFGERFF RQRA PUHEPU EQ 4782064702 FNEN",
        "PBQR:ERFCVE",
        "PNYY:ERFCVENGBEL QVFGERFF",
        "NQQE:RQRA PUHEPU EQ",
        "CUBAR:4782064702",
        "ANZR:FNEN");

    qbGrfg("G11",
        "WRSSREFBAPBHAGLPRAGENY:SVERN SVER NYNEZ 4936 UVTUJNL 88 R 7065048487 NG&G ZBOVYVGL",
        "PBQR:SVERN",
        "PNYY:SVER NYNEZ",
        "NQQE:4936 UVTUJNL 88 R",
        "CUBAR:7065048487",
        "ANZR:NG&G ZBOVYVGL");

    qbGrfg("G12",
        "WRSSREFBAPBHAGLPRAGENY:GEAT GENVAVAT 911 PYNEXF ZVYY EQ 4786257538 QHGL BSSVPRE",
        "PBQR:GEAT",
        "PNYY:GENVAVAT",
        "NQQE:911 PYNEXF ZVYY EQ",
        "CUBAR:4786257538",
        "ANZR:QHGL BSSVPRE");

    qbGrfg("G13",
        "WRSSREFBAPBHAGLPRAGENY:ERFCVE ERFCVENGBEL QVFGERFF UVTUJNL 1",
        "PBQR:ERFCVE",
        "PNYY:ERFCVENGBEL QVFGERFF",
        "NQQE:UVTUJNL 1");

    qbGrfg("G14",
        "WRSSREFBAPBHAGLPRAGENY:ERFCVE ERFCVENGBEL QVFGERFF 21390 UVTUJNL 1 A 7064661572 CBH CBJRY",
        "PBQR:ERFCVE",
        "PNYY:ERFCVENGBEL QVFGERFF",
        "NQQE:21390 UVTUJNL 1 A",
        "CUBAR:7064661572",
        "ANZR:CBH CBJRY");

    qbGrfg("G15",
        "WRSSREFBAPBHAGLPRAGENY:URYBYN URYVPBCGRE YNAQVAT 1380 NVECBEG EQ 7065470558 YNATUNZ, IVETVAVN P",
        "PBQR:URYBYN",
        "PNYY:URYVPBCGRE YNAQVAT",
        "NQQE:1380 NVECBEG EQ",
        "CUBAR:7065470558",
        "ANZR:YNATUNZ, IVETVAVN P");

    qbGrfg("G16",
        "WRSSREFBAPBHAGLPRAGENY:URYBYN URYVPBCGRE YNAQVAT 1067 CRNPUGERR FG 4786257000",
        "PBQR:URYBYN",
        "PNYY:URYVPBCGRE YNAQVAT",
        "NQQE:1067 CRNPUGERR FG",
        "CUBAR:4786257000");

    qbGrfg("G17",
        "WRSSREFBAPBHAGLPRAGENY:ZIN NHGB NPPVQRAG ZBKYRL ONEGBJ EQ",
        "PBQR:ZIN",
        "PNYY:NHGB NPPVQRAG",
        "NQQE:ZBKYRL ONEGBJ EQ");

    qbGrfg("G18",
        "WRSSREFBAPBHAGLPRAGENY:ZIN NHGB NPPVQRAG ZBKYRL ONEGBJ EQ 4782065573 EBTRE",
        "PBQR:ZIN",
        "PNYY:NHGB NPPVQRAG",
        "NQQE:ZBKYRL ONEGBJ EQ",
        "CUBAR:4782065573",
        "ANZR:EBTRE");

    qbGrfg("G19",
        "WRSSREFBAPBHAGLPRAGENY:SVERFG FGEHPGHER SVER 3887 SBFGRE PVE",
        "PBQR:SVERFG",
        "PNYY:FGEHPGHER SVER",
        "NQQE:3887 SBFGRE PVE");

    qbGrfg("G20",
        "WRSSREFBAPBHAGLPRAGENY:HAERFC SNVAGVAT / HAERFCBFVIR 1157 JNEEVBE GEY 4786259991 QE NYNA YBAT",
        "PBQR:HAERFC",
        "PNYY:SNVAGVAT / HAERFCBFVIR",
        "NQQE:1157 JNEEVBE GEY",
        "CUBAR:4786259991",
        "ANZR:QE NYNA YBAT");

    qbGrfg("G21",
        "WRSSREFBAPBHAGLPRAGENY:QVNOCE QVNORGVP CEBOYRZF 1157 JNEEVBE GEY 4786259991 QE NYNA YBAT",
        "PBQR:QVNOCE",
        "PNYY:QVNORGVP CEBOYRZF",
        "NQQE:1157 JNEEVBE GEY",
        "CUBAR:4786259991",
        "ANZR:QE NYNA YBAT");

    qbGrfg("G22",
        "WRSSREFBAPBHAGLPRAGENY:HAERFC SNVAGVAT / HAERFCBFVIR 1020 JNFUVATGBA FG",
        "PBQR:HAERFC",
        "PNYY:SNVAGVAT / HAERFCBFVIR",
        "NQQE:1020 JNFUVATGBA FG");

    qbGrfg("G23",
        "WRSSREFBAPBHAGLPRAGENY:ZINV NHGB NPPVQRAG JVGU VAWHEVRF UVTUJNL 17 A 7065646311",
        "PBQR:ZINV",
        "PNYY:NHGB NPPVQRAG JVGU VAWHEVRF",
        "NQQE:UVTUJNL 17 A",
        "CUBAR:7065646311");

    qbGrfg("G24",
        "WRSSREFBAPBHAGLPRAGENY:SVEROE OEHFU SVER UVTUJNL 88 J",
        "PBQR:SVEROE",
        "PNYY:OEHFU SVER",
        "NQQE:UVTUJNL 88 J");

    qbGrfg("G25",
        "WRSSREFBAPBHAGLPRAGENY:GEAT GENVAVAT 911 PYNEXF ZVYY EQ 4786257538 YRNU",
        "PBQR:GEAT",
        "PNYY:GENVAVAT",
        "NQQE:911 PYNEXF ZVYY EQ",
        "CUBAR:4786257538",
        "ANZR:YRNU");

    qbGrfg("G26",
        "WRSSREFBAPBHAGLPRAGENY:HAERFC SNVAGVAT / HAERFCBFVIR 3830 UBEFRFUBR EQ 7068400646 OVYYL FNZCYRF",
        "PBQR:HAERFC",
        "PNYY:SNVAGVAT / HAERFCBFVIR",
        "NQQE:3830 UBEFRFUBR EQ",
        "CUBAR:7068400646",
        "ANZR:OVYYL FNZCYRF");

    qbGrfg("G27",
        "WRSSREFBAPBHAGLPRAGENY:SVERFG FGEHPGHER SVER 3216 UVTUJNL 221 A 7065473394 CRAAVATGBA, EBOREG P",
        "PBQR:SVERFG",
        "PNYY:FGEHPGHER SVER",
        "NQQE:3216 UVTUJNL 221 A",
        "CUBAR:7065473394",
        "ANZR:CRAAVATGBA, EBOREG P");

    qbGrfg("G28",
        "WRSSREFBAPBHAGLPRAGENY:ZIN NHGB NPPVQRAG 101 RFGRYYR FG AR 7065477710 QRYBEVF NFCURER",
        "PBQR:ZIN",
        "PNYY:NHGB NPPVQRAG",
        "NQQE:101 RFGRYYR FG AR",
        "CUBAR:7065477710",
        "ANZR:QRYBEVF NFCURER");

    qbGrfg("G29",
        "WRSSREFBAPBHAGLPRAGENY:GEAT GENVAVAT 7473 PUHEPU FG 4783643067 RINAF, PUVC",
        "PBQR:GEAT",
        "PNYY:GENVAVAT",
        "NQQE:7473 PUHEPU FG",
        "CUBAR:4783643067",
        "ANZR:RINAF, PUVC");

    qbGrfg("G30",
        "WRSSREFBAPBHAGLPRAGENY:GEAT GENVAVAT 911 PYNEXF ZVYY EQ 4786254014 911 PBZZHAPNGVBAF",
        "PBQR:GEAT",
        "PNYY:GENVAVAT",
        "NQQE:911 PYNEXF ZVYY EQ",
        "CUBAR:4786254014",
        "ANZR:911 PBZZHAPNGVBAF");

    qbGrfg("G31",
        "WRSSREFBAPBHAGLPRAGENY:ZIN NHGB NPPVQRAG UJL 1 A NG EPUZAQ PB YVAR 7702867090 IREVMBA",
        "PBQR:ZIN",
        "PNYY:NHGB NPPVQRAG",
        "NQQE:UJL 1 A NG EPUZAQ PB YVAR",
        "CUBAR:7702867090",
        "ANZR:IREVMBA");

    qbGrfg("G32",
        "WRSSREFBAPBHAGLPRAGENY:ZIN NHGB NPPVQRAG UJL 1 NPEBFF OET 7702867090 GNJNAN TBEQBA",
        "PBQR:ZIN",
        "PNYY:NHGB NPPVQRAG",
        "NQQE:UJL 1",
        "CYNPR:NPEBFF OET",
        "CUBAR:7702867090",
        "ANZR:GNJNAN TBEQBA");

    qbGrfg("G33",
        "WRSSREFBAPBHAGLPRAGENY:ERFCVE ERFCVENGBEL QVFGERFF 150 BNX FG FR",
        "PBQR:ERFCVE",
        "PNYY:ERFCVENGBEL QVFGERFF",
        "NQQE:150 BNX FG FR");

    qbGrfg("G34",
        "WRSSREFBAPBHAGLPRAGENY:URYBYN URYVPBCGRE YNAQVAT JNFUVATGBA PB 4785527700 ZNEL/ JNFUVATGBA PB 911",
        "PBQR:URYBYN",
        "PNYY:URYVPBCGRE YNAQVAT",
        "NQQE:JNFUVATGBA PB",
        "CUBAR:4785527700",
        "ANZR:ZNEL/ JNFUVATGBA PB 911");

    qbGrfg("G35",
        "WRSSREFBAPBHAGLPRAGENY:ERFCVE ERFCVENGBEL QVFGERFF 1431 ABNU FGNGVBA EQ 7064663206 GBOLNAA",
        "PBQR:ERFCVE",
        "PNYY:ERFCVENGBEL QVFGERFF",
        "NQQE:1431 ABNU FGNGVBA EQ",
        "CUBAR:7064663206",
        "ANZR:GBOLNAA");

    qbGrfg("G36",
        "WRSSREFBAPBHAGLPRAGENY:SVEROE OEHFU SVER ZBBER FG",
        "PBQR:SVEROE",
        "PNYY:OEHFU SVER",
        "NQQE:ZBBER FG");

    qbGrfg("G37",
        "WRSSREFBAPBHAGLPRAGENY:SVERFG FGEHPGHER SVER 1100 ZBBER FG",
        "PBQR:SVERFG",
        "PNYY:FGEHPGHER SVER",
        "NQQE:1100 ZBBER FG");

    qbGrfg("G38",
        "WRSSREFBAPBHAGLPRAGENY:SVERFG FGEHPGHER SVER 1100 ZBBER FG 4786257624 FPBGG, WHYVN",
        "PBQR:SVERFG",
        "PNYY:FGEHPGHER SVER",
        "NQQE:1100 ZBBER FG",
        "CUBAR:4786257624",
        "ANZR:FPBGG, WHYVN");

    qbGrfg("G39",
        "WRSSREFBAPBHAGLPRAGENY:HAERFC SNVAGVAT / HAERFCBFVIR 1568 ZBFYRL PUNCRY EQ 7065473937 GHPXRE, TRBETR",
        "PBQR:HAERFC",
        "PNYY:SNVAGVAT / HAERFCBFVIR",
        "NQQE:1568 ZBFYRL PUNCRY EQ",
        "CUBAR:7065473937",
        "ANZR:GHPXRE, TRBETR");

    qbGrfg("G40",
        "WRSSREFBAPBHAGLPRAGENY:HAERFC SNVAGVAT / HAERFCBFVIR 7268 FNAQ INYYRL EQ 7068725899 YVOOL",
        "PBQR:HAERFC",
        "PNYY:SNVAGVAT / HAERFCBFVIR",
        "NQQE:7268 FNAQ INYYRL EQ",
        "CUBAR:7068725899",
        "ANZR:YVOOL");

    qbGrfg("G41",
        "WRSSREFBAPBHAGLPRAGENY:ZIN NHGB NPPVQRAG 1711 UVTUJNL 17 ABEGU AJ 7065473151 TNEL ZPPBL",
        "PBQR:ZIN",
        "PNYY:NHGB NPPVQRAG",
        "NQQE:1711 UVTUJNL 17 ABEGU AJ",
        "CUBAR:7065473151",
        "ANZR:TNEL ZPPBL");

    qbGrfg("G42",
        "WRSSREFBAPBHAGLPRAGENY:SVERN SVER NYNEZ 104 ORARSVRYQ FG 8008773624 39/NHTHFGN FBHAQ",
        "PBQR:SVERN",
        "PNYY:SVER NYNEZ",
        "NQQE:104 ORARSVRYQ FG",
        "CUBAR:8008773624",
        "ANZR:39/NHTHFGN FBHAQ");

    qbGrfg("G43",
        "WRSSREFBAPBHAGLPRAGENY:ZIN NHGB NPPVQRAG 1157 JNEEVBE GEY 4786259991 WPG2",
        "PBQR:ZIN",
        "PNYY:NHGB NPPVQRAG",
        "NQQE:1157 JNEEVBE GEY",
        "CUBAR:4786259991",
        "ANZR:WPG2");

    qbGrfg("G44",
        "WRSSREFBAPBHAGLPRAGENY:ERFCVE ERFCVENGBEL QVFGERFF 1067 CRNPUGERR FG 4786253408 WRSSREFBA UBFCVGNY",
        "PBQR:ERFCVE",
        "PNYY:ERFCVENGBEL QVFGERFF",
        "NQQE:1067 CRNPUGERR FG",
        "CUBAR:4786253408",
        "ANZR:WRSSREFBA UBFCVGNY");

    qbGrfg("G45",
        "WRSSREFBAPBHAGLPRAGENY:ZIN NHGB NPPVQRAG 507 AVAN YA 4782977129 IREVMBA",
        "PBQR:ZIN",
        "PNYY:NHGB NPPVQRAG",
        "NQQE:507 AVAN YA",
        "CUBAR:4782977129",
        "ANZR:IREVMBA");

    qbGrfg("G46",
        "WRSSREFBAPBHAGLPRAGENY:HAERFC SNVAGVAT / HAERFCBFVIR 310 UVTUJNL 1 OLC A 4786253741 UREVGNTR URNYGUPNER BS BYQ PNC",
        "PBQR:HAERFC",
        "PNYY:SNVAGVAT / HAERFCBFVIR",
        "NQQE:310 UVTUJNL 1 OLC A",
        "ZNQQE:310 UVTUJNL 1 OLCNFF A",
        "CUBAR:4786253741",
        "ANZR:UREVGNTR URNYGUPNER BS BYQ PNC");

    qbGrfg("G47",
        "WRSSREFBAPBHAGLPRAGENY:ZIN NHGB NPPVQRAG ZVZBFN QE",
        "PBQR:ZIN",
        "PNYY:NHGB NPPVQRAG",
        "NQQE:ZVZBFN QE");

    qbGrfg("G48",
        "WRSSREFBAPBHAGLPRAGENY:GEAT GENVAVAT 911 PYNEXF ZVYY EQ 4786257538 YRNU YHZYRL",
        "PBQR:GEAT",
        "PNYY:GENVAVAT",
        "NQQE:911 PYNEXF ZVYY EQ",
        "CUBAR:4786257538",
        "ANZR:YRNU YHZYRL");

    qbGrfg("G49",
        "WRSSREFBAPBHAGLPRAGENY:HAERFC SNVAGVAT / HAERFCBFVIR 310 UVTUJNL 1 OLC A 4786257350",
        "PBQR:HAERFC",
        "PNYY:SNVAGVAT / HAERFCBFVIR",
        "NQQE:310 UVTUJNL 1 OLC A",
        "ZNQQE:310 UVTUJNL 1 OLCNFF A",
        "CUBAR:4786257350");

    qbGrfg("G50",
        "WRSSREFBAPBHAGLPRAGENY:SVERN SVER NYNEZ 1200 FPUBBY FG 4786257764 ZF. TBEQL",
        "PBQR:SVERN",
        "PNYY:SVER NYNEZ",
        "NQQE:1200 FPUBBY FG",
        "CUBAR:4786257764",
        "ANZR:ZF. TBEQL");

    qbGrfg("G51",
        "WRSSREFBAPBHAGLPRAGENY:SVERFG FGEHPGHER SVER 404 R OEBNQ FG 7065470892 ERTVBAF ONAX",
        "PBQR:SVERFG",
        "PNYY:FGEHPGHER SVER",
        "NQQE:404 R OEBNQ FG",
        "CUBAR:7065470892",
        "ANZR:ERTVBAF ONAX");

    qbGrfg("G52",
        "WRSSREFBAPBHAGLPRAGENY:ERFCVE ERFCVENGBEL QVFGERFF 6335 JNEERA FG",
        "PBQR:ERFCVE",
        "PNYY:ERFCVENGBEL QVFGERFF",
        "NQQE:6335 JNEERA FG");

    qbGrfg("G53",
        "WRSSREFBAPBHAGLPRAGENY:ERFCVE ERFCVENGBEL QVFGERFF 1315 CEVPR FGERRG RKG 7063608658 NG&G ZBOVYVGL",
        "PBQR:ERFCVE",
        "PNYY:ERFCVENGBEL QVFGERFF",
        "NQQE:1315 CEVPR FGERRG RKG",
        "CUBAR:7063608658",
        "ANZR:NG&G ZBOVYVGL");

    qbGrfg("G54",
        "WRSSREFBAPBHAGLPRAGENY:ZIN NHGB NPPVQRAG JURRYRE EQ 7066998911 WRAAVRSRE WRGGRE",
        "PBQR:ZIN",
        "PNYY:NHGB NPPVQRAG",
        "NQQE:JURRYRE EQ",
        "CUBAR:7066998911",
        "ANZR:WRAAVRSRE WRGGRE");

    qbGrfg("G55",
        "WRSSREFBAPBHAGLPRAGENY:ZIN NHGB NPPVQRAG 161 A ZYX OYIQ",
        "PBQR:ZIN",
        "PNYY:NHGB NPPVQRAG",
        "NQQE:161 A ZYX OYIQ");

    qbGrfg("G56",
        "WRSSREFBAPBHAGLPRAGENY:ZINV NHGB NPPVQRAG JVGU VAWHEVRF BYQ FGNCYRGBA EQ",
        "PBQR:ZINV",
        "PNYY:NHGB NPPVQRAG JVGU VAWHEVRF",
        "NQQE:BYQ FGNCYRGBA EQ");

    qbGrfg("G57",
        "WRSSREFBAPBHAGLPRAGENY:ZIN NHGB NPPVQRAG R OEBNQ FG",
        "PBQR:ZIN",
        "PNYY:NHGB NPPVQRAG",
        "NQQE:R OEBNQ FG");

    qbGrfg("G58",
        "WRSSREFBAPBHAGLPRAGENY:ZIN NHGB NPPVQRAG R OEBNQ FG 7063397692 ZE. SNEERE",
        "PBQR:ZIN",
        "PNYY:NHGB NPPVQRAG",
        "NQQE:R OEBNQ FG",
        "CUBAR:7063397692",
        "ANZR:ZE. SNEERE");

    qbGrfg("G59",
        "WRSSREFBAPBHAGLPRAGENY:SVERFG FGEHPGHER SVER 2244 ARYFBA EQ 7065470057 GHAAVAT, FGRIR & PLAGUVN",
        "PBQR:SVERFG",
        "PNYY:FGEHPGHER SVER",
        "NQQE:2244 ARYFBA EQ",
        "CUBAR:7065470057",
        "ANZR:GHAAVAT, FGRIR & PLAGUVN");

    qbGrfg("G60",
        "WRSSREFBAPBHAGLPRAGENY:URYBYN URYVPBCGRE YNAQVAT JERAF NVECBEG",
        "PBQR:URYBYN",
        "PNYY:URYVPBCGRE YNAQVAT",
        "NQQE:JERAF NVECBEG");

    qbGrfg("G61",
        "WRSSREFBAPBHAGLPRAGENY:ZINV NHGB NPPVQRAG JVGU VAWHEVRF YVAPBYA CNEX EQ",
        "PBQR:ZINV",
        "PNYY:NHGB NPPVQRAG JVGU VAWHEVRF",
        "NQQE:YVAPBYA CNEX EQ");

    qbGrfg("G62",
        "WRSSREFBAPBHAGLPRAGENY:ZIN NHGB NPPVQRAG PVGL FUBC",
        "PBQR:ZIN",
        "PNYY:NHGB NPPVQRAG",
        "NQQE:PVGL FUBC");

    qbGrfg("G63",
        "WRSSREFBAPBHAGLPRAGENY:ZINV NHGB NPPVQRAG JVGU VAWHEVRF UVTUJNL 1 A 7068368727 IREVMBA",
        "PBQR:ZINV",
        "PNYY:NHGB NPPVQRAG JVGU VAWHEVRF",
        "NQQE:UVTUJNL 1 A",
        "CUBAR:7068368727",
        "ANZR:IREVMBA");

    qbGrfg("G64",
        "WRSSREFBAPBHAGLPRAGENY:ERFCVE ERFCVENGBEL QVFGERFF 100 FARNQFG",
        "PBQR:ERFCVE",
        "PNYY:ERFCVENGBEL QVFGERFF",
        "NQQE:100 FARNQFG");

    qbGrfg("G65",
        "WRSSREFBAPBHAGLPRAGENY:SVERN SVER NYNEZ 310 UVTUJNL 1 OLC F 4786254119 BYQ PNCVGBY URNYGUPNER",
        "PBQR:SVERN",
        "PNYY:SVER NYNEZ",
        "NQQE:310 UVTUJNL 1 OLC F",
        "ZNQQE:310 UVTUJNL 1 OLCNFF F",
        "CUBAR:4786254119",
        "ANZR:BYQ PNCVGBY URNYGUPNER");

    qbGrfg("G66",
        "WRSSREFBAPBHAGLPRAGENY:ZIN NHGB NPPVQRAG 1067 R CRNPUGERR FG",
        "PBQR:ZIN",
        "PNYY:NHGB NPPVQRAG",
        "NQQE:1067 R CRNPUGERR FG");

    qbGrfg("G67",
        "WRSSREFBAPBHAGLPRAGENY:ERFCVE ERFCVENGBEL QVFGERFF 310 UVTUJNL 1 OLC A 4786257350",
        "PBQR:ERFCVE",
        "PNYY:ERFCVENGBEL QVFGERFF",
        "NQQE:310 UVTUJNL 1 OLC A",
        "ZNQQE:310 UVTUJNL 1 OLCNFF A",
        "CUBAR:4786257350");

    qbGrfg("G68",
        "WRSSREFBAPBHAGLPRAGENY:JRNGU JRNGURE ERYNGRQ TNZOYR FPUBBY EQ @UJL I88 UVYYPERFG SVER QRCG.",
        "PBQR:JRNGU",
        "PNYY:JRNGURE ERYNGRQ",
        "NQQE:TNZOYR FPUBBY EQ & UJL 88",
        "ANZR:UVYYPERFG SVER QRCG.");

    qbGrfg("G69",
        "WRSSREFBAPBHAGLPRAGENY:ZINV NHGB NPPVQRAG JVGU VAWHEVRF UVTUJNL 1 A",
        "PBQR:ZINV",
        "PNYY:NHGB NPPVQRAG JVGU VAWHEVRF",
        "NQQE:UVTUJNL 1 A");

    qbGrfg("G70",
        "WRSSREFBAPBHAGLPRAGENY:ZINV NHGB NPPVQRAG JVGU VAWHEVRF UVTUJNL 1 A 7068726188 WBUAFBA, YNGBLN",
        "PBQR:ZINV",
        "PNYY:NHGB NPPVQRAG JVGU VAWHEVRF",
        "NQQE:UVTUJNL 1 A",
        "CUBAR:7068726188",
        "ANZR:WBUAFBA, YNGBLN");

    qbGrfg("G71",
        "WRSSREFBAPBHAGLPRAGENY:ZIN NHGB NPPVQRAG UVTUJNL 171 A 4783310550 CRTTL YNAINMREIR",
        "PBQR:ZIN",
        "PNYY:NHGB NPPVQRAG",
        "NQQE:UVTUJNL 171 A",
        "CUBAR:4783310550",
        "ANZR:CRTTL YNAINMREIR");

    qbGrfg("G72",
        "WRSSREFBAPBHAGLPRAGENY:SVEROE OEHFU SVER 1820 JVYPURE EQ 4786258521 SNEEVF, ELNA & YVAQN",
        "PBQR:SVEROE",
        "PNYY:OEHFU SVER",
        "NQQE:1820 JVYPURE EQ",
        "CUBAR:4786258521",
        "ANZR:SNEEVF, ELNA & YVAQN");

    qbGrfg("G73",
        "WRSSREFBAPBHAGLPRAGENY:ERFCVE ERFCVENGBEL QVFGERFF 604 JNYXRE FG 4782681943 TNZOYR,",
        "PBQR:ERFCVE",
        "PNYY:ERFCVENGBEL QVFGERFF",
        "NQQE:604 JNYXRE FG",
        "CUBAR:4782681943",
        "ANZR:TNZOYR,");

    qbGrfg("G74",
        "WRSSREFBAPBHAGLPRAGENY:ZIN NHGB NPPVQRAG 202 UVTUJNL 1 OLC A 4784944435 FPBGG, NYVPR",
        "PBQR:ZIN",
        "PNYY:NHGB NPPVQRAG",
        "NQQE:202 UVTUJNL 1 OLC A",
        "ZNQQE:202 UVTUJNL 1 OLCNFF A",
        "CUBAR:4784944435",
        "ANZR:FPBGG, NYVPR");

    qbGrfg("G75",
        "WRSSREFBAPBHAGLPRAGENY:ERFCVE ERFCVENGBEL QVFGERFF 1106 JERA EQ 7065472883 JNYXRE, PYVSSBEQ",
        "PBQR:ERFCVE",
        "PNYY:ERFCVENGBEL QVFGERFF",
        "NQQE:1106 JERA EQ",
        "CUBAR:7065472883",
        "ANZR:JNYXRE, PYVSSBEQ");

    qbGrfg("G76",
        "WRSSREFBAPBHAGLPRAGENY:ZIN NHGB NPPVQRAG 410 J OEBNQ FG 4784944867 PUHEPU BS GUR ANMNERAR",
        "PBQR:ZIN",
        "PNYY:NHGB NPPVQRAG",
        "NQQE:410 J OEBNQ FG",
        "CUBAR:4784944867",
        "ANZR:PUHEPU BS GUR ANMNERAR");

    qbGrfg("G77",
        "WRSSREFBAPBHAGLPRAGENY:SVEROE OEHFU SVER 8911 JVYYVNZF OEVQTR EQ 7065472166 OENQQBPX, RYVMNORGU",
        "PBQR:SVEROE",
        "PNYY:OEHFU SVER",
        "NQQE:8911 JVYYVNZF OEVQTR EQ",
        "CUBAR:7065472166",
        "ANZR:OENQQBPX, RYVMNORGU");

    qbGrfg("G78",
        "WRSSREFBAPBHAGLPRAGENY:SVEROE OEHFU SVER 1191 RIRETERRA YA 7065470251 ONGGYR, ERTTVR",
        "PBQR:SVEROE",
        "PNYY:OEHFU SVER",
        "NQQE:1191 RIRETERRA YA",
        "CUBAR:7065470251",
        "ANZR:ONGGYR, ERTTVR");

    qbGrfg("G79",
        "WRSSREFBAPBHAGLPRAGENY:ZIN NHGB NPPVQRAG R 4GU FG 4782065182 SENAXYVA CUVYOREG",
        "PBQR:ZIN",
        "PNYY:NHGB NPPVQRAG",
        "NQQE:R 4GU FG",
        "CUBAR:4782065182",
        "ANZR:SENAXYVA CUVYOREG");

    qbGrfg("G80",
        "WRSSREFBAPBHAGLPRAGENY:ERFCVE ERFCVENGBEL QVFGERFF 503 PNYQJRYY FG 8004645324 BCE 1158",
        "PBQR:ERFCVE",
        "PNYY:ERFCVENGBEL QVFGERFF",
        "NQQE:503 PNYQJRYY FG",
        "CUBAR:8004645324",
        "ANZR:BCE 1158");

    qbGrfg("G81",
        "WRSSREFBAPBHAGLPRAGENY:ZPNPP ZBGBEPLPYR NPPVQRAG UVTUJNL 171 A",
        "PBQR:ZPNPP",
        "PNYY:ZBGBEPLPYR NPPVQRAG",
        "NQQE:UVTUJNL 171 A");

    qbGrfg("G82",
        "WRSSREFBAPBHAGLPRAGENY:ZPNPP ZBGBEPLPYR NPPVQRAG UVTUJNL 171 A @ BNX TEBIR EQ",
        "PBQR:ZPNPP",
        "PNYY:ZBGBEPLPYR NPPVQRAG",
        "NQQE:UVTUJNL 171 A & BNX TEBIR EQ");

    qbGrfg("G83",
        "WRSSREFBAPBHAGLPRAGENY:ERFCVE ERFCVENGBEL QVFGERFF 7902 PNZCTEBHAQ EQ 7064950199 NAQERN TVOOBAF",
        "PBQR:ERFCVE",
        "PNYY:ERFCVENGBEL QVFGERFF",
        "NQQE:7902 PNZCTEBHAQ EQ",
        "CUBAR:7064950199",
        "ANZR:NAQERN TVOOBAF");

    qbGrfg("G84",
        "WRSSREFBAPBHAGLPRAGENY:ERFCVE ERFCVENGBEL QVFGERFF 1067 R CRNPUGERR FG 4786253783 ORGU",
        "PBQR:ERFCVE",
        "PNYY:ERFCVENGBEL QVFGERFF",
        "NQQE:1067 R CRNPUGERR FG",
        "CUBAR:4786253783",
        "ANZR:ORGU");

    qbGrfg("G85",
        "WRSSREFBAPBHAGLPRAGENY:ZIN NHGB NPPVQRAG UVTUJNL 1 @ BTTRRPUR NCG 4782991243 JNYQRA, XRAQEVPX",
        "PBQR:ZIN",
        "PNYY:NHGB NPPVQRAG",
        "NQQE:UVTUJNL 1 & BTTRRPUR NCG",
        "CUBAR:4782991243",
        "ANZR:JNYQRA, XRAQEVPX");

    qbGrfg("G86",
        "WRSSREFBAPBHAGLPRAGENY:SVEROE OEHFU SVER 5111 ZVQQYRTEBHAQ EQ 7068290261 IREVMBA",
        "PBQR:SVEROE",
        "PNYY:OEHFU SVER",
        "NQQE:5111 ZVQQYRTEBHAQ EQ",
        "CUBAR:7068290261",
        "ANZR:IREVMBA");

    qbGrfg("G87",
        "WRSSREFBAPBHAGLPRAGENY:HAERFC SNVAGVAT / HAERFCBFVIR 1557 TRBETR JVYYVNZF EQ 7068299298 IREVMBA",
        "PBQR:HAERFC",
        "PNYY:SNVAGVAT / HAERFCBFVIR",
        "NQQE:1557 TRBETR JVYYVNZF EQ",
        "CUBAR:7068299298",
        "ANZR:IREVMBA");

    qbGrfg("G88",
        "WRSSREFBAPBHAGLPRAGENY:ZIN NHGB NPPVQRAG 101 A ZNVA FG AR 7063575147 RYYN WNPXFBA",
        "PBQR:ZIN",
        "PNYY:NHGB NPPVQRAG",
        "NQQE:101 A ZNVA FG AR",
        "CUBAR:7063575147",
        "ANZR:RYYN WNPXFBA");

    qbGrfg("G89",
        "WRSSREFBAPBHAGLPRAGENY:ZIN NHGB NPPVQRAG 308 UVTUJNL 1 OLC A 4786257168 JNAQN QHEQRA",
        "PBQR:ZIN",
        "PNYY:NHGB NPPVQRAG",
        "NQQE:308 UVTUJNL 1 OLC A",
        "ZNQQE:308 UVTUJNL 1 OLCNFF A",
        "CUBAR:4786257168",
        "ANZR:JNAQN QHEQRA");

    qbGrfg("G90",
        "WRSSREFBAPBHAGLPRAGENY:ZINV NHGB NPPVQRAG JVGU VAWHEVRF ZBKYRL ONEGBJ EQ",
        "PBQR:ZINV",
        "PNYY:NHGB NPPVQRAG JVGU VAWHEVRF",
        "NQQE:ZBKYRL ONEGBJ EQ");

    qbGrfg("G91",
        "WRSSREFBAPBHAGLPRAGENY:ZINV NHGB NPPVQRAG JVGU VAWHEVRF ZBKYRL ONEGBJ EQ 7068402710 YNZO, PBYOL",
        "PBQR:ZINV",
        "PNYY:NHGB NPPVQRAG JVGU VAWHEVRF",
        "NQQE:ZBKYRL ONEGBJ EQ",
        "CUBAR:7068402710",
        "ANZR:YNZO, PBYOL");

    qbGrfg("G92",
        "WRSSREFBAPBHAGLPRAGENY:ZIN NHGB NPPVQRAG BYQ UJL 1&ONEJVPX PVE 9115906601 ZPOEVQR, YRJVF",
        "PBQR:ZIN",
        "PNYY:NHGB NPPVQRAG",
        "NQQE:BYQ UJL 1 & ONEJVPX PVE",
        "CUBAR:9115906601",
        "ANZR:ZPOEVQR, YRJVF");

    qbGrfg("G93",
        "WRSSREFBAPBHAGLPRAGENY:ERFCVE ERFCVENGBEL QVFGERFF 203 CUVYYVCF FG AJ 7065476961 OENAARA, ORGGL U",
        "PBQR:ERFCVE",
        "PNYY:ERFCVENGBEL QVFGERFF",
        "NQQE:203 CUVYYVCF FG AJ",
        "CUBAR:7065476961",
        "ANZR:OENAARA, ORGGL U");

    qbGrfg("G94",
        "WRSSREFBAPBHAGLPRAGENY:ZIN NHGB NPPVQRAG 205 A ZNVA FG AR 7064660768 WNPDHYVAR UHSS",
        "PBQR:ZIN",
        "PNYY:NHGB NPPVQRAG",
        "NQQE:205 A ZNVA FG AR",
        "CUBAR:7064660768",
        "ANZR:WNPDHYVAR UHSS");

    qbGrfg("G95",
        "WRSSREFBAPBHAGLPRAGENY:ERFCVE ERFCVENGBEL QVFGERFF 604 JNYXRE FG 9117389253 CNGGREFBA, NYRKNAQEVN",
        "PBQR:ERFCVE",
        "PNYY:ERFCVENGBEL QVFGERFF",
        "NQQE:604 JNYXRE FG",
        "CUBAR:9117389253",
        "ANZR:CNGGREFBA, NYRKNAQEVN");

    qbGrfg("G96",
        "WRSSREFBAPBHAGLPRAGENY:ERFCVE ERFCVENGBEL QVFGERFF 207 GENSNYTNE QE AR",
        "PBQR:ERFCVE",
        "PNYY:ERFCVENGBEL QVFGERFF",
        "NQQE:207 GENSNYTNE QE AR");

  }
  
  choyvp fgngvp ibvq znva(Fgevat[] netf) {
    arj TNWrssrefbaPbhaglCnefreGrfg().trarengrGrfgf("G1");
  }
}
