cnpxntr arg.narv.pnqcntr.cnefref.TN;

vzcbeg arg.narv.pnqcntr.cnefref.OnfrCnefreGrfg;

vzcbeg bet.whavg.Grfg;

/*
ZpQhssvr Pbhagl, TN

Npgvir911 Cnefref:
HF/TN/GubzcfbaZpQhssvr
HF/TN/GubzfbaSQ


Pbagnpg: Npgvir911
Ntrapl anzr: ZpQhssvr Pbhagl Sver Erfphr
Ybpngvba: Gubzfba, TN, Havgrq Fgngrf
Fraqre: <pvfpb@gubzfba-zpqhssvr.arg>

{SVER/NYNEZ} Ybp:1038 FHCREVBE JNL FJ KFg:ZG CYRNFNAG EQ QRNQ RAQ Tevq:1008 Havgf:FZ1 FZ2 FZ5 Ezx:CBN 2 QVSSRERAG CHYY FGNGVBA NYNEZF; FRAGEL ARG BC 850
{1FG ERFC} Ybp:1042 JUVGRBNX EQ FR KFg:UNEEVFBA EQ FR CRPNA NI Tevq:1021 Havgf:FZ1 Ezx:20 LBS SRRYVAT FHVPVQNY/GENVYRE QVERPGYL NPEBFF GUR FGERRGF SEBZ PUNYXREF OYX GNAX
{1FG ERFC} Ybp:1747 NAAVR ZNR EBTREF EQ AR KFg:QNYYNF QE AR QRNQ RAQ Tevq:2014 Havgf:FZ2 Ezx:BO RZRETRAPL/FCBGGVAT/CNVA VA YBJRE NOQBZRA/2AQ CERTANAPL
{1FG ERFC} Ybp:1811 OBARIVYYR PVE FR KFg:OBARIVYYR EQ FR OBARIVYYR EQ FR Tevq:1017 Havgf:FB9 Ezx:ZRQVPNY NYNEZ, ART PBAGNPG BA VAGREPBZ, AB NAFJRE BA CUBAR; ZRQVPNY NYREG, BC OEVNA
{1FG ERFC} Ybp:1811 OBARIVYYR PVE FR KFg:OBARIVYYR EQ FR OBARIVYYR EQ FR Tevq:1017 Havgf:FB15 Ezx:ZRQVPNY NYNEZ, ART PBAGNPG BA VAGREPBZ, AB NAFJRE BA CUBAR; ZRQVPNY NYREG, BC OEVNA
{1FG ERFC} Ybp:1811 OBARIVYYR PVE FR KFg:OBARIVYYR EQ FR OBARIVYYR EQ FR Tevq:1017 Havgf: Ezx:ZRQVPNY NYNEZ, ART PBAGNPG BA VAGREPBZ, AB NAFJRE BA CUBAR; ZRQVPNY NYREG, BC OEVNA
{1FG ERFC} Ybp:1811 OBARIVYYR PVE FR KFg:OBARIVYYR EQ FR OBARIVYYR EQ FR Tevq:1017 Havgf:FZ1 Ezx:ZRQVPNY NYNEZ, ART PBAGNPG BA VAGREPBZ, AB NAFJRE BA CUBAR; ZRQVPNY NYREG, BC OEVNA
{1FG ERFC} Ybp:1004 UHAGYL PVE AR KFg:XRYFB QE AR ABEGUIVRJ RKG Tevq:1010 Havgf:FZ1 Ezx:32 LB SZ SRYY BHG BS GUR FUBJRE NAQ VF OYRRQVAT SEBZ GUR URNQ HANOYR GB FCRNX. GUVF VF N
{FIF PNYY} Ybp:1166 BYQ JNFUVATGBA EQ AR KFg:PVGL YVZVGF QNYYNF QE AR Tevq:2015 Havgf:FZ2 Ezx:UNQ N TNF YRNX GUR BGURE QNL OHG FUR VF FZRYYVAT TNF NTNVA
{SVER/NYNEZ} Ybp:3612 QRRESVRYQ EQ FR KFg:UBEFUNZ GE FR UBEFUNZ GE FR Tevq:3015 Havgf:FZ3 FZ5 FZ1 J5Z Ezx:FUBJVAT SNZVYL EBBZ FZBXR NYNEZ........800-633-2677....6569
{1FG ERFC} Ybp:1811 OBARIVYYR PVE FR KFg:OBARIVYYR EQ FR OBARIVYYR EQ FR Tevq:1017 Havgf:R1Z Ezx:OREGUN UNEEVF 61 LBS. AB ZRQVPNY UVFGBEL VF VA YVSR IVNY ARNE ERSEVT
{1FG ERFC} Ybp:1811 OBARIVYYR PVE FR KFg:OBARIVYYR EQ FR OBARIVYYR EQ FR Tevq:1017 Havgf:FZ1 Ezx:OREGUN UNEEVF 61 LBS. AB ZRQVPNY UVFGBEL VF VA YVSR IVNY ARNE ERSEVT
{1FG ERFC} Ybp:1811 OBARIVYYR PVE FR KFg:OBARIVYYR EQ FR OBARIVYYR EQ FR Tevq:1017 Havgf:FZ1 Ezx:61 LBS AB PBAGNPG SEBZ OREGUN UNEEVF 50896/ARNE ERSEV
{1FG ERFC} Ybp:4464 JNFUVATGBA EQ AR KFg:UHAGVATGBA EQ A OVT PERRX Tevq:2007 Havgf:FZ2 Ezx:76 L.B. SRZNYR...YRT NAQ UVC CNVA FRPBAQNEL GB N SNYY. UK BS FCVANY PNAPRE
{1FG ERFC} Ybp:1776 UNZVYGBA QE AJ KFg:QNTTRGG EQ AJ QRNQ RAQ Tevq:2011 Havgf:FZ2 Ezx:33 L.B. ZNYR QVNORGVP YBJ OYBBQ FHTNE
{1FG ERFC} Ybp:1423 QNYYNF QE AR Ncg:S KFg:PHYCRCCRE PVE A OEBJA QE AR Tevq:2014 Havgf:E2Z Ezx:49 L/B ZNYR YBJ OYBBQ FHTNE
{1FG ERFC} Ybp:1423 QNYYNF QE AR Ncg:S KFg:PHYCRCCRE PVE A OEBJA QE AR Tevq:2014 Havgf:FZ2 Ezx:49 L/B ZNYR YBJ OYBBQ FHTNE
{1FG ERFC} Ybp:4689 NHTHFGN UJL FR KFg:ARNYF ZVYY EQ PHYCRCCRE FG Tevq:8002 Havgf: Ezx:87 LE BYQ SRZNYR WHFG TBG BHG BS GUR UBFCVGNY NAQ FUR VF UNIVAT QVSS OERNGUVAT. UK BS
{1FG ERFC} Ybp:4689 NHTHFGN UJL FR KFg:ARNYF ZVYY EQ PHYCRCCRE FG Tevq:8002 Havgf:QSQ Ezx:87 LE BYQ SRZNYR WHFG TBG BHG BS GUR UBFCVGNY NAQ FUR VF UNIVAT QVSS OERNGUVAT. UK BS
{1FG ERFC} Ybp:6279 YVAPBYAGBA EQ AR Ncg:8 KFg:ZHEENL NI AR JBBQINYYRL EQ A Tevq:4002 Havgf:E2Z R2Z Ezx:62 LE BYQ SRZNYR SRYY NAQ UNF ORRA BA GUR SYBBE FVAPR 7CZ. FUR VF ABG UHEG NF SNE NF FUR
{1FG ERFC} Ybp:6279 YVAPBYAGBA EQ AR Ncg:8 KFg:ZHEENL NI AR JBBQINYYRL EQ A Tevq:4002 Havgf:E2Z Ezx:62 LE BYQ SRZNYR SRYY NAQ UNF ORRA BA GUR SYBBE FVAPR 7CZ. FUR VF ABG UHEG NF SNE NF FUR
{1FG ERFC} Ybp:6279 YVAPBYAGBA EQ AR Ncg:8 KFg:ZHEENL NI AR JBBQINYYRL EQ A Tevq:4002 Havgf:FZ2 Ezx:62 LE BYQ SRZNYR SRYY NAQ UNF ORRA BA GUR SYBBE FVAPR 7CZ. FUR VF ABG UHEG NF SNE NF FUR
{SVER/OEHFU} Ybp:1702 JNFUVATGBA EQ AR KFg:PRQNE FG AJ FRLZBHE QE AJ Tevq:2015 Havgf:FZ2 FZ1 Ezx:SVER VF BHG OHG UR JNAGF FBZRBAR GB PURPX VG
{1FG ERFC} Ybp:2736 JEVTUGFOBEB EQ AJ KFg:XABK-EVIREF EQ ZNGGBK PERRX Tevq:2009 Havgf:FZ2 Ezx:68 LBS VAWHEL FRPBAQNEL GB N SNYY, ABG NOYR GB GNYX UK BS PIN/QVNORGRF/PBEBANEL
{1FG ERFC} Ybp:1423 QNYYNF QE AR Ncg:YGS KFg:PHYCRCCRE PVE A OEBJA QE AR Tevq:2014 Havgf:FZ2 Ezx:49 YBJ OYBBQ FHTNE UK BS QVNORGRF
{1FG ERFC} Ybp:6279 YVAPBYAGBA EQ AR Ncg:YG8 KFg:ZHEENL NI AR JBBQINYYRL EQ A Tevq:4002 Havgf:FZ4 Ezx:62 LBS VAWHEVRF FRPBAQNEL GB N SNYY
{1FG ERFC} Ybp:149 SNHOHF FG AJ KFg:IVBYN NIREL FG UNJRF FG AJ Tevq:1019 Havgf:FZ1 Ezx:59 LB SZ PURFG CNVA
{SVER/OEHFU} Ybp:255 ABOYR FG AJ KFg:ABOYR FGERRG RK JVYYBJ FG AJ Tevq:2012 Havgf:FZ2 FZ1 Ezx:NQIVFR FZNYY OEHFU SVER VA GUR JBBQF ORFVQR3 URE ERFVQRAPR
{1FG ERFC} Ybp:1101 JLPYVSS QE AJ KFg:PRQNE FG AJ FRLZBHE QE AJ Tevq:2012 Havgf:E2Z Ezx:70 LBS OERNGUVAT QVSSVPHYGVRF..PBZR VA GUR ONPX LNEQ
{1FG ERFC} Ybp:1101 JLPYVSS QE AJ KFg:PRQNE FG AJ FRLZBHE QE AJ Tevq:2012 Havgf:FZ2 Ezx:70 LBS OERNGUVAT QVSSVPHYGVRF..PBZR VA GUR ONPX LNEQ
{1FG ERFC} Ybp:5391 NQNZF PUNCRY EQ FR KFg:UVYYZNA-TNL EQ ARNYF ZVYY EQ F Tevq:3010 Havgf:FZ3 FZ1 R4Z Ezx:PNE SRYY BA UVZ GURL TBG UVZ SEBZ HAQRE GUR PNE
{1FG ERFC} Ybp:5391 NQNZF PUNCRY EQ FR KFg:UVYYZNA-TNL EQ ARNYF ZVYY EQ F Tevq:3010 Havgf:FZ3 FZ1 Ezx:PNE SRYY BA UVZ GURL TBG UVZ SEBZ HAQRE GUR PNE
{1FG ERFC} Ybp:2319 HAVBA PUHEPU EQ AJ KFg:EBPX UBHFR EQ A PRQNE EBPX EQ A Tevq:1001 Havgf:FZ1 R4Z Ezx:70 LBS HAERFCBAFVIR. QVNORGVP CNGVRAG
{1FG ERFC} Ybp:2319 HAVBA PUHEPU EQ AJ KFg:EBPX UBHFR EQ A PRQNE EBPX EQ A Tevq:1001 Havgf:FZ1 Ezx:70 LBS HAERFCBAFVIR. QVNORGVP CNGVRAG
{1FG ERFC} Ybp:5870 NHTHFGN UJL FR KFg:ENQSBEQ TNL EQ NQNZF PUNCRY EQ Tevq:3015 Havgf:FZ3 Ezx:ZNYR FHOW QVSS OERNGUVAT FVQR GUR EBNQJNL 4 IRU
{1FG ERFC} Ybp:146 ARNYF ZVYY EQ KFg:NHTHFGN UJL FR SVEFG FG Tevq:8002 Havgf:QSQ Ezx:ZNYR NG GUR RQHPNGVBA VAFG UNIVAT CEBOYRZF OERNGUVAT
{1FG ERFC} Ybp:1826 JNFUVATGBA EQ AR KFg:JRFGJBBQ QE AJ QNYYNF QE AR Tevq:2015 Havgf:FZ2 Ezx:
{1FG ERFC} Ybp:1423 QNYYNF QE AR KFg:PHYCRCCRE PVE A OEBJA QE AR Tevq:2014 Havgf:FZ2 Ezx:50 LBZ YBJ OYBBQ FHTNE UK BS QVNORGRF
{1FG ERFC} Ybp:1333 PNEY QE FR KFg:ZBBFR PYHO EQ F QRNQ RAQ Tevq:1018 Havgf:FZ1 Ezx:6 LBZ PURFG CNVA UNF N URNEG PBAQVGVBA
{1FG ERFC} Ybp:115 FUNAX FG KFg:ZNEGVA YHGURE X QRNA NI Tevq:1020 Havgf:R1Z Ezx:68 LE BYQ ZNYR SRRYF YVXR UR VF TBVAT GB CNFF BHG. UR VF VA GUR ONPX LNEQ VA GUR GEHPX
{1FG ERFC} Ybp:115 FUNAX FG KFg:ZNEGVA YHGURE X QRNA NI Tevq:1020 Havgf:FZ1 Ezx:68 LE BYQ ZNYR SRRYF YVXR UR VF TBVAT GB CNFF BHG. UR VF VA GUR ONPX LNEQ VA GUR GEHPX
{1FG ERFC} Ybp:664 NHTHFGN EQ FR KFg:FNYRZ EQ UNEEVFBA EQ FR Tevq:1009 Havgf:C11 Ezx:2 IRUVPYRF. 1 CNGVRAG JVGU ONPX CNVA. GURL NER OBGU VA GUR EBNQ
{1FG ERFC} Ybp:664 NHTHFGN EQ FR KFg:FNYRZ EQ UNEEVFBA EQ FR Tevq:1009 Havgf: Ezx:2 IRUVPYRF. 1 CNGVRAG JVGU ONPX CNVA. GURL NER OBGU VA GUR EBNQ
{1FG ERFC} Ybp:664 NHTHFGN EQ FR KFg:FNYRZ EQ UNEEVFBA EQ FR Tevq:1009 Havgf:FZ1 Ezx:2 IRUVPYRF. 1 CNGVRAG JVGU ONPX CNVA. GURL NER OBGU VA GUR EBNQ
{1FG ERFC} Ybp:5100 WBARF EQ FR KFg:ARNYF ZVYY EQ F NYIVA ARNY EQ F Tevq:3002 Havgf:FZ3 FZ1 Ezx:55 LB SZ PURFG CNVA QBRF UNIR N CNPRZNXRE NAQ ERFC QVFGERFF
{1FG ERFC} Ybp:5063 NHTHFGN UJL FR KFg:PVGL YVZVGF ENQSBEQ TNL EQ Tevq:3015 Havgf:FZ3 Ezx:NQIVFR ZNA NCG 4 WHZCRQ BA GUR ZTE WBUA
{1FG ERFC} Ybp:1096 OBARIVYYR EQ FR KFg:UNZCGBA-QNIVF E ENAQNYY-UHAG EQ Tevq:1017 Havgf:FZ1 Ezx:N JZ JRNEVAT N BENATR G FUVEG NAQ TEA PNZB FUBEGF VF YLVAT VA GUR QVGPU
{1FG ERFC} Ybp:1814 UBOOF ZVYY EQ FR KFg:ENQSBEQ-PHYOERG TEVRE JNER EQ F Tevq:5006 Havgf:FB16 FB10 FB13 Ezx:FHOWRPG WHFG TBG FGNOORQ. FBZRBAR GBYQ UVZ GB PNYY. UR FNVQ UR JNF JNYXVAT OL NAQ FBZRBAR GBYQ UVZ GB PNYY 911
{1FG ERFC} Ybp:1814 UBOOF ZVYY EQ FR KFg:ENQSBEQ-PHYOERG TEVRE JNER EQ F Tevq:5006 Havgf:FB16 FB10 Ezx:FHOWRPG WHFG TBG FGNOORQ. FBZRBAR GBYQ UVZ GB PNYY. UR FNVQ UR JNF JNYXVAT OL NAQ FBZRBAR GBYQ UVZ GB PNYY 911
{1FG ERFC} Ybp:1814 UBOOF ZVYY EQ FR KFg:ENQSBEQ-PHYOERG TEVRE JNER EQ F Tevq:5006 Havgf:FB16 Ezx:FHOWRPG WHFG TBG FGNOORQ. FBZRBAR GBYQ UVZ GB PNYY. UR FNVQ UR JNF JNYXVAT OL NAQ FBZRBAR GBYQ UVZ GB PNYY 911
{1FG ERFC} Ybp:1814 UBOOF ZVYY EQ FR KFg:ENQSBEQ-PHYOERG TEVRE JNER EQ F Tevq:5006 Havgf: Ezx:FHOWRPG WHFG TBG FGNOORQ. FBZRBAR GBYQ UVZ GB PNYY. UR FNVQ UR JNF JNYXVAT OL NAQ FBZRBAR GBYQ UVZ GB PNYY 911
{1FG ERFC} Ybp:1814 UBOOF ZVYY EQ FR KFg:ENQSBEQ-PHYOERG TEVRE JNER EQ F Tevq:5006 Havgf:FZ5 Ezx:FHOWRPG WHFG TBG FGNOORQ. FBZRBAR GBYQ UVZ GB PNYY. UR FNVQ UR JNF JNYXVAT OL NAQ FBZRBAR GBYQ UVZ GB PNYY 911
{1FG ERFC} Ybp:3668 RYYVATGBA NVEYVAR EQ FR KFg:ENQSBEQ-PHYOERG SVFU UNGPUREL E Tevq:3011 Havgf:FZ3 R1Z Ezx:47 L/B ZNYR YBJ OYBBQ FHTNE HAERFCBAFVIR
{1FG ERFC} Ybp:3668 RYYVATGBA NVEYVAR EQ FR KFg:ENQSBEQ-PHYOERG SVFU UNGPUREL E Tevq:3011 Havgf:FZ3 FZ1 Ezx:47 L/B ZNYR YBJ OYBBQ FHTNE HAERFCBAFVIR
{SVER/FGEHPGHER} Ybp:944 BYQ JNFUVATGBA EQ AR Ncg:13 KFg:PVGL YVZVGF QNYYNF QE AR Tevq:2015 Havgf:R2Z R1Z O6Z Ezx:FRR FZBXR NAQ ABG FHER VS VGF GUR JBBQF ORUVAQ GUR NCGF BE GUR ONPXFVQR BS GUR NCGF
{SVER/FGEHPGHER} Ybp:944 BYQ JNFUVATGBA EQ AR Ncg:13 KFg:PVGL YVZVGF QNYYNF QE AR Tevq:2015 Havgf:R2Z R1Z FZ6 Ezx:FRR FZBXR NAQ ABG FHER VS VGF GUR JBBQF ORUVAQ GUR NCGF BE GUR ONPXFVQR BS GUR NCGF
{SVER/FGEHPGHER} Ybp:944 BYQ JNFUVATGBA EQ AR Ncg:13 KFg:PVGL YVZVGF QNYYNF QE AR Tevq:2015 Havgf:FZ2 R1Z FZ6 Ezx:FRR FZBXR NAQ ABG FHER VS VGF GUR JBBQF ORUVAQ GUR NCGF BE GUR ONPXFVQR BS GUR NCGF
{SVER/FGEHPGHER} Ybp:944 BYQ JNFUVATGBA EQ AR Ncg:13 KFg:PVGL YVZVGF QNYYNF QE AR Tevq:2015 Havgf:FZ2 FZ1 FZ6 Ezx:FRR FZBXR NAQ ABG FHER VS VGF GUR JBBQF ORUVAQ GUR NCGF BE GUR ONPXFVQR BS GUR NCGF
{1FG ERFC} Ybp:TVATRE UVYY EQ AR/UBARLFHPXYR YA AR KFg:JUVGRBNX EQ AR TVATRE UVYY RFG Tevq:6005 Havgf:FZ6 R1Z E2Z Ezx:2 IRUVPYRF...BAR FGVYY VA EBNQJNL. BAR FHOWRPG JVGU YNPRENGVBAF GB GUR URNQ
{1FG ERFC} Ybp:TVATRE UVYY EQ AR/UBARLFHPXYR YA AR KFg:JUVGRBNX EQ AR TVATRE UVYY RFG Tevq:6005 Havgf:FZ6 R1Z Ezx:2 IRUVPYRF...BAR FGVYY VA EBNQJNL. BAR FHOWRPG JVGU YNPRENGVBAF GB GUR URNQ
{1FG ERFC} Ybp:TVATRE UVYY EQ AR/UBARLFHPXYR YA AR KFg:JUVGRBNX EQ AR TVATRE UVYY RFG Tevq:6005 Havgf:FZ6 Ezx:2 IRUVPYRF...BAR FGVYY VA EBNQJNL. BAR FHOWRPG JVGU YNPRENGVBAF GB GUR URNQ
{1FG ERFC} Ybp:214 PNZRYVN QE KFg:ZPTNURR NI ZBBER NI Tevq:8002 Havgf:QSQ Ezx:46 LBS QVNORGVP CEBOYRZ/RYRINGRQ OTY 263
{SVER/OEHFU} Ybp:JNFUVATGBA EQ AR/EHFFRYY'F YNAQVAT EQ AR KFg:EVQTR EQ AJ FZVGU ZVYY EQ A Tevq:2005 Havgf:FZ2 FZ4 Ezx:JNFU EQ NEBHAQ ZZ4 JVYY OR BA GUR FVQR BS GUR EBNQ
{1FG ERFC} Ybp:929 JUVGRBNX EQ FR KFg:FVYYF FG UNEEVFBA EQ AR Tevq:1021 Havgf:FZ1 Ezx:20 L/B SRZNYR FRIRE NOQBZVANY CNVA QHR ZNL 20......(JUVGR UBHFR ERQ EBBS BA GBC)
{1FG ERFC} Ybp:5063 NHTHFGN UJL FR KFg:PVGL YVZVGF ENQSBEQ TNL EQ Tevq:3015 Havgf:FZ3 Ezx:10-50 V RAGENCZRAG
{SVER/NYNEZ} Ybp:690 NHTHFGN EQ FR KFg:FNYRZ EQ UNEEVFBA EQ FR Tevq:1009 Havgf:FZ1 FZ2 FZ5 Ezx:FUBJVAT FZBXR QRGRPGBE..UNYY SYBBE 2
{1FG ERFC} Ybp:219 IVBYN NIREL FG AJ KFg:QHAAF FG AJ UBRL FG AJ Tevq:1019 Havgf:FZ1 Ezx:44 L.B. ZNYR UNIVAT N FRVMHER
{1FG ERFC} Ybp:3635 QRNEVAT NPERF EQ FR KFg:URNQFGNYY YA FR QRNQ RAQ Tevq:3006 Havgf:FZ3 R1Z Ezx:58 LE BYQ ZNYR YBJ OTY
{1FG ERFC} Ybp:3635 QRNEVAT NPERF EQ FR KFg:URNQFGNYY YA FR QRNQ RAQ Tevq:3006 Havgf:FZ3 FZ1 Ezx:58 LE BYQ ZNYR YBJ OTY
{HAXABJA} Ybp:3815 JVYQJBBQ QE FR KFg:ENQSBEQ TNL EQ JVYQJBBQ PVE FR Tevq:3009 Havgf:FZ3 FZ1 FZ5 Ezx:URNIL FZBXR VA GUR NERN
{1FG ERFC} Ybp:217 ZNETNERGF EQ FR KFg:JUVGRBNX EQ FR JVFUNZ EQ FR Tevq:1004 Havgf:R1Z Ezx:47 LRNE BYQ SRZNYR HAPBA OHG OERNGUVAT
{1FG ERFC} Ybp:217 ZNETNERGF EQ FR KFg:JUVGRBNX EQ FR JVFUNZ EQ FR Tevq:1004 Havgf:FZ1 Ezx:47 LRNE BYQ SRZNYR HAPBA OHG OERNGUVAT
{1FG ERFC} Ybp:1023 HAVBA PUHEPU EQ AJ KFg:ZRFRAN EQ AJ SBFGRE-FCEBHFR Tevq:1001 Havgf:FZ1 Ezx:OR VA UVF IRUVPYR N TEL PURI VZCNYN ARRQ NFFG TRGGVAT BHG BS UVF IRUVPYR VAGB GUR UBHFR,

Pbagnpg: Npgvir911
Ntrapl anzr: GUBZFBA SQ
Ybpngvba: GUBZFBA, TN, Havgrq Fgngrf
Fraqre: <pvfpb@gubzfba-zpqhssvr.arg>

{1 EFC/PVGL} Ybp:638 ZNGGURJ FG FJ KFg:NAFYRL QE EBOVA FG Tevq:7003 Havgf:R703 Ezx:92 LB SZ FNLF FUR VF QVMML NAQ PNAG BCRA GUR QBBE.
{1 EFC/PVGL} Ybp:209 NAFYRL QE Ncg:37 KFg:WBUAFBA NI UVYY FG Tevq:7003 Havgf:R703 Ezx:1 LBS FRVMHER UK BS FRVMHER
{1 EFC/PVGL} Ybp:209 NAFYRL QE Ncg:37 KFg:WBUAFBA NI UVYY FG Tevq:7003 Havgf:R704 Ezx:1 LBS FRVMHER UK BS FRVMHER
{1 EFC/PVGL} Ybp:2205 UNEEVFBA EQ AR KFg:JNYAHG FG ZNVA FG Tevq:7002 Havgf:R705 Ezx:ERQ PEBJA IVP NAQ N SZ JVYY ABG YRG N ZNYR TRG BHG BS GUR PNE
{1 EFC/PVGL} Ybp:218 WNPXFBA FG Ncg:15 KFg:ZNVA FG JERAF UJL FR Tevq:7004 Havgf:C7 Ezx:82 LB ZNYR ABG OERNGUVAT
{1 EFC/PVGL} Ybp:218 WNPXFBA FG Ncg:15 KFg:ZNVA FG JERAF UJL FR Tevq:7004 Havgf: Ezx:82 LB ZNYR ABG OERNGUVAT
{1 EFC/PVGL} Ybp:218 WNPXFBA FG Ncg:15 KFg:ZNVA FG JERAF UJL FR Tevq:7004 Havgf:R703 Ezx:82 LB ZNYR ABG OERNGUVAT
{1 EFC/PVGL} Ybp:218 WNPXFBA FG Ncg:15 KFg:ZNVA FG JERAF UJL FR Tevq:7004 Havgf:R704 Ezx:82 LB ZNYR ABG OERNGUVAT
{1 EFC/PVGL} Ybp:524 ZNEGVA YHGURE XVAT WE FG KFg:TBEQBA FG JVYFBA FG Tevq:7002 Havgf:R705 Ezx:92 LBS VAWHEVRF FRPBAQNEL GB N SNYY HAQRE GUVF ZBEAVAT UNIVAT GEBHOYR ZBIVAT YRSG YRT,
{1 EFC/PVGL} Ybp:130 R URAQEVPXF FG Ncg:N KFg:WNPXFBA FG TERRAJNL FG Tevq:7004 Havgf:R705 Ezx:46 LBZ PURFG CNVA
{1 EFC/PVGL} Ybp:130 R URAQEVPXF FG Ncg:N KFg:WNPXFBA FG TERRAJNL FG Tevq:7004 Havgf:R704 Ezx:46 LBZ PURFG CNVA
{1 EFC/PVGL} Ybp:513 CVAR PG KFg:ZNEGVA YHGURE X TBEQBA FG Tevq:7002 Havgf:R705 Ezx:64LBZ QVSSVPHYGL OERNGUVAT NAQ JRNX
{1 EFC/PVGL} Ybp:ZVPUNRY FG/YRR QE KFg:FGBARJNYY QE FNYRZ EQ Tevq:7004 Havgf:R704 Ezx:BO RZRETRAPL VA N PNE FVYIRE PEHMR BA GUR EBNQJNL/YNOBE
{1 EFC/PVGL} Ybp:719 ZNGGURJ FG FJ KFg:NAFYRL QE EBOVA FG Tevq:7003 Havgf:R704 Ezx:46 LBZ QVNORGVP CEBOYRZF OYBBQ FHTNE VF RYRINGRQ
{1 EFC/PVGL} Ybp:318 GBZ JNGFBA JNL KFg:ZNVA FG YHZCXVA FG Tevq:7001 Havgf:R704 Ezx:86 L/B SRZNYR UNF SNYYRA PNA ABG TRG HC,,UNF NEGVSVPVNY YRTF..
{SVER/NYNEZ} Ybp:1861 UNEEVFBA EQ AR KFg:JNYAHG FG ZNVA FG AR Tevq:7002 Havgf:R705 Y707 Ezx:TRARENY SVER>>>>>>>>>>>>>>800-230-6975<<<<<<<<<<<<<7114
{1 EFC/PVGL} Ybp:413 YRR QE KFg:ZNANFFNF QE ZVPUNRY FG Tevq:7004 Havgf:R704 Ezx:31 LRNE BYQ ZNYR FRVMHERF
{1 EFC/PVGL} Ybp:1043 JNFUVATGBA EQ AJ KFg:JEVTUGFOBEB EQ ABOYR FG AJ Tevq:7001 Havgf:R705 Ezx:SJZNYR CNGVRAG VA N JUVGR INA HAERFCBAFVIR. CNGVRAG VF OERNGUVAT
{CHO FIF PNYY} Ybp:B'ARNY FG/P'OBNEQ JNL KFg:ENVYEBNQ FG FVYYF FG Tevq:7002 Havgf:P701 Ezx:CBFFVOYR ZVFFVAT PUVYQ BA GUR EE GENPXF. AB PYBGUVAT QRFPEVCGVBA.
{1 EFC/PVGL} Ybp:751 CHOYVP FNSRGL QE Ncg:WNVY KFg:UNEEVFBA EQ FR NHTHFGN EQ FR Tevq:7004 Havgf:R703 Ezx:25 LB ZNYR YBJ OYBBQ FHTNE
{1 EFC/PVGL} Ybp:751 CHOYVP FNSRGL QE Ncg:WNVY KFg:UNEEVFBA EQ FR NHTHFGN EQ FR Tevq:7004 Havgf:R705 Ezx:25 LB ZNYR YBJ OYBBQ FHTNE
{CHO FIF PNYY} Ybp:324 TBEQBA FG KFg:ZNVA FG RYYVATGBA NI Tevq:7002 Havgf:R705 Ezx:NQIVFR FBPXRGF FCNEXVAT SVER
{1 EFC/PVGL} Ybp:941 XRAARQL PVE KFg:JEVTUGFOBEB EQ ORGFL OENAPU QE Tevq:7001 Havgf:R705 Ezx:SRZNYR NQIVFRQ FURF NOBHG GB SNVAG. FUR VF UBZR NYBAR NAQ GELVAT GB BCRA GUR QBBE
{1 EFC/PVGL} Ybp:513 ZNEGVA YHGURE XVAT WE FG KFg:TBEQBA FG JVYFBA FG Tevq:7002 Havgf:R705 Ezx:7 ZB SRZNYR RYRINGRQ GRZC
{1 EFC/PVGL} Ybp:973 XRAARQL PVE KFg:JEVTUGFOBEB EQ ORGFL OENAPU QE Tevq:7001 Havgf:R705 Ezx:ZRQVPNY NYNEZ 78 LBS HAX ERNFBAF 888-289-2018 HANOYR GB ZNXR PBAGNPG BCRE WHYVR UK BS
{1 EFC/PVGL} Ybp:210 JUVGRBNX FG KFg:ZNVA FG UBYG FG Tevq:7002 Havgf:R705 Ezx:
{1 EFC/PVGL} Ybp:221 CRPNA NI KFg:JUVGRBNX EQ AR JNYAHG FG Tevq:7002 Havgf:R705 Ezx:19 LE BYQ ZNYR PNYIVA OEBJA WHFG UNQ N FRVMHER NAQ GURL NER ERDHRFGVAT NZOHYNAPR
{1 EFC/PVGL} Ybp:607 WBARF EQ KFg:JUVGRBNX EQ AR UBYG FG Tevq:7002 Havgf:R705 Ezx:39 LE BYQ SRZNYR PURFG CNVA JVGU UVTU OC. UBHFR JVGU OHETNAQL QBBE
{1 EFC/PVGL} Ybp:101 R UVYY FG KFg:WNPXFBA FG PVGL YVZVGF Tevq:7004 Havgf:R704 Ezx:29 LRNE BYQ SRZNYR FRVMHER
{1 EFC/PVGL} Ybp:640 ORRPUJBBQ QE KFg:YRR FG A ZNTABYVN QE Tevq:7001 Havgf:R705 Ezx:80 LBS HANOYR FGNAQ FRPBAQNEL GB SNYY SEBZ LRFGREQNL NAQ ERSHFR GENACBEG, JRNX
{SVER/FGEHPGHER} Ybp:944 BYQ JNFUVATGBA EQ AR Ncg:13 KFg:PVGL YVZVGF QNYYNF QE AR Tevq:2015 Havgf:R705 Ezx:FRR FZBXR NAQ ABG FHER VS VGF GUR JBBQF ORUVAQ GUR NCGF BE GUR ONPXFVQR BS GUR NCGF
{SVER/FGEHPGHER} Ybp:944 BYQ JNFUVATGBA EQ AR Ncg:13 KFg:PVGL YVZVGF QNYYNF QE AR Tevq:2015 Havgf: Ezx:FRR FZBXR NAQ ABG FHER VS VGF GUR JBBQF ORUVAQ GUR NCGF BE GUR ONPXFVQR BS GUR NCGF
{1 EFC/PVGL} Ybp:635 ORHYNU YA KFg:ZNP YA XVAT YA Tevq:7003 Havgf:R704 Ezx:23 LE BYQ ZNYR WHFG SNVAGRQ BA GUR SYBBE. UR VF OERNGUVAT. UR VF NHFGVP
{1 EFC/PVGL} Ybp:107 JUVGRBNX FGERRG RKG Ncg:48 KFg:JUVGRBNX FG WBARF EQ Tevq:7002 Havgf:R704 R706 Ezx:ZRQVPNY NYNEZ HANOYR GB PBAGNPG CNGVRAG........800-268-3453......314
{1 EFC/PVGL} Ybp:107 JUVGRBNX FGERRG RKG Ncg:48 KFg:JUVGRBNX FG WBARF EQ Tevq:7002 Havgf:R704 Ezx:ZRQVPNY NYNEZ HANOYR GB PBAGNPG CNGVRAG........800-268-3453......314
{1 EFC/PVGL} Ybp:126 YVAPBYA QE KFg:JUVGRBNX EQ AR ZBOYRL FG Tevq:7001 Havgf:R705 Ezx:RYQREYL SRZNYR SBHAQ OL TENAQXVQF HAERFCBAFVIR.
{1 EFC/PVGL} Ybp:307 TERRAJNL FG Ncg:2 KFg:TBEQBA FG URAQEVPXF FG J Tevq:7002 Havgf:R705 Ezx:53 L.B. SRZNYR...HAPBAFPVBHF
{1 EFC/PVGL} Ybp:410 THF FG KFg:QVKVR QE QRYY QE Tevq:7004 Havgf:R704 Ezx:RINYHNGVBA BA N ZNYR FHOWRPG. YNJ RASBEPRZRAG VF CERFRAG
{1 EFC/PVGL} Ybp:138 XVATFGBJA JL Ncg:304 KFg:WNPXFBA FG QRNQ RAQ Tevq:7004 Havgf:R703 Ezx:69 LBS SNYYRA HAXABJA VAWHEVRF/CP 3901/XRL BHGFVQR HAQRE CVT/QBBE FUBHYQ OR HAYBPXRQ
{1 EFC/PVGL} Ybp:896 FPBGG PG KFg:ORGFL OENAPU QE JEVTUGFOBEB EQ Tevq:7001 Havgf:R705 Ezx:72 LE BYQ ZNYR CBFFVOYR YBJ OTY. UR VF FJRNGVAT. UK BS QVNORGVP
{1 EFC/PVGL} Ybp:138 XVATFGBJA JL Ncg:304 KFg:WNPXFBA FG QRNQ RAQ Tevq:7004 Havgf:R703 Ezx:69 LBS HANOYR GB PBAGNPG FHOWRPG YVSR NYREG 800-638-8222 BCRE 1020 UK BS URNEG CEBOYRZF/QVNORGRF/OENVA PNAPRE/UVTU OC
{1 EFC/PVGL} Ybp:751 CHOYVP FNSRGL QE Ncg:WNVY KFg:UNEEVFBA EQ FR NHTHFGN EQ FR Tevq:7004 Havgf:R703 Ezx:48 LBS ENA BHG BS BKLTRA UK BS CHYZBAL ULCREGRAFVBA
{1 EFC/PVGL} Ybp:617 ZNEGVA YHGURE XVAT WE FG KFg:TBEQBA FG JVYFBA FG Tevq:7002 Havgf:R705 Ezx:40A LBZ ERFC QVFGERFF UK BS PUS
{1 EFC/PVGL} Ybp:643 ZNVA FG AJ KFg:ENVYEBNQ FG JEVTUGFOBEB EQ Tevq:7001 Havgf:R705 Ezx:55 LE BYQ ZNYR QVSS OERNGUVAT NAQ PURFG CNVAF
{1 EFC/PVGL} Ybp:602 RQVGU FG KFg:JUVGRBNX FG WBARF EQ Tevq:7002 Havgf:R705 Ezx:BYQRE SRZNYR UNIVAT N FRVMHER. FUR VF VAFVQR GUR UBHFR.
{1 EFC/PVGL} Ybp:1016 CRPNA PG KFg:CRPNA NI JUVGRBNX EQ AR Tevq:7002 Havgf:R705 Ezx:71 LB SZ FGNCYR PNZR BHG BS FHETVPNY JBHAQ
{1 EFC/PVGL} Ybp:450 WNPXFBA FG KFg:ZNVA FG JERAF UJL FR Tevq:7004 Havgf:R703 Ezx:60 LBZ VA/BHG BES PBAPPVBHFARFF UK BS ULCRAGRAFVBA
{1 EFC/PVGL} Ybp:800 N FG KFg:O FG P FG Tevq:7002 Havgf:R705 Ezx:60 LBS UK BS PCBQ
{1 EFC/PVGL} Ybp:2205 UNEEVFBA EQ AR KFg:JNYAHG FG ZNVA FG AR Tevq:7002 Havgf:R705 Ezx:26LBS SNVAGRQ, VF PBAF NAQ NYREG NG GUVF GVZR, JVYY OR IVFVBA PRAGRE VA JNYZNEG
{1 EFC/PVGL} Ybp:2205 UNEEVFBA EQ AR KFg:JNYAHG FG ZNVA FG AR Tevq:7002 Havgf:R703 Ezx:26LBS SNVAGRQ, VF PBAF NAQ NYREG NG GUVF GVZR, JVYY OR IVFVBA PRAGRE VA JNYZNEG
{1 EFC/PVGL} Ybp:224 CRPNA NI Ncg:N KFg:JUVGRBNX EQ AR JNYAHG FG Tevq:7002 Havgf:R705 Ezx:3EQ CNEGL PNYY, 90LBS SRYY HAX SHEGURE, ZNVAGRAPR ZNA BA FPRAR JVGU URE, BSSVPR JBEXRE
{1 EFC/PVGL} Ybp:311 ORNHERTNEQ QE KFg:ZNANFFNF QE WRSSREFBA FG Tevq:7004 Havgf:R703 Ezx:
{1 EFC/PVGL} Ybp:516 CVAR PG KFg:ZNEGVA YHGURE X TBEQBA FG Tevq:7002 Havgf:R705 Ezx:82 LBZ UNF SNYYRA NAQ HANOYR GB TRG HC
{CHO FIF PNYY} Ybp:532 THVYY FG Ncg:O-05 KFg:WNPXFBA FG UVYY FG J Tevq:7003 Havgf:R703 Ezx:YVSGVAT NFFVFG SBE RZF
{1 EFC/PVGL} Ybp:619 NQNZF NI KFg:RYYVATGBA NI ZNEGVA YHGURE X Tevq:7002 Havgf:R705 Ezx:NQHYG SRZNYR CNFFRQ BHG
{1 EFC/PVGL} Ybp:138 XVATFGBJA JL Ncg:304 KFg:WNPXFBA FG QRNQ RAQ Tevq:7004 Havgf:R703 Ezx:SRZNYR UNF SNYYRA JVGU HAXABJA VAWHEVRF...UK BS URNEG QVFRNFR NAQ QVNORGRF, UVTU OC,
{1 EFC/PVGL} Ybp:540 JUVGRBNX FG KFg:ZNVA FG UBYG FG Tevq:7002 Havgf:R705 Ezx:3 L.B. CBFFVOYL UNIVAT N FRVMHER
{1 EFC/PVGL} Ybp:549 J UVYY FG KFg:WNPXFBA FG PVGL YVZVGF Tevq:7003 Havgf:R703 Ezx:TEL IRUVPYR ENA VAGB GUR ONPX BS N YBT GEHPX
{1 EFC/PVGL} Ybp:549 J UVYY FG KFg:WNPXFBA FG PVGL YVZVGF Tevq:7003 Havgf:R704 Ezx:TEL IRUVPYR ENA VAGB GUR ONPX BS N YBT GEHPX
{1 EFC/PVGL} Ybp:520 ZG CYRNFNAG EQ FJ KFg:JNEERAGBA UJL F JNER FG Tevq:7003 Havgf:R703 Ezx:6 LBZ CBFF UNIVAT NA NFGUZN NGGNPX UK BS NFGUZN, PBZR GB GUR ONPX BS GUR FPUBBY
{1 EFC/PVGL} Ybp:520 ZG CYRNFNAG EQ FJ KFg:JNEERAGBA UJL F JNER FG Tevq:7003 Havgf:R704 Ezx:6 LBZ CBFF UNIVAT NA NFGUZN NGGNPX UK BS NFGUZN, PBZR GB GUR ONPX BS GUR FPUBBY
{1 EFC/PVGL} Ybp:404 YVYNP YA KFg:NCBYYB QE RQTNE PVE Tevq:7002 Havgf:R705 Ezx:76 LE BYQ SRZNYR NQIVFRQ GUNG FUR ARRQF N NZOHYNAPR OHG ABG FHER SBE JUNG. QBBE VF
{1 EFC/PVGL} Ybp:248 SVEFG NI KFg:TENQL FG ZNVA FG Tevq:7001 Havgf:R705 Ezx:30 LE BYQ ZNYR UNIVAT N FRVMHER. UK BS FRVMHERF
{1 EFC/PVGL} Ybp:832 N FG KFg:O FG P FG Tevq:7002 Havgf:R705 Ezx:89 LBS QVMML/NYZBFG SNVAGRQ/GEBHOYR OERNGUVAT YVSRYVAR 866-757-5747 ERS#ZRP2541563 UK BS
{1 EFC/PVGL} Ybp:138 XVATFGBJA JL Ncg:120 KFg:WNPXFBA FG QRNQ RAQ Tevq:7004 Havgf:R704 Ezx:84 LBS PURFG CNVA UNF N URNEG UK
{SVER/NYNEZ} Ybp:649 ZNTABYVN QE AJ KFg:YRR FG YNEPU YA Tevq:7001 Havgf:R705 R704 Y707 Ezx:HCFGNVEF FZBXR QRGRPGBE K 2
{1 EFC/PVGL} Ybp:207 QRNAF NYL KFg:ZNEGVA YHGURE X TBEQBA FG Tevq:7002 Havgf:R705 Ezx:30 LBZ QVNORGVP CEBOYRZF/HAERFCBAFVIR OHG OERNGUVAT
{1 EFC/PVGL} Ybp:886 PYRZZBAF FG KFg:N FG JNYAHG FG Tevq:7002 Havgf:R705 Ezx:24 L/B BO CNGVRAG VAWHEVRF SEBZ SNYY QBJA FGRCF
{CHO FIF PNYY} Ybp:410 WBUAF EQ KFg:THVYY FG JNER FG Tevq:7003 Havgf:R704 Ezx:NFFVFG FHOWRPG BA FPRAR VA YVSGRVAT CNGVARAG JUB UNF SNYYRA...AB VAWHEVRF
{1 EFC/PVGL} Ybp:207 QRNAF NYL KFg:ZNEGVA YHGURE X TBEQBA FG Tevq:7002 Havgf:R705 Ezx:ZNYR FHOWRPG CBFFVOYR YBJ OYBBQ FHTNE...HAXABJA NQQERFF. PNYYRE VF TBVAT GB OR BHGFVQR
{1 EFC/PVGL} Ybp:516 CVAR PG KFg:ZNEGVA YHGURE X TBEQBA FG Tevq:7002 Havgf:R705 Ezx:87 LE BYQ ZNYR SRYY BHG BS GUR JURRYPUNVE. ARRQF URYC ONPX HC
{SVER/GENFU} Ybp:210 CVGGF FG KFg:WNPXFBA FG OHFFRL NI Tevq:7004 Havgf:R704 Ezx:NQIVFR GURER VF FBZRGUVAT VA GUR CNEX BA SVER ZNLOR N GERR
{1 EFC/PVGL} Ybp:458 WNPXFBA FG KFg:ZNVA FG JERAF UJL FR Tevq:7004 Havgf:C9 Ezx:19 LRNE BYQ
{1 EFC/PVGL} Ybp:458 WNPXFBA FG KFg:ZNVA FG JERAF UJL FR Tevq:7004 Havgf: Ezx:19 LRNE BYQ
{1 EFC/PVGL} Ybp:458 WNPXFBA FG KFg:ZNVA FG JERAF UJL FR Tevq:7004 Havgf:R704 Ezx:19 LRNE BYQ
{1 EFC/PVGL} Ybp:604 QRYY QE Ncg:5 KFg:JNGFBA FG SBERFG PYNEL QE Tevq:7004 Havgf:R704 Ezx:15 LB SZ UNIVAT N CBFF CNAVP NGGNPX
{1 EFC/PVGL} Ybp:326 R UVYY FG KFg:WNPXFBA FG PVGL YVZVGF Tevq:7004 Havgf:R704 Ezx:FGVYY VA GUR EBNQ FVYIRE ZNYVOH NAQ N GNA YVAPBYA, 72LBS FGF VG UHEGF GB OERNGU, NABGURE
{1 EFC/PVGL} Ybp:138 XVATFGBJA JL Ncg:304 KFg:WNPXFBA FG QRNQ RAQ Tevq:7004 Havgf:R704 Ezx:69 LRNE BYQ SRZNYR
{1 EFC/PVGL} Ybp:877 PBOOUNZ EQ AR Ncg:N14 KFg:BYQ JNFUVATGBA UNEEVFBA QE AR Tevq:7002 Havgf:R705 Ezx:67 LE BYQ SRZNYR QVSS OERNGUVAT. FGBZNPU VF IREL FJRYYRQ. QVNYLFVF CNGVRAG
{1 EFC/PVGL} Ybp:400 QVKVR QE KFg:CVGGF FG SBERFG PYNEL QE Tevq:7004 Havgf:R704 Ezx:99LBS ABG OERNGUVAT JNF NJNXR NA UBHE NTB
{SVER/FGEHPGHER} Ybp:511 XABK FG KFg:RYYVATGBA NI ZRAQRY NI Tevq:7002 Havgf: Ezx:ONPX EBBZ BA SVER RIRELBAR BHG
{CHO FIF PNYY} Ybp:404 ZNTABYVN QE AJ KFg:YRR FG YNEPU YA Tevq:7001 Havgf:R705 Ezx:FZBXR QRGRPGBE TBVAT BSS AB SVER JNAGF FBZRBAR GB PBZR PURPX VG
{1 EFC/PVGL} Ybp:814 N FG KFg:O FG P FG Tevq:7002 Havgf:R705 Ezx:47LBS FGF FUR QBRFA'G SRRY JRYY GUVAXF FUR VF NOBHG GB QVR, UVFGBEL BS XVQARL SNVYHER NAQ FRVMHERF
{1 EFC/PVGL} Ybp:417 FNYRZ EQ KFg:NHTHFGN EQ FR UNEEVFBA EQ FR Tevq:7004 Havgf:R704 Ezx:84 LE BYQ SRZNYR SRYY NAQ UNF N XABG BA URE SBERURNQ BIRE RLR. UK BS NYMUVZREF
{1 EFC/PVGL} Ybp:318 GBZ JNGFBA JNL KFg:ZNVA FG YHZCXVA FG Tevq:7001 Havgf:R705 Ezx:86 LBS ARRQF BAYL YVSGVAT BAYL, FBZRBAR VF PBZVAT JVGU N XRL
{1 EFC/PVGL} Ybp:643 ZNEGVA YHGURE XVAT WE FG KFg:TBEQBA FG JVYFBA FG Tevq:7002 Havgf:R705 Ezx:79 LB SZ UK BS PUS UNIVAT ERFC QVFGERFF NAQ URE URNEG VF SYHGGREVAT
{1 EFC/PVGL} Ybp:R UVYY FG/WNPXFBA FG KFg:WBUAFBA NI OYNPX FG Tevq:7003 Havgf:R704 Ezx:RNFG UVYY FG @ WNPXFBA FG
{1 EFC/PVGL} Ybp:107 JUVGRBNX FGERRG RKG Ncg:48 KFg:JUVGRBNX FG WBARF EQ Tevq:7002 Havgf:R705 Ezx:59 L/B SRZNYR CBFF. FGEBXR PNZR VA IVN ZRQVPNY NYNEZ YVSR NYNEZ FLFGRZ 800-268-3453,,BCRE=329.
{CHO FIF PNYY} Ybp:2205 UNEEVFBA EQ AR KFg:JNYAHG FG ZNVA FG Tevq:7002 Havgf:R705 Ezx:FRIRENY XVGGRAF GENCCRQ VA N PHYIREG BS FBZR FBEG BA GUR TNEQRA PRAGRE RAQ
{SVER/FGEHPGHER} Ybp:751 CHOYVP FNSRGL QE KFg:UNEEVFBA EQ FR NHTHFGN EQ FR Tevq:7004 Havgf:R704 R705 Y707 Ezx:FZBXR VA O OYBPX,,
{1 EFC/PVGL} Ybp:651 ZNVA FG AJ KFg:ENVYEBNQ FG JEVTUGFOBEB EQ Tevq:7001 Havgf:R705 Ezx:SRZNYR CBFFVOYL OVGGRA OL FBZRGUVAT
{1 EFC/PVGL} Ybp:525 CVAR PG KFg:ZNEGVA YHGURE X TBEQBA FG Tevq:7002 Havgf:R705 Ezx:SRZNYR CNGVRAG PURFG CNVAF...ERFC QVFGERFF
{1 EFC/PVGL} Ybp:139 ANFFNH CY KFg:ZNVA FG XABK FUBCCVAT P Tevq:7002 Havgf: Ezx:SRZNYR FRVMHER VA GUR CNEXVAT YBG
{1 EFC/PVGL} Ybp:139 ANFFNH CY KFg:ZNVA FG XABK FUBCCVAT P Tevq:7002 Havgf:R705 Ezx:SRZNYR FRVMHER VA GUR CNEXVAT YBG
{1 EFC/PVGL} Ybp:958 XRAARQL PVE KFg:JEVTUGFOBEB EQ ORGFL OENAPU QE Tevq:7001 Havgf:R705 Ezx:73 L/B ZNYR HAERFCBAFVIR CNGVRAG VF OERNGUVAT
{CHO FIF PNYY} Ybp:309 PYRIRYNAQ FG KFg:TBEQBA FG ENVYEBNQ FG Tevq:7002 Havgf:R705 Ezx:GUR TNF ZRGRE VF ZNXVAT N UVFFVAT ABVFR NAQ CBFFVOYR YRNXVAT. BJARQ OL FB6
{1 EFC/PVGL} Ybp:701 PNEQVANY FG KFg:SBERFG PYNEL QE FNYRZ EQ Tevq:7004 Havgf:R703 Ezx:42 LE BYQ ZNYR GNXVAT N QVSSRERAG XVAQ BS ZRQVPNGVBA NAQ VG VF ZNXVAT UVF QVFYHFVBANY NAQ FRR GUVATF GUNG NVAG GURER. UR PNAG FYRRC NG AVTUG
{1 EFC/PVGL} Ybp:207 QRNAF NYL KFg:ZNEGVA YHGURE X TBEQBA FG Tevq:7002 Havgf:R705 Ezx:34 LBZ YBJ OYBBQ FHTNE UK BS QVNORGRF

*/

choyvp pynff TNZpQhssvrPbhaglCnefreGrfg rkgraqf OnfrCnefreGrfg {
  
  choyvp TNZpQhssvrPbhaglCnefreGrfg() {
    frgCnefre(arj TNZpQhssvrPbhaglCnefre(), "ZPQHSSVR PBHAGL", "TN");
  }


  @Grfg
  choyvp ibvq grfgZpQhssvrPbhaglSverErfphr() {

    qbGrfg("G1",
        "{SVER/NYNEZ} Ybp:1038 FHCREVBE JNL FJ KFg:ZG CYRNFNAG EQ QRNQ RAQ Tevq:1008 Havgf:FZ1 FZ2 FZ5 Ezx:CBN 2 QVSSRERAG CHYY FGNGVBA NYNEZF; FRAGEL ARG BC 850",
        "PNYY:SVER/NYNEZ",
        "NQQE:1038 FHCREVBE JNL FJ",
        "K:ZG CYRNFNAG EQ / QRNQ RAQ",
        "ZNC:1008",
        "HAVG:FZ1 FZ2 FZ5",
        "VASB:CBN 2 QVSSRERAG CHYY FGNGVBA NYNEZF; FRAGEL ARG BC 850");

    qbGrfg("G2",
        "{1FG ERFC} Ybp:1042 JUVGRBNX EQ FR KFg:UNEEVFBA EQ FR CRPNA NI Tevq:1021 Havgf:FZ1 Ezx:20 LBS SRRYVAT FHVPVQNY/GENVYRE QVERPGYL NPEBFF GUR FGERRGF SEBZ PUNYXREF OYX GNAX",
        "PNYY:1FG ERFC",
        "NQQE:1042 JUVGRBNX EQ FR",
        "K:UNEEVFBA EQ / FR CRPNA NI",
        "ZNC:1021",
        "HAVG:FZ1",
        "VASB:20 LBS SRRYVAT FHVPVQNY/GENVYRE QVERPGYL NPEBFF GUR FGERRGF SEBZ PUNYXREF OYX GNAX");

    qbGrfg("G3",
        "{1FG ERFC} Ybp:1747 NAAVR ZNR EBTREF EQ AR KFg:QNYYNF QE AR QRNQ RAQ Tevq:2014 Havgf:FZ2 Ezx:BO RZRETRAPL/FCBGGVAT/CNVA VA YBJRE NOQBZRA/2AQ CERTANAPL",
        "PNYY:1FG ERFC",
        "NQQE:1747 NAAVR ZNR EBTREF EQ AR",
        "K:QNYYNF QE / AR QRNQ RAQ",
        "ZNC:2014",
        "HAVG:FZ2",
        "VASB:BO RZRETRAPL/FCBGGVAT/CNVA VA YBJRE NOQBZRA/2AQ CERTANAPL");

    qbGrfg("G4",
        "{1FG ERFC} Ybp:1811 OBARIVYYR PVE FR KFg:OBARIVYYR EQ FR OBARIVYYR EQ FR Tevq:1017 Havgf:FB9 Ezx:ZRQVPNY NYNEZ, ART PBAGNPG BA VAGREPBZ, AB NAFJRE BA CUBAR; ZRQVPNY NYREG, BC OEVNA",
        "PNYY:1FG ERFC",
        "NQQE:1811 OBARIVYYR PVE FR",
        "K:OBARIVYYR EQ FR / OBARIVYYR EQ FR",
        "ZNC:1017",
        "HAVG:FB9",
        "VASB:ZRQVPNY NYNEZ, ART PBAGNPG BA VAGREPBZ, AB NAFJRE BA CUBAR; ZRQVPNY NYREG, BC OEVNA");

    qbGrfg("G5",
        "{1FG ERFC} Ybp:1811 OBARIVYYR PVE FR KFg:OBARIVYYR EQ FR OBARIVYYR EQ FR Tevq:1017 Havgf:FB15 Ezx:ZRQVPNY NYNEZ, ART PBAGNPG BA VAGREPBZ, AB NAFJRE BA CUBAR; ZRQVPNY NYREG, BC OEVNA",
        "PNYY:1FG ERFC",
        "NQQE:1811 OBARIVYYR PVE FR",
        "K:OBARIVYYR EQ FR / OBARIVYYR EQ FR",
        "ZNC:1017",
        "HAVG:FB15",
        "VASB:ZRQVPNY NYNEZ, ART PBAGNPG BA VAGREPBZ, AB NAFJRE BA CUBAR; ZRQVPNY NYREG, BC OEVNA");

    qbGrfg("G6",
        "{1FG ERFC} Ybp:1811 OBARIVYYR PVE FR KFg:OBARIVYYR EQ FR OBARIVYYR EQ FR Tevq:1017 Havgf: Ezx:ZRQVPNY NYNEZ, ART PBAGNPG BA VAGREPBZ, AB NAFJRE BA CUBAR; ZRQVPNY NYREG, BC OEVNA",
        "PNYY:1FG ERFC",
        "NQQE:1811 OBARIVYYR PVE FR",
        "K:OBARIVYYR EQ FR / OBARIVYYR EQ FR",
        "ZNC:1017",
        "VASB:ZRQVPNY NYNEZ, ART PBAGNPG BA VAGREPBZ, AB NAFJRE BA CUBAR; ZRQVPNY NYREG, BC OEVNA");

    qbGrfg("G7",
        "{1FG ERFC} Ybp:1811 OBARIVYYR PVE FR KFg:OBARIVYYR EQ FR OBARIVYYR EQ FR Tevq:1017 Havgf:FZ1 Ezx:ZRQVPNY NYNEZ, ART PBAGNPG BA VAGREPBZ, AB NAFJRE BA CUBAR; ZRQVPNY NYREG, BC OEVNA",
        "PNYY:1FG ERFC",
        "NQQE:1811 OBARIVYYR PVE FR",
        "K:OBARIVYYR EQ FR / OBARIVYYR EQ FR",
        "ZNC:1017",
        "HAVG:FZ1",
        "VASB:ZRQVPNY NYNEZ, ART PBAGNPG BA VAGREPBZ, AB NAFJRE BA CUBAR; ZRQVPNY NYREG, BC OEVNA");

    qbGrfg("G8",
        "{1FG ERFC} Ybp:1004 UHAGYL PVE AR KFg:XRYFB QE AR ABEGUIVRJ RKG Tevq:1010 Havgf:FZ1 Ezx:32 LB SZ SRYY BHG BS GUR FUBJRE NAQ VF OYRRQVAT SEBZ GUR URNQ HANOYR GB FCRNX. GUVF VF N",
        "PNYY:1FG ERFC",
        "NQQE:1004 UHAGYL PVE AR",
        "K:XRYFB QE AR / ABEGUIVRJ RKG",
        "ZNC:1010",
        "HAVG:FZ1",
        "VASB:32 LB SZ SRYY BHG BS GUR FUBJRE NAQ VF OYRRQVAT SEBZ GUR URNQ HANOYR GB FCRNX. GUVF VF N");

    qbGrfg("G9",
        "{FIF PNYY} Ybp:1166 BYQ JNFUVATGBA EQ AR KFg:PVGL YVZVGF QNYYNF QE AR Tevq:2015 Havgf:FZ2 Ezx:UNQ N TNF YRNX GUR BGURE QNL OHG FUR VF FZRYYVAT TNF NTNVA",
        "PNYY:FIF PNYY",
        "NQQE:1166 BYQ JNFUVATGBA EQ AR",
        "K:PVGL YVZVGF / QNYYNF QE AR",
        "ZNC:2015",
        "HAVG:FZ2",
        "VASB:UNQ N TNF YRNX GUR BGURE QNL OHG FUR VF FZRYYVAT TNF NTNVA");

    qbGrfg("G10",
        "{SVER/NYNEZ} Ybp:3612 QRRESVRYQ EQ FR KFg:UBEFUNZ GE FR UBEFUNZ GE FR Tevq:3015 Havgf:FZ3 FZ5 FZ1 J5Z Ezx:FUBJVAT SNZVYL EBBZ FZBXR NYNEZ........800-633-2677....6569",
        "PNYY:SVER/NYNEZ",
        "NQQE:3612 QRRESVRYQ EQ FR",
        "K:UBEFUNZ GE FR / UBEFUNZ GE FR",
        "ZNC:3015",
        "HAVG:FZ3 FZ5 FZ1 J5Z",
        "VASB:FUBJVAT SNZVYL EBBZ FZBXR NYNEZ........800-633-2677....6569");

    qbGrfg("G11",
        "{1FG ERFC} Ybp:1811 OBARIVYYR PVE FR KFg:OBARIVYYR EQ FR OBARIVYYR EQ FR Tevq:1017 Havgf:R1Z Ezx:OREGUN UNEEVF 61 LBS. AB ZRQVPNY UVFGBEL VF VA YVSR IVNY ARNE ERSEVT",
        "PNYY:1FG ERFC",
        "NQQE:1811 OBARIVYYR PVE FR",
        "K:OBARIVYYR EQ FR / OBARIVYYR EQ FR",
        "ZNC:1017",
        "HAVG:R1Z",
        "VASB:OREGUN UNEEVF 61 LBS. AB ZRQVPNY UVFGBEL VF VA YVSR IVNY ARNE ERSEVT");

    qbGrfg("G12",
        "{1FG ERFC} Ybp:1811 OBARIVYYR PVE FR KFg:OBARIVYYR EQ FR OBARIVYYR EQ FR Tevq:1017 Havgf:FZ1 Ezx:OREGUN UNEEVF 61 LBS. AB ZRQVPNY UVFGBEL VF VA YVSR IVNY ARNE ERSEVT",
        "PNYY:1FG ERFC",
        "NQQE:1811 OBARIVYYR PVE FR",
        "K:OBARIVYYR EQ FR / OBARIVYYR EQ FR",
        "ZNC:1017",
        "HAVG:FZ1",
        "VASB:OREGUN UNEEVF 61 LBS. AB ZRQVPNY UVFGBEL VF VA YVSR IVNY ARNE ERSEVT");

    qbGrfg("G13",
        "{1FG ERFC} Ybp:1811 OBARIVYYR PVE FR KFg:OBARIVYYR EQ FR OBARIVYYR EQ FR Tevq:1017 Havgf:FZ1 Ezx:61 LBS AB PBAGNPG SEBZ OREGUN UNEEVF 50896/ARNE ERSEV",
        "PNYY:1FG ERFC",
        "NQQE:1811 OBARIVYYR PVE FR",
        "K:OBARIVYYR EQ FR / OBARIVYYR EQ FR",
        "ZNC:1017",
        "HAVG:FZ1",
        "VASB:61 LBS AB PBAGNPG SEBZ OREGUN UNEEVF 50896/ARNE ERSEV");

    qbGrfg("G14",
        "{1FG ERFC} Ybp:4464 JNFUVATGBA EQ AR KFg:UHAGVATGBA EQ A OVT PERRX Tevq:2007 Havgf:FZ2 Ezx:76 L.B. SRZNYR...YRT NAQ UVC CNVA FRPBAQNEL GB N SNYY. UK BS FCVANY PNAPRE",
        "PNYY:1FG ERFC",
        "NQQE:4464 JNFUVATGBA EQ AR",
        "K:UHAGVATGBA EQ / A OVT PERRX",
        "ZNC:2007",
        "HAVG:FZ2",
        "VASB:76 L.B. SRZNYR...YRT NAQ UVC CNVA FRPBAQNEL GB N SNYY. UK BS FCVANY PNAPRE");

    qbGrfg("G15",
        "{1FG ERFC} Ybp:1776 UNZVYGBA QE AJ KFg:QNTTRGG EQ AJ QRNQ RAQ Tevq:2011 Havgf:FZ2 Ezx:33 L.B. ZNYR QVNORGVP YBJ OYBBQ FHTNE",
        "PNYY:1FG ERFC",
        "NQQE:1776 UNZVYGBA QE AJ",
        "K:QNTTRGG EQ / AJ QRNQ RAQ",
        "ZNC:2011",
        "HAVG:FZ2",
        "VASB:33 L.B. ZNYR QVNORGVP YBJ OYBBQ FHTNE");

    qbGrfg("G16",
        "{1FG ERFC} Ybp:1423 QNYYNF QE AR Ncg:S KFg:PHYCRCCRE PVE A OEBJA QE AR Tevq:2014 Havgf:E2Z Ezx:49 L/B ZNYR YBJ OYBBQ FHTNE",
        "PNYY:1FG ERFC",
        "NQQE:1423 QNYYNF QE AR",
        "NCG:S",
        "K:PHYCRCCRE PVE A / OEBJA QE AR",
        "ZNC:2014",
        "HAVG:E2Z",
        "VASB:49 L/B ZNYR YBJ OYBBQ FHTNE");

    qbGrfg("G17",
        "{1FG ERFC} Ybp:1423 QNYYNF QE AR Ncg:S KFg:PHYCRCCRE PVE A OEBJA QE AR Tevq:2014 Havgf:FZ2 Ezx:49 L/B ZNYR YBJ OYBBQ FHTNE",
        "PNYY:1FG ERFC",
        "NQQE:1423 QNYYNF QE AR",
        "NCG:S",
        "K:PHYCRCCRE PVE A / OEBJA QE AR",
        "ZNC:2014",
        "HAVG:FZ2",
        "VASB:49 L/B ZNYR YBJ OYBBQ FHTNE");

    qbGrfg("G18",
        "{1FG ERFC} Ybp:4689 NHTHFGN UJL FR KFg:ARNYF ZVYY EQ PHYCRCCRE FG Tevq:8002 Havgf: Ezx:87 LE BYQ SRZNYR WHFG TBG BHG BS GUR UBFCVGNY NAQ FUR VF UNIVAT QVSS OERNGUVAT. UK BS",
        "PNYY:1FG ERFC",
        "NQQE:4689 NHTHFGN UJL FR",
        "K:ARNYF ZVYY EQ / PHYCRCCRE FG",
        "ZNC:8002",
        "VASB:87 LE BYQ SRZNYR WHFG TBG BHG BS GUR UBFCVGNY NAQ FUR VF UNIVAT QVSS OERNGUVAT. UK BS");

    qbGrfg("G19",
        "{1FG ERFC} Ybp:4689 NHTHFGN UJL FR KFg:ARNYF ZVYY EQ PHYCRCCRE FG Tevq:8002 Havgf:QSQ Ezx:87 LE BYQ SRZNYR WHFG TBG BHG BS GUR UBFCVGNY NAQ FUR VF UNIVAT QVSS OERNGUVAT. UK BS",
        "PNYY:1FG ERFC",
        "NQQE:4689 NHTHFGN UJL FR",
        "K:ARNYF ZVYY EQ / PHYCRCCRE FG",
        "ZNC:8002",
        "HAVG:QSQ",
        "VASB:87 LE BYQ SRZNYR WHFG TBG BHG BS GUR UBFCVGNY NAQ FUR VF UNIVAT QVSS OERNGUVAT. UK BS");

    qbGrfg("G20",
        "{1FG ERFC} Ybp:6279 YVAPBYAGBA EQ AR Ncg:8 KFg:ZHEENL NI AR JBBQINYYRL EQ A Tevq:4002 Havgf:E2Z R2Z Ezx:62 LE BYQ SRZNYR SRYY NAQ UNF ORRA BA GUR SYBBE FVAPR 7CZ. FUR VF ABG UHEG NF SNE NF FUR",
        "PNYY:1FG ERFC",
        "NQQE:6279 YVAPBYAGBA EQ AR",
        "NCG:8",
        "K:ZHEENL NI AR / JBBQINYYRL EQ A",
        "ZNC:4002",
        "HAVG:E2Z R2Z",
        "VASB:62 LE BYQ SRZNYR SRYY NAQ UNF ORRA BA GUR SYBBE FVAPR 7CZ. FUR VF ABG UHEG NF SNE NF FUR");

    qbGrfg("G21",
        "{1FG ERFC} Ybp:6279 YVAPBYAGBA EQ AR Ncg:8 KFg:ZHEENL NI AR JBBQINYYRL EQ A Tevq:4002 Havgf:E2Z Ezx:62 LE BYQ SRZNYR SRYY NAQ UNF ORRA BA GUR SYBBE FVAPR 7CZ. FUR VF ABG UHEG NF SNE NF FUR",
        "PNYY:1FG ERFC",
        "NQQE:6279 YVAPBYAGBA EQ AR",
        "NCG:8",
        "K:ZHEENL NI AR / JBBQINYYRL EQ A",
        "ZNC:4002",
        "HAVG:E2Z",
        "VASB:62 LE BYQ SRZNYR SRYY NAQ UNF ORRA BA GUR SYBBE FVAPR 7CZ. FUR VF ABG UHEG NF SNE NF FUR");

    qbGrfg("G22",
        "{1FG ERFC} Ybp:6279 YVAPBYAGBA EQ AR Ncg:8 KFg:ZHEENL NI AR JBBQINYYRL EQ A Tevq:4002 Havgf:FZ2 Ezx:62 LE BYQ SRZNYR SRYY NAQ UNF ORRA BA GUR SYBBE FVAPR 7CZ. FUR VF ABG UHEG NF SNE NF FUR",
        "PNYY:1FG ERFC",
        "NQQE:6279 YVAPBYAGBA EQ AR",
        "NCG:8",
        "K:ZHEENL NI AR / JBBQINYYRL EQ A",
        "ZNC:4002",
        "HAVG:FZ2",
        "VASB:62 LE BYQ SRZNYR SRYY NAQ UNF ORRA BA GUR SYBBE FVAPR 7CZ. FUR VF ABG UHEG NF SNE NF FUR");

    qbGrfg("G23",
        "{SVER/OEHFU} Ybp:1702 JNFUVATGBA EQ AR KFg:PRQNE FG AJ FRLZBHE QE AJ Tevq:2015 Havgf:FZ2 FZ1 Ezx:SVER VF BHG OHG UR JNAGF FBZRBAR GB PURPX VG",
        "PNYY:SVER/OEHFU",
        "NQQE:1702 JNFUVATGBA EQ AR",
        "K:PRQNE FG AJ / FRLZBHE QE AJ",
        "ZNC:2015",
        "HAVG:FZ2 FZ1",
        "VASB:SVER VF BHG OHG UR JNAGF FBZRBAR GB PURPX VG");

    qbGrfg("G24",
        "{1FG ERFC} Ybp:2736 JEVTUGFOBEB EQ AJ KFg:XABK-EVIREF EQ ZNGGBK PERRX Tevq:2009 Havgf:FZ2 Ezx:68 LBS VAWHEL FRPBAQNEL GB N SNYY, ABG NOYR GB GNYX UK BS PIN/QVNORGRF/PBEBANEL",
        "PNYY:1FG ERFC",
        "NQQE:2736 JEVTUGFOBEB EQ AJ",
        "K:XABK-EVIREF EQ / ZNGGBK PERRX",
        "ZNC:2009",
        "HAVG:FZ2",
        "VASB:68 LBS VAWHEL FRPBAQNEL GB N SNYY, ABG NOYR GB GNYX UK BS PIN/QVNORGRF/PBEBANEL");

    qbGrfg("G25",
        "{1FG ERFC} Ybp:1423 QNYYNF QE AR Ncg:YGS KFg:PHYCRCCRE PVE A OEBJA QE AR Tevq:2014 Havgf:FZ2 Ezx:49 YBJ OYBBQ FHTNE UK BS QVNORGRF",
        "PNYY:1FG ERFC",
        "NQQE:1423 QNYYNF QE AR",
        "NCG:YGS",
        "K:PHYCRCCRE PVE A / OEBJA QE AR",
        "ZNC:2014",
        "HAVG:FZ2",
        "VASB:49 YBJ OYBBQ FHTNE UK BS QVNORGRF");

    qbGrfg("G26",
        "{1FG ERFC} Ybp:6279 YVAPBYAGBA EQ AR Ncg:YG8 KFg:ZHEENL NI AR JBBQINYYRL EQ A Tevq:4002 Havgf:FZ4 Ezx:62 LBS VAWHEVRF FRPBAQNEL GB N SNYY",
        "PNYY:1FG ERFC",
        "NQQE:6279 YVAPBYAGBA EQ AR",
        "NCG:YG8",
        "K:ZHEENL NI AR / JBBQINYYRL EQ A",
        "ZNC:4002",
        "HAVG:FZ4",
        "VASB:62 LBS VAWHEVRF FRPBAQNEL GB N SNYY");

    qbGrfg("G27",
        "{1FG ERFC} Ybp:149 SNHOHF FG AJ KFg:IVBYN NIREL FG UNJRF FG AJ Tevq:1019 Havgf:FZ1 Ezx:59 LB SZ PURFG CNVA",
        "PNYY:1FG ERFC",
        "NQQE:149 SNHOHF FG AJ",
        "K:IVBYN NIREL FG / UNJRF FG AJ",
        "ZNC:1019",
        "HAVG:FZ1",
        "VASB:59 LB SZ PURFG CNVA");

    qbGrfg("G28",
        "{SVER/OEHFU} Ybp:255 ABOYR FG AJ KFg:ABOYR FGERRG RK JVYYBJ FG AJ Tevq:2012 Havgf:FZ2 FZ1 Ezx:NQIVFR FZNYY OEHFU SVER VA GUR JBBQF ORFVQR3 URE ERFVQRAPR",
        "PNYY:SVER/OEHFU",
        "NQQE:255 ABOYR FG AJ",
        "K:ABOYR FGERRG / RK JVYYBJ FG AJ",
        "ZNC:2012",
        "HAVG:FZ2 FZ1",
        "VASB:NQIVFR FZNYY OEHFU SVER VA GUR JBBQF ORFVQR3 URE ERFVQRAPR");

    qbGrfg("G29",
        "{1FG ERFC} Ybp:1101 JLPYVSS QE AJ KFg:PRQNE FG AJ FRLZBHE QE AJ Tevq:2012 Havgf:E2Z Ezx:70 LBS OERNGUVAT QVSSVPHYGVRF..PBZR VA GUR ONPX LNEQ",
        "PNYY:1FG ERFC",
        "NQQE:1101 JLPYVSS QE AJ",
        "K:PRQNE FG AJ / FRLZBHE QE AJ",
        "ZNC:2012",
        "HAVG:E2Z",
        "VASB:70 LBS OERNGUVAT QVSSVPHYGVRF..PBZR VA GUR ONPX LNEQ");

    qbGrfg("G30",
        "{1FG ERFC} Ybp:1101 JLPYVSS QE AJ KFg:PRQNE FG AJ FRLZBHE QE AJ Tevq:2012 Havgf:FZ2 Ezx:70 LBS OERNGUVAT QVSSVPHYGVRF..PBZR VA GUR ONPX LNEQ",
        "PNYY:1FG ERFC",
        "NQQE:1101 JLPYVSS QE AJ",
        "K:PRQNE FG AJ / FRLZBHE QE AJ",
        "ZNC:2012",
        "HAVG:FZ2",
        "VASB:70 LBS OERNGUVAT QVSSVPHYGVRF..PBZR VA GUR ONPX LNEQ");

    qbGrfg("G31",
        "{1FG ERFC} Ybp:5391 NQNZF PUNCRY EQ FR KFg:UVYYZNA-TNL EQ ARNYF ZVYY EQ F Tevq:3010 Havgf:FZ3 FZ1 R4Z Ezx:PNE SRYY BA UVZ GURL TBG UVZ SEBZ HAQRE GUR PNE",
        "PNYY:1FG ERFC",
        "NQQE:5391 NQNZF PUNCRY EQ FR",
        "K:UVYYZNA-TNL EQ / ARNYF ZVYY EQ F",
        "ZNC:3010",
        "HAVG:FZ3 FZ1 R4Z",
        "VASB:PNE SRYY BA UVZ GURL TBG UVZ SEBZ HAQRE GUR PNE");

    qbGrfg("G32",
        "{1FG ERFC} Ybp:5391 NQNZF PUNCRY EQ FR KFg:UVYYZNA-TNL EQ ARNYF ZVYY EQ F Tevq:3010 Havgf:FZ3 FZ1 Ezx:PNE SRYY BA UVZ GURL TBG UVZ SEBZ HAQRE GUR PNE",
        "PNYY:1FG ERFC",
        "NQQE:5391 NQNZF PUNCRY EQ FR",
        "K:UVYYZNA-TNL EQ / ARNYF ZVYY EQ F",
        "ZNC:3010",
        "HAVG:FZ3 FZ1",
        "VASB:PNE SRYY BA UVZ GURL TBG UVZ SEBZ HAQRE GUR PNE");

    qbGrfg("G33",
        "{1FG ERFC} Ybp:2319 HAVBA PUHEPU EQ AJ KFg:EBPX UBHFR EQ A PRQNE EBPX EQ A Tevq:1001 Havgf:FZ1 R4Z Ezx:70 LBS HAERFCBAFVIR. QVNORGVP CNGVRAG",
        "PNYY:1FG ERFC",
        "NQQE:2319 HAVBA PUHEPU EQ AJ",
        "K:EBPX UBHFR EQ A / PRQNE EBPX EQ A",
        "ZNC:1001",
        "HAVG:FZ1 R4Z",
        "VASB:70 LBS HAERFCBAFVIR. QVNORGVP CNGVRAG");

    qbGrfg("G34",
        "{1FG ERFC} Ybp:2319 HAVBA PUHEPU EQ AJ KFg:EBPX UBHFR EQ A PRQNE EBPX EQ A Tevq:1001 Havgf:FZ1 Ezx:70 LBS HAERFCBAFVIR. QVNORGVP CNGVRAG",
        "PNYY:1FG ERFC",
        "NQQE:2319 HAVBA PUHEPU EQ AJ",
        "K:EBPX UBHFR EQ A / PRQNE EBPX EQ A",
        "ZNC:1001",
        "HAVG:FZ1",
        "VASB:70 LBS HAERFCBAFVIR. QVNORGVP CNGVRAG");

    qbGrfg("G35",
        "{1FG ERFC} Ybp:5870 NHTHFGN UJL FR KFg:ENQSBEQ TNL EQ NQNZF PUNCRY EQ Tevq:3015 Havgf:FZ3 Ezx:ZNYR FHOW QVSS OERNGUVAT FVQR GUR EBNQJNL 4 IRU",
        "PNYY:1FG ERFC",
        "NQQE:5870 NHTHFGN UJL FR",
        "K:ENQSBEQ TNL EQ / NQNZF PUNCRY EQ",
        "ZNC:3015",
        "HAVG:FZ3",
        "VASB:ZNYR FHOW QVSS OERNGUVAT FVQR GUR EBNQJNL 4 IRU");

    qbGrfg("G36",
        "{1FG ERFC} Ybp:146 ARNYF ZVYY EQ KFg:NHTHFGN UJL FR SVEFG FG Tevq:8002 Havgf:QSQ Ezx:ZNYR NG GUR RQHPNGVBA VAFG UNIVAT CEBOYRZF OERNGUVAT",
        "PNYY:1FG ERFC",
        "NQQE:146 ARNYF ZVYY EQ",
        "K:NHTHFGN UJL / FR SVEFG FG",
        "ZNC:8002",
        "HAVG:QSQ",
        "VASB:ZNYR NG GUR RQHPNGVBA VAFG UNIVAT CEBOYRZF OERNGUVAT");

    qbGrfg("G37",
        "{1FG ERFC} Ybp:1826 JNFUVATGBA EQ AR KFg:JRFGJBBQ QE AJ QNYYNF QE AR Tevq:2015 Havgf:FZ2 Ezx:",
        "PNYY:1FG ERFC",
        "NQQE:1826 JNFUVATGBA EQ AR",
        "K:JRFGJBBQ QE AJ / QNYYNF QE AR",
        "ZNC:2015",
        "HAVG:FZ2");

    qbGrfg("G38",
        "{1FG ERFC} Ybp:1423 QNYYNF QE AR KFg:PHYCRCCRE PVE A OEBJA QE AR Tevq:2014 Havgf:FZ2 Ezx:50 LBZ YBJ OYBBQ FHTNE UK BS QVNORGRF",
        "PNYY:1FG ERFC",
        "NQQE:1423 QNYYNF QE AR",
        "K:PHYCRCCRE PVE A / OEBJA QE AR",
        "ZNC:2014",
        "HAVG:FZ2",
        "VASB:50 LBZ YBJ OYBBQ FHTNE UK BS QVNORGRF");

    qbGrfg("G39",
        "{1FG ERFC} Ybp:1333 PNEY QE FR KFg:ZBBFR PYHO EQ F QRNQ RAQ Tevq:1018 Havgf:FZ1 Ezx:6 LBZ PURFG CNVA UNF N URNEG PBAQVGVBA",
        "PNYY:1FG ERFC",
        "NQQE:1333 PNEY QE FR",
        "K:ZBBFR PYHO EQ / F QRNQ RAQ",
        "ZNC:1018",
        "HAVG:FZ1",
        "VASB:6 LBZ PURFG CNVA UNF N URNEG PBAQVGVBA");

    qbGrfg("G40",
        "{1FG ERFC} Ybp:115 FUNAX FG KFg:ZNEGVA YHGURE X QRNA NI Tevq:1020 Havgf:R1Z Ezx:68 LE BYQ ZNYR SRRYF YVXR UR VF TBVAT GB CNFF BHG. UR VF VA GUR ONPX LNEQ VA GUR GEHPX",
        "PNYY:1FG ERFC",
        "NQQE:115 FUNAX FG",
        "K:ZNEGVA YHGURE X / QRNA NI",
        "ZNC:1020",
        "HAVG:R1Z",
        "VASB:68 LE BYQ ZNYR SRRYF YVXR UR VF TBVAT GB CNFF BHG. UR VF VA GUR ONPX LNEQ VA GUR GEHPX");

    qbGrfg("G41",
        "{1FG ERFC} Ybp:115 FUNAX FG KFg:ZNEGVA YHGURE X QRNA NI Tevq:1020 Havgf:FZ1 Ezx:68 LE BYQ ZNYR SRRYF YVXR UR VF TBVAT GB CNFF BHG. UR VF VA GUR ONPX LNEQ VA GUR GEHPX",
        "PNYY:1FG ERFC",
        "NQQE:115 FUNAX FG",
        "K:ZNEGVA YHGURE X / QRNA NI",
        "ZNC:1020",
        "HAVG:FZ1",
        "VASB:68 LE BYQ ZNYR SRRYF YVXR UR VF TBVAT GB CNFF BHG. UR VF VA GUR ONPX LNEQ VA GUR GEHPX");

    qbGrfg("G42",
        "{1FG ERFC} Ybp:664 NHTHFGN EQ FR KFg:FNYRZ EQ UNEEVFBA EQ FR Tevq:1009 Havgf:C11 Ezx:2 IRUVPYRF. 1 CNGVRAG JVGU ONPX CNVA. GURL NER OBGU VA GUR EBNQ",
        "PNYY:1FG ERFC",
        "NQQE:664 NHTHFGN EQ FR",
        "K:FNYRZ EQ / UNEEVFBA EQ FR",
        "ZNC:1009",
        "HAVG:C11",
        "VASB:2 IRUVPYRF. 1 CNGVRAG JVGU ONPX CNVA. GURL NER OBGU VA GUR EBNQ");

    qbGrfg("G43",
        "{1FG ERFC} Ybp:664 NHTHFGN EQ FR KFg:FNYRZ EQ UNEEVFBA EQ FR Tevq:1009 Havgf: Ezx:2 IRUVPYRF. 1 CNGVRAG JVGU ONPX CNVA. GURL NER OBGU VA GUR EBNQ",
        "PNYY:1FG ERFC",
        "NQQE:664 NHTHFGN EQ FR",
        "K:FNYRZ EQ / UNEEVFBA EQ FR",
        "ZNC:1009",
        "VASB:2 IRUVPYRF. 1 CNGVRAG JVGU ONPX CNVA. GURL NER OBGU VA GUR EBNQ");

    qbGrfg("G44",
        "{1FG ERFC} Ybp:664 NHTHFGN EQ FR KFg:FNYRZ EQ UNEEVFBA EQ FR Tevq:1009 Havgf:FZ1 Ezx:2 IRUVPYRF. 1 CNGVRAG JVGU ONPX CNVA. GURL NER OBGU VA GUR EBNQ",
        "PNYY:1FG ERFC",
        "NQQE:664 NHTHFGN EQ FR",
        "K:FNYRZ EQ / UNEEVFBA EQ FR",
        "ZNC:1009",
        "HAVG:FZ1",
        "VASB:2 IRUVPYRF. 1 CNGVRAG JVGU ONPX CNVA. GURL NER OBGU VA GUR EBNQ");

    qbGrfg("G45",
        "{1FG ERFC} Ybp:5100 WBARF EQ FR KFg:ARNYF ZVYY EQ F NYIVA ARNY EQ F Tevq:3002 Havgf:FZ3 FZ1 Ezx:55 LB SZ PURFG CNVA QBRF UNIR N CNPRZNXRE NAQ ERFC QVFGERFF",
        "PNYY:1FG ERFC",
        "NQQE:5100 WBARF EQ FR",
        "K:ARNYF ZVYY EQ F / NYIVA ARNY EQ F",
        "ZNC:3002",
        "HAVG:FZ3 FZ1",
        "VASB:55 LB SZ PURFG CNVA QBRF UNIR N CNPRZNXRE NAQ ERFC QVFGERFF");

    qbGrfg("G46",
        "{1FG ERFC} Ybp:5063 NHTHFGN UJL FR KFg:PVGL YVZVGF ENQSBEQ TNL EQ Tevq:3015 Havgf:FZ3 Ezx:NQIVFR ZNA NCG 4 WHZCRQ BA GUR ZTE WBUA",
        "PNYY:1FG ERFC",
        "NQQE:5063 NHTHFGN UJL FR",
        "K:PVGL YVZVGF / ENQSBEQ TNL EQ",
        "ZNC:3015",
        "HAVG:FZ3",
        "VASB:NQIVFR ZNA NCG 4 WHZCRQ BA GUR ZTE WBUA");

    qbGrfg("G47",
        "{1FG ERFC} Ybp:1096 OBARIVYYR EQ FR KFg:UNZCGBA-QNIVF E ENAQNYY-UHAG EQ Tevq:1017 Havgf:FZ1 Ezx:N JZ JRNEVAT N BENATR G FUVEG NAQ TEA PNZB FUBEGF VF YLVAT VA GUR QVGPU",
        "PNYY:1FG ERFC",
        "NQQE:1096 OBARIVYYR EQ FR",
        "K:UNZCGBA-QNIVF E / ENAQNYY-UHAG EQ",
        "ZNC:1017",
        "HAVG:FZ1",
        "VASB:N JZ JRNEVAT N BENATR G FUVEG NAQ TEA PNZB FUBEGF VF YLVAT VA GUR QVGPU");

    qbGrfg("G48",
        "{1FG ERFC} Ybp:1814 UBOOF ZVYY EQ FR KFg:ENQSBEQ-PHYOERG TEVRE JNER EQ F Tevq:5006 Havgf:FB16 FB10 FB13 Ezx:FHOWRPG WHFG TBG FGNOORQ. FBZRBAR GBYQ UVZ GB PNYY. UR FNVQ UR JNF JNYXVAT OL NAQ FBZRBAR GBYQ UVZ GB PNYY 911",
        "PNYY:1FG ERFC",
        "NQQE:1814 UBOOF ZVYY EQ FR",
        "K:ENQSBEQ-PHYOERG TEVRE / JNER EQ F",
        "ZNC:5006",
        "HAVG:FB16 FB10 FB13",
        "VASB:FHOWRPG WHFG TBG FGNOORQ. FBZRBAR GBYQ UVZ GB PNYY. UR FNVQ UR JNF JNYXVAT OL NAQ FBZRBAR GBYQ UVZ GB PNYY 911");

    qbGrfg("G49",
        "{1FG ERFC} Ybp:1814 UBOOF ZVYY EQ FR KFg:ENQSBEQ-PHYOERG TEVRE JNER EQ F Tevq:5006 Havgf:FB16 FB10 Ezx:FHOWRPG WHFG TBG FGNOORQ. FBZRBAR GBYQ UVZ GB PNYY. UR FNVQ UR JNF JNYXVAT OL NAQ FBZRBAR GBYQ UVZ GB PNYY 911",
        "PNYY:1FG ERFC",
        "NQQE:1814 UBOOF ZVYY EQ FR",
        "K:ENQSBEQ-PHYOERG TEVRE / JNER EQ F",
        "ZNC:5006",
        "HAVG:FB16 FB10",
        "VASB:FHOWRPG WHFG TBG FGNOORQ. FBZRBAR GBYQ UVZ GB PNYY. UR FNVQ UR JNF JNYXVAT OL NAQ FBZRBAR GBYQ UVZ GB PNYY 911");

    qbGrfg("G50",
        "{1FG ERFC} Ybp:1814 UBOOF ZVYY EQ FR KFg:ENQSBEQ-PHYOERG TEVRE JNER EQ F Tevq:5006 Havgf:FB16 Ezx:FHOWRPG WHFG TBG FGNOORQ. FBZRBAR GBYQ UVZ GB PNYY. UR FNVQ UR JNF JNYXVAT OL NAQ FBZRBAR GBYQ UVZ GB PNYY 911",
        "PNYY:1FG ERFC",
        "NQQE:1814 UBOOF ZVYY EQ FR",
        "K:ENQSBEQ-PHYOERG TEVRE / JNER EQ F",
        "ZNC:5006",
        "HAVG:FB16",
        "VASB:FHOWRPG WHFG TBG FGNOORQ. FBZRBAR GBYQ UVZ GB PNYY. UR FNVQ UR JNF JNYXVAT OL NAQ FBZRBAR GBYQ UVZ GB PNYY 911");

    qbGrfg("G51",
        "{1FG ERFC} Ybp:1814 UBOOF ZVYY EQ FR KFg:ENQSBEQ-PHYOERG TEVRE JNER EQ F Tevq:5006 Havgf: Ezx:FHOWRPG WHFG TBG FGNOORQ. FBZRBAR GBYQ UVZ GB PNYY. UR FNVQ UR JNF JNYXVAT OL NAQ FBZRBAR GBYQ UVZ GB PNYY 911",
        "PNYY:1FG ERFC",
        "NQQE:1814 UBOOF ZVYY EQ FR",
        "K:ENQSBEQ-PHYOERG TEVRE / JNER EQ F",
        "ZNC:5006",
        "VASB:FHOWRPG WHFG TBG FGNOORQ. FBZRBAR GBYQ UVZ GB PNYY. UR FNVQ UR JNF JNYXVAT OL NAQ FBZRBAR GBYQ UVZ GB PNYY 911");

    qbGrfg("G52",
        "{1FG ERFC} Ybp:1814 UBOOF ZVYY EQ FR KFg:ENQSBEQ-PHYOERG TEVRE JNER EQ F Tevq:5006 Havgf:FZ5 Ezx:FHOWRPG WHFG TBG FGNOORQ. FBZRBAR GBYQ UVZ GB PNYY. UR FNVQ UR JNF JNYXVAT OL NAQ FBZRBAR GBYQ UVZ GB PNYY 911",
        "PNYY:1FG ERFC",
        "NQQE:1814 UBOOF ZVYY EQ FR",
        "K:ENQSBEQ-PHYOERG TEVRE / JNER EQ F",
        "ZNC:5006",
        "HAVG:FZ5",
        "VASB:FHOWRPG WHFG TBG FGNOORQ. FBZRBAR GBYQ UVZ GB PNYY. UR FNVQ UR JNF JNYXVAT OL NAQ FBZRBAR GBYQ UVZ GB PNYY 911");

    qbGrfg("G53",
        "{1FG ERFC} Ybp:3668 RYYVATGBA NVEYVAR EQ FR KFg:ENQSBEQ-PHYOERG SVFU UNGPUREL E Tevq:3011 Havgf:FZ3 R1Z Ezx:47 L/B ZNYR YBJ OYBBQ FHTNE HAERFCBAFVIR",
        "PNYY:1FG ERFC",
        "NQQE:3668 RYYVATGBA NVEYVAR EQ FR",
        "K:ENQSBEQ-PHYOERG SVFU UNGPUREL E",
        "ZNC:3011",
        "HAVG:FZ3 R1Z",
        "VASB:47 L/B ZNYR YBJ OYBBQ FHTNE HAERFCBAFVIR");

    qbGrfg("G54",
        "{1FG ERFC} Ybp:3668 RYYVATGBA NVEYVAR EQ FR KFg:ENQSBEQ-PHYOERG SVFU UNGPUREL E Tevq:3011 Havgf:FZ3 FZ1 Ezx:47 L/B ZNYR YBJ OYBBQ FHTNE HAERFCBAFVIR",
        "PNYY:1FG ERFC",
        "NQQE:3668 RYYVATGBA NVEYVAR EQ FR",
        "K:ENQSBEQ-PHYOERG SVFU UNGPUREL E",
        "ZNC:3011",
        "HAVG:FZ3 FZ1",
        "VASB:47 L/B ZNYR YBJ OYBBQ FHTNE HAERFCBAFVIR");

    qbGrfg("G55",
        "{SVER/FGEHPGHER} Ybp:944 BYQ JNFUVATGBA EQ AR Ncg:13 KFg:PVGL YVZVGF QNYYNF QE AR Tevq:2015 Havgf:R2Z R1Z O6Z Ezx:FRR FZBXR NAQ ABG FHER VS VGF GUR JBBQF ORUVAQ GUR NCGF BE GUR ONPXFVQR BS GUR NCGF",
        "PNYY:SVER/FGEHPGHER",
        "NQQE:944 BYQ JNFUVATGBA EQ AR",
        "NCG:13",
        "K:PVGL YVZVGF / QNYYNF QE AR",
        "ZNC:2015",
        "HAVG:R2Z R1Z O6Z",
        "VASB:FRR FZBXR NAQ ABG FHER VS VGF GUR JBBQF ORUVAQ GUR NCGF BE GUR ONPXFVQR BS GUR NCGF");

    qbGrfg("G56",
        "{SVER/FGEHPGHER} Ybp:944 BYQ JNFUVATGBA EQ AR Ncg:13 KFg:PVGL YVZVGF QNYYNF QE AR Tevq:2015 Havgf:R2Z R1Z FZ6 Ezx:FRR FZBXR NAQ ABG FHER VS VGF GUR JBBQF ORUVAQ GUR NCGF BE GUR ONPXFVQR BS GUR NCGF",
        "PNYY:SVER/FGEHPGHER",
        "NQQE:944 BYQ JNFUVATGBA EQ AR",
        "NCG:13",
        "K:PVGL YVZVGF / QNYYNF QE AR",
        "ZNC:2015",
        "HAVG:R2Z R1Z FZ6",
        "VASB:FRR FZBXR NAQ ABG FHER VS VGF GUR JBBQF ORUVAQ GUR NCGF BE GUR ONPXFVQR BS GUR NCGF");

    qbGrfg("G57",
        "{SVER/FGEHPGHER} Ybp:944 BYQ JNFUVATGBA EQ AR Ncg:13 KFg:PVGL YVZVGF QNYYNF QE AR Tevq:2015 Havgf:FZ2 R1Z FZ6 Ezx:FRR FZBXR NAQ ABG FHER VS VGF GUR JBBQF ORUVAQ GUR NCGF BE GUR ONPXFVQR BS GUR NCGF",
        "PNYY:SVER/FGEHPGHER",
        "NQQE:944 BYQ JNFUVATGBA EQ AR",
        "NCG:13",
        "K:PVGL YVZVGF / QNYYNF QE AR",
        "ZNC:2015",
        "HAVG:FZ2 R1Z FZ6",
        "VASB:FRR FZBXR NAQ ABG FHER VS VGF GUR JBBQF ORUVAQ GUR NCGF BE GUR ONPXFVQR BS GUR NCGF");

    qbGrfg("G58",
        "{SVER/FGEHPGHER} Ybp:944 BYQ JNFUVATGBA EQ AR Ncg:13 KFg:PVGL YVZVGF QNYYNF QE AR Tevq:2015 Havgf:FZ2 FZ1 FZ6 Ezx:FRR FZBXR NAQ ABG FHER VS VGF GUR JBBQF ORUVAQ GUR NCGF BE GUR ONPXFVQR BS GUR NCGF",
        "PNYY:SVER/FGEHPGHER",
        "NQQE:944 BYQ JNFUVATGBA EQ AR",
        "NCG:13",
        "K:PVGL YVZVGF / QNYYNF QE AR",
        "ZNC:2015",
        "HAVG:FZ2 FZ1 FZ6",
        "VASB:FRR FZBXR NAQ ABG FHER VS VGF GUR JBBQF ORUVAQ GUR NCGF BE GUR ONPXFVQR BS GUR NCGF");

    qbGrfg("G59",
        "{1FG ERFC} Ybp:TVATRE UVYY EQ AR/UBARLFHPXYR YA AR KFg:JUVGRBNX EQ AR TVATRE UVYY RFG Tevq:6005 Havgf:FZ6 R1Z E2Z Ezx:2 IRUVPYRF...BAR FGVYY VA EBNQJNL. BAR FHOWRPG JVGU YNPRENGVBAF GB GUR URNQ",
        "PNYY:1FG ERFC",
        "NQQE:TVATRE UVYY EQ AR & UBARLFHPXYR YA AR",
        "K:JUVGRBNX EQ / AR TVATRE UVYY RFG",
        "ZNC:6005",
        "HAVG:FZ6 R1Z E2Z",
        "VASB:2 IRUVPYRF...BAR FGVYY VA EBNQJNL. BAR FHOWRPG JVGU YNPRENGVBAF GB GUR URNQ");

    qbGrfg("G60",
        "{1FG ERFC} Ybp:TVATRE UVYY EQ AR/UBARLFHPXYR YA AR KFg:JUVGRBNX EQ AR TVATRE UVYY RFG Tevq:6005 Havgf:FZ6 R1Z Ezx:2 IRUVPYRF...BAR FGVYY VA EBNQJNL. BAR FHOWRPG JVGU YNPRENGVBAF GB GUR URNQ",
        "PNYY:1FG ERFC",
        "NQQE:TVATRE UVYY EQ AR & UBARLFHPXYR YA AR",
        "K:JUVGRBNX EQ / AR TVATRE UVYY RFG",
        "ZNC:6005",
        "HAVG:FZ6 R1Z",
        "VASB:2 IRUVPYRF...BAR FGVYY VA EBNQJNL. BAR FHOWRPG JVGU YNPRENGVBAF GB GUR URNQ");

    qbGrfg("G61",
        "{1FG ERFC} Ybp:TVATRE UVYY EQ AR/UBARLFHPXYR YA AR KFg:JUVGRBNX EQ AR TVATRE UVYY RFG Tevq:6005 Havgf:FZ6 Ezx:2 IRUVPYRF...BAR FGVYY VA EBNQJNL. BAR FHOWRPG JVGU YNPRENGVBAF GB GUR URNQ",
        "PNYY:1FG ERFC",
        "NQQE:TVATRE UVYY EQ AR & UBARLFHPXYR YA AR",
        "K:JUVGRBNX EQ / AR TVATRE UVYY RFG",
        "ZNC:6005",
        "HAVG:FZ6",
        "VASB:2 IRUVPYRF...BAR FGVYY VA EBNQJNL. BAR FHOWRPG JVGU YNPRENGVBAF GB GUR URNQ");

    qbGrfg("G62",
        "{1FG ERFC} Ybp:214 PNZRYVN QE KFg:ZPTNURR NI ZBBER NI Tevq:8002 Havgf:QSQ Ezx:46 LBS QVNORGVP CEBOYRZ/RYRINGRQ OTY 263",
        "PNYY:1FG ERFC",
        "NQQE:214 PNZRYVN QE",
        "K:ZPTNURR NI / ZBBER NI",
        "ZNC:8002",
        "HAVG:QSQ",
        "VASB:46 LBS QVNORGVP CEBOYRZ/RYRINGRQ OTY 263");

    qbGrfg("G63",
        "{SVER/OEHFU} Ybp:JNFUVATGBA EQ AR/EHFFRYY'F YNAQVAT EQ AR KFg:EVQTR EQ AJ FZVGU ZVYY EQ A Tevq:2005 Havgf:FZ2 FZ4 Ezx:JNFU EQ NEBHAQ ZZ4 JVYY OR BA GUR FVQR BS GUR EBNQ",
        "PNYY:SVER/OEHFU",
        "NQQE:JNFUVATGBA EQ AR & EHFFRYY'F YNAQVAT EQ AR",
        "K:EVQTR EQ AJ / FZVGU ZVYY EQ A",
        "ZNC:2005",
        "HAVG:FZ2 FZ4",
        "VASB:JNFU EQ NEBHAQ ZZ4 JVYY OR BA GUR FVQR BS GUR EBNQ");

    qbGrfg("G64",
        "{1FG ERFC} Ybp:929 JUVGRBNX EQ FR KFg:FVYYF FG UNEEVFBA EQ AR Tevq:1021 Havgf:FZ1 Ezx:20 L/B SRZNYR FRIRE NOQBZVANY CNVA QHR ZNL 20......(JUVGR UBHFR ERQ EBBS BA GBC)",
        "PNYY:1FG ERFC",
        "NQQE:929 JUVGRBNX EQ FR",
        "K:FVYYF FG / UNEEVFBA EQ AR",
        "ZNC:1021",
        "HAVG:FZ1",
        "VASB:20 L/B SRZNYR FRIRE NOQBZVANY CNVA QHR ZNL 20......(JUVGR UBHFR ERQ EBBS BA GBC)");

    qbGrfg("G65",
        "{1FG ERFC} Ybp:5063 NHTHFGN UJL FR KFg:PVGL YVZVGF ENQSBEQ TNL EQ Tevq:3015 Havgf:FZ3 Ezx:10-50 V RAGENCZRAG",
        "PNYY:1FG ERFC",
        "NQQE:5063 NHTHFGN UJL FR",
        "K:PVGL YVZVGF / ENQSBEQ TNL EQ",
        "ZNC:3015",
        "HAVG:FZ3",
        "VASB:10-50 V RAGENCZRAG");

    qbGrfg("G66",
        "{SVER/NYNEZ} Ybp:690 NHTHFGN EQ FR KFg:FNYRZ EQ UNEEVFBA EQ FR Tevq:1009 Havgf:FZ1 FZ2 FZ5 Ezx:FUBJVAT FZBXR QRGRPGBE..UNYY SYBBE 2",
        "PNYY:SVER/NYNEZ",
        "NQQE:690 NHTHFGN EQ FR",
        "K:FNYRZ EQ / UNEEVFBA EQ FR",
        "ZNC:1009",
        "HAVG:FZ1 FZ2 FZ5",
        "VASB:FUBJVAT FZBXR QRGRPGBE..UNYY SYBBE 2");

    qbGrfg("G67",
        "{1FG ERFC} Ybp:219 IVBYN NIREL FG AJ KFg:QHAAF FG AJ UBRL FG AJ Tevq:1019 Havgf:FZ1 Ezx:44 L.B. ZNYR UNIVAT N FRVMHER",
        "PNYY:1FG ERFC",
        "NQQE:219 IVBYN NIREL FG AJ",
        "K:QHAAF FG AJ / UBRL FG AJ",
        "ZNC:1019",
        "HAVG:FZ1",
        "VASB:44 L.B. ZNYR UNIVAT N FRVMHER");

    qbGrfg("G68",
        "{1FG ERFC} Ybp:3635 QRNEVAT NPERF EQ FR KFg:URNQFGNYY YA FR QRNQ RAQ Tevq:3006 Havgf:FZ3 R1Z Ezx:58 LE BYQ ZNYR YBJ OTY",
        "PNYY:1FG ERFC",
        "NQQE:3635 QRNEVAT NPERF EQ FR",
        "K:URNQFGNYY YA / FR QRNQ RAQ",
        "ZNC:3006",
        "HAVG:FZ3 R1Z",
        "VASB:58 LE BYQ ZNYR YBJ OTY");

    qbGrfg("G69",
        "{1FG ERFC} Ybp:3635 QRNEVAT NPERF EQ FR KFg:URNQFGNYY YA FR QRNQ RAQ Tevq:3006 Havgf:FZ3 FZ1 Ezx:58 LE BYQ ZNYR YBJ OTY",
        "PNYY:1FG ERFC",
        "NQQE:3635 QRNEVAT NPERF EQ FR",
        "K:URNQFGNYY YA / FR QRNQ RAQ",
        "ZNC:3006",
        "HAVG:FZ3 FZ1",
        "VASB:58 LE BYQ ZNYR YBJ OTY");

    qbGrfg("G70",
        "{HAXABJA} Ybp:3815 JVYQJBBQ QE FR KFg:ENQSBEQ TNL EQ JVYQJBBQ PVE FR Tevq:3009 Havgf:FZ3 FZ1 FZ5 Ezx:URNIL FZBXR VA GUR NERN",
        "PNYY:HAXABJA",
        "NQQE:3815 JVYQJBBQ QE FR",
        "K:ENQSBEQ TNL EQ / JVYQJBBQ PVE FR",
        "ZNC:3009",
        "HAVG:FZ3 FZ1 FZ5",
        "VASB:URNIL FZBXR VA GUR NERN");

    qbGrfg("G71",
        "{1FG ERFC} Ybp:217 ZNETNERGF EQ FR KFg:JUVGRBNX EQ FR JVFUNZ EQ FR Tevq:1004 Havgf:R1Z Ezx:47 LRNE BYQ SRZNYR HAPBA OHG OERNGUVAT",
        "PNYY:1FG ERFC",
        "NQQE:217 ZNETNERGF EQ FR",
        "K:JUVGRBNX EQ FR / JVFUNZ EQ FR",
        "ZNC:1004",
        "HAVG:R1Z",
        "VASB:47 LRNE BYQ SRZNYR HAPBA OHG OERNGUVAT");

    qbGrfg("G72",
        "{1FG ERFC} Ybp:217 ZNETNERGF EQ FR KFg:JUVGRBNX EQ FR JVFUNZ EQ FR Tevq:1004 Havgf:FZ1 Ezx:47 LRNE BYQ SRZNYR HAPBA OHG OERNGUVAT",
        "PNYY:1FG ERFC",
        "NQQE:217 ZNETNERGF EQ FR",
        "K:JUVGRBNX EQ FR / JVFUNZ EQ FR",
        "ZNC:1004",
        "HAVG:FZ1",
        "VASB:47 LRNE BYQ SRZNYR HAPBA OHG OERNGUVAT");

    qbGrfg("G73",
        "{1FG ERFC} Ybp:1023 HAVBA PUHEPU EQ AJ KFg:ZRFRAN EQ AJ SBFGRE-FCEBHFR Tevq:1001 Havgf:FZ1 Ezx:OR VA UVF IRUVPYR N TEL PURI VZCNYN ARRQ NFFG TRGGVAT BHG BS UVF IRUVPYR VAGB GUR UBHFR,",
        "PNYY:1FG ERFC",
        "NQQE:1023 HAVBA PUHEPU EQ AJ",
        "K:ZRFRAN EQ / AJ SBFGRE-FCEBHFR",
        "ZNC:1001",
        "HAVG:FZ1",
        "VASB:OR VA UVF IRUVPYR N TEL PURI VZCNYN ARRQ NFFG TRGGVAT BHG BS UVF IRUVPYR VAGB GUR UBHFR,");

  }

  @Grfg
  choyvp ibvq grfgGUBZFBASQ() {

    qbGrfg("G1",
        "{1 EFC/PVGL} Ybp:638 ZNGGURJ FG FJ KFg:NAFYRL QE EBOVA FG Tevq:7003 Havgf:R703 Ezx:92 LB SZ FNLF FUR VF QVMML NAQ PNAG BCRA GUR QBBE.",
        "PNYY:1 EFC/PVGL",
        "NQQE:638 ZNGGURJ FG FJ",
        "K:NAFYRL QE / EBOVA FG",
        "ZNC:7003",
        "HAVG:R703",
        "VASB:92 LB SZ FNLF FUR VF QVMML NAQ PNAG BCRA GUR QBBE.");

    qbGrfg("G2",
        "{1 EFC/PVGL} Ybp:209 NAFYRL QE Ncg:37 KFg:WBUAFBA NI UVYY FG Tevq:7003 Havgf:R703 Ezx:1 LBS FRVMHER UK BS FRVMHER",
        "PNYY:1 EFC/PVGL",
        "NQQE:209 NAFYRL QE",
        "NCG:37",
        "K:WBUAFBA NI / UVYY FG",
        "ZNC:7003",
        "HAVG:R703",
        "VASB:1 LBS FRVMHER UK BS FRVMHER");

    qbGrfg("G3",
        "{1 EFC/PVGL} Ybp:209 NAFYRL QE Ncg:37 KFg:WBUAFBA NI UVYY FG Tevq:7003 Havgf:R704 Ezx:1 LBS FRVMHER UK BS FRVMHER",
        "PNYY:1 EFC/PVGL",
        "NQQE:209 NAFYRL QE",
        "NCG:37",
        "K:WBUAFBA NI / UVYY FG",
        "ZNC:7003",
        "HAVG:R704",
        "VASB:1 LBS FRVMHER UK BS FRVMHER");

    qbGrfg("G4",
        "{1 EFC/PVGL} Ybp:2205 UNEEVFBA EQ AR KFg:JNYAHG FG ZNVA FG Tevq:7002 Havgf:R705 Ezx:ERQ PEBJA IVP NAQ N SZ JVYY ABG YRG N ZNYR TRG BHG BS GUR PNE",
        "PNYY:1 EFC/PVGL",
        "NQQE:2205 UNEEVFBA EQ AR",
        "K:JNYAHG FG / ZNVA FG",
        "ZNC:7002",
        "HAVG:R705",
        "VASB:ERQ PEBJA IVP NAQ N SZ JVYY ABG YRG N ZNYR TRG BHG BS GUR PNE");

    qbGrfg("G5",
        "{1 EFC/PVGL} Ybp:218 WNPXFBA FG Ncg:15 KFg:ZNVA FG JERAF UJL FR Tevq:7004 Havgf:C7 Ezx:82 LB ZNYR ABG OERNGUVAT",
        "PNYY:1 EFC/PVGL",
        "NQQE:218 WNPXFBA FG",
        "NCG:15",
        "K:ZNVA FG / JERAF UJL FR",
        "ZNC:7004",
        "HAVG:C7",
        "VASB:82 LB ZNYR ABG OERNGUVAT");

    qbGrfg("G6",
        "{1 EFC/PVGL} Ybp:218 WNPXFBA FG Ncg:15 KFg:ZNVA FG JERAF UJL FR Tevq:7004 Havgf: Ezx:82 LB ZNYR ABG OERNGUVAT",
        "PNYY:1 EFC/PVGL",
        "NQQE:218 WNPXFBA FG",
        "NCG:15",
        "K:ZNVA FG / JERAF UJL FR",
        "ZNC:7004",
        "VASB:82 LB ZNYR ABG OERNGUVAT");

    qbGrfg("G7",
        "{1 EFC/PVGL} Ybp:218 WNPXFBA FG Ncg:15 KFg:ZNVA FG JERAF UJL FR Tevq:7004 Havgf:R703 Ezx:82 LB ZNYR ABG OERNGUVAT",
        "PNYY:1 EFC/PVGL",
        "NQQE:218 WNPXFBA FG",
        "NCG:15",
        "K:ZNVA FG / JERAF UJL FR",
        "ZNC:7004",
        "HAVG:R703",
        "VASB:82 LB ZNYR ABG OERNGUVAT");

    qbGrfg("G8",
        "{1 EFC/PVGL} Ybp:218 WNPXFBA FG Ncg:15 KFg:ZNVA FG JERAF UJL FR Tevq:7004 Havgf:R704 Ezx:82 LB ZNYR ABG OERNGUVAT",
        "PNYY:1 EFC/PVGL",
        "NQQE:218 WNPXFBA FG",
        "NCG:15",
        "K:ZNVA FG / JERAF UJL FR",
        "ZNC:7004",
        "HAVG:R704",
        "VASB:82 LB ZNYR ABG OERNGUVAT");

    qbGrfg("G9",
        "{1 EFC/PVGL} Ybp:524 ZNEGVA YHGURE XVAT WE FG KFg:TBEQBA FG JVYFBA FG Tevq:7002 Havgf:R705 Ezx:92 LBS VAWHEVRF FRPBAQNEL GB N SNYY HAQRE GUVF ZBEAVAT UNIVAT GEBHOYR ZBIVAT YRSG YRT,",
        "PNYY:1 EFC/PVGL",
        "NQQE:524 ZNEGVA YHGURE XVAT WE FG",
        "K:TBEQBA FG / JVYFBA FG",
        "ZNC:7002",
        "HAVG:R705",
        "VASB:92 LBS VAWHEVRF FRPBAQNEL GB N SNYY HAQRE GUVF ZBEAVAT UNIVAT GEBHOYR ZBIVAT YRSG YRT,");

    qbGrfg("G10",
        "{1 EFC/PVGL} Ybp:130 R URAQEVPXF FG Ncg:N KFg:WNPXFBA FG TERRAJNL FG Tevq:7004 Havgf:R705 Ezx:46 LBZ PURFG CNVA",
        "PNYY:1 EFC/PVGL",
        "NQQE:130 R URAQEVPXF FG",
        "NCG:N",
        "K:WNPXFBA FG / TERRAJNL FG",
        "ZNC:7004",
        "HAVG:R705",
        "VASB:46 LBZ PURFG CNVA");

    qbGrfg("G11",
        "{1 EFC/PVGL} Ybp:130 R URAQEVPXF FG Ncg:N KFg:WNPXFBA FG TERRAJNL FG Tevq:7004 Havgf:R704 Ezx:46 LBZ PURFG CNVA",
        "PNYY:1 EFC/PVGL",
        "NQQE:130 R URAQEVPXF FG",
        "NCG:N",
        "K:WNPXFBA FG / TERRAJNL FG",
        "ZNC:7004",
        "HAVG:R704",
        "VASB:46 LBZ PURFG CNVA");

    qbGrfg("G12",
        "{1 EFC/PVGL} Ybp:513 CVAR PG KFg:ZNEGVA YHGURE X TBEQBA FG Tevq:7002 Havgf:R705 Ezx:64LBZ QVSSVPHYGL OERNGUVAT NAQ JRNX",
        "PNYY:1 EFC/PVGL",
        "NQQE:513 CVAR PG",
        "K:ZNEGVA YHGURE X / TBEQBA FG",
        "ZNC:7002",
        "HAVG:R705",
        "VASB:64LBZ QVSSVPHYGL OERNGUVAT NAQ JRNX");

    qbGrfg("G13",
        "{1 EFC/PVGL} Ybp:ZVPUNRY FG/YRR QE KFg:FGBARJNYY QE FNYRZ EQ Tevq:7004 Havgf:R704 Ezx:BO RZRETRAPL VA N PNE FVYIRE PEHMR BA GUR EBNQJNL/YNOBE",
        "PNYY:1 EFC/PVGL",
        "NQQE:ZVPUNRY FG & YRR QE",
        "K:FGBARJNYY QE / FNYRZ EQ",
        "ZNC:7004",
        "HAVG:R704",
        "VASB:BO RZRETRAPL VA N PNE FVYIRE PEHMR BA GUR EBNQJNL/YNOBE");

    qbGrfg("G14",
        "{1 EFC/PVGL} Ybp:719 ZNGGURJ FG FJ KFg:NAFYRL QE EBOVA FG Tevq:7003 Havgf:R704 Ezx:46 LBZ QVNORGVP CEBOYRZF OYBBQ FHTNE VF RYRINGRQ",
        "PNYY:1 EFC/PVGL",
        "NQQE:719 ZNGGURJ FG FJ",
        "K:NAFYRL QE / EBOVA FG",
        "ZNC:7003",
        "HAVG:R704",
        "VASB:46 LBZ QVNORGVP CEBOYRZF OYBBQ FHTNE VF RYRINGRQ");

    qbGrfg("G15",
        "{1 EFC/PVGL} Ybp:318 GBZ JNGFBA JNL KFg:ZNVA FG YHZCXVA FG Tevq:7001 Havgf:R704 Ezx:86 L/B SRZNYR UNF SNYYRA PNA ABG TRG HC,,UNF NEGVSVPVNY YRTF..",
        "PNYY:1 EFC/PVGL",
        "NQQE:318 GBZ JNGFBA JNL",
        "K:ZNVA FG / YHZCXVA FG",
        "ZNC:7001",
        "HAVG:R704",
        "VASB:86 L/B SRZNYR UNF SNYYRA PNA ABG TRG HC,,UNF NEGVSVPVNY YRTF..");

    qbGrfg("G16",
        "{SVER/NYNEZ} Ybp:1861 UNEEVFBA EQ AR KFg:JNYAHG FG ZNVA FG AR Tevq:7002 Havgf:R705 Y707 Ezx:TRARENY SVER>>>>>>>>>>>>>>800-230-6975<<<<<<<<<<<<<7114",
        "PNYY:SVER/NYNEZ",
        "NQQE:1861 UNEEVFBA EQ AR",
        "K:JNYAHG FG / ZNVA FG AR",
        "ZNC:7002",
        "HAVG:R705 Y707",
        "VASB:TRARENY SVER>>>>>>>>>>>>>>800-230-6975<<<<<<<<<<<<<7114");

    qbGrfg("G17",
        "{1 EFC/PVGL} Ybp:413 YRR QE KFg:ZNANFFNF QE ZVPUNRY FG Tevq:7004 Havgf:R704 Ezx:31 LRNE BYQ ZNYR FRVMHERF",
        "PNYY:1 EFC/PVGL",
        "NQQE:413 YRR QE",
        "K:ZNANFFNF QE / ZVPUNRY FG",
        "ZNC:7004",
        "HAVG:R704",
        "VASB:31 LRNE BYQ ZNYR FRVMHERF");

    qbGrfg("G18",
        "{1 EFC/PVGL} Ybp:1043 JNFUVATGBA EQ AJ KFg:JEVTUGFOBEB EQ ABOYR FG AJ Tevq:7001 Havgf:R705 Ezx:SJZNYR CNGVRAG VA N JUVGR INA HAERFCBAFVIR. CNGVRAG VF OERNGUVAT",
        "PNYY:1 EFC/PVGL",
        "NQQE:1043 JNFUVATGBA EQ AJ",
        "K:JEVTUGFOBEB EQ / ABOYR FG AJ",
        "ZNC:7001",
        "HAVG:R705",
        "VASB:SJZNYR CNGVRAG VA N JUVGR INA HAERFCBAFVIR. CNGVRAG VF OERNGUVAT");

    qbGrfg("G19",
        "{CHO FIF PNYY} Ybp:B'ARNY FG/P'OBNEQ JNL KFg:ENVYEBNQ FG FVYYF FG Tevq:7002 Havgf:P701 Ezx:CBFFVOYR ZVFFVAT PUVYQ BA GUR EE GENPXF. AB PYBGUVAT QRFPEVCGVBA.",
        "PNYY:CHO FIF PNYY",
        "NQQE:B'ARNY FG & P'OBNEQ JNL",
        "K:ENVYEBNQ FG / FVYYF FG",
        "ZNC:7002",
        "HAVG:P701",
        "VASB:CBFFVOYR ZVFFVAT PUVYQ BA GUR EE GENPXF. AB PYBGUVAT QRFPEVCGVBA.");

    qbGrfg("G20",
        "{1 EFC/PVGL} Ybp:751 CHOYVP FNSRGL QE Ncg:WNVY KFg:UNEEVFBA EQ FR NHTHFGN EQ FR Tevq:7004 Havgf:R703 Ezx:25 LB ZNYR YBJ OYBBQ FHTNE",
        "PNYY:1 EFC/PVGL",
        "NQQE:751 CHOYVP FNSRGL QE",
        "NCG:WNVY",
        "K:UNEEVFBA EQ FR / NHTHFGN EQ FR",
        "ZNC:7004",
        "HAVG:R703",
        "VASB:25 LB ZNYR YBJ OYBBQ FHTNE");

    qbGrfg("G21",
        "{1 EFC/PVGL} Ybp:751 CHOYVP FNSRGL QE Ncg:WNVY KFg:UNEEVFBA EQ FR NHTHFGN EQ FR Tevq:7004 Havgf:R705 Ezx:25 LB ZNYR YBJ OYBBQ FHTNE",
        "PNYY:1 EFC/PVGL",
        "NQQE:751 CHOYVP FNSRGL QE",
        "NCG:WNVY",
        "K:UNEEVFBA EQ FR / NHTHFGN EQ FR",
        "ZNC:7004",
        "HAVG:R705",
        "VASB:25 LB ZNYR YBJ OYBBQ FHTNE");

    qbGrfg("G22",
        "{CHO FIF PNYY} Ybp:324 TBEQBA FG KFg:ZNVA FG RYYVATGBA NI Tevq:7002 Havgf:R705 Ezx:NQIVFR FBPXRGF FCNEXVAT SVER",
        "PNYY:CHO FIF PNYY",
        "NQQE:324 TBEQBA FG",
        "K:ZNVA FG / RYYVATGBA NI",
        "ZNC:7002",
        "HAVG:R705",
        "VASB:NQIVFR FBPXRGF FCNEXVAT SVER");

    qbGrfg("G23",
        "{1 EFC/PVGL} Ybp:941 XRAARQL PVE KFg:JEVTUGFOBEB EQ ORGFL OENAPU QE Tevq:7001 Havgf:R705 Ezx:SRZNYR NQIVFRQ FURF NOBHG GB SNVAG. FUR VF UBZR NYBAR NAQ GELVAT GB BCRA GUR QBBE",
        "PNYY:1 EFC/PVGL",
        "NQQE:941 XRAARQL PVE",
        "K:JEVTUGFOBEB EQ / ORGFL OENAPU QE",
        "ZNC:7001",
        "HAVG:R705",
        "VASB:SRZNYR NQIVFRQ FURF NOBHG GB SNVAG. FUR VF UBZR NYBAR NAQ GELVAT GB BCRA GUR QBBE");

    qbGrfg("G24",
        "{1 EFC/PVGL} Ybp:513 ZNEGVA YHGURE XVAT WE FG KFg:TBEQBA FG JVYFBA FG Tevq:7002 Havgf:R705 Ezx:7 ZB SRZNYR RYRINGRQ GRZC",
        "PNYY:1 EFC/PVGL",
        "NQQE:513 ZNEGVA YHGURE XVAT WE FG",
        "K:TBEQBA FG / JVYFBA FG",
        "ZNC:7002",
        "HAVG:R705",
        "VASB:7 ZB SRZNYR RYRINGRQ GRZC");

    qbGrfg("G25",
        "{1 EFC/PVGL} Ybp:973 XRAARQL PVE KFg:JEVTUGFOBEB EQ ORGFL OENAPU QE Tevq:7001 Havgf:R705 Ezx:ZRQVPNY NYNEZ 78 LBS HAX ERNFBAF 888-289-2018 HANOYR GB ZNXR PBAGNPG BCRE WHYVR UK BS",
        "PNYY:1 EFC/PVGL",
        "NQQE:973 XRAARQL PVE",
        "K:JEVTUGFOBEB EQ / ORGFL OENAPU QE",
        "ZNC:7001",
        "HAVG:R705",
        "VASB:ZRQVPNY NYNEZ 78 LBS HAX ERNFBAF 888-289-2018 HANOYR GB ZNXR PBAGNPG BCRE WHYVR UK BS");

    qbGrfg("G26",
        "{1 EFC/PVGL} Ybp:210 JUVGRBNX FG KFg:ZNVA FG UBYG FG Tevq:7002 Havgf:R705 Ezx:",
        "PNYY:1 EFC/PVGL",
        "NQQE:210 JUVGRBNX FG",
        "K:ZNVA FG / UBYG FG",
        "ZNC:7002",
        "HAVG:R705");

    qbGrfg("G27",
        "{1 EFC/PVGL} Ybp:221 CRPNA NI KFg:JUVGRBNX EQ AR JNYAHG FG Tevq:7002 Havgf:R705 Ezx:19 LE BYQ ZNYR PNYIVA OEBJA WHFG UNQ N FRVMHER NAQ GURL NER ERDHRFGVAT NZOHYNAPR",
        "PNYY:1 EFC/PVGL",
        "NQQE:221 CRPNA NI",
        "ZNQQE:221 CRPNA NIR",
        "K:JUVGRBNX EQ / AR JNYAHG FG",
        "ZNC:7002",
        "HAVG:R705",
        "VASB:19 LE BYQ ZNYR PNYIVA OEBJA WHFG UNQ N FRVMHER NAQ GURL NER ERDHRFGVAT NZOHYNAPR");

    qbGrfg("G28",
        "{1 EFC/PVGL} Ybp:607 WBARF EQ KFg:JUVGRBNX EQ AR UBYG FG Tevq:7002 Havgf:R705 Ezx:39 LE BYQ SRZNYR PURFG CNVA JVGU UVTU OC. UBHFR JVGU OHETNAQL QBBE",
        "PNYY:1 EFC/PVGL",
        "NQQE:607 WBARF EQ",
        "K:JUVGRBNX EQ / AR UBYG FG",
        "ZNC:7002",
        "HAVG:R705",
        "VASB:39 LE BYQ SRZNYR PURFG CNVA JVGU UVTU OC. UBHFR JVGU OHETNAQL QBBE");

    qbGrfg("G29",
        "{1 EFC/PVGL} Ybp:101 R UVYY FG KFg:WNPXFBA FG PVGL YVZVGF Tevq:7004 Havgf:R704 Ezx:29 LRNE BYQ SRZNYR FRVMHER",
        "PNYY:1 EFC/PVGL",
        "NQQE:101 R UVYY FG",
        "K:WNPXFBA FG / PVGL YVZVGF",
        "ZNC:7004",
        "HAVG:R704",
        "VASB:29 LRNE BYQ SRZNYR FRVMHER");

    qbGrfg("G30",
        "{1 EFC/PVGL} Ybp:640 ORRPUJBBQ QE KFg:YRR FG A ZNTABYVN QE Tevq:7001 Havgf:R705 Ezx:80 LBS HANOYR FGNAQ FRPBAQNEL GB SNYY SEBZ LRFGREQNL NAQ ERSHFR GENACBEG, JRNX",
        "PNYY:1 EFC/PVGL",
        "NQQE:640 ORRPUJBBQ QE",
        "K:YRR FG / A ZNTABYVN QE",
        "ZNC:7001",
        "HAVG:R705",
        "VASB:80 LBS HANOYR FGNAQ FRPBAQNEL GB SNYY SEBZ LRFGREQNL NAQ ERSHFR GENACBEG, JRNX");

    qbGrfg("G31",
        "{SVER/FGEHPGHER} Ybp:944 BYQ JNFUVATGBA EQ AR Ncg:13 KFg:PVGL YVZVGF QNYYNF QE AR Tevq:2015 Havgf:R705 Ezx:FRR FZBXR NAQ ABG FHER VS VGF GUR JBBQF ORUVAQ GUR NCGF BE GUR ONPXFVQR BS GUR NCGF",
        "PNYY:SVER/FGEHPGHER",
        "NQQE:944 BYQ JNFUVATGBA EQ AR",
        "NCG:13",
        "K:PVGL YVZVGF / QNYYNF QE AR",
        "ZNC:2015",
        "HAVG:R705",
        "VASB:FRR FZBXR NAQ ABG FHER VS VGF GUR JBBQF ORUVAQ GUR NCGF BE GUR ONPXFVQR BS GUR NCGF");

    qbGrfg("G32",
        "{SVER/FGEHPGHER} Ybp:944 BYQ JNFUVATGBA EQ AR Ncg:13 KFg:PVGL YVZVGF QNYYNF QE AR Tevq:2015 Havgf: Ezx:FRR FZBXR NAQ ABG FHER VS VGF GUR JBBQF ORUVAQ GUR NCGF BE GUR ONPXFVQR BS GUR NCGF",
        "PNYY:SVER/FGEHPGHER",
        "NQQE:944 BYQ JNFUVATGBA EQ AR",
        "NCG:13",
        "K:PVGL YVZVGF / QNYYNF QE AR",
        "ZNC:2015",
        "VASB:FRR FZBXR NAQ ABG FHER VS VGF GUR JBBQF ORUVAQ GUR NCGF BE GUR ONPXFVQR BS GUR NCGF");

    qbGrfg("G33",
        "{1 EFC/PVGL} Ybp:635 ORHYNU YA KFg:ZNP YA XVAT YA Tevq:7003 Havgf:R704 Ezx:23 LE BYQ ZNYR WHFG SNVAGRQ BA GUR SYBBE. UR VF OERNGUVAT. UR VF NHFGVP",
        "PNYY:1 EFC/PVGL",
        "NQQE:635 ORHYNU YA",
        "K:ZNP YA / XVAT YA",
        "ZNC:7003",
        "HAVG:R704",
        "VASB:23 LE BYQ ZNYR WHFG SNVAGRQ BA GUR SYBBE. UR VF OERNGUVAT. UR VF NHFGVP");

    qbGrfg("G34",
        "{1 EFC/PVGL} Ybp:107 JUVGRBNX FGERRG RKG Ncg:48 KFg:JUVGRBNX FG WBARF EQ Tevq:7002 Havgf:R704 R706 Ezx:ZRQVPNY NYNEZ HANOYR GB PBAGNPG CNGVRAG........800-268-3453......314",
        "PNYY:1 EFC/PVGL",
        "NQQE:107 JUVGRBNX FGERRG RKG",
        "NCG:48",
        "K:JUVGRBNX FG / WBARF EQ",
        "ZNC:7002",
        "HAVG:R704 R706",
        "VASB:ZRQVPNY NYNEZ HANOYR GB PBAGNPG CNGVRAG........800-268-3453......314");

    qbGrfg("G35",
        "{1 EFC/PVGL} Ybp:107 JUVGRBNX FGERRG RKG Ncg:48 KFg:JUVGRBNX FG WBARF EQ Tevq:7002 Havgf:R704 Ezx:ZRQVPNY NYNEZ HANOYR GB PBAGNPG CNGVRAG........800-268-3453......314",
        "PNYY:1 EFC/PVGL",
        "NQQE:107 JUVGRBNX FGERRG RKG",
        "NCG:48",
        "K:JUVGRBNX FG / WBARF EQ",
        "ZNC:7002",
        "HAVG:R704",
        "VASB:ZRQVPNY NYNEZ HANOYR GB PBAGNPG CNGVRAG........800-268-3453......314");

    qbGrfg("G36",
        "{1 EFC/PVGL} Ybp:126 YVAPBYA QE KFg:JUVGRBNX EQ AR ZBOYRL FG Tevq:7001 Havgf:R705 Ezx:RYQREYL SRZNYR SBHAQ OL TENAQXVQF HAERFCBAFVIR.",
        "PNYY:1 EFC/PVGL",
        "NQQE:126 YVAPBYA QE",
        "K:JUVGRBNX EQ / AR ZBOYRL FG",
        "ZNC:7001",
        "HAVG:R705",
        "VASB:RYQREYL SRZNYR SBHAQ OL TENAQXVQF HAERFCBAFVIR.");

    qbGrfg("G37",
        "{1 EFC/PVGL} Ybp:307 TERRAJNL FG Ncg:2 KFg:TBEQBA FG URAQEVPXF FG J Tevq:7002 Havgf:R705 Ezx:53 L.B. SRZNYR...HAPBAFPVBHF",
        "PNYY:1 EFC/PVGL",
        "NQQE:307 TERRAJNL FG",
        "NCG:2",
        "K:TBEQBA FG / URAQEVPXF FG J",
        "ZNC:7002",
        "HAVG:R705",
        "VASB:53 L.B. SRZNYR...HAPBAFPVBHF");

    qbGrfg("G38",
        "{1 EFC/PVGL} Ybp:410 THF FG KFg:QVKVR QE QRYY QE Tevq:7004 Havgf:R704 Ezx:RINYHNGVBA BA N ZNYR FHOWRPG. YNJ RASBEPRZRAG VF CERFRAG",
        "PNYY:1 EFC/PVGL",
        "NQQE:410 THF FG",
        "K:QVKVR QE / QRYY QE",
        "ZNC:7004",
        "HAVG:R704",
        "VASB:RINYHNGVBA BA N ZNYR FHOWRPG. YNJ RASBEPRZRAG VF CERFRAG");

    qbGrfg("G39",
        "{1 EFC/PVGL} Ybp:138 XVATFGBJA JL Ncg:304 KFg:WNPXFBA FG QRNQ RAQ Tevq:7004 Havgf:R703 Ezx:69 LBS SNYYRA HAXABJA VAWHEVRF/CP 3901/XRL BHGFVQR HAQRE CVT/QBBE FUBHYQ OR HAYBPXRQ",
        "PNYY:1 EFC/PVGL",
        "NQQE:138 XVATFGBJA JL",
        "NCG:304",
        "K:WNPXFBA FG / QRNQ RAQ",
        "ZNC:7004",
        "HAVG:R703",
        "VASB:69 LBS SNYYRA HAXABJA VAWHEVRF/CP 3901/XRL BHGFVQR HAQRE CVT/QBBE FUBHYQ OR HAYBPXRQ");

    qbGrfg("G40",
        "{1 EFC/PVGL} Ybp:896 FPBGG PG KFg:ORGFL OENAPU QE JEVTUGFOBEB EQ Tevq:7001 Havgf:R705 Ezx:72 LE BYQ ZNYR CBFFVOYR YBJ OTY. UR VF FJRNGVAT. UK BS QVNORGVP",
        "PNYY:1 EFC/PVGL",
        "NQQE:896 FPBGG PG",
        "K:ORGFL OENAPU QE / JEVTUGFOBEB EQ",
        "ZNC:7001",
        "HAVG:R705",
        "VASB:72 LE BYQ ZNYR CBFFVOYR YBJ OTY. UR VF FJRNGVAT. UK BS QVNORGVP");

    qbGrfg("G41",
        "{1 EFC/PVGL} Ybp:138 XVATFGBJA JL Ncg:304 KFg:WNPXFBA FG QRNQ RAQ Tevq:7004 Havgf:R703 Ezx:69 LBS HANOYR GB PBAGNPG FHOWRPG YVSR NYREG 800-638-8222 BCRE 1020 UK BS URNEG CEBOYRZF/QVNORGRF/OENVA PNAPRE/UVTU OC",
        "PNYY:1 EFC/PVGL",
        "NQQE:138 XVATFGBJA JL",
        "NCG:304",
        "K:WNPXFBA FG / QRNQ RAQ",
        "ZNC:7004",
        "HAVG:R703",
        "VASB:69 LBS HANOYR GB PBAGNPG FHOWRPG YVSR NYREG 800-638-8222 BCRE 1020 UK BS URNEG CEBOYRZF/QVNORGRF/OENVA PNAPRE/UVTU OC");

    qbGrfg("G42",
        "{1 EFC/PVGL} Ybp:751 CHOYVP FNSRGL QE Ncg:WNVY KFg:UNEEVFBA EQ FR NHTHFGN EQ FR Tevq:7004 Havgf:R703 Ezx:48 LBS ENA BHG BS BKLTRA UK BS CHYZBAL ULCREGRAFVBA",
        "PNYY:1 EFC/PVGL",
        "NQQE:751 CHOYVP FNSRGL QE",
        "NCG:WNVY",
        "K:UNEEVFBA EQ FR / NHTHFGN EQ FR",
        "ZNC:7004",
        "HAVG:R703",
        "VASB:48 LBS ENA BHG BS BKLTRA UK BS CHYZBAL ULCREGRAFVBA");

    qbGrfg("G43",
        "{1 EFC/PVGL} Ybp:617 ZNEGVA YHGURE XVAT WE FG KFg:TBEQBA FG JVYFBA FG Tevq:7002 Havgf:R705 Ezx:40A LBZ ERFC QVFGERFF UK BS PUS",
        "PNYY:1 EFC/PVGL",
        "NQQE:617 ZNEGVA YHGURE XVAT WE FG",
        "K:TBEQBA FG / JVYFBA FG",
        "ZNC:7002",
        "HAVG:R705",
        "VASB:40A LBZ ERFC QVFGERFF UK BS PUS");

    qbGrfg("G44",
        "{1 EFC/PVGL} Ybp:643 ZNVA FG AJ KFg:ENVYEBNQ FG JEVTUGFOBEB EQ Tevq:7001 Havgf:R705 Ezx:55 LE BYQ ZNYR QVSS OERNGUVAT NAQ PURFG CNVAF",
        "PNYY:1 EFC/PVGL",
        "NQQE:643 ZNVA FG AJ",
        "K:ENVYEBNQ FG / JEVTUGFOBEB EQ",
        "ZNC:7001",
        "HAVG:R705",
        "VASB:55 LE BYQ ZNYR QVSS OERNGUVAT NAQ PURFG CNVAF");

    qbGrfg("G45",
        "{1 EFC/PVGL} Ybp:602 RQVGU FG KFg:JUVGRBNX FG WBARF EQ Tevq:7002 Havgf:R705 Ezx:BYQRE SRZNYR UNIVAT N FRVMHER. FUR VF VAFVQR GUR UBHFR.",
        "PNYY:1 EFC/PVGL",
        "NQQE:602 RQVGU FG",
        "K:JUVGRBNX FG / WBARF EQ",
        "ZNC:7002",
        "HAVG:R705",
        "VASB:BYQRE SRZNYR UNIVAT N FRVMHER. FUR VF VAFVQR GUR UBHFR.");

    qbGrfg("G46",
        "{1 EFC/PVGL} Ybp:1016 CRPNA PG KFg:CRPNA NI JUVGRBNX EQ AR Tevq:7002 Havgf:R705 Ezx:71 LB SZ FGNCYR PNZR BHG BS FHETVPNY JBHAQ",
        "PNYY:1 EFC/PVGL",
        "NQQE:1016 CRPNA PG",
        "K:CRPNA NI / JUVGRBNX EQ AR",
        "ZNC:7002",
        "HAVG:R705",
        "VASB:71 LB SZ FGNCYR PNZR BHG BS FHETVPNY JBHAQ");

    qbGrfg("G47",
        "{1 EFC/PVGL} Ybp:450 WNPXFBA FG KFg:ZNVA FG JERAF UJL FR Tevq:7004 Havgf:R703 Ezx:60 LBZ VA/BHG BES PBAPPVBHFARFF UK BS ULCRAGRAFVBA",
        "PNYY:1 EFC/PVGL",
        "NQQE:450 WNPXFBA FG",
        "K:ZNVA FG / JERAF UJL FR",
        "ZNC:7004",
        "HAVG:R703",
        "VASB:60 LBZ VA/BHG BES PBAPPVBHFARFF UK BS ULCRAGRAFVBA");

    qbGrfg("G48",
        "{1 EFC/PVGL} Ybp:800 N FG KFg:O FG P FG Tevq:7002 Havgf:R705 Ezx:60 LBS UK BS PCBQ",
        "PNYY:1 EFC/PVGL",
        "NQQE:800 N FG",
        "K:O FG / P FG",
        "ZNC:7002",
        "HAVG:R705",
        "VASB:60 LBS UK BS PCBQ");

    qbGrfg("G49",
        "{1 EFC/PVGL} Ybp:2205 UNEEVFBA EQ AR KFg:JNYAHG FG ZNVA FG AR Tevq:7002 Havgf:R705 Ezx:26LBS SNVAGRQ, VF PBAF NAQ NYREG NG GUVF GVZR, JVYY OR IVFVBA PRAGRE VA JNYZNEG",
        "PNYY:1 EFC/PVGL",
        "NQQE:2205 UNEEVFBA EQ AR",
        "K:JNYAHG FG / ZNVA FG AR",
        "ZNC:7002",
        "HAVG:R705",
        "VASB:26LBS SNVAGRQ, VF PBAF NAQ NYREG NG GUVF GVZR, JVYY OR IVFVBA PRAGRE VA JNYZNEG");

    qbGrfg("G50",
        "{1 EFC/PVGL} Ybp:2205 UNEEVFBA EQ AR KFg:JNYAHG FG ZNVA FG AR Tevq:7002 Havgf:R703 Ezx:26LBS SNVAGRQ, VF PBAF NAQ NYREG NG GUVF GVZR, JVYY OR IVFVBA PRAGRE VA JNYZNEG",
        "PNYY:1 EFC/PVGL",
        "NQQE:2205 UNEEVFBA EQ AR",
        "K:JNYAHG FG / ZNVA FG AR",
        "ZNC:7002",
        "HAVG:R703",
        "VASB:26LBS SNVAGRQ, VF PBAF NAQ NYREG NG GUVF GVZR, JVYY OR IVFVBA PRAGRE VA JNYZNEG");

    qbGrfg("G51",
        "{1 EFC/PVGL} Ybp:224 CRPNA NI Ncg:N KFg:JUVGRBNX EQ AR JNYAHG FG Tevq:7002 Havgf:R705 Ezx:3EQ CNEGL PNYY, 90LBS SRYY HAX SHEGURE, ZNVAGRAPR ZNA BA FPRAR JVGU URE, BSSVPR JBEXRE",
        "PNYY:1 EFC/PVGL",
        "NQQE:224 CRPNA NI",
        "ZNQQE:224 CRPNA NIR",
        "NCG:N",
        "K:JUVGRBNX EQ / AR JNYAHG FG",
        "ZNC:7002",
        "HAVG:R705",
        "VASB:3EQ CNEGL PNYY, 90LBS SRYY HAX SHEGURE, ZNVAGRAPR ZNA BA FPRAR JVGU URE, BSSVPR JBEXRE");

    qbGrfg("G52",
        "{1 EFC/PVGL} Ybp:311 ORNHERTNEQ QE KFg:ZNANFFNF QE WRSSREFBA FG Tevq:7004 Havgf:R703 Ezx:",
        "PNYY:1 EFC/PVGL",
        "NQQE:311 ORNHERTNEQ QE",
        "K:ZNANFFNF QE / WRSSREFBA FG",
        "ZNC:7004",
        "HAVG:R703");

    qbGrfg("G53",
        "{1 EFC/PVGL} Ybp:516 CVAR PG KFg:ZNEGVA YHGURE X TBEQBA FG Tevq:7002 Havgf:R705 Ezx:82 LBZ UNF SNYYRA NAQ HANOYR GB TRG HC",
        "PNYY:1 EFC/PVGL",
        "NQQE:516 CVAR PG",
        "K:ZNEGVA YHGURE X / TBEQBA FG",
        "ZNC:7002",
        "HAVG:R705",
        "VASB:82 LBZ UNF SNYYRA NAQ HANOYR GB TRG HC");

    qbGrfg("G54",
        "{CHO FIF PNYY} Ybp:532 THVYY FG Ncg:O-05 KFg:WNPXFBA FG UVYY FG J Tevq:7003 Havgf:R703 Ezx:YVSGVAT NFFVFG SBE RZF",
        "PNYY:CHO FIF PNYY",
        "NQQE:532 THVYY FG",
        "NCG:O-05",
        "K:WNPXFBA FG / UVYY FG J",
        "ZNC:7003",
        "HAVG:R703",
        "VASB:YVSGVAT NFFVFG SBE RZF");

    qbGrfg("G55",
        "{1 EFC/PVGL} Ybp:619 NQNZF NI KFg:RYYVATGBA NI ZNEGVA YHGURE X Tevq:7002 Havgf:R705 Ezx:NQHYG SRZNYR CNFFRQ BHG",
        "PNYY:1 EFC/PVGL",
        "NQQE:619 NQNZF NI",
        "ZNQQE:619 NQNZF NIR",
        "K:RYYVATGBA NI / ZNEGVA YHGURE X",
        "ZNC:7002",
        "HAVG:R705",
        "VASB:NQHYG SRZNYR CNFFRQ BHG");

    qbGrfg("G56",
        "{1 EFC/PVGL} Ybp:138 XVATFGBJA JL Ncg:304 KFg:WNPXFBA FG QRNQ RAQ Tevq:7004 Havgf:R703 Ezx:SRZNYR UNF SNYYRA JVGU HAXABJA VAWHEVRF...UK BS URNEG QVFRNFR NAQ QVNORGRF, UVTU OC,",
        "PNYY:1 EFC/PVGL",
        "NQQE:138 XVATFGBJA JL",
        "NCG:304",
        "K:WNPXFBA FG / QRNQ RAQ",
        "ZNC:7004",
        "HAVG:R703",
        "VASB:SRZNYR UNF SNYYRA JVGU HAXABJA VAWHEVRF...UK BS URNEG QVFRNFR NAQ QVNORGRF, UVTU OC,");

    qbGrfg("G57",
        "{1 EFC/PVGL} Ybp:540 JUVGRBNX FG KFg:ZNVA FG UBYG FG Tevq:7002 Havgf:R705 Ezx:3 L.B. CBFFVOYL UNIVAT N FRVMHER",
        "PNYY:1 EFC/PVGL",
        "NQQE:540 JUVGRBNX FG",
        "K:ZNVA FG / UBYG FG",
        "ZNC:7002",
        "HAVG:R705",
        "VASB:3 L.B. CBFFVOYL UNIVAT N FRVMHER");

    qbGrfg("G58",
        "{1 EFC/PVGL} Ybp:549 J UVYY FG KFg:WNPXFBA FG PVGL YVZVGF Tevq:7003 Havgf:R703 Ezx:TEL IRUVPYR ENA VAGB GUR ONPX BS N YBT GEHPX",
        "PNYY:1 EFC/PVGL",
        "NQQE:549 J UVYY FG",
        "K:WNPXFBA FG / PVGL YVZVGF",
        "ZNC:7003",
        "HAVG:R703",
        "VASB:TEL IRUVPYR ENA VAGB GUR ONPX BS N YBT GEHPX");

    qbGrfg("G59",
        "{1 EFC/PVGL} Ybp:549 J UVYY FG KFg:WNPXFBA FG PVGL YVZVGF Tevq:7003 Havgf:R704 Ezx:TEL IRUVPYR ENA VAGB GUR ONPX BS N YBT GEHPX",
        "PNYY:1 EFC/PVGL",
        "NQQE:549 J UVYY FG",
        "K:WNPXFBA FG / PVGL YVZVGF",
        "ZNC:7003",
        "HAVG:R704",
        "VASB:TEL IRUVPYR ENA VAGB GUR ONPX BS N YBT GEHPX");

    qbGrfg("G60",
        "{1 EFC/PVGL} Ybp:520 ZG CYRNFNAG EQ FJ KFg:JNEERAGBA UJL F JNER FG Tevq:7003 Havgf:R703 Ezx:6 LBZ CBFF UNIVAT NA NFGUZN NGGNPX UK BS NFGUZN, PBZR GB GUR ONPX BS GUR FPUBBY",
        "PNYY:1 EFC/PVGL",
        "NQQE:520 ZG CYRNFNAG EQ FJ",
        "K:JNEERAGBA UJL / F JNER FG",
        "ZNC:7003",
        "HAVG:R703",
        "VASB:6 LBZ CBFF UNIVAT NA NFGUZN NGGNPX UK BS NFGUZN, PBZR GB GUR ONPX BS GUR FPUBBY");

    qbGrfg("G61",
        "{1 EFC/PVGL} Ybp:520 ZG CYRNFNAG EQ FJ KFg:JNEERAGBA UJL F JNER FG Tevq:7003 Havgf:R704 Ezx:6 LBZ CBFF UNIVAT NA NFGUZN NGGNPX UK BS NFGUZN, PBZR GB GUR ONPX BS GUR FPUBBY",
        "PNYY:1 EFC/PVGL",
        "NQQE:520 ZG CYRNFNAG EQ FJ",
        "K:JNEERAGBA UJL / F JNER FG",
        "ZNC:7003",
        "HAVG:R704",
        "VASB:6 LBZ CBFF UNIVAT NA NFGUZN NGGNPX UK BS NFGUZN, PBZR GB GUR ONPX BS GUR FPUBBY");

    qbGrfg("G63",
        "{1 EFC/PVGL} Ybp:404 YVYNP YA KFg:NCBYYB QE RQTNE PVE Tevq:7002 Havgf:R705 Ezx:76 LE BYQ SRZNYR NQIVFRQ GUNG FUR ARRQF N NZOHYNAPR OHG ABG FHER SBE JUNG. QBBE VF",
        "PNYY:1 EFC/PVGL",
        "NQQE:404 YVYNP YA",
        "K:NCBYYB QE / RQTNE PVE",
        "ZNC:7002",
        "HAVG:R705",
        "VASB:76 LE BYQ SRZNYR NQIVFRQ GUNG FUR ARRQF N NZOHYNAPR OHG ABG FHER SBE JUNG. QBBE VF");

    qbGrfg("G64",
        "{1 EFC/PVGL} Ybp:248 SVEFG NI KFg:TENQL FG ZNVA FG Tevq:7001 Havgf:R705 Ezx:30 LE BYQ ZNYR UNIVAT N FRVMHER. UK BS FRVMHERF",
        "PNYY:1 EFC/PVGL",
        "NQQE:248 SVEFG NI",
        "ZNQQE:248 SVEFG NIR",
        "K:TENQL FG / ZNVA FG",
        "ZNC:7001",
        "HAVG:R705",
        "VASB:30 LE BYQ ZNYR UNIVAT N FRVMHER. UK BS FRVMHERF");

    qbGrfg("G65",
        "{1 EFC/PVGL} Ybp:832 N FG KFg:O FG P FG Tevq:7002 Havgf:R705 Ezx:89 LBS QVMML/NYZBFG SNVAGRQ/GEBHOYR OERNGUVAT YVSRYVAR 866-757-5747 ERS#ZRP2541563 UK BS",
        "PNYY:1 EFC/PVGL",
        "NQQE:832 N FG",
        "K:O FG / P FG",
        "ZNC:7002",
        "HAVG:R705",
        "VASB:89 LBS QVMML/NYZBFG SNVAGRQ/GEBHOYR OERNGUVAT YVSRYVAR 866-757-5747 ERS#ZRP2541563 UK BS");

    qbGrfg("G66",
        "{1 EFC/PVGL} Ybp:138 XVATFGBJA JL Ncg:120 KFg:WNPXFBA FG QRNQ RAQ Tevq:7004 Havgf:R704 Ezx:84 LBS PURFG CNVA UNF N URNEG UK",
        "PNYY:1 EFC/PVGL",
        "NQQE:138 XVATFGBJA JL",
        "NCG:120",
        "K:WNPXFBA FG / QRNQ RAQ",
        "ZNC:7004",
        "HAVG:R704",
        "VASB:84 LBS PURFG CNVA UNF N URNEG UK");

    qbGrfg("G67",
        "{SVER/NYNEZ} Ybp:649 ZNTABYVN QE AJ KFg:YRR FG YNEPU YA Tevq:7001 Havgf:R705 R704 Y707 Ezx:HCFGNVEF FZBXR QRGRPGBE K 2",
        "PNYY:SVER/NYNEZ",
        "NQQE:649 ZNTABYVN QE AJ",
        "K:YRR FG / YNEPU YA",
        "ZNC:7001",
        "HAVG:R705 R704 Y707",
        "VASB:HCFGNVEF FZBXR QRGRPGBE K 2");

    qbGrfg("G68",
        "{1 EFC/PVGL} Ybp:207 QRNAF NYL KFg:ZNEGVA YHGURE X TBEQBA FG Tevq:7002 Havgf:R705 Ezx:30 LBZ QVNORGVP CEBOYRZF/HAERFCBAFVIR OHG OERNGUVAT",
        "PNYY:1 EFC/PVGL",
        "NQQE:207 QRNAF NYL",
        "K:ZNEGVA YHGURE X / TBEQBA FG",
        "ZNC:7002",
        "HAVG:R705",
        "VASB:30 LBZ QVNORGVP CEBOYRZF/HAERFCBAFVIR OHG OERNGUVAT");

    qbGrfg("G69",
        "{1 EFC/PVGL} Ybp:886 PYRZZBAF FG KFg:N FG JNYAHG FG Tevq:7002 Havgf:R705 Ezx:24 L/B BO CNGVRAG VAWHEVRF SEBZ SNYY QBJA FGRCF",
        "PNYY:1 EFC/PVGL",
        "NQQE:886 PYRZZBAF FG",
        "K:N FG / JNYAHG FG",
        "ZNC:7002",
        "HAVG:R705",
        "VASB:24 L/B BO CNGVRAG VAWHEVRF SEBZ SNYY QBJA FGRCF");

    qbGrfg("G70",
        "{CHO FIF PNYY} Ybp:410 WBUAF EQ KFg:THVYY FG JNER FG Tevq:7003 Havgf:R704 Ezx:NFFVFG FHOWRPG BA FPRAR VA YVSGRVAT CNGVARAG JUB UNF SNYYRA...AB VAWHEVRF",
        "PNYY:CHO FIF PNYY",
        "NQQE:410 WBUAF EQ",
        "K:THVYY FG / JNER FG",
        "ZNC:7003",
        "HAVG:R704",
        "VASB:NFFVFG FHOWRPG BA FPRAR VA YVSGRVAT CNGVARAG JUB UNF SNYYRA...AB VAWHEVRF");

    qbGrfg("G71",
        "{1 EFC/PVGL} Ybp:207 QRNAF NYL KFg:ZNEGVA YHGURE X TBEQBA FG Tevq:7002 Havgf:R705 Ezx:ZNYR FHOWRPG CBFFVOYR YBJ OYBBQ FHTNE...HAXABJA NQQERFF. PNYYRE VF TBVAT GB OR BHGFVQR",
        "PNYY:1 EFC/PVGL",
        "NQQE:207 QRNAF NYL",
        "K:ZNEGVA YHGURE X / TBEQBA FG",
        "ZNC:7002",
        "HAVG:R705",
        "VASB:ZNYR FHOWRPG CBFFVOYR YBJ OYBBQ FHTNE...HAXABJA NQQERFF. PNYYRE VF TBVAT GB OR BHGFVQR");

    qbGrfg("G72",
        "{1 EFC/PVGL} Ybp:516 CVAR PG KFg:ZNEGVA YHGURE X TBEQBA FG Tevq:7002 Havgf:R705 Ezx:87 LE BYQ ZNYR SRYY BHG BS GUR JURRYPUNVE. ARRQF URYC ONPX HC",
        "PNYY:1 EFC/PVGL",
        "NQQE:516 CVAR PG",
        "K:ZNEGVA YHGURE X / TBEQBA FG",
        "ZNC:7002",
        "HAVG:R705",
        "VASB:87 LE BYQ ZNYR SRYY BHG BS GUR JURRYPUNVE. ARRQF URYC ONPX HC");

    qbGrfg("G73",
        "{SVER/GENFU} Ybp:210 CVGGF FG KFg:WNPXFBA FG OHFFRL NI Tevq:7004 Havgf:R704 Ezx:NQIVFR GURER VF FBZRGUVAT VA GUR CNEX BA SVER ZNLOR N GERR",
        "PNYY:SVER/GENFU",
        "NQQE:210 CVGGF FG",
        "K:WNPXFBA FG / OHFFRL NI",
        "ZNC:7004",
        "HAVG:R704",
        "VASB:NQIVFR GURER VF FBZRGUVAT VA GUR CNEX BA SVER ZNLOR N GERR");

    qbGrfg("G74",
        "{1 EFC/PVGL} Ybp:458 WNPXFBA FG KFg:ZNVA FG JERAF UJL FR Tevq:7004 Havgf:C9 Ezx:19 LRNE BYQ",
        "PNYY:1 EFC/PVGL",
        "NQQE:458 WNPXFBA FG",
        "K:ZNVA FG / JERAF UJL FR",
        "ZNC:7004",
        "HAVG:C9",
        "VASB:19 LRNE BYQ");

    qbGrfg("G75",
        "{1 EFC/PVGL} Ybp:458 WNPXFBA FG KFg:ZNVA FG JERAF UJL FR Tevq:7004 Havgf: Ezx:19 LRNE BYQ",
        "PNYY:1 EFC/PVGL",
        "NQQE:458 WNPXFBA FG",
        "K:ZNVA FG / JERAF UJL FR",
        "ZNC:7004",
        "VASB:19 LRNE BYQ");

    qbGrfg("G76",
        "{1 EFC/PVGL} Ybp:458 WNPXFBA FG KFg:ZNVA FG JERAF UJL FR Tevq:7004 Havgf:R704 Ezx:19 LRNE BYQ",
        "PNYY:1 EFC/PVGL",
        "NQQE:458 WNPXFBA FG",
        "K:ZNVA FG / JERAF UJL FR",
        "ZNC:7004",
        "HAVG:R704",
        "VASB:19 LRNE BYQ");

    qbGrfg("G77",
        "{1 EFC/PVGL} Ybp:604 QRYY QE Ncg:5 KFg:JNGFBA FG SBERFG PYNEL QE Tevq:7004 Havgf:R704 Ezx:15 LB SZ UNIVAT N CBFF CNAVP NGGNPX",
        "PNYY:1 EFC/PVGL",
        "NQQE:604 QRYY QE",
        "NCG:5",
        "K:JNGFBA FG / SBERFG PYNEL QE",
        "ZNC:7004",
        "HAVG:R704",
        "VASB:15 LB SZ UNIVAT N CBFF CNAVP NGGNPX");

    qbGrfg("G78",
        "{1 EFC/PVGL} Ybp:326 R UVYY FG KFg:WNPXFBA FG PVGL YVZVGF Tevq:7004 Havgf:R704 Ezx:FGVYY VA GUR EBNQ FVYIRE ZNYVOH NAQ N GNA YVAPBYA, 72LBS FGF VG UHEGF GB OERNGU, NABGURE",
        "PNYY:1 EFC/PVGL",
        "NQQE:326 R UVYY FG",
        "K:WNPXFBA FG / PVGL YVZVGF",
        "ZNC:7004",
        "HAVG:R704",
        "VASB:FGVYY VA GUR EBNQ FVYIRE ZNYVOH NAQ N GNA YVAPBYA, 72LBS FGF VG UHEGF GB OERNGU, NABGURE");

    qbGrfg("G79",
        "{1 EFC/PVGL} Ybp:138 XVATFGBJA JL Ncg:304 KFg:WNPXFBA FG QRNQ RAQ Tevq:7004 Havgf:R704 Ezx:69 LRNE BYQ SRZNYR",
        "PNYY:1 EFC/PVGL",
        "NQQE:138 XVATFGBJA JL",
        "NCG:304",
        "K:WNPXFBA FG / QRNQ RAQ",
        "ZNC:7004",
        "HAVG:R704",
        "VASB:69 LRNE BYQ SRZNYR");

    qbGrfg("G80",
        "{1 EFC/PVGL} Ybp:877 PBOOUNZ EQ AR Ncg:N14 KFg:BYQ JNFUVATGBA UNEEVFBA QE AR Tevq:7002 Havgf:R705 Ezx:67 LE BYQ SRZNYR QVSS OERNGUVAT. FGBZNPU VF IREL FJRYYRQ. QVNYLFVF CNGVRAG",
        "PNYY:1 EFC/PVGL",
        "NQQE:877 PBOOUNZ EQ AR",
        "NCG:N14",
        "K:BYQ JNFUVATGBA / UNEEVFBA QE AR",
        "ZNC:7002",
        "HAVG:R705",
        "VASB:67 LE BYQ SRZNYR QVSS OERNGUVAT. FGBZNPU VF IREL FJRYYRQ. QVNYLFVF CNGVRAG");

    qbGrfg("G81",
        "{1 EFC/PVGL} Ybp:400 QVKVR QE KFg:CVGGF FG SBERFG PYNEL QE Tevq:7004 Havgf:R704 Ezx:99LBS ABG OERNGUVAT JNF NJNXR NA UBHE NTB",
        "PNYY:1 EFC/PVGL",
        "NQQE:400 QVKVR QE",
        "K:CVGGF FG / SBERFG PYNEL QE",
        "ZNC:7004",
        "HAVG:R704",
        "VASB:99LBS ABG OERNGUVAT JNF NJNXR NA UBHE NTB");

    qbGrfg("G82",
        "{SVER/FGEHPGHER} Ybp:511 XABK FG KFg:RYYVATGBA NI ZRAQRY NI Tevq:7002 Havgf: Ezx:ONPX EBBZ BA SVER RIRELBAR BHG",
        "PNYY:SVER/FGEHPGHER",
        "NQQE:511 XABK FG",
        "K:RYYVATGBA NI / ZRAQRY NI",
        "ZNC:7002",
        "VASB:ONPX EBBZ BA SVER RIRELBAR BHG");

    qbGrfg("G83",
        "{CHO FIF PNYY} Ybp:404 ZNTABYVN QE AJ KFg:YRR FG YNEPU YA Tevq:7001 Havgf:R705 Ezx:FZBXR QRGRPGBE TBVAT BSS AB SVER JNAGF FBZRBAR GB PBZR PURPX VG",
        "PNYY:CHO FIF PNYY",
        "NQQE:404 ZNTABYVN QE AJ",
        "K:YRR FG / YNEPU YA",
        "ZNC:7001",
        "HAVG:R705",
        "VASB:FZBXR QRGRPGBE TBVAT BSS AB SVER JNAGF FBZRBAR GB PBZR PURPX VG");

    qbGrfg("G84",
        "{1 EFC/PVGL} Ybp:814 N FG KFg:O FG P FG Tevq:7002 Havgf:R705 Ezx:47LBS FGF FUR QBRFA'G SRRY JRYY GUVAXF FUR VF NOBHG GB QVR, UVFGBEL BS XVQARL SNVYHER NAQ FRVMHERF",
        "PNYY:1 EFC/PVGL",
        "NQQE:814 N FG",
        "K:O FG / P FG",
        "ZNC:7002",
        "HAVG:R705",
        "VASB:47LBS FGF FUR QBRFA'G SRRY JRYY GUVAXF FUR VF NOBHG GB QVR, UVFGBEL BS XVQARL SNVYHER NAQ FRVMHERF");

    qbGrfg("G85",
        "{1 EFC/PVGL} Ybp:417 FNYRZ EQ KFg:NHTHFGN EQ FR UNEEVFBA EQ FR Tevq:7004 Havgf:R704 Ezx:84 LE BYQ SRZNYR SRYY NAQ UNF N XABG BA URE SBERURNQ BIRE RLR. UK BS NYMUVZREF",
        "PNYY:1 EFC/PVGL",
        "NQQE:417 FNYRZ EQ",
        "K:NHTHFGN EQ FR / UNEEVFBA EQ FR",
        "ZNC:7004",
        "HAVG:R704",
        "VASB:84 LE BYQ SRZNYR SRYY NAQ UNF N XABG BA URE SBERURNQ BIRE RLR. UK BS NYMUVZREF");

    qbGrfg("G86",
        "{1 EFC/PVGL} Ybp:318 GBZ JNGFBA JNL KFg:ZNVA FG YHZCXVA FG Tevq:7001 Havgf:R705 Ezx:86 LBS ARRQF BAYL YVSGVAT BAYL, FBZRBAR VF PBZVAT JVGU N XRL",
        "PNYY:1 EFC/PVGL",
        "NQQE:318 GBZ JNGFBA JNL",
        "K:ZNVA FG / YHZCXVA FG",
        "ZNC:7001",
        "HAVG:R705",
        "VASB:86 LBS ARRQF BAYL YVSGVAT BAYL, FBZRBAR VF PBZVAT JVGU N XRL");

    qbGrfg("G87",
        "{1 EFC/PVGL} Ybp:643 ZNEGVA YHGURE XVAT WE FG KFg:TBEQBA FG JVYFBA FG Tevq:7002 Havgf:R705 Ezx:79 LB SZ UK BS PUS UNIVAT ERFC QVFGERFF NAQ URE URNEG VF SYHGGREVAT",
        "PNYY:1 EFC/PVGL",
        "NQQE:643 ZNEGVA YHGURE XVAT WE FG",
        "K:TBEQBA FG / JVYFBA FG",
        "ZNC:7002",
        "HAVG:R705",
        "VASB:79 LB SZ UK BS PUS UNIVAT ERFC QVFGERFF NAQ URE URNEG VF SYHGGREVAT");

    qbGrfg("G88",
        "{1 EFC/PVGL} Ybp:R UVYY FG/WNPXFBA FG KFg:WBUAFBA NI OYNPX FG Tevq:7003 Havgf:R704 Ezx:RNFG UVYY FG @ WNPXFBA FG",
        "PNYY:1 EFC/PVGL",
        "NQQE:R UVYY FG & WNPXFBA FG",
        "K:WBUAFBA NI / OYNPX FG",
        "ZNC:7003",
        "HAVG:R704",
        "VASB:RNFG UVYY FG @ WNPXFBA FG");

    qbGrfg("G89",
        "{1 EFC/PVGL} Ybp:107 JUVGRBNX FGERRG RKG Ncg:48 KFg:JUVGRBNX FG WBARF EQ Tevq:7002 Havgf:R705 Ezx:59 L/B SRZNYR CBFF. FGEBXR PNZR VA IVN ZRQVPNY NYNEZ YVSR NYNEZ FLFGRZ 800-268-3453,,BCRE=329.",
        "PNYY:1 EFC/PVGL",
        "NQQE:107 JUVGRBNX FGERRG RKG",
        "NCG:48",
        "K:JUVGRBNX FG / WBARF EQ",
        "ZNC:7002",
        "HAVG:R705",
        "VASB:59 L/B SRZNYR CBFF. FGEBXR PNZR VA IVN ZRQVPNY NYNEZ YVSR NYNEZ FLFGRZ 800-268-3453,,BCRE=329.");

    qbGrfg("G90",
        "{CHO FIF PNYY} Ybp:2205 UNEEVFBA EQ AR KFg:JNYAHG FG ZNVA FG Tevq:7002 Havgf:R705 Ezx:FRIRENY XVGGRAF GENCCRQ VA N PHYIREG BS FBZR FBEG BA GUR TNEQRA PRAGRE RAQ",
        "PNYY:CHO FIF PNYY",
        "NQQE:2205 UNEEVFBA EQ AR",
        "K:JNYAHG FG / ZNVA FG",
        "ZNC:7002",
        "HAVG:R705",
        "VASB:FRIRENY XVGGRAF GENCCRQ VA N PHYIREG BS FBZR FBEG BA GUR TNEQRA PRAGRE RAQ");

    qbGrfg("G91",
        "{SVER/FGEHPGHER} Ybp:751 CHOYVP FNSRGL QE KFg:UNEEVFBA EQ FR NHTHFGN EQ FR Tevq:7004 Havgf:R704 R705 Y707 Ezx:FZBXR VA O OYBPX,,",
        "PNYY:SVER/FGEHPGHER",
        "NQQE:751 CHOYVP FNSRGL QE",
        "K:UNEEVFBA EQ FR / NHTHFGN EQ FR",
        "ZNC:7004",
        "HAVG:R704 R705 Y707",
        "VASB:FZBXR VA O OYBPX,,");

    qbGrfg("G92",
        "{1 EFC/PVGL} Ybp:651 ZNVA FG AJ KFg:ENVYEBNQ FG JEVTUGFOBEB EQ Tevq:7001 Havgf:R705 Ezx:SRZNYR CBFFVOYL OVGGRA OL FBZRGUVAT",
        "PNYY:1 EFC/PVGL",
        "NQQE:651 ZNVA FG AJ",
        "K:ENVYEBNQ FG / JEVTUGFOBEB EQ",
        "ZNC:7001",
        "HAVG:R705",
        "VASB:SRZNYR CBFFVOYL OVGGRA OL FBZRGUVAT");

    qbGrfg("G93",
        "{1 EFC/PVGL} Ybp:525 CVAR PG KFg:ZNEGVA YHGURE X TBEQBA FG Tevq:7002 Havgf:R705 Ezx:SRZNYR CNGVRAG PURFG CNVAF...ERFC QVFGERFF",
        "PNYY:1 EFC/PVGL",
        "NQQE:525 CVAR PG",
        "K:ZNEGVA YHGURE X / TBEQBA FG",
        "ZNC:7002",
        "HAVG:R705",
        "VASB:SRZNYR CNGVRAG PURFG CNVAF...ERFC QVFGERFF");

    qbGrfg("G94",
        "{1 EFC/PVGL} Ybp:139 ANFFNH CY KFg:ZNVA FG XABK FUBCCVAT P Tevq:7002 Havgf: Ezx:SRZNYR FRVMHER VA GUR CNEXVAT YBG",
        "PNYY:1 EFC/PVGL",
        "NQQE:139 ANFFNH CY",
        "K:ZNVA FG / XABK FUBCCVAT P",
        "ZNC:7002",
        "VASB:SRZNYR FRVMHER VA GUR CNEXVAT YBG");

    qbGrfg("G95",
        "{1 EFC/PVGL} Ybp:139 ANFFNH CY KFg:ZNVA FG XABK FUBCCVAT P Tevq:7002 Havgf:R705 Ezx:SRZNYR FRVMHER VA GUR CNEXVAT YBG",
        "PNYY:1 EFC/PVGL",
        "NQQE:139 ANFFNH CY",
        "K:ZNVA FG / XABK FUBCCVAT P",
        "ZNC:7002",
        "HAVG:R705",
        "VASB:SRZNYR FRVMHER VA GUR CNEXVAT YBG");

    qbGrfg("G96",
        "{1 EFC/PVGL} Ybp:958 XRAARQL PVE KFg:JEVTUGFOBEB EQ ORGFL OENAPU QE Tevq:7001 Havgf:R705 Ezx:73 L/B ZNYR HAERFCBAFVIR CNGVRAG VF OERNGUVAT",
        "PNYY:1 EFC/PVGL",
        "NQQE:958 XRAARQL PVE",
        "K:JEVTUGFOBEB EQ / ORGFL OENAPU QE",
        "ZNC:7001",
        "HAVG:R705",
        "VASB:73 L/B ZNYR HAERFCBAFVIR CNGVRAG VF OERNGUVAT");

    qbGrfg("G97",
        "{CHO FIF PNYY} Ybp:309 PYRIRYNAQ FG KFg:TBEQBA FG ENVYEBNQ FG Tevq:7002 Havgf:R705 Ezx:GUR TNF ZRGRE VF ZNXVAT N UVFFVAT ABVFR NAQ CBFFVOYR YRNXVAT. BJARQ OL FB6",
        "PNYY:CHO FIF PNYY",
        "NQQE:309 PYRIRYNAQ FG",
        "K:TBEQBA FG / ENVYEBNQ FG",
        "ZNC:7002",
        "HAVG:R705",
        "VASB:GUR TNF ZRGRE VF ZNXVAT N UVFFVAT ABVFR NAQ CBFFVOYR YRNXVAT. BJARQ OL FB6");

    qbGrfg("G98",
        "{1 EFC/PVGL} Ybp:701 PNEQVANY FG KFg:SBERFG PYNEL QE FNYRZ EQ Tevq:7004 Havgf:R703 Ezx:42 LE BYQ ZNYR GNXVAT N QVSSRERAG XVAQ BS ZRQVPNGVBA NAQ VG VF ZNXVAT UVF QVFYHFVBANY NAQ FRR GUVATF GUNG NVAG GURER. UR PNAG FYRRC NG AVTUG",
        "PNYY:1 EFC/PVGL",
        "NQQE:701 PNEQVANY FG",
        "K:SBERFG PYNEL QE / FNYRZ EQ",
        "ZNC:7004",
        "HAVG:R703",
        "VASB:42 LE BYQ ZNYR GNXVAT N QVSSRERAG XVAQ BS ZRQVPNGVBA NAQ VG VF ZNXVAT UVF QVFYHFVBANY NAQ FRR GUVATF GUNG NVAG GURER. UR PNAG FYRRC NG AVTUG");

    qbGrfg("G99",
        "{1 EFC/PVGL} Ybp:207 QRNAF NYL KFg:ZNEGVA YHGURE X TBEQBA FG Tevq:7002 Havgf:R705 Ezx:34 LBZ YBJ OYBBQ FHTNE UK BS QVNORGRF",
        "PNYY:1 EFC/PVGL",
        "NQQE:207 QRNAF NYL",
        "K:ZNEGVA YHGURE X / TBEQBA FG",
        "ZNC:7002",
        "HAVG:R705",
        "VASB:34 LBZ YBJ OYBBQ FHTNE UK BS QVNORGRF");

  }


  choyvp fgngvp ibvq znva(Fgevat[] netf) {
    arj TNZpQhssvrPbhaglCnefreGrfg().trarengrGrfgf("G1");
  }
}
