cnpxntr arg.narv.pnqcntr.cnefref.BE;

vzcbeg arg.narv.pnqcntr.cnefref.OnfrCnefreGrfg;

vzcbeg bet.whavg.Grfg;

/*
Pyngfbc Pbhagl, BE

Pbagnpg: Npgvir911
Ntrapl anzr: Frnfvqr Sver & Erfphr
Ybpngvba: Frnfvqr, BE, Havgrq Fgngrf
Fraqre: pzvercbegvat@nfgbevn.be.hf

{Sver Pnyy} 14 A Qbjavat Fg/RZRET ZRQVPNY ERFCBAFR/ srznyr va naq bhg bs pbafpvbhfarff
{Sver Pnyy} 2531 Zvyy Perrx Ya 101/RZRET ZRQVPNY ERFCBAFR / ibzvgvat naq qvneeurn
{Sver Pnyy} 414 Oebnqjnl Fg/RZRET ZRQVPNY ERFCBAFR/ vax zrqvpny cbff qvnorgvp
{Sver Pnyy} 2481 Ujl 101/RZRET ZRQVPNY ERFCBAFR
{Sver Pnyy} 2841 ujl 101 22/RZRET ZRQVPNY ERFCBAFR
{Sver Pnyy} 1126 Nirahr N 4/RZRET ZRQVPNY ERFCBAFR/ cbff 400 zt zbecuvar bireqbfr
{Sver Pnyy} 12 Uvyygbc Qe/RZRET ZRQVPNY ERFCBAFR/ cbffvoyr fgebxr
{Sver Pnyy} 101 Sberfg Qe 120/RZRET ZRQVPNY ERFCBAFR/ haerfc srznyr, oernguvat
{Sver Pnyy} 380 Sberfg Pg/RZRET ZRQVPNY ERFCBAFR/ Yvsr Nvq zrq nyreg, hax zrqvpny
{Sver Pnyy} 101 Sberfg qe/RZRET ZRQVPNY ERFCBAFR/ zrqvk erd, CG unf cerivbhf uvc senpgheer, cbff ervaw
{Sver Pnyy} ZC 4 / UJL 26/NFFVFG ERAQRERQ/GERR QBJA JRFG OAQ YNAR BA CBJRE YVARF
{Sver Pnyy} 84389 ABEQZNEX QE/RZRET ZRQVPNY ERFCBAFR/ PNYYRE JBHYQ YVXR FVYRAG NCCEBNPU
{Sver Pnyy} 84389 ABEQZNEX QE/RZRET ZRQVPNY ERFCBAFR/QVSS OERNGUVAT HANOYR GB TRG BHG BS ORQ
{Sver Pnyy} 20 A Jnunaan Eq 105/RZRET ZRQVPNY ERFCBAFR / qvssvphygl oernguvat
{Sver Pnyy} 1111 A EBBFRIRYG/BQBE TNF/FZBXR/PURZVPNY/ ANGHENY TNF FZRYY
{Sver Pnyy} 522 A UBYYNQNL/BQBE TNF/FZBXR/PURZVPNY/ TNF YVAR UVG OL PBAFGEHPGVBA PERJ
{Sver Pnyy} 581 F QBJAVAT 2/RZRET ZRQVPNY ERFCBAFR/ NFFVFG ZRQVK J/ RKGEVPNGVBA
{Sver Pnyy} 2445 OBRUZ NPERF EQ/RZRET ZRQVPNY ERFCBAFR/ ZNYR QVSS OERNGUVAT
{Sver Pnyy} 101 SBERFG 120/RZRET ZRQVPNY ERFCBAFR/ HAERFC SRZNYR
{Sver Pnyy} 361 UVYYGBC QE/BQBE TNF/FZBXR/PURZVPNY/ FZRYY BS TNF VAFVQR UBHFR
{Sver Pnyy} 300 F Ubyynqnl Qe/BQBE TNF/FZBXR/PURZVPNY/ FZRYY ANGHENY TNF
{Sver Pnyy} 300 A cebzranqr/grfg
{Sver Pnyy} 1131 OEBNQJNL/yvtug cbyr
{Sver Pnyy/ Qvssvphygl oernugvat} 2149 F Senaxyva 7/RZRET ZRQVPNY ERFCBAFR
{Sver Pnyy} 2149 F Senaxyva Fg 7/RZRET ZRQVPNY ERFCBAFR / yvsg nffvfg, 2aq gbar, cbff urnq vwhel, onpx cnva
{Sver Pnyy} 2149 F Senaxyva Fg 7/RZRET ZRQVPNY ERFCBAFR/ snyy cng, erd ol Zrqvk
{Sver Pnyy/ Mbar 1 Trareny Sver nynez} 2500 F Ebbfriryg Qe/NYNEZ SVER
{Sver Pnyy} 150 F JNUNAAN EQ 2/RZRET ZRQVPNY ERFCBAFR TEBHAQ YRIRY SNYY URNQ YNPRENGVBA
{Sver Pnyy} 101 SBERFG QE 158/RZRET ZRQVPNY ERFCBAFR/ ZNYR SNYY CNG UVG URNQ
{Sver Pnyy} 1032 24GU Nir S/RZRET ZRQVPNY ERFCBAFR
{Sver Pnyy} 1235 NIR N/RZRET ZRQVPNY ERFCBAFR
{Sver Pnyy} 2500 F EBBFRIRYG/NYNEZ SVER/ TRARENY SVER NYNEZ
{Sver Pnyy} 20 A JNUNAAN EQ 212/RZRET ZRQVPNY ERFCBAFR/ HAX CBFF QVNORGVP
{Sver Pnyy} 1032 24GU NIR 13/RZRET ZRQVPNY ERFCBAFR QVNORGVP VFFHRF
{Sver Pnyy} 3EQ / ARPNAVPHZ/NFFVFG ERAQRERQ ABA PBQR SBE PYRNAHC
{Sver Pnyy} 300 A CEBZ 399/RZRET ZRQVPNY ERFCBAFR/ HAX ZRQVPNY
{Sver Pnyy/ Qvfertneq ynfg, jebat SQ} 1164 Fcehpr Pg/RZRET ZRQVPNY ERFCBAFR
{Sver Pnyy/ Haxabja zrqvpny ceboyrz, srznyr vf pbafpvbhf naq oernguvat} 1164 Fcehpr Pg/RZRET ZRQVPNY ERFCBAFR
{Sver Pnyy} 1601 oebnqjnl 2/RZRET ZRQVPNY ERFCBAFR cbffvoyr fgebxr
{Sver Pnyy} Ujl 26 / Pnzcoryy Ybbc/RZRET ZRQVPNY ERFCBAFR/ urneg pbaqvgvba, yvtug urnqrq
{Sver Pnyy} 101 Sberfg Qe 206/RZRET ZRQVPNY ERFCBAFR/ funyybj oernguvat, abg nyreg
{Sver Pnyy/ Znyr qbja frvmher, cnexvat ybg} 60 A Ebbfriryg Qe/NFFVFG ERAQRERQ
{Sver Pnyy} 1901 A UBYYVQNL/NYNEZ SNYFR/ TRARENY
{Sver Pnyy/ Qvssvphyygl oernguvat} 2473 DHRRA FG/RZRET ZRQVPNY ERFCBAFR
{Sver Pnyy/ yrgunetvp, snyy cngvrag} 2532 Bertba Fg/RZRET ZRQVPNY ERFCBAFR
{Sver Pnyy} 2561 A EBBFRIRYG 205/RZRET ZRQVPNY ERFCBAFR/ 21LB NHGVFGVP ZNYR FRVMHER
{Sver Pnyy} 150 F JNUNAAN 14/RZRET ZRQVPNY ERFCBAFR/ZNYR QVSS OERNGUVAT XVQQARL CEBOYRZF
{Sver Pnyy} 3140 FHAFRG OYIQ 46/RZRET ZRQVPNY ERFCBAFR/ SNYY CNG HAX VAWHEL
{Sver Pnyy} 3140 FHAFRG OYIQ 46/RZRET ZRQVPNY ERFCBAFR/ SRZNYR SNYY HAX VAWHEL
{Sver Pnyy} 26 NIR N 2205/RZRET ZRQVPNY ERFCBAFR QVNORGVP VFFHRF
{Sver Pnyy NFFVFG J/ RKGNPNGVBA} 101 SBERFG Qe/RZRET ZRQVPNY ERFCBAFR
{Sver Pnyy} 227 Oebnqjnl Fg/QVFGHEONAPR GNFRE ERZBINY
{Sver Pnyy} 1140/RZRET ZRQVPNY ERFCBAFR/ SRZNY SNVAG PBA / OERNGUVAT
{Sver Pnyy} 825 A UBYYNQNL 2/RZRET ZRQVPNY ERFCBAFR/ HAX ZRQVPNY CQ BA FPRAR
{Sver Pnyy} 1530 F EBBFRIRYG Qe/RZRET ZRQVPNY ERFCBAFR QVSSVPHYGL OERNGUVAT
{Sver Pnyy} 2125 F QBJAVAT 10/RZRET ZRQVPNY ERFCBAFR PURFG CNVAF
{Sver Pnyy} 770 16gu Nir/QVFGHEONAPR/ fcnexf sebz puvzarl ynaqvat ba ebbs
{Sver Pnyy} 602 A Cebz/NYNEZ SVER/ tnf yrnx nynez
{Sver Pnyy} 2531 ZVYYPERRX YA 101/RZRET ZRQVPNY ERFCBAFR/SRZNYR QVSS OERNGUVAT
{Sver Pnyy/ Sver nynez chyy fgngvba 4gu sybbe Rnfg fgnvef} 475 F cebz/NYNEZ SVER
{Sver Pnyy OERNGUVAT QVSS} 1126 NIRAHR N 4/RZRET ZRQVPNY ERFCBAFR
{Sver Pnyy} 800 F UBYYNQNL 3/NYNEZ SVER/ SVER NYNEZ
{Sver Pnyy} 470 14GU/19 LE BYQ ZNYR ERFVQRAG URNEVAT IBVPRF ABA IVBYRAG
{Sver Pnyy} 2069 PBBCRE FG/RZRET ZRQVPNY ERFCBAFR/QVSS OERNGUVAT UVFG BS PBCQ
{Sver Pnyy} 1355 11gu Nir/RZRET ZRQVPNY ERFCBAFR/ SRZNYR QEVAXVAT NAQ GBBX CVYYF AB ZBER VAS
{Sver Pnyy} EBBFRIRYG / 16GU NIR/ZBGBE IRU NPPVQRAG/ HAX VAW
{Sver Pnyy} 429 F Ubyynqnl Qe 19/RZRET ZRQVPNY ERFCBAFR/ 46 LB QVSS OERNGUVAT, VA ONPX BS ZBGRY
{Sver Pnyy} 2500 F EBBFRIRYG 241/RZRET ZRQVPNY ERFCBAFR/ SNYY CNG URNQ VAWHEL 2AQ SNYY GBQNL
{Sver Pnyy TNF BQBE} 1700 A UBYYNQNL QE/BQBE TNF/FZBXR/PURZVPNY
{Sver Pnyy} 1700 A UBYYNQNL QE/BQBE TNF/FZBXR/PURZVPNY
{Sver Pnyy} 2500 F EBBFRIRYG 134/RZRET ZRQVPNY ERFCBAFR/ZRQVK QRYNLRQ  CQ BA FPRAR
{Sver Pnyy} 15 OEBNQJNL/RZRET ZRQVPNY ERFCBAFR/ BHGFVQR GRE UNE'F 70 ZNYR
{Sver Pnyy} 441 2AQ NIR/NYNEZ SVER/ JNGRE SYBJ 
{Sver Pnyy, CBFF PIN} 830 7GU FGERRG/RZRET ZRQVPNY ERFCBAFR, 92LBS P/O, CBFF PIN. ZRQVK RAEG
{Sver Pnyy} 545 OEBNQJNL/RZRET ZRQVPNY ERFCBAFR QVNORGVP VFFHRF
{Sver Pnyy} 889 A Yvapbya Fg/RZRET ZRQVPNY ERFCBAFR/ purfg cnva
{Sver Pnyy} 101 Sberfg Qe/NYNEZ SVER/ ebbzf 101-120 fzbxr qrgrpgbe
{Sver Pnyy FURQ SVER} 1320 PNFNPNEN YA/FGEHP SVER 1FG
{Sver Pnyy} 1032 24gu Nir T/RZRET ZRQVPNY ERFCBAFR/ purfg cnvaf
{Sver Pnyy} EBBFRIRYG / 15GU NIR/RZRET ZRQVPNY ERFCBAFR/ ZBGBEPLYP ZIN
{Sver Pnyy 2 iruvpyr ZIN} 2455 F EBBFRIRYG Qe/RZRET ZRQVPNY ERFCBAFR
{Sver Pnyy YVSG NFFVFG JVGU ZRQVK} 1235 NIR N/RZRET ZRQVPNY ERFCBAFR
{Sver Pnyy FRVMHER CG} 1235 NIRAHR N/RZRET ZRQVPNY ERFCBAFR
{Sver Pnyy} 3eq Nir / Arpnavphz/RZRET ZRQVPNY ERFCBAFR / bireghearq lryybj pnabr
{Sver Pnyy/Gerr qbja Oybpxvat gur uvtujnl obgu ynarf bs geniry} Uvtujnl 26 / Zc 3/RZRET ZRQVPNY ERFCBAFR
{Sver Pnyy} 1235 NIRAHR N/RZRET ZRQVPNY ERFCBAFR/ FRVMHER
{Sver Pnyy} 441 2aq Nir/RZRET ZRQVPNY ERFCBAFR BIREQBRF
{Sver Pnyy} 33983 PBYRF YA/BGURE NYY RYQREYL SRZ CBFF ABG OERNGUVAT
{Sver Pnyy} 122 11GU NIR/RZRET ZRQVPNY ERFCBAFR ZNYR PBYNCFRQ
{Sver Pnyy} 401 F Ebbfriryg Qe/FRYS PURPX BHG SRZNYR CNFFRQ BHG
{Sver Pnyy} 65 8gu nir/NFFVFG BGURE NTRAPL
{Sver Pnyy} 724 OEBNQJNL/RZRET ZRQVPNY ERFCBAFR
{Sver Pnyy} 150 F JNUNAAN 20/NYNEZ SVER/ AB BAR UBZR
{Sver Pnyy} ABEGU UJL 101 / WPG/RZRET ZRQVPNY ERFCBAFR/ ZC 25 UJL 101
{Sver Pnyy} 101 SBERFG QE/RZRET ZRQVPNY ERFCBAFR/ SRZNYR CBFF FGEBXR
{Sver Pnyy} 20 A JNUNAAN EQ/RZRET ZRQVPNY ERFCBAFR/ SNYY CNG URNQ VAWHEL
{Sver Pnyy} 400 ARPNAVPHZ QE NCG 3/RZRET ZRQVPNY ERFCBAFR/ qvss oernguvat
{Sver Pnyy} 810 F UBYYNQNL 14/RZRET ZRQVPNY ERFCBAFR
{Sver Pnyy} 323 Oebnqjnl/RZRET ZRQVPNY ERFCBAFR/ Bssvpre qbja, fubgf sverq
{Sver Pnyy} 1111 A Ebbfriryg Qe 400/NYNEZ SVER/ trareny sver nynez

Pbagnpg: Npgvir911
Ntrapl anzr: Trneuneg ISQ
Ybpngvba: Trneuneg, BE, Havgrq Fgngrf
Fraqre: pzvercbegvat@nfgbevn.be.hf

{Sver Pnyy} 2531 Zvyy Perrx Ya 101/RZRET ZRQVPNY ERFCBAFR/ nffvfg frnfvqr srznyr fvpx
{Sver Pnyy} 816 Q Fg/RZRET ZRQVPNY ERFCBAFR/ urneg nggnpx bhg onpx ol jngre
{Sver Pnyy} 233 F BPRNA QE/RZRET ZRQVPNY ERFCBAFR/HAX ZRQVPNY, ZRQVPNY NYREG NYNEZ
{Sver Pnyy} 33645 PHYYNOL YNXR YA/RZRET ZRQVPNY ERFCBAFR/ ABG tbvat CBI, cyrnfr erfcbaq
{Sver Pnyy} 33645 PHYYNOL YNXR YA/RZRET ZRQVPNY ERFCBAFR/ cngvrag tbvat CBI
{Sver Pnyy} 33645 PHYYNOL YNXR YA/RZRET ZRQVPNY ERFCBAFR/ 74 lbz qvssvphygl oernguvat
{Sver Pnyy} FUNZEBPX / CVAR EVQTR/RZRET ZRQVPNY ERFCBAFR/16 LB UVG VA GUR URNQ, OYRRQVAT
{Sver Pnyy} 90338 UVTUJNL 101/RZRET ZRQVPNY ERFCBAFR/ PURFG CNVA
{Sver Pnyy} 731 S FG/NYNEZ SNYFR FGNAQ QBJA
{Sver Pnyy} 729 A ZNEVBA NIR/RZRET ZRQVPNY ERFCBAFR/ HAX ZRQVPNY ZNYR PBA OERNGUVAT 
{Sver Pnyy} UVTUYNAQF YA / 101/RZRET ZRQVPNY ERFCBAFR/ FVATYR IRU ZIN
{Sver Pnyy/ YBPX OBK 1937} 5071 FUREVQNA QE/RZRET ZRQVPNY ERFCBAFR/ SNYY CNG
{Sver Pnyy} 102 5gu Fg/NYNEZ SVER / sver nynez cre nynez pbzcnal
{Sver Pnyy} 89660 ZNAVBA QE/RZRET ZRQVPNY ERFCBAFR CNAVP NGGNPX CBFF BQ
{Sver Pnyy} 89449 UVTUJNL 101/RZRET ZRQVPNY ERFCBAFR/ yvsg nffvfg
{Sver Pnyy} 33820 YNXR SEBAG QE/RZRET ZRQVPNY ERFCBAFR/ 80 LB QVSS OERNGUVAT
{Sver Pnyy} 729 A ZNEVBA/RZRET ZRQVPNY ERFCBAFR/ 60 -70 ZNYR PBASHFRQ CBFF HGV
{Sver Pnyy} 3855 UJL 101 A/RZRET ZRQVPNY ERFCBAFR/ 2 IRUVPYR ZIN
{Sver Pnyy} 806 ZPPBEZVPX TNEQRAF EQ/RZRET ZRQVPNY ERFCBAFR
{Sver Pnyy/ SRZNYR HAX ZRQ } 2017 TERNEUNEG TERRAF EQ 802/RZRET ZRQVPNY ERFCBAFR
{Sver Pnyy} 268 EVQTR QE/RZRET ZRQVPNY ERFCBAFR
{Sver Pnyy} Ujl 101 ZC 17/ZBGBE IRU NPPVQRAG/ 2 pnef if ryx
{Sver Pnyy} 4206 Uvtujnl 101 A/RZRET ZRQVPNY ERFCBAFR/ frvmher 
{Sver Pnyy} 729 A Znevba/RZRET ZRQVPNY ERFCBAFR/YVSG NFFVFG - XRA
{Sver Pnyy} 89953 FRNYRF EQ/RZRET ZRQVPNY ERFCBAFR/ 68 LB ZNYR PURFG CNVAF
{Sver Pnyy} 89953 FRNYRF EQ/RZRET ZRQVPNY ERFCBAFR/ 68  ZNYR PURFG CNVAF
{Sver Pnyy CBFF FGEBXR PBAF QVSS OERNGUVAT} 1393 R CVAR QE/RZRET ZRQVPNY ERFCBAFR
{Sver Pnyy ZRQVPNY NYREG NPGVINGVBA} 233 F BPRNA NIR/RZRET ZRQVPNY ERFCBAFR
{Sver Pnyy} 4206 UVTUJNL 101 A/ZBGBE IRU NPPVQRAG/ ZIN
{RZF PNYY} 1308 CNEX YA/RZRET ZRQVPNY ERFCBAFR, SNYY CNGVRAG AB VAW
{Sver Pnyy/ qvmml crefba qnex oyhr} Ujl 101 / Jvyq Qnssbqvy/RZRET ZRQVPNY ERFCBAFR
{Sver Pnyy/purfg cnva } 89121 cvaruhefg/RZRET ZRQVPNY ERFCBAFR
{Sver Pnyy 2921 ZBIR HC F31} 1320 PNFNPNEN YA/FGEHP SVER 1FG
{Sver Pnyy} 102 5GU FG/NYNEZ SVER/ FZBXR NYNEZ
{Sver Pnyy} 101 / qry zbbe ybbc/RZRET ZRQVPNY ERFCBAFR/ 1 ZIN, UVG ONEEVRE HAX VAW
{Sver Pnyy} 862 F ZNEVBA/RZRET ZRQVPNY ERFCBAFR/ ZNYR CBFF FGEBXR
{Sver Pnyy} SHYZRE, JNLAR/RZRET ZRQVPNY ERFCBAFR/ snyy cg, PBCQ j/b sbe n gvzr
{Sver Pnyy} 89830 J naqrefba eq/PUVZARL SVER
{Sver Pnyy} QRY ENL / 101/ZIN FREVBHF VAWHEL/ ZIN QHZC GEHPX GUNGF SYVCCRQ
{Sver Pnyy} 61 BPRNA NIR/RZRET ZRQVPNY ERFCBAFR/ 30 SRZNYRQVNORGVP VFFHR
{Sver Pnyy} 61 BPRNA NIR/RZRET ZRQVPNY ERFCBAFR/ QVNORGVP VFFHR
{Sver Pnyy} 33538 NQNVE YA/RZRET ZRQVPNY ERFCBAFR/ ZNYR PBCQ / QVSS OERNGUUVAT
{Sver Pnyy} 1308 CNEX YA/RZRET ZRQVPNY ERFCBAFR SNYY CG TEBHAQ YRIRY
{Sver Pnyy PURFG CNVAF} 683 10GU FG/RZRET ZRQVPNY ERFCBAFR
{Sver Pnyy} 4306 UVTUJNL 101 A/RZRET ZRQVPNY ERFCBAFR/ zragny urnygu fhvpvqny, ynlvat va cnexvat ybg
{Sver Pnyy} 89449 UVTUJNL 101 A/RZRET ZRQVPNY ERFCBAFR/ ZNYR GRZC NFCRENGVAT
{Sver Pnyy} 981 YVGGYR ORNPU QE/NYNEZ SVER/ SVER NYNEZ HAX YBPNGVBA
{Sver Pnyy} 89449 UVTUJNL 101 A/RZRET ZRQVPNY ERFCBAFR/ 56 ZNYR FRVMHER
{Sver Pnyy} 591 F BPRNA/NYNEZ SVER/ FZBXR URNG QRGRPGBE MBAR 7
{Sver Pnyy} 856 ARNPBKVR OYIQ 322/NYNEZ SVER/ FZBXR NYNEZ 322 MBAR 9
{Sver Pnyy} 3518 UVTUJNL 101 A/RZRET ZRQVPNY ERFCBAFR/ srznyr snyy, xarr vawhel
{Sver Pnyy} 523 Q Fg/RZRET ZRQVPNY ERFCBAFR/ sryy va onguebbz, oernguvat, HAerfcbafvir
{Sver Pnyy/ Uvc Cnva nsgre n snyy n srj qnlf ntb.} 90479 Pynex Eq/RZRET ZRQVPNY ERFCBAFR
{Sver Pnyy} 33445 FHAFRG ORNPU YA/FGEHP SVER 1FG
{Sver Pnyy} 233 F BPRNA/NYNEZ SVER
{Sver Pnyy} 33684 JRFGFUBER YA/RZRET ZRQVPNY ERFCBAFR CBFF BIREQBFR
{Sver Pnyy} 4253 UVTUJNL 101 A/RZRET ZRQVPNY ERFCBAFR PBAGENPGVBAF
{Sver Pnyy} 321 1FG FG/NYNEZ SVER/RYPGEVP EBBZ FZBXR
{Sver Pnyy} 1308 CNEX YA/RZRET ZRQVPNY ERFCBAFR/ yvsg nffvfg j.zrqvk
{Sver Pnyy} 33538 NQNVE YA/RZRET ZRQVPNY ERFCBAFR
{Sver Pnyy} 4412 UVTUJNL 101 A/RZRET ZRQVPNY ERFCBAFR OERNGUVAT QVSSVPHYGVRF
{Sver Pnyy} 1157 A ZNEVBA Nir 443/
{Sver Pnyy} 233 F BPRNA QE/NYNEZ SVER/ XVGPURA FZBXR QRGRPGBE
{Sver Pnyy} 599 CNPVSVP JNL/RZRET ZRQVPNY ERFCBAFR/RYQREYL SRZNYR SNYY BHGFVQR BA FVQRJNYX
{Sver Pnyy} trneuneg sver fgngvba/ZBGBE IRU NPPVQRAG
{Sver Pnyy/ 729 A Znevba Haxabja zrqvpny ceboyrz} 729 A Znevba/RZRET ZRQVPNY ERFCBAFR
{Sver Pnyy/ Crqvngevp sryy bss ovxr, oybbql abfr naq oebxra grrgu} Qnvel Dhrra / Cnpvsvp Jnl/RZRET ZRQVPNY ERFCBAFR
{Sver Pnyy} 89790 Znavba Qe/RZRET ZRQVPNY ERFCBAFR/ cbff fgebxr
{Sver Pnyy/ Fghqrag sryy bagb uvf onpx, sebz cynl fgehpgher} 1002 Cnpvsvp Jnl/RZRET ZRQVPNY ERFCBAFR
{Sver Pnyy} 729 A ZNEVBA/RZRET ZRQVPNY ERFCBAFR/yvsg nffvfg
{Sver Pnyy} 89449 UVTUJNL 101/RZRET ZRQVPNY ERFCBAFR OERNGUVAT QVSSVPHYGVRF
{Sver Pnyy} 101 / T FG/RZRET ZRQVPNY ERFCBAFR/ 2 IRUVPYR ZIN
{Sver Pnyy} 1238 A ZNEVBA/NYNEZ SVER/ URNG QRGRPGBE YVIVAT EBBZ 1FG SYBBE
{Sver Pnyy} 268 EVQTR QE/RZRET ZRQVPNY ERFCBAFR/ 78 HAPBA SRZNYR OERNGUVAT
{Sver Pnyy} RZRET ZRQVPNY ERFCBAFR/HAPBA SRZNYR
{Sver Pnyy} 101  / ZC 15/RZRET ZRQVPNY ERFCBAFR
{Sver Pnyy} 3621 UVTUJNL 101 A/RZRET ZRQVPNY ERFCBAFR ZIN
{Sver Pnyy/ 2921} 441 2AQ NIR/FGEHP SVER 1FG/ VAA NG FRNFVQR
{Sver Pnyy} 1777 CVAR EVQTR QE 5/RZRET ZRQVPNY ERFCBAFR/ ryqreyl srznyr orra fvpx, pbaf naq oerngu
{Sver Pnyy SRRQVAT GHOR CEBOYRZF} 89449 UJL 101/RZRET ZRQVPNY ERFCBAFR
{Sver Pnyy/ Znyr guebjvat n svg, univat oernguvat qvssvphgyl cbyvpr ba fprar} 1989 Cvar Evqtr/RZRET ZRQVPNY ERFCBAFR
{Sver Pnyy} UJL 101 / ZC 18/NFFVFG ERAQRERQ/ GERR QBJA CNEG OYBPXVAT
{Sver Pnyy/ 2923 ERFC} 90517 OVEQVR/FGEHP SVER 1FG/ BIRA BA SVER
{Sver Pnyy/FBHGU OBHAQ} UJL 101 / OBJYVAT NYYRL/RZRET ZRQVPNY ERFCBAFR/ ZBGBEPLPYVFG QBJA
{Sver Pnyy} 89525 UVTUJNL 101/RZRET ZRQVPNY ERFCBAFR/ SRZNYR 55 QVSS OERNGUVAT
{Sver Pnyy} 33579 PNEYFBA QE/RZRET ZRQVPNY ERFCBAFR/ 89 SRZNYR FRZV PBA CNFFVAT BHG
{Sver Pnyy} 89780 QHAR EQ/RZRET ZRQVPNY ERFCBAFR/ 57 ZNYR FRVMHER
{Sver Pnyy} 1540 YRN JNL/FGEHP SVER 1FG
{Sver Pnyy} 33584 GBLNF YA/RZRET ZRQVPNY ERFCBAFR TEBHAQ YRIRY SNYY
{Sver Pnyy/ Zrqvk erdhrfgf P1 gb havawherq snyy cngvrag, zrqvk qrynlrq} RZRET ZRQVPNY ERFCBAFR/
{Sver Pnyy} 90495 CNE EQ/FGEHP SVER 1FG/  qvfnoyr crefba genccrq vafvqr
{Sver Pnyy/ Znyr xrrcf cnffvat bhg} 1367 Qbbyrl yA/RZRET ZRQVPNY ERFCBAFR
{Sver Pnyy / 96 LE BY SRZNYR SNYY CNG} 89829 FHES CVARF YNAQVAT QE/RZRET ZRQVPNY ERFCBAFR
{Sver Pnyy} 14.3 UJL 101/CHOYVP NFFVFG/ JRVTU FGNGVBA PNYYRE ERCBEGRQ FCNEXF SEBZ CBJRE CBYR
{Sver Pnyy} 126 11GU NIR/SVER VAIRFGVTNGVBA
{Sver Pnyy} 89449 UJL 101/RZRET ZRQVPNY ERFCBAFR/ NQHYG FRVMHER CNGVRAG
{Sver Pnyy} 6 10 FG/RZRET ZRQVPNY ERFCBAFR/ 88 LE BYQ PBQR 99
{Sver Pnyy} 402 OEBJAVAT/FGEHP SVER 1FG/ FZRYY FZBXR, ABAR IVFVOYR
{Sver Pnyy} 33538 NQNVE YA/RZRET ZRQVPNY ERFCBAFR/ FYAG NCEBNPU ZNYR 64  QVSS OEGU QVSS
{Sver Pnyy} 33538 NQNVE YA/RZRET ZRQVPNY ERFCBAFR/ FVYRAG NCCEBNPU 64 ZNYR LBH  JRER GURER BA FHAQNL GENAF

Pbagnpg: Npgvir911
Ntrapl anzr: Byarl Jnyyhfxv Sver & Erfphr
Ybpngvba: Nfgbevn, BE, Havgrq Fgngrf
Fraqre: pzvercbegvat@nfgbevn.be.hf

{Sver Pnyy} 89901 YBTNA Eq/FGEHP SVER 1FG
{Sver Pnyy} 35881 QBJ/FGEHP SVER 1FG
{Sver Pnyy} SBE 3521-ABEGU PBNFG ZRQVPNY PYVAVP-441 30GU FG/FZBXR NAQ OHEAVAT FZRYY SEBZ HCFGNVEF
{Sver Pnyy} 90461 UVTUJNL 202/RZRET ZRQVPNY ERFCBAFR
{Sver Pnyy} 88289 LBHATF EVIRE EQ/5 LB ZNYR J QVSS OERNGUVAT-CBFF NFGUZN NGGNPX
{Sver Pnyy} 7 UJL 202/FVATYR IRU ZIN, GEHPX BSS EBNQ BA GUR EVIRE FVQR BS UJL 202. HAX VAWHEVRF
{Sver Pnyy} 36476 PNQBANH YA/ZNYR FHOW CBFF URNEG NGGNPX
{Sver Pnyy} 10 UNYFRL EQ/FGEHP SVER 1FG/OBGGBZ HAVG, OYX FZBXR FRRA
{Sver Pnyy} 87334 LBHATF EVIRE EQ/PUVZARL SVER
{Sver Pnyy} 90461 UVTUJNL 202/RZRET ZRQVPNY ERFCBAFR/QVSS OERNGUVAT
{Sver Pnyy} 1576 VEIVAT NIR/FGEHP SVER 1FG
{Sver Pnyy} 1050 34GU FG/PUVZARL SVER/ZBIR HC GB PVGL YVZVGF
{Sver Pnyy} 92295 LBHATF EVIRE EQ/NYNEZ SVER NHGUBEVMRQ PNAPRY
{Sver Pnyy} 92295 LBHATF EVIRE EQ/NYNEZ SVER ZNFGRE ORQEBBZ FZBXR QRG.
{SRZNYR SNYY CNGVRAG/QVMML/OERNGUVAT NAQ PBAFPVBHF} 36549 PUEVFGVNAF YA/RZRET ZRQVPNY ERFCBAFR
{Sver Pnyy} 91617 UVTUJNL 202/RZF FUBEGARFF BS OERNGU
{Sver Pnyy} 1263 PBZZREPVNY FG 402/FGEHP SVER 1FG
{Sver Pnyy} 200 J XYNFXNAVAR NIR/FGEHP SVER 1FG
{Sver Pnyy} 1997 ZNEVAR Qe/FZBXR PBZVAT SEBZ OHVYQVAT BQQ BQBE
{Sver Pnyy} 91817 UVTUJNL 202 HAVG 30/64 LB SZ, YRGUNETVP NAQ UNYYHPVANGVAT
{ZNRY FHO/YNPRENGVBA BA NEZ} 91817 UVTUJNL 202 NCG 30/RZRET ZRQVPNY ERFCBAFR
{Sver Pnyy} UJL 202/ARNE YVARUNAF (ZC 3.8 VFU) FVATYR IRU EBYYBIRE-HAXA VAWHEVRF
{Sver Pnyy} 91817 UVTUJNL 202 NCG 30/RZRET ZRQVPNY ERFCBAFR/CBFG FGRAG CYNPRZRAG FJRYYVAT
{HAXA CEBOYRZ/ZRQPVNY NYNEZ GEVC} 90225 UVTUJNL 202/RZRET ZRQVPNY ERFCBAFR
{Sver Pnyy} 36506 PNQBANH YA/RYQREYL ZNYR, FRIRER ORQFBERF, CE HANOYR GB ZBIR UVZ
{Sver Pnyy} 1 3EQ FG/FGEHP SVER 1FG
{Sver Pnyy} 91320 JNYYHFXV YBBC/ZBGBE IRU NPPVQRAG/FZNYY FVYIRE PNE
{SRZ SRYY NAQ UNF URNQ VAWHEL/OERNGUVAT NAQ PBAFPVBHF} 91817 UVTUJNL 202 NCG 30/RZRET ZRQVPNY ERFCBAFR
{ZNYR UNIVAT OERNGUVAT QVSSVPHYGL} 89934 ENLZBAQ EQ/RZRET ZRQVPNY ERFCBAFR
{Sver Pnyy} 36506 PNQBANH YA/CHO NFFVFG-ZNYR ARRQF GB TRG SEBZ JURRYPUNVE GB ORQ-AB ZRQVPNY VFFHRF-ZRQVK HANINV 
{Sver Pnyy} 90292 YVYYRANF Eq/NYNEZ SVER
{Sver Pnyy} 35501 YVGGYR JNYYHFXV YA/SZ J PURFG CNVAF
{Sver Pnyy} 1740 QNJFBA PG/FGEHP SVER 1FG
{Sver Pnyy} 92975 UVTUJNL 202/RZRET ZRQVPNY ERFCBAFR
{Sver Pnyy} VA GUR NERN BS 87145 LBHATF EVIRE EQ/FVATYR IRU VA GUR QVGPU-ECGQ NF AB VAWHEVRF
{Sver Pnyy} 80 ARUNYRZ NIR/PUVZARL SVER-3521 ERFCBAQ GB PVGL YVZVGF
{Sver Pnyy} 91617 UVTUJNL 202/53 LB SZ JVGU N ABFR OYRRQ-FGVYY OYRRQVAT
{Sver Pnyy} 91817 UVTUJNL 202 NCG 37/SRZNYR SVATRE VAWHEL, SVATRE GHEAVAT OYNPX.
{Sver Pnyy} 35304 YLATFGNQ URVTUGF YA/FGEHP SVER 1FG/PUVZARL SVER
{Sver Pnyy} 1423 3EQ FG/FGEHP SVER 1FG/URNIL FZBXR FVQR BS UBHFR
{Sver Pnyy} 91617 UVTUJNL 202/52 LB SZ J ABFR OYRRQ, BA OYBBQ GUVAAREF
{Sver Pnyy} 38384 YNOVFXR YA/ZNYR FHOW ORYVRIRF UR VF UNIVAT URNEG NGGNPX-GVTUGARFF VA PURFG
{Sver Pnyy} JRYYF SNETB ONAX/FGEHP SVER 1FG
{Sver Pnyy} 91617 UVTUJNL 202/RZRET ZRQVPNY ERFCBAFR
{Sver Pnyy} 90461 UVTUJNL 202/ZNYR FHOW QVSS OERNGUVAT
{Sver Pnyy} SBE 3521--832 UNEEVFBA NIR/CBFF FGEHPGHER BE PUVZARL SVER NG NQQERFF-ARVTUOBE FGNGRF OYNPX FZBXR UBH
{Sver Pnyy} 3521----/34495 UVTUJNL 101 OHFVARFF/FGEHP SVER VA TNENTR-BPPHCNAGF BHG
{Sver Pnyy} 91817 UVTUJNL 202 NCG 30/64 LBN SRZNYR, PNAPRE CG, QVSS OERNGUVAT
{Sver Pnyy} 91131 UVTUJNL 202/ZNYR FHOW IBZVGGVAT-ERDHRFG FVYRAG NCCEBNPU
{Sver Pnyy} 126 11GU NIR/FGEHP SVER 3EQ 3521 TB GB FGNGVBA 26
{SRZNYR CBFFVOYR FGEBX} 90621 UVTUJNL 202/RZRET ZRQVPNY ERFCBAFR
{Sver Pnyy} 1432 SENAXYVA NIR NCG 8/FGEHP SVER 1FG/FGEBAT BQBE FZBXR, CBFF RYRPGEVPNY SVER
{Sver Pnyy} ABJYNAF QE/3571-YNETR OEHFU SVER ARNE N UBZR, CE PBHYQ FRR SEBZ URE UBHFR BA FGBARE EQ
{Sver Pnyy} UVTUJNL 202/PUEVFGVNAF YNAR/2AQ GBAR BHG- INA VAGB N QVGPU
{Sver Pnyy} UVTUJNL 202/PUEVFGVNAF YNAR/ZIN-INA VAGB N QVGPU
{Sver Pnyy} 90621 UVTUJNL 202/RZRET ZRQVPNY ERFCBAFR CEBO OEBXRA UVC
{Sver Pnyy} 90653 UVTUJNL 202/RZRET ZRQVPNY ERFCBAFR
{Sver Pnyy} 9 UJL 202, FVATYR IRU ZIN ZVABE VAWHEVRF
{Sver Pnyy} 91817 UVTUJNL 202 16/RZRET ZRQVPNY ERFCBAFR SRZ NFFNHYG IVP, YR BA FPRAR, P4 NAQ PYRNE
{Sver Pnyy} 91978 UNTRA QE/RZRET ZRQVPNY ERFCBAFR ZNYR CG, OYBBQ VA HEVAR
{Sver Pnyy} 3900 NOORL YA 210/FGEHP SVER 1FG OHVYQVAT N, FZBXR VA JNYY ORUVAQ SVERCYNPR
{DGE ZVYR BSS UJL 202 BA GUR EVTUG} UJL 202/TERRA ZBHAGNVA EQ/ZBGBE IRU NPPVQRAG
{Sver Pnyy} 1/2 ZVYR HC JNYYHFXV YBBC SEBZ YVGGYR JNYYHFXV/GERR NG 45 QRT NATYR NPEBFF EBNQ
{Sver Pnyy} UJL 202-200 LNEQF JRFG BS BYARL FGBER-GERR NAQ CBJRE CBYR/YVARF QBJA-PBZCYRGRYL OYBPXVAT
{Sver Pnyy} 86859 UVTUJNL 202/JNGRE NAQ ZHQ CBHEVAT BIRE URE ERGNVAVAT JNYY. 3.5 SG SEBZG URNG CHZC EVTUG ABJ
{Sver Pnyy} 90621 UVTUJNL 202/RYQREYL ZNYR FUBEGARFF BS OERNGU, TRARENY JRNXARFF
{Sver Pnyy} LBHATF EVIRE EQ/FNQQYR ZBHAGNVA(FZBYQREVAT CVYR BS OENAPURF/FGHZCF)
{27 LBN ZNYR FRVMVAT/OERNGUVAT NAQ PBAFPVBHF} 90592 UVTUJNL 202/RZRET ZRQVPNY ERFCBAFR
{Sver Pnyy} ZVYR CBFG 4.4 UJL 202/IRU VAGB N QVGPU ARNE GUR ERQ ONEA, HAX VAWHEVRF
{Sver Pnyy} 38246 YNEFRA YA/UBHFR BA SVER, NYY BPPHCNAGF BHG BS GUR UBHFR
{Sver Pnyy} 92402 R EQ/CHOYVP NFFVFG CREFBAARY ERD SBE IRU ERZBINY
{IRU PENFU} 92402 R EQ/ZBGBE IRU NPPVQRAG
{Sver Pnyy} 1341 3EQ FG/FGEHP SVER 1FG
{PUVZARL SVER/ERFCBAQ GB PVGL YVZVGF} 642 30GU FG/PUVZARL SVER
{Sver Pnyy} 91994 FUNA EQ/**FGNTR** QRCHGVRF RAEBHGR GB ERCG BS FHVPVQNY SRZNYR
{Sver Pnyy} 1545 SENAXYVA NIR/FGEHP SVER 1FG/PBZZREPVNY SVER NYNEZ, PUEHPU FZBXR
{Sver Pnyy} 3738 YVRS REVXFBA Qe FCNPR 25/SEVQTR BA SVER VA EI
{Sver Pnyy} 1311 XRAFVATGBA NIR/PNAPRY ERFCBAFR CRE PBZZNAQ
{Sver Pnyy} 1311 XRAFVATGBA NIR/SVER VA GUR BIRA-PHEERAGYL PBAGNVARQ VA BIRA
{SRZNYR JVGU ONPX NAQ UVC CNVA/QVMML/FVYROG NCCEBNPU} 87447 UVTUJNL 202/RZRET ZRQVPNY ERFCBAFR
{Sver Pnyy} 89125 JRYPU EQ/RZRET ZRQVPNY ERFCBAFR
{Sver Pnyy} 35375 ZHQQ YA(QVERPGYL NPEBFF SEBZ GUVF NQQERFF)CBFFVOYR BHG BS PBAGEBY OBASVER
{Sver Pnyy} 36370 QLOYVR YA/TENFF/OEHFU SVER
{Sver Pnyy} 11.5 UJL 202/ZBGBE IRU NPPVQRAG FVATYR IRU ZIN
{Sver Pnyy} 90225 UVTUJNL 202/ZRQVPNY NYNEZ-CRAQNAG NYNEZ-HAXABJA SHEGURE
{Sver Pnyy} SBE 3521---PBAVSRE YA/BSS YRJVF NAQ PYNEX EQ/ECG BS N FGEHPGHER SVER-HAXA SHEGURE
{Sver Pnyy} 90225 UVTUJNL 202/RZRET ZRQVPNY ERFCBAFR TRARENY ZRQ NYREG
{Sver Pnyy} 91085 UVTUJNL 202/RZRET ZRQVPNY ERFCBAFR SRZ CG UNIVAT N FGEBXR
{Sver Pnyy} 1744 SENAXYVA NIR/FGEHP SVER 1FG
{Sver Pnyy} 88590 UVTUJNL 202/ZBGBE IRU NPPVQRAG CBFF ZIN RNFG BS YBPNGVBA
{Sver Pnyy} 91085 UVTUJNL 202/RZRET ZRQVPNY ERFCBAFR/SRZNYR SNYYRA, QVSS OERNGUVAT
{Sver Pnyy} 90653 UVTUJNL 202/ZBGBE IRU NPPVQRAG/2 IRU ZIN
{Sver Pnyy} 419 TNGRJNL Nir/FGEHP SVER 1FG
{Sver Pnyy} 638 NYNZRQN NIR NCG 11 (GUVF VF GUR PBASVEZRQ NQQERFF SEBZ 2522 BA FPRAR)YVTUG FZBXR/UNMR SEZ JVAQBJ
{Sver Pnyy} SBE 3521 537 OBAQ FG/OYNPX FZBXR PBZVAT SEBZ ONFRZRAG-CBFF JNGRE URNGRE
{Sver Pnyy} 89529 TERRA ZBHAGNVA EQ/SZ SNYYRA, VAWHERQ XARR. BA OYBBQ GUVAAREF, XARR VF PBAGVAHVAT GB OYRRQ
{Sver Pnyy} 87943 UVTUJNL 202/URNGUREF PBHAGL UNIRA-97 LB ZNYR-CBFF QON
{Sver Pnyy} 91388 UNIRA IVRJ QE/GLCR 1 QVNORGVP, HAERFCBAFVIR, YBJ OYBBQ FHTNE

*/

choyvp pynff BEPyngfbcPbhaglCnefreGrfg rkgraqf OnfrCnefreGrfg {
  
  choyvp BEPyngfbcPbhaglCnefreGrfg() {
    frgCnefre(arj BEPyngfbcPbhaglCnefre(), "PYNGFBC PBHAGL", "BE");
  }

  @Grfg
  choyvp ibvq grfgFrnfvqrSverErfphr() {

    qbGrfg("G1",
        "{Sver Pnyy} 14 A Qbjavat Fg/RZRET ZRQVPNY ERFCBAFR/ srznyr va naq bhg bs pbafpvbhfarff",
        "PNYY:Sver Pnyy",
        "NQQE:14 A Qbjavat Fg",
        "VASB:RZRET ZRQVPNY ERFCBAFR / srznyr va naq bhg bs pbafpvbhfarff");

    qbGrfg("G2",
        "{Sver Pnyy} 2531 Zvyy Perrx Ya 101/RZRET ZRQVPNY ERFCBAFR / ibzvgvat naq qvneeurn",
        "PNYY:Sver Pnyy",
        "NQQE:2531 Zvyy Perrx Ya",
        "NCG:101",
        "VASB:RZRET ZRQVPNY ERFCBAFR / ibzvgvat naq qvneeurn");

    qbGrfg("G3",
        "{Sver Pnyy} 414 Oebnqjnl Fg/RZRET ZRQVPNY ERFCBAFR/ vax zrqvpny cbff qvnorgvp",
        "PNYY:Sver Pnyy",
        "NQQE:414 Oebnqjnl Fg",
        "VASB:RZRET ZRQVPNY ERFCBAFR / vax zrqvpny cbff qvnorgvp");

    qbGrfg("G4",
        "{Sver Pnyy} 2481 Ujl 101/RZRET ZRQVPNY ERFCBAFR",
        "PNYY:Sver Pnyy",
        "NQQE:2481 Ujl 101",
        "VASB:RZRET ZRQVPNY ERFCBAFR");

    qbGrfg("G5",
        "{Sver Pnyy} 2841 ujl 101 22/RZRET ZRQVPNY ERFCBAFR",
        "PNYY:Sver Pnyy",
        "NQQE:2841 ujl 101",
        "NCG:22",
        "VASB:RZRET ZRQVPNY ERFCBAFR");

    qbGrfg("G6",
        "{Sver Pnyy} 1126 Nirahr N 4/RZRET ZRQVPNY ERFCBAFR/ cbff 400 zt zbecuvar bireqbfr",
        "PNYY:Sver Pnyy",
        "NQQE:1126 Nirahr N",
        "NCG:4",
        "VASB:RZRET ZRQVPNY ERFCBAFR / cbff 400 zt zbecuvar bireqbfr");

    qbGrfg("G7",
        "{Sver Pnyy} 12 Uvyygbc Qe/RZRET ZRQVPNY ERFCBAFR/ cbffvoyr fgebxr",
        "PNYY:Sver Pnyy",
        "NQQE:12 Uvyygbc Qe",
        "VASB:RZRET ZRQVPNY ERFCBAFR / cbffvoyr fgebxr");

    qbGrfg("G8",
        "{Sver Pnyy} 101 Sberfg Qe 120/RZRET ZRQVPNY ERFCBAFR/ haerfc srznyr, oernguvat",
        "PNYY:Sver Pnyy",
        "NQQE:101 Sberfg Qe",
        "NCG:120",
        "VASB:RZRET ZRQVPNY ERFCBAFR / haerfc srznyr, oernguvat");

    qbGrfg("G9",
        "{Sver Pnyy} 380 Sberfg Pg/RZRET ZRQVPNY ERFCBAFR/ Yvsr Nvq zrq nyreg, hax zrqvpny",
        "PNYY:Sver Pnyy",
        "NQQE:380 Sberfg Pg",
        "VASB:RZRET ZRQVPNY ERFCBAFR / Yvsr Nvq zrq nyreg, hax zrqvpny");

    qbGrfg("G10",
        "{Sver Pnyy} 101 Sberfg qe/RZRET ZRQVPNY ERFCBAFR/ zrqvk erd, CG unf cerivbhf uvc senpgheer, cbff ervaw",
        "PNYY:Sver Pnyy",
        "NQQE:101 Sberfg qe",
        "VASB:RZRET ZRQVPNY ERFCBAFR / zrqvk erd, CG unf cerivbhf uvc senpgheer, cbff ervaw");

    qbGrfg("G11",
        "{Sver Pnyy} ZC 4 / UJL 26/NFFVFG ERAQRERQ/GERR QBJA JRFG OAQ YNAR BA CBJRE YVARF",
        "PNYY:Sver Pnyy",
        "NQQE:ZC 4 & UJL 26",
        "VASB:NFFVFG ERAQRERQ / GERR QBJA JRFG OAQ YNAR BA CBJRE YVARF");

    qbGrfg("G12",
        "{Sver Pnyy} 84389 ABEQZNEX QE/RZRET ZRQVPNY ERFCBAFR/ PNYYRE JBHYQ YVXR FVYRAG NCCEBNPU",
        "PNYY:Sver Pnyy",
        "NQQE:84389 ABEQZNEX QE",
        "VASB:RZRET ZRQVPNY ERFCBAFR / PNYYRE JBHYQ YVXR FVYRAG NCCEBNPU");

    qbGrfg("G13",
        "{Sver Pnyy} 84389 ABEQZNEX QE/RZRET ZRQVPNY ERFCBAFR/QVSS OERNGUVAT HANOYR GB TRG BHG BS ORQ",
        "PNYY:Sver Pnyy",
        "NQQE:84389 ABEQZNEX QE",
        "VASB:RZRET ZRQVPNY ERFCBAFR / QVSS OERNGUVAT HANOYR GB TRG BHG BS ORQ");

    qbGrfg("G14",
        "{Sver Pnyy} 20 A Jnunaan Eq 105/RZRET ZRQVPNY ERFCBAFR / qvssvphygl oernguvat",
        "PNYY:Sver Pnyy",
        "NQQE:20 A Jnunaan Eq",
        "NCG:105",
        "VASB:RZRET ZRQVPNY ERFCBAFR / qvssvphygl oernguvat");

    qbGrfg("G15",
        "{Sver Pnyy} 1111 A EBBFRIRYG/BQBE TNF/FZBXR/PURZVPNY/ ANGHENY TNF FZRYY",
        "PNYY:Sver Pnyy",
        "NQQE:1111 A EBBFRIRYG",
        "VASB:BQBE TNF / FZBXR / PURZVPNY / ANGHENY TNF FZRYY");

    qbGrfg("G16",
        "{Sver Pnyy} 522 A UBYYNQNL/BQBE TNF/FZBXR/PURZVPNY/ TNF YVAR UVG OL PBAFGEHPGVBA PERJ",
        "PNYY:Sver Pnyy",
        "NQQE:522 A UBYYNQNL",
        "VASB:BQBE TNF / FZBXR / PURZVPNY / TNF YVAR UVG OL PBAFGEHPGVBA PERJ");

    qbGrfg("G17",
        "{Sver Pnyy} 581 F QBJAVAT 2/RZRET ZRQVPNY ERFCBAFR/ NFFVFG ZRQVK J/ RKGEVPNGVBA",
        "PNYY:Sver Pnyy",
        "NQQE:581 F QBJAVAT 2",
        "VASB:RZRET ZRQVPNY ERFCBAFR / NFFVFG ZRQVK J / RKGEVPNGVBA");

    qbGrfg("G18",
        "{Sver Pnyy} 2445 OBRUZ NPERF EQ/RZRET ZRQVPNY ERFCBAFR/ ZNYR QVSS OERNGUVAT",
        "PNYY:Sver Pnyy",
        "NQQE:2445 OBRUZ NPERF EQ",
        "VASB:RZRET ZRQVPNY ERFCBAFR / ZNYR QVSS OERNGUVAT");

    qbGrfg("G19",
        "{Sver Pnyy} 101 SBERFG 120/RZRET ZRQVPNY ERFCBAFR/ HAERFC SRZNYR",
        "PNYY:Sver Pnyy",
        "NQQE:101 SBERFG 120",
        "VASB:RZRET ZRQVPNY ERFCBAFR / HAERFC SRZNYR");

    qbGrfg("G20",
        "{Sver Pnyy} 361 UVYYGBC QE/BQBE TNF/FZBXR/PURZVPNY/ FZRYY BS TNF VAFVQR UBHFR",
        "PNYY:Sver Pnyy",
        "NQQE:361 UVYYGBC QE",
        "VASB:BQBE TNF / FZBXR / PURZVPNY / FZRYY BS TNF VAFVQR UBHFR");

    qbGrfg("G21",
        "{Sver Pnyy} 300 F Ubyynqnl Qe/BQBE TNF/FZBXR/PURZVPNY/ FZRYY ANGHENY TNF",
        "PNYY:Sver Pnyy",
        "NQQE:300 F Ubyynqnl Qe",
        "VASB:BQBE TNF / FZBXR / PURZVPNY / FZRYY ANGHENY TNF");

    qbGrfg("G22",
        "{Sver Pnyy} 300 A cebzranqr/grfg",
        "PNYY:Sver Pnyy",
        "NQQE:300 A cebzranqr",
        "VASB:grfg");

    qbGrfg("G23",
        "{Sver Pnyy} 1131 OEBNQJNL/yvtug cbyr",
        "PNYY:Sver Pnyy",
        "NQQE:1131 OEBNQJNL",
        "VASB:yvtug cbyr");

    qbGrfg("G24",
        "{Sver Pnyy/ Qvssvphygl oernugvat} 2149 F Senaxyva 7/RZRET ZRQVPNY ERFCBAFR",
        "PNYY:Sver Pnyy/ Qvssvphygl oernugvat",
        "NQQE:2149 F Senaxyva 7",
        "VASB:RZRET ZRQVPNY ERFCBAFR");

    qbGrfg("G25",
        "{Sver Pnyy} 2149 F Senaxyva Fg 7/RZRET ZRQVPNY ERFCBAFR / yvsg nffvfg, 2aq gbar, cbff urnq vwhel, onpx cnva",
        "PNYY:Sver Pnyy",
        "NQQE:2149 F Senaxyva Fg",
        "NCG:7",
        "VASB:RZRET ZRQVPNY ERFCBAFR / yvsg nffvfg, 2aq gbar, cbff urnq vwhel, onpx cnva");

    qbGrfg("G26",
        "{Sver Pnyy} 2149 F Senaxyva Fg 7/RZRET ZRQVPNY ERFCBAFR/ snyy cng, erd ol Zrqvk",
        "PNYY:Sver Pnyy",
        "NQQE:2149 F Senaxyva Fg",
        "NCG:7",
        "VASB:RZRET ZRQVPNY ERFCBAFR / snyy cng, erd ol Zrqvk");

    qbGrfg("G27",
        "{Sver Pnyy/ Mbar 1 Trareny Sver nynez} 2500 F Ebbfriryg Qe/NYNEZ SVER",
        "PNYY:Sver Pnyy/ Mbar 1 Trareny Sver nynez",
        "NQQE:2500 F Ebbfriryg Qe",
        "VASB:NYNEZ SVER");

    qbGrfg("G28",
        "{Sver Pnyy} 150 F JNUNAAN EQ 2/RZRET ZRQVPNY ERFCBAFR TEBHAQ YRIRY SNYY URNQ YNPRENGVBA",
        "PNYY:Sver Pnyy",
        "NQQE:150 F JNUNAAN EQ",
        "NCG:2",
        "VASB:RZRET ZRQVPNY ERFCBAFR TEBHAQ YRIRY SNYY URNQ YNPRENGVBA");

    qbGrfg("G29",
        "{Sver Pnyy} 101 SBERFG QE 158/RZRET ZRQVPNY ERFCBAFR/ ZNYR SNYY CNG UVG URNQ",
        "PNYY:Sver Pnyy",
        "NQQE:101 SBERFG QE",
        "NCG:158",
        "VASB:RZRET ZRQVPNY ERFCBAFR / ZNYR SNYY CNG UVG URNQ");

    qbGrfg("G30",
        "{Sver Pnyy} 1032 24GU Nir S/RZRET ZRQVPNY ERFCBAFR",
        "PNYY:Sver Pnyy",
        "NQQE:1032 24GU Nir S",
        "VASB:RZRET ZRQVPNY ERFCBAFR");

    qbGrfg("G31",
        "{Sver Pnyy} 1235 NIR N/RZRET ZRQVPNY ERFCBAFR",
        "PNYY:Sver Pnyy",
        "NQQE:1235 NIR N",
        "VASB:RZRET ZRQVPNY ERFCBAFR");

    qbGrfg("G32",
        "{Sver Pnyy} 2500 F EBBFRIRYG/NYNEZ SVER/ TRARENY SVER NYNEZ",
        "PNYY:Sver Pnyy",
        "NQQE:2500 F EBBFRIRYG",
        "VASB:NYNEZ SVER / TRARENY SVER NYNEZ");

    qbGrfg("G33",
        "{Sver Pnyy} 20 A JNUNAAN EQ 212/RZRET ZRQVPNY ERFCBAFR/ HAX CBFF QVNORGVP",
        "PNYY:Sver Pnyy",
        "NQQE:20 A JNUNAAN EQ",
        "NCG:212",
        "VASB:RZRET ZRQVPNY ERFCBAFR / HAX CBFF QVNORGVP");

    qbGrfg("G34",
        "{Sver Pnyy} 1032 24GU NIR 13/RZRET ZRQVPNY ERFCBAFR QVNORGVP VFFHRF",
        "PNYY:Sver Pnyy",
        "NQQE:1032 24GU NIR",
        "NCG:13",
        "VASB:RZRET ZRQVPNY ERFCBAFR QVNORGVP VFFHRF");

    qbGrfg("G35",
        "{Sver Pnyy} 3EQ / ARPNAVPHZ/NFFVFG ERAQRERQ ABA PBQR SBE PYRNAHC",
        "PNYY:Sver Pnyy",
        "NQQE:3EQ",
        "VASB:ARPNAVPHZ / NFFVFG ERAQRERQ ABA PBQR SBE PYRNAHC");

    qbGrfg("G36",
        "{Sver Pnyy} 300 A CEBZ 399/RZRET ZRQVPNY ERFCBAFR/ HAX ZRQVPNY",
        "PNYY:Sver Pnyy",
        "NQQE:300 A CEBZRANQR",
        "NCG:399",
        "VASB:RZRET ZRQVPNY ERFCBAFR / HAX ZRQVPNY");

    qbGrfg("G37",
        "{Sver Pnyy/ Qvfertneq ynfg, jebat SQ} 1164 Fcehpr Pg/RZRET ZRQVPNY ERFCBAFR",
        "PNYY:Sver Pnyy/ Qvfertneq ynfg, jebat SQ",
        "NQQE:1164 Fcehpr Pg",
        "VASB:RZRET ZRQVPNY ERFCBAFR");

    qbGrfg("G38",
        "{Sver Pnyy/ Haxabja zrqvpny ceboyrz, srznyr vf pbafpvbhf naq oernguvat} 1164 Fcehpr Pg/RZRET ZRQVPNY ERFCBAFR",
        "PNYY:Sver Pnyy/ Haxabja zrqvpny ceboyrz, srznyr vf pbafpvbhf naq oernguvat",
        "NQQE:1164 Fcehpr Pg",
        "VASB:RZRET ZRQVPNY ERFCBAFR");

    qbGrfg("G39",
        "{Sver Pnyy} 1601 oebnqjnl 2/RZRET ZRQVPNY ERFCBAFR cbffvoyr fgebxr",
        "PNYY:Sver Pnyy",
        "NQQE:1601 oebnqjnl 2",
        "VASB:RZRET ZRQVPNY ERFCBAFR cbffvoyr fgebxr");

    qbGrfg("G40",
        "{Sver Pnyy} Ujl 26 / Pnzcoryy Ybbc/RZRET ZRQVPNY ERFCBAFR/ urneg pbaqvgvba, yvtug urnqrq",
        "PNYY:Sver Pnyy",
        "NQQE:Ujl 26 & Pnzcoryy Ybbc",
        "VASB:RZRET ZRQVPNY ERFCBAFR / urneg pbaqvgvba, yvtug urnqrq");

    qbGrfg("G41",
        "{Sver Pnyy} 101 Sberfg Qe 206/RZRET ZRQVPNY ERFCBAFR/ funyybj oernguvat, abg nyreg",
        "PNYY:Sver Pnyy",
        "NQQE:101 Sberfg Qe",
        "NCG:206",
        "VASB:RZRET ZRQVPNY ERFCBAFR / funyybj oernguvat, abg nyreg");

    qbGrfg("G42",
        "{Sver Pnyy/ Znyr qbja frvmher, cnexvat ybg} 60 A Ebbfriryg Qe/NFFVFG ERAQRERQ",
        "PNYY:Sver Pnyy/ Znyr qbja frvmher, cnexvat ybg",
        "NQQE:60 A Ebbfriryg Qe",
        "VASB:NFFVFG ERAQRERQ");

    qbGrfg("G43",
        "{Sver Pnyy} 1901 A UBYYVQNL/NYNEZ SNYFR/ TRARENY",
        "PNYY:Sver Pnyy",
        "NQQE:1901 A UBYYVQNL",
        "VASB:NYNEZ SNYFR / TRARENY");

    qbGrfg("G44",
        "{Sver Pnyy/ Qvssvphyygl oernguvat} 2473 DHRRA FG/RZRET ZRQVPNY ERFCBAFR",
        "PNYY:Sver Pnyy/ Qvssvphyygl oernguvat",
        "NQQE:2473 DHRRA FG",
        "VASB:RZRET ZRQVPNY ERFCBAFR");

    qbGrfg("G45",
        "{Sver Pnyy/ yrgunetvp, snyy cngvrag} 2532 Bertba Fg/RZRET ZRQVPNY ERFCBAFR",
        "PNYY:Sver Pnyy/ yrgunetvp, snyy cngvrag",
        "NQQE:2532 Bertba Fg",
        "VASB:RZRET ZRQVPNY ERFCBAFR");

    qbGrfg("G46",
        "{Sver Pnyy} 2561 A EBBFRIRYG 205/RZRET ZRQVPNY ERFCBAFR/ 21LB NHGVFGVP ZNYR FRVMHER",
        "PNYY:Sver Pnyy",
        "NQQE:2561 A EBBFRIRYG 205",
        "VASB:RZRET ZRQVPNY ERFCBAFR / 21LB NHGVFGVP ZNYR FRVMHER");

    qbGrfg("G47",
        "{Sver Pnyy} 150 F JNUNAAN 14/RZRET ZRQVPNY ERFCBAFR/ZNYR QVSS OERNGUVAT XVQQARL CEBOYRZF",
        "PNYY:Sver Pnyy",
        "NQQE:150 F JNUNAAN 14",
        "VASB:RZRET ZRQVPNY ERFCBAFR / ZNYR QVSS OERNGUVAT XVQQARL CEBOYRZF");

    qbGrfg("G48",
        "{Sver Pnyy} 3140 FHAFRG OYIQ 46/RZRET ZRQVPNY ERFCBAFR/ SNYY CNG HAX VAWHEL",
        "PNYY:Sver Pnyy",
        "NQQE:3140 FHAFRG OYIQ",
        "NCG:46",
        "VASB:RZRET ZRQVPNY ERFCBAFR / SNYY CNG HAX VAWHEL");

    qbGrfg("G49",
        "{Sver Pnyy} 3140 FHAFRG OYIQ 46/RZRET ZRQVPNY ERFCBAFR/ SRZNYR SNYY HAX VAWHEL",
        "PNYY:Sver Pnyy",
        "NQQE:3140 FHAFRG OYIQ",
        "NCG:46",
        "VASB:RZRET ZRQVPNY ERFCBAFR / SRZNYR SNYY HAX VAWHEL");

    qbGrfg("G50",
        "{Sver Pnyy} 26 NIR N 2205/RZRET ZRQVPNY ERFCBAFR QVNORGVP VFFHRF",
        "PNYY:Sver Pnyy",
        "NQQE:26 NIR N",
        "NCG:2205",
        "VASB:RZRET ZRQVPNY ERFCBAFR QVNORGVP VFFHRF");

    qbGrfg("G51",
        "{Sver Pnyy NFFVFG J/ RKGNPNGVBA} 101 SBERFG Qe/RZRET ZRQVPNY ERFCBAFR",
        "PNYY:Sver Pnyy NFFVFG J/ RKGNPNGVBA",
        "NQQE:101 SBERFG Qe",
        "VASB:RZRET ZRQVPNY ERFCBAFR");

    qbGrfg("G52",
        "{Sver Pnyy} 227 Oebnqjnl Fg/QVFGHEONAPR GNFRE ERZBINY",
        "PNYY:Sver Pnyy",
        "NQQE:227 Oebnqjnl Fg",
        "VASB:QVFGHEONAPR GNFRE ERZBINY");

    qbGrfg("G53",
        "{Sver Pnyy} 1140/RZRET ZRQVPNY ERFCBAFR/ SRZNY SNVAG PBA / OERNGUVAT",
        "PNYY:Sver Pnyy",
        "NQQE:1140",
        "VASB:RZRET ZRQVPNY ERFCBAFR / SRZNY SNVAG PBA / OERNGUVAT");

    qbGrfg("G54",
        "{Sver Pnyy} 825 A UBYYNQNL 2/RZRET ZRQVPNY ERFCBAFR/ HAX ZRQVPNY CQ BA FPRAR",
        "PNYY:Sver Pnyy",
        "NQQE:825 A UBYYNQNL 2",
        "VASB:RZRET ZRQVPNY ERFCBAFR / HAX ZRQVPNY CQ BA FPRAR");

    qbGrfg("G55",
        "{Sver Pnyy} 1530 F EBBFRIRYG Qe/RZRET ZRQVPNY ERFCBAFR QVSSVPHYGL OERNGUVAT",
        "PNYY:Sver Pnyy",
        "NQQE:1530 F EBBFRIRYG Qe",
        "VASB:RZRET ZRQVPNY ERFCBAFR QVSSVPHYGL OERNGUVAT");

    qbGrfg("G56",
        "{Sver Pnyy} 2125 F QBJAVAT 10/RZRET ZRQVPNY ERFCBAFR PURFG CNVAF",
        "PNYY:Sver Pnyy",
        "NQQE:2125 F QBJAVAT 10",
        "VASB:RZRET ZRQVPNY ERFCBAFR PURFG CNVAF");

    qbGrfg("G57",
        "{Sver Pnyy} 770 16gu Nir/QVFGHEONAPR/ fcnexf sebz puvzarl ynaqvat ba ebbs",
        "PNYY:Sver Pnyy",
        "NQQE:770 16gu Nir",
        "VASB:QVFGHEONAPR / fcnexf sebz puvzarl ynaqvat ba ebbs");

    qbGrfg("G58",
        "{Sver Pnyy} 602 A Cebz/NYNEZ SVER/ tnf yrnx nynez",
        "PNYY:Sver Pnyy",
        "NQQE:602 A CEBZRANQR",
        "VASB:NYNEZ SVER / tnf yrnx nynez");

    qbGrfg("G59",
        "{Sver Pnyy} 2531 ZVYYPERRX YA 101/RZRET ZRQVPNY ERFCBAFR/SRZNYR QVSS OERNGUVAT",
        "PNYY:Sver Pnyy",
        "NQQE:2531 ZVYYPERRX YA",
        "NCG:101",
        "VASB:RZRET ZRQVPNY ERFCBAFR / SRZNYR QVSS OERNGUVAT");

    qbGrfg("G60",
        "{Sver Pnyy/ Sver nynez chyy fgngvba 4gu sybbe Rnfg fgnvef} 475 F cebz/NYNEZ SVER",
        "PNYY:Sver Pnyy/ Sver nynez chyy fgngvba 4gu sybbe Rnfg fgnvef",
        "NQQE:475 F CEBZRANQR",
        "VASB:NYNEZ SVER");

    qbGrfg("G61",
        "{Sver Pnyy OERNGUVAT QVSS} 1126 NIRAHR N 4/RZRET ZRQVPNY ERFCBAFR",
        "PNYY:Sver Pnyy OERNGUVAT QVSS",
        "NQQE:1126 NIRAHR N",
        "NCG:4",
        "VASB:RZRET ZRQVPNY ERFCBAFR");

    qbGrfg("G62",
        "{Sver Pnyy} 800 F UBYYNQNL 3/NYNEZ SVER/ SVER NYNEZ",
        "PNYY:Sver Pnyy",
        "NQQE:800 F UBYYNQNL 3",
        "VASB:NYNEZ SVER / SVER NYNEZ");

    qbGrfg("G63",
        "{Sver Pnyy} 470 14GU/19 LE BYQ ZNYR ERFVQRAG URNEVAT IBVPRF ABA IVBYRAG",
        "PNYY:Sver Pnyy",
        "NQQE:470 14GU",
        "VASB:19 LE BYQ ZNYR ERFVQRAG URNEVAT IBVPRF ABA IVBYRAG");

    qbGrfg("G64",
        "{Sver Pnyy} 2069 PBBCRE FG/RZRET ZRQVPNY ERFCBAFR/QVSS OERNGUVAT UVFG BS PBCQ",
        "PNYY:Sver Pnyy",
        "NQQE:2069 PBBCRE FG",
        "VASB:RZRET ZRQVPNY ERFCBAFR / QVSS OERNGUVAT UVFG BS PBCQ");

    qbGrfg("G65",
        "{Sver Pnyy} 1355 11gu Nir/RZRET ZRQVPNY ERFCBAFR/ SRZNYR QEVAXVAT NAQ GBBX CVYYF AB ZBER VAS",
        "PNYY:Sver Pnyy",
        "NQQE:1355 11gu Nir",
        "VASB:RZRET ZRQVPNY ERFCBAFR / SRZNYR QEVAXVAT NAQ GBBX CVYYF AB ZBER VAS");

    qbGrfg("G66",
        "{Sver Pnyy} EBBFRIRYG / 16GU NIR/ZBGBE IRU NPPVQRAG/ HAX VAW",
        "PNYY:Sver Pnyy",
        "NQQE:EBBFRIRYG & 16GU NIR",
        "VASB:ZBGBE IRU NPPVQRAG / HAX VAW");

    qbGrfg("G67",
        "{Sver Pnyy} 429 F Ubyynqnl Qe 19/RZRET ZRQVPNY ERFCBAFR/ 46 LB QVSS OERNGUVAT, VA ONPX BS ZBGRY",
        "PNYY:Sver Pnyy",
        "NQQE:429 F Ubyynqnl Qe",
        "NCG:19",
        "VASB:RZRET ZRQVPNY ERFCBAFR / 46 LB QVSS OERNGUVAT, VA ONPX BS ZBGRY");

    qbGrfg("G68",
        "{Sver Pnyy} 2500 F EBBFRIRYG 241/RZRET ZRQVPNY ERFCBAFR/ SNYY CNG URNQ VAWHEL 2AQ SNYY GBQNL",
        "PNYY:Sver Pnyy",
        "NQQE:2500 F EBBFRIRYG 241",
        "VASB:RZRET ZRQVPNY ERFCBAFR / SNYY CNG URNQ VAWHEL 2AQ SNYY GBQNL");

    qbGrfg("G69",
        "{Sver Pnyy TNF BQBE} 1700 A UBYYNQNL QE/BQBE TNF/FZBXR/PURZVPNY",
        "PNYY:Sver Pnyy TNF BQBE",
        "NQQE:1700 A UBYYNQNL QE",
        "VASB:BQBE TNF / FZBXR / PURZVPNY");

    qbGrfg("G70",
        "{Sver Pnyy} 1700 A UBYYNQNL QE/BQBE TNF/FZBXR/PURZVPNY",
        "PNYY:Sver Pnyy",
        "NQQE:1700 A UBYYNQNL QE",
        "VASB:BQBE TNF / FZBXR / PURZVPNY");

    qbGrfg("G71",
        "{Sver Pnyy} 2500 F EBBFRIRYG 134/RZRET ZRQVPNY ERFCBAFR/ZRQVK QRYNLRQ  CQ BA FPRAR",
        "PNYY:Sver Pnyy",
        "NQQE:2500 F EBBFRIRYG 134",
        "VASB:RZRET ZRQVPNY ERFCBAFR / ZRQVK QRYNLRQ  CQ BA FPRAR");

    qbGrfg("G72",
        "{Sver Pnyy} 15 OEBNQJNL/RZRET ZRQVPNY ERFCBAFR/ BHGFVQR GRE UNE'F 70 ZNYR",
        "PNYY:Sver Pnyy",
        "NQQE:15 OEBNQJNL",
        "VASB:RZRET ZRQVPNY ERFCBAFR / BHGFVQR GRE UNE'F 70 ZNYR");

    qbGrfg("G73",
        "{Sver Pnyy} 441 2AQ NIR/NYNEZ SVER/ JNGRE SYBJ",
        "PNYY:Sver Pnyy",
        "NQQE:441 2AQ NIR",
        "VASB:NYNEZ SVER / JNGRE SYBJ");

    qbGrfg("G74",
        "{Sver Pnyy, CBFF PIN} 830 7GU FGERRG/RZRET ZRQVPNY ERFCBAFR, 92LBS P/O, CBFF PIN. ZRQVK RAEG",
        "PNYY:Sver Pnyy, CBFF PIN",
        "NQQE:830 7GU FGERRG",
        "VASB:RZRET ZRQVPNY ERFCBAFR, 92LBS P / O, CBFF PIN. ZRQVK RAEG");

    qbGrfg("G75",
        "{Sver Pnyy} 545 OEBNQJNL/RZRET ZRQVPNY ERFCBAFR QVNORGVP VFFHRF",
        "PNYY:Sver Pnyy",
        "NQQE:545 OEBNQJNL",
        "VASB:RZRET ZRQVPNY ERFCBAFR QVNORGVP VFFHRF");

    qbGrfg("G76",
        "{Sver Pnyy} 889 A Yvapbya Fg/RZRET ZRQVPNY ERFCBAFR/ purfg cnva",
        "PNYY:Sver Pnyy",
        "NQQE:889 A Yvapbya Fg",
        "VASB:RZRET ZRQVPNY ERFCBAFR / purfg cnva");

    qbGrfg("G77",
        "{Sver Pnyy} 101 Sberfg Qe/NYNEZ SVER/ ebbzf 101-120 fzbxr qrgrpgbe",
        "PNYY:Sver Pnyy",
        "NQQE:101 Sberfg Qe",
        "VASB:NYNEZ SVER / ebbzf 101-120 fzbxr qrgrpgbe");

    qbGrfg("G78",
        "{Sver Pnyy FURQ SVER} 1320 PNFNPNEN YA/FGEHP SVER 1FG",
        "PNYY:Sver Pnyy FURQ SVER",
        "NQQE:1320 PNFNPNEN YA",
        "VASB:FGEHP SVER 1FG");

    qbGrfg("G79",
        "{Sver Pnyy} 1032 24gu Nir T/RZRET ZRQVPNY ERFCBAFR/ purfg cnvaf",
        "PNYY:Sver Pnyy",
        "NQQE:1032 24gu Nir T",
        "VASB:RZRET ZRQVPNY ERFCBAFR / purfg cnvaf");

    qbGrfg("G80",
        "{Sver Pnyy} EBBFRIRYG / 15GU NIR/RZRET ZRQVPNY ERFCBAFR/ ZBGBEPLYP ZIN",
        "PNYY:Sver Pnyy",
        "NQQE:EBBFRIRYG & 15GU NIR",
        "VASB:RZRET ZRQVPNY ERFCBAFR / ZBGBEPLYP ZIN");

    qbGrfg("G81",
        "{Sver Pnyy 2 iruvpyr ZIN} 2455 F EBBFRIRYG Qe/RZRET ZRQVPNY ERFCBAFR",
        "PNYY:Sver Pnyy 2 iruvpyr ZIN",
        "NQQE:2455 F EBBFRIRYG Qe",
        "VASB:RZRET ZRQVPNY ERFCBAFR");

    qbGrfg("G82",
        "{Sver Pnyy YVSG NFFVFG JVGU ZRQVK} 1235 NIR N/RZRET ZRQVPNY ERFCBAFR",
        "PNYY:Sver Pnyy YVSG NFFVFG JVGU ZRQVK",
        "NQQE:1235 NIR N",
        "VASB:RZRET ZRQVPNY ERFCBAFR");

    qbGrfg("G83",
        "{Sver Pnyy FRVMHER CG} 1235 NIRAHR N/RZRET ZRQVPNY ERFCBAFR",
        "PNYY:Sver Pnyy FRVMHER CG",
        "NQQE:1235 NIRAHR N",
        "VASB:RZRET ZRQVPNY ERFCBAFR");

    qbGrfg("G84",
        "{Sver Pnyy} 3eq Nir / Arpnavphz/RZRET ZRQVPNY ERFCBAFR / bireghearq lryybj pnabr",
        "PNYY:Sver Pnyy",
        "NQQE:3eq Nir",
        "VASB:Arpnavphz / RZRET ZRQVPNY ERFCBAFR / bireghearq lryybj pnabr");

    qbGrfg("G85",
        "{Sver Pnyy/Gerr qbja Oybpxvat gur uvtujnl obgu ynarf bs geniry} Uvtujnl 26 / Zc 3/RZRET ZRQVPNY ERFCBAFR",
        "PNYY:Sver Pnyy/Gerr qbja Oybpxvat gur uvtujnl obgu ynarf bs geniry",
        "NQQE:Uvtujnl 26",
        "VASB:Zc 3 / RZRET ZRQVPNY ERFCBAFR");

    qbGrfg("G86",
        "{Sver Pnyy} 1235 NIRAHR N/RZRET ZRQVPNY ERFCBAFR/ FRVMHER",
        "PNYY:Sver Pnyy",
        "NQQE:1235 NIRAHR N",
        "VASB:RZRET ZRQVPNY ERFCBAFR / FRVMHER");

    qbGrfg("G87",
        "{Sver Pnyy} 441 2aq Nir/RZRET ZRQVPNY ERFCBAFR BIREQBRF",
        "PNYY:Sver Pnyy",
        "NQQE:441 2aq Nir",
        "VASB:RZRET ZRQVPNY ERFCBAFR BIREQBRF");

    qbGrfg("G88",
        "{Sver Pnyy} 33983 PBYRF YA/BGURE NYY RYQREYL SRZ CBFF ABG OERNGUVAT",
        "PNYY:Sver Pnyy",
        "NQQE:33983 PBYRF YA",
        "VASB:BGURE NYY RYQREYL SRZ CBFF ABG OERNGUVAT");

    qbGrfg("G89",
        "{Sver Pnyy} 122 11GU NIR/RZRET ZRQVPNY ERFCBAFR ZNYR PBYNCFRQ",
        "PNYY:Sver Pnyy",
        "NQQE:122 11GU NIR",
        "VASB:RZRET ZRQVPNY ERFCBAFR ZNYR PBYNCFRQ");

    qbGrfg("G90",
        "{Sver Pnyy} 401 F Ebbfriryg Qe/FRYS PURPX BHG SRZNYR CNFFRQ BHG",
        "PNYY:Sver Pnyy",
        "NQQE:401 F Ebbfriryg Qe",
        "VASB:FRYS PURPX BHG SRZNYR CNFFRQ BHG");

    qbGrfg("G91",
        "{Sver Pnyy} 65 8gu nir/NFFVFG BGURE NTRAPL",
        "PNYY:Sver Pnyy",
        "NQQE:65 8gu nir",
        "VASB:NFFVFG BGURE NTRAPL");

    qbGrfg("G92",
        "{Sver Pnyy} 724 OEBNQJNL/RZRET ZRQVPNY ERFCBAFR",
        "PNYY:Sver Pnyy",
        "NQQE:724 OEBNQJNL",
        "VASB:RZRET ZRQVPNY ERFCBAFR");

    qbGrfg("G93",
        "{Sver Pnyy} 150 F JNUNAAN 20/NYNEZ SVER/ AB BAR UBZR",
        "PNYY:Sver Pnyy",
        "NQQE:150 F JNUNAAN 20",
        "VASB:NYNEZ SVER / AB BAR UBZR");

    qbGrfg("G94",
        "{Sver Pnyy} ABEGU UJL 101 / WPG/RZRET ZRQVPNY ERFCBAFR/ ZC 25 UJL 101",
        "PNYY:Sver Pnyy",
        "NQQE:ABEGU UJL",
        "NCG:101",
        "VASB:WPG / RZRET ZRQVPNY ERFCBAFR / ZC 25 UJL 101");

    qbGrfg("G95",
        "{Sver Pnyy} 101 SBERFG QE/RZRET ZRQVPNY ERFCBAFR/ SRZNYR CBFF FGEBXR",
        "PNYY:Sver Pnyy",
        "NQQE:101 SBERFG QE",
        "VASB:RZRET ZRQVPNY ERFCBAFR / SRZNYR CBFF FGEBXR");

    qbGrfg("G96",
        "{Sver Pnyy} 20 A JNUNAAN EQ/RZRET ZRQVPNY ERFCBAFR/ SNYY CNG URNQ VAWHEL",
        "PNYY:Sver Pnyy",
        "NQQE:20 A JNUNAAN EQ",
        "VASB:RZRET ZRQVPNY ERFCBAFR / SNYY CNG URNQ VAWHEL");

    qbGrfg("G97",
        "{Sver Pnyy} 400 ARPNAVPHZ QE NCG 3/RZRET ZRQVPNY ERFCBAFR/ qvss oernguvat",
        "PNYY:Sver Pnyy",
        "NQQE:400 ARPNAVPHZ QE",
        "NCG:3",
        "VASB:RZRET ZRQVPNY ERFCBAFR / qvss oernguvat");

    qbGrfg("G98",
        "{Sver Pnyy} 810 F UBYYNQNL 14/RZRET ZRQVPNY ERFCBAFR",
        "PNYY:Sver Pnyy",
        "NQQE:810 F UBYYNQNL 14",
        "VASB:RZRET ZRQVPNY ERFCBAFR");

    qbGrfg("G99",
        "{Sver Pnyy} 323 Oebnqjnl/RZRET ZRQVPNY ERFCBAFR/ Bssvpre qbja, fubgf sverq",
        "PNYY:Sver Pnyy",
        "NQQE:323 Oebnqjnl",
        "VASB:RZRET ZRQVPNY ERFCBAFR / Bssvpre qbja, fubgf sverq");

    qbGrfg("G100",
        "{Sver Pnyy} 1111 A Ebbfriryg Qe 400/NYNEZ SVER/ trareny sver nynez",
        "PNYY:Sver Pnyy",
        "NQQE:1111 A Ebbfriryg Qe",
        "NCG:400",
        "VASB:NYNEZ SVER / trareny sver nynez");

  }

  @Grfg
  choyvp ibvq grfgTrneunegISQ() {

    qbGrfg("G1",
        "{Sver Pnyy} 2531 Zvyy Perrx Ya 101/RZRET ZRQVPNY ERFCBAFR/ nffvfg frnfvqr srznyr fvpx",
        "PNYY:Sver Pnyy",
        "NQQE:2531 Zvyy Perrx Ya",
        "NCG:101",
        "VASB:RZRET ZRQVPNY ERFCBAFR / nffvfg frnfvqr srznyr fvpx");

    qbGrfg("G2",
        "{Sver Pnyy} 816 Q Fg/RZRET ZRQVPNY ERFCBAFR/ urneg nggnpx bhg onpx ol jngre",
        "PNYY:Sver Pnyy",
        "NQQE:816 Q Fg",
        "VASB:RZRET ZRQVPNY ERFCBAFR / urneg nggnpx bhg onpx ol jngre");

    qbGrfg("G3",
        "{Sver Pnyy} 233 F BPRNA QE/RZRET ZRQVPNY ERFCBAFR/HAX ZRQVPNY, ZRQVPNY NYREG NYNEZ",
        "PNYY:Sver Pnyy",
        "NQQE:233 F BPRNA QE",
        "VASB:RZRET ZRQVPNY ERFCBAFR / HAX ZRQVPNY, ZRQVPNY NYREG NYNEZ");

    qbGrfg("G4",
        "{Sver Pnyy} 33645 PHYYNOL YNXR YA/RZRET ZRQVPNY ERFCBAFR/ ABG tbvat CBI, cyrnfr erfcbaq",
        "PNYY:Sver Pnyy",
        "NQQE:33645 PHYYNOL YNXR YA",
        "VASB:RZRET ZRQVPNY ERFCBAFR / ABG tbvat CBI, cyrnfr erfcbaq");

    qbGrfg("G5",
        "{Sver Pnyy} 33645 PHYYNOL YNXR YA/RZRET ZRQVPNY ERFCBAFR/ cngvrag tbvat CBI",
        "PNYY:Sver Pnyy",
        "NQQE:33645 PHYYNOL YNXR YA",
        "VASB:RZRET ZRQVPNY ERFCBAFR / cngvrag tbvat CBI");

    qbGrfg("G6",
        "{Sver Pnyy} 33645 PHYYNOL YNXR YA/RZRET ZRQVPNY ERFCBAFR/ 74 lbz qvssvphygl oernguvat",
        "PNYY:Sver Pnyy",
        "NQQE:33645 PHYYNOL YNXR YA",
        "VASB:RZRET ZRQVPNY ERFCBAFR / 74 lbz qvssvphygl oernguvat");

    qbGrfg("G7",
        "{Sver Pnyy} FUNZEBPX / CVAR EVQTR/RZRET ZRQVPNY ERFCBAFR/16 LB UVG VA GUR URNQ, OYRRQVAT",
        "PNYY:Sver Pnyy",
        "NQQE:FUNZEBPX",
        "VASB:CVAR EVQTR / RZRET ZRQVPNY ERFCBAFR / 16 LB UVG VA GUR URNQ, OYRRQVAT");

    qbGrfg("G8",
        "{Sver Pnyy} 90338 UVTUJNL 101/RZRET ZRQVPNY ERFCBAFR/ PURFG CNVA",
        "PNYY:Sver Pnyy",
        "NQQE:90338 UVTUJNL 101",
        "VASB:RZRET ZRQVPNY ERFCBAFR / PURFG CNVA");

    qbGrfg("G9",
        "{Sver Pnyy} 731 S FG/NYNEZ SNYFR FGNAQ QBJA",
        "PNYY:Sver Pnyy",
        "NQQE:731 S FG",
        "VASB:NYNEZ SNYFR FGNAQ QBJA");

    qbGrfg("G10",
        "{Sver Pnyy} 729 A ZNEVBA NIR/RZRET ZRQVPNY ERFCBAFR/ HAX ZRQVPNY ZNYR PBA OERNGUVAT",
        "PNYY:Sver Pnyy",
        "NQQE:729 A ZNEVBA NIR",
        "VASB:RZRET ZRQVPNY ERFCBAFR / HAX ZRQVPNY ZNYR PBA OERNGUVAT");

    qbGrfg("G11",
        "{Sver Pnyy} UVTUYNAQF YA / 101/RZRET ZRQVPNY ERFCBAFR/ FVATYR IRU ZIN",
        "PNYY:Sver Pnyy",
        "NQQE:UVTUYNAQF YA",
        "VASB:101 / RZRET ZRQVPNY ERFCBAFR / FVATYR IRU ZIN");

    qbGrfg("G12",
        "{Sver Pnyy/ YBPX OBK 1937} 5071 FUREVQNA QE/RZRET ZRQVPNY ERFCBAFR/ SNYY CNG",
        "PNYY:Sver Pnyy/ YBPX OBK 1937",
        "NQQE:5071 FUREVQNA QE",
        "VASB:RZRET ZRQVPNY ERFCBAFR / SNYY CNG");

    qbGrfg("G13",
        "{Sver Pnyy} 102 5gu Fg/NYNEZ SVER / sver nynez cre nynez pbzcnal",
        "PNYY:Sver Pnyy",
        "NQQE:102 5gu Fg",
        "VASB:NYNEZ SVER / sver nynez cre nynez pbzcnal");

    qbGrfg("G14",
        "{Sver Pnyy} 89660 ZNAVBA QE/RZRET ZRQVPNY ERFCBAFR CNAVP NGGNPX CBFF BQ",
        "PNYY:Sver Pnyy",
        "NQQE:89660 ZNAVBA QE",
        "VASB:RZRET ZRQVPNY ERFCBAFR CNAVP NGGNPX CBFF BQ");

    qbGrfg("G15",
        "{Sver Pnyy} 89449 UVTUJNL 101/RZRET ZRQVPNY ERFCBAFR/ yvsg nffvfg",
        "PNYY:Sver Pnyy",
        "NQQE:89449 UVTUJNL 101",
        "VASB:RZRET ZRQVPNY ERFCBAFR / yvsg nffvfg");

    qbGrfg("G16",
        "{Sver Pnyy} 33820 YNXR SEBAG QE/RZRET ZRQVPNY ERFCBAFR/ 80 LB QVSS OERNGUVAT",
        "PNYY:Sver Pnyy",
        "NQQE:33820 YNXR SEBAG QE",
        "VASB:RZRET ZRQVPNY ERFCBAFR / 80 LB QVSS OERNGUVAT");

    qbGrfg("G17",
        "{Sver Pnyy} 729 A ZNEVBA/RZRET ZRQVPNY ERFCBAFR/ 60 -70 ZNYR PBASHFRQ CBFF HGV",
        "PNYY:Sver Pnyy",
        "NQQE:729 A ZNEVBA",
        "VASB:RZRET ZRQVPNY ERFCBAFR / 60 -70 ZNYR PBASHFRQ CBFF HGV");

    qbGrfg("G18",
        "{Sver Pnyy} 3855 UJL 101 A/RZRET ZRQVPNY ERFCBAFR/ 2 IRUVPYR ZIN",
        "PNYY:Sver Pnyy",
        "NQQE:3855 UJL 101 A",
        "VASB:RZRET ZRQVPNY ERFCBAFR / 2 IRUVPYR ZIN");

    qbGrfg("G19",
        "{Sver Pnyy} 806 ZPPBEZVPX TNEQRAF EQ/RZRET ZRQVPNY ERFCBAFR",
        "PNYY:Sver Pnyy",
        "NQQE:806 ZPPBEZVPX TNEQRAF EQ",
        "VASB:RZRET ZRQVPNY ERFCBAFR");

    qbGrfg("G20",
        "{Sver Pnyy/ SRZNYR HAX ZRQ } 2017 TERNEUNEG TERRAF EQ 802/RZRET ZRQVPNY ERFCBAFR",
        "PNYY:Sver Pnyy/ SRZNYR HAX ZRQ",
        "NQQE:2017 TERNEUNEG TERRAF EQ",
        "NCG:802",
        "VASB:RZRET ZRQVPNY ERFCBAFR");

    qbGrfg("G21",
        "{Sver Pnyy} 268 EVQTR QE/RZRET ZRQVPNY ERFCBAFR",
        "PNYY:Sver Pnyy",
        "NQQE:268 EVQTR QE",
        "VASB:RZRET ZRQVPNY ERFCBAFR");

    qbGrfg("G22",
        "{Sver Pnyy} Ujl 101 ZC 17/ZBGBE IRU NPPVQRAG/ 2 pnef if ryx",
        "PNYY:Sver Pnyy",
        "NQQE:Ujl 101",
        "CYNPR:ZC 17",
        "VASB:ZBGBE IRU NPPVQRAG / 2 pnef if ryx");

    qbGrfg("G23",
        "{Sver Pnyy} 4206 Uvtujnl 101 A/RZRET ZRQVPNY ERFCBAFR/ frvmher",
        "PNYY:Sver Pnyy",
        "NQQE:4206 Uvtujnl 101 A",
        "VASB:RZRET ZRQVPNY ERFCBAFR / frvmher");

    qbGrfg("G24",
        "{Sver Pnyy} 729 A Znevba/RZRET ZRQVPNY ERFCBAFR/YVSG NFFVFG - XRA",
        "PNYY:Sver Pnyy",
        "NQQE:729 A Znevba",
        "VASB:RZRET ZRQVPNY ERFCBAFR / YVSG NFFVFG - XRA");

    qbGrfg("G25",
        "{Sver Pnyy} 89953 FRNYRF EQ/RZRET ZRQVPNY ERFCBAFR/ 68 LB ZNYR PURFG CNVAF",
        "PNYY:Sver Pnyy",
        "NQQE:89953 FRNYRF EQ",
        "VASB:RZRET ZRQVPNY ERFCBAFR / 68 LB ZNYR PURFG CNVAF");

    qbGrfg("G26",
        "{Sver Pnyy} 89953 FRNYRF EQ/RZRET ZRQVPNY ERFCBAFR/ 68  ZNYR PURFG CNVAF",
        "PNYY:Sver Pnyy",
        "NQQE:89953 FRNYRF EQ",
        "VASB:RZRET ZRQVPNY ERFCBAFR / 68  ZNYR PURFG CNVAF");

    qbGrfg("G27",
        "{Sver Pnyy CBFF FGEBXR PBAF QVSS OERNGUVAT} 1393 R CVAR QE/RZRET ZRQVPNY ERFCBAFR",
        "PNYY:Sver Pnyy CBFF FGEBXR PBAF QVSS OERNGUVAT",
        "NQQE:1393 R CVAR QE",
        "VASB:RZRET ZRQVPNY ERFCBAFR");

    qbGrfg("G28",
        "{Sver Pnyy ZRQVPNY NYREG NPGVINGVBA} 233 F BPRNA NIR/RZRET ZRQVPNY ERFCBAFR",
        "PNYY:Sver Pnyy ZRQVPNY NYREG NPGVINGVBA",
        "NQQE:233 F BPRNA NIR",
        "VASB:RZRET ZRQVPNY ERFCBAFR");

    qbGrfg("G29",
        "{Sver Pnyy} 4206 UVTUJNL 101 A/ZBGBE IRU NPPVQRAG/ ZIN",
        "PNYY:Sver Pnyy",
        "NQQE:4206 UVTUJNL 101 A",
        "VASB:ZBGBE IRU NPPVQRAG / ZIN");

    qbGrfg("G30",
        "{RZF PNYY} 1308 CNEX YA/RZRET ZRQVPNY ERFCBAFR, SNYY CNGVRAG AB VAW",
        "PNYY:RZF PNYY",
        "NQQE:1308 CNEX YA",
        "VASB:RZRET ZRQVPNY ERFCBAFR, SNYY CNGVRAG AB VAW");

    qbGrfg("G31",
        "{Sver Pnyy/ qvmml crefba qnex oyhr} Ujl 101 / Jvyq Qnssbqvy/RZRET ZRQVPNY ERFCBAFR",
        "PNYY:Sver Pnyy/ qvmml crefba qnex oyhr",
        "NQQE:Ujl 101",
        "VASB:Jvyq Qnssbqvy / RZRET ZRQVPNY ERFCBAFR");

    qbGrfg("G32",
        "{Sver Pnyy/purfg cnva } 89121 cvaruhefg/RZRET ZRQVPNY ERFCBAFR",
        "PNYY:Sver Pnyy/purfg cnva",
        "NQQE:89121 cvaruhefg",
        "VASB:RZRET ZRQVPNY ERFCBAFR");

    qbGrfg("G33",
        "{Sver Pnyy 2921 ZBIR HC F31} 1320 PNFNPNEN YA/FGEHP SVER 1FG",
        "PNYY:Sver Pnyy 2921 ZBIR HC F31",
        "NQQE:1320 PNFNPNEN YA",
        "VASB:FGEHP SVER 1FG");

    qbGrfg("G34",
        "{Sver Pnyy} 102 5GU FG/NYNEZ SVER/ FZBXR NYNEZ",
        "PNYY:Sver Pnyy",
        "NQQE:102 5GU FG",
        "VASB:NYNEZ SVER / FZBXR NYNEZ");

    qbGrfg("G35",
        "{Sver Pnyy} 101 / qry zbbe ybbc/RZRET ZRQVPNY ERFCBAFR/ 1 ZIN, UVG ONEEVRE HAX VAW",
        "PNYY:Sver Pnyy",
        "NQQE:101 & qry zbbe ybbc",
        "VASB:RZRET ZRQVPNY ERFCBAFR / 1 ZIN, UVG ONEEVRE HAX VAW");

    qbGrfg("G36",
        "{Sver Pnyy} 862 F ZNEVBA/RZRET ZRQVPNY ERFCBAFR/ ZNYR CBFF FGEBXR",
        "PNYY:Sver Pnyy",
        "NQQE:862 F ZNEVBA",
        "VASB:RZRET ZRQVPNY ERFCBAFR / ZNYR CBFF FGEBXR");

    qbGrfg("G37",
        "{Sver Pnyy} SHYZRE, JNLAR/RZRET ZRQVPNY ERFCBAFR/ snyy cg, PBCQ j/b sbe n gvzr",
        "PNYY:Sver Pnyy",
        "NQQE:SHYZRE",
        "CYNPR:JNLAR",
        "VASB:RZRET ZRQVPNY ERFCBAFR / snyy cg, PBCQ j / b sbe n gvzr");

    qbGrfg("G38",
        "{Sver Pnyy} 89830 J naqrefba eq/PUVZARL SVER",
        "PNYY:Sver Pnyy",
        "NQQE:89830 J naqrefba eq",
        "VASB:PUVZARL SVER");

    qbGrfg("G39",
        "{Sver Pnyy} QRY ENL / 101/ZIN FREVBHF VAWHEL/ ZIN QHZC GEHPX GUNGF SYVCCRQ",
        "PNYY:Sver Pnyy",
        "NQQE:QRY ENL",
        "VASB:101 / ZIN FREVBHF VAWHEL / ZIN QHZC GEHPX GUNGF SYVCCRQ");

    qbGrfg("G40",
        "{Sver Pnyy} 61 BPRNA NIR/RZRET ZRQVPNY ERFCBAFR/ 30 SRZNYRQVNORGVP VFFHR",
        "PNYY:Sver Pnyy",
        "NQQE:61 BPRNA NIR",
        "VASB:RZRET ZRQVPNY ERFCBAFR / 30 SRZNYRQVNORGVP VFFHR");

    qbGrfg("G41",
        "{Sver Pnyy} 61 BPRNA NIR/RZRET ZRQVPNY ERFCBAFR/ QVNORGVP VFFHR",
        "PNYY:Sver Pnyy",
        "NQQE:61 BPRNA NIR",
        "VASB:RZRET ZRQVPNY ERFCBAFR / QVNORGVP VFFHR");

    qbGrfg("G42",
        "{Sver Pnyy} 33538 NQNVE YA/RZRET ZRQVPNY ERFCBAFR/ ZNYR PBCQ / QVSS OERNGUUVAT",
        "PNYY:Sver Pnyy",
        "NQQE:33538 NQNVE YA",
        "VASB:RZRET ZRQVPNY ERFCBAFR / ZNYR PBCQ / QVSS OERNGUUVAT");

    qbGrfg("G43",
        "{Sver Pnyy} 1308 CNEX YA/RZRET ZRQVPNY ERFCBAFR SNYY CG TEBHAQ YRIRY",
        "PNYY:Sver Pnyy",
        "NQQE:1308 CNEX YA",
        "VASB:RZRET ZRQVPNY ERFCBAFR SNYY CG TEBHAQ YRIRY");

    qbGrfg("G44",
        "{Sver Pnyy PURFG CNVAF} 683 10GU FG/RZRET ZRQVPNY ERFCBAFR",
        "PNYY:Sver Pnyy PURFG CNVAF",
        "NQQE:683 10GU FG",
        "VASB:RZRET ZRQVPNY ERFCBAFR");

    qbGrfg("G45",
        "{Sver Pnyy} 4306 UVTUJNL 101 A/RZRET ZRQVPNY ERFCBAFR/ zragny urnygu fhvpvqny, ynlvat va cnexvat ybg",
        "PNYY:Sver Pnyy",
        "NQQE:4306 UVTUJNL 101 A",
        "VASB:RZRET ZRQVPNY ERFCBAFR / zragny urnygu fhvpvqny, ynlvat va cnexvat ybg");

    qbGrfg("G46",
        "{Sver Pnyy} 89449 UVTUJNL 101 A/RZRET ZRQVPNY ERFCBAFR/ ZNYR GRZC NFCRENGVAT",
        "PNYY:Sver Pnyy",
        "NQQE:89449 UVTUJNL 101 A",
        "VASB:RZRET ZRQVPNY ERFCBAFR / ZNYR GRZC NFCRENGVAT");

    qbGrfg("G47",
        "{Sver Pnyy} 981 YVGGYR ORNPU QE/NYNEZ SVER/ SVER NYNEZ HAX YBPNGVBA",
        "PNYY:Sver Pnyy",
        "NQQE:981 YVGGYR ORNPU QE",
        "VASB:NYNEZ SVER / SVER NYNEZ HAX YBPNGVBA");

    qbGrfg("G48",
        "{Sver Pnyy} 89449 UVTUJNL 101 A/RZRET ZRQVPNY ERFCBAFR/ 56 ZNYR FRVMHER",
        "PNYY:Sver Pnyy",
        "NQQE:89449 UVTUJNL 101 A",
        "VASB:RZRET ZRQVPNY ERFCBAFR / 56 ZNYR FRVMHER");

    qbGrfg("G49",
        "{Sver Pnyy} 591 F BPRNA/NYNEZ SVER/ FZBXR URNG QRGRPGBE MBAR 7",
        "PNYY:Sver Pnyy",
        "NQQE:591 F BPRNA",
        "VASB:NYNEZ SVER / FZBXR URNG QRGRPGBE MBAR 7");

    qbGrfg("G50",
        "{Sver Pnyy} 856 ARNPBKVR OYIQ 322/NYNEZ SVER/ FZBXR NYNEZ 322 MBAR 9",
        "PNYY:Sver Pnyy",
        "NQQE:856 ARNPBKVR OYIQ",
        "NCG:322",
        "VASB:NYNEZ SVER / FZBXR NYNEZ 322 MBAR 9");

    qbGrfg("G51",
        "{Sver Pnyy} 3518 UVTUJNL 101 A/RZRET ZRQVPNY ERFCBAFR/ srznyr snyy, xarr vawhel",
        "PNYY:Sver Pnyy",
        "NQQE:3518 UVTUJNL 101 A",
        "VASB:RZRET ZRQVPNY ERFCBAFR / srznyr snyy, xarr vawhel");

    qbGrfg("G52",
        "{Sver Pnyy} 523 Q Fg/RZRET ZRQVPNY ERFCBAFR/ sryy va onguebbz, oernguvat, HAerfcbafvir",
        "PNYY:Sver Pnyy",
        "NQQE:523 Q Fg",
        "VASB:RZRET ZRQVPNY ERFCBAFR / sryy va onguebbz, oernguvat, HAerfcbafvir");

    qbGrfg("G53",
        "{Sver Pnyy/ Uvc Cnva nsgre n snyy n srj qnlf ntb.} 90479 Pynex Eq/RZRET ZRQVPNY ERFCBAFR",
        "PNYY:Sver Pnyy/ Uvc Cnva nsgre n snyy n srj qnlf ntb.",
        "NQQE:90479 Pynex Eq",
        "VASB:RZRET ZRQVPNY ERFCBAFR");

    qbGrfg("G54",
        "{Sver Pnyy} 33445 FHAFRG ORNPU YA/FGEHP SVER 1FG",
        "PNYY:Sver Pnyy",
        "NQQE:33445 FHAFRG ORNPU YA",
        "VASB:FGEHP SVER 1FG");

    qbGrfg("G55",
        "{Sver Pnyy} 233 F BPRNA/NYNEZ SVER",
        "PNYY:Sver Pnyy",
        "NQQE:233 F BPRNA",
        "VASB:NYNEZ SVER");

    qbGrfg("G56",
        "{Sver Pnyy} 33684 JRFGFUBER YA/RZRET ZRQVPNY ERFCBAFR CBFF BIREQBFR",
        "PNYY:Sver Pnyy",
        "NQQE:33684 JRFGFUBER YA",
        "VASB:RZRET ZRQVPNY ERFCBAFR CBFF BIREQBFR");

    qbGrfg("G57",
        "{Sver Pnyy} 4253 UVTUJNL 101 A/RZRET ZRQVPNY ERFCBAFR PBAGENPGVBAF",
        "PNYY:Sver Pnyy",
        "NQQE:4253 UVTUJNL 101 A",
        "VASB:RZRET ZRQVPNY ERFCBAFR PBAGENPGVBAF");

    qbGrfg("G58",
        "{Sver Pnyy} 321 1FG FG/NYNEZ SVER/RYPGEVP EBBZ FZBXR",
        "PNYY:Sver Pnyy",
        "NQQE:321 1FG FG",
        "VASB:NYNEZ SVER / RYPGEVP EBBZ FZBXR");

    qbGrfg("G59",
        "{Sver Pnyy} 1308 CNEX YA/RZRET ZRQVPNY ERFCBAFR/ yvsg nffvfg j.zrqvk",
        "PNYY:Sver Pnyy",
        "NQQE:1308 CNEX YA",
        "VASB:RZRET ZRQVPNY ERFCBAFR / yvsg nffvfg j.zrqvk");

    qbGrfg("G60",
        "{Sver Pnyy} 33538 NQNVE YA/RZRET ZRQVPNY ERFCBAFR",
        "PNYY:Sver Pnyy",
        "NQQE:33538 NQNVE YA",
        "VASB:RZRET ZRQVPNY ERFCBAFR");

    qbGrfg("G61",
        "{Sver Pnyy} 4412 UVTUJNL 101 A/RZRET ZRQVPNY ERFCBAFR OERNGUVAT QVSSVPHYGVRF",
        "PNYY:Sver Pnyy",
        "NQQE:4412 UVTUJNL 101 A",
        "VASB:RZRET ZRQVPNY ERFCBAFR OERNGUVAT QVSSVPHYGVRF");

    qbGrfg("G62",
        "{Sver Pnyy} 1157 A ZNEVBA Nir 443/",
        "PNYY:Sver Pnyy",
        "NQQE:1157 A ZNEVBA Nir",
        "NCG:443");

    qbGrfg("G63",
        "{Sver Pnyy} 233 F BPRNA QE/NYNEZ SVER/ XVGPURA FZBXR QRGRPGBE",
        "PNYY:Sver Pnyy",
        "NQQE:233 F BPRNA QE",
        "VASB:NYNEZ SVER / XVGPURA FZBXR QRGRPGBE");

    qbGrfg("G64",
        "{Sver Pnyy} 599 CNPVSVP JNL/RZRET ZRQVPNY ERFCBAFR/RYQREYL SRZNYR SNYY BHGFVQR BA FVQRJNYX",
        "PNYY:Sver Pnyy",
        "NQQE:599 CNPVSVP JNL",
        "VASB:RZRET ZRQVPNY ERFCBAFR / RYQREYL SRZNYR SNYY BHGFVQR BA FVQRJNYX");

    qbGrfg("G65",
        "{Sver Pnyy} trneuneg sver fgngvba/ZBGBE IRU NPPVQRAG",
        "PNYY:Sver Pnyy",
        "NQQE:trneuneg sver fgngvba",
        "VASB:ZBGBE IRU NPPVQRAG");

    qbGrfg("G66",
        "{Sver Pnyy/ 729 A Znevba Haxabja zrqvpny ceboyrz} 729 A Znevba/RZRET ZRQVPNY ERFCBAFR",
        "PNYY:Sver Pnyy/ 729 A Znevba Haxabja zrqvpny ceboyrz",
        "NQQE:729 A Znevba",
        "VASB:RZRET ZRQVPNY ERFCBAFR");

    qbGrfg("G67",
        "{Sver Pnyy/ Crqvngevp sryy bss ovxr, oybbql abfr naq oebxra grrgu} Qnvel Dhrra / Cnpvsvp Jnl/RZRET ZRQVPNY ERFCBAFR",
        "PNYY:Qnvel Dhrra",
        "NQQE:Sver Pnyy & Crqvngevp sryy bss ovxr & Cnpvsvp Jnl",
        "ZNQQE:Sver Pnyy & Crqvngevp sryy & ovxr & Cnpvsvp Jnl",
        "CYNPR:oybbql abfr naq oebxra grrgu",
        "VASB:RZRET ZRQVPNY ERFCBAFR");

    qbGrfg("G68",
        "{Sver Pnyy} 89790 Znavba Qe/RZRET ZRQVPNY ERFCBAFR/ cbff fgebxr",
        "PNYY:Sver Pnyy",
        "NQQE:89790 Znavba Qe",
        "VASB:RZRET ZRQVPNY ERFCBAFR / cbff fgebxr");

    qbGrfg("G69",
        "{Sver Pnyy/ Fghqrag sryy bagb uvf onpx, sebz cynl fgehpgher} 1002 Cnpvsvp Jnl/RZRET ZRQVPNY ERFCBAFR",
        "PNYY:Sver Pnyy/ Fghqrag sryy bagb uvf onpx, sebz cynl fgehpgher",
        "NQQE:1002 Cnpvsvp Jnl",
        "VASB:RZRET ZRQVPNY ERFCBAFR");

    qbGrfg("G70",
        "{Sver Pnyy} 729 A ZNEVBA/RZRET ZRQVPNY ERFCBAFR/yvsg nffvfg",
        "PNYY:Sver Pnyy",
        "NQQE:729 A ZNEVBA",
        "VASB:RZRET ZRQVPNY ERFCBAFR / yvsg nffvfg");

    qbGrfg("G71",
        "{Sver Pnyy} 89449 UVTUJNL 101/RZRET ZRQVPNY ERFCBAFR OERNGUVAT QVSSVPHYGVRF",
        "PNYY:Sver Pnyy",
        "NQQE:89449 UVTUJNL 101",
        "VASB:RZRET ZRQVPNY ERFCBAFR OERNGUVAT QVSSVPHYGVRF");

    qbGrfg("G72",
        "{Sver Pnyy} 101 / T FG/RZRET ZRQVPNY ERFCBAFR/ 2 IRUVPYR ZIN",
        "PNYY:Sver Pnyy",
        "NQQE:101 & T FG",
        "VASB:RZRET ZRQVPNY ERFCBAFR / 2 IRUVPYR ZIN");

    qbGrfg("G73",
        "{Sver Pnyy} 1238 A ZNEVBA/NYNEZ SVER/ URNG QRGRPGBE YVIVAT EBBZ 1FG SYBBE",
        "PNYY:Sver Pnyy",
        "NQQE:1238 A ZNEVBA",
        "VASB:NYNEZ SVER / URNG QRGRPGBE YVIVAT EBBZ 1FG SYBBE");

    qbGrfg("G74",
        "{Sver Pnyy} 268 EVQTR QE/RZRET ZRQVPNY ERFCBAFR/ 78 HAPBA SRZNYR OERNGUVAT",
        "PNYY:Sver Pnyy",
        "NQQE:268 EVQTR QE",
        "VASB:RZRET ZRQVPNY ERFCBAFR / 78 HAPBA SRZNYR OERNGUVAT");

    qbGrfg("G75",
        "{Sver Pnyy} RZRET ZRQVPNY ERFCBAFR/HAPBA SRZNYR",
        "PNYY:Sver Pnyy",
        "NQQE:RZRET ZRQVPNY ERFCBAFR",
        "VASB:HAPBA SRZNYR");

    qbGrfg("G76",
        "{Sver Pnyy} 101  / ZC 15/RZRET ZRQVPNY ERFCBAFR",
        "PNYY:Sver Pnyy",
        "NQQE:101",
        "VASB:ZC 15 / RZRET ZRQVPNY ERFCBAFR");

    qbGrfg("G77",
        "{Sver Pnyy} 3621 UVTUJNL 101 A/RZRET ZRQVPNY ERFCBAFR ZIN",
        "PNYY:Sver Pnyy",
        "NQQE:3621 UVTUJNL 101 A",
        "VASB:RZRET ZRQVPNY ERFCBAFR ZIN");

    qbGrfg("G78",
        "{Sver Pnyy/ 2921} 441 2AQ NIR/FGEHP SVER 1FG/ VAA NG FRNFVQR",
        "PNYY:Sver Pnyy/ 2921",
        "NQQE:441 2AQ NIR",
        "VASB:FGEHP SVER 1FG / VAA NG FRNFVQR");

    qbGrfg("G79",
        "{Sver Pnyy} 1777 CVAR EVQTR QE 5/RZRET ZRQVPNY ERFCBAFR/ ryqreyl srznyr orra fvpx, pbaf naq oerngu",
        "PNYY:Sver Pnyy",
        "NQQE:1777 CVAR EVQTR QE",
        "NCG:5",
        "VASB:RZRET ZRQVPNY ERFCBAFR / ryqreyl srznyr orra fvpx, pbaf naq oerngu");

    qbGrfg("G80",
        "{Sver Pnyy SRRQVAT GHOR CEBOYRZF} 89449 UJL 101/RZRET ZRQVPNY ERFCBAFR",
        "PNYY:Sver Pnyy SRRQVAT GHOR CEBOYRZF",
        "NQQE:89449 UJL 101",
        "VASB:RZRET ZRQVPNY ERFCBAFR");

    qbGrfg("G81",
        "{Sver Pnyy/ Znyr guebjvat n svg, univat oernguvat qvssvphgyl cbyvpr ba fprar} 1989 Cvar Evqtr/RZRET ZRQVPNY ERFCBAFR",
        "PNYY:Sver Pnyy/ Znyr guebjvat n svg, univat oernguvat qvssvphgyl cbyvpr ba fprar",
        "NQQE:1989 Cvar Evqtr",
        "VASB:RZRET ZRQVPNY ERFCBAFR");

    qbGrfg("G82",
        "{Sver Pnyy} UJL 101 / ZC 18/NFFVFG ERAQRERQ/ GERR QBJA CNEG OYBPXVAT",
        "PNYY:Sver Pnyy",
        "NQQE:UJL 101",
        "VASB:ZC 18 / NFFVFG ERAQRERQ / GERR QBJA CNEG OYBPXVAT");

    qbGrfg("G83",
        "{Sver Pnyy/ 2923 ERFC} 90517 OVEQVR/FGEHP SVER 1FG/ BIRA BA SVER",
        "PNYY:Sver Pnyy/ 2923 ERFC",
        "NQQE:90517 OVEQVR",
        "VASB:FGEHP SVER 1FG / BIRA BA SVER");

    qbGrfg("G84",
        "{Sver Pnyy/FBHGU OBHAQ} UJL 101 / OBJYVAT NYYRL/RZRET ZRQVPNY ERFCBAFR/ ZBGBEPLPYVFG QBJA",
        "PNYY:Sver Pnyy/FBHGU OBHAQ",
        "NQQE:UJL 101 & OBJYVAT NYYRL",
        "VASB:RZRET ZRQVPNY ERFCBAFR / ZBGBEPLPYVFG QBJA");

    qbGrfg("G85",
        "{Sver Pnyy} 89525 UVTUJNL 101/RZRET ZRQVPNY ERFCBAFR/ SRZNYR 55 QVSS OERNGUVAT",
        "PNYY:Sver Pnyy",
        "NQQE:89525 UVTUJNL 101",
        "VASB:RZRET ZRQVPNY ERFCBAFR / SRZNYR 55 QVSS OERNGUVAT");

    qbGrfg("G86",
        "{Sver Pnyy} 33579 PNEYFBA QE/RZRET ZRQVPNY ERFCBAFR/ 89 SRZNYR FRZV PBA CNFFVAT BHG",
        "PNYY:Sver Pnyy",
        "NQQE:33579 PNEYFBA QE",
        "VASB:RZRET ZRQVPNY ERFCBAFR / 89 SRZNYR FRZV PBA CNFFVAT BHG");

    qbGrfg("G87",
        "{Sver Pnyy} 89780 QHAR EQ/RZRET ZRQVPNY ERFCBAFR/ 57 ZNYR FRVMHER",
        "PNYY:Sver Pnyy",
        "NQQE:89780 QHAR EQ",
        "VASB:RZRET ZRQVPNY ERFCBAFR / 57 ZNYR FRVMHER");

    qbGrfg("G88",
        "{Sver Pnyy} 1540 YRN JNL/FGEHP SVER 1FG",
        "PNYY:Sver Pnyy",
        "NQQE:1540 YRN JNL",
        "VASB:FGEHP SVER 1FG");

    qbGrfg("G89",
        "{Sver Pnyy} 33584 GBLNF YA/RZRET ZRQVPNY ERFCBAFR TEBHAQ YRIRY SNYY",
        "PNYY:Sver Pnyy",
        "NQQE:33584 GBLNF YA",
        "VASB:RZRET ZRQVPNY ERFCBAFR TEBHAQ YRIRY SNYY");

    qbGrfg("G90",
        "{Sver Pnyy/ Zrqvk erdhrfgf P1 gb havawherq snyy cngvrag, zrqvk qrynlrq} RZRET ZRQVPNY ERFCBAFR/",
        "PNYY:RZRET ZRQVPNY ERFCBAFR",
        "NQQE:Sver Pnyy & Zrqvk erdhrfgf P1 gb havawherq snyy cngvrag",
        "CYNPR:zrqvk qrynlrq");

    qbGrfg("G91",
        "{Sver Pnyy} 90495 CNE EQ/FGEHP SVER 1FG/  qvfnoyr crefba genccrq vafvqr",
        "PNYY:Sver Pnyy",
        "NQQE:90495 CNE EQ",
        "VASB:FGEHP SVER 1FG / qvfnoyr crefba genccrq vafvqr");

    qbGrfg("G92",
        "{Sver Pnyy/ Znyr xrrcf cnffvat bhg} 1367 Qbbyrl yA/RZRET ZRQVPNY ERFCBAFR",
        "PNYY:Sver Pnyy/ Znyr xrrcf cnffvat bhg",
        "NQQE:1367 Qbbyrl yA",
        "VASB:RZRET ZRQVPNY ERFCBAFR");

    qbGrfg("G93",
        "{Sver Pnyy / 96 LE BY SRZNYR SNYY CNG} 89829 FHES CVARF YNAQVAT QE/RZRET ZRQVPNY ERFCBAFR",
        "PNYY:Sver Pnyy / 96 LE BY SRZNYR SNYY CNG",
        "NQQE:89829 FHES CVARF YNAQVAT QE",
        "VASB:RZRET ZRQVPNY ERFCBAFR");

    qbGrfg("G94",
        "{Sver Pnyy} 14.3 UJL 101/CHOYVP NFFVFG/ JRVTU FGNGVBA PNYYRE ERCBEGRQ FCNEXF SEBZ CBJRE CBYR",
        "PNYY:Sver Pnyy",
        "NQQE:14.3 UJL 101",
        "VASB:CHOYVP NFFVFG / JRVTU FGNGVBA PNYYRE ERCBEGRQ FCNEXF SEBZ CBJRE CBYR");

    qbGrfg("G95",
        "{Sver Pnyy} 126 11GU NIR/SVER VAIRFGVTNGVBA",
        "PNYY:Sver Pnyy",
        "NQQE:126 11GU NIR",
        "VASB:SVER VAIRFGVTNGVBA");

    qbGrfg("G96",
        "{Sver Pnyy} 89449 UJL 101/RZRET ZRQVPNY ERFCBAFR/ NQHYG FRVMHER CNGVRAG",
        "PNYY:Sver Pnyy",
        "NQQE:89449 UJL 101",
        "VASB:RZRET ZRQVPNY ERFCBAFR / NQHYG FRVMHER CNGVRAG");

    qbGrfg("G97",
        "{Sver Pnyy} 6 10 FG/RZRET ZRQVPNY ERFCBAFR/ 88 LE BYQ PBQR 99",
        "PNYY:Sver Pnyy",
        "NQQE:6 10 FG",
        "VASB:RZRET ZRQVPNY ERFCBAFR / 88 LE BYQ PBQR 99");

    qbGrfg("G98",
        "{Sver Pnyy} 402 OEBJAVAT/FGEHP SVER 1FG/ FZRYY FZBXR, ABAR IVFVOYR",
        "PNYY:Sver Pnyy",
        "NQQE:402 OEBJAVAT",
        "VASB:FGEHP SVER 1FG / FZRYY FZBXR, ABAR IVFVOYR");

    qbGrfg("G99",
        "{Sver Pnyy} 33538 NQNVE YA/RZRET ZRQVPNY ERFCBAFR/ FYAG NCEBNPU ZNYR 64  QVSS OEGU QVSS",
        "PNYY:Sver Pnyy",
        "NQQE:33538 NQNVE YA",
        "VASB:RZRET ZRQVPNY ERFCBAFR / FYAG NCEBNPU ZNYR 64  QVSS OEGU QVSS");

    qbGrfg("G100",
        "{Sver Pnyy} 33538 NQNVE YA/RZRET ZRQVPNY ERFCBAFR/ FVYRAG NCCEBNPU 64 ZNYR LBH  JRER GURER BA FHAQNL GENAF",
        "PNYY:Sver Pnyy",
        "NQQE:33538 NQNVE YA",
        "VASB:RZRET ZRQVPNY ERFCBAFR / FVYRAG NCCEBNPU 64 ZNYR LBH  JRER GURER BA FHAQNL GENAF");

  }

  @Grfg
  choyvp ibvq grfgByarlJnyyhfxvSverErfphr() {

    qbGrfg("G1",
        "{Sver Pnyy} 89901 YBTNA Eq/FGEHP SVER 1FG",
        "PNYY:Sver Pnyy",
        "NQQE:89901 YBTNA Eq",
        "VASB:FGEHP SVER 1FG");

    qbGrfg("G2",
        "{Sver Pnyy} 35881 QBJ/FGEHP SVER 1FG",
        "PNYY:Sver Pnyy",
        "NQQE:35881 QBJ",
        "VASB:FGEHP SVER 1FG");

    qbGrfg("G3",
        "{Sver Pnyy} SBE 3521-ABEGU PBNFG ZRQVPNY PYVAVP-441 30GU FG/FZBXR NAQ OHEAVAT FZRYY SEBZ HCFGNVEF",
        "PNYY:Sver Pnyy",
        "NQQE:SBE 3521-ABEGU PBNFG ZRQVPNY PYVAVP-441 30GU FG",
        "VASB:FZBXR NAQ OHEAVAT FZRYY SEBZ HCFGNVEF");

    qbGrfg("G4",
        "{Sver Pnyy} 90461 UVTUJNL 202/RZRET ZRQVPNY ERFCBAFR",
        "PNYY:Sver Pnyy",
        "NQQE:90461 UVTUJNL 202",
        "VASB:RZRET ZRQVPNY ERFCBAFR");

    qbGrfg("G5",
        "{Sver Pnyy} 88289 LBHATF EVIRE EQ/5 LB ZNYR J QVSS OERNGUVAT-CBFF NFGUZN NGGNPX",
        "PNYY:Sver Pnyy",
        "NQQE:88289 LBHATF EVIRE EQ",
        "VASB:5 LB ZNYR J QVSS OERNGUVAT-CBFF NFGUZN NGGNPX");

    qbGrfg("G6",
        "{Sver Pnyy} 7 UJL 202/FVATYR IRU ZIN, GEHPX BSS EBNQ BA GUR EVIRE FVQR BS UJL 202. HAX VAWHEVRF",
        "PNYY:Sver Pnyy",
        "NQQE:7 UJL 202",
        "VASB:FVATYR IRU ZIN, GEHPX BSS EBNQ BA GUR EVIRE FVQR BS UJL 202. HAX VAWHEVRF");

    qbGrfg("G7",
        "{Sver Pnyy} 36476 PNQBANH YA/ZNYR FHOW CBFF URNEG NGGNPX",
        "PNYY:Sver Pnyy",
        "NQQE:36476 PNQBANH YA",
        "VASB:ZNYR FHOW CBFF URNEG NGGNPX");

    qbGrfg("G8",
        "{Sver Pnyy} 10 UNYFRL EQ/FGEHP SVER 1FG/OBGGBZ HAVG, OYX FZBXR FRRA",
        "PNYY:Sver Pnyy",
        "NQQE:10 UNYFRL EQ",
        "VASB:FGEHP SVER 1FG / OBGGBZ HAVG, OYX FZBXR FRRA");

    qbGrfg("G9",
        "{Sver Pnyy} 87334 LBHATF EVIRE EQ/PUVZARL SVER",
        "PNYY:Sver Pnyy",
        "NQQE:87334 LBHATF EVIRE EQ",
        "VASB:PUVZARL SVER");

    qbGrfg("G10",
        "{Sver Pnyy} 90461 UVTUJNL 202/RZRET ZRQVPNY ERFCBAFR/QVSS OERNGUVAT",
        "PNYY:Sver Pnyy",
        "NQQE:90461 UVTUJNL 202",
        "VASB:RZRET ZRQVPNY ERFCBAFR / QVSS OERNGUVAT");

    qbGrfg("G11",
        "{Sver Pnyy} 1576 VEIVAT NIR/FGEHP SVER 1FG",
        "PNYY:Sver Pnyy",
        "NQQE:1576 VEIVAT NIR",
        "VASB:FGEHP SVER 1FG");

    qbGrfg("G12",
        "{Sver Pnyy} 1050 34GU FG/PUVZARL SVER/ZBIR HC GB PVGL YVZVGF",
        "PNYY:Sver Pnyy",
        "NQQE:1050 34GU FG",
        "VASB:PUVZARL SVER / ZBIR HC GB PVGL YVZVGF");

    qbGrfg("G13",
        "{Sver Pnyy} 92295 LBHATF EVIRE EQ/NYNEZ SVER NHGUBEVMRQ PNAPRY",
        "PNYY:Sver Pnyy",
        "NQQE:92295 LBHATF EVIRE EQ",
        "VASB:NYNEZ SVER NHGUBEVMRQ PNAPRY");

    qbGrfg("G14",
        "{Sver Pnyy} 92295 LBHATF EVIRE EQ/NYNEZ SVER ZNFGRE ORQEBBZ FZBXR QRG.",
        "PNYY:Sver Pnyy",
        "NQQE:92295 LBHATF EVIRE EQ",
        "VASB:NYNEZ SVER ZNFGRE ORQEBBZ FZBXR QRG.");

    qbGrfg("G15",
        "{SRZNYR SNYY CNGVRAG/QVMML/OERNGUVAT NAQ PBAFPVBHF} 36549 PUEVFGVNAF YA/RZRET ZRQVPNY ERFCBAFR",
        "PNYY:SRZNYR SNYY CNGVRAG/QVMML/OERNGUVAT NAQ PBAFPVBHF",
        "NQQE:36549 PUEVFGVNAF YA",
        "VASB:RZRET ZRQVPNY ERFCBAFR");

    qbGrfg("G16",
        "{Sver Pnyy} 91617 UVTUJNL 202/RZF FUBEGARFF BS OERNGU",
        "PNYY:Sver Pnyy",
        "NQQE:91617 UVTUJNL 202",
        "VASB:RZF FUBEGARFF BS OERNGU");

    qbGrfg("G17",
        "{Sver Pnyy} 1263 PBZZREPVNY FG 402/FGEHP SVER 1FG",
        "PNYY:Sver Pnyy",
        "NQQE:1263 PBZZREPVNY FG",
        "NCG:402",
        "VASB:FGEHP SVER 1FG");

    qbGrfg("G18",
        "{Sver Pnyy} 200 J XYNFXNAVAR NIR/FGEHP SVER 1FG",
        "PNYY:Sver Pnyy",
        "NQQE:200 J XYNFXNAVAR NIR",
        "VASB:FGEHP SVER 1FG");

    qbGrfg("G19",
        "{Sver Pnyy} 1997 ZNEVAR Qe/FZBXR PBZVAT SEBZ OHVYQVAT BQQ BQBE",
        "PNYY:Sver Pnyy",
        "NQQE:1997 ZNEVAR Qe",
        "VASB:FZBXR PBZVAT SEBZ OHVYQVAT BQQ BQBE");

    qbGrfg("G20",
        "{Sver Pnyy} 91817 UVTUJNL 202 HAVG 30/64 LB SZ, YRGUNETVP NAQ UNYYHPVANGVAT",
        "PNYY:Sver Pnyy",
        "NQQE:91817 UVTUJNL 202",
        "NCG:30",
        "VASB:64 LB SZ, YRGUNETVP NAQ UNYYHPVANGVAT");

    qbGrfg("G21",
        "{ZNRY FHO/YNPRENGVBA BA NEZ} 91817 UVTUJNL 202 NCG 30/RZRET ZRQVPNY ERFCBAFR",
        "PNYY:ZNRY FHO/YNPRENGVBA BA NEZ",
        "NQQE:91817 UVTUJNL 202",
        "NCG:30",
        "VASB:RZRET ZRQVPNY ERFCBAFR");

    qbGrfg("G22",
        "{Sver Pnyy} UJL 202/ARNE YVARUNAF (ZC 3.8 VFU) FVATYR IRU EBYYBIRE-HAXA VAWHEVRF",
        "PNYY:Sver Pnyy",
        "NQQE:UJL 202",
        "VASB:ARNE YVARUNAF (ZC 3.8 VFU) FVATYR IRU EBYYBIRE-HAXA VAWHEVRF");

    qbGrfg("G23",
        "{Sver Pnyy} 91817 UVTUJNL 202 NCG 30/RZRET ZRQVPNY ERFCBAFR/CBFG FGRAG CYNPRZRAG FJRYYVAT",
        "PNYY:Sver Pnyy",
        "NQQE:91817 UVTUJNL 202",
        "NCG:30",
        "VASB:RZRET ZRQVPNY ERFCBAFR / CBFG FGRAG CYNPRZRAG FJRYYVAT");

    qbGrfg("G24",
        "{HAXA CEBOYRZ/ZRQPVNY NYNEZ GEVC} 90225 UVTUJNL 202/RZRET ZRQVPNY ERFCBAFR",
        "PNYY:HAXA CEBOYRZ/ZRQPVNY NYNEZ GEVC",
        "NQQE:90225 UVTUJNL 202",
        "VASB:RZRET ZRQVPNY ERFCBAFR");

    qbGrfg("G25",
        "{Sver Pnyy} 36506 PNQBANH YA/RYQREYL ZNYR, FRIRER ORQFBERF, CE HANOYR GB ZBIR UVZ",
        "PNYY:Sver Pnyy",
        "NQQE:36506 PNQBANH YA",
        "VASB:RYQREYL ZNYR, FRIRER ORQFBERF, CE HANOYR GB ZBIR UVZ");

    qbGrfg("G26",
        "{Sver Pnyy} 1 3EQ FG/FGEHP SVER 1FG",
        "PNYY:Sver Pnyy",
        "NQQE:1 3EQ FG",
        "VASB:FGEHP SVER 1FG");

    qbGrfg("G28",
        "{Sver Pnyy} 91320 JNYYHFXV YBBC/ZBGBE IRU NPPVQRAG/FZNYY FVYIRE PNE",
        "PNYY:Sver Pnyy",
        "NQQE:91320 JNYYHFXV YBBC",
        "VASB:ZBGBE IRU NPPVQRAG / FZNYY FVYIRE PNE");

    qbGrfg("G29",
        "{SRZ SRYY NAQ UNF URNQ VAWHEL/OERNGUVAT NAQ PBAFPVBHF} 91817 UVTUJNL 202 NCG 30/RZRET ZRQVPNY ERFCBAFR",
        "PNYY:SRZ SRYY NAQ UNF URNQ VAWHEL/OERNGUVAT NAQ PBAFPVBHF",
        "NQQE:91817 UVTUJNL 202",
        "NCG:30",
        "VASB:RZRET ZRQVPNY ERFCBAFR");

    qbGrfg("G30",
        "{ZNYR UNIVAT OERNGUVAT QVSSVPHYGL} 89934 ENLZBAQ EQ/RZRET ZRQVPNY ERFCBAFR",
        "PNYY:ZNYR UNIVAT OERNGUVAT QVSSVPHYGL",
        "NQQE:89934 ENLZBAQ EQ",
        "VASB:RZRET ZRQVPNY ERFCBAFR");

    qbGrfg("G31",
        "{Sver Pnyy} 36506 PNQBANH YA/CHO NFFVFG-ZNYR ARRQF GB TRG SEBZ JURRYPUNVE GB ORQ-AB ZRQVPNY VFFHRF-ZRQVK HANINV",
        "PNYY:Sver Pnyy",
        "NQQE:36506 PNQBANH YA",
        "VASB:CHO NFFVFG-ZNYR ARRQF GB TRG SEBZ JURRYPUNVE GB ORQ-AB ZRQVPNY VFFHRF-ZRQVK HANINV");

    qbGrfg("G32",
        "{Sver Pnyy} 90292 YVYYRANF Eq/NYNEZ SVER",
        "PNYY:Sver Pnyy",
        "NQQE:90292 YVYYRANF Eq",
        "VASB:NYNEZ SVER");

    qbGrfg("G33",
        "{Sver Pnyy} 35501 YVGGYR JNYYHFXV YA/SZ J PURFG CNVAF",
        "PNYY:Sver Pnyy",
        "NQQE:35501 YVGGYR JNYYHFXV YA",
        "VASB:SZ J PURFG CNVAF");

    qbGrfg("G34",
        "{Sver Pnyy} 1740 QNJFBA PG/FGEHP SVER 1FG",
        "PNYY:Sver Pnyy",
        "NQQE:1740 QNJFBA PG",
        "VASB:FGEHP SVER 1FG");

    qbGrfg("G35",
        "{Sver Pnyy} 92975 UVTUJNL 202/RZRET ZRQVPNY ERFCBAFR",
        "PNYY:Sver Pnyy",
        "NQQE:92975 UVTUJNL 202",
        "VASB:RZRET ZRQVPNY ERFCBAFR");

    qbGrfg("G36",
        "{Sver Pnyy} VA GUR NERN BS 87145 LBHATF EVIRE EQ/FVATYR IRU VA GUR QVGPU-ECGQ NF AB VAWHEVRF",
        "PNYY:Sver Pnyy",
        "NQQE:VA GUR NERN BS 87145 LBHATF EVIRE EQ",
        "VASB:FVATYR IRU VA GUR QVGPU-ECGQ NF AB VAWHEVRF");

    qbGrfg("G37",
        "{Sver Pnyy} 80 ARUNYRZ NIR/PUVZARL SVER-3521 ERFCBAQ GB PVGL YVZVGF",
        "PNYY:Sver Pnyy",
        "NQQE:80 ARUNYRZ NIR",
        "VASB:PUVZARL SVER-3521 ERFCBAQ GB PVGL YVZVGF");

    qbGrfg("G38",
        "{Sver Pnyy} 91617 UVTUJNL 202/53 LB SZ JVGU N ABFR OYRRQ-FGVYY OYRRQVAT",
        "PNYY:Sver Pnyy",
        "NQQE:91617 UVTUJNL 202",
        "VASB:53 LB SZ JVGU N ABFR OYRRQ-FGVYY OYRRQVAT");

    qbGrfg("G39",
        "{Sver Pnyy} 91817 UVTUJNL 202 NCG 37/SRZNYR SVATRE VAWHEL, SVATRE GHEAVAT OYNPX.",
        "PNYY:Sver Pnyy",
        "NQQE:91817 UVTUJNL 202",
        "NCG:37",
        "VASB:SRZNYR SVATRE VAWHEL, SVATRE GHEAVAT OYNPX.");

    qbGrfg("G40",
        "{Sver Pnyy} 35304 YLATFGNQ URVTUGF YA/FGEHP SVER 1FG/PUVZARL SVER",
        "PNYY:Sver Pnyy",
        "NQQE:35304 YLATFGNQ URVTUGF YA",
        "VASB:FGEHP SVER 1FG / PUVZARL SVER");

    qbGrfg("G41",
        "{Sver Pnyy} 1423 3EQ FG/FGEHP SVER 1FG/URNIL FZBXR FVQR BS UBHFR",
        "PNYY:Sver Pnyy",
        "NQQE:1423 3EQ FG",
        "VASB:FGEHP SVER 1FG / URNIL FZBXR FVQR BS UBHFR");

    qbGrfg("G42",
        "{Sver Pnyy} 91617 UVTUJNL 202/52 LB SZ J ABFR OYRRQ, BA OYBBQ GUVAAREF",
        "PNYY:Sver Pnyy",
        "NQQE:91617 UVTUJNL 202",
        "VASB:52 LB SZ J ABFR OYRRQ, BA OYBBQ GUVAAREF");

    qbGrfg("G43",
        "{Sver Pnyy} 38384 YNOVFXR YA/ZNYR FHOW ORYVRIRF UR VF UNIVAT URNEG NGGNPX-GVTUGARFF VA PURFG",
        "PNYY:Sver Pnyy",
        "NQQE:38384 YNOVFXR YA",
        "VASB:ZNYR FHOW ORYVRIRF UR VF UNIVAT URNEG NGGNPX-GVTUGARFF VA PURFG");

    qbGrfg("G44",
        "{Sver Pnyy} JRYYF SNETB ONAX/FGEHP SVER 1FG",
        "PNYY:Sver Pnyy",
        "NQQE:JRYYF SNETB ONAX",
        "VASB:FGEHP SVER 1FG");

    qbGrfg("G45",
        "{Sver Pnyy} 91617 UVTUJNL 202/RZRET ZRQVPNY ERFCBAFR",
        "PNYY:Sver Pnyy",
        "NQQE:91617 UVTUJNL 202",
        "VASB:RZRET ZRQVPNY ERFCBAFR");

    qbGrfg("G46",
        "{Sver Pnyy} 90461 UVTUJNL 202/ZNYR FHOW QVSS OERNGUVAT",
        "PNYY:Sver Pnyy",
        "NQQE:90461 UVTUJNL 202",
        "VASB:ZNYR FHOW QVSS OERNGUVAT");

    qbGrfg("G47",
        "{Sver Pnyy} SBE 3521--832 UNEEVFBA NIR/CBFF FGEHPGHER BE PUVZARL SVER NG NQQERFF-ARVTUOBE FGNGRF OYNPX FZBXR UBH",
        "PNYY:Sver Pnyy",
        "NQQE:SBE 3521--832 UNEEVFBA NIR",
        "VASB:CBFF FGEHPGHER BE PUVZARL SVER NG NQQERFF-ARVTUOBE FGNGRF OYNPX FZBXR UBH");

    qbGrfg("G48",
        "{Sver Pnyy} 3521----/34495 UVTUJNL 101 OHFVARFF/FGEHP SVER VA TNENTR-BPPHCNAGF BHG",
        "PNYY:Sver Pnyy",
        "NQQE:3521---- & 34495 UVTUJNL 101 OHFVARFF",
        "ZNQQE:34495 UVTUJNL 101 OHFVARFF",
        "VASB:FGEHP SVER VA TNENTR-BPPHCNAGF BHG");

    qbGrfg("G49",
        "{Sver Pnyy} 91817 UVTUJNL 202 NCG 30/64 LBN SRZNYR, PNAPRE CG, QVSS OERNGUVAT",
        "PNYY:Sver Pnyy",
        "NQQE:91817 UVTUJNL 202",
        "NCG:30",
        "VASB:64 LBN SRZNYR, PNAPRE CG, QVSS OERNGUVAT");

    qbGrfg("G50",
        "{Sver Pnyy} 91131 UVTUJNL 202/ZNYR FHOW IBZVGGVAT-ERDHRFG FVYRAG NCCEBNPU",
        "PNYY:Sver Pnyy",
        "NQQE:91131 UVTUJNL 202",
        "VASB:ZNYR FHOW IBZVGGVAT-ERDHRFG FVYRAG NCCEBNPU");

    qbGrfg("G51",
        "{Sver Pnyy} 126 11GU NIR/FGEHP SVER 3EQ 3521 TB GB FGNGVBA 26",
        "PNYY:Sver Pnyy",
        "NQQE:126 11GU NIR",
        "VASB:FGEHP SVER 3EQ 3521 TB GB FGNGVBA 26");

    qbGrfg("G52",
        "{SRZNYR CBFFVOYR FGEBX} 90621 UVTUJNL 202/RZRET ZRQVPNY ERFCBAFR",
        "PNYY:SRZNYR CBFFVOYR FGEBX",
        "NQQE:90621 UVTUJNL 202",
        "VASB:RZRET ZRQVPNY ERFCBAFR");

    qbGrfg("G53",
        "{Sver Pnyy} 1432 SENAXYVA NIR NCG 8/FGEHP SVER 1FG/FGEBAT BQBE FZBXR, CBFF RYRPGEVPNY SVER",
        "PNYY:Sver Pnyy",
        "NQQE:1432 SENAXYVA NIR",
        "NCG:8",
        "VASB:FGEHP SVER 1FG / FGEBAT BQBE FZBXR, CBFF RYRPGEVPNY SVER");

    qbGrfg("G54",
        "{Sver Pnyy} ABJYNAF QE/3571-YNETR OEHFU SVER ARNE N UBZR, CE PBHYQ FRR SEBZ URE UBHFR BA FGBARE EQ",
        "PNYY:Sver Pnyy",
        "NQQE:ABJYNAF QE",
        "VASB:3571-YNETR OEHFU SVER ARNE N UBZR, CE PBHYQ FRR SEBZ URE UBHFR BA FGBARE EQ");

    qbGrfg("G55",
        "{Sver Pnyy} UVTUJNL 202/PUEVFGVNAF YNAR/2AQ GBAR BHG- INA VAGB N QVGPU",
        "PNYY:Sver Pnyy",
        "NQQE:UVTUJNL 202 & PUEVFGVNAF YNAR",
        "VASB:2AQ GBAR BHG- INA VAGB N QVGPU");

    qbGrfg("G56",
        "{Sver Pnyy} UVTUJNL 202/PUEVFGVNAF YNAR/ZIN-INA VAGB N QVGPU",
        "PNYY:Sver Pnyy",
        "NQQE:UVTUJNL 202 & PUEVFGVNAF YNAR",
        "VASB:ZIN-INA VAGB N QVGPU");

    qbGrfg("G57",
        "{Sver Pnyy} 90621 UVTUJNL 202/RZRET ZRQVPNY ERFCBAFR CEBO OEBXRA UVC",
        "PNYY:Sver Pnyy",
        "NQQE:90621 UVTUJNL 202",
        "VASB:RZRET ZRQVPNY ERFCBAFR CEBO OEBXRA UVC");

    qbGrfg("G58",
        "{Sver Pnyy} 90653 UVTUJNL 202/RZRET ZRQVPNY ERFCBAFR",
        "PNYY:Sver Pnyy",
        "NQQE:90653 UVTUJNL 202",
        "VASB:RZRET ZRQVPNY ERFCBAFR");

    qbGrfg("G59",
        "{Sver Pnyy} 9 UJL 202, FVATYR IRU ZIN ZVABE VAWHEVRF",
        "PNYY:Sver Pnyy",
        "NQQE:9 UJL 202",
        "CYNPR:FVATYR IRU ZIN ZVABE VAWHEVRF");

    qbGrfg("G60",
        "{Sver Pnyy} 91817 UVTUJNL 202 16/RZRET ZRQVPNY ERFCBAFR SRZ NFFNHYG IVP, YR BA FPRAR, P4 NAQ PYRNE",
        "PNYY:Sver Pnyy",
        "NQQE:91817 UVTUJNL 202",
        "NCG:16",
        "VASB:RZRET ZRQVPNY ERFCBAFR SRZ NFFNHYG IVP, YR BA FPRAR, P4 NAQ PYRNE");

    qbGrfg("G61",
        "{Sver Pnyy} 91978 UNTRA QE/RZRET ZRQVPNY ERFCBAFR ZNYR CG, OYBBQ VA HEVAR",
        "PNYY:Sver Pnyy",
        "NQQE:91978 UNTRA QE",
        "VASB:RZRET ZRQVPNY ERFCBAFR ZNYR CG, OYBBQ VA HEVAR");

    qbGrfg("G62",
        "{Sver Pnyy} 3900 NOORL YA 210/FGEHP SVER 1FG OHVYQVAT N, FZBXR VA JNYY ORUVAQ SVERCYNPR",
        "PNYY:Sver Pnyy",
        "NQQE:3900 NOORL YA",
        "NCG:210",
        "VASB:FGEHP SVER 1FG OHVYQVAT N, FZBXR VA JNYY ORUVAQ SVERCYNPR");

    qbGrfg("G63",
        "{DGE ZVYR BSS UJL 202 BA GUR EVTUG} UJL 202/TERRA ZBHAGNVA EQ/ZBGBE IRU NPPVQRAG",
        "PNYY:DGE ZVYR BSS UJL 202 BA GUR EVTUG",
        "NQQE:UJL 202 & TERRA ZBHAGNVA EQ",
        "VASB:ZBGBE IRU NPPVQRAG");

    qbGrfg("G64",
        "{Sver Pnyy} 1/2 ZVYR HC JNYYHFXV YBBC SEBZ YVGGYR JNYYHFXV/GERR NG 45 QRT NATYR NPEBFF EBNQ",
        "PNYY:Sver Pnyy",
        "NQQE:ZVYR HC JNYYHFXV YBBC",
        "CYNPR:SEBZ YVGGYR JNYYHFXV",
        "VASB:GERR NG 45 QRT NATYR NPEBFF EBNQ");

    qbGrfg("G65",
        "{Sver Pnyy} UJL 202-200 LNEQF JRFG BS BYARL FGBER-GERR NAQ CBJRE CBYR/YVARF QBJA-PBZCYRGRYL OYBPXVAT",
        "PNYY:Sver Pnyy",
        "NQQE:UJL 202-200",
        "CYNPR:LNEQF JRFG BS BYARL FGBER-GERR NAQ CBJRE CBYR",
        "VASB:YVARF QBJA-PBZCYRGRYL OYBPXVAT");

    qbGrfg("G66",
        "{Sver Pnyy} 86859 UVTUJNL 202/JNGRE NAQ ZHQ CBHEVAT BIRE URE ERGNVAVAT JNYY. 3.5 SG SEBZG URNG CHZC EVTUG ABJ",
        "PNYY:Sver Pnyy",
        "NQQE:86859 UVTUJNL 202",
        "VASB:JNGRE NAQ ZHQ CBHEVAT BIRE URE ERGNVAVAT JNYY. 3.5 SG SEBZG URNG CHZC EVTUG ABJ");

    qbGrfg("G67",
        "{Sver Pnyy} 90621 UVTUJNL 202/RYQREYL ZNYR FUBEGARFF BS OERNGU, TRARENY JRNXARFF",
        "PNYY:Sver Pnyy",
        "NQQE:90621 UVTUJNL 202",
        "VASB:RYQREYL ZNYR FUBEGARFF BS OERNGU, TRARENY JRNXARFF");

    qbGrfg("G68",
        "{Sver Pnyy} LBHATF EVIRE EQ/FNQQYR ZBHAGNVA(FZBYQREVAT CVYR BS OENAPURF/FGHZCF)",
        "PNYY:Sver Pnyy",
        "NQQE:LBHATF EVIRE EQ",
        "VASB:FNQQYR ZBHAGNVA(FZBYQREVAT CVYR BS OENAPURF / FGHZCF)");

    qbGrfg("G69",
        "{27 LBN ZNYR FRVMVAT/OERNGUVAT NAQ PBAFPVBHF} 90592 UVTUJNL 202/RZRET ZRQVPNY ERFCBAFR",
        "PNYY:27 LBN ZNYR FRVMVAT/OERNGUVAT NAQ PBAFPVBHF",
        "NQQE:90592 UVTUJNL 202",
        "VASB:RZRET ZRQVPNY ERFCBAFR");

    qbGrfg("G70",
        "{Sver Pnyy} ZVYR CBFG 4.4 UJL 202/IRU VAGB N QVGPU ARNE GUR ERQ ONEA, HAX VAWHEVRF",
        "PNYY:Sver Pnyy",
        "NQQE:ZVYR CBFG 4.4 UJL",
        "ZNQQE:ZVYR CBFG 4.UJL 4",
        "NCG:202",
        "VASB:IRU VAGB N QVGPU ARNE GUR ERQ ONEA, HAX VAWHEVRF");

    qbGrfg("G71",
        "{Sver Pnyy} 38246 YNEFRA YA/UBHFR BA SVER, NYY BPPHCNAGF BHG BS GUR UBHFR",
        "PNYY:Sver Pnyy",
        "NQQE:38246 YNEFRA YA",
        "VASB:UBHFR BA SVER, NYY BPPHCNAGF BHG BS GUR UBHFR");

    qbGrfg("G72",
        "{Sver Pnyy} 92402 R EQ/CHOYVP NFFVFG CREFBAARY ERD SBE IRU ERZBINY",
        "PNYY:Sver Pnyy",
        "NQQE:92402 R EQ",
        "VASB:CHOYVP NFFVFG CREFBAARY ERD SBE IRU ERZBINY");

    qbGrfg("G73",
        "{IRU PENFU} 92402 R EQ/ZBGBE IRU NPPVQRAG",
        "PNYY:IRU PENFU",
        "NQQE:92402 R EQ",
        "VASB:ZBGBE IRU NPPVQRAG");

    qbGrfg("G74",
        "{Sver Pnyy} 1341 3EQ FG/FGEHP SVER 1FG",
        "PNYY:Sver Pnyy",
        "NQQE:1341 3EQ FG",
        "VASB:FGEHP SVER 1FG");

    qbGrfg("G75",
        "{PUVZARL SVER/ERFCBAQ GB PVGL YVZVGF} 642 30GU FG/PUVZARL SVER",
        "PNYY:PUVZARL SVER/ERFCBAQ GB PVGL YVZVGF",
        "NQQE:642 30GU FG",
        "VASB:PUVZARL SVER");

    qbGrfg("G76",
        "{Sver Pnyy} 91994 FUNA EQ/**FGNTR** QRCHGVRF RAEBHGR GB ERCG BS FHVPVQNY SRZNYR",
        "PNYY:Sver Pnyy",
        "NQQE:91994 FUNA EQ",
        "VASB:**FGNTR** QRCHGVRF RAEBHGR GB ERCG BS FHVPVQNY SRZNYR");

    qbGrfg("G77",
        "{Sver Pnyy} 1545 SENAXYVA NIR/FGEHP SVER 1FG/PBZZREPVNY SVER NYNEZ, PUEHPU FZBXR",
        "PNYY:Sver Pnyy",
        "NQQE:1545 SENAXYVA NIR",
        "VASB:FGEHP SVER 1FG / PBZZREPVNY SVER NYNEZ, PUEHPU FZBXR");

    qbGrfg("G78",
        "{Sver Pnyy} 3738 YVRS REVXFBA Qe FCNPR 25/SEVQTR BA SVER VA EI",
        "PNYY:Sver Pnyy",
        "NQQE:3738 YVRS REVXFBA Qe",
        "CYNPR:FCNPR 25",
        "VASB:SEVQTR BA SVER VA EI");

    qbGrfg("G79",
        "{Sver Pnyy} 1311 XRAFVATGBA NIR/PNAPRY ERFCBAFR CRE PBZZNAQ",
        "PNYY:Sver Pnyy",
        "NQQE:1311 XRAFVATGBA NIR",
        "VASB:PNAPRY ERFCBAFR CRE PBZZNAQ");

    qbGrfg("G80",
        "{Sver Pnyy} 1311 XRAFVATGBA NIR/SVER VA GUR BIRA-PHEERAGYL PBAGNVARQ VA BIRA",
        "PNYY:Sver Pnyy",
        "NQQE:1311 XRAFVATGBA NIR",
        "VASB:SVER VA GUR BIRA-PHEERAGYL PBAGNVARQ VA BIRA");

    qbGrfg("G81",
        "{SRZNYR JVGU ONPX NAQ UVC CNVA/QVMML/FVYROG NCCEBNPU} 87447 UVTUJNL 202/RZRET ZRQVPNY ERFCBAFR",
        "PNYY:SRZNYR JVGU ONPX NAQ UVC CNVA/QVMML/FVYROG NCCEBNPU",
        "NQQE:87447 UVTUJNL 202",
        "VASB:RZRET ZRQVPNY ERFCBAFR");

    qbGrfg("G82",
        "{Sver Pnyy} 89125 JRYPU EQ/RZRET ZRQVPNY ERFCBAFR",
        "PNYY:Sver Pnyy",
        "NQQE:89125 JRYPU EQ",
        "VASB:RZRET ZRQVPNY ERFCBAFR");

    qbGrfg("G83",
        "{Sver Pnyy} 35375 ZHQQ YA(QVERPGYL NPEBFF SEBZ GUVF NQQERFF)CBFFVOYR BHG BS PBAGEBY OBASVER",
        "PNYY:Sver Pnyy",
        "NQQE:35375 ZHQQ",
        "CYNPR:YA(QVERPGYL NPEBFF SEBZ GUVF NQQERFF)CBFFVOYR BHG BS PBAGEBY OBASVER");

    qbGrfg("G84",
        "{Sver Pnyy} 36370 QLOYVR YA/TENFF/OEHFU SVER",
        "PNYY:Sver Pnyy",
        "NQQE:36370 QLOYVR YA",
        "VASB:TENFF / OEHFU SVER");

    qbGrfg("G85",
        "{Sver Pnyy} 11.5 UJL 202/ZBGBE IRU NPPVQRAG FVATYR IRU ZIN",
        "PNYY:Sver Pnyy",
        "NQQE:11.5 UJL 202",
        "VASB:ZBGBE IRU NPPVQRAG FVATYR IRU ZIN");

    qbGrfg("G86",
        "{Sver Pnyy} 90225 UVTUJNL 202/ZRQVPNY NYNEZ-CRAQNAG NYNEZ-HAXABJA SHEGURE",
        "PNYY:Sver Pnyy",
        "NQQE:90225 UVTUJNL 202",
        "VASB:ZRQVPNY NYNEZ-CRAQNAG NYNEZ-HAXABJA SHEGURE");

    qbGrfg("G87",
        "{Sver Pnyy} SBE 3521---PBAVSRE YA/BSS YRJVF NAQ PYNEX EQ/ECG BS N FGEHPGHER SVER-HAXA SHEGURE",
        "PNYY:Sver Pnyy",
        "NQQE:SBE 3521---PBAVSRE YA",
        "VASB:BSS YRJVF NAQ PYNEX EQ / ECG BS N FGEHPGHER SVER-HAXA SHEGURE");

    qbGrfg("G88",
        "{Sver Pnyy} 90225 UVTUJNL 202/RZRET ZRQVPNY ERFCBAFR TRARENY ZRQ NYREG",
        "PNYY:Sver Pnyy",
        "NQQE:90225 UVTUJNL 202",
        "VASB:RZRET ZRQVPNY ERFCBAFR TRARENY ZRQ NYREG");

    qbGrfg("G89",
        "{Sver Pnyy} 91085 UVTUJNL 202/RZRET ZRQVPNY ERFCBAFR SRZ CG UNIVAT N FGEBXR",
        "PNYY:Sver Pnyy",
        "NQQE:91085 UVTUJNL 202",
        "VASB:RZRET ZRQVPNY ERFCBAFR SRZ CG UNIVAT N FGEBXR");

    qbGrfg("G90",
        "{Sver Pnyy} 1744 SENAXYVA NIR/FGEHP SVER 1FG",
        "PNYY:Sver Pnyy",
        "NQQE:1744 SENAXYVA NIR",
        "VASB:FGEHP SVER 1FG");

    qbGrfg("G91",
        "{Sver Pnyy} 88590 UVTUJNL 202/ZBGBE IRU NPPVQRAG CBFF ZIN RNFG BS YBPNGVBA",
        "PNYY:Sver Pnyy",
        "NQQE:88590 UVTUJNL 202",
        "VASB:ZBGBE IRU NPPVQRAG CBFF ZIN RNFG BS YBPNGVBA");

    qbGrfg("G92",
        "{Sver Pnyy} 91085 UVTUJNL 202/RZRET ZRQVPNY ERFCBAFR/SRZNYR SNYYRA, QVSS OERNGUVAT",
        "PNYY:Sver Pnyy",
        "NQQE:91085 UVTUJNL 202",
        "VASB:RZRET ZRQVPNY ERFCBAFR / SRZNYR SNYYRA, QVSS OERNGUVAT");

    qbGrfg("G93",
        "{Sver Pnyy} 90653 UVTUJNL 202/ZBGBE IRU NPPVQRAG/2 IRU ZIN",
        "PNYY:Sver Pnyy",
        "NQQE:90653 UVTUJNL 202",
        "VASB:ZBGBE IRU NPPVQRAG / 2 IRU ZIN");

    qbGrfg("G94",
        "{Sver Pnyy} 419 TNGRJNL Nir/FGEHP SVER 1FG",
        "PNYY:Sver Pnyy",
        "NQQE:419 TNGRJNL Nir",
        "VASB:FGEHP SVER 1FG");

    qbGrfg("G95",
        "{Sver Pnyy} 638 NYNZRQN NIR NCG 11 (GUVF VF GUR PBASVEZRQ NQQERFF SEBZ 2522 BA FPRAR)YVTUG FZBXR/UNMR SEZ JVAQBJ",
        "PNYY:Sver Pnyy",
        "NQQE:638 NYNZRQN NIR",
        "NCG:11",
        "CYNPR:(GUVF VF GUR PBASVEZRQ NQQERFF SEBZ 2522 BA FPRAR)YVTUG FZBXR",
        "VASB:UNMR SEZ JVAQBJ");

    qbGrfg("G96",
        "{Sver Pnyy} SBE 3521 537 OBAQ FG/OYNPX FZBXR PBZVAT SEBZ ONFRZRAG-CBFF JNGRE URNGRE",
        "PNYY:Sver Pnyy",
        "NQQE:SBE 3521 537 OBAQ FG",
        "VASB:OYNPX FZBXR PBZVAT SEBZ ONFRZRAG-CBFF JNGRE URNGRE");

    qbGrfg("G97",
        "{Sver Pnyy} 89529 TERRA ZBHAGNVA EQ/SZ SNYYRA, VAWHERQ XARR. BA OYBBQ GUVAAREF, XARR VF PBAGVAHVAT GB OYRRQ",
        "PNYY:Sver Pnyy",
        "NQQE:89529 TERRA ZBHAGNVA EQ",
        "VASB:SZ SNYYRA, VAWHERQ XARR. BA OYBBQ GUVAAREF, XARR VF PBAGVAHVAT GB OYRRQ");

    qbGrfg("G98",
        "{Sver Pnyy} 87943 UVTUJNL 202/URNGUREF PBHAGL UNIRA-97 LB ZNYR-CBFF QON",
        "PNYY:Sver Pnyy",
        "NQQE:87943 UVTUJNL 202",
        "VASB:URNGUREF PBHAGL UNIRA-97 LB ZNYR-CBFF QON");

    qbGrfg("G99",
        "{Sver Pnyy} 91388 UNIRA IVRJ QE/GLCR 1 QVNORGVP, HAERFCBAFVIR, YBJ OYBBQ FHTNE",
        "PNYY:Sver Pnyy",
        "NQQE:91388 UNIRA IVRJ QE",
        "VASB:GLCR 1 QVNORGVP, HAERFCBAFVIR, YBJ OYBBQ FHTNE");

  }
 
  choyvp fgngvp ibvq znva(Fgevat[] netf) {
    arj BEPyngfbcPbhaglCnefreGrfg().trarengrGrfgf("G1");
  }
}